### ISSUE TITLE
[Bug] Problem installing newest version from repository.

### ISSUE THREAD

**Issue by galuszkak** [driftyco/ionic-cli#1005]
Thank You guys for awesome framework!
I'm not quite sure to which project I should report this bug. But I'm starting here as I'm trying to install ionic-cli ;). The reason that I'm trying install newest version from branch v2 is that there is fix for `ionic share` which now is broken and I couldn't share my project to other people.

```
$ npm install -g github:driftyco/ionic-cli#v2                                                                                                                                                       15:39:53  ☁  master ☂ ✭
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "github:driftyco/ionic-cli#v2"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.1
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/galuszkak/PycharmProjects/angularattack2016-adamite/npm-debug.log
npm ERR! code 1

```

**Comment by iignatov** [comment]
@galuszkak I guess that the problem is caused by **Node v6** which is not supported yet, see #960.

**Comment by galuszkak** [comment]
Thanks @iignatov . If so then I'm in favor of closing this.

**Comment by iantearle** [comment]
Would the same answer be for if node is outdated? 

```
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/local/lib
└── (empty)

npm WARN In ionic@2.0.0 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.0.0 replacing bundled version of ionic-app-lib with ionic-app-lib@2.0.0
npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/Users/iantearle/.nvm/versions/node/v0.12.7/bin/npm" "install" "-g" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v3.9.0
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed'
npm ERR! enoent ENOENT, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iantearle/Ionic/heritageApp/npm-debug.log
npm ERR! code 1
```

**Comment by iignatov** [comment]
@iantearle I'm not sure, but I would recommend you to upgrade to the latest Node v4 or v5 and then retry.

**Comment by tuongaz** [comment]
I had the same issue. The cli doesn't seem to work on the Node 6.x

**Comment by msegers** [comment]
So how does that work when angular recommends something after 5? I had issues with that, that's fixed already?

**Comment by teerasej** [comment]
I also found same problem with Ionic2 RC4 & Node 6.9.3. I can confirm that Ionic2 RC3 has no problem with this.

**Comment by JamesLeeTrigg** [comment]
I am having this problem too. 
`npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic" "cordova"
npm ERR! node v7.0.0
npm ERR! npm  v4.0.5
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jamestrigg/Dropbox/ThreeJS/npm-debug.log`

**Comment by jtushar53** [comment]
@JamesLeeTrigg , thanks working for me. Im on 6.9.1

**Comment by jacksonkr** [comment]
@JamesLeeTrigg I highly encourage you to not use `sudo` on your install. Why? Because it's a habit that will eventually, and ultimately, run you into permissions problems all over the place and once you get yourself into that position it's often "too late". For uninstalls it's not so bad, but for installs I recommend finding another way until you've exhausted your options.

**Comment by kleeb** [comment]
Tried ``npm install -g ionic`` without sudo on 3 Node's: node/5.8.0, node/6.2.1, node/7.0.0.
In all cases I'm getting this:

```
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
```

**Comment by akazmierczak** [comment]
I have the same error too.. 
I'm using Node Version: v6.0.0, and Ionic Framework Version: 2.0.0-rc.4

**Comment by kleeb** [comment]
just to confirm @JamesLeeTrigg , this helps:

```
npm uninstall -g ionic
npm install -g ionic
```
