### ISSUE TITLE
Cli arguments are not passed to cordova

### ISSUE THREAD

**Issue by jetwitaussi** [driftyco/ionic-cli#1014]
Ionic cli wraps cordova cli and removes its params before calling cordova, but the '--address' special case is not well handled, and when you have a ionic arg skipped, all next valid args are skipped too

you can add any params to cordova cli as you can use them in hooks

then:
```
ionic run --device --livereload --consolelogs --myparam
```
will launch 
```
cordova run --device
```
instead of
```
cordova run --device --myparam
```
i will provide a PR to fix that

**Comment by jthoms1** [comment]
I believe this has been fixed with the most recent refactor.
