### ISSUE TITLE
Updated the hooks directory to have execute permissions

### ISSUE THREAD

**Issue by iarsalanarain** [driftyco/ionic-cli#1017]
Ionic App is working very well but when i export android apk of ionic framework i got that of error ?

What is the problem ?

**Comment by jthoms1** [comment]
Could you provide details about your current setup?  Try running `ionic info` from within your project directory. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by varunendra-mishra** [comment]
same issue 
ionic info prints this:
Your system information:

Cordova CLI: Not installed
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 1.3.3
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v4.2.0

**Comment by MuhammadTahir92** [comment]
D:\projects\troutBird\ionic>ionic info
(node:8808) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Your system information:

Cordova CLI: 7.0.1
Ionic Version: 1.3.3
Ionic CLI Version: 1.4.0
Ionic App Lib Version: 0.0.16
OS: null
Node Version: v6.11.3

**Comment by dwieeb** [comment]
@MuhammadTahir92 You have the oldest Ionic CLI I've ever seen. Please update to the latest and then make a new issue and fill out the issue template, because that problem is not related to this issue.
