### ISSUE TITLE
Live mode not working on ios-cordova 4.0.1

### ISSUE THREAD

**Issue by asemoon** [driftyco/ionic-cli#1027]
Type: bug

Ionic CLI Version: 1.x

Platform: ios 9 browser (on iPad)

Hey Everyone,
ionic live mode does not seem to work from ios-cordova version 4.x on (when deployed to the device with no live mode, it works fine). The app gets stuck at loading with the following message from Safari:
```
An error occurred trying to load the resource.
```
Steps to reproduce:
```
1. download the ionic starter app for tabs and cd to the directory
ionic start myApp2 tabs
2. ionic platform remove ios
3. ionic platform add ios@4.0.1
4. cordova prepare
5. ionic run ios --device -l -c -s
```
the run log is available [here](http://pastebin.com/hvpTbzBY)
If ios-cordova version is kept at 3.8.0. The live mode works fine. 
Also deleting the app + reconnecting the iPad did not help resolving the issue.

ionic version : 1.7.15
cordova cli version: 6.2.0
ios-cordova version: 4.0.1
ios-deploy version: 1.8.6
ios-version : 9.3.2

PS: I don't know if this is helpful but on ios-cordova 3.8.0 I can kill the ios-deploy process and it actually terminates the app on the device, however, it does not terminate the app on ios-cordova 4.0.1. Maybe the root of the problem is because the app gets disconnected from the local web server?

**Comment by zmoshansky** [comment]
I'm also having a similar issue. It works up until `cordova-ios 3.9.2`. Ionic/Cordova also starts having issues with symlinks in my www/lib folder once upgrading into the 4.x branch.
