### ISSUE TITLE
ionic prepare ios not working

### ISSUE THREAD

**Issue by sfabriece** [driftyco/ionic-cli#1030]
Before updating to beta 28 I was able to run ```ionic prepare ios``` to update my xcode project.

What is the recommended way to refresh the app when running from xcode?

**Comment by jthoms1** [comment]
This is still a valid command.  There is a task for it but it appears that the cli is failing to find it.  I have identified the issue, have a fix, and I am now working on writing test cases.

In the meantime you should be able to run `cordova prepare ios`. Please let me know if this does not work for you.

**Comment by jthoms1** [comment]
This is fixed with commit 7ddd42e5536d915ef412db93c8d1a7c375d7a7e4. A new version of ionic was published to npm. ionic@2.0.0-beta.29

**Comment by sfabriece** [comment]
Thanks @jthoms1.

**Comment by bobvandevijver** [comment]
I noticed that when running the `prepare` command, the transpile/webpack etc actions are not run, while they are run with the `build` command. 

However, I want to build the app using Xcode, and when using the `build` command, ionic also builds the action application. Previously, the `prepare` command (at least in Ionic 1) took care of the steps required before the actual build, which is no longer the case. 

What can I do to solve this?
