### ISSUE TITLE
Can't generate splash screen either update icons and splash empty folders

### ISSUE THREAD

**Issue by tmpdirmk** [driftyco/ionic-cli#1031]
Hello, 

I'm a week trying to generate the icons and splash screen for ios.

I tried already generate on another computer, but appears in the log that is "generating" the files but to enter the directories there is no generated image.

What can I do? There is another alternative besides the ionic resources? I googled and saw that this bug is old, how to get around this?

I've used the flags: `--clean-cache`,` --force`.

When i delete folders of ios/android and try generate the log says "generating" but the folders are empty both android and ios.

**Comment by kamilbrk** [comment]
Same thing here. Both for new and cached resources, it does say that it's generating the files, but they are not saved.

<img width="149" alt="screen shot 2016-06-06 at 17 29 41" src="https://cloud.githubusercontent.com/assets/591349/15829603/5063eed8-2c0c-11e6-9bbd-fda3143653e9.png">

**Comment by teledemic** [comment]
I have found this to occur when your splash image is larger than 2208x2208.
Likely the same as #1045

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
