### ISSUE TITLE
ionic package ios error

### ISSUE THREAD

**Issue by hussaino** [driftyco/ionic-cli#1033]
I am trying to use the ionic platform to package and produce an ipa for ios.
I keep facing this error code that I have no clue what it's about:
error: Specified application doesn't exist or isn't a bundle directory : '/Users/package/workspace/apps-app_id-build#/cordova/platforms/ios/build/device/myapp'

P.S. I changed my app_id and build# above

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by yankustefan** [comment]
Hi 

I get the same error
`error: Specified application doesn't exist or isn't a bundle directory : '/Users/package/workspace/apps-cfaf6f09-127/cordova/platforms/ios/build/device/v2.app'`

`Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.4.5
`

**Comment by luckylooke** [comment]
Same error here
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3.1 Build version 8E1000a
