### ISSUE TITLE
ionic add ionic-platform-web-client error on ionic2 project

### ISSUE THREAD

**Issue by matsprea** [driftyco/ionic-cli#1037]
I would like to try the ionic platform with the ionic2 conference app but I've got an error

> $ git clone https://github.com/driftyco/ionic-conference-app.git
> Cloning into 'ionic-conference-app'...
> remote: Counting objects: 14187, done.
> remote: Compressing objects: 100% (104/104), done.
> remote: Total 14187 (delta 41), reused 0 (delta 0), pack-reused 14083
> Receiving objects: 100% (14187/14187), 30.99 MiB | 305.00 KiB/s, done.
> Resolving deltas: 100% (4313/4313), done.
> Checking connectivity... done.

> $ cd ionic-conference-app/
> $ ionic io init
> Initializing app with ionic.io....
> Saved app_id, writing to ionic.io.bundle.min.js...
> Saved api_key, writing to ionic.io.bundle.min.js...

> $ ionic add ionic-platform-web-client
> Caught exception:
>  TypeError: Cannot read property 'indexOf' of undefined
>     at Object.checkForBower (/usr/local/lib/node_modules/ionic/lib/utils/bower.js:52:20)
>     at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/add.js:48:14)
>     at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
>     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
>     at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:1304:14
>     at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Function.Module.runMain (module.js:577:11)
>     at startup (node.js:160:18) 
> 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues

system info

```
$ ionic info

Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.29
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v6.2.1


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
```

**Comment by fahimshekaib** [comment]
Same here..

**Comment by jthoms1** [comment]
Thanks for opening this issue! This will be resolved in the next release of Ionic CLI.  The release should occur in a few days. I am sorry for the inconvenience this might cause.
