### ISSUE TITLE
new error while building

### ISSUE THREAD

**Issue by petkoe** [driftyco/ionic-cli#1039]
Hello,

i am getting the following errors: 

The following build commands failed:
	Ld build/emulator/test.app/test normal i386

	GenerateDSYMFile build/emulator/test.app.dSYM build/emulator/test.app/test
(2 failures)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/pk/Documents/Daten/Privat/••Dev/Apps/test/platforms/ios/cordova/build-debug.xcconfig,-project,test.xcodeproj,ARCHS=i386,-target,test,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/pk/Documents/Daten/Privat/••Dev/Apps/test/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/pk/Documents/Daten/Privat/••Dev/Apps/test/platforms/ios/build/sharedpch

Caught exception:
 undefined 

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.7-201606031813
Ionic CLI Version: 2.0.0-beta.29
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.5 
ios-sim version: 5.0.7 
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

regards

Peter

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
