### ISSUE TITLE
ionic run -l changes config.xml style

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-cli#1047]
Cordova uses 4 spaces in config.xml, so when you run commands like `cordova plugin add --save` it formats config.xml to adhere that, but if you run `ionic run -l` it reformats config.xml to use 2 spaces.

If you're running both commands regularly it causes the config.xml style to flip flop annoyingly, so let's use the same formatting as Cordova.

**Comment by tlancina** [comment]
Just a quick update - not as straightforward as I'd hoped. We can change the indentation with:
```
var xmlBuilder = new xml2js.Builder({ 
  renderOpts: { 
    'pretty': true, 
    'indent': '    ',
    'newline': '\n'
  }
});
```

but there is another issue in that elementtree (what Cordova uses for xml stuff) appears to close tags with ` />` (space before) and xml2js uses `/>`, which still causes version control to flip flop and doesn't appear to be configurable in either lib.

**Comment by sryze** [comment]
Was this fixed at some point? I'm still seeing indentation changes after running some commands. 

Also there appears to be a bug with line endings handling where ionic would insert a lot of empty lines in the project description over time (I think this has something to do with LF vs. CRLF issue between macOS and Windows).

**Comment by aggarwalankush** [comment]
@jthoms1 running `ionic cordova run android` still reformats config.xml and package.json. Is there any solution for this as this issue is closed?

ionic info
```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.7.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

```

**Comment by dwieeb** [comment]
@aggarwalankush It's mostly Cordova: https://github.com/apache/cordova-lib/pull/558
