### ISSUE TITLE
Failed to add to body class: platform-android

### ISSUE THREAD

**Issue by 05bca054** [driftyco/ionic-cli#1048]
Running 'build:before' gulp task before build
[11:23:26] Starting 'clean'...
[11:23:26] Finished 'clean' after 48 ms
[11:23:26] Starting 'build'...
[11:23:26] Starting 'sass'...
[11:23:26] Starting 'html'...
[11:23:26] Starting 'fonts'...
[11:23:26] Starting 'scripts'...
[11:23:26] Finished 'html' after 49 ms
[11:23:26] Finished 'scripts' after 48 ms
[11:23:26] Finished 'fonts' after 54 ms
[11:23:27] Finished 'sass' after 1.01 s
[11:23:33] Finished 'build' after 7.2 s
[11:23:33] Starting 'build:before'...
[11:23:33] Finished 'build:before' after 8.49 μs

Running command: /home/naitik/Desktop/proximiio/IdentifyMe/hooks/after_prepare/010_add_platform_class.js /home/naitik/Desktop/proximiio/IdentifyMe

add to body class: platform-android

Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Both above path(ANDROID_HOME) is set and works perfectly fine.

**Comment by vuhung3990** [comment]
add ANDROID_HOME path before deploy on android

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by 05bca054** [comment]
It's permission issue to .cordova and .config folder under users in ubuntu.

It was fixed once given proper permission.

-Thanks

**Comment by telcro** [comment]
i am getting this error while buliding a andriod app 

add to body class: platform-android

ANDROID_HOME=C:\Android_SDK

JAVA_HOME=C:\Program Files\Java\jdk1.8.0_111

Subproject Path: CordovaLib

Downloading http://services.gradle.org/distributions/gradle-2.14.1-all.zip


my path is 

C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_111;C:\Android_SDK;C:\Android_SDK\tools;C:\Android_SDK\platform-tools;C:\Program Files (x86)\Skype\Phone\;%ANDRIOD_HOME%\platform-tools;%ANDRIOD_HOME%\build-tools


please Help me with the Solution 

THanx in Advance

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.
