### ISSUE TITLE
"Error Logging in", Ionic login issue using CLI

### ISSUE THREAD

**Issue by nickkenens** [driftyco/ionic-cli#1049]
Whenever I try to login using the CLI, I get this error: `Error logging in`.

I've tried changing my password, making another account, updating ionic & ionic-cli, etc...

This seems to be a consistent & serious issue in Ionic.

Is there any other alternative to upload your app for testing on Ionic View for now?

**Comment by damienstanton** [comment]
I am also having this issue with `2.0.0-beta.30`.

Here is what is happening:
```sh
dev   ✎ ionic login
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: email@myemail.com
Password:
Error logging in
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by TestAccount9691** [comment]
Hi 
I m also facing the same issue.

```
Error logging in
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by jthoms1** [comment]
commit 2379b41cd93dd43441364ac88e587e9552924a0c

Thank you for helping identify this issue!  I have resolved the problem and it will be fixed in the next CLI release which should be pushed in the next day or two.  Thanks for being patient, and I apologize for any inconvenience this might have caused.

In the mean time you are likely see this error because of an incorrect username or password.  You should try logging into the website to verify your information. https://apps.ionic.io/login

**Comment by TestAccount9691** [comment]
Hi @jthoms1 

Let us know when next CLI release is pushed.

Thanks

**Comment by nickkenens** [comment]
Thanks for the rapid feedback @jthoms1, appreciate the effort! ;)

**Comment by jthoms1** [comment]
I just published a release. beta.31 Is now available so please update.  Thanks!

**Comment by b3h3rkz** [comment]
I just had the same problem, running updates and installing different versions of ionic didn't work.
Only worked when I used a VPN.
