### ISSUE TITLE
run add platform android

### ISSUE THREAD

**Issue by emoryr** [driftyco/ionic-cli#1052]
I got this error:

Caught exception:
 TypeError: Cannot read property 'indexOf' of undefined
    at Object.checkForBower (/home/emory/node-v5.6.0-linux-x86/lib/node_modules/ionic/lib/utils/bower.js:52:20)
    at Object.run (/home/emory/node-v5.6.0-linux-x86/lib/node_modules/ionic/lib/ionic/add.js:48:14)
    at Promise.apply (/home/emory/node-v5.6.0-linux-x86/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/home/emory/node-v5.6.0-linux-x86/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /home/emory/node-v5.6.0-linux-x86/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/home/emory/node-v5.6.0-linux-x86/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by emoryr** [comment]
Sure, anything.

Your system information:

Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.29
Ionic App Lib Version: 2.0.0-beta.16
OS: Distributor ID:	Ubuntu Description:	Ubuntu 16.04 LTS 
Node Version: v5.6.0

I would like to report that I am using _ionic build android_ and it is working fine.

**Comment by jthoms1** [comment]
Please update to beta.30. The issue has been resolved in commit 53bcbbbdb902616121bacafd08396b8245dd2f60.

**Comment by teach2educate** [comment]
Hi,

I am facing an issue even after updating to latest version of ionic

C:\Users\Ravi\Desktop\ionic\teacher_view>ionic platform add android
Error: Platform android already added.


Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


C:\Users\Ravi\Desktop\ionic\teacher_view>ionic run android

Running 'run:before' gulp task before run
[14:41:31] Starting 'clean'...
[14:41:31] Finished 'clean' after 46 ms
[14:41:31] Starting 'build'...
[14:41:31] Starting 'sass'...
[14:41:31] Starting 'html'...
[14:41:31] Starting 'fonts'...
[14:41:31] Starting 'scripts'...
[14:41:32] Finished 'scripts' after 107 ms
[14:41:32] Finished 'html' after 114 ms
[14:41:32] Finished 'fonts' after 124 ms
[14:41:33] Finished 'sass' after 1.11 s
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(22,55): Error TS2339: Property 'description' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(23,55): Error TS2339: Property 'max_response_duration_min' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(24,55): Error TS2339: Property 'assigned_on' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(25,55): Error TS2339: Property 'soft_deadline_due' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(26,55): Error TS2339: Property 'hard_deadline_due' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(27,45): Error TS2339: Property 'responses' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(28,55): Error TS2339: Property 'responses' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/class-group/class-group.ts(24,38): Error TS2339: Property 'chapters' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/teacher-home/teacher-home.ts(19,35): Error TS2339: Property 'class_subject' does not exist on type '{}'.
[14:41:47] Finished 'build' after 15 s
[14:41:47] Starting 'run:before'...
[14:41:47] Finished 'run:before' after 11 μs

Running command: "C:\Program Files\nodejs\node.exe" C:\Users\Ravi\Desktop\ionic\teacher_view\hooks\after_prepare\010_add_platform_class.js C:\Users\Ravi\Desktop\ionic\teacher_view


add to body class: platform-android

Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.


Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


C:\Users\Ravi\Desktop\ionic\teacher_view>echo %ANDROID_HOME%
C:\Users\Ravi\AppData\Local\Android\sdk

C:\Users\Ravi\Desktop\ionic\teacher_view>ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v5.10.1



C:\Users\Ravi\Desktop\ionic\teacher_view>
