### ISSUE TITLE
You must have bower installed to continue.

### ISSUE THREAD

**Issue by matsprea** [driftyco/ionic-cli#1053]
I would like to try the the new beta8, so I cloned the [ionic-conference-app](https://github.com/driftyco/ionic-conference-app) and I did a `npm install` and I tried to add the ionic-platform-web-client but I've got this message:

```
PS C:\Projects\ionic-conference-app> ionic add ionic-platform-web-client
(node:12000) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please u
pdate it to a more recent version.

You must have bower installed to continue.
Type `npm install -g bower` (CLI v2.0.0-beta.30)

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v6.2.0
```

Sadly bower is already installed :(
```

PS C:\Projects\ionic-conference-app> npm install -g bower
C:\Users\Matteo Spreafico\AppData\Roaming\npm\bower -> C:\Users\Matteo Spreafico\AppData\Roaming\npm\node_modules\bower\
bin\bower
C:\Users\Matteo Spreafico\AppData\Roaming\npm
`-- bower@1.7.9

PS C:\Projects\ionic-conference-app> ionic add ionic-platform-web-client
(node:13460) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please u
pdate it to a more recent version.

You must have bower installed to continue.
Type `npm install -g bower` (CLI v2.0.0-beta.30)

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS:
Node Version: v6.2.0


```

**Comment by duduBaiao** [comment]
The same here:

ionic add platform android --verbose

Task: title=add, name=add, summary=Add an Ion, bower component, or addon to the project, [name]=The name of the ion, bower component, or addon you wish to install, isProjectTask=true, run=function run(ionic, argv) {

  if (!bower.checkForBower()) {
    appLibUtils.fail(bower.installMessage, 'add');
    return;
  }

  var componentName = argv._[1];
  var ioSet = false;

  try {
    ioSet = true;
    installBowerComponent(componentName);
  } catch (error) {
    var errorMessage = error.message ? error.message : error;
    appLibUtils.fail(errorMessage, 'service');
  }

  // Inject the component into our index.html, if necessary, and save the app_id
  ioLib.injectIoComponent(ioSet, componentName);
  ioLib.warnMissingData();
}
Looking up Ionic root, cwd: /Users/dudu/Documents/Desenvolvimento/IonicApps/MyFirstApp
Ionic root directory:  /Users/dudu/Documents/Desenvolvimento/IonicApps/MyFirstApp
Gulpfile found
Utils.fail You must have bower installed to continue. 
Type `npm install -g bower` add
Utils.fail stack undefined
Utils.errorHandler is set, calling that now
Cli.Utils.errorHandler msg You must have bower installed to continue. 
Type `npm install -g bower` string

You must have bower installed to continue. 
Type `npm install -g bower` (CLI v2.0.0-beta.30)

Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.3.1 Build version 7D1014 



bower --version
1.7.9

**Comment by Zorgatone** [comment]
Same issue for me!

**Comment by Zorgatone** [comment]
@duduBaiao you're using a wrong command by the way...

It should be `ionic platform add android` and NOT `ionic add platform android` (platform is before add)

**Comment by Zorgatone** [comment]
@matsprea: when you find this issue you can simply add that library using normal bower commands:

`bower install --save ionic-platform-web-client`

**Comment by duduBaiao** [comment]
Hi guys! The solution is simple.

I have just typed:

`cordova telemetry on`

After that, Ionic was able to detect Cordova version.

**Comment by jthoms1** [comment]
commit 9de215758874c856d3220c924e908c10b94e322e.

Thank you for helping identify this issue!  I have resolved the problem and it will be fixed in the next CLI release which should be pushed in the next day or two.  Thanks for being patient, and I apologize for any inconvenience this might have caused.

**Comment by jthoms1** [comment]
I just published beta.31.  Please update. Thanks!

**Comment by matsprea** [comment]
I've got a different error, but it's not working for me (on the vanilla ionic-conference-app)

```
PS D:\Progetti\ionic-conference-app>  ionic add ionic-platform-web-client --verbose
Task: title=add, name=add, summary=Add an Ion, bower component, or addon to the project, [name]=The name of the ion, bow
er component, or addon you wish to install, isProjectTask=true, run=function run(ionic, argv) {

  // This command will be deprecated in the future.
  var deprecationMsg = 'This command has been ' + 'deprecate'.red + '.  All ' +
   'resources are currently available in NPM and we recommend that you use NPM to manage these.\n' +
   'More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower\n';
  log.info(deprecationMsg.bold);

  if (!bower.checkForBower()) {
    appLibUtils.fail(bower.installMessage, 'add');
    return;
  }

  var componentName = argv._[1];
  var ioSet = false;

  try {
    ioSet = true;
    installBowerComponent(componentName);
  } catch (error) {
    var errorMessage = error.message ? error.message : error;
    appLibUtils.fail(errorMessage, 'service');
  }

  // Inject the component into our index.html, if necessary, and save the app_id
  ioLib.injectIoComponent(ioSet, componentName);
  ioLib.warnMissingData();
}
Looking up Ionic root, cwd: D:\Progetti\ionic-conference-app
Ionic root directory:  D:\Progetti\ionic-conference-app
(node:7240) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please up
date it to a more recent version.
Gulpfile found
This command has been deprecate.  All resources are currently available in NPM and we recommend that you use NPM to mana
ge these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower

Utils.fail Bower error, check that "undefined" exists,
or try running "undefined" for more info. add
Utils.fail stack undefined
Utils.errorHandler is set, calling that now
Cli.appLibUtils.errorHandler msg Bower error, check that "undefined" exists,
or try running "undefined" for more info. string

Bower error, check that "undefined" exists,
or try running "undefined" for more info. (CLI v2.0.0-beta.31)

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v6.2.0
 
```

**Comment by matsprea** [comment]
Thanks @Zorgatone your workaroud works!

**Comment by SanjayYadav90** [comment]
hi all,
@Zorgatone you are right- 
I have used wrong command as-

`- ionic platform add android `

`-  ionic add platform android`
 it work for me.
thanks
