### ISSUE TITLE
Failed to install ionic-platform-web-client

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1055]
_From @zh-wowtv on June 8, 2016 10:9_

I followed the ionic.io document and tried to install ionic-platform-web-client by:

> ionic add ionic-platform-web-client

But failed with the following error message:

```
You must have bower installed to continue. 
Type `npm install -g bower` (CLI v2.0.0-beta.30)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.7.1
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

What could be the reason? Any suggestion? Thanks.

_Copied from original issue: driftyco/ionic#6801_

**Comment by jgw96** [comment]
_From @wb9688 on June 8, 2016 13:1_

Have you installed bower as the error message suggests?

**Comment by jgw96** [comment]
_From @zh-wowtv on June 8, 2016 13:52_

Of course， I installed bower. My bower version is 1.7.9.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by jgw96** [comment]
_From @wb9688 on June 8, 2016 16:18_

@jgw96 It's a bug. Create a v1 project with the v2 cli and try adding a plugin (eg. `ionicdatepicker` or the `ionic-platform-web-client` mentioned by @zh-wowtv) and it will fail with that error message  even if you've install `bower`...

**Comment by jgw96** [comment]
Ahh ok, thanks for clearing this up @wb9688 . I will be moving this issue to the ionic-cli repo as this issue is related to the ionic cli and not the ionic framework.

**Comment by adriantombu** [comment]
Same problem here. Just to be sure, I tried to uninstall and reinstall bower but no changes.

```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.2.1
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by zh-wowtv** [comment]
As @jgw96 mentioned, it's a bug in ionic@beta. I resolved the issue by installing ionic 1.

**Comment by fakharkhan** [comment]
Still facing the issue while installing "ionic add ionic-platform-web-client"
Respond with following issue:
You must have bower installed to continue. 
Type `npm install -g bower` (CLI v2.0.0-beta.30)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.1.1 Build version 7B1005 

**I have already installed bower**

**Comment by jthoms1** [comment]
commit 9de215758874c856d3220c924e908c10b94e322e.

Thank you for helping identify this issue!  I have resolved the problem and it will be fixed in the next CLI release which should be pushed in the next day or two.  Thanks for being patient, and I apologize for any inconvenience this might have caused.
