### ISSUE TITLE
Change JS flag to --js

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#1057]
Instead of `--no-ts` for starting a JavaScript version, let's change it to `--js`.

**Comment by jthoms1** [comment]
This flag was removed in favor of all v2 projects being TypeScript. Please reference commit 3f87bfb09e37214301c27863c53bb7a9cabdf555.

**Comment by khamaileon** [comment]
Please update [http://ionicframework.com/docs/v2/getting-started/tutorial/](documentation).

> Want to use JavaScript instead? Pass the **--no-ts** flag and get a project set up for JavaScript instead.

**Comment by Herb-sh** [comment]
If I am not mistaken there is no way to start sample app in JavaScript?!  (https://github.com/driftyco/ionic-cli/commit/3f87bfb09e37214301c27863c53bb7a9cabdf555#diff-26488b21857121cfbc2862f3af3b0a3cL51)

**Comment by jthoms1** [comment]
This is correct.  Ionic2 applications are only available as Typescript.

**Comment by diosney** [comment]
That's really bad for us :( I really like ECMAScript 6 instead of Typescript, I even have to migrate all my `beta.25` code to typescript. I feel really bad for this :(

**Comment by delijati** [comment]
If i have dependencies which don't have a TS definition file i have to stick with ``ionic < 2```?
