### ISSUE TITLE
Node Hanging on ionic Account login

### ISSUE THREAD

**Issue by KaraAJC** [driftyco/ionic-cli#1064]
I am attempting to upload my ionic app to ionic.io and upon using ``ionic upload`` it lets me know ``no previous login existed. Attempting to log in now`` then asks me for Email and Password. But after submitting the password, the terminal does nothing. I see it's running node from the terminal bar, but it is not doing anything. 

I'm using Ionic 1.7.4 and I've been able to set the id of the app, run ionic serve, etc. Not getting any errors. 

I've also tried doing ionic login, ionic io, and ionic upload with -email and -password in one line, all of which are hanging after password is entered. 

My credentials work on the apps.ionic.io site. 

Halp? 

``
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Version: 1.3.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Mavericks
Node Version: v4.2.4
Xcode version: Xcode 6.2 Build version 6C131e ``

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jthoms1** [comment]
This was just fixed with release of beta.31. Commit 2379b41cd93dd43441364ac88e587e9552924a0c fixes this issue and should allow you to see more information. Please reopen if the issue still occurs. Thanks!
