### ISSUE TITLE
ionic platform add ios  -->  "Caught exception: undefined"

### ISSUE THREAD

**Issue by vk2sky** [driftyco/ionic-cli#1081]
Verbose output is as follows:

Task: title=platform, name=platform, summary=Add platform target for building an Ionic app, [options]=, <PLATFORM>=, title=Do not add default Ionic icons and splash screen resources, boolean=true, title=Do not save the platform to the package.json file, boolean=true, isProjectTask=true, run=function run(ionic, argv, rawCliArguments) {
  var appDirectory = process.cwd();
  var cmdName = process.argv[2].toLowerCase();
  var rawArgs = rawCliArguments.slice(0);
  var argumentName = argv._[2];

  var isAddCmd = argv._.indexOf('add') !== -1;
  var isRmCmd = argv._.indexOf('rm') !== -1 || argv._.indexOf('remove') !== -1;
  var addResources = isAddCmd &&  !(argv.noresources || argv.r);

  // ensure the content node was set back to its original
  return ConfigXml.setConfigXml(appDirectory, {
    resetContent: true,
    errorWhenNotFound: false
  })
  .then(function() {
    if (addResources) {
      return IonicResources.copyIconFilesIntoResources(appDirectory)
        .then(function() {
          return IonicResources.addIonicIcons(appDirectory, argumentName);
        });
    }
  })
  .then(function() {
    var optionList = cordovaUtils.filterArgumentsForCordova(cmdName, argv, rawArgs);
    return cordovaUtils.execCordovaCommand(optionList);
  })
  .then(function(runCode) {

    // We dont want to do anything if the cordova command failed
    if (runCode !== 0 || argv.nosave) {
      return;
    }

    if (isAddCmd) {
      log.info('Saving platform to package.json file');
      return State.savePlatform(appDirectory, argumentName);
    }
    if (isRmCmd) {
      log.info('Removing platform from package.json file');
      return State.removePlatform(appDirectory, argumentName);
    }
  });
}
Looking up Ionic root, cwd: /Users/richardmurnane/WebstormProjects/temp/ionic/Ionic 2/Building Mobile Apps with Ionic 2/quicklists
Ionic root directory:  /Users/richardmurnane/WebstormProjects/temp/ionic/Ionic 2/Building Mobile Apps with Ionic 2/quicklists
Gulpfile found
ConfigXml.setConfigXml /Users/richardmurnane/WebstormProjects/temp/ionic/Ionic 2/Building Mobile Apps with Ionic 2/quicklists resetContent=true, errorWhenNotFound=false
Executing cordova cli: platform add ios --verbose
No scripts found for hook "before_platform_add".

No version supplied. Retrieving version from config.xml...

Error: CordovaError: Platform ios already added.
    at /Users/richardmurnane/.nvm/versions/node/v5.5.0/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform.js:130:31
    at _fulfilled (/Users/richardmurnane/.nvm/versions/node/v5.5.0/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/richardmurnane/.nvm/versions/node/v5.5.0/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/richardmurnane/.nvm/versions/node/v5.5.0/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/richardmurnane/.nvm/versions/node/v5.5.0/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/Users/richardmurnane/.nvm/versions/node/v5.5.0/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

-------------------------------------------------------------------------------------------------------------------
ionic info gives the following:

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
