### ISSUE TITLE
ionic run android throws error "Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by kamlmish** [driftyco/ionic-cli#1082]
D:\Trivia\trivia>ionic run android
 You're trying to build for androidbut don't have the platform installed yet.
? Installing android for you.
√ Installed platform android
Running command: "C:\Program Files\nodejs\node.exe" D:\Trivia\trivia\hooks\after
_prepare\010_add_platform_class.js D:\Trivia\trivia

add to body class: platform-android

Error: Path must be a string. Received undefined

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post the output of ionic info here please? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by johnlowvale** [comment]
i'm getting the same error, my ionic info:

Your system information:

Cordova CLI: 6.3.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v5.9.1

**Comment by johnlowvale** [comment]
beside the error "Error: Path must be a string. Received undefined", i wonder why OS name is blank too (im using windows 10)

**Comment by johnlowvale** [comment]
i found out why, i have to set ANDROID_HOME environment variable, 

but this matter is described in Apache Cordova Project, not in Ionic Project

**Comment by vegardlarsen** [comment]
I encountered this while doing `ionic build android` under TeamCity. In that case it was because I was missing the `HOME` environment variable, and it couldn't find `.ionic/ionic.config`.

**Comment by fgagneten** [comment]
Works for me doing:
Removing "platforms" and "plugins" folder in the file system. Then:
cordova platform rm android
cordova platform add android
