### ISSUE TITLE
unable to build for android

### ISSUE THREAD

**Issue by raviraju** [driftyco/ionic-cli#1085]
C:\Users\Ravi\Desktop\ionic\teacher_view>ionic platform add android
Error: Platform android already added.

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

C:\Users\Ravi\Desktop\ionic\teacher_view>ionic run android

Running 'run:before' gulp task before run
[14:41:31] Starting 'clean'...
[14:41:31] Finished 'clean' after 46 ms
[14:41:31] Starting 'build'...
[14:41:31] Starting 'sass'...
[14:41:31] Starting 'html'...
[14:41:31] Starting 'fonts'...
[14:41:31] Starting 'scripts'...
[14:41:32] Finished 'scripts' after 107 ms
[14:41:32] Finished 'html' after 114 ms
[14:41:32] Finished 'fonts' after 124 ms
[14:41:33] Finished 'sass' after 1.11 s
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(22,55): Error TS2339: Property 'description' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(23,55): Error TS2339: Property 'max_response_duration_min' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(24,55): Error TS2339: Property 'assigned_on' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(25,55): Error TS2339: Property 'soft_deadline_due' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(26,55): Error TS2339: Property 'hard_deadline_due' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(27,45): Error TS2339: Property 'responses' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/assignment-page/assignment-page.ts(28,55): Error TS2339: Property 'responses' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/class-group/class-group.ts(24,38): Error TS2339: Property 'chapters' does not exist on type '{}'.
TypeScript error: C:/Users/Ravi/Desktop/ionic/teacher_view/app/pages/teacher-home/teacher-home.ts(19,35): Error TS2339: Property 'class_subject' does not exist on type '{}'.
[14:41:47] Finished 'build' after 15 s
[14:41:47] Starting 'run:before'...
[14:41:47] Finished 'run:before' after 11 μs

Running command: "C:\Program Files\nodejs\node.exe" C:\Users\Ravi\Desktop\ionic\teacher_view\hooks\after_prepare\010_add_platform_class.js C:\Users\Ravi\Desktop\ionic\teacher_view

add to body class: platform-android

Error: Android SDK not found. Make sure that it is installed. If it is not at the default location, set the ANDROID_HOME environment variable.

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

C:\Users\Ravi\Desktop\ionic\teacher_view>echo %ANDROID_HOME%
C:\Users\Ravi\AppData\Local\Android\sdk

C:\Users\Ravi\Desktop\ionic\teacher_view>ionic info

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.31
Ionic App Lib Version: 2.0.0-beta.17
OS:
Node Version: v5.10.1

C:\Users\Ravi\Desktop\ionic\teacher_view>

**Comment by codelero** [comment]
Similar issue on OSX when running ionic build android. 

I've built without issue using version 1.3 in the past. It also fails when trying to emulate on ios/android

Cordova CLI: 5.2.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 5.0.1 
OS: Mac OS X Yosemite
Node Version: v4.4.5
Xcode version: Xcode 6.1.1 Build version 6A2008a 

Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:362:9)
    at Object.exports.spawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:108:31)
    at runScriptViaChildProcessSpawn (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:23)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
