### ISSUE TITLE
`ionic start` download ionic-app-base every time

### ISSUE THREAD

**Issue by panlina** [driftyco/ionic-cli#1087]
Every time I run `ionic start`, it downloads `ionic-app-base` from the internet, no matter it's a blank or boilerplate project.
Can't it just cache the package? It's annoying to wait every time I create a project.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! This is actually the expected behavior as the `app-base` contains our base packages that have to be installed for each project. Thanks for using Ionic!
