### ISSUE TITLE
Adding gulpStartupTasks to ionic.project causes ionic serve to error on 1.2.5

### ISSUE THREAD

**Issue by boardman** [driftyco/ionic-cli#110]
Adding gulpStartupTasks parameter in ionic.project causes ionic serve to fail with the following error.

```
Rogers-MacBook-Pro:tester roger$ ionic serve
Gulp startup tasks: [ 'sass', 'watch' ]
Running dev server: http://172.17.10.222:8100
Running live reload server: http://172.17.10.222:35729
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

My ionic.project file is as follows

```javascript
{
  "name": "Tester",
  "app_id": "com.bxthree.tester",
  "gulpStartupTasks": ["sass", "watch"]
}
```

This doesn't seem to be related to the tasks specified within gulpStartupTasks.  All tasks specified within this parameter can be run directly via Gulp without issue.  Specifying an empty array for gulpStartupTasks also causes the error.

```javascript
{
  "name": "Tester",
  "app_id": "com.bxthree.tester",
  "gulpStartupTasks": []
}
```

Removing gulpStartupTasks from ionic.project allows ionic serve to one again function normally.

Thanks

**Comment by jbavari** [comment]
@depsypher - I've updated the CLI to run a few checks:

If the user has `gulpStartupTasks` specified, but does not have gulp installed globally, they shall be shown a message to do so.

I hope this resolves the issue you have had. This should ship in 1.3.1.
