### ISSUE TITLE
Ionic browser command is not recognized in latest CLI version.

### ISSUE THREAD

**Issue by Sobiru** [driftyco/ionic-cli#1100]
Hello,

I've updated my Ionic CLI to the latest version (2.0.0-beta.31). Then I tried to add crosswalk to my Ionic project with this command: 
`ionic browser add crosswalk`

This is the error I'm getting : 

```
$ ionic browser add crosswalk
  _             _
 (_)           (_)
  _  ___  _ __  _  ___
 | |/ _ \| '_ \| |/ __|
 | | (_) | | | | | (__
 |_|\___/|_| |_|_|\___|  CLI v2.0.0-beta.31

Usage: ionic task args


=======================
browser is not a valid task


Available tasks:
(use --help or -h for more info)


   start  ..........  Starts a new Ionic project in the specified PATH
   serve  ..........  Start a local development server for app dev/testing
   generate  .......  Generate pages and components
   platform  .......  Add platform target for building an Ionic app
   run  ............  Run an Ionic project on a connected device
   emulate  ........  Emulate an Ionic project on a simulator or emulator
   build  ..........  Build (prepare + compile) an Ionic project for a given platform.

   plugin  .........  Add a Cordova plugin
   resources  ......  Automatically create icon and splash screen resources (beta)
                      Put your images in the ./resources directory, named splash or icon.
                      Accepted file types are .png, .ai, and .psd.
                      Icons should be 192x192 px without rounded corners.
                      Splashscreens should be 2208x2208 px, with the image centered in the middle.

   upload  .........  Upload an app to your Ionic account
   share  ..........  Share an app with a client, co-worker, friend, or customer
   lib  ............  Gets Ionic library version or updates the Ionic library
   io  .............  Integrate your app with the ionic.io platform services (alpha)
   security  .......  Store your app's credentials for the Ionic Platform (alpha)
   push  ...........  Upload APNS and GCM credentials to Ionic Push (alpha)
   package  ........  Use Ionic Package to build your app (alpha)
   config  .........  Set configuration variables for your ionic app (alpha)
   service  ........  Add an Ionic service package and install any required plugins
   add  ............  Add an Ion, bower component, or addon to the project
   remove  .........  Remove an Ion, bower component, or addon from the project
   list  ...........  List Ions, bower components, or addons in the project
   info  ...........  List information about the users runtime environment
   help  ...........  Provides help for a certain command
   link  ...........  Sets your Ionic App ID for your project
   hooks  ..........  Manage your Ionic Cordova hooks
   state  ..........  Saves or restores state of your Ionic Application using the package.json file
   docs  ...........  Opens up the documentation for Ionic
```
It appears that `ionic browser` is no longer a valid command. How can I add crosswalk then?

**Comment by flobacher** [comment]
The browser command is deprecated in favor of using the
Cordova Crosswalk plugin, as stated in https://github.com/driftyco/ionic-cli/commit/96b79ec61f7007d03f28a916ce201dd0fa22dc2c
It should still be there in beta.30. Try `ionic plugin add cordova-crosswalk-webview`. Please let me know if it works for you. I am just getting started with this as well..

**Comment by vgarzom** [comment]
Thanks for helping, actually de command is `ionic plugin add cordova-plugin-crosswalk-webview`

**Comment by jthoms1** [comment]
Looks like the correct command has been provided in a comment. Thanks @vgarzom and @flobacher.

**Comment by infinnie** [comment]
@flobacher HTTP 404…
Help me.

**Comment by ParsaAkbari** [comment]
So how do we perform the ionic browser list and ionic browser add commands which are used in ionic 1 to configure crosswalk?

**Comment by kumbhanialex111** [comment]
i got Error 
D:\Ionic\my_app>ionic plugin add cordova-crosswalk-webview
Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-crosswalk-webview

**Comment by localpcguy** [comment]
For future visitors to this page, the necessary command (as of the date of this comment) is

`ionic plugin add cordova-plugin-crosswalk-webview`

**Comment by giuzero** [comment]
when I run ionic plugin add cordova-plugin-crosswalk-webview I get
 Could not resolve org.xwalk:xwalk_core_library:22+.
This
https://repo1.maven.org/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml give a 404.

What should I do?

**Comment by shanesmith** [comment]
@jthoms1 The confusion might stem from the browser command still being mentioned in the docs here: http://ionicframework.com/docs/cli/browsers.html

**Comment by cgsmith** [comment]
@shanesmith I created #1685 to address that. I just ran into the same issue and stumbled onto this page.

**Comment by sharansp** [comment]
whats the command in ionic 3?

**Comment by hacklock** [comment]
whats the command in ionic 3?

**Comment by dwieeb** [comment]
`ionic cordova plugin add cordova-plugin-crosswalk-webview`
