### ISSUE TITLE
"ionic run" shortcut... 

### ISSUE THREAD

**Issue by furnaceX** [driftyco/ionic-cli#1109]
I used to be able to just do an "ionic run" without listing the platform.  And since I only have android platform installed, it would just figure it out and launch.  But now gives an error.  Very very minor, I know! 

the error message is very cryptic (`Caught exception: undefined`), which took a while for me to figure out what was wrong.

I also get this "graceful-fs module"  reminder.  But doesn't seem to have an impact.

```
(node:10104) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Running 'run:before' gulp task before run
[14:28:27] Starting 'clean'...
[14:28:27] Finished 'clean' after 68 ms
[14:28:27] Starting 'build'...
[14:28:27] Starting 'sass'...
[14:28:27] Starting 'html'...
[14:28:27] Starting 'fonts'...
[14:28:27] Starting 'scripts'...
[14:28:27] Finished 'html' after 222 ms
[14:28:28] Finished 'scripts' after 358 ms
[14:28:28] Finished 'fonts' after 449 ms
[14:28:31] Finished 'sass' after 3.47 s
[14:28:47] Finished 'build' after 20 s
[14:28:47] Starting 'run:before'...
[14:28:47] Finished 'run:before' after 16 µs

Caught exception:
 undefined
```

```
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Windows 7 SP1
Node Version: v6.2.0
```

**Comment by jthoms1** [comment]
Thanks for reporting this.  I believe it currently defaults to iOS. I will look into fixing the error message as well as providing messaging to users to let them know that it is defaulting to iOS when the command is executed without a platform provided.

**Comment by jthoms1** [comment]
Thank you for helping identify this issue!  I have resolved the problem and it will be fixed in the next CLI release which should be pushed in the next day or two.  Thanks for being patient, and I apologize for any inconvenience this might have caused.
