### ISSUE TITLE
[beta 32] Error Initializing app

### ISSUE THREAD

**Issue by manekinekko** [driftyco/ionic-cli#1114]
The installation process in beta 32 seems to be broken.

`Error Initializing app: There was an error with the spawned command: npminstall`

![image](https://cloud.githubusercontent.com/assets/1699357/16364907/34386734-3bf2-11e6-8ff6-f6f0f99706be.png)

**Comment by sasharevzin** [comment]
@manekinekko https://github.com/driftyco/ionic-cli/issues/1089

**Comment by jthoms1** [comment]
Closing this as a duplicate of #1013.
