### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by mrpsweet** [driftyco/ionic-cli#1116]
When i update my ionic ,i use the cmd `ionic serve` so the error show |

the  ·http://localhost:8100/build/js/app.bundle.js·  server responded with a status of 404 (Not Found)

**Comment by ViolaMa** [comment]
I have the same problems with you, I deleted the build fold in www , and clean up the npm cache,then it works. Maybe you can have a try.

**Comment by mrpsweet** [comment]
thank you , i try it .And it work
