### ISSUE TITLE
Deprecated ionic commands.

### ISSUE THREAD

**Issue by Skryabind** [driftyco/ionic-cli#1118]
I have a problem with installing ionic plugins:

```
# ionic add ionic-platform-web-client
This command has been deprecate.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower


Bower error, check that "undefined" exists,
or try running "undefined" for more info. (CLI v2.0.0-beta.32)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9-201606241930
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

Also I can't  update ionic libs, I get the same error:
```
ionic lib update
This command has been deprecate.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower

Unable to load ionic lib version information
Are you sure you want to replace /Users/dimon/Projects/one-place/planistic/www/lib/ionic with an updated version of Ionic?
(yes/no): yes
Invalid version: undefined
```

What should I do? Maybe, update some module? 
Thanks.

**Comment by lthh89vt** [comment]
@Skryabind I'm having the same issue! If you have found the answer, please share! Thanks.

**Comment by williantenfen** [comment]
`ionic add plugin ssh://git@bitbucket.org/triacyl/quimobackgroundservice.git`
 

> This command has been deprecate.  All resources are currently available in NPM and we recommend that you use NPM to manage these.
> More information is available here: https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower
> 
> Bower error, check that "undefined" exists,
> or try running "undefined" for more info. (CLI v2.0.0-beta.32)
> Your system information:
> 

> Cordova
   CLI: 6.2.0
   Gulp version:  CLI version 3.9.1
   Gulp local:   Local version 3.9.1
   Ionic Framework Version: 2.0.0-beta.10
   Ionic CLI Version: 2.0.0-beta.32
   Ionic App Lib Version: 2.0.0-beta.18 
   OS: Distributor ID:	LinuxMint Description:	Linux Mint 17.3 Rosa 
   Node Version: v4.4.1

**Comment by lthh89vt** [comment]
I think I know where the issue is but no solution

We are using ionic CLI version 2 whereas the ionic.io documentation is for ionic 1.

So no `ionic add` for anyone using ionic 2.

@williantenfen for your case, I'm sure you can do this

`ionic plugin add ssh://git@bitbucket.org/triacyl/quimobackgroundservice.git`

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As you can see from the above message the `ionic add` plugin has been deprecated with the latest version of the ionic 2 cli. You can read the v2 cli docs [here](http://ionicframework.com/docs/v2/cli/). Also, these docs will be updated as ionic 2 gets closer and closer to stable. Thanks for using Ionic!

**Comment by xkris6x** [comment]
I help solve this problem as:
xkris6x@NextSofts-Server:/home/project/web/nodeJS/ionic/oea$ ionic serve

There is an error in your gulpfile: 
Error: /home/project/web/nodeJS/ionic/oea/node_modules/node-sass/vendor/linux-x64-47/binding.node: failed to map segment from shared object: Operation not permitted
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/project/web/nodeJS/ionic/oea/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

xkris6x@NextSofts-Server:/home/project/web/nodeJS/ionic/oea$ ionic start

Invalid command (CLI v2.0.0-beta.32)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.4 (jessie)

**Comment by jacquesdev** [comment]
@jgw96 - can you please get this doc updated https://github.com/driftyco/ionic-cli/wiki/Migrating-to-NPM-from-bower, because it is referenced everywhere, but seems to be essentially be blank :)
