### ISSUE TITLE
sometimes it happens `File to import not found or unreadable: ionicons-icons `

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1119]
_From @RunningV on June 27, 2016 3:32_

when i change scss file to a component style sometime it can build to css file sometime it happens errors at cli ` File to import not found or unreadable:`, i have no idea about it. i try to remove `node_modules` and `npm install` again it is alse the same.so it's not the node_modules problem .my sys is like this : 
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.30
Ionic App Lib Version: 2.0.0-beta.16
OS: Windows 7 SP1
Node Version: v4.4.0

```
is it the windows sys problem???:persevere:

_Copied from original issue: driftyco/ionic#7065_

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! SInce this issue is an issue with the Ionic cli and not the framework i will be moving this issue to the ionic-cli repo. Thanks for using Ionic!

**Comment by RunningV** [comment]
i use `gulp-wait` to revise the 'ionic-gulp-sass-build' module, to delay sass build it seems solve the problem, maybe i should not use `ionic-gulp-sass-build` module,just add a gulp task to replace it.

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question of how to build your sass with your custom changes you made I will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
