### ISSUE TITLE
Typescript compile error on adding plain JS (using a plugin without typings)

### ISSUE THREAD

**Issue by Inoverse** [driftyco/ionic-cli#1121]
Following situation:
1. Added the [OneSignal](https://github.com/OneSignal/OneSignal-Cordova-SDK) ([Docs](https://documentation.onesignal.com/docs/phonegap-sdk-installation)) cordova plugin (this plugin has no typings and no ionic-native support).
2. Added the following code:

```
var notificationOpenedCallback = function(jsonData) {
    console.log('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
  };

  window.plugins.OneSignal.init("b2f7f966-d8cc-11e4-bed1-df8f05be55ba",
                                 {googleProjectNumber: "703322744261"},
                                 notificationOpenedCallback);

  // Show an alert box if a notification comes in when the user is in your app.
  window.plugins.OneSignal.enableInAppAlertNotification(true);
```

3.No on running 'ionic serve' the typescript compiler fails: Property 'plugins' does not exist on type 'Window'.

Tried more options:
Extended the Window interface with this code:

```
interface Window {
       plugins: any
}
```

Still the same error. Typescript compiler fails and ionic serve said it cannot find app.bundle.js, which is consistent because of the compiler fails and doesn't create the bundle.

Mike says this is probably an CLI bug.

**Comment by emgould** [comment]
Same issue

**Comment by Inoverse** [comment]
This is resolved a long time ago. Forget to close it...
