### ISSUE TITLE
Ionic Upload "Error Logging In"

### ISSUE THREAD

**Issue by sarahhostyk** [driftyco/ionic-cli#1122]
I recently changed my username and password on ionic account.

In the terminal when I do `ionic login` and put in my email and new password I keep on getting `Error loggin in`

I tried my old password and it doesn't work either. Also, my new password works fine when I log in/out of ionic.io.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post the output of ionic info here please? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
