### ISSUE TITLE
Error: Cannot find module '<full folder path to project>/plugins/ios.json'

### ISSUE THREAD

**Issue by johntomcy** [driftyco/ionic-cli#1123]
Using ionic 2.0.0-beta.30 trying to add ios platform using command 'ionic platform add ios' getting below error:
CHCP plugin after prepare hook:

Error: Cannot find module '/Users/<path to project>/plugins/ios.json'

Caught exception:
 undefined

Not sure what more details to be put in. Please let me know and i will do the needful.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post the output of ionic info here please? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
