### ISSUE TITLE
Error: Unmatched closing tag: widget

### ISSUE THREAD

**Issue by Devorite** [driftyco/ionic-cli#1129]
I run command : ionic emulate ios

and found error

Error: Unmatched closing tag: widget
Line: 53
Column: 9
Char: >

Caught exception:
 undefined 

help me to fix it please.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Could you post the output of `ionic info` here please? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by sigmasoldi3r** [comment]
Hey! I have a similar issue! It seems to be related to the 'Hockey-app-plugin' but i'm not sure. (I say it because in previous attempts of building the app, i've seen something mentioning it, but not really sure)

## _The log_
```
Error: Unmatched closing tag: widget
Line: 79
Column: 9
Char: >
```

## Ionic Info

```
Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

```

## Plugins
### Field in _package.json_
```
"cordovaPlugins": [
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "com.groupe-sii.device-display-metrics",
    "cordova-plugin-hockeyapp",
    "cordova-plugin-file",
    "cordova-plugin-compat",
    "cordova-plugin-statusbar",
    "cordova-plugin-device",
    "cordova-plugin-android-misc-info",
    "cordova-plugin-whitelist@~1.2.2",
    "cordova-plugin-splashscreen@~3.2.2",
    "cordova-plugin-statusbar@~2.1.3"
  ],
```
