### ISSUE TITLE
Output on every CLI command

### ISSUE THREAD

**Issue by Jota2142** [driftyco/ionic-cli#1131]
Every command on CLI outputs the same weird text:

<img width="581" alt="captura de tela 2016-06-29 as 09 38 26" src="https://cloud.githubusercontent.com/assets/976151/16452162/69517b9e-3ddd-11e6-9592-85c65ec93344.png">

**Comment by mhartington** [comment]
This is related to running node6.2.2. 
Node 6.3 was released yesterday which fixes this issue.

**Comment by jgw96** [comment]
SInce this issue does seem to be fixed in Node 6.3 i will be closing this issue. Thanks for using Ionic!
