### ISSUE TITLE
'ionic resources' generating empty directories with no icon and splash images

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1133]
_From @saqueib on June 29, 2016 5:29_

I am trying to generate icon and splash using `ionic resources` command but it's giving me empty directories every time.

so I tried using `ionic resources --icon` which generated icons, but same with `--splash` is still not giving any splash screens.

```
My system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.5
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002
```

_Copied from original issue: driftyco/ionic#7111_

**Comment by jgw96** [comment]
_From @laurentf on June 29, 2016 11:54_

same problem here.. any idea?

**Comment by jgw96** [comment]
_From @BergkampHUN on June 29, 2016 13:31_

The sample.psd is too big. Try to reduce the image size to 2208x2208.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with the ionic-cli and not the framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by saqueib** [comment]
@BergkampHUN thanks for suggesting, I reduced size to 2208x2208 and it generated the splash, someone should update the Sample PSD splash here (http://ionicframework.com/docs/cli/icon-splashscreen.html)

**Comment by kallelat** [comment]
Rather annoying issue, I recommend changing the sample PSD as soon as possible. Just spend too much time struggling with this...

**Comment by koiyu** [comment]
Reducing the size to 2208x2208 worked for me too, although:

```
$ ionic resources --splash
…
splash ios Default-Portrait@~ipadpro.png (2048x2732) skipped, source image splash.png (2208x2208) too small
…
splash ios Default-Landscape@~ipadpro.png (2732x2048) skipped, source image splash.png (2208x2208) too small
…
```
I can currently live with this, as I'm making a phone-only app.

**Comment by wendellpalazzo** [comment]
Hi... the command ionic resources --splash not creating splash images... 
but icons alright..

and cli not returning error

**Comment by kabus202** [comment]
Same here 👍

**Comment by jgw96** [comment]
Hello all, I will be closing this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1166. Thanks for using Ionic!
