### ISSUE TITLE
[ionic2] ionic package build android - Invalid transformation: invalid width: 2732 (CLI v2.0.0-beta.28)

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1134]
_From @pawsaw on June 29, 2016 10:40_

Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.28
Ionic App Lib Version: 2.0.0-beta.16
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.11.1
Xcode version: Xcode 7.3.1 Build version 7D1014 

```
$ ionic package build android
The resources folder already exists. We will not overwrite your files unless you pass the --force argument.
Running with the force flag will overwrite your resources directory and modify your config.xml file
Preparing your resources...

Invalid transformation: invalid width: 2732 (CLI v2.0.0-beta.28)
```

The width 2732 is the pixel size of the splash.png in the resources folder.

_Copied from original issue: driftyco/ionic#7118_

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Since this is an issue with the ionic cli and not the framework i will be moving this issue to the ionic cli repo. Thanks for using Ionic!

**Comment by Nielesonimusso** [comment]
So this is still a problem in CLI beta.36...

**Comment by pawsaw** [comment]
Hi. Any updates on this? Maybe this should be prioritised higher?

**Comment by rockertux** [comment]
This might be related to #1166. When I resize my base splash to 2208x2208 (instead of the original 3k x 3k) it successfully uploads my application.

(even though it fails to build)

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should fix this issue.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
