### ISSUE TITLE
Remove many apks getting after Crosswalk integration in an Ionic app

### ISSUE THREAD

**Issue by SanjayYadav90** [driftyco/ionic-cli#1141]
Hi all,
I am new to ionic.
I just added crosswalk and trying to build apt
`$ ionic build android`
Before this i was just getting 2 apps in project-folder/platforms/android/build/outputs/apk/ but after adding i am getting 6 akps.
_i am just wondering which will work on my devise?_

else shall i remove crosswalk to get appropriate apk by-

Removing Crosswalk
```
$ ionic browser revert android
# or
$ ionic browser remove crosswalk
```
Hope your help...

**Comment by jgw96** [comment]
Hello! This is actually a feature of crosswalk. Crosswalk compiles an apk for all the different cpu architectures out available on Android devices. I would recommend reading [here](https://crosswalk-project.org/documentation/android.html) to understand which one you should use. Thanks for using Ionic!
