### ISSUE TITLE
ionic run ios failed:Code Sign error

### ISSUE THREAD

**Issue by RocWangv** [driftyco/ionic-cli#1142]
Running 'run:before' gulp task before run
[14:43:10] Starting 'clean'...
[14:43:10] Finished 'clean' after 7.04 ms
[14:43:10] Starting 'build'...
[14:43:10] Starting 'sass'...
[14:43:10] Starting 'html'...
[14:43:10] Starting 'fonts'...
[14:43:10] Starting 'scripts'...
[14:43:10] Starting 'images'...
[14:43:10] Finished 'images' after 63 ms
[14:43:10] Finished 'scripts' after 84 ms
[14:43:10] Finished 'html' after 102 ms
[14:43:10] Finished 'fonts' after 99 ms
[14:43:11] Finished 'sass' after 940 ms
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/base-model.ts(26,16): Error TS2339: Property 'getBaseUrl' does not exist on type 'TFunction'.
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/oil-gun.ts(13,140): Error TS2314: Generic type 'Observable' requires 1 type argument(s).
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/order.ts(40,126): Error TS2314: Generic type 'Observable' requires 1 type argument(s).
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/order.ts(54,194): Error TS2314: Generic type 'Observable' requires 1 type argument(s).
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/order.ts(69,231): Error TS2314: Generic type 'Observable' requires 1 type argument(s).
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/order.ts(69,231): Error TS2314: Generic type 'Observable' requires 1 type argument(s).
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/order.ts(83,197): Error TS2314: Generic type 'Observable' requires 1 type argument(s).
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/models/order.ts(93,36): Error TS2314: Generic type 'Observable' requires 1 type argument(s).
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/pages/print/print.ts(4,9): Error TS2305: Module '"/Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/components/order-log"' has no exported member 'OrderLog'.
TypeScript error: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/app/pages/query/query.ts(24,30): Error TS2345: Argument of type '{ orderId: string; oilSort: string; oilCode: string; oilPrice: number; oilSumPrice: number; consu...' is not assignable to parameter of type 'Order'.
  Property 'orderid' is missing in type '{ orderId: string; oilSort: string; oilCode: string; oilPrice: number; oilSumPrice: number; consu...'.
[14:43:18] Finished 'build' after 8.25 s
[14:43:18] Starting 'run:before'...
[14:43:18] Finished 'run:before' after 11 μs

Running command: /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/hooks/after_prepare/010_add_platform_class.js /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos

add to body class: platform-ios

Building project  : /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/platforms/ios/eps_pos.xcodeproj

        Configuration : Debug

        Platform      : device

Build settings from command line:

    ARCHS = armv7 arm64

    CONFIGURATION_BUILD_DIR = /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/platforms/ios/build/device
    SDKROOT = iphoneos9.3
    SHARED_PRECOMPS_DIR = /Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/platforms/ios/build/sharedpch
    VALID_ARCHS = armv7 arm64

Build settings from configuration file '/Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    IPHONEOS_DEPLOYMENT_TARGET = 8.0
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h
    TARGETED_DEVICE_FAMILY = 1,2

=== BUILD TARGET CordovaLib OF PROJECT CordovaLib WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET eps_pos OF PROJECT eps_pos WITH CONFIGURATION Debug ===

Check dependencies

Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.

** BUILD FAILED **

The following build commands failed:

        Check dependencies

(1 failure)

Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/platforms/ios/cordova/build-debug.xcconfig,-project,eps_pos.xcodeproj,ARCHS=armv7 arm64,-target,eps_pos,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR=/Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/RocWang/Documents/workspace/project/EPS/02_Development/eps_pos/platforms/ios/build/sharedpch

Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

`
Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.12.0
Xcode version: Xcode 7.3.1 Build version 7D1014 

`

**Comment by RocWangv** [comment]
Any answer will appreciate !!!

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. It seems that you do not have your signing identity set up in xcode. Can you confirm that this is setup correctly? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by gtzinos** [comment]
Document this solution on your website. Write in your documentation that to run an ionic application on ios device need 2 months research.

**Comment by gtzinos** [comment]
Here is the solution guys !!! https://stackoverflow.com/questions/36095819/cordova-ios-error-building-images-xcassets/36968113#36968113
