### ISSUE TITLE
There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by aweifly** [driftyco/ionic-cli#1145]
Downloading: https://github.com/driftyco/ionic-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by jthoms1** [comment]
Closing this as a duplicate of #1013.
