### ISSUE TITLE
Problem when run `ionic run ios` mac os

### ISSUE THREAD

**Issue by emoryr** [driftyco/ionic-cli#1146]
Caught exception:
 Error: Command failed: cordova plugin add --save cordova-plugin-device
(node:839) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:839) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
info trying registry request attempt 1 at 09:44:35
http GET http://registry.cordova.io/cordova-plugin-device
info retry will retry, error on last attempt: Error: connect ETIMEDOUT 50.17.177.14:80
info trying registry request attempt 2 at 09:46:01
http GET http://registry.cordova.io/cordova-plugin-device
info retry will retry, error on last attempt: Error: connect ETIMEDOUT 50.17.177.14:80
info trying registry request attempt 3 at 09:48:18
http GET http://registry.cordova.io/cordova-plugin-device
Error: connect ETIMEDOUT 50.17.177.14:80
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12) 

-----

ionic info : 

Your system information:

Cordova CLI: 4.2.0
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. It seems that you are running an older version of the cordova cli. Would you mind running `sudo npm install -g cordova` and trying again please? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
