### ISSUE TITLE
ionic start ionic2sidemenu --v2(am using ionic 2.0.0-beta.32 )

### ISSUE THREAD

**Issue by SellvakumarSS** [driftyco/ionic-cli#1148]
Creating Ionic app in folder D:\ionic2R&D\ionic2sidemenu based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

sugesst me some solutions plz?>

**Comment by jthoms1** [comment]
Closing this as a duplicate of #1013.
