### ISSUE TITLE
Ionic io init 

### ISSUE THREAD

**Issue by vinodkumarmarupu** [driftyco/ionic-cli#1149]
While executing this command the following error. I'm getting

cd> ionic io init
![capture](https://cloud.githubusercontent.com/assets/11839708/16592517/b4431a60-42fe-11e6-8bcd-8c4ea5924af2.PNG)

**Comment by jthoms1** [comment]
Sorry could you provide a little more detail on this issue.  Are you saying that your password is correct but not being identified as being correct?

Thanks

**Comment by vinodkumarmarupu** [comment]
Thanks jthoms1. Now it is working on for me.

**Comment by jthoms1** [comment]
Thanks!

**Comment by lluisnieto** [comment]
How did you solve it? Can't make it work on cli.

**Comment by lluisnieto** [comment]
Ok, i managed it to work just by creating a new account....
