### ISSUE TITLE
ionic upload 403 error

### ISSUE THREAD

**Issue by james-andrewsmith** [driftyco/ionic-cli#115]
As described on the forum (http://forum.ionicframework.com/t/forbidden-upload-during-ionic-package/9712)

There appears to be an error with the upload process. 

Not sure if it's relevant but I found the ionic.project file has a blank app_id (even when specified on start), judging by the code that could be causing the URL created to have some issues?

Not sure what a valid app_id looks like so I couldn't test a manual fix.

**Comment by Haruhi999** [comment]
Also tried inserting app_id from the dummy project i created, still getting the same error
Error upload response: SyntaxError: Unexpected token < (CLI v1.2.14)

**Comment by softBarbarian** [comment]
same issue here, i do have app_id in ionic.project

```
ionic info

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.34
Cordova CLI: 4.1.2
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1 

```

**Comment by jbavari** [comment]
@softBarbarian @Haruhi999 @michaelkrog are you all still experiencing this issue with the latest CLI version, 1.3.11?

**Comment by amir-s** [comment]
@jbavari I had this problem, I updated to the latest CLI version (1.3.11) and it seems I don't have that `Error upload response: SyntaxError: Unexpected token` problem anymore.

But I get `Error packaging project, please try again later` every time I tried to package the project.

**Comment by MichaelJCole** [comment]
@jbavari  Same here on a new app.

```
$  ionic start appName creator:c5d7cbe3 

[lots of text]
 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>
[ok, I'll try it]

$  ionic package debug android
Loading appName...

Uploading app...
Successfully uploaded (be773c72)

android debug building...
Error packaging project, please try again later
```

**Comment by murilolobato** [comment]
@jbavari @amir-s @MichaelJCole Im following the getting started, and I can build the 'sidemenu' into my android phone with no problem, but when I try to 'ionic package debug ios' all I can get is:

    Error packaging project, please try again later

**Comment by MichaelJCole** [comment]
@murilolobato Me too :-)  I think it's either under construction or abandoned...  If it's not, post back!

**Comment by jbavari** [comment]
Hey guys - an update.

The package feature is still being worked on internally by the team. I'll keep you all posted when its completed.

**Comment by yanniboi** [comment]
I'm having the same problem.

I created a new project: 

ionic start packager tabs
cd packager
ionic upload
//Everything works fine up until this point.
ionic package debug android

Print out:

Loading packager...

Uploading app...
Successfully uploaded ([projectid])
Share your beautiful app with someone:
$ ionic share EMAIL
android debug building...
Error packaging project, please try again later


Probably just that the feature is still in development, but can someone update this when it is ready?

**Comment by ncapito** [comment]
+1 What is the deal with this ?

**Comment by dougshults** [comment]
Also curious about this one. Different error for me.

App `"app_id": ""` is empty in ionic.project and was working with fresh install. 

` ✗ name: <ul class="errorlist"><li>This field is required.</li></ul>
Unable to upload app (CLI v1.3.19)`

**Comment by ckahle33** [comment]
Getting errors as well. 

Uploading app...
 ✗ App d44ce385 not found
Unable to upload app (CLI v1.3.19)

```Your system information:

OS: Mac OS X Yosemite
Node Version: v0.12.2
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.19
Xcode version: Xcode 6.2 Build version 6C131e 
ios-sim version: 3.1.1 
ios-deploy version: 1.4.0 ```

**Comment by IsmaBit** [comment]
I've the same problem of @ckahle33 .
It's possible that the error is generate when we try to upload an existing project and not a blank or just created project?

**Comment by ckahle33** [comment]
Possibly. For now I am going the ad hoc route via OTA for beta distribution. Later today or tomorrw I will change the `app_id` and let you know if that works for me.

**Comment by eternalsnow00** [comment]
I have the same problem.And how to deal with it?

Loading myApp...

Uploading app...
Successfully uploaded (1ee97e25)

Share your beautiful app with someone:

$ ionic share EMAIL

android debug building...
Error packaging project, please try again later

**Comment by ThomasDalla** [comment]
Same here.
<pre>
android release building...
Error packaging project, please try again later
</pre>

**Comment by adomenech73** [comment]
The same:
Your system information:

OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.2 LTS 
Node Version: v0.10.38
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.22

**Comment by adomenech73** [comment]
found a workaround: http://ionicframework.com/docs/guide/publishing.html

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by allen8300** [comment]
Hi, I'm playing with your official sample "cutePuppyPics";
And I upload successfully.
While I keep getting Size: "NAN UNDEFINED" on the Ionic View App, and cannot view it.
I also tried all steps in documents.
Please help out about where is wrong and save my life.
Thanks so much.

**Comment by lisaiceland** [comment]
It seems this bug has come back. 
I'm getting this issue this morning. Can you plz help resolve this.

**Comment by smallbitt** [comment]
to me either..

**Comment by 1BJK903** [comment]
Nobody who can solve this problem? I got this problem today...

**Comment by pabloservin** [comment]
We are facing the same issue now... Started an hour ago. We can login but can't upload

**Comment by matinieves** [comment]
Same problem here :(

**Comment by anton-white** [comment]
Me too :(

**Comment by mlynch** [comment]
We are looking into this as we speak to fix

**Comment by dovk** [comment]
Same here, Good luck!

**Comment by mlynch** [comment]
Hey everyone, this has just been fixed. To be sure, run `ionic login` again to re-login to refresh the sessions. We had made some server side changes to cookies/session data that impacted the CLI.

**Comment by AbhayShiro** [comment]
@mlynch 
Thanks..... It is fixed. It is working fine here. I knew it was a temporary server issue.

**Comment by AbhayShiro** [comment]
@mlynch  

Thanks.
It is working fine here.
I knew it was a temporary server issue.

**Comment by rthomps7** [comment]
I'm now getting past the upload step, but having trouble with the provisioning profiles:

> Check dependencies
> Code Sign error: No matching provisioning profiles found: None of the valid provisioning profiles allowed the specified entitlements: com.apple.developer.associated-domains.
> 
> ** BUILD FAILED **

I tried deleting and recreating my profile. No luck. I'm running the same command as earlier this morning when everything worked.

**Comment by sertunc** [comment]
@mlynch you save my life dude <3

**Comment by ecommerce-technician** [comment]
You rock!

**Comment by lisaiceland** [comment]
thnx so much Matt & Team yaaaayyyy!

**Comment by dallasclark** [comment]
@mlynch thanks for the tip
