### ISSUE TITLE
Android build on Mac OS X - V2

### ISSUE THREAD

**Issue by kresogalic8** [driftyco/ionic-cli#1153]
Hey guys, i am having issues to build your starter cutePuppy app.

This is the error which i got in terminal. 

![screen shot 2016-07-07 at 2 32 01 pm 2](https://cloud.githubusercontent.com/assets/7289406/16653202/b49b3c16-444f-11e6-92c1-f27ac2155d75.png)

**Comment by jgw96** [comment]
Hello! Do you have the Android sdk installed on your mac? The easiest way to install it is to install [Android studio](https://developer.android.com/studio/index.html). This will also give you an easy to keep the sdk updated. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
