### ISSUE TITLE
Compatibilize ionic-cli with ionic-cli@beta

### ISSUE THREAD

**Issue by voliva** [driftyco/ionic-cli#1157]
I'm finding I always have to switch back and forth with ionic-cli for my ionic v1 projects with ionic-cli@beta for my ionic v2 projects. It's very uncomfortable.

It would be nice if ionic-cli@beta was backwards-compatible with ionic v1 (also all commands like browser add, setup sass, etc.) or rename the CLI to something like ionic-beta or just ionic2

**Comment by mhartington** [comment]
The beta CLI is backwards compatible with older V1. As stated in the docs...
>Worried about your V1 Ionic projects? Don’t worry! The beta release has all the functionality to work with both V1 projects and V2 projects.


http://ionicframework.com/docs/v2/getting-started/installation/

**Comment by voliva** [comment]
@mhartington Then why am I getting the following output?`

``````
E:\Victor>ionic --version
1.7.16


E:\Victor>ionic browser list
iOS - Browsers Listing:

Not Available Yet - WKWebView
Not Available Yet - UIWebView


Android - Browsers Listing:


Available - Crosswalk - ionic browser add crosswalk
         Version 8.37.189.14 Published
         Version 9.38.208.10 Published
         Version 10.39.235.15 Published
         Version 11.40.277.7 Published
         Version 12.41.296.5 Published
(beta)   Version 13.42.319.6 Published
(canary) Version 14.42.334.0 Published

Available - Crosswalk-lite - ionic browser add crosswalk-lite
(canary) Version 10.39.234.1 Published
(canary) Version 10.39.236.1 Published

Available - Browser (default) - ionic browser revert android
Not Available Yet - GeckoView

------------------------------------------------------------------------------------

E:\Victor>ionic --version
2.0.0-beta.32


E:\Victor>ionic browser list
  _             _
 (_)           (_)
  _  ___  _ __  _  ___
 | |/ _ \| '_ \| |/ __|
 | | (_) | | | | | (__
 |_|\___/|_| |_|_|\___|  CLI v2.0.0-beta.32

Usage: ionic task args


=======================
browser is not a valid task
``````

Or exactly the same for sass:

``````
E:\Victor>ionic setup sass
  _             _
 (_)           (_)
  _  ___  _ __  _  ___
 | |/ _ \| '_ \| |/ __|
 | | (_) | | | | | (__
 |_|\___/|_| |_|_|\___|  CLI v2.0.0-beta.32

Usage: ionic task args


=======================
setup is not a valid task
``````

From my point of view, the documentation is wrong. As example, these two features are available in v1 CLI, but not in v2 CLI. And it's specially important with the `browser` command, since it's often used when finishing a project.

**Comment by mhartington** [comment]
The browser command has been depreciated for some time, as for the setup task, that looks like it was removed. Though it doesn't remove sass capabilities.
