### ISSUE TITLE
Ionic serve not working properly on MacOS Sierra

### ISSUE THREAD

**Issue by jpike88** [driftyco/ionic-cli#1161]
Live reload isn't kicking in, the script seems to be triggering CSP incorrectly. Have to refresh manually all the time while developing.

![screen shot 2016-07-11 at 9 54 32 am](https://cloud.githubusercontent.com/assets/9585787/16716918/81c69dca-474d-11e6-8633-e63b4fed0e3b.png)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by mhartington** [comment]
This is not an issue with the CLI, rather the CSP that is in the index.html.
Running macOS and have not run into any issues.

**Comment by jpike88** [comment]
I'm having issues. The same exact repo runs fine on my El Captain laptop, and it was simply upgrading to macOS that caused this issue to occur on my Mac mini.

Ionic info shows this:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.2 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Not installed

Prematurely closing the issue doesn't help things.

**Comment by jpike88** [comment]
And the content security policy tag looks like this:

<meta http-equiv="Content-Security-Policy" content="default-src * 'self' blob: 'unsafe-inline' 'unsafe-eval' data: gap: https://ssl.gstatic.com; style-src 'self' 'unsafe-inline'; media-src * blob: data:">

**Comment by jpike88** [comment]
Resolved, this modification to the tag was needed:

`<meta http-equiv="Content-Security-Policy" content="default-src * 'self' blob: 'unsafe-inline' 'unsafe-eval' data: gap: https://ssl.gstatic.com; style-src 'self' 'unsafe-inline'; media-src * blob: data:; connect-src ws: *">`

This appears to be a difference in how Safari handles CSP, and should probably be taken into account somehow.

**Comment by mhartington** [comment]
The new version of safari shipped in macOS is much stricter. We actually remove the CSP tag in all of our starters, so this must be an older project.
