### ISSUE TITLE
Ionic CLI fail 

### ISSUE THREAD

**Issue by braianj** [driftyco/ionic-cli#1163]
After having lot of problems with facebook plugin, it turns into a ionic CLI problem. I've updated cordova and ionic and no fixes.

Here go some test

    $ ionic start test
    Creating Ionic app in folder /.../test based on tabs project
    Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
    [=============================]  100%  0.0s
    Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
    [=============================]  100%  0.0s
    Updated the hooks directory to have execute permissions
    Update Config.xml
    Initializing cordova project
    Adding in iOS application by default
    Brai:test braianmellor$ cd test
    Brai:test braianmellor$ ionic plugin ls
    /usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:53
				throw err;
				^

    Error: EACCES: permission denied, open '/Users/braianmellor/.config/configstore/insight-cordova.json'
    You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.create.all.get (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/cordova/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/cordova/node_modules/insight/lib/index.js:38:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/telemetry.js:37:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

So I do $ ionic info
    
    Your system information:
    
    Cordova CLI: Not installed
    Ionic Framework Version: 1.3.1
    Ionic CLI Version: 1.7.16
    Ionic App Lib Version: 0.7.3
    ios-deploy version: Not installed
    ios-sim version: 4.1.1 
    OS: Mac OS X El Capitan
    Node Version: v5.9.0
    Xcode version: Xcode 7.3.1 Build version 7D1014 
    
    
    ******************************************************
     Dependency warning - for the CLI to run correctly,      
     it is highly recommended to install/upgrade the following:     
    
     Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
     Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)
    
    ******************************************************

Then 

    : $ sudo npm install -g cordova
    Password:
    npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    /usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
    /usr/local/lib
    └── cordova@6.2.0 
    
    : $ sudo npm install -g ios-deploy
    npm WARN lifecycle ios-deploy@1.8.6~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.6 ./src/scripts/    check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
    npm ERR! Darwin 15.5.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
    npm ERR! node v5.9.0
    npm ERR! npm  v3.7.3
    npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall chmod
    
    npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/    ios-deploy'
    npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/    ios-deploy'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent 
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /.../test/test/npm-debug.log

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by braianj** [comment]
Sorry I was just editing the post

**Comment by braianj** [comment]
Of after spending more than 3 hours I've reinstalled node, npm, cordova and ionic

So i do ionic info

    Your system information:
    
    Cordova CLI: 6.2.0
    Ionic CLI Version: 1.7.16
    Ionic App Lib Version: 0.7.3
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Mac OS X El Capitan
    Node Version: v5.9.1
    Xcode version: Xcode 7.3.1 Build version 7D1014 
    
    
    ******************************************************
     Dependency warning - for the CLI to run correctly,      
     it is highly recommended to install/upgrade the following:     
    
     Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
     Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)
    
    ******************************************************

Then $ sudo npm install -g ios-sim

    /usr/local/bin/ios-sim -> /usr/local/lib/node_modules/ios-sim/bin/ios-sim
    /usr/local/lib
    └─┬ ios-sim@5.0.8 
      ├── bplist-parser@0.0.6 
      ├─┬ nopt@1.0.9 
      │ └── abbrev@1.0.9 
      ├─┬ plist@1.2.0 
      │ ├── base64-js@0.0.8 
      │ ├── util-deprecate@1.0.2 
      │ ├─┬ xmlbuilder@4.0.0 
      │ │ └── lodash@3.10.1 
      │ └── xmldom@0.1.22 
      └─┬ simctl@0.0.9 
        ├── shelljs@0.2.6 
        └── tail@0.4.0 

And then $ sudo npm install -g ios-deploy and here comes an error



    npm WARN lifecycle ios-deploy@1.8.6~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.6 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
    npm ERR! Darwin 15.5.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
    npm ERR! node v5.9.1
    npm ERR! npm  v3.7.3
    npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall chmod
    
    npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
    npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent 
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/local/bin/npm-debug.log

**Comment by ariellav** [comment]
Try
    $       sudo npm install --unsafe-perm=true ios-deploy -g

**Comment by braianj** [comment]
You know what you are doing!
Thanks Bro!!!!

**Comment by knzeng-e** [comment]
Thanks a lot @ariellav! Got the exact same problem and you fixed it! thanks you @braianj too for the topic!

**Comment by JoseVanterpool** [comment]
Thanks @ariellav!!! Solved it for me too!

**Comment by ariellav** [comment]
Glad I could help! :)

**Comment by DomTheBass** [comment]
Thank you @ariellav
