### ISSUE TITLE
ionic v2 project  use ionic emulate ios --cl  start emulate but alway loading 

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1167]
_From @tslearn on July 9, 2016 9:0_

**Which Ionic Version?** 1.x or 2.x
2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
ionic start test --v2
ionic emulate ios -cl

_Copied from original issue: driftyco/ionic#7249_

**Comment by jgw96** [comment]
Hello, since this issue seems to be an issue with the ionic cli and not the framework i will be moving this issue to that repo. Thanks for using Ionic!

**Comment by mhartington** [comment]
Livereload on devices has been disabled for some time now. Changes between OS's and cordova prevent livereload from being used. Closing for now.

**Comment by getqd** [comment]
Livereload on devices and emulators are disabled on v2.0 official release. Is there any plan on when it is enabled again? We're building apps that use a few cordova plugins and these apps must be tested on real devices. Without livereload it would be a hassle for trouble shooting. Thanks!

**Comment by mhartington** [comment]
There is not a whole lot that can be done about it right now. As I stated before, with security changes in the OS and cordova, they prevent livereload from working.
