### ISSUE TITLE
"ionic run ios" with multiple developer accounts

### ISSUE THREAD

**Issue by mrthehud** [driftyco/ionic-cli#117]
When xCode is configured with more than one developer account, ionic seems to use the first account in the list to sign, which causes problems because my apps provisioning profile is from the second account.

Has anyone else found a similar situation, and found a work around for it?

Is there an option for "ionic run ios" that lets me specify which identity / provisioning profile to use?

The docs (https://github.com/driftyco/ionic-cli/blob/master/README.md) seem a bit sparse to me, have I not found a more in-depth document?

Thanks in advance,
Hud

**Comment by jbavari** [comment]
Not sure I've really seen this before.

The `ionic run ios` commands relies on Cordova, which is really going to handle running the iOS build/xcrun processes based on your xcode project.

What you could do is open your xcode project that cordova generates, go into your information about your app, and selected the identity/profile to use.

Then when you run `ionic run ios`, it will execute the profile that you just specified. Let me know if that works.
