### ISSUE TITLE
Certain CLI commands require sudo to run

### ISSUE THREAD

**Issue by EavenSheets** [driftyco/ionic-cli#1172]
Why am I able to create an Ionic project without sudo, but when I begin to run commands such as build or state restore I am unable to do so without sudo? Below is the information I am getting back, but for me it doesn't make sense why if it would require permissions to add the plugins back to the project.

```
| => ionic state restore
(node:26923) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by mhartington** [comment]
None of the ionic command require sudo. Probably what happened, was that at some point, sudo was used, and now the current user does not have owner ship of the project.

Try running this command.

```bash
sudo chown -R $(whoami) ~/project/path
```

**Comment by gedeagas** [comment]
yep as @mhartington pointed out probably at some point you use sudo 
and to fix this just use chown command

**Comment by jgw96** [comment]
Hello all! As this issue should be solved by the solution above i will be closing this issue for now. Thanks for using Ionic!
