### ISSUE TITLE
bug: aapt finished with non-zero exit value 2

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1179]
_From @andreluiz93 on July 15, 2016 2:41_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>6.0</span>  <span ionic-webview>webview</span>

<span ionic-description>When I build the android with command.

What I do wrong?

The log: 

root@Andre-notebook:/home/andre/Pessoal/Devlopment/todo# ionic build android
Running command: /home/andre/Pessoal/Devlopment/todo/hooks/after_prepare/010_add_platform_class.js /home/andre/Pessoal/Devlopment/todo
add to body class: platform-android
ANDROID_HOME=/root/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-i386
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/root/Android/Sdk/build-tools/24.0.0/aapt'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.659 secs
Error: Error code 1 for command: /home/andre/Pessoal/Devlopment/todo/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/andre/Pessoal/Devlopment/todo/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#7325_

**Comment by hossam9995** [comment]
+1

**Comment by jcfuentes102** [comment]
I have the same problem, solutions?

**Comment by andreluiz93** [comment]
Hello all!

I Find de solution!

I see that version of platform-build(build-tools) it is so much to my notebook and O.S. (Debian 8 i386). So I find the version 23.0.1 and got build it.

**Comment by jcfuentes102** [comment]
Mmm I am using the API 24 but i have Ubuntu 12.0 i think should not be a problem!
Anyway i have dowloaded 23.0.1 how can i change in my project to use this version?

**Comment by andreluiz93** [comment]
I Think that you need to reload the ambient variable.

I changed in exactly path are called by "ionic build".

Look: In my computer the that path contains the build-tools is in "/root/Android/Sdk/build-tools/". I put the new version there and in the Android SDK Packpages I deleted the 24.

Shoud you have to download other packpages related in the version 23.0.1 too to avoid issues

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!

**Comment by trekommend** [comment]
it really worked @andreluiz93

**Comment by keshav-marketingmindz** [comment]
it really worked, you saved my day.. @andreluiz93
