### ISSUE TITLE
Should ignore www/lib

### ISSUE THREAD

**Issue by 5im0n** [driftyco/ionic-cli#120]
When we start a project with ionic-cli a .gitignore file is create.

I think we should ignore the ``www/lib`` repository because it contains the bower dependencies of the project and we don't need to keep track of them.

**Comment by jbavari** [comment]
@5im0n for now, we are going to leave that decisions to the developers who use ionic. Thanks for the suggestion!

**Comment by tomsun** [comment]
+1 for gitignoring `www/lib`

package.json exists in the file tree generated by `ionic start` and declares misc dependencies managed via npm, to be installed in `node_modules`, which is in .gitignore by default

bower.json  exists in the file tree generated by `ionic start` and declares mich dependencies managed via bower, to be installed in `www/lib`, ...
