### ISSUE TITLE
Cannot find module `tough-cookie`

### ISSUE THREAD

**Issue by aycanadal** [driftyco/ionic-cli#1206]
ionic start MyIonic2Project --v2

Caught exception:
 Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Quest\AppData\Roaming\npm\node_modules\ionic
\node_modules\request\lib\cookies.js:3:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by geetapuri** [comment]
Got the same error even after 'sudo npm install tough-cookie'
Need to include the path?

**Comment by geetapuri** [comment]
Added the path in bash profile.  Still same

**Comment by kumaro** [comment]
on 'npm install -g ionic@beta'  (node modules are not getting installed)
I tried with npm install -g tough-cookie now it is complaining about a different module

**Comment by sameera207** [comment]
I'm having the same error, Started happening after I update the cli, I'm currently on 

`ionic@2.0.0-beta.33`

**Comment by bazmatic** [comment]
Same issue running on Windows 10.  I've installed the following missing modules:
tough-cookie json-stringify-safe bl hawk
At this stage, after installing hawk, I get this on ionic serve
```
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.

**Comment by Vishnuraj910** [comment]
👍

**Comment by Vishnuraj910** [comment]
I installed all the missing modules and at last I ended up in an error like this
```
$ ionic start myApp --v2

Error: Cannot find module 'utile'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/prompt/lib/prompt.js:10:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)


Cannot find module 'utile' (CLI v2.0.0-beta.33)

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.33
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014 

```

**Comment by giobi** [comment]
same on windows 10 with tough cookie - same project in debian no problem (but i need windows to build)

**Comment by Vishnuraj910** [comment]
I'm getting problem in Mac
```
Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.33
Ionic App Lib Version: 2.0.0-beta.18
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.7
Xcode version: Xcode 7.3.1 Build version 7D1014 

```

**Comment by olaferlandsen** [comment]
Same error on Windows 8 x64, Windows 8.1 x64 and Mac OS El Capitan.

**Comment by pedrozbb** [comment]
try 
npm cache clean
npm update -g

**Comment by Peekmo** [comment]
@pedrozbb It totally breaks my `npm` but after a nodejs reinstallation it worked.

Thank you

**Comment by aycanadal** [comment]
npm cache clean
npm update -g

These helped thanks.

**Comment by jthoms1** [comment]
Found the issue. There is a problem with npm where you need to always publish packages with bundledDependencies from npm2 with the node_modules structure of npm2 (nested). When I released ionic@2.0.0-beta.33 I was using npm3 with the flat structure. So release beta.33 would only work with npm3 installs, which is what I used for testing.

I am sorry for the pain this might have caused. It is resolved in beta.35. I have tested and we should be ok now. Please let me know if you are still having issues. Thank you!

Fix: npm install -g ionic@2.0.0-beta.35

**Comment by anson-GH** [comment]
this is not regarding the toggle cookies

to resolving this:
1.install the nodejs correctly
2.delete the node_modules and “package-lock.json”
3. execute again npm install

this work for me.

**Comment by madodabado** [comment]
any update !!!
