### ISSUE TITLE
Sudo npm install -g ionic@beta errors in teminal, ionic serve won't work

### ISSUE THREAD

**Issue by sarahhostyk** [driftyco/ionic-cli#1210]
I tried running sudo npm install -g ionic@beta which apparently upgraded me to beta 33 from 32, and resulted in the following error messages in terminal and ionic serve and ionic serve -lc not working at all.

I had to do npm install -g ionic@2.0.0-beta.32 for ionic serve to work again although it still resulted in errors in my app.

First time tried errors:

![screen shot 2016-07-26 at 8 11 43 pm](https://cloud.githubusercontent.com/assets/19256663/17163629/3edf059e-538f-11e6-8ade-8ee2f56d095b.png)

Second time tried errors:

![screen shot 2016-07-27 at 12 15 04 am](https://cloud.githubusercontent.com/assets/19256663/17163631/477f8ade-538f-11e6-8261-3e8afe26a2e3.png)

**Comment by jthoms1** [comment]
Found the issue. There is a problem with npm where you need to always publish packages with bundledDependencies from npm2 with the node_modules structure of npm2 (nested). When I released ionic@2.0.0-beta.33 I was using npm3 with the flat structure. So release beta.33 would only work with npm3 installs, which is what I used for testing.

I am sorry for the pain this might have caused. It is resolved in beta.35. I have tested and we should be ok now. Please let me know if you are still having issues. Thank you!

Fix: npm install -g ionic@2.0.0-beta.35
