### ISSUE TITLE
Multiple address selection hangs

### ISSUE THREAD

**Issue by bradberger** [driftyco/ionic-cli#122]
Having an issue running the `ionic run android -l` command. It just hangs until finally resulting in error. The selection for interfaces/addresses never shows up. Running `ionic run android` works fine.

A few things have tried already:

* Typing in numbers, too, like 1, 2, etc., but doesn't seem to help.
* Versions `1.2.6-beta1`, `1.2.7` and `1.2.8-beta1`
* Clearing npm cache and all that...
* Using both `bash` and `sh`
* Other command flags (everything else works)

For what it's worth, this is on Xubuntu 14.10 (everything's updated, and ionic installed via bower is resolving to `1.0.0-beta.5b`).

![selection_022](https://cloud.githubusercontent.com/assets/3027536/4559651/344c70d2-4eee-11e4-8c04-c86277c0c6cd.png)

**Comment by jbavari** [comment]
@bradberger - have you tried this with the latest release of the CLI?

**Comment by bradberger** [comment]
Yes, seems fixed now.
