### ISSUE TITLE
Command start with sidemnu template does not work

### ISSUE THREAD

**Issue by altafit-git** [driftyco/ionic-cli#1225]
installing npm packages...
Error with start undefined
Error initializing app: There was an error with spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Ionic installed by "npm install ionic@beta"

**Comment by brunoosilva** [comment]
Problem resolved!

Run command: `sudo ionic start cutePuppyPics --v2`

See more: https://github.com/driftyco/ionic-cli/issues/1013

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. I am going to be closing this issue as a duplicate of #1013. Thanks for using Ionic!
