### ISSUE TITLE
inconsistency between 010_install_plugins.js hook and ionic state reset way to read package.json plugins

### ISSUE THREAD

**Issue by Freundschaft** [driftyco/ionic-cli#1226]
The 010_install_plugins.js hooks added by using ionic hooks add uses a different method of adding plugins, allowing it only to read strings for cordova plugins add (https://github.com/driftyco/ionic-cli/blob/master/lib/hooks/after_platform_add/010_install_plugins.js#L26).
Something like 

```
{
      "locator": "https://github.com/gfnork/Calendar-PhoneGap-Plugin.git",
      "id": "cordova-plugin-calendar"
}
``` 

will fail to be added by this hook.

This is largely inconsistent with the behavior of ionic state reset which uses a more sophisticated way to read the package.json and generate the cordova plugins add command. (https://github.com/driftyco/ionic-app-lib/blob/master/lib/state.js#L511)

I know the ionic state reset command is planned for deprecation, but to be honest, I think this could be fixed fast and painless until the ionic state reset command is removed

**Comment by Freundschaft** [comment]
I just added a PR for the changes by simply Copy pasting from ionic app lib, can this be merged?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
