### ISSUE TITLE
Ionice 2 - starter app issue

### ISSUE THREAD

**Issue by ranjit-battewad** [driftyco/ionic-cli#1233]
When I run command - " _ionic start cutePuppyPics --v2_ "

**I got following output -**

Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************
Creating Ionic app in folder /Users/XXX/ionic/apps/cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

And when I issue command ionic serve, it shows the following error in chrome console, hence 
not able to launch the application, any help will be appreciated.

(index):53 GET http://localhost:8100/build/js/es6-shim.min.js 
(index):55 GET http://localhost:8100/build/js/Reflect.js 
(index):56 GET http://localhost:8100/build/js/zone.js 
(index):58 GET http://localhost:8100/build/js/app.bundle.js

**Comment by brunoosilva** [comment]
Problem resolved!

Run command: `sudo ionic start cutePuppyPics --v2`

See more: https://github.com/driftyco/ionic-cli/issues/1013

**Comment by jgw96** [comment]
Hello all! It looks as if you have your permissions set up incorrectly as you should not need sudo to run any ionic commands. To get more info about this add the `--verbose` options to the end of your `ionic start` command. Since this is an issue with your local setup and not the cli itself i will be closing this issue for now. Thanks for using Ionic!
