### ISSUE TITLE
 only-valid attribute is Not taking value From Any Variable

### ISSUE THREAD

**Issue by anjaligithub** [driftyco/ionic-cli#1234]
As I am trying to select date from particular Interval of days ,  It is working with  hard coded value to only-valid attribute And not with the value in variable. My code is as follows

woking==>
<div class="col" ion-datetime-picker date  ng-model="date" placeholder="dd/mm/yyyy" only-valid="{'between': {'initial': '2016-7-01', 'final': '2016-10-30' }, 'inclusive': true}" ng-change="setTime()">
 </div>

Not working==>
<div class="col" ion-datetime-picker date  ng-model="date" placeholder="dd/mm/yyyy" only-valid="{'between': {'initial': '{{date1}}', 'final': 'date2' }, 'inclusive': true}" ng-change="setTime()">
 </div>

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!
