### ISSUE TITLE
Android Platform is not adding.

### ISSUE THREAD

**Issue by surender7790** [driftyco/ionic-cli#1237]
It is showing this error when I try to add android platform. 
I tried adding hooks.
And solution on the internet but error still occurring.
Error: EIO: i/o error, read

**Comment by jgw96** [comment]
Hello! Would you be able to provide more info about your error? If you could run `ionic info` and post the output here that would be great! Also, if could post the exact, full error that you are getting when trying to add the platform, along with the exact command you are running that would be awesome!

**Comment by surender7790** [comment]
##### Thank you @jgw96   for replying. I really appreciate it. But my issue was related to node.js, so [I completely uninstalled NodeJ](http://stackoverflow.com/a/20711410) from my machine.
##### It worked for me, so thank you once again.
#####  You are doing a great job. I'm closing this issue.
