### ISSUE TITLE
Cannot run ionic 

### ISSUE THREAD

**Issue by HassanBK** [driftyco/ionic-cli#1242]
I'm trying to run an ionic application, by the command 

`ionic install`

But it gives me the following error:

> Caught exception:
>  Error: Cannot find module 'async'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (E:\nodejs\node_modules\ionic\node_modules\request\nod
> e_modules\form-data\lib\form_data.js:9:13)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)

**Comment by jgw96** [comment]
Hello @HassanBK ! Thanks for opening an issue with us! `ionic install` is not a valid ionic cli command.  For info on how to use the ionic cli, including how to run your application you can look [here](http://ionicframework.com/docs/v2/cli/). Thanks for using Ionic!
