### ISSUE TITLE
undefined exception trying to start an ionic app

### ISSUE THREAD

**Issue by apijay** [driftyco/ionic-cli#1246]
#ionic start cutePuppyPics --v2
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
undefined

**Comment by brunoosilva** [comment]
+1

**Comment by brunoosilva** [comment]
Problem resolved!

Run command: `sudo ionic start cutePuppyPics --v2`

See more: https://github.com/driftyco/ionic-cli/issues/1013

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by apijay** [comment]
Cordova CLI: 4.2.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v5.9.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
