### ISSUE TITLE
ionic serve does not automatically reload the browser

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic-cli#1250]
Hello, I am having a really weird issue. 

I have latest ionic2 beta cli installed and working on Ionic v1 project, when I save a file i can see that ionic serve's command output logs out `HTML changes: www/templates/login.html` however `SASS` task is not executed and browser window is not reloaded. I have reinstalled Node and ionic to no luck...

Any help appreciated.

```
Cordova CLI: 6.3.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by NeckbreakerPascal** [comment]
Same issue here. I think that the issue with the SASS task has also to do with the issue that the command `ionic setup sass` is not working. 

As far as I know they work on it.

**Comment by okonon** [comment]
@NeckbreakerPascal which existing issue are you talking about? can you mention it here?

**Comment by roblouie** [comment]
I have a fix for you in the meantime (doesn't fix ionic setup sass, just sass running).

I just made a new task named 'serve:before', which will run first anytime ionic serve is run.  Then have a watch task run sass for you anytime you make changes.

```
gulp.task('serve:before', [ "sass", "watch"], function() {
});
```

**Comment by NeckbreakerPascal** [comment]
@okonon I mean issue #1245

**Comment by NeckbreakerPascal** [comment]
@roblouie where did you add the code? Sorry, always just using ionic serve, so I did not really work with gulp before.

**Comment by bartekmis** [comment]
@NeckbreakerPascal I had exactly the same issue as you and fix from @roblouie has helped me now. Just add this code to gulpfile.js, after `gulp.task('watch', function() {...` and it should work fine.

Hope that helps.

**Comment by MikelArnaiz** [comment]
@roblouie solution works

**Comment by okonon** [comment]
Tried solution above but browser does not automatically reload still...

**Comment by jbeuckm** [comment]
This works, thanks! Is there a way to run the new task when I do:
`ionic emulate ios -lsc`
???

**Comment by MischaZed** [comment]
@jbeuckm You can do:
`gulp.task('emulate:before', [ "sass", "watch"], function() {});`

**Comment by okonon** [comment]
This issue is fixed in 2bd7aeea83fe86eafe69e5f83e1ac766c58bbb39 .
Just updated ionic cli to `2.0.0-beta.37` and browser reloads correctly. Thanks @jthoms1

**Comment by performatric** [comment]
Not working for me.

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
**Ionic CLI Version: 2.0.0-beta.37**
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.4.4

**Comment by payen83** [comment]
I solved this problem by removing the folder node_modules/ and file package-lock.json, then at terminal run:
`npm install --save`

**Comment by deepak6446** [comment]
worked for me when i save with sublime instead of vscode
