### ISSUE TITLE
Error: Registry returned 404 for GET on http://registry.npmjs.org/cordova_plugin_googlemaps

### ISSUE THREAD

**Issue by meskatjahan** [driftyco/ionic-cli#1266]
I'm facing error while executing the following command.
    
         cordova plugin add cordova_plugin_googlemaps --variable API_KEY_FOR_ANDROID="API_KEY_GOES_HERE" --variable API_KEY_FOR_IOS="API_KEY_GOES HERE"

and it throws the error like below:

    Error: Registry returned 404 for GET on http://registry.npmjs.org/cordova_plugin_googlemaps.
 then i try to set the registry using the following command 
  
    npm set registry http://registry.npmjs.org/
 but, it doesn't work to me. It would be nice to me, if you help me to solve this problem.

Thanks.

**Comment by Yaman007** [comment]
how did you get this fixed? I am facing similar problem.
