### ISSUE TITLE
"ionic" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable

### ISSUE THREAD

**Issue by 3jFernando** [driftyco/ionic-cli#1267]
No se que sucede funcionaba pero ya no,
y lo bolvi a instalar pero nada.
alguien que me ayude

**Comment by tiago-pereira** [comment]
Have you installed ionic with -g option?

`npm install ionic -g`

**Comment by iluisdat** [comment]
Actualiza node, me paso lo mismo, tenia la 6.10 y actualice a 6.10.2 y ya está.
Saludos

**Comment by wcauich** [comment]
Instale con npm install -g ionic y cree un proyecto myproject, despues al correr el comando ionic serve en el directorio de mi proyecto me manda este error: Ionic no se reconoce como comando interno o externo.

Instalando ionic dentro de la carpeta corre la aplicacion pero no se si sea correcto volver a instalarlo dentro de mi proyecto, ademas de que lo tendria que hacer en cada proyecto que cree.

**Comment by AbnerSaavedra** [comment]
Verifica tu variable de entorno PATH, puede que falte añadir la ruta de los modulos de nodejs, esta: C:\Users\Nombre_de_usuario\AppData\Roaming\npm que suele eliminarse al instalar algún programa. En mi caso ocurrio luego de instalar el manejador de dependencias Yarn. Saludos, espero que te sirva.

**Comment by anRoswell** [comment]
Gracias AbnerSaavedra tal cual dices funciono y volvio a servir...

**Comment by AbnerSaavedra** [comment]
De nada @anRoswell

**Comment by JaredOrtz** [comment]
> Actualiza node, me paso lo mismo, tenia la 6.10 y actualice a 6.10.2 y ya está.
> Saludos

Exacto yo tenia la 8 y la actualice a la ultima.

**Comment by cristhian2121** [comment]
@AbnerSaavedra Gracias

**Comment by RichardLewis64** [comment]
tengo problemas al ejecutar el comando ionic start por lo demas con node y npm salen normal los comandos el problema deviba con el uso de comandos de ionic
