### ISSUE TITLE
After upgrading to ionic v2.0, error when creating new project

### ISSUE THREAD

**Issue by sklaujb** [driftyco/ionic-cli#1277]
Hi, after upgrading to the latest ionic version, I have these error message when creating new project.

**_Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined_** 

May I know how  to fix this.............

**Comment by bencarlson** [comment]
I'm having the same issue: 

C:\Users\Benjamin\AppData\Roaming\npm\ionic -> C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ionic
ionic@2.0.0-beta.37 C:\Users\Benjamin\AppData\Roaming\npm\node_modules\ionic

C:\workspace>
C:\workspace>ionic start avialoft-buildlog --v2
Creating Ionic app in folder C:\workspace\avialoft-buildlog based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

C:\workspace>

**Comment by sklaujb** [comment]
I reinstall ionic v2.0 and the error just no longer showing anymore, not sure why but is working fine now.

**Comment by Temeteron** [comment]
Same problem here, reinstall ionic doesn't solve the problem

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
