### ISSUE TITLE
ionic-cli 2.0.0: Plugins not remembered in package.json?

### ISSUE THREAD

**Issue by MaxDaten** [driftyco/ionic-cli#1278]
Hi,

beside I have some problems with plugins and ionic.native (https://github.com/driftyco/ionic-native/issues/438) which I hope it is somehow solved by the 2.0.0 version of the ionic-cli, I have problems when installing plugins.

Simple steps to reproduce in any project:

```sh
ionic state clear
ionic plugin add cordova-plugin-camera

cat package.json # no cordova-plugin-camera added
```

**Comment by tiago-pereira** [comment]
Looks the same as https://github.com/driftyco/ionic-cli/issues/1255

**Comment by MaxDaten** [comment]
Yes it's the same, sorry for double posting. I'm closing this one.
