### ISSUE TITLE
Error on ionic push --production-mode=y - Cannot read property 'inputValues' of undefined

### ISSUE THREAD

**Issue by casp0or** [driftyco/ionic-cli#1281]
Hi,

I ran into an issue ... ionic push --ios-prod-cert was fine ... upload ok

now ionic push --production-mode=y produce 

**error**
`
ionic push --production-mode=y
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
Caught exception:
 TypeError: Cannot read property 'inputValues' of undefined
    at getCmdArgValue (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:431:11)
    at getCmdLineOptions (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:447:3)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/push.js:39:3)
    at Promise.apply (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:1304:14
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
`

**my plugins**

> ionic plugin
> WARN: ionic.project has been renamed to ionic.config.json, please rename it.
> com.okmemo.cordova.imgdownloader 0.1.0 "ImgDownloader"
> cordova-plugin-app-event 1.2.0 "Application Events"
> cordova-plugin-autostart 2.0.1 "Autostart"
> cordova-plugin-camera 2.1.0 "Camera"
> cordova-plugin-console 1.0.2 "Console"
> cordova-plugin-crosswalk-webview 1.6.1 "Crosswalk WebView Engine"
> cordova-plugin-device 1.1.0 "Device"
> cordova-plugin-file 4.1.0 "File"
> cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
> cordova-plugin-network-information 1.2.1 "Network Information"
> cordova-plugin-splashscreen 3.0.0 "Splashscreen"
> cordova-plugin-statusbar 2.0.0 "StatusBar"
> cordova-plugin-vibration 2.1.0 "Vibration"
> cordova-plugin-whitelist 1.2.0 "Whitelist"
> de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
> ionic-plugin-keyboard 1.0.8 "Keyboard"
> phonegap-plugin-push 1.7.0 "PushPlugin"

**ionic info**
`ionic info

Your system information:

Cordova CLI: 6.2.0
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 7.3.1 Build version 7D1014`

Thanks

**Comment by jickpictures** [comment]
+1

**Comment by cmarin18** [comment]
+1

**Comment by casp0or** [comment]
you don´t need to "ionic push --production-mode=y"

I build my app for appstore and added the certificate on xcode and apps.ionic.io and it worked!
