### ISSUE TITLE
Caught exception  Cannot find module 'lodash/assign'

### ISSUE THREAD

**Issue by emag50** [driftyco/ionic-cli#1282]
Error when trying to install Ionic with sudo npm install -g ionic

Caught exception:
 Error: Cannot find module 'lodash/assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by yoricktran** [comment]
Same here when I run bower update ionic

**Comment by polouis** [comment]
Same for me

**Comment by alairjt** [comment]
+1

**Comment by BraveVN** [comment]
Same for me

**Comment by doug-shontz** [comment]
+1

**Comment by iBasit** [comment]
+1

**Comment by BraveVN** [comment]
I managed to try with a solution:
First, uninstall ionic with this command
`sudo npm uninstall -g cordova ionic`
and then re-install it 
`sudo npm install -g cordova ionic`
It works for me.
Hope it helps.

**Comment by trinhvanhuy** [comment]
i have the same issue :(
trying to unistall then reinstall not works :( 
any help ?

**Comment by sukealo** [comment]
Hello try this is:

`curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash`
`sudo npm uninstall -g cordova ionic`
`sudo apt-get install -y nodejs`
`sudo apt autoremove`
`sudo apt-get install -y build-essential`
`sudo npm install -g cordova ionic`

greats!

**Comment by ihachani** [comment]
Try reinstalling ionic and cordova and don't forget to empty npm cache
```
npm uninstall -g ionic cordova
npm cache clean
npm install -g ionic cordova
```
I hope this helps

**Comment by gchandrapati** [comment]
Thanks !  works for me

**Comment by denzelwamburu** [comment]
Same problem here with;
`node 6.6.0`

**Comment by evgeniyM** [comment]
Same problem, re-install didn't help

**Comment by vinchauhan** [comment]
@evgeniyM - Did you resolve it ? - I am in the same situation, looks like something is messed up with new ionic package - I updated it and started getting it

**Comment by evgeniyM** [comment]
I've switched back to node v4.2.6 and i don't get this error

**Comment by vinchauhan** [comment]
reinstalling ionic and cordova works - I guess I updated ionic earlier on a choppy network which started all this

node 7.0.0

**Comment by luciandarabus** [comment]
Thanks @ihachani. Works for me.

**Comment by Dora3monz** [comment]
just run npm install lodash...mine solve!!

**Comment by nanchaoP** [comment]
Thanks ihachani :)

**Comment by rakeshskc** [comment]
Thanks its work me ihachani :)

**Comment by emag50** [comment]
Thanks...wow really late but as newer node versions came out the problem just went away.

**Comment by davidvanvickle** [comment]
My system was using node 4.4, incompatible with ionic, where I had first installed cordova and ionic.  I had to uninstall cordova and ionic from that node version, then use nvm to use node 6.10+ instead, then install cordova and ionic there under node 6.10+, and it worked no problem.
