### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by AFAgarap** [driftyco/ionic-cli#1289]
```
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 
```

I'm using Ionic 2.0.0 on Ubuntu 14.04 LTS x64

![screenshot from 2016-08-19 15 42 44](https://cloud.githubusercontent.com/assets/11130276/17802631/e90c3bc6-6623-11e6-835f-f8b18b3acd39.png)

**Comment by BureauJorwert** [comment]
Same on OSX (10.11.6) after update via npm:
![image](https://cloud.githubusercontent.com/assets/19358700/17813637/725b17be-662c-11e6-9133-4c874870a0db.png)

**Comment by joshdobbs** [comment]
I'm getting the same error on windows 10  using ionic 2

![image](https://cloud.githubusercontent.com/assets/571858/17833827/905ccfb2-66dd-11e6-8319-ec5eb900e79f.png)

**Comment by AFAgarap** [comment]
On my case, I updated my `minimatch` by `sudo npm install -g minimatch`. Then, re-installed `sudo npm install -g cordova ionic`. Now, it's fine. 

![deepinscreenshot20160821190509](https://cloud.githubusercontent.com/assets/11130276/17836834/38ca2ccc-67d2-11e6-9ac5-014d05bc49b3.png)

**Comment by AFAgarap** [comment]
@joshdobbs @BureauJorwert Have you solved your issues?

**Comment by BureauJorwert** [comment]
Yep, updating minimatch was the solution. Thanks!
After updating cordova though, I had to update minimatch again, because I didn't trust the deprecation messages about minimatch cordova gave me.

**Comment by AFAgarap** [comment]
@BureauJorwert You're welcome :)
