### ISSUE TITLE
Space missing from command ?

### ISSUE THREAD

**Issue by KSDevTeam** [driftyco/ionic-cli#1290]
after running 'ionic start myApp tabs' the cli downloads the template but then displays this;

There was an error with the spawned command: npminstall

Running 'npm install' manually seems to work as per.

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
