### ISSUE TITLE
problem with ionic start ionicMySideMenu sidemenu

### ISSUE THREAD

**Issue by Somebi** [driftyco/ionic-cli#1300]
Creating Ionic app in folder C:\Cordova\ionicMySideMenu based on sidemenu project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

PS C:\Cordova>
---------------------------------------------------------------------

Probably npminstall should be with a space?

Was following setup readme from here:
http://taco.visualstudio.com/en-us/docs/tutorial-ionic/

**Comment by sv1jsb** [comment]
Hi,
I am getting the same error while using the start command on linux 14.10
with a fresh installation of Ionic CLI 2.0.

Checked all three templates, tabs, blank, sidemenu, all had the same result.

**Comment by mhartington** [comment]
Please provide your ionic info out. Node version, npm version, etc.

**Comment by sv1jsb** [comment]
Hi @mhartington ,

My ionic info gives:
Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.5 LTS 
Node Version: v5.4.1

npm -v
3.3.12

Thanks a lot 
Andreas

**Comment by Diegow3b** [comment]
run as root, works for me 
`sudo ionic...`

**Comment by tsanne** [comment]
I have the same issue starting all three template apps.  Here's my ionic info:

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 1.2.2
Gulp local:
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Windows 7 SP1
Node Version: v4.2.3

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
