### ISSUE TITLE
After update, won't succeed in initializing new projects:

### ISSUE THREAD

**Issue by sophiaphillyqueen** [driftyco/ionic-cli#1305]
The problem started after I obediently (albeit under 'sudo') ran the command to update as I was told by ionic.

Ironically, the project Initiated before that update (upon which I was told to update) initiated successfully. It was the update that broke everything.

Here is the error output:

Sophia-Shapiras-MacBook-Pro:tmp sophiashapira$ rm -rf NeoApp IaSo
Sophia-Shapiras-MacBook-Pro:tmp sophiashapira$ ionic start NeoApp sidemenu
Creating Ionic app in folder /Users/sophiashapira/tmp/NeoApp based on sidemenu project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Sophia-Shapiras-MacBook-Pro:tmp sophiashapira$

**Comment by cesarcosta99** [comment]
+1

**Comment by osyo** [comment]
try as a root

**Comment by aboodysa** [comment]
@osyo I tried root it did not work
+1


My system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.3.1

Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:Windows 10
Node Version: v5.5.0

Debug file contains error information is attached

[npm-debug.zip](https://github.com/driftyco/ionic-cli/files/433341/npm-debug.zip)

**Comment by stefan-frank** [comment]
I run into the same problem, and could fix it by updating to newer version of npm:

**Before:**
```
npm -v
1.4.28
ionic start <project-name> --v2
(...)
Installing npm packages...
Error with start undefined
(...)
```

After upgrading (https://www.npmjs.com/package/npm-windows-upgrade / https://docs.npmjs.com/getting-started/installing-node) npm to the latest version everything works fine:

**After:**
```
npm -v
3.10.7
```

I finally succeed starting a new ionic project 
```
ionic start <project-name> --v2
(...)
Installing npm packages...

Adding initial native plugins
[=============================]  100%  0.0s
Saving your Ionic app state of platforms and plugins
Saved platform
Saved plugins
Saved package.json

? ♫ ? ♫  Your Ionic app is ready to go! ? ♫ ? ♫
(...)
```

**Comment by osyo** [comment]
You have to update npm - cordova - ionic
I succeed starting an ionic project

**Comment by sophiaphillyqueen** [comment]
How do I update npm?

The instructions I followed from StackOverflow (http://stackoverflow.com/questions/11284634/upgrade-nodejs-to-the-latest-version-on-mac-os) didn't really seem to work too well: I got the following fatal-error:


    Sophia-Shapiras-MacBook-Pro:tmp sophiashapira$ npm install -g npm
    module.js:327
        throw err;
        ^
    
    Error: Cannot find module './cache/caching-client.js'
        at Function.Module._resolveFilename (module.js:325:15)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at /usr/local/lib/node_modules/npm/lib/npm.js:23:24
        at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:475:3)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
    Sophia-Shapiras-MacBook-Pro:tmp sophiashapira$

**Comment by stefan-frank** [comment]
I was struggling as well with the update on my Windows machine and had similar issues with caching problems. I moved the folders in my user directory (.npm -> .npm.old & .npm-cache -> .npm-cache.old) and restarted with installing the packages. I took a while, but the caching problems were resolved.

There might be better ways ;-).

**Comment by Z3R0c007** [comment]
Im having the same problem. I think that it might be because I installed the 6.5 v instead of 4.5 v. Im going to install the 4.5 v and see whats what.
![captureionicinstall](https://cloud.githubusercontent.com/assets/17053169/18139036/ea222b7a-6faf-11e6-89fd-3c3fb981c221.PNG)

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
