### ISSUE TITLE
events.js:72 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by aruncumer** [driftyco/ionic-cli#131]
events.js:72 throw er; // Unhandled 'error' event ^ Error: spawn ENOENT at errnoException (child_process.js:975:11) at Process.ChildProcess._handle.onexit (child_process.js:766:34)

----This is my code -----

var curl = require('curlrequest');
var express = require('express');
var app = express();

var options = {
    url: "https://api.github.com/repos/jiangmiao/node-curl",
    encoding: null,
  //, headers: { 'foo bar': 'wha' }
};

curl.request(options, function (err, data, meta) {

    data = JSON.parse(data.toString());

    console.log(data);

});

--------------------- my node details is------------

{ http_parser: '1.0', node: '0.10.5', v8: '3.14.5.8', ares: '1.9.0-DEV', uv: '0.10.5', zlib: '1.2.3', modules: '11', openssl: '1.0.1e', npm: '1.2.18', 'email-node': '1.0.0' }

---------------my system config--- 64-bit operating system WINDOWS 8, x64-based processor

**Comment by jbavari** [comment]
Could you please give some more information about what you are trying to do here?

It looks like you're trying to figure up an express server, how does this relate to ionic?
