### ISSUE TITLE
Error While Creating a Project 

### ISSUE THREAD

**Issue by anveshnara** [driftyco/ionic-cli#1319]
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

I am not able to create a new App in Ionic V2

**Comment by anveshnara** [comment]
https://cloud.githubusercontent.com/assets/8431063/18045897/cf410218-6df2-11e6-9688-76f7416cb71d.png

**Comment by Diegow3b** [comment]
Same in here
![bugionic](https://cloud.githubusercontent.com/assets/1602831/18068694/127bd654-6e19-11e6-9bb5-2a343a2ba695.png)

**Comment by Diegow3b** [comment]
work for me when i use as root
`sudo `ionic start cameraApp blank --v2 --ts

**Comment by anveshnara** [comment]
Thanks @Diegow3b

**Comment by jag2kn** [comment]
the sudo command no fix the problem for me  :(

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
