### ISSUE TITLE
New blank project failed to start scafolding 

### ISSUE THREAD

**Issue by ManuInNZ** [driftyco/ionic-cli#1337]
Not sure if going back a version would do the trick
PS C:\Users\emmanuel.auffray\Documents\Personal\ionic\recorder> npm install -g cordova
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\emmanuel.auffray\AppData\Roaming\npm\cordova -> C:\Users\emmanuel.auffray\AppData\Roaming\npm\node_modules\cordova\bin\cordova
C:\Users\emmanuel.auffray\AppData\Roaming\npm
`-- cordova@6.3.1

PS C:\Users\emmanuel.auffray\Documents\Personal\ionic\recorder> npm install -g ionic@beta
C:\Users\emmanuel.auffray\AppData\Roaming\npm\ionic -> C:\Users\emmanuel.auffray\AppData\Roaming\npm\node_modules\ionic\bin\ionic
C:\Users\emmanuel.auffray\AppData\Roaming\npm
`-- ionic@2.0.0-beta.37

PS C:\Users\emmanuel.auffray\Documents\Personal\ionic\recorder> ionic start ionic2-recorder blank --v2
Directory already exists: C:\Users\emmanuel.auffray\Documents\Personal\ionic\recorder\ionic2-recorder
Would you like to overwrite the directory with this new project?
(yes/no): yes
yes

Creating Ionic app in folder C:\Users\emmanuel.auffray\Documents\Personal\ionic\recorder\ionic2-recorder based on blank project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by ManuInNZ** [comment]
Fixed by upgrading to node 6.5

**Comment by jazib-bashir** [comment]
@ManuInNZ After upgrading still same error

**Ionic**: ionic@2.0.0-beta.37
**Node**: 6.5.0
