### ISSUE TITLE
 Ionic start a new project 

### ISSUE THREAD

**Issue by vividwang** [driftyco/ionic-cli#1341]
Error with start undefined
Error Initializing app: There was an error with the spawned command: npm install
There was an error with the spawned command: npm install
Caught exception:
 undefined

**Comment by emilio-simoes** [comment]
I have the same issue, just thought that it would be worth to mention that the output shows the 'npminstall' command without a space between the 'npm' and the 'install':

`Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined`

**Comment by vividwang** [comment]
This is because I have changed the system default font，which makes 'npm install' looks like 'npminstall'.

**Comment by lovedaan** [comment]
Then how do you solve it？Can you tell me the way to solve it？Thank you very much.

**Comment by emilio-simoes** [comment]
In my case I didn't, I just deleted the all directory and executed the command again. The second time it finished without a problem.

**Comment by lovedaan** [comment]
Do you delete the directory, the project directory, or re download ionic and Cordova?

**Comment by emilio-simoes** [comment]
Deleted the project directory.

**Comment by vividwang** [comment]
And i don't know how to solve it too.All I do is kind like what emilio-simoes did.

**Comment by alamops** [comment]
On OS X El Capitan, I also tried to delete directory and to install again.
But, on every try I got this error.

**Comment by money4marry** [comment]
I met this error,too. Someone told me that maybe because the version is old,but i didn't know how to upgrade it

**Comment by anesumuz** [comment]
Same issue here..anyone resolve this?

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
