### ISSUE TITLE
Error with ionic start

### ISSUE THREAD

**Issue by suvajit** [driftyco/ionic-cli#1356]
Followed installation guide on http://ionicframework.com/docs/v2/getting-started/installation/ to create a project.
Got the following error:
LII-RLM-013:Ionic suvajit$ ionic start bt-test --v2
Directory already exists: /Users/suvajit/Works/Ionic/bt-test
Would you like to overwrite the directory with this new project?
(yes/no): yes

Creating Ionic app in folder /Users/suvajit/Works/Ionic/bt-test based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by benlooi** [comment]
I have the same problem with Ionic 1
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by benlooi** [comment]
Here is my verbose dump. Seems I need to run ionic with sudo. Really?
Installing npm packages...
Running exec command: npminstall
npm
 WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css

npm 
ERR! Darwin 15.6.0

npm ERR! 
argv "/usr/local/Cellar/node4-lts/4.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.3.0
npm ERR! npm  v3.10.7
npm ERR! path /Users/Ben/.npm/array-uniq/1.0.3
npm ERR! 
code EACCES

npm ERR! errno
 -13
npm ERR!
 
syscall
 mkdir



npm 
ERR! Error: EACCES: permission denied, mkdir '/Users/Ben/.npm/array-uniq/1.0.3'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/Users/Ben/.npm/array-uniq/1.0.3']
npm ERR!   errno: -13,
npm 
ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm
 ERR!   path: '/Users/Ben/.npm/array-uniq/1.0.3',
npm
 
ERR!   parent: 'gulp-util' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.



npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ben/GitHub/ThotsApp_new/npm-debug.log

Spawn command completed


Here are a whole bunch of other warnings after I run with sudo ionic start

Installing npm packages...
Running exec command: npminstall
npm
 WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm
 WARN prefer global node-gyp@3.4.0 should be installed with -g

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!

**Comment by iamnathanwindsor** [comment]
I'm still having trouble installing ionic properly even after running 

`npm install -g ionic@latest`



response:

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/ionic
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└── ionic@2.1.4 

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@latest"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/ionic
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/ionic'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/ionic'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/ionic' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nathan/testApp/npm-debug.log
