### ISSUE TITLE
Issue encountered while starting ionic 2

### ISSUE THREAD

**Issue by clementcrownrise** [driftyco/ionic-cli#1360]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Double Edge>npm
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\Double Edge\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:
20:13
    at Object.<anonymous> (C:\Users\Double Edge\AppData\Roaming\npm\node_modules
\npm\bin\npm-cli.js:76:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

C:\Users\Double Edge>ionic start newap tabs -v2
Creating Ionic app in folder C:\Users\Double Edge\newap based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

C:\Users\Double Edge>y
'y' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Double Edge>https://github.com/driftyco/ionic-cli/issues
'https:' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Double Edge>https://github.com/driftyco/ionic-cli/issues

**Comment by omotlhaga** [comment]
I never got this issue before but now new projects are failing from this morning.

**Comment by kiwox** [comment]
Same here in macOS. Looks like an issue with create project command.

npminstall should be npm install (space between)

**Comment by money4marry** [comment]
i figure it out
1.enter the error project directory ;
2.run cmd , input "npm install" wait for success;
3.now try to run the project,
if it isn't work for u,i can't help more.
ps:sry about my poor english-writing.

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
