### ISSUE TITLE
ToDo: check for plugins directory before adding platform

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#137]
Many projects ignore plugins and platforms directories. Missing plugins will prevent us from adding a platform. We should check for the plugins dir and add it if it's missing before adding a platform.

**Comment by softBarbarian** [comment]
@diegonetto's generator-ionic has that hook already can it be incorporated into ionic-cli? Here is the link https://github.com/diegonetto/generator-ionic/blob/master/templates/hooks/before_platform_add/init_directories.js

Also another feature that generator ionic has is when you add a platform, the Cordova plugins that are listed in package.json are added automatically! https://github.com/diegonetto/generator-ionic/blob/master/templates/hooks/after_platform_add/install_plugins.js

**Comment by jbavari** [comment]
@softBarbarian - I've added a few hooks from @diegonetto for initing directories, keeping tracking of plugins, and installing them on platform add. Should be going out in 1.3.3.
