### ISSUE TITLE
Installing Ionic error: Cannot find module 'inherits'

### ISSUE THREAD

**Issue by Stephenradams** [driftyco/ionic-cli#1378]
Hi, I've just been trying to install Ionic 2 (as I was originally trying to update to the latest beta). Now I keep getting this error:
`Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/glob/glob.js:42:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)`

I've tried option 1 of the how to fix npm permissions problems from the npm site (https://docs.npmjs.com/getting-started/fixing-npm-permissions). But still the error keeps on happening.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Would you mind posting the command you used to try to install the cli? Thanks!

**Comment by Stephenradams** [comment]
I used `npm install -g ionic` I also tried with sudo

**Comment by calebeaires** [comment]
This could help:


`npm uninstall -g ionic cordova`
`npm install -g ionic cordova`


Sometimes cordova is not present!

**Comment by Stephenradams** [comment]
I actually found out what the problem was, I have a newer version of Node running, not the LTS version. So I had to remove Node and npm, then install nvm to have both the LTS version and a latest version (which I need for a workshop I'm attending). 
So now everything is working (as long as I remember which version I'm running on).

**Comment by GSThina** [comment]
@calebeaires  I'm using mac and pls let me know what to do for the same issue!

**Comment by Bikramcodifier** [comment]
@calebeaires Thanks a lot It helps me. First we have to uninstall completely then install again.
