### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by happy05abc** [driftyco/ionic-cli#1379]
Hi,i am very excited to use ionic. 
But,when i executed "ionic start emotion1.0" in my mint,i got the wrong info as following:

Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

so,why???

**Comment by sanledi-buli** [comment]
Same with me, i'm using windows 8.

```shell
Your system information

Cordova CLI: 6.3.0
Gulp version:  CLI ve
Gulp local:
Ionic CLI Version: 2.
Ionic App Lib Version
OS: Windows 8.1
Node Version: v4.4.7
```

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
