### ISSUE TITLE
ionic resources doesn't  work properly with PSD

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1383]
_From @loursbourg on September 18, 2016 13:15_

#### Short description of the problem:
When i run Ionic resources from the Command line, nothing happens

#### What behavior are you expecting?
ionic should generate the rousources.

**Steps to reproduce:**
1. Create a simple image in Photoshop
2. Add a new layer, apply a Layer mask
3. Run ionic resources.

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0

**Using:**
Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v6.0.0

_Copied from original issue: driftyco/ionic#8111_

**Comment by jgw96** [comment]
_From @ramonornela on September 18, 2016 18:6_

Close and move to ionic-cli

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
