### ISSUE TITLE
Error with start undefined

### ISSUE THREAD

**Issue by namezy** [driftyco/ionic-cli#1388]
Installing npm packages...
Error with start undefined

Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by namezy** [comment]
C:\Users\LEN\AppData\Roaming\npm\ionic -> C:\Users\LEN\AppData\Roaming\npm\node_modules\ionic\bin\ionic
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\LEN\AppData\Roaming\npm\cordova -> C:\Users\LEN\AppData\Roaming\npm\node_modules\cordova\bin\cordova
ionic@2.0.0 C:\Users\LEN\AppData\Roaming\npm\node_modules\ionic

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
