### ISSUE TITLE
Ionic install error with MacOS Sierra

### ISSUE THREAD

**Issue by chemitaxis** [driftyco/ionic-cli#1397]
Hi, I have this error when try to install with MacOS Sierra:

> npm WARN In ionic@2.0.0 replacing bundled version of semver with semver@4.2.0
> npm WARN In ionic@2.0.0 replacing bundled version of ionic-app-lib with ionic-app-lib@2.0.0
> npm ERR! Darwin 16.0.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.3
> npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall rename
> 
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
> npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/*******/npm-debug.log
> npm ERR! code 1

Node version 6.6.0
npm version 3.10.3

Thanks.

**Comment by chemitaxis** [comment]
Ok, sudo npm uninstall ionic -g

And reinstall again, fixed my problem...

**Comment by YuyangHYY** [comment]
Thank you very much, perfect solve my problem
