### ISSUE TITLE
run -r <some number> raises Unknown platforms

### ISSUE THREAD

**Issue by pellekrogholt** [driftyco/ionic-cli#140]
$ ionic --help

says:

    run [options] <PLATFORM> ..................  Run an Ionic project on a connected device
        [--livereload|-l]  ....................  Live reload app dev files from the device (beta)
        [--port|-p]  ..........................  Dev server HTTP port (8100 default, livereload req.)
        [--livereload-port|-r]  ...............  Live Reload port (35729 default, livereload req.)

works: 

    $ ionic run -l -c -s -p 8101 --livereload-port 35740 android

but:

    $ ionic run -l -c -s -p 8101 -r 35740 android

raises:

    ...
    Unknown platforms: 35740

ionic cli version

    $ ionic --version
    1.2.8

**Comment by jbavari** [comment]
@pellekrogholt - thanks for reporting. Nice catch.

Sorry for the delay in getting to this. This fix should be rolling out in 1.3.3.
