### ISSUE TITLE
What problem?  Installing npm packages...

### ISSUE THREAD

**Issue by zsc123400** [driftyco/ionic-cli#1409]
zhou-mac:WebstormProjects zhou$ ionic start myShrine tabs -i com.shheal.shrine
Creating Ionic app in folder /Users/zhou/WebstormProjects/myShrine based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by Grover1331** [comment]
I am facing this issue while installing the npm packages in my app while creating it, please let me know the solution on this problem

**Comment by varios983** [comment]
I have the same error creating my first ionic app in a Microsoft Windows 10. 
This is my last configuration:

**c:\workspace\projects> ionic info**
Your system information:
Cordova CLI: 6.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v6.3.0

**c:\workspace\projects> npm -v**
3.10.3

I have test a lot of combinated versions of nodejs, cordova and ionic, but I could not find the solution to this error. Here is the command I exec.

**C:\workspace\proyectos>ionic start demoApp --verbose**

Creating Ionic app in folder C:\workspace\proyectos\demoApp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Running exec command: npminstall
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-clean-css

npm WARN
 deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm
WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN
deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

npm WARN
 deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.

npm WARN prefer global node-gyp@3.4.0 should be installed with -g


> node-sass@3.10.0 install C:\workspace\proyectos\demoApp\node_modules\node-sass
> node scripts/install.js


Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-48_binding.node

Cannot download "https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-48_binding.node":

tunneling socket could not be established, cause=connect ECONNREFUSED 10.16.138.100:443

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080


> node-sass@3.10.0 postinstall C:\workspace\proyectos\demoApp\node_modules\node-sass
> node scripts/build.js


Building: C:\workspace\tools\nodejs\node.exe C:\workspace\proyectos\demoApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

gyp

info it worked if it ends with ok

gyp verb cli [ 'C:\\workspace\\tools\\nodejs\\node.exe',
gyp verb cli   'C:\\workspace\\proyectos\\demoApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.3.0 | win32 | x64
gyp verb command rebuild []

gyp
 verb command clean []

gyp
 verb clean removing "build" directory

gyp
verb command configure []

gyp
verb check python checking for Python executable "python2" in the PATH

gyp
verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\workspace\proyectos\demoApp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\workspace\proyectos\demoApp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\workspace\proyectos\demoApp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\which\which.js:90:16
gyp verb
`which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\index.js:44:5

gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\workspace\proyectos\demoApp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\workspace\proyectos\demoApp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\workspace\proyectos\demoApp\node_modules\which\which.js:81:29)

gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH

gyp
verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\workspace\proyectos\demoApp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\workspace\proyectos\demoApp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\workspace\proyectos\demoApp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
gyp verb `which` failed  python { Error: not found: python
gyp
verb `which` failed     at getNotFoundError (C:\workspace\proyectos\demoApp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\workspace\proyectos\demoApp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\workspace\proyectos\demoApp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\workspace\proyectos\demoApp\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher

gyp
 verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe

gyp
 ERR! configure error

gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\workspace\proyectos\demoApp\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\workspace\proyectos\demoApp\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR!
stack     at C:\workspace\proyectos\demoApp\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\workspace\\tools\\nodejs\\node.exe" "C:\\workspace\\proyectos\\demoApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\workspace\proyectos\demoApp\node_modules\node-sass
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

Build failed

ionic-project@1.1.1 C:\workspace\proyectos\demoApp
+-- bower@1.7.9
+-- d@0.1.1  extraneous
+-- gulp@3.9.1
| +-- archy@1.0.0
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.0.0
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- deprecated@0.0.1
| +-- interpret@1.0.1
| +-- liftoff@2.3.0
| | +-- extend@3.0.0
| | +-- findup-sync@0.4.2
| | | +-- detect-file@0.1.0
| | | | `-- fs-exists-sync@0.1.0
| | | +-- is-glob@2.0.1
| | | | `-- is-extglob@1.0.0
| | | +-- micromatch@2.3.11
| | | | +-- arr-diff@2.0.0
| | | | | `-- arr-flatten@1.0.1
| | | | +-- array-unique@0.2.1
| | | | +-- braces@1.8.5
| | | | | +-- expand-range@1.8.2
| | | | | | `-- fill-range@2.2.3
| | | | | |   +-- is-number@2.1.0
| | | | | |   +-- isobject@2.1.0
| | | | | |   | `-- isarray@1.0.0
| | | | | |   +-- randomatic@1.1.5
| | | | | |   `-- repeat-string@1.5.4
| | | | | +-- preserve@0.2.0
| | | | | `-- repeat-element@1.1.2
| | | | +-- expand-brackets@0.1.5
| | | | | `-- is-posix-bracket@0.1.1
| | | | +-- extglob@0.3.2
| | | | +-- filename-regex@2.0.0
| | | | +-- kind-of@3.0.4
| | | | | `-- is-buffer@1.1.4
| | | | +-- normalize-path@2.0.1
| | | | +-- object.omit@2.0.0
| | | | | +-- for-own@0.1.4
| | | | | | `-- for-in@0.1.6
| | | | | `-- is-extendable@0.1.1
| | | | +-- parse-glob@3.0.4
| | | | | +-- glob-base@0.3.0
| | | | | | `-- glob-parent@2.0.0
| | | | | `-- is-dotfile@1.0.2
| | | | `-- regex-cache@0.4.3
| | | |   +-- is-equal-shallow@0.1.3
| | | |   `-- is-primitive@2.0.0
| | | `-- resolve-dir@0.1.1
| | |   `-- global-modules@0.2.3
| | |     +-- global-prefix@0.1.4
| | |     | +-- ini@1.3.4
| | |     | +-- osenv@0.1.3
| | |     | | `-- os-tmpdir@1.0.1
| | |     | `-- which@1.2.11
| | |     |   `-- isexe@1.1.2
| | |     `-- is-windows@0.2.0
| | +-- fined@1.0.1
| | | +-- expand-tilde@1.2.2
| | | +-- lodash.assignwith@4.2.0
| | | +-- lodash.isarray@4.0.0
| | | +-- lodash.isempty@4.4.0
| | | +-- lodash.pick@4.4.0
| | | `-- parse-filepath@1.0.1
| | |   +-- is-absolute@0.2.5
| | |   | +-- is-relative@0.2.1
| | |   | | `-- is-unc-path@0.1.1
| | |   | |   `-- unc-path-regex@0.1.2
| | |   | `-- is-windows@0.1.1
| | |   +-- map-cache@0.2.2
| | |   `-- path-root@0.1.1
| | |     `-- path-root-regex@0.1.2
| | +-- flagged-respawn@0.3.2
| | +-- lodash.isplainobject@4.0.6
| | +-- lodash.isstring@4.0.1
| | +-- lodash.mapvalues@4.6.0
| | +-- rechoir@0.6.2
| | `-- resolve@1.1.7
| +-- minimist@1.2.0
| +-- orchestrator@0.3.7
| | +-- end-of-stream@0.1.5
| | | `-- once@1.3.3
| | |   `-- wrappy@1.0.2
| | +-- sequencify@0.0.7
| | `-- stream-consume@0.1.0
| +-- pretty-hrtime@1.0.2
| +-- semver@4.3.6
| +-- tildify@1.2.0
| | `-- os-homedir@1.0.1
| +-- v8flags@2.0.11
| | `-- user-home@1.1.1
| `-- vinyl-fs@0.3.14
|   +-- defaults@1.0.3
|   | `-- clone@1.0.2
|   +-- glob-stream@3.1.18
|   | +-- glob@4.5.3
|   | | `-- inflight@1.0.5
|   | +-- glob2base@0.0.12
|   | | `-- find-index@0.1.1
|   | +-- minimatch@2.0.10
|   | | `-- brace-expansion@1.1.6
|   | |   +-- balanced-match@0.4.2
|   | |   `-- concat-map@0.0.1
|   | +-- ordered-read-streams@0.1.0
|   | +-- through2@0.6.5
|   | | `-- readable-stream@1.0.34
|   | `-- unique-stream@1.0.0
|   +-- glob-watcher@0.0.6
|   | `-- gaze@0.5.2
|   |   `-- globule@0.1.0
|   |     +-- glob@3.1.21
|   |     | +-- graceful-fs@1.2.3
|   |     | `-- inherits@1.0.2
|   |     +-- lodash@1.0.2
|   |     `-- minimatch@0.2.14
|   |       +-- lru-cache@2.7.3
|   |       `-- sigmund@1.0.1
|   +-- graceful-fs@3.0.11
|   | `-- natives@1.1.0
|   +-- mkdirp@0.5.1
|   | `-- minimist@0.0.8
|   +-- strip-bom@1.0.0
|   | +-- first-chunk-stream@1.0.0
|   | `-- is-utf8@0.2.1
|   +-- through2@0.6.5
|   | `-- readable-stream@1.0.34
|   `-- vinyl@0.4.6
|     `-- clone@0.2.0
+-- gulp-concat@2.6.0
| +-- concat-with-sourcemaps@1.0.4
| | `-- source-map@0.5.6
| `-- through2@0.6.5
|   +-- readable-stream@1.0.34
|   | +-- core-util-is@1.0.2
|   | +-- inherits@2.0.3
|   | +-- isarray@0.0.1
|   | `-- string_decoder@0.10.31
|   `-- xtend@4.0.1
+-- gulp-minify-css@0.3.13
| +-- bufferstreams@0.0.2
| | `-- readable-stream@1.1.14
| +-- clean-css@3.0.10
| | +-- commander@2.5.1
| | `-- source-map@0.1.43
| |   `-- amdefine@1.0.0
| +-- memory-cache@0.0.5
| +-- through2@0.6.5
| | `-- readable-stream@1.0.34
| `-- vinyl-sourcemaps-apply@0.1.4
|   `-- source-map@0.1.43
+-- gulp-rename@1.2.2
+-- gulp-util@2.2.20
| +-- chalk@0.5.1
| | +-- ansi-styles@1.1.0
| | +-- has-ansi@0.1.0
| | | `-- ansi-regex@0.2.1
| | +-- strip-ansi@0.3.0
| | `-- supports-color@0.2.0
| +-- dateformat@1.0.12
| | +-- get-stdin@4.0.1
| | `-- meow@3.7.0
| |   +-- camelcase-keys@2.1.0
| |   | `-- camelcase@2.1.1
| |   +-- decamelize@1.2.0
| |   +-- loud-rejection@1.6.0
| |   | +-- currently-unhandled@0.4.1
| |   | | `-- array-find-index@1.0.1
| |   | `-- signal-exit@3.0.1
| |   +-- map-obj@1.0.1
| |   +-- normalize-package-data@2.3.5
| |   | +-- hosted-git-info@2.1.5
| |   | +-- is-builtin-module@1.0.0
| |   | | `-- builtin-modules@1.1.1
| |   | `-- validate-npm-package-license@3.0.1
| |   |   +-- spdx-correct@1.0.2
| |   |   | `-- spdx-license-ids@1.2.2
| |   |   `-- spdx-expression-parse@1.0.3
| |   +-- object-assign@4.1.0
| |   +-- read-pkg-up@1.0.1
| |   | +-- find-up@1.1.2
| |   | | +-- path-exists@2.1.0
| |   | | `-- pinkie-promise@2.0.1
| |   | |   `-- pinkie@2.0.4
| |   | `-- read-pkg@1.1.0
| |   |   +-- load-json-file@1.1.0
| |   |   | +-- graceful-fs@4.1.8
| |   |   | +-- parse-json@2.2.0
| |   |   | | `-- error-ex@1.3.0
| |   |   | |   `-- is-arrayish@0.2.1
| |   |   | +-- pify@2.3.0
| |   |   | `-- strip-bom@2.0.0
| |   |   `-- path-type@1.1.0
| |   +-- redent@1.0.0
| |   | +-- indent-string@2.1.0
| |   | | `-- repeating@2.0.1
| |   | |   `-- is-finite@1.0.1
| |   | |     `-- number-is-nan@1.0.0
| |   | `-- strip-indent@1.0.1
| |   `-- trim-newlines@1.0.0
| +-- lodash._reinterpolate@2.4.1
| +-- lodash.template@2.4.1
| | +-- lodash._escapestringchar@2.4.1
| | +-- lodash.defaults@2.4.1
| | | `-- lodash._objecttypes@2.4.1
| | +-- lodash.escape@2.4.1
| | | +-- lodash._escapehtmlchar@2.4.1
| | | | `-- lodash._htmlescapes@2.4.1
| | | `-- lodash._reunescapedhtml@2.4.1
| | +-- lodash.keys@2.4.1
| | | +-- lodash._isnative@2.4.1
| | | +-- lodash._shimkeys@2.4.1
| | | `-- lodash.isobject@2.4.1
| | +-- lodash.templatesettings@2.4.1
| | `-- lodash.values@2.4.1
| +-- minimist@0.2.0
| +-- multipipe@0.1.2
| | `-- duplexer2@0.0.2
| +-- through2@0.5.1
| | +-- readable-stream@1.0.34
| | `-- xtend@3.0.0
| `-- vinyl@0.2.3
|   `-- clone-stats@0.0.1
`-- shelljs@0.3.0


npm WARN ionic-project@1.1.1 No repository field.
npm WARN ionic-project@1.1.1 No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\workspace\\tools\\nodejs\\node.exe" "C:\\workspace\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.10.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\proyectos\demoApp\npm-debug.log

Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Thanks in advanced!!

**Comment by jthoms1** [comment]
For those experiencing this issue passing the `--verbose` can provide insight into what might be failing.

@varios983 It looks like node-sass is failing to compile on your system. It looks like they released a new version of it today so could you please try running the command again.

Thanks!

**Comment by zsc123400** [comment]
I gave up the new version.

**Comment by varios983** [comment]
Thank you @jthoms1.
I have reinstalled ionic and there is no problem. It was a problem with the old version of ionic.
