### ISSUE TITLE
Changes of templates are ignored during buildUpdate

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1413]
_From @olostan on September 26, 2016 16:16_

ionic 2.1.0-beta.2

When I run `ionic serve`, everything works ok until i change templates - app reloads, but templates are without my changes. Only stopping `ionic serve` and run again helps… making development process extremely slow

Seems `ng-template` plugin is not re-run or does not receive changes of templates.

_Copied from original issue: driftyco/ionic#8216_

**Comment by olostan** [comment]
The only workaround I've found is to disable `rollup` cache in `@ionic/app-scripts/dist/bundle.js` (bundleApp function) by commenting:
```
bundleCache = bundle;
```

**Comment by cozzbie** [comment]
+1

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#260
