### ISSUE TITLE
'ionic/app-generators' is not in the npm registry

### ISSUE THREAD

**Issue by feldi88** [driftyco/ionic-cli#1416]
Since the last version, I have problems to install the ionic-cli. It seems that the newly added dependendy (@ionic/app-generators) makes the troubles:

After running `npm install -g ionic-cli` I get the following error:
```
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'ionic/app-generators' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

And by directly installing the package with  `npm i -g @ionic/app-generators` I get

```
npm ERR! git clone git@github.com:ionic/app-generators Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-ionic-app-generators-4a008aa7'...
npm ERR! git clone git@github.com:ionic/app-generators Permission denied (publickey).
npm ERR! git clone git@github.com:ionic/app-generators fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:ionic/app-generators
npm ERR! git clone git@github.com:ionic/app-generators Please make sure you have the correct access rights
npm ERR! git clone git@github.com:ionic/app-generators and the repository exists.
npm ERR! addLocal Could not install ionic/app-generators
npm ERR! Error: ENOENT, stat 'ionic/app-generators'
```

Can you check it and please correct the package.json? Thanks in advance!

**Comment by jthoms1** [comment]
You are most likely using a version of npm older than 2.7. This was the release that introduced scoped packages.  Try updating to a new version of node 4+ or just install the latest NPM.

npm install npm -g

**Comment by knasim** [comment]
updated to new version of node.  same issue.

npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code E404

npm ERR! 404 no such package available : @ionic/app-generators
npm ERR! 404 
npm ERR! 404  '@ionic/app-generators' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by warptec** [comment]
Downgrading npm from 3.10.8 to 3.10.7 solves this problem.

sudo npm install -g npm@latest-2
sudo npm install -g npm@3.10.7

**Comment by Ulfasaar** [comment]
Me too I have also tried to install the latest version of npm which didn't seem to do anything and I could install scoped packages for typescript perfectly fine using npm 2.15.9

**Comment by MelleI** [comment]
Several things tried. But still the same error:

```
npm install -g ionic
```

```
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 not found : @ionic/app-generators
npm ERR! 404
npm ERR! 404  '@ionic/app-generators' is not in the npm registry.
```

Someone an idea how to fix this?

**Comment by borgespires** [comment]
I am experiencing the same problem. What is the solution?

**Comment by knasim** [comment]
it is my opinion that these "generators" cannot offer native speed.

**Comment by luqni** [comment]
npm install npm -g

**Comment by remisture** [comment]
`npm install npm -g` does not help for me. Nor `sudo npm install -g npm@3.10.7`.

Any ideas?

**Comment by knasim** [comment]
best thing is to go native - such generators will not scale when you get into performance concerns. 
they maybe good for prototyping - but that's it.  otherwise go native.

**Comment by rbecheras** [comment]
Are you using a Sinopia private npm registry as a front of the public npm registry ?

If so, a bug in Sinopia make fail the download because of the `@` in the package path.

Configure your npm client to force using the public npm registry for this package:

     npm config set "@ionic:registry" http://registry.npmjs.org/


Source: https://github.com/rlidwka/sinopia/issues/431#issuecomment-274297632

**Comment by theCrius** [comment]
rbecheras your suggestion was correct. However now I step into a different issue:

```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! code E404
npm ERR! 404 Not Found: @types/gulp@^3.8.33

```
Simply add also @types to the user config

`npm config set "@types:registry" http://registry.npmjs.org/`

In the end with `npm config list` you should have something like this:
```
[...]
; userconfig /home/<your_username>/.npmrc
@ionic:registry = "http://registry.npmjs.org/"
@types:registry = "http://registry.npmjs.org/"
[...]
```

This is somewhat obvious but could help newcomers as a confirmation of what to do :)
