### ISSUE TITLE
Gulpfile.js missing in ionic2-app-base project

### ISSUE THREAD

**Issue by AamirAli310** [driftyco/ionic-cli#1418]
Hi All,

i wanted to kick-start enterprise project to manage its directory structure etc, I gone-through almost all wrappers of gulp-tasks as well as project structures. Yesterday I was able to run and modified both myApp & MySlidemenu projects through directly gulp build & ionic build options. 

Now while i finalised my paper-work and going to taking base project "https://github.com/driftyco/ionic2-app-base" but it was unfortunately/fortunately updated to encapsulate package.json dependencies and gulpfile.js file totally missed.

Project still can produce ios build but without including anything of the app because there is no gulp tasks.

Any alternative??? Or should i start with old version of ionic-2-base project template i taken yesterday and then manually upgrading on latest format?

Kindly see the attachment for more details.
<img width="312" alt="screen shot 2016-09-28 at 12 05 05 pm" src="https://cloud.githubusercontent.com/assets/204746/18905499/78a242ca-8574-11e6-9bbb-37049333ed59.png">
<img width="358" alt="screen shot 2016-09-28 at 12 07 23 pm" src="https://cloud.githubusercontent.com/assets/204746/18905541/b3d916c0-8574-11e6-9262-84844e29020a.png">
<img width="356" alt="screen shot 2016-09-28 at 12 10 55 pm" src="https://cloud.githubusercontent.com/assets/204746/18905542/b3df8dac-8574-11e6-83fd-f6c6c9502331.png">

Looking forward for a quick response.

Regards!
Aamir Ali

**Comment by AamirAli310** [comment]
XCode Project:

<img width="336" alt="screen shot 2016-09-28 at 12 11 22 pm" src="https://cloud.githubusercontent.com/assets/204746/18905572/dff9380c-8574-11e6-83c5-92152e16afa0.png">

**Comment by chsakell** [comment]
+1

**Comment by razvantomegea** [comment]
+1

**Comment by larssn** [comment]
@chsakell @razvantomegea 
The emote function is there for a reason, use it please.
No need to clutter topics with needless +1's.

Sorry for creating more clutter. :(

**Comment by danbucholtz** [comment]
We no longer use gulp in the project as of Ionic 2 RC, which launched yesterday.  Gulp can still be used but we recommend moving to npm scripts.  You'll still use `ionic serve`, `ionic run`, `ionic build`, `ionic start`, etc.

Thanks,
Dan

**Comment by AamirAli310** [comment]
Thanks @danbucholtz  Yup i reviewed app-base project at github and there are npm run build. 
It works (Y)
