### ISSUE TITLE
ionic-cli fails to install

### ISSUE THREAD

**Issue by chsakell** [driftyco/ionic-cli#1419]
``` npm install -g ionic@beta ``` fails reporting 

ERR! enoent: no such file or directory, rename 'C:\Users\myuser\AppData\Roaming\npm\node_modules\ionic\node_modules\cordova-lib\node_modules\ansi'

```
node v6.2.0
npm v3.9.2
```
```npm install -g cordova``` have finished successfully. 
 Of course cannot create a new project normaly, missing gulp file etc, but I guess firstly I need to install the cli properly. Any ideas?

**Comment by joshuamorony** [comment]
I had the same issue, try running:

`npm uninstall -g ionic`
`npm cahce clean`

and then try installing again. Also, dont use the @beta version anymore, use:

`npm install -g ionic`

**Comment by chsakell** [comment]
That did the job, thanks @joshuamorony

**Comment by murshid1988** [comment]
Thanks @joshuamorony, worked for me as well.
