### ISSUE TITLE
ionic-cli error when compiling after awhile

### ISSUE THREAD

**Issue by Bandito11** [driftyco/ionic-cli#1426]
I use the 'ionic serve' and run the app and it does fine on the browser. After editing the app files this tends to happen. It says "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory'.

I am using ionic 2.1.0 , cordova 6.3.1, node 6.6.0, and npm 3.10.3 on Windows 10 using VS Code.

I attached a screen shot with the problem. 

![2016-09-28 1](https://cloud.githubusercontent.com/assets/9807561/18938462/b12b850a-85c6-11e6-948c-b472126482e2.png)

**Comment by Bandito11** [comment]
This has happened to me 3 times after doing all the steps to upgrade today. I uninstall the beta and install the new version .

**Comment by jthoms1** [comment]
This issue has being resolved under driftyco/ionic-app-lib#44. It will be fixed in the next release of app-lib.
