### ISSUE TITLE
 error with the spawned command: npminstall

### ISSUE THREAD

**Issue by bazigatabassum** [driftyco/ionic-cli#1428]
ionic start ExampleProject blank --v2

Creating Ionic app in folder C:\UsersDELL\ExampleProject based on bla
nk project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zip

[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Kindly suggest the stable version to work on further....

**Comment by meeximum** [comment]
same as #1424

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by huichogil** [comment]
same problem

**Comment by bazigatabassum** [comment]
here is the info regarding ionuc 
Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v6.3.1

**Comment by DoFabien** [comment]
Hi.
You can use "verbose" option (--verbose)
You use CMD? 
You have to have Git installed. You can use "Git Shell" for exemple.

**Comment by bazigatabassum** [comment]
i tried with --verbose but same issue exist.. 
yes i do use cmd ...
will it work with git?

**Comment by DoFabien** [comment]
Yes it work with _Git Shell_ for me.

With cmd (--verbose) I have this message : 
`npm ERR!
 not found: git`

**Comment by ramonornela** [comment]
Related #1440

**Comment by ramonornela** [comment]
See step 2 https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0

Thanks

**Comment by hasimashari** [comment]
ionic info

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 7 SP1
Node Version: v6.7.0

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
