### ISSUE TITLE
npm ERR! 404 'ionic' is not in the npm registry.

### ISSUE THREAD

**Issue by megamind79** [driftyco/ionic-cli#1432]
When I tried to run 

> **npm install -g ionic**

, I'm getting the following error:

```
npm http GET https://registry.npmjs.org/ionic
npm http 304 https://registry.npmjs.org/ionic
npm http GET https://registry.npmjs.org/ionic/app-generators/0.0.3
npm http 404 https://registry.npmjs.org/ionic/app-generators/0.0.3
npm ERR! 404 'ionic' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.2.0-42-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ionic"
npm ERR! cwd /home/Megamind
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/Megamind/npm-debug.log
npm ERR! not ok code 0

```
How to install ionic the right way?

**Comment by jthoms1** [comment]
Not sure why you would receive this error. https://www.npmjs.com/package/ionic

Could you try again? Also you should upgrade your NodeJS instance to something more recent like v4.

**Comment by jthoms1** [comment]
It appears that NPM scoped packages where not introduced until NPM v2.7.0.  This is why you were receiving the error. An upgrade to NodeJS later than 12.2 will resolve the issue or you could just update npm to the latest.

Thanks for reporting this!

**Comment by megamind79** [comment]
Is there some way to use ionic, if I installed it using zip file from clone/download link, without updating nodejs?
But after I did the above step, if I run ionic, it gives "ionic command not found".

**Comment by captainZ3ro** [comment]
same issue. already updated Node.js and npm.

**Comment by knasim** [comment]
same issue for me as well.  upgrade node/npm.  still getting the following:

npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code E404

npm ERR! 404 no such package available : @ionic/app-generators
npm ERR! 404 
npm ERR! 404  '@ionic/app-generators' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Diegow3b** [comment]
Same error with lastest version of node js and npm

npm http GET https://registry.npmjs.org/ionic                                                          
npm http 304 https://registry.npmjs.org/ionic                                                          
npm http GET https://registry.npmjs.org/ionic/app-generators/0.0.3                                     
npm http 404 https://registry.npmjs.org/ionic/app-generators/0.0.3                                     
npm ERR! 404 'ionic' is not in the npm registry.                                                       
npm ERR! 404 You should bug the author to publish it                                                   
npm ERR! 404                                                                                           
npm ERR! 404 Note that you can also install from a                                                     
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by moyeen52** [comment]
Not sure sudo npm install -g ionic-framework gives no 404.

**Comment by paul-landaeta-tierconnect-com** [comment]
I installed "**npm install -g cordova ionic**" it's working

**Comment by paul-landaeta-tierconnect-com** [comment]
I update my node. it's working Now

**Comment by GogetitLDM** [comment]
Is this possible?
When I try to install it says that my current node version is 0.10.48.
But when I do a "node -v" I get 9.3.0
ec2-user:~/environment $ sudo npm install -g ionic
npm http GET https://registry.npmjs.org/ionic
npm http 304 https://registry.npmjs.org/ionic
npm WARN engine ionic@3.19.0: wanted: {"node":">=6.4.0"} (current: {"node":"v0.10.48","npm":"1.3.6"})
npm http GET https://registry.npmjs.org/ionic/cli-framework/0.1.2
npm http GET https://registry.npmjs.org/ionic/cli-utils/1.19.0
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/opn
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/tslib
npm http 304 https://registry.npmjs.org/opn
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/tslib
npm http 404 https://registry.npmjs.org/ionic/cli-framework/0.1.2
npm ERR! 404 'ionic' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.51-10.52.amzn1.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "ionic"
npm ERR! cwd /home/ec2-user/environment
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! code E404
npm http 404 https://registry.npmjs.org/ionic/cli-utils/1.19.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ec2-user/environment/npm-debug.log
npm ERR! not ok code 0
ec2-user:~/environment $ node -v
v9.3.0

**Comment by dwieeb** [comment]
@GogetitLDM what about `sudo node -v`?
