### ISSUE TITLE
There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by wjjxyz2006** [driftyco/ionic-cli#1440]

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by FaisalAriyanto** [comment]
i have same problem when start new project after instal ionic rc0
Cordova CLI: 6.3.0                                                                                                        
Ionic CLI Version: 2.1.0                                                                                                  
Ionic App Lib Version: 2.1.0-beta.1                                                                                       
OS: Windows 8.1                                                                                                           
Node Version: v6.7.0

**Comment by srikanth748** [comment]
I too have the same problem when starting a new ionic project with cmd: ionic start --v2 firstapp

Cordova Cli :6.3.1
Ionic Cli Version: 2.1.0
Ionic App Lib Version : 2.0.0-beta.20
OS :Windows 7 SP1
Node Version : v4.6.0

Suggest me a solution to fix this error. Thanks

**Comment by srikanth748** [comment]
I tired installing git tools and and in the git cmd i ran the same cmd commands to build ionic app but now i get a different error.
[gitcmd_errorlog.pdf](https://github.com/driftyco/ionic-cli/files/503511/gitcmd_errorlog.pdf)

**Comment by srikanth748** [comment]
I tried installing Git tools and run the same commands to develop ionic2 project but this it gives me a new kind of error.
[gitcmd_errorlog.pdf](https://github.com/driftyco/ionic-cli/files/503515/gitcmd_errorlog.pdf)

**Comment by jthoms1** [comment]
@srikanth748 Did you remember to run `npm install` first within the new project directory? Thanks.

**Comment by srikanth748** [comment]
Yes i tried to install all the npm modules that is asked manually but now the error says build failed .

**Comment by jthoms1** [comment]
Could you provide me with the output of the `npm install` command?

**Comment by srikanth748** [comment]
Oofff ..I tried to create a new project and then everything went perfect .The only thing i did was to execute npm install -g npm before I went to my project folder.
Then when i executed npm start --v2 appname ,then it built all the node_modules which i was missing some of modules before.
so finally I could  build my firstapp with ionic RC.
thanks for your guidance @jthoms1

**Comment by ramonornela** [comment]
@wjjxyz2006 @FaisalAriyanto @srikanth748  run step 2 https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0?

Thanks

**Comment by jthoms1** [comment]
cool, Thanks!
