### ISSUE TITLE
Ionic serve not refresh correctly!

### ISSUE THREAD

**Issue by gholami-mohammad** [driftyco/ionic-cli#1443]
After update to ionic-cli 2.1.0 , `ionic serve` command start web server but main.js and main.css not created and It cannot refresh files correctly after making changes on any files! Each time I must to run `ionic build ` to apply changes!

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by gholami-mohammad** [comment]
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 8.0 Build version 8A218a 


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

**Comment by jthoms1** [comment]
If you are transitioning a current project to rc0 please be sure to follow the upgrade guide.

https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#steps-to-upgrade-to-rc0

**Comment by gholami-mohammad** [comment]
I removed my ionic last night and reinstalled this version and then create my project! After installing new cli , ionic serve not works correctly!

**Comment by jthoms1** [comment]
Awesome, Thanks for following up with us!
