### ISSUE TITLE
ionic-cli 2.1.0 fails to install

### ISSUE THREAD

**Issue by faraazc** [driftyco/ionic-cli#1449]
Faraazs-MacBook-Pro:Downloads faraazc$ sudo npm install ionic -g
Password:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ionic" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for /tmp/npm-2755-c080be4a/registry.npmjs.org/ionic/-/ionic-2.1.0.tgz
npm ERR! Expected: cc4218ec13f31b635c1119c9defae5b2bad31335
npm ERR! Actual:   820e454219064310e1aa898efed6a1ef39584d21
npm ERR! From:     https://registry.npmjs.org/ionic/-/ionic-2.1.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by hounsellal** [comment]
upgrade node to 6 and try again

**Comment by faraazc** [comment]
@hounsellal thanks upgraded and it worked.
