### ISSUE TITLE
ionic start works once in 5 attempts 

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic-cli#145]
This is not a ionic-cli bug but something to do with github whenever i ```ionic start``` i get following error
```javascript
Error: Unable to initalize app:  { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
```

but after multiple attempts i can manage to get it done successfully 

i think this has to something github not responding 

and 

secondly downloading bare projects every time is waste of bandwidth and time , so i suggest it should be cached like npm modules and downloaded only if its changed on github.

thankis

**Comment by jbavari** [comment]
Any update?

**Comment by programming-kid** [comment]
i tried creating 3 different project  all were :+1: A Ok, i thinks it safe to close this issue for now

**Comment by wiii** [comment]
Solution

In the File   'C:\Users\[username]\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js'

Add the line
self.proxy = ' http://proxy.com:port ' ;

Just comom to in step 1 of the following link
http://jasonwatmore.com/post/2014/04/02/Ionic-Framework-Getting-ionic-start-appName-Working-Behind-a-Proxy.aspx

Regards
