### ISSUE TITLE
ionic package iOS IPA size and cordova logo

### ISSUE THREAD

**Issue by anilcancakir** [driftyco/ionic-cli#1450]
Ionic package build ends successfully, but as we download the IPA file which is about %60 smaller than straight IPA and i only can see this Apache Cordova Logo after the splash-screen. Please find the system info I already use.

Since this issue stops our development plan we’re waiting forward for hearing your response asap.

There are some guys started to face the same issue for 2 days at the forum. eg.
https://forum.ionicframework.com/t/ionic-package-ios-build-fails-development-team-required/65033 @mlynch

**Comment by mikael-dk** [comment]
This is a major issue for us as well (I already posted details in the other thread).

**Comment by mlynch** [comment]
Hey all, please see my response here: https://forum.ionicframework.com/t/ionic-package-ios-build-fails-development-team-required/65033/15?u=max

Closing this on ionic-cli and moving to ionic-cloud-issues repo: https://github.com/driftyco/ionic-cloud-issues/issues/197
