### ISSUE TITLE
ionic run android fails to bui main.js not built

### ISSUE THREAD

**Issue by gregor-srdic** [driftyco/ionic-cli#1454]
Running the **ionic build command** 

file:///android_asset/www/build/main.js 
Failed to load resource: net::ERR_FILE_NOT_FOUND

I have some typscript related issues in the code - due to imports and type inconsistencies, but ionic serve works, and also **ionic build works if the ionic serve is active**.

[screenshot of the error](https://s12.postimg.org/z80dkcq65/2016_10_03_11_56_43.png)

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v4.6.0

**Comment by pantonis** [comment]
I have exactly the same problem. Did you manager to resolve it?

**Comment by gregor-srdic** [comment]
it seems building for android is much more sensitive to typescript errors and warnings and therefore the build failed. After I fixed the inconsistencies in my code, I got it working.

**Comment by pantonis** [comment]
Yes I saw that. Good this that they are improving the error messages in ngc as they wrote in the Ionic weekly notes
