### ISSUE TITLE
ionic start project failed to install node packages

### ISSUE THREAD

**Issue by mrcprasad** [driftyco/ionic-cli#1455]
I tried creating a new project using ionic 2. I got the below error:

C:\Users\ramukala\Desktop\ionic>ionic start sampleTutorial --v2
Directory already exists: C:\Users\ramukala\Desktop\ionic\sampleTutorial
Would you like to overwrite the directory with this new project?
(yes/no): y

Creating Ionic app in folder C:\Users\ramukala\Desktop\ionic\sampleTutorial base
d on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

My npm version is 3.10.8
node version : v4.6.0
ionic beta version. 

Share a possible work around ASAP.

**Comment by jthoms1** [comment]
Closing this as a duplicate. Please see #1445.  The quick fix is to cd into the new created directory and just run `npm install` manually.

Thanks!

**Comment by mrcprasad** [comment]
thomas I installed git as per the ticket 1445. And after I created a project and did cd into project, tried installing npm install manually. Now I am getting git not found error. Share a possible solution for this.
