### ISSUE TITLE
failure to install ionic --v2

### ISSUE THREAD

**Issue by hasimashari** [driftyco/ionic-cli#1461]
ionic start MyIonic2Project tutorial --v2
Creating Ionic app in folder D:\cmder_mini\config\profile.d\MyIonic2Project based on tutorial project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tutorial/archive/master.zip [=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by klaus-kuplen** [comment]
I had the exact same issue, a hint here solved it: https://github.com/driftyco/ionic-cli/issues/1463

Try to install Git for Windows.

**Comment by hasimashari** [comment]
they still fail

**Comment by Gope** [comment]
Hello,
I get the same error on the mac platform. Just installed the default git package. Problem still occurs... Any ideas? Thanks!

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
