### ISSUE TITLE
`ionic start` command should not install npm dependencies itself

### ISSUE THREAD

**Issue by jdat82** [driftyco/ionic-cli#1466]
Just a remark here, but I find it unfortunate that the `ionic start` command execute itself the `npm install` command that install all npm dependencies. Its job should be to generate code, not install all dependencies. It would be more align with the single responsibility principle. 

`npm install` is a single line command that we can type next after generating the project. I say that because it makes the execution time very long especially on slow networks which can be very frustrating if you want to execute it several times for instance to see generated code for several templates or with different options. 

Just because you generate code doesn't mean you will execute it.

**Comment by jthoms1** [comment]
This is a feature of the ionic start command.  If you would like to get started without using this you could just visit the base application starters directly on github.

https://github.com/driftyco/ionic2-app-base
https://github.com/driftyco?utf8=%E2%9C%93&query=ionic2-start
