### ISSUE TITLE
Error running Ionic Start

### ISSUE THREAD

**Issue by unboxedsolutions** [driftyco/ionic-cli#1471]
ionic start Ionic2Test2 -ts -v2

Creating Ionic app in folder C:\winning\Ionic2Test2 based on  project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Error with start TypeError: options.template.indexOf is not a function
    at Object.Start.fetchSeed (C:\Users\bob\AppData\Roaming\nvm\v6.3.1\node_modules\ionic\node_modules\ionic-app-lib\lib\start.js:245:25)

**Comment by doylestowncoder** [comment]
I am also having an issue running Ionic start.  I am running on Windows 10. Any ideas what could be wrong?  


C:\Dev\ionicProjects>ionic info

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0



C:\Dev\ionicProjects>ionic start --v2 myApp
Creating Ionic app in folder C:\Dev\ionicProjects\myApp based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues


C:\Dev\ionicProjects>

**Comment by doylestowncoder** [comment]
After several hours of trying many things, I finally got this to work.  I had to install git.  Once I did this, then I could run ionic start --v2 without issues.

See https://git-for-windows.github.io/

BUT remember, I am running on Windows 10.  Not sure about a Mac.

**Comment by zgji957** [comment]
@doylestowncoder thank you,i made it

**Comment by jgw96** [comment]
@unboxedsolutions does installing git fix the issues for you?

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
