### ISSUE TITLE
Issue with building ios version 

### ISSUE THREAD

**Issue by TimothyKrajewski** [driftyco/ionic-cli#1474]
Here the error log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.8
3 info using node@v4.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle test2@~prebuild: test2@
6 silly lifecycle test2@~prebuild: no script for prebuild, continuing
7 info lifecycle test2@~build: test2@
8 verbose lifecycle test2@~build: unsafe-perm in lifecycle true
9 verbose lifecycle test2@~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/TimKrajewski/TimsDrive/TimCollegeDrive/CSC498Capstone/Test2/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin
10 verbose lifecycle test2@~build: CWD: /Users/TimKrajewski/TimsDrive/TimCollegeDrive/CSC498Capstone/Test2
11 silly lifecycle test2@~build: Args: [ '-c', 'ionic-app-scripts build' ]
12 silly lifecycle test2@~build: Returned: code: 1  signal: null
13 info lifecycle test2@~build: Failed to exec build script
14 verbose stack Error: test2@ build: `ionic-app-scripts build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid test2@
16 verbose cwd /Users/TimKrajewski/TimsDrive/TimCollegeDrive/CSC498Capstone/Test2
17 error Darwin 16.0.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v4.5.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error test2@ build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the test2@ build script 'ionic-app-scripts build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ionic-app-scripts build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

I had to change the permissions of the hooks folder with chmod +x hooks/after_prepare/010_add_platform_class.js of the app just to run the command then it still failed

**Comment by cjdreiss** [comment]
just started getting a similar issue.  my app was building last night, going to try rolling back some changes in my app to see if it helps.  ionic serve runs fine and my app functions.

**Comment by cjdreiss** [comment]
So, the actual error didn't show up in the npm log file.

I scrolled up a bit more and saw that the `ngc` process was failing, and complaining that I had something set to private 
```
ngc: Error: Error at /Users/USER/Sites/enterprise-demo/.tmp/pages/dashboard/dashboard.ngfactory.ts:1919:42: Property 'pagesService' is private and only accessible within class 'DashboardPage'.
```

I set that to public and I'm good to go again.

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#257
