### ISSUE TITLE
Error installing npm packages with ionic 2

### ISSUE THREAD

**Issue by cdodge89** [driftyco/ionic-cli#1485]
I wanted to do a tutorial on Ionic 2 from http://gonehybrid.com/build-your-first-mobile-app-with-ionic-2-angular-2-part-5/ but when I ran the first command I got an error as it tried automatically install npm packages. the npm-debug log is attached and as a side note it also downloaded 568 package.json files https://www.dropbox.com/s/hcomjmphdvdh9m6/Screenshot%202016-10-06%2017.50.06.png?dl=0
[npm-debug.txt](https://github.com/driftyco/ionic-cli/files/515008/npm-debug.txt)

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
