### ISSUE TITLE
Ionic RC0 - sidemenu starter template error

### ISSUE THREAD

**Issue by fbenedetto** [driftyco/ionic-cli#1487]
I have following errors when I try to start a new project using _sidemenu_ starter template:

`Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined`

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

Also could you please rerun this command using the `--verbose` flag and provide the output.

**Comment by fbenedetto** [comment]
I've just reinstalled cordova, ionic and typescript and the problem seems to be solved
