### ISSUE TITLE
Firebase ionic2 and rollup - “rollup: Use of `eval` is strongly discouraged”

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic-cli#1500]
i  have configured AngularFire2 according to this blog post: [https://javebratt.com/ionic-2-firebase-3-facebook/](url)
i'm getting this error

> rollup: Use ofeval(in c:\XXX\node_modules\angularfire2\node_modules\firebase\firebase.js) is strongly discouraged, as it poses security risks and may cause issues with minification. See https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval for more details

this is my source code
`console.log("I'm the Hulk");// for test

var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');

// https://github.com/rollup/rollup/wiki/JavaScript-API

```
var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: 'src/app/main.dev.ts',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',

  useStrict: false,
  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    builtins(),
    commonjs({
      include: [
        'node_modules/rxjs/**', // firebase needs rxjs to avoid build errors
        'node_modules/firebase/**', // here we're calling firebase.
        'node_modules/angularfire2/**' // here we're calling angularfire2.
      ],
      namedExports: {
        'node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
        'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database']
      }
    }),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};


if (process.env.IONIC_ENV == 'prod') {
  // production mode
  rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
  rollupConfig.sourceMap = false;
}


module.exports = rollupConfig;`

```

**Comment by balasivagnanam** [comment]
I also tried to do this, with whatever I researched looks like firebase library need to change from using eval in their  JS library, what ever you are using above is a temporary fix.

**Comment by jgw96** [comment]
Hello everyone, thanks for opening an issue with us! This is unfortunately an issue in the firebase library that AngularFire2 depends on. They are aware of the issue and we are hoping that it is fixed soon. While this warning is scary (as it should be, usage of eval has a'lot of security issues) your app should continue to build and work with no problem. Since this is not an Ionic issue, but instead a Firebase issue I am going to close this issue for now. Thanks!
