### ISSUE TITLE
Getting Error when running ionic start todo blank

### ISSUE THREAD

**Issue by harshapenikalapati** [driftyco/ionic-cli#1501]
I am getting the below error when trying to create a sample Application using ionic framework. Used the below command.

ionic start todo blank and got the below error message.

I installed both Ionic and Cordova using npm manager.
Caught exception:
 Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\peniha01\AppData\Roaming\npm\node_modules\ionic\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by ataraxus** [comment]
please provide `ionic info` and `npm -v` ouptut

**Comment by harshapenikalapati** [comment]
Hi When I ran the above commands I get the below response.

**_ionic info:_**

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS: Windows 8.1
Node Version: v6.7.0

**_npm -v:_**
3.10.3

**Comment by harshapenikalapati** [comment]
Hi ,

The above is fixed and am able to create a sample application with ionic start. 

Now the second issue am facing is when trying to run this command **_ionic build android_** getting the below error.


**Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.**

Before building the android app i have ran the below command and it ran successfully without any errors

**_ionic platform add android_**

**Comment by jgw96** [comment]
Hello @harshapenikalapati , great to hear that your first issue is fixed! For the new issue you are facing i would recommend taking a look at [these docs](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html). Those will show you how to set the `ANDROID_HOME` env variable that is needed for cordova. Thanks!
