### ISSUE TITLE
using bcryptjs with rc0 breaks bootstrapping

### ISSUE THREAD

**Issue by ataraxus** [driftyco/ionic-cli#1503]
Hello, 

I recently migrated my project to the new rc0 release. With this release a prior working npm package now breaks startup of the app. 

To reproduce: 

```
ionic start vanilla tutorial --v2
npm install bcryptjs @types/bcryptjs
```

then import and use bcrypt: 

```
import { Component } from '@angular/core';
import bc from 'bcryptjs'

@Component({
  templateUrl: 'hello-ionic.html'
})
export class HelloIonicPage {
  constructor() {
    bc.hashSync("secret", bc.genSaltSync());
  }
}
```
and you'll get an error in des.js
```
des.js:7                   Uncaught TypeError: Cannot read property 'utils' of undefined
```
which is this line: 

```
'use strict';

var assert = require('minimalistic-assert');
var inherits = require('inherits');

var des = require('../des');
--> var utils = des.utils;
var Cipher = des.Cipher;

function DESState() {
  this.tmp = new Array(2);
  this.keys = null;
}
```

Please note that bcryptjs does not have any dependencies. For whatever reason inclusion of bcryptjs causes des.js to be loaded. if i don't import bcrypt des.js is not executed. 

----- 

```

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.6.0

npm 3.10.8
```

**Comment by ataraxus** [comment]
apparently this issue is somehow tied to the new rollup build tool which has issues with commonjs modules.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Would you mind taking a look at [these docs](http://ionicframework.com/docs/v2/resources/third-party-libs/) and trying a few of the solutions there? Also I am going to move this issue to the ionic-app-scripts repo since this is an app-scripts issue and not a cli issue. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#139
