### ISSUE TITLE
build without ngc

### ISSUE THREAD

**Issue by smkamranqadri** [driftyco/ionic-cli#1504]
is there any way i can build without using ngc as i am getting below error and the auther of lib is working to resolve but will take time.

ngc: Error: Unexpected value 'NgReduxModule' imported by the module 'StoreModule'

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! If you want to build without NGC you can change [this line in your package.json](https://github.com/driftyco/ionic2-app-base/blob/master/package.json#L7) to `ionic-app-scripts build --dev`. Be aware that your app will be slower as it will not be ran through the Angular AoT compiler and the uglify minifier.

**Comment by smkamranqadri** [comment]
hey, thanks a lot. it worked.

**Comment by smkamranqadri** [comment]
hey thanks, it worked.

**Comment by kadox07** [comment]
Waooo! Thanx
