### ISSUE TITLE
Error running '$ ionic serve' command.

### ISSUE THREAD

**Issue by maxdonetsk** [driftyco/ionic-cli#1506]
Hi guys, please help me to figure out with this issue.
I have installed Ionic2 as Tutorial says, ran 'npm install' after cloning and typed 'ionic serve'.
This is what I got in Console:

****************
$ ionic serve

Running 'serve:before' npm script before serve
npm

ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! path D:\wamp\www\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\wamp\www\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'D:\wamp\www\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\wamp\www\npm-debug.log

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
****************

This is what I got in npm-debug.log:

****************
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.8
3 info using node@v4.6.0
4 verbose stack Error: ENOENT: no such file or directory, open 'D:\wamp\www\package.json'
4 verbose stack     at Error (native)
5 verbose cwd D:\wamp\www
6 error Windows_NT 6.1.7601
7 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
8 error node v4.6.0
9 error npm  v3.10.8
10 error path D:\wamp\www\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'D:\wamp\www\package.json'
15 error enoent ENOENT: no such file or directory, open 'D:\wamp\www\package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]
****************

I'll appreciate any help. Thanks!

**Comment by zhangruinian** [comment]
I meet the same problem as you,if you solve it ,please tell me thanks!

**Comment by maxdonetsk** [comment]
zhangruinian,
You can use
$npm run build
to make sure you can work.

**Comment by zhangruinian** [comment]
I use npm install -g node-gyp and installing python, it works

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
