### ISSUE TITLE
Dual LiveReload Refresh for 2.RC0 + SASS project

### ISSUE THREAD

**Issue by MathieuNls** [driftyco/ionic-cli#1512]
Using the 2.1.0 cli serving a ionic 2.rc0 project with SASS (`ionic serve`), I got two livereload induced refresh.

The first refresh is triggered when main.js is transpiled and the second one when the the sass file is compiled. One refresh at the end of the sass process would be enough. It's kind of bothering to have to wait for the second refresh to verify things.

In addition, the sass compilation is triggered even when no .sass file is changed.

```
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

[18:26:19]  bundle dev update started ...
JS changed:   www/build/main.js
[18:26:28]  bundle dev update finished in 8.61 s  **// Refresh signal sent here**
[18:26:28]  sass started ...
[18:26:28]  sass finished in 6 ms  **// Another Refresh signal sent here**
```

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-app-scripts#138

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this is an issue with ionic-app-scripts and not the CLI I have moved this issue to that repo.
