### ISSUE TITLE
Unable to Run Android

### ISSUE THREAD

**Issue by klee0589** [driftyco/ionic-cli#1513]
I am running Genymotion andorid simulator along side ionic and this the npm-debug.log created.

0 info it worked if it ends with ok
1 verbose cli [ '/Users/Kangil/.nvm/versions/node/v4.6.0/bin/node',
1 verbose cli   '/Users/Kangil/.nvm/versions/node/v4.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild mythemeapp@
6 info build mythemeapp@
7 verbose unsafe-perm in lifecycle true
8 info mythemeapp@ Failed to exec build script
9 verbose stack Error: mythemeapp@ build: `ionic-app-scripts build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/Kangil/.nvm/versions/node/v4.6.0/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/Kangil/.nvm/versions/node/v4.6.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid mythemeapp@
11 verbose cwd /Users/Kangil/Desktop/Ionic_tutorial_project/myThemeApp
12 error Darwin 15.6.0
13 error argv "/Users/Kangil/.nvm/versions/node/v4.6.0/bin/node" "/Users/Kangil/.nvm/versions/node/v4.6.0/bin/npm" "run" "build"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error mythemeapp@ build: `ionic-app-scripts build`
17 error Exit status 1
18 error Failed at the mythemeapp@ build script 'ionic-app-scripts build'.
18 error This is most likely a problem with the mythemeapp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ionic-app-scripts build
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs mythemeapp
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls mythemeapp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by hayuki** [comment]
I also have this problem. It's very strange - I created a page with two <div> tags inside <ion-content> on it, and that builds and runs fine. But the moment I add <ion-list> to one of the divs, it breaks with the error shown above.

**Comment by klee0589** [comment]
I was able to getting it working for iOS but still the issue persists with my attempt to emulate Android and running the Genymotion simulator. Here are also my dev environment info:

Cordova CLI: 6.3.1
Gulp version: CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
OS:
Node Version: v6.7.0

**Comment by klee0589** [comment]
Found a solution!

I reverted my Android SDK to 23.0.3 and everything working fine.
Also another thing I had noticed was I had initially added a click method on a button that referenced a function in a class that did not exist. After removing that entirely from the button everything rendered fine in an Android emulator via genymotion.

**Comment by jgw96** [comment]
Hello all! Going to close this one as it seemed to be a genymotion issue and not an Ionic issue. Thanks for using Ionic!
