### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by adsonrocha** [driftyco/ionic-cli#1516]
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by bholub** [comment]
I run into the same; ran with --verbose and got the following additional info (but I'm still not sure how to resolve it):

node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.0.2 wants rxjs@5.0.0-beta.12
npm ERR! peerinvalid Peer @angular/http@2.0.2 wants rxjs@5.0.0-beta.12

**Comment by rhedin** [comment]
Same.

**Comment by sunilachyut** [comment]
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Please retry the command with the `--verbose` flag and it should provide more details.  @bholub this sounds like we have some mismatch in ionic framework.  I will ensure this is addressed in driftyco/ionic.

**Comment by jgw96** [comment]
@bholub Is this with a Could you try upgrading your npm install to npm 3 and trying again? To update to npm 3 you can simply run `npm install -g npm`. Thanks!

**Comment by bholub** [comment]
Updating npm fixed it for me. Thanks!

**Comment by Newan** [comment]
`npm 
ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node
 v4.6.0
npm ERR! npm  v2.15.9

npm ERR! code EPEERINVALID



npm
 ERR! peerinvalid The package rxjs@5.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.0.2 wants rxjs@5.0.0-beta.12

npm ERR! peerinvalid Peer @angular/http@2.0.2 wants rxjs@5.0.0-beta.12



npm ERR! Please include the following file with any support request:
npm ERR!     /Users/newan/myApp/npm-debug.log

Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues`

OSX:
node -v
v4.6.0

ionic-CLI v2.1.0

**Comment by plnkr2015** [comment]
even after updating node version, i am getting above error.

Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

node -v
v4.6.0

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 7 SP1
Node Version: v4.6.0

**Comment by plnkr2015** [comment]
upgrading npm version to 3 fixed the issue. thanks,

**Comment by sunilachyut** [comment]
My issue was due to proxy settings, once I changed the settings its working like a charm.  Thanks jthoms1, your idea of running the command with verbose helped me uncover the network issue.

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
