### ISSUE TITLE
bug: CLI "ionic info" shows incorrect information (macOS Sierra)

### ISSUE THREAD

**Issue by panchazo** [driftyco/ionic-cli#1517]
This seem to happen again (https://github.com/driftyco/ionic-cli/issues/230) in Mac OS Sierra. 
ionic info shows Os X El Capitan instead...

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jthoms1** [comment]
Will be resolved in the pull request waiting in ionic-app-lib. This should be out in the next release.
