### ISSUE TITLE
cli continues building & emulating even after failed compilation

### ISSUE THREAD

**Issue by golear91** [driftyco/ionic-cli#1518]
When I run `ionic run android` and it fails because of a typescript compilation error
the CLI continues running and spawns the emulator/ runs the app in my device.

Why is this?  If it fails to compile shouldn't the entire process just end there? So that I don't have to scroll up through the console output to see that the compile step in fact failed?

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by golear91** [comment]
Your system information:

    Cordova CLI: 6.3.1
    Gulp version:  CLI version 3.9.1
    Gulp local:
    Ionic Framework Version: 2.0.0-rc.0
    Ionic CLI Version: 2.1.0
    Ionic App Lib Version: 2.1.0-beta.1
    OS:
    Node Version: v4.4.7

**Comment by golear91** [comment]
after upgrading to ionic 2.0.0-rc.1 following change log instructions, I am no longer seeing this issue
