### ISSUE TITLE
Feature request: Please make it possible to get files copied to the www folder during build

### ISSUE THREAD

**Issue by ch-weiss** [driftyco/ionic-cli#1519]
The plugin cordoba-plugin-inapppurchase requires a manifest.json file with the Android Billing Key directly in the www folder:
https://github.com/AlexDisler/cordova-plugin-inapppurchase

Now with the changes in the build process of Ionic rc0 the manifest file gets deleted with every build. 

Please make it possible to get files copied to the www folder apart from the asset folder and the index file. Thank you.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! We are discussing making www not get erased everytime a build is done here https://github.com/driftyco/ionic-app-scripts/issues/134 which should fix this issue as you could just put the file in www and not have to worry about it anymore after this. Something you can do in the mean-time is setup a custom `copy.config` to make sure your file gets copied from src to www every time. You can use the `ionic_copy` npm config to point to a custom copy.config file ( [here](https://github.com/driftyco/ionic-app-scripts#npm-config) is a good example of setting up a custom npm property ). In your custom copy.config you can just copy paste [ours](https://github.com/driftyco/ionic-app-scripts/blob/master/config/copy.config.js) and then put in a new entry for your file. `src` is the path to the file in the `src` directory of your app and `dest` is where it should be copied too. Thanks!

**Comment by ch-weiss** [comment]
@jgw96 Thanks for your great support!
