### ISSUE TITLE
Http POST not working

### ISSUE THREAD

**Issue by borntodesign** [driftyco/ionic-cli#1523]
I am making a POST request to Zapier and it works fine in the browser, however when I emulate the app (iOS) it does not work...

It does however log out?

MyIonic2Project[2711]: {"_body":"{\"status\": \"success\", \"attempt\": \"57fe4951-1b0a-4656-bf06-59fb57acb4e0\", \"id\": \"7c1077ad-66d4-47f8-8f9b-473bb297a10a\", \"request_id\": \"u3QSrzNwL6GbrkPp\"}","status":200,"ok":true,"statusText":"OK","headers":{"access-control-allow-origin":["*"],"connection":["keep-alive"],"content-length":["152"],"date":["Wed"," 12 Oct 2016 14:31:45 GMT"],"server":["nginx"],"content-type":["application/json"],"vary":["X-Session-Key"],"x-frame-options":["SAMEORIGIN"],"x-session-key":["anonymous"],"x-zapier-jobs-link":["https://zapier.com/blog/help-automate-business-zapier-jobs-and-careers/"],"response-id":["u3QSrzNwL6GbrkPp"],"x-zapier-jobs":["Woooo"," a hacker like yourself should consider working at Zapier!"],"x-zapier-fast-return":["true"],"p3p":["CP=\"IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT\""]},"type":2,"url":"https://hooks.zapier.com/hooks/catch/1725545/6w4qfk/?name=Dsf&title=Fds&description=Fds&commision=Fds&nameFirst=Kate%20Bell"}

**Comment by jthoms1** [comment]
Could you provide more details?  Are you running `ionic emulate` when this occurs and also could you provide the output of running `ionic info` within your project directory.  Thanks!

**Comment by borntodesign** [comment]
Thanks Josh, it was user error ;)

**Comment by jthoms1** [comment]
Thanks for getting back to us,  glad you got it!
