### ISSUE TITLE
Error running 'ionic serve' command.

### ISSUE THREAD

**Issue by zhangruinian** [driftyco/ionic-cli#1524]
D:\geetest\ionic01>ionic serve

Running 'serve:before' npm script before serve
> ionic-app-base@ watch D:\geetest\ionic01
> ionic-app-scripts watch
module.js:440
    throw err;
    ^

Error: Cannot find module 'D:\geetest\ionic01\node_modules\@ionic\app-scripts\bin\ionic-app-scripts.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3

npm

ERR!
 Windows_NT 10.0.10586

npm
 ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"

npm
 ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! ionic-app-base@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-app-base@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-app-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm
ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\geetest\ionic01\npm-debug.log

Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#264
