### ISSUE TITLE
Error with spawned command npminstall

### ISSUE THREAD

**Issue by jnuic7** [driftyco/ionic-cli#1527]
Just gives an undefined exception so no help there hah.

**Comment by woodyalain** [comment]
I think it's because you don't have the last version of "node.js" !

**Comment by twofb** [comment]
got the same error:

npm@2.15.9 D:\nodejs\node_modules\npm

p:\node>npm install -g ionic
C:\Users\comp\AppData\Roaming\npm\ionic -> C:\Users\comp\AppData\Roaming\npm\node_modules\ionic\bin\ionic
ionic@2.1.0 C:\Users\comp\AppData\Roaming\npm\node_modules\ionic
└── @ionic/app-generators@0.0.3

p:\node>npm install -g cordova
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
C:\Users\comp\AppData\Roaming\npm\cordova -> C:\Users\comp\AppData\Roaming\npm\node_modules\cordova\bin\cordova
cordova@6.3.1 C:\Users\comp\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.9)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, chalk@1.1.3, repeating@1.1.3, configstore@1.4.0, latest-version@1.0.1)
├── cordova-common@1.4.1 (cordova-registry-mapper@1.1.15, unorm@1.4.1, underscore@1.8.3, q@1.4.1, semver@5.3.0, ansi@0.3.1, shelljs@0.5.3, osenv@0.1.3, bplist-parser@0.1.1, glob@5.0.15, minimatch@3.0.3, elementtree@0.1.6, plist@1.2.0)
├── insight@0.8.3 (object-assign@4.1.0, async@1.5.2, tough-cookie@2.3.1, node-uuid@1.4.7, lodash.debounce@3.1.1, chalk@1.1.3, os-name@1.0.3, configstore@1.4.0, inquirer@0.10.1, request@2.75.0)
└── cordova-lib@6.3.1 (valid-identifier@0.0.1, cordova-registry-mapper@1.1.15, opener@1.4.1, unorm@1.3.3, properties-parser@0.2.3, semver@4.3.6, nopt@3.0.6, dep-graph@1.1.0, shelljs@0.3.0, glob@5.0.15, elementtree@0.1.6, request@2.47.0, xcode@0.8.9, cordova-serve@1.0.0, tar@1.0.2, aliasify@1.9.0, init-package-json@1.9.4, cordova-app-hello-world@3.10.0, cordova-fetch@1.0.1, plist@1.2.0, cordova-js@4.1.4, npm@2.15.11)


p:\node>ionic start cutePuppyPics --v2
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************
Creating Ionic app in folder p:\node\cutePuppyPics based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by stefandroog** [comment]
Same here.

Some extra logging

`Creating Ionic app in folder /Users/stefan/Development/MyApp-mobile/MyAppMobile based on tutorial project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tutorial/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Running exec command: npminstall
npm

WARN peerDependencies The peer dependency rxjs@5.0.0-beta.12 included from @angular/http will no

npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency

npm WARN peerDependencies
 in npm 3+. Your application will need to depend on it explicitly.

npm

WARN peerDependencies The peer dependency rxjs@5.0.0-beta.12 included from @angular/core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency

npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.


> node-sass@3.9.3 install /Users/stefan/Development/MyApp-mobile/MyAppMobile/node_modules/@ionic/app-scripts/node_modules/node-sass
> node scripts/install.js


Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.3/darwin-x64-46_binding.node

Binary downloaded and installed at /Users/stefan/Development/MyApp-mobile/MyAppMobile/node_modules/@ionic/app-scripts/node_modules/node-sass/vendor/darwin-x64-46/binding.node


> fsevents@1.0.14 install /Users/stefan/Development/MyApp-mobile/MyAppMobile/node_modules/@ionic/app-scripts/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build


[fsevents] Success: "/Users/stefan/Development/MyApp-mobile/MyAppMobile/node_modules/@ionic/app-scripts/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" already installed

Pass --update-binary to reinstall or --build-from-source to recompile


> node-sass@3.9.3 postinstall /Users/stefan/Development/MyApp-mobile/MyAppMobile/node_modules/@ionic/app-scripts/node_modules/node-sass
> node scripts/build.js


"/Users/stefan/Development/MyApp-mobile/MyAppMobile/node_modules/@ionic/app-scripts/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists.
 testing binary.

Binary is fine; exiting.

npm
 ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.0

npm ERR! npm  v2.15.9

npm
 ERR! code EPEERINVALID


npm ERR! peerinvalid The package rxjs@5.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid
 Peer @angular/core@2.0.2 wants rxjs@5.0.0-beta.12
npm
 ERR! peerinvalid Peer @angular/http@2.0.2 wants rxjs@5.0.0-beta.12



npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stefan/Development/MyApp-mobile/MyAppMobile/npm-debug.log

Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues`

**Comment by stefandroog** [comment]
Fixed my issue. Had to update NPM via

`npm update -g npm`

**Comment by aas1226** [comment]
I had to reinstall node js, npm update -g npm didn't work for me

**Comment by twofb** [comment]
Neither for me.

**Comment by chrisoconnell** [comment]
I'm also getting the exact same error.
Mac OS X 10.11.5
Node 4.6.0
npm 3.10.8

**Comment by SteveYemSGSG** [comment]
Same issue here. And it cause the ionic 1 setup failed as well.

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8.1
Node Version: v6.7.0

Please advice. Thanks.

**Comment by chrisoconnell** [comment]
It must have something to do with permissions because I got it to work by using:
`sudo ionic start cutePuppyPics --v2`

**Comment by jthoms1** [comment]
Could you please try this again? We recently made changes to the app-base and this should no longer be an issue for you.  Below is the commit that fixed the issue.

driftyco/ionic-storage@92f9032d97f32959e6ae6642bd4d37070792faf3
