### ISSUE TITLE
Failed optional dependency /chokidar/fsevents

### ISSUE THREAD

**Issue by rashid-softordi** [driftyco/ionic-cli#1528]
I am installing "cordova-plugin-geolocation" via npm but "cordova-plugin-geolocation" is unable to intsall. Getting the Warnings

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

Any possible solution?

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#263
