### ISSUE TITLE
No source mappings for providers

### ISSUE THREAD

**Issue by golear91** [driftyco/ionic-cli#1529]
When debugging my Ionic2 application on an android device and connected via the Chrome Debugger, I see that the source mapping has nicely made my .ts files available for everything in the /pages folder however all of my services in the /providers folder are not available.

[![enter image description here][1]][1]
What gives?

when I debug using `ionic serve` i can see the /providers files in another form:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/HVxs7.png
  [2]: https://i.stack.imgur.com/j6Znb.png

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#262

**Comment by golear91** [comment]
Cool thanks!
