### ISSUE TITLE
Ionic Lab updates

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#153]
- [x] Make both iframes the same size
- [x] Change `iPhone 6` to `iOS`
- [x] Make the header a link which opens that iframe in its own page
- [ ] Landscape mode
- [ ] Tablet mode (only one view at a time though)
- [ ] Disable the entire webpage from bouncing when scrolling one of the iframes
- [x] Give the lab a `<title>`
- [x] More obscure url, `/lab` may already be used by someone's app. Maybe `/ionic-lab`
- [ ] Option to have both apps navigate together, even though you only click one of the iframes to navigate
- [ ] Pretty @bensperry designed way to change these settings. Clean/simple

**Comment by Foxandxss** [comment]
Hello, can I suggest a new feature?

I use the --lab for development (more than just a final review) and it would be lovely if the livereload could maintain the route as well. It is a bit of hassle to having to navigate to somewhere just to see the new changes.

**Comment by jbavari** [comment]
@Foxandxss I've been looking into that. I've not found a way yet to make just the iframe reload.

It appears the entire page reloads. However, each iframe points towards android/ios. Those should update individually, but do not. I think the entire window gets reloaded.

I'd love some help to figure it out though. Any ideas?

**Comment by leob** [comment]
@jbavari yes I want this too ...

I love the "labs" option but yes, it should be able to maintain its route (for each iframe)
It's a pain to have to navigate to that view every time you make a change.

I want it so badly that I'd volunteer to work on it.
Especially since nobody else seems to be picking this up anytime soon.

Opinions?

**Comment by jthoms1** [comment]
It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue. Thanks!
