### ISSUE TITLE
Ionic 2 rc0 whitescreen

### ISSUE THREAD

**Issue by Fernanda-Athayde** [driftyco/ionic-cli#1546]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:

Whitescreen after ionic serve on RC0

#### What behavior are you expecting?

Whenever I run the ionic serve command, It starts the application normally but all I get is a whitescreen.

**Steps to reproduce:**
1. create new sidemenu project on RC0
2. run it with ionic serve

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by joepegler** [comment]
+1 When I serve/run android with a sidemenu template (haven't tested the others)

![image](https://cloud.githubusercontent.com/assets/4627587/19408977/92ee5cc2-92c1-11e6-8fe3-1eba62275a9c.png)

**Comment by jthoms1** [comment]
It appears that the commit driftyco/ionic2-starter-sidemenu@47c4c3e8e6cac42da7bd418ec42a0919093b4f37 fixes this issue.  Simple fix for now would be to delete the www/index.html file and try running serve again. Thanks!
