### ISSUE TITLE
Browser is not updating when livereload is runnig

### ISSUE THREAD

**Issue by mbakker96** [driftyco/ionic-cli#1555]
#### Short description of the problem:

When I run `ionic run browser -l`it start up a browser but it is not updating when I change something in my code. I did run `npm run watch` in an other terminal tab in the hope it was fixed but it still not updates the app.

I don't use `ionic serve` becease I want to make use of the SQLite plugin in ionic native.
#### What behavior are you expecting?

Automatic updating like `ionic serve`. 

**Steps to reproduce:**
1. Create a app
2. install the browser device
3. run the browser with `ionic run browser -l` and run in another tab `npm run watch`
4. change something in the code
5. the app is not updating even when you refresh

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jthoms1** [comment]
Please install the latest ionic cli. ionic@2.1.12.  This has incorporated the test tag branch. Thanks for your patience.  If you are still having issues please let me know!

`npm uninstall -g ionic`
`npm install -g ionic@latest`
