### ISSUE TITLE
v2 not respecting package.json 'ionic_www_dir'

### ISSUE THREAD

**Issue by spongessuck** [driftyco/ionic-cli#1558]
#### Short description of the problem:
Ionic CLI v2 isn't properly passing dir configuration from package.json to the build scripts.

#### What behavior are you expecting?
The build scripts should use the custom www dir I specify in package.json.

**Steps to reproduce:**
1. Move www dir to a subfolder
2. Add "ionic_www_dir": "subfolder/www" to the config section in package.json
3. Run "ionic serve"

**Post the output of `ionic info` below please**
Cordova CLI: 6.3.1                                                                                                                        
Gulp version:  CLI version 3.9.1                                                                                                          
Gulp local:                                                                                                                               
Ionic Framework Version: 2.0.0-rc.1                                                                                                       
Ionic CLI Version: 2.1.1                                                                                                                  
Ionic App Lib Version: 2.1.1                                                                                                              
Ionic App Scripts Version: 0.0.36                                                                                                         
ios-deploy version: 1.9.0                                                                                                                 
ios-sim version: Not installed                                                                                                            
OS: Mac OS X El Capitan                                                                                                                   
Node Version: v6.5.0                                                                                                                      
Xcode version: Xcode 8.0 Build version 8A218a

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
It doesn't seem like it's respecting "ionic_root_dir" config also, but I may just be doing it wrong.

**Comment by spongessuck** [comment]
It also seems to not respect the "ionic_src_dir" configuration when using the generator.

**Comment by distante** [comment]
Why is this closed?

**Comment by dwieeb** [comment]
@distante Not sure, but this issue can be consolidated to this: https://github.com/ionic-team/ionic-cli/issues/2232
