### ISSUE TITLE
CLI Generate help text error

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-cli#1559]
_From @richardshergold on October 18, 2016 13:34_

If I do:

ionic g Page OrderDetails

I get an error saying that the available generators are:

Available generators:
 * Component
 * Directive
 * Page
 * Pipe
 * Provider
 * Tabs

what it wants is page in lower-case but in the list presented above, first letters are upper case

_Copied from original issue: driftyco/ionic#8774_

**Comment by jthoms1** [comment]
Here is the location in the source code to correct this issue. https://github.com/driftyco/ionic-app-generators/blob/62db048e852b92c0a45560b650276611a0a76483/src/index.ts#L10

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-generators#5
