### ISSUE TITLE
There was an error with the spawned command: npminstall

### ISSUE THREAD

**Issue by StevenFewster** [driftyco/ionic-cli#1560]
#### Short description of the problem:

Error on `ionic start project-name blank`

This was on a Windows 7 machine using npm v3.9.6 and node v4..4.3

#### What behavior are you expecting?

My guess is there's a space missing in the script between npm and install.

**Steps to reproduce:**
1. Following initial `npm install -g cordova ionic` and circumventing proxy issues I type the following

2. `ionic start test-app blank`

.../ionic-app-base.../master.zip 
.../ionic-start-blank.../master.zip

both download 100%

3. `Installing npm packages`

4. Error with start undefined

```
Error Initializing app: there was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
  undefined
```

**Post the output of `ionic info` below please**

Error Initializing app: there was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
  undefined

**Comment by intheb0x** [comment]
i have the same problem

**Comment by arunmaan** [comment]
I have  the same problem

**Comment by arunmaan** [comment]
Dear all please update your ionic version (latest -beta)
problem will be resolved

**Comment by StevenFewster** [comment]
Used @beta.37 and had the same problem.  Will try uninstalling ionic and installing again with that beta to see if it resolves the issue (maybe residual files?)

**Comment by reflexarg** [comment]
Same problem here, with:
```
Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0-beta.3
Ionic App Lib Version: 2.1.0-beta.1
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.2 LTS
Node Version: v6.8.0
```
and also with:
```
Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.2 LTS
Node Version: v6.8.0

```


Verbose error:
```
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! path /home/dev/projects/despacho/node_modules/esprima-fb/bin/esparse.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/dev/projects/despacho/node_modules/esprima-fb/bin/esparse.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/dev/projects/despacho/node_modules/esprima-fb/bin/esparse.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by reflexarg** [comment]
I have the same issue.. but I have an especial setup. I'm using ionic in a VirtualBox Machine (Host: Windows, GUEST: Ubuntu 16.02). All this with Shared Folders (VirtualBox ones).

If I try to start a v2 project inside my shared folder I get the next error:
```
npm ERR! npm  v3.10.8
npm ERR! path /home/dev/projects/despacho/node_modules/typescript/bin/tsc
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/dev/projects/despacho/node_modules/typescript/bin/tsc'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/dev/projects/despacho/node_modules/typescript/bin/tsc'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

But starting my project in my home folder everything works great.

If I find the solution I'm going to post that in the forums.

**Comment by diegotrsl** [comment]
I had the same problem.

I saw a npm-debug.log in the project folder and the error inside was:

"1029 error not found: git
1030 error Failed using git.
1030 error This is most likely not a problem with npm itself.
1030 error Please check if you have git installed and in your PATH."

I installed git and its solved.

**Comment by edmundtfy** [comment]
I have the same problem, using windows:
Ionic: v2.1.1
Cordova v6.3.1
Node v6.7.0
npm v3.10.3

**Comment by Liuqin** [comment]
me me me me  me  2

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
