### ISSUE TITLE
This is error while setting up new project with ionic start ....

### ISSUE THREAD

**Issue by codershubhamverma** [driftyco/ionic-cli#1566]
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by StevenFewster** [comment]
Duplicate of #1560

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
