### ISSUE TITLE
Not able to build in android

### ISSUE THREAD

**Issue by jayeshanandani** [driftyco/ionic-cli#1571]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### Short description of the problem:
When I try to build in android I encounter the below-mentioned error in the image. Same works in ionic ios build.

#### What behavior are you expecting?
Build should pass.

**Steps to reproduce:**
1. Clone ionic-conference-app
2. Run ionic build android
3. See error in console.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
![capture](https://cloud.githubusercontent.com/assets/3860787/19589602/cbad17e2-978a-11e6-884b-c3c0d88535b9.PNG)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by sfraga94** [comment]
Same problem

**Comment by vintage** [comment]
You can try temporary solution which I've put in https://github.com/driftyco/ionic-cli/issues/1574

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#259
