### ISSUE TITLE
can not create ionic blank app

### ISSUE THREAD

**Issue by mahonlee** [driftyco/ionic-cli#1578]
i can't create ionic blank app.

error message:

Error with start undefined.
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

help me!

**Comment by terrylau2013** [comment]
same issue with tabs app

**Comment by kovack** [comment]
same problem with blank and tabs 

C:\Users\kkovac\ionic2>ionic start todo tabs --v2
Creating Ionic app in folder C:\Users\kkovac\ionic2\todo based on tabs project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!

**Comment by Dbl0207** [comment]
I have a problem.

when i add ionic start "project name" tutorial --v2 in command prompt of windows, it says .git not installed. I have been trying to work with ionic framework but I'm not able to set the base up very clearly.

**Comment by Dbl0207** [comment]
![capture-1](https://cloud.githubusercontent.com/assets/22885198/19763984/4fb271ea-9c5e-11e6-8c1e-68f5f1ad495a.PNG)

The above is the error i get while installing ionic2 using
" ionic start myproject --v2"

**Comment by kovack** [comment]
still not working after npm install -g ionic@latest

here is npm debug log:

[npm-debug.zip](https://github.com/driftyco/ionic-cli/files/555653/npm-debug.zip)

**Comment by jthoms1** [comment]
Could you please try this again? We recently made changes to the app-base and this should no longer be an issue for you.  Below is the commit that fixed the issue.

driftyco/ionic-storage@92f9032d97f32959e6ae6642bd4d37070792faf3

**Comment by dannybritto96** [comment]
C:\Users\DANIE>ionic start todo blank
? The directory todo contains file(s) that could conflict. Would you like to overwrite the directory with this new proj
ect? Yes
✔ Creating directory .\todo - done!
[INFO] Fetching app base (https://github.com/ionic-team/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
[INFO] Fetching starter template blank (https://github.com/ionic-team/ionic2-starter-blank/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
[INFO] Installing dependencies may take several minutes!
> npm install
✖ Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):

        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
        npm WARN prefer global node-gyp@3.6.2 should be installed with -g

        > node-sass@4.5.0 install C:\Users\DANIE\todo\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
        try setting a proxy via HTTP_PROXY, e.g.

        export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

        npm config set proxy http://example.com:8080

        > fsevents@1.1.2 install C:\Users\DANIE\todo\node_modules\fsevents
        > node install


        > node-sass@4.5.0 postinstall C:\Users\DANIE\todo\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe C:\Users\DANIE\todo\node_modules\node-gyp\bin\node-gyp.js rebuild
        --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'C:\\Users\\DANIE\\todo\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@8.1.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\DANIE\todo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\DANIE\todo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\DANIE\todo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (C:\Users\DANIE\todo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\DANIE\todo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\DANIE\todo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\DANIE\todo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\DANIE\todo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\DANIE\todo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (C:\Users\DANIE\todo\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (C:\Users\DANIE\todo\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (C:\Users\DANIE\todo\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\which\which.js:89:16
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at C:\Users\DANIE\todo\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython
        (C:\Users\DANIE\todo\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous>
        (C:\Users\DANIE\todo\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at C:\Users\DANIE\todo\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp ERR! System Windows_NT 10.0.15063
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"
        "C:\\Users\\DANIE\\todo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext="
        "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd C:\Users\DANIE\todo\node_modules\node-sass
        gyp ERR! node -v v8.1.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.5.0 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\DANIE\AppData\Roaming\npm-cache\_logs\2017-06-13T07_05_04_608Z-debug.log

What should I do now ?

**Comment by dwieeb** [comment]
@dannybritto96 
```
    gyp verb could not find "python". checking python launcher
    gyp verb could not find "python". guessing location
    gyp verb ensuring that file exists: C:\Python27\python.exe
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

node-gyp needs python installed

**Comment by dannybritto96** [comment]
I have a different version of Python.. and I have added it to the
environment variables as well.. this specifically needs Python27 ?

Also what about the 404 error for some resource from the git ?

**Comment by dwieeb** [comment]
@dannybritto96 I think it does need Python 2.7. As for the 404 error, not sure... I've seen it before though. Are you behind a firewall? If so, do what those instructions tell you to do. Or maybe one of their releases got screwed up.

**Comment by Dbl0207** [comment]
Hi, Sorry for not reverting. We have completed the project with QR code scanner and other needed functionality with ionic. And made the app live into app store and playstore. All perfect. Thanks for the support.
