### ISSUE TITLE
no valid session found,must call init and login before logout

### ISSUE THREAD

**Issue by adirzoari** [driftyco/ionic-cli#1579]
I only have login via facebook in my ionic 2 app. I installed cordova plugins for that. Sometimes I see this message pop up on my app:

> no valid session found,must call init and login before logout
and my app crashes. Below is a screenshot:

![screenshot_2016-10-21-16-54-36 525](https://cloud.githubusercontent.com/assets/20258998/19621221/bf82afac-9895-11e6-874b-7387d9498ac7.png)

I have already tried to delete the app and install it again but the issue still persists.

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic#8937
