### ISSUE TITLE
Error starting a new project with Version 1

### ISSUE THREAD

**Issue by kesavard** [driftyco/ionic-cli#1580]
Hi
Got installation error while starting a new project with tutorial template. Details below

----
PS D:\SanoHub\Sanosense\Ionic> ionic start MyIonic2Project tutorial --v2
Creating Ionic app in folder D:\SanoHub\Sanosense\Ionic\MyIonic2Project based on tutorial project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tutorial/archive/master.zip
[=============================]  100%  0.0s
Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

PS D:\SanoHub\Sanosense\Ionic>

**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!

**Comment by kesavard** [comment]
Thank You
