### ISSUE TITLE
Ionic livereload is not working @ ionic@1.7.15

### ISSUE THREAD

**Issue by premcarver** [driftyco/ionic-cli#1584]
I am working on a project which is using below configuration for development. When I tried to setup the working environment on MacBookPro with Xcode 10 and iphone 5 running at ios 10. Live reload was initially not working at all. However I have managed to get the console logs but still the changes in html and js files are getting reflected only after the restart(kill and then reopen) the running on device. Could you please help me?

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 1.7.15
Ionic App Lib Version: 0.7.2
ios-deploy version: 1.9.0 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.9.1
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jake4679** [comment]
I'm running into he same issue.  It appears the live reload server is watching the transpiled JS but the process which executes the transpilation is not.

**Comment by jthoms1** [comment]
Could you try updating to a newer version of the CLI? The latest is 2.1.4.
