### ISSUE TITLE
Error: ENOENT: no such file or directory, open '../Documents/project/myApp/www/index.html'

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#1586]
_From @souzacristsf on October 23, 2016 16:48_

I'm trying to create a few weeks IONIC 2 project and so far without success. Hard to create an expectation with ionic 2.

My error is the following:

```
Error: ENOENT: no such file or directory, open '../Documents/project/myApp/www/index.html'
```

use operacinal system `Arch Linux`.

cat / etc / issue
```
Arch Linux \ r (\ l)
```

uname
```
Linux localhost.localdomain 4.7.2-1-ARCH # 1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU / Linux
```

ionic info
```
----------------------------------------------------------------

Your system information:

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.1
Ionic App Lib Version: 2.1.1
OS: / bin / sh: lsb_release: command not found
Node Version: v6.9.1
----------------------------------------------------------------
```
npm -v
```
3.10.9
```

I would like to help, because they do not know what I can faver to solve this problem.

Regards,

Michel Ferreira Souza

_Copied from original issue: driftyco/ionic#8868_

**Comment by souzacristsf** [comment]
I managed to solve the problem by creating another host on Linux User.

It's a shame to have to make this process.
