### ISSUE TITLE
Could not start new ionic2 app with typescript

### ISSUE THREAD

**Issue by ngocnv371** [driftyco/ionic-cli#1595]
I ran "ionic start k5 tutorial --v2 --ts" and got this response.

> 
D:\Projects>ionic start k5 tutorial --v2 --ts
Creating Ionic app in folder D:\Projects\k5 based on tutorial project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tutorial/archive/master.
zip
[=============================]  100%  0.0s
Installing npm packages...
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:1
1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:493:12)
npm WARN addRemoteGit  driftyco/localforage-cordovasqlitedriver#9803562a61c2172a
69f3475f97e98922c0b49ac0 resetting remote C:\Users\Max\AppData\Roaming\npm-cache
\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-980356
2a61c2172a69f3475f97e98922c0b49ac0-f7bfd5d6 because of error: { Error: Command f
ailed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:1
1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:493:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git://github.com/driftyco/localforage-cordovasqlitedriver.
git C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-
localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-f7b
fd5d6: Cloning into bare repository C:\Users\Max\AppData\Roaming\npm-cache\_git-
remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c2
172a69f3475f97e98922c0b49ac0-f7bfd5d6...
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git://github.com/driftyco/localforage-cordovasqlitedriver.
git C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-
localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-f7b
fd5d6:
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git://github.com/driftyco/localforage-cordovasqlitedriver.
git C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-
localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-f7b
fd5d6: fatal: Fetch attempted without a local repo
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit  driftyco/localforage-cordovasqlitedriver#9803562a61c2172a
69f3475f97e98922c0b49ac0 resetting remote C:\Users\Max\AppData\Roaming\npm-cache
\_git-remotes\git-https-github-com-driftyco-localforage-cordovasqlitedriver-git-
9803562a61c2172a69f3475f97e98922c0b49ac0-e715d57c because of error: { Error: Com
mand failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror https://github.com/driftyco/localforage-cordovasqlitedrive
r.git C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-d
riftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b4
9ac0-e715d57c: Cloning into bare repository C:\Users\Max\AppData\Roaming\npm-cac
he\_git-remotes\git-https-github-com-driftyco-localforage-cordovasqlitedriver-gi
t-9803562a61c2172a69f3475f97e98922c0b49ac0-e715d57c...
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror https://github.com/driftyco/localforage-cordovasqlitedrive
r.git C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-d
riftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b4
9ac0-e715d57c:
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror https://github.com/driftyco/localforage-cordovasqlitedrive
r.git C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-d
riftyco-localforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b4
9ac0-e715d57c: fatal: Fetch attempted without a local repo
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit  driftyco/localforage-cordovasqlitedriver#9803562a61c2172a
69f3475f97e98922c0b49ac0 resetting remote C:\Users\Max\AppData\Roaming\npm-cache
\_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-980356
2a61c2172a69f3475f97e98922c0b49ac0-97e37af2 because of error: { Error: Command f
ailed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.gi
t C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-lo
calforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-97e37
af2: Cloning into bare repository C:\Users\Max\AppData\Roaming\npm-cache\_git-re
motes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562a61c217
2a69f3475f97e98922c0b49ac0-97e37af2...
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.gi
t C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-lo
calforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-97e37
af2:
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.gi
t C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-lo
calforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-97e37
af2: Permission denied (publickey).
npm ERR! git clone --template=C:\Users\Max\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git@github.com:driftyco/localforage-cordovasqlitedriver.gi
t C:\Users\Max\AppData\Roaming\npm-cache\_git-remotes\git-github-com-driftyco-lo
calforage-cordovasqlitedriver-git-9803562a61c2172a69f3475f97e98922c0b49ac0-97e37
af2: fatal: The remote end hung up unexpectedly
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code 128
> 
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Ma
x\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:drif
tyco/localforage-cordovasqlitedriver.git C:\Users\Max\AppData\Roaming\npm-cache\
_git-remotes\git-github-com-driftyco-localforage-cordovasqlitedriver-git-9803562
a61c2172a69f3475f97e98922c0b49ac0-97e37af2
npm ERR! Permission denied (publickey).
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
> 
npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\k5\npm-debug.log
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined
> 
Mind letting us know? https://github.com/driftyco/ionic-cli/issues
> 

So could you tell me what did I do wrong, or anyway to get pass this?

As far as I know, GIT is installed and in PATH. ionic, cordova, typescript are all installed globally via npm.

Funny though, I use the same configuration on my virtual Ubuntu 16.04 LTS 32bit and it ran just fine.

My info
>
--------------------------------
--------------------------------
>
Your system information:
>
You have been opted out of telemetry. To change this, run: cordova telemetry on.
>
6.4.0
>
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 8.1
Node Version: v6.6.0
>
--------------------------------
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:
>
 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`
>
******************************************************

This is my fresh factory reset of my windows (just this morning), because last night I thought I f*cked something up real hard.

**Comment by jthoms1** [comment]
I am not sure why npm is not able to find git.  But your issue did help us realize that our dependency on @ionic/storage was out of date and that we should never be pulling from git for our package.  This has been fixed.  Please try to run this again.  Thank you!

driftyco/ionic-storage@92f9032d97f32959e6ae6642bd4d37070792faf3
