### ISSUE TITLE
Issue with installation of Ionic v2 - No Remote GIT

### ISSUE THREAD

**Issue by Dbl0207** [driftyco/ionic-cli#1597]
#### Short description of the problem:
When i install with ionic CLI v2.1.4, i get the following issue i have shown in screenshot. Im not sure where i go wrong. Im a newbie into Ionic Framework. PFA error.

![capture-1](https://cloud.githubusercontent.com/assets/22885198/19764161/4347d976-9c5f-11e6-9b3e-fdf09ef00ab2.PNG)

**Comment by kovack** [comment]
same problem here after npm install -g ionic@latest

here is log: 
[npm-debug.zip](https://github.com/driftyco/ionic-cli/files/555670/npm-debug.zip)

**Comment by Dbl0207** [comment]
@kovack i hope someone will help us really soon. I too have the same issue with ionic2 framework.

**Comment by jthoms1** [comment]
Could you please try this again? We recently made changes to the app-base and this should no longer be an issue for you.  Below is the commit that fixed the issue.

driftyco/ionic-storage@92f9032d97f32959e6ae6642bd4d37070792faf3

**Comment by kovack** [comment]
thanks jthoms1

now it's working
