### ISSUE TITLE
Add release option

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-cli#16]
We could have a release option that removes unnecessary files and strips everything down.

**Comment by softBarbarian** [comment]
this might be related to #168 
Don't you think?

**Comment by jbavari** [comment]
This is being discussed in Issue #270 by another user Luis. We may be incorporating his changes for this there.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
