### ISSUE TITLE
CLI crashes whilst creating fresh Ionic 2 project

### ISSUE THREAD

**Issue by salman-pathan** [driftyco/ionic-cli#1600]
#### Short description of the problem:
Tried to start a fresh ionic v2 project but ended up with error.

#### What behavior are you expecting?
To create a fresh Ionic v2 project.

**Steps to reproduce:**
1. ionic start projectName --v2

**Post the output of `ionic info` below please**
6.3.1

Gulp version:  CLI version 1.2.2
Gulp local:
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Windows 8.1
Node Version: v4.4.5

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!

**Comment by salman-pathan** [comment]
Solved this issue by installing latest version of Cordova.
