### ISSUE TITLE
Can not create ionic app

### ISSUE THREAD

**Issue by sharifullahsh** [driftyco/ionic-cli#1606]
**I am trying to create ionic app but it gives error, while creating app**
```
$ ionic start cutePuppyPics --v2
```

**The error is:**
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v\\nodev7.0.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.9.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodeProjects\ionic\cutePuppyPics\npm-debug.log
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should allow us to gather more insight into NPM issues.  Could you please update your CLI to at least 2.1.4? This should resolve the issue you are seeting.

`npm install -g ionic@latest`

Thank you!

**Comment by sharifullahsh** [comment]
ionic info
--------------------------------
--------------------------------

Your system information:

You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 7 SP1
Node Version: v7.0.0


--------------------------------
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Thanks from your response.
I have above specification but do not solved my problem.

**Comment by jthoms1** [comment]
Can you rerun the command with `ionic start cutePuppyPics --v2 --verbose` and provide me with the output?

**Comment by sharifullahsh** [comment]
ionic start cutePuppyPics --v2 --verbose
Task: title=start, name=start, summary=Starts a new Ionic project in the specifi                      ed PATH, [options]=any flags for the command, <PATH>=directory for the new proje                      ct, [template]=Starter templates can either come from a named template,
(ex: tabs, sidemenu, blank),
a Github repo, a Codepen url, or a local directory.
Codepen url, ex: http://codepen.io/ionic/pen/odqCz
Defaults to Ionic "tabs" starter template, --appname|-a=Human readable name for                       the app (Use quotes around the name), --id|-i=Package name for <widget id> confi                      g, ex: com.mycompany.myapp, title=Skip npm package installation, boolean=true, t                      itle=Create a basic structure without Cordova requirements, boolean=true, title=                      Setup the project to use Sass CSS precompiling, boolean=true, title=List starter                       templates available, boolean=true, --io-app-id=The Ionic.io app ID to use, --te                      mplate|-t=Project starter template, boolean=true, title=Start a Ionic v2 project                      , --zip-file|-z=URL to download zipfile for starter template, isProjectTask=fals                      e, run=function run(ionic, argv) {
  if (argv.list || argv.l) {
    return templateUtils.listTemplates();
  }

  if (argv._.length < 2) {
    return appLibUtils.fail('Invalid command', 'start');
  }

  if (argv._[1] === '.') {
    return log.error('Please name your Ionic project something meaningful other                       than \'.\''.red);
  }

  // Ensure that the folder name provided is a String
  // ie 5 becomes '5' AND '5' stays as '5'
  argv._[1] = argv._[1].toString();

  var promptPromise;
  var options = appLibUtils.preprocessCliOptions(argv);
  var startingApp = true;

  // Grab the app's relative directory name
  if (fs.existsSync(options.targetPath)) {
    promptPromise = Start.promptForOverwrite(options.targetPath);
  } else {
    promptPromise = Q(true);
  }

  return promptPromise
  .then(function(promptToContinue) {
    if (!promptToContinue) {
      startingApp = false;
      log.info('\nIonic start cancelled by user.');
      return;
    }
    return Start.startApp(options);
  })
  .then(function() {
    if (startingApp) {
      return Start.printQuickHelp(options);
    }
  })
  .then(function() {
    if (startingApp) {
      return Start.promptLogin(options);
    }
  })
  .then(function() {
    if (options.v2 && startingApp) {
      log.info('\nNew to Ionic? Get started here: http://ionicframework.com/docs                      /v2/getting-started\n');
    }
  })
  .catch(function(error) {
    log.error(error);
    throw error;
  });
}
Utils.preprocessCliOptions _=[start, cutePuppyPics], skip-npm=false, no-cordova=                      false, w=false, sass=false, s=false, list=false, l=false, v2=true, v=false, verb                      ose=true, $0=C:\Program Files (x86)\Nodist\v\nodev7.0.0\node.exe C:\Program File                      s (x86)\Nodist\bin\node_modules\ionic\bin\ionic
Creating Ionic app in folder E:\nodeProjects\ionic\cutePuppyPics based on tabs p                      roject
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip

Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip

Installing npm packages...
Running exec command: npminstall
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.9.3 install E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.9.3/win32-ia32-51_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.9.3/win32-ia32-51_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.9.3 postinstall E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files (x86)\Nodist\v\nodev7.0.0\node.exe E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files (x86)\\Nodist\\v\\nodev7.0.0\\node.exe',
gyp verb cli   'E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@7.0.0 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:81:29)
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:90:16
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:111:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:81:29)
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:90:16
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:111:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:81:29)
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:90:16
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:111:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:81:29)
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\which\which.js:90:16
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\nodeProjects\ionic\cutePuppyPics\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:111:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.6\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 7.0.0
gyp verb command install [ '7.0.0' ]
gyp verb install input version string "7.0.0"
gyp verb install installing version: 7.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 7.0.0
gyp verb build dir attempting to create "build" dir: E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\intern01\\.node-gyp\\7.0.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\intern01\\.node-gyp\\7.0.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\intern01\.node-gyp\7.0.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for ia32 C:\Users\intern01\.node-gyp\7.0.0\Release\node.lib
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 10/29/2016 4:41:38 PM.
Project "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Win32".
Project "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.sln" (1) is building "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default targets).
Project "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Release\obj\libsass\".
  Creating directory "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\Release\".
  Creating directory "Release\obj\libsass\libsass.tlog\".
InitializeBuildStatus:
  Creating "Release\obj\libsass\libsass.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  CL.exe /c /I"C:\Users\intern01\.node-gyp\7.0.0\include\node" /I"C:\Users\intern01\.node-gyp\7.0.0\src" /I"C:\Users\intern01\.node-gyp\7.0.0\deps\uv\include" /I"C:\Users\intern01\.node-gyp\7.0.0\deps\v8\include" /I..\..\src\libsass\include /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=libsass /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARNINGS=1 /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _HAS_EXCEPTIONS=0 /D "LIBSASS_VERSION=\"3.3.6\"" /GF /Gm- /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"Release\obj\libsass\\" /Fd"Release\obj\libsass\libsass.pdb" /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /analyze- /errorReport:queue /GR /EHsc /MP ..\..\src\libsass\src\ast.cpp ..\..\src\libsass\src\base64vlq.cpp ..\..\src\libsass\src\bind.cpp ..\..\src\libsass\src\color_maps.cpp ..\..\src\libsass\src\constants.cpp ..\..\src\libsass\src\context.cpp ..\..\src\libsass\src\cssize.cpp ..\..\src\libsass\src\emitter.cpp ..\..\src\libsass\src\environment.cpp ..\..\src\libsass\src\error_handling.cpp ..\..\src\libsass\src\eval.cpp ..\..\src\libsass\src\expand.cpp ..\..\src\libsass\src\extend.cpp ..\..\src\libsass\src\file.cpp ..\..\src\libsass\src\functions.cpp ..\..\src\libsass\src\inspect.cpp ..\..\src\libsass\src\json.cpp ..\..\src\libsass\src\lexer.cpp ..\..\src\libsass\src\listize.cpp ..\..\src\libsass\src\memory_manager.cpp ..\..\src\libsass\src\node.cpp ..\..\src\libsass\src\output.cpp ..\..\src\libsass\src\parser.cpp ..\..\src\libsass\src\plugins.cpp ..\..\src\libsass\src\position.cpp ..\..\src\libsass\src\prelexer.cpp ..\..\src\libsass\src\remove_placeholders.cpp ..\..\src\libsass\src\sass.cpp ..\..\src\libsass\src\sass2scss.cpp ..\..\src\libsass\src\sass_context.cpp ..\..\src\libsass\src\sass_functions.cpp ..\..\src\libsass\src\sass_util.cpp ..\..\src\libsass\src\sass_values.cpp ..\..\src\libsass\src\source_map.cpp ..\..\src\libsass\src\to_c.cpp ..\..\src\libsass\src\to_value.cpp ..\..\src\libsass\src\units.cpp ..\..\src\libsass\src\utf8_string.cpp ..\..\src\libsass\src\util.cpp ..\..\src\libsass\src\values.cpp
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\src\libsass.vcxproj]


Done Building Project "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.
Done Building Project "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.
Done Building Project "E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(ClCompile target) ->
  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass\build\src\libsass.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.42
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v\\nodev7.0.0\\node.exe" "E:\\nodeProjects\\ionic\\cutePuppyPics\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\nodeProjects\ionic\cutePuppyPics\node_modules\node-sass
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
ionic-app-base@ E:\nodeProjects\ionic\cutePuppyPics
+-- @angular/common@2.0.0
+-- @angular/compiler@2.0.0
+-- @angular/compiler-cli@0.6.2
| +-- @angular/tsc-wrapped@0.3.0
| | `-- tsickle@0.1.7
| |   +-- mkdirp@0.5.1
| |   | `-- minimist@0.0.8
| |   +-- source-map@0.4.4
| |   | `-- amdefine@1.0.0
| |   `-- source-map-support@0.3.3
| |     `-- source-map@0.1.32
| +-- minimist@1.2.0
| +-- parse5@1.3.2
| `-- reflect-metadata@0.1.8
+-- @angular/core@2.0.0
+-- @angular/forms@2.0.0
+-- @angular/http@2.0.0
+-- @angular/platform-browser@2.0.0
+-- @angular/platform-browser-dynamic@2.0.0
+-- @angular/platform-server@2.0.0
+-- @ionic/storage@1.1.6
| +-- @types/localforage@0.0.30
| +-- localforage@1.4.3
| | `-- lie@3.0.2
| |   +-- es3ify@0.1.4
| |   | +-- esprima-fb@3001.1.0-dev-harmony-fb
| |   | +-- jstransform@3.0.0
| |   | | +-- base62@0.1.1
| |   | | `-- source-map@0.1.31
| |   | `-- through@2.3.8
| |   +-- immediate@3.0.6
| |   +-- inline-process-browser@1.0.0
| |   | +-- falafel@1.2.0
| |   | | +-- acorn@1.2.2
| |   | | +-- foreach@2.0.5
| |   | | +-- isarray@0.0.1
| |   | | `-- object-keys@1.0.11
| |   | `-- through2@0.6.5
| |   |   +-- readable-stream@1.0.34
| |   |   | +-- core-util-is@1.0.2
| |   |   | +-- inherits@2.0.3
| |   |   | `-- string_decoder@0.10.31
| |   |   `-- xtend@4.0.1
| |   `-- unreachable-branch-transform@0.3.0
| |     +-- esmangle-evaluator@1.0.1
| |     `-- recast@0.10.43
| |       +-- ast-types@0.8.15
| |       +-- esprima-fb@15001.1001.0-dev-harmony-fb
| |       +-- private@0.1.6
| |       `-- source-map@0.5.6
| `-- localforage-cordovasqlitedriver@1.5.0
+-- d@0.1.1  extraneous
+-- ionic-angular@2.0.0-rc.1
+-- ionic-native@2.2.3
+-- ionicons@3.0.0
+-- rxjs@5.0.0-beta.12
| `-- symbol-observable@1.0.4
+-- typescript@2.0.6
`-- zone.js@0.6.21

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v\\nodev7.0.0\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.9.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\nodeProjects\ionic\cutePuppyPics\npm-debug.log
Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
It appears that lib-sass is failing to install on your machine. Looks like they have an open issue for Node 7 support.  sass/node-sass#1766

Could you install the latest LTS version of Node instead?  This should work much better.
https://nodejs.org/en/download/

**Comment by sharifullahsh** [comment]
Thanks, jthoms1 it solved my problem.
