### ISSUE TITLE
Ionic livereload on 2.1.4

### ISSUE THREAD

**Issue by ronakkaria** [driftyco/ionic-cli#1607]
**Note: for support questions, please use one of these channels:**
Not sure if this the right channel for this
#### Short description of the problem:

Just shifted to the new version of Ionic Cli 2.1.4 from 1.7.x. Created a new Ionic V2 project using the `tabs` starter kit. 

Running on Android device with live-reload option doesn't watch for changes on my `src` files. If I go into my `build` folder however and modify the minified javascript file, the app reloads and the terminal logs a change in the `.js` file.
#### What behavior are you expecting?

Shouldn't it watch for changes to my `.ts` and `.html` files in my `src` folder and automatically do the transpilation and copy into `build`?

**Steps to reproduce:**
1. `ionic run android --device -l`
2. Change any `.ts` file
3.

**Post the output of `ionic info` below please**
Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.36
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v6.5.0
Xcode version: Not installed

**Comment by ronakkaria** [comment]
Any workaround for now?

**Comment by ronakkaria** [comment]
Never mind. Just saw the same problem being mentioned here: https://github.com/driftyco/ionic-cli/issues/1425. 
Thanks

**Comment by jthoms1** [comment]
Please install the latest ionic cli. ionic@2.1.12.  This has incorporated the test tag branch. Thanks for your patience.  If you are still having issues please let me know!

`npm uninstall -g ionic`
`npm install -g ionic@latest`
