### ISSUE TITLE
Default icon and splash instead of in resouces

### ISSUE THREAD

**Issue by smkamranqadri** [driftyco/ionic-cli#1625]
I recently switched my laptop and now i am on macbook pro with sierra macos and when i build the application i didn't put the new icon and splash screen which i had put in resouces folder.

I had check two app same result the default one was using while when i build with my old pc which is on yosemite it's working.

**Comment by smkamranqadri** [comment]
i have noticed that when ever i run build command it generates res folder in root instead of platform/android which is why the icon is not updating.

**Comment by JustinPierce** [comment]
@smkamranqadri Based on my experience this morning, this seems to be a bug in Cordova 6.4.0. Try installing 6.3.1 and see if that helps.

**Comment by Chris1308** [comment]
The bug is already fixed but you have to get the latest platform from master. For more information go here: https://github.com/apache/cordova-android/pull/343

**Comment by smkamranqadri** [comment]
@JustinPierce thanks downgrading solves my problem.
