### ISSUE TITLE
Ionic serve in prod mode

### ISSUE THREAD

**Issue by Maziar-Fotouhi** [driftyco/ionic-cli#1631]
Can we have something like this added to the cli?
`ionic serve --prod`

This would be a huge help for testing the app when you have different codes for _prod_ and _dev_. One example can be having different environment variables set up.

Right now the only way to run the app in prod mode is to _run_ it on a _device_ which is very time consuming at least.

**Comment by maxflex** [comment]
Agreed. I am new to Ionic and assumed this functionality existed, but no.

**Comment by maxflex** [comment]
It's not possible right now:
https://github.com/driftyco/ionic-app-scripts/issues/709

**Comment by jpradeep2003** [comment]
Is there any other alternative to get an optimized build for production deployment of web-app?

**Comment by Maziar-Fotouhi** [comment]
After reading this:
https://github.com/driftyco/ionic-app-scripts/issues/709#issuecomment-277454896
I'm closing this for now.
