### ISSUE TITLE
An error occurred uploading the build: Forbidden upload (403)

### ISSUE THREAD

**Issue by gbrigens** [driftyco/ionic-cli#1647]
Am running into issue when I try uploading an app in ionic view, I have search online but all of the solution haven't fixed the issue.

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
ios-deploy version: 1.9.0
ios-sim version: 5.0.8
OS: Mac OS X Sierra
Node Version: v6.8.0
Xcode version: Xcode 8.1 Build version 8B62
**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by HuddleHouse** [comment]
Hello, I am having the same problem. Did you find a solution?

**Comment by HamzaLJ** [comment]
@HuddleHouse You can solve it running the following `ionic login` enter your details and try again, it should work fine ;)

**Comment by raae** [comment]
Thanks @HamzaLJ!

Would be great if the error message could say "Please log in first using command ionic login".

**Comment by gbrigens** [comment]
This was solved by logging in @raae that true haha.
