### ISSUE TITLE
ionic  start ->problem npminstal

### ISSUE THREAD

**Issue by lvdesign** [driftyco/ionic-cli#1677]
Hello a problem bizarre !

Installing npm packages...
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall
Caught exception:
 undefined 

**Post the output of `ionic info` below please**
Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.4.0

Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Snow Leopard
Node Version: v4.4.4
Xcode version: Xcode 3.2.6 Component versions: DevToolsCore-1809.0; DevToolsSupport-1806.0 BuildVersion: 10M2518 

////
ionic@2.0.0 /usr/local/lib/node_modules/ionic
cordova@6.4.0 /usr/local/lib/node_modules/cordova

**Comment by jthoms1** [comment]
This was a known issue that has been resolved.  Could you please update your CLI to 2.1.8?

`npm install -g ionic@latest`

Thank you!

**Comment by lvdesign** [comment]
Thanks John,
Always a problem but certainly about system Darwin 10.8.0
best regard
