### ISSUE TITLE
ionic 2 serve not work on OSX (but on Windows)

### ISSUE THREAD

**Issue by darklx** [driftyco/ionic-cli#1679]
When I upgrade to the new ionic angular & cordova version, ionci serve no work on OSX

**Steps to reproduce:**
1.run npm i -g cordova to upgrade cordova to the new ionic required version
2.upgrade the inic pacakge.json file
3.run npm i
4.run ionic serve

pacakge.json
```
{
  "name": "ionic-app-base",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.2",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.42",
    "typescript": "2.0.6"
  }
}

```

**the output of `ionic serve`**

MarkdeMacBook-Pro:ionic laurel$ ionic serve
"www" directory cannot be found. Please make sure the working directory is an Ionic project.
There was an error serving your Ionic application: "www" directory cannot be found. Please make sure the working directory is an Ionic project.
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

===================

^C
MarkdeMacBook-Pro:ionic laurel$ sudo ionic serve
Password:
"www" directory cannot be found. Please make sure the working directory is an Ionic project.
There was an error serving your Ionic application: "www" directory cannot be found. Please make sure the working directory is an Ionic project.
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**the output of `ionic info`**

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.5.0
Xcode version: Xcode 8.1 Build version 8B62 

******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications.`npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices.  `npm install -g ios-deploy` (may require sudo)

******************************************************

**Comment by jthoms1** [comment]
Could you please update to the latest CLI? (2.1.8)

`npm install -g ionic@latest`
