### ISSUE TITLE
Bug: Multiple proxies are ignored

### ISSUE THREAD

**Issue by budacoder** [driftyco/ionic-cli#1686]
#### Short description of the problem:
Using the latest ionic-cli (2.1.11), multiple proxies (set in the ionic.config.json file) will be ignored, just the first element will be used. It throws 404 for the other endpoints.

**Steps to reproduce:**  
1. npm i -g ionic@2.1.11  
2. set ionic.config.json, like this:  
```
{
  "name": "...",
  "app_id": "...",
  "v2": true,
  "typescript": true,
  "proxies": [
    {
      "path": "/api/",
      "proxyUrl": "http://google.com/",
      "rejectUnauthorized": false
    },
    {
      "path": "/api2/",
      "proxyUrl": "http://google.com/",
      "rejectUnauthorized": false
    }
  ]
}
```
3. Start the server: `ionic serve`  
4. Check in the browser:   
 - `localhost:8100/api/` -> status 200  
 -  `localhost:8100/api2/` -> status 404

**Comment by marcellkiss** [comment]
Sorry, wrong repo (app-scripts is the good one), solved here:
https://github.com/driftyco/ionic-app-scripts/pull/395
