### ISSUE TITLE
ion-fab color in ion-fab-list not working

### ISSUE THREAD

**Issue by kovack** [driftyco/ionic-cli#1689]
ion-fab buttons in ion-fab-list not colored in "calm" in latest 2.0.0-rc.3 

`<ion-fab right bottom>
		<button ion-fab color="calm"><ion-icon name="arrow-dropup"></ion-icon></button>
		<ion-fab-list side="top">
			<button ion-fab color="calm" (click)="loaddatafromwebservice()" ><ion-icon name="refresh"></ion-icon></button>
			<button ion-fab color="calm" (click)="openspwho()"><ion-icon name="person"></ion-icon></button>
		</ion-fab-list>
	</ion-fab>`

in variables.scss I have :

$colors: (
     calm:       #AF251C
);

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic#9240
