### ISSUE TITLE
Docs on main site

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#169]
Would it makes sense to add a CLI section to the docs at ionicframework.com, just to have it consolidated? Right now if I want to know how the CLI works, I have to install it (which isn't a big deal), but it seems like it would make sense to include it at ionicframework.com too.

**Comment by jbavari** [comment]
Ray,

We're definitely on the move with this. Coming soon.

**Comment by pbernasconi** [comment]
Or the Ionic CLI could have separate docs like EmberJS: http://www.ember-cli.com/

**Comment by cfjedimaster** [comment]
As long as it is linked from the main site. I don't want to have to think
("So, wait, the docs are here or there....")

On Thu, Jan 8, 2015 at 10:26 AM, Paolo Bernasconi <notifications@github.com>
wrote:

> Or the Ionic CLI could have separate docs like EmberJS:
> http://www.ember-cli.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-cli/issues/169#issuecomment-69204698>.
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by pbernasconi** [comment]
It should really be @ http://ionicframework.com/docs/ in the left side-menu. I wouldn't mind helping out on this, if someone @ ionic can get the project started.

**Comment by jbavari** [comment]
@pbernasconi - I'd love to take this on with you. I have a few other tasks to attend to, but after that, I'm all in.

**Comment by pbernasconi** [comment]
@jbavari I made a PR to the Ionic site as a starter, lets see if @mlynch and @bensperry like it.

**Comment by pbernasconi** [comment]
This can be closed now. https://github.com/driftyco/ionic-site/pull/245 was accepted. and can be found @ http://ionicframework.com/docs/cli/

**Comment by cfjedimaster** [comment]
Nice - thank you for doing this!

On Thu, Jan 15, 2015 at 8:45 AM, Paolo Bernasconi <notifications@github.com>
wrote:

> This can be closed now. driftyco/ionic-site#245
> <https://github.com/driftyco/ionic-site/pull/245> was accepted. and can
> be found @ http://ionicframework.com/docs/cli/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-cli/issues/169#issuecomment-70095057>.
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by jbavari** [comment]
Thanks @pbernasconi - you are crushing it man!
