### ISSUE TITLE
Enabling live reload option in CLI results with black screen on Genymotion and ionic-box

### ISSUE THREAD

**Issue by sydneyhenrard** [driftyco/ionic-cli#170]
Similar issue as #81 but this time with Genymotion.

Application works fine when -l is not passed. I've used sample app built with ionic start myapp sidemenu. There is nothing in the logs (even if -c and -s are provided)

Console output tail:

```
Installing app on device...
Launching application...
LAUNCH SUCCESS
```

```
vagrant@ionic-android:/tmp$ ionic start myapp sidemenu
Creating Ionic app in folder /tmp/myapp based on sidemenu project

vagrant@ionic-android:/tmp$ adb devices
List of devices attached
192.168.56.101:5555     device

vagrant@ionic-android:/tmp/myapp$ ionic --version
1.2.14
```

Live reload is working because if I change a file, I can see a trace that the file changed.

**Comment by jbavari** [comment]
I know you've said that without `-l` it works fine.

If you debug the device with Chrome, do you see any errors happening in the log? I'm wondering if some livereload stuff is causing some errors with the app.

Sometimes error in your javascript or script src tags not being loaded correctly can cause a crash.

Please check that and let me know.

**Comment by sydneyhenrard** [comment]
Genymotion is running on 192.168.56.101. My local ip address is 192.168.0.27.

I don't understand what you mean by debugging the device with Chrome but the code source is basically the sidemenu project provided by ionic. I don't see any error in the code.

I use Genymotion 2.3.1

**Comment by softBarbarian** [comment]
Here is what he means by remote debugging in chrome:
https://developer.chrome.com/devtools/docs/remote-debugging

And your code running in gennymotion is considered as a device as far as  host operating system is concerned

**Comment by sydneyhenrard** [comment]
I can see my device:

```
```

I think I have a problem with the IP found by ionic http://10.0.2.15:8100:

```
vagrant@ionic-android:/project$ ionic run android -c -s -l
Setup Live Reload

Multiple addresses available.
Please select which address to use by entering its number from the list below:
Note that the emulator/device must be able to access the given IP address
Running dev server: http://10.0.2.15:8100
Running live reload server: http://10.0.2.15:35729
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

My local IP is `192.168.0.27`:

```
K:\home>ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::f5e9:ae9d:7c62:61f2%10
   IPv4 Address. . . . . . . . . . . : 192.168.0.27
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.8

Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::60d7:4c7d:e6d1:2410%16
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
```

**Comment by jbavari** [comment]
Were you able to make any progress and get it to work?

**Comment by sydneyhenrard** [comment]
I checked my IP
Genymotion: 192.168.56.101
Vagrant VM: 10.0.2.15

`adb connect 192.168.56.101` is working.

So when running with `-l`, the reload server runs on `10.0.2.15`

```
Note that the emulator/device must be able to access the given IP address
Running dev server: http://10.0.2.15:8100
Running live reload server: http://10.0.2.15:35729
```

If I try to use the browser in genymotion and access `http://10.0.2.15:8100`, it's not working. So it seems that Genymotion can't access the servers on the vagrant box. I guess this is why `-l` is not working.

**Comment by sydneyhenrard** [comment]
I can now access my app from genymotion browser by using `http://10.0.3.2:8100`
Source: http://stackoverflow.com/questions/18463319/access-host-from-genymotion-emulator

I don't know if it helps.

**Comment by jbavari** [comment]
@sydneyhenrard - are you all good on this issue?

**Comment by sydneyhenrard** [comment]
Unfortunately no. I don't really know what I should look for. I guess the problem is that I can't get access to `10.0.2.15` which is the vagrant box IP from genymotion.
