### ISSUE TITLE
"ionic upload" crashing (Tested on Windows 7 and Ubuntu 14.04)

### ISSUE THREAD

**Issue by PadreMontoya** [driftyco/ionic-cli#171]
I'm trying to do a bare-bones test of "ionic upload".  I'm using Ionic 1.2.14.  Steps:

1)  "ionic start helloworld"
2)  "cd helloworld"
3)  "ionic upload"

I enter my credentials and it says "Logged in!  :)   Uploading app...".  Then it crashes:

    C:\Users\Anthony\AppData\Roaming\npm\node_modules\ionic\lib\ionic\upload.js:53
      for (var i = 0; i < jar.cookies.length; i++) {
                                     ^
    TypeError: Cannot read property 'length' of undefined at WriteStream.<anonymous> (C:\Users\Anthony\AppData\Roaming\npm\node_modules\ionic\lib\ionic\upload.js:53:38)
        at WriteStream.emit (events.js:117:20)
        at fs.js:1609:14
        at Object.oncomplete (fs.js:107:15)

The same error happens on Windows 7 and Ubuntu 14.04.

Open to suggestions...

**Comment by PadreMontoya** [comment]
FYI: Did a tiny bit of debugging.  It looks like the jar variable has changed and there is no longer a "cookie" variable.

    { _jar:
       { store:
          { idx: { 'ionic.io':
             { '/':
                { __cfduid: Cookie="__cfduid=d73a4800f67a714b57451f591b1cf47251420602013; Expires=Fri, 07 Jan 162000 03:40:13 GMT; Domain=ionic.io; Path=/; HttpOnly; hostOnly=false; aAge=2524ms; cAge=2524ms",
    csrftoken: Cookie="csrftoken=0xv2NmO7WiBDxQ41nFJ1AsuosFG1GLdj; Expires=Wed, 06 Jan 2016 03:42:32 GMT; Max-Age=31449600; Domain=ionic.io; Path=/; hostOnly=false; aAge=2523ms; cAge=2523ms",
    sessionid: Cookie="sessionid=0bkm0tkvcuqm2ab0l6r1cuk5sq7z8xml; Expires=Wed, 21 Jan 2015 03:42:32 GMT; Max-Age=1209600; Domain=ionic.io; Path=/; HttpOnly; hostOnly=false; aAge=2523ms; cAge=2523ms",
    AWSELB: Cookie="AWSELB=69D5F1C31030FBCA8CD735FECC480AE0DB08761F1950E3581B953D0614A1373553FC7E641DAF1124C2DDE59350A417C2577412E14FFD6FB71B8E7F3A4CFBE12AFD2BE4341CCCCACD5C6C4A1A7B68E70BF9158BD111; Max-Age=1209600; Domain=ionic.io; Path=/; HttpOnly; hostOnly=false; aAge=2524ms; cAge=2524ms" } } } } } } { __cfduid: Cookie="__cfduid=d73a4800f67a714b57451f591b1cf47251420602013; Expires=Fri, 07 Jan 162000 03:40:13 GMT; Domain=ionic.io; Path=/; HttpOnly; hostOnly=false; aAge=2525ms; cAge=2525ms",
    csrftoken: Cookie="csrftoken=0xv2NmO7WiBDxQ41nFJ1AsuosFG1GLdj; Expires=Wed, 06 Jan 2016 03:42:32 GMT; Max-Age=31449600; Domain=ionic.io; Path=/; hostOnly=false; aAge=2524ms; cAge=2524ms",
          sessionid: Cookie="sessionid=0bkm0tkvcuqm2ab0l6r1cuk5sq7z8xml; Expires=Wed, 21 Jan 2015 03:42:32 GMT; Max-Age=1209600; Domain=ionic.io; Path=/; HttpOnly; hostOnly=false; aAge=2524ms; cAge=2524ms",
      AWSELB: Cookie="AWSELB=69D5F1C31030FBCA8CD735FECC480AE0DB08761F1950E3581B953D0614A1373553FC7E641DAF1124C2DDE59350A417C2577412E14FFD6FB71B8E7F3A4CFBE12AFD2BE4341CCCCACD5C6C4A1A7B68E70BF9158BD111; Max-Age=1209600; Domain=ionic.io; Path=/; HttpOnly; hostOnly=false; aAge=2524ms; cAge=2524ms" }

The data is still there, however, buried in `jar._jar.store.idx['ionic.io']['/']['csrftoken']`

**Comment by dkavraal** [comment]
Same issue here. Anything?

**Comment by jbavari** [comment]
Thanks for the feedback and issue.

I'll be looking into this today and tomorrow.

**Comment by jbavari** [comment]
@PadreMontoya - I've fixed this and it should be shipping today. What it was - we bumped the version of request up, which then changed the way the cookies were used a bit. Thanks again for the help.

**Comment by mavenius** [comment]
This behavior is happening for me with ionic 1.2. Any chance this got reverted? It worked fine before upgrading versions.

**Comment by mavenius** [comment]
...And now I see it was fixed in 1.3, so any chance it can get pushed to 1.2 as well?

**Comment by mavenius** [comment]
Scratch that... I had a weird version mismatch. All good when I got fully to 1.2. 

Sorry about that...
