### ISSUE TITLE
ionic resources, missing line in config.xml (android)

### ISSUE THREAD

**Issue by jQrgen** [driftyco/ionic-cli#172]
For android, It doesn't work automatically. We have to manually add following to config.xml after running ionic resources:

<preference name="SplashScreen" value="screen"/>

creds: Jian Wu Chen 
(commented here: http://ionicframework.com/blog/automating-icons-and-splash-screens/ )

**Comment by jbavari** [comment]
@jQrgen - Thanks, we're looking into it!

**Comment by jbavari** [comment]
This should be changed now. Thanks!

**Comment by InfiniteRandomVariable** [comment]
Update to the latest Ionic version, still require the below to work,
<preference name="SplashScreen" value="screen"/>
<preference name="SplashScreenDelay" value="4000"/>
