### ISSUE TITLE
Live Reloading and Server Commands not working

### ISSUE THREAD

**Issue by SaadeMotion** [driftyco/ionic-cli#1727]
When i hit:
```
ionic serve --lab
```
it opens the browser, but not in lab, live reloading does not work, AND i cannot type Ionic Server Commands in console, like:

```
restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

the problem its the same with
```
ionic run android -l -c
```
Live Reload dont work, i cant type server commands, AND when JS Changes, does nothing, i need to close the terminal and hit Run again to get a new code.

--------------------------------

Your system information:

Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.6.1
Xcode version: Xcode 8.0 Build version 8A218a

--------------------------------

**Comment by jthoms1** [comment]
Please update to the latest CLI release. This issue has been resolved. Thanks!

`npm install -g ionic@latest`
