### ISSUE TITLE
ionic g page command is not registering the page component in app.module.ts file

### ISSUE THREAD

**Issue by faraazc** [driftyco/ionic-cli#1728]
#### Short description of the problem:
ionic g page command is not registering the page component in app.module.ts file. Ideally it should include and register the component in the declarations array. 
Angular-cli does registers components when scaffold.  

#### What behavior are you expecting?
i would expect ionic cli to register page component in the declarations array of @ngModule decorator and also in entry points array if possible in the file app.module.ts

**Steps to reproduce:**
1. run below command
ionic generate page page_name
and check the behaviour in app.module.ts

**Post the output of `ionic info` below please**

Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.1.0
Xcode version: Not installed

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-generators#7
