### ISSUE TITLE
[ionic-cli v2.1.12 ]plugin add <plugin> not added to package.json

### ISSUE THREAD

**Issue by CroModder** [driftyco/ionic-cli#1734]
#### Short description of the problem:
When I add the plugin with ionic-cli it is not added to package.json

#### What behavior are you expecting?
That the added plugin is also added in the package.json

**Steps to reproduce:**
` ionic plugin add phonegap-plugin-barcodescanner`

**Post the output of `ionic info` below please**
``` 
 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7

Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.1
Xcode version: Not installed
```

**package.json content**:
```
"cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-splashscreen"
  ],
```

**Comment by cleever** [comment]
you should use --save parameter.

`ionic plugin add phonegap-plugin-barcodescanner --save`

The plugin information will be save at config.xml

**Comment by CroModder** [comment]
Thanks for the response.
Still confused why some plugins are saved in package.json and others in config.xml. And I can't find the docs to clarify that.
But anyway, closing the issue.

**Comment by rosdi** [comment]
Had the same question, and I didn't use `--save` parameter as well and neither the ionic documentation says so...

The plugin information somehow is available in config.xml (not sure whether it was there originally before I executed the command).

So I don't think it is neccessary to have it in package.json
