### ISSUE TITLE
Issue with config.xml in 1.3

### ISSUE THREAD

**Issue by danda1man** [driftyco/ionic-cli#175]
Similar to the issue I faced in #84, I moved my config.xml from my www folder to the root (so xcode would quit complaining and to better match templates I have been seeing).   Get the following error without a stack trace this time:

C:\code\current>ionic run android
Error updating C:\code\current\config.xml: TypeError: Cannot read property '0' of undefined (CLI v1.3.0)

**Comment by jbavari** [comment]
Have you tried updating the CLI to latest 4.1.2?

**Comment by danda1man** [comment]
Latest version I can get is 1.3.1 for the ionic CLI.  Cordova CLI is up to date, version 4.2.0:

C:\code\current>npm list -g cordova
C:\Users\djohnso\AppData\Roaming\npm
├── cordova@4.2.0
└─┬ vs-mda@0.1.70
  └── cordova@4.0.0

**Comment by danda1man** [comment]
using "cordova build android" works just fine, but "ionic build android" still gives the error in cli 1.3.2, any update on getting this fixed @jbavari?

**Comment by jbavari** [comment]
Could you post the contents of your config.xml file?

**Comment by danda1man** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget xmlns="http://www.w3.org/ns/widgets" id="com.referredrewards.mobile" versionCode="7" version="1.0.7">
  <name>Referred Rewards</name>
  <description>You refer, we reward!  Find deals for local companies and refer your friends to earn rewards.</description>
  <author href="https://referredrewards.com" email="support@referredrewards.com">Referred Inc</author>
  <preference name="permissions" value="none"/>
  <preference name="Fullscreen" value="true"/>
  <preference name="Orientation" value="portrait"/>
  <preference name="exit-on-suspend" value="false"/>
  <preference name="StatusBarOverlaysWebView" value="true"/>
  <preference name="StatusBarBackgroundColor" value="#bb1c1c"/>
  <preference name="StatusBarStyle" value="lightcontent"/>
  <preference name="EnableViewportScale" value="true"/>
  <preference name="MediaPlaybackRequiresUserAction" value="false"/>
  <preference name="AllowInlineMediaPlayback" value="true"/>
  <preference name="BackupWebStorage" value="none"/>
  <preference name="TopActivityIndicator" value="white"/>
  <preference name="KeyboardDisplayRequiresUserAction" value="false"/>
  <preference name="SuppressesIncrementalRendering" value="true"/>
  <preference name="GapBetweenPages" value="0"/>
  <preference name="PageLength" value="0"/>
  <preference name="PaginationBreakingMode" value="page"/>
  <preference name="PaginationMode" value="unpaginated"/>
  <preference name="UIWebViewDecelerationSpeed" value="normal"/>
  <preference name="AutoHideSplashScreen" value="false"/>
  <preference name="ShowSplashScreenSpinner" value="false"/>
  <preference name="target-device" value="handset"/>
  <preference name="prerendered-icon" value="false"/>
  <preference name="detect-data-types" value="true"/>
  <preference name="KeepRunning" value="true"/>
  <preference name="LoadUrlTimeoutValue" value="10000"/>
  <preference name="SplashScreen" value="screen"/>
  <preference name="SplashScreenDelay" value="10000"/>
  <preference name="InAppBrowserStorageEnabled" value="true"/>
  <preference name="ErrorUrl" value=""/>
  <preference name="ShowTitle" value="false"/>
  <preference name="LogLevel" value="WARN"/>
  <preference name="AndroidLaunchMode" value="singleTop"/>
  <preference name="android-minSdkVersion" value="14"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="BackgroundColor" value="0xff000000"/>
  <access origin="*"/>
  <access origin="tel:*" launch-external="yes"/>
  <access origin="geo:*" launch-external="yes"/>
  <access origin="mailto:*" launch-external="yes"/>
  <access origin="market:*" launch-external="yes"/>
  <feature name="Keyboard">
    <param name="android-package" value="com.ionic.keyboard.IonicKeyboard"/>
    <param name="onload" value="true"/>
  </feature>
  <feature name="Keyboard">
    <param name="ios-package" value="IonicKeyboard" onload="true"/>
  </feature>
  <feature name="SplashScreen">
    <param name="android-package" value="org.apache.cordova.splashscreen.SplashScreen"/>
    <param name="ios-package" value="CDVSplashScreen"/>
    <param name="onload" value="true"/>
  </feature>
  <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
  </feature>
  <platform name="android">
    <splash src="resources\android\splash\drawable-port-ldpi-screen.png" density="port-ldpi"/>
    <splash src="resources\android\splash\drawable-port-mdpi-screen.png" density="port-mdpi"/>
    <splash src="resources\android\splash\drawable-port-hdpi-screen.png" density="port-hdpi"/>
    <splash src="resources\android\splash\drawable-port-xhdpi-screen.png" density="port-xhdpi"/>
    <splash src="resources\android\splash\drawable-port-xxhdpi-screen.png" density="port-xxhdpi"/>
    <splash src="resources\android\splash\drawable-port-xxxhdpi-screen.png" density="port-xxxhdpi"/>
  </platform>
</widget>

**Comment by danda1man** [comment]
@jbavari Any update?  This is especially annoying since using ionic resources requires the config.xml be in the root instead of www so I have to move it back and forth

**Comment by jbavari** [comment]
I just copied and pasted your config.xml into my project, and immediately got the error.

You're missing the `<content>` tag.

Add something like this: `<content src="index.html"/>`

**Comment by danda1man** [comment]
Ah, thanks.  Cordova must ignore it if that is missing

**Comment by jbavari** [comment]
I'll go ahead and add another issue to check for this and alert the users going forward. Thanks for the catch.

**Comment by dbaq** [comment]
I can confirm that with a regular config.xml coming from cordova, ionic-cli fails if the ```content``` tag is missing.
