### ISSUE TITLE
ionic add command will delete ionic-cli itself!

### ISSUE THREAD

**Issue by WingGao** [driftyco/ionic-cli#176]
CMD:  ionic add circletype.js

Then run ionic:   zsh: command not found: ionic

**Comment by jbavari** [comment]
@WingGao - are you sure that happens every time?

Try this:
`npm install -g ionic`
`ionic add circletype.js`

Are you sure it is removed then?

**Comment by WingGao** [comment]
yes EVERYTIME

**Comment by jbavari** [comment]
Could you please reinstall ionic, then run `ionic info`, and copy/paste that information here?

I am unable to reproduce the problem.

Without providing some additional information about your environment or project settings, there's not much I can do.
