### ISSUE TITLE
ionic serve not working after updating to 2.1.0

### ISSUE THREAD

**Issue by casper123** [driftyco/ionic-cli#1766]
I have updated my ionic to latest version 2.1.0 through npm. This is my version information

Your system information:

```
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 7.2 Build version 7C68 
```

After update, I am having stange behavior with ionic serve, it runs localhost server fine but no linting, or webpack and my www directory always remain empty.

```
root@Abduls-MacBook-Air.local:/Users/abdulwahab/Documents/mobileapps/bytemunch$ionic serve
Running live reload server: http://localhost:35729
Watching: www/**/*, !www/lib/**/*, !www/**/*.map
√ Running dev server:  http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ 

```

**Comment by goleary** [comment]
I was having the exact same problem.  I upgraded to the latest version of ionic (2.0.0-rc.4) and it fixed it for me:
https://github.com/driftyco/ionic/blob/master/CHANGELOG.md

**Comment by jthoms1** [comment]
The answer provided by @goleary should resolve your issues.  Our changelog details some of the changes that you might need to make to your package.json file to follow our new processes. Thanks!
