### ISSUE TITLE
Ionic Serve - build dev failed: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic-cli#1777]
Wasn't sure where to place this issue - here or in the App Scripts repo.  I placed it there - sorry to duplicate

https://github.com/driftyco/ionic-app-scripts/issues/544

**Comment by richardshergold** [comment]
FIXED - I had Firebase as a dependency as well as AngularFire  - removing Firebase from package.json fixed the issue.

**Comment by HuddleHouse** [comment]
I don't think this is a long term solution but if you are trying to get 'ionic serve' to work and this is your error you can make a change in a typescript file and save it and then it starts webpack and works. Well works for me and I'm using angularfire2 2.0.0-beta.6 and firebase 3.6.4

**Comment by unboxedsolutions** [comment]
"Delete the firebase.d.ts in the folder node_modules\firebase"

https://github.com/driftyco/ionic-cli/issues/1713#issuecomment-267753479
