### ISSUE TITLE
Android Build falied after adding Crosswalk

### ISSUE THREAD

**Issue by Que8549** [driftyco/ionic-cli#178]
Got excited about Ionic adding Crosswalk and now my project won't build. Here's my info:

Your system information:

OS: Windows 8
Node Version: v0.10.32
Cordova CLI: 4.2.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.1

WARNING [Project: :org.apache.cordova.engine.crosswalk:<app>382300-xwalk_core_library] Current NDK support is deprecated.  Alternative will be provided in the future.

:mergeDebugResourcesC:\Users\<project path>\platforms\android\build\intermediates\exploded-aar\android.org.apache.cordova.engine
.crosswalk\rsgapp382300-xwalk_core_library\unspecified\debug\res\drawable-hdpi-v4\color_picker_advanced_select_handle.png ERROR: Unable to open PNG file

Error: Failed to run command:
        C:\Users\<username>\AppData\Local\Android\sdk\build-tools\21.0.2\aapt.exe s-i C:\Users\<project  path>\platforms\android\build\intermediates\exploded-aar\android.org.apache.cordova.engine.crosswalk\<app> 382300-xwalk_core_library\unspecified\debug\res\drawable-hdpi-v4\color_picker_advanced_select_handle.png -o C:\Users\<project path>\platforms\android\build\intermediates\res\debug\drawable-hdpi-v4\color_picker_advanced_select_handle.png

Error Code:
        42
Output:
        C:\Users\<project path>\platforms\android\build\intermediates\exploded-aar\android.org.apache.cordova.engine.crosswalk\<app>382300-xwalk_core_library\unspecified\debug\res\drawable-hdpi-v4\color_pick
er_advanced_select_handle.png ERROR: Unable to open PNG file

:mergeDebugResources FAILED

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':mergeDebugResources'.
> Error: Failed to run command:
        C:\Users\AppData\Local\Android\sdk\build-tools\21.0.2\aapt.exe s
-i C:\Users\<project path>\platforms\android\build\intermediates\exploded-aar\android.org.apache.cordova.engine.crosswalk\<app>
382300-xwalk_core_library\unspecified\debug\res\drawable-hdpi-v4\color_picker_advanced_select_handle.png -o C:\Users\<project path>\platforms\android\build\intermediates\res\debug\drawable-hdpi-v4\color_picker_advanced_select_handle.png
Error Code:
        42
Output:
        C:\Users\<project path>\platforms\android\build\intermediates\exploded-aar\android.org.apache.cordova.engine.crosswalk\<app>382300-xwalk_core_library\unspecified\debug\res\drawable-hdpi-v4\color_picker_advanced_select_handle.png ERROR: Unable to open PNG file

**Comment by Que8549** [comment]
I got the answer on stackoverflow.com http://stackoverflow.com/questions/27946793/android-build-failed-after-adding-crosswalk-to-ionic 

It seems that my project path was too long more than 256 characters. I placed the project under C:\ and it built successfully.

**Comment by jbavari** [comment]
Thanks for reporting the error @Que8549 

This may be useful for others as well.
