### ISSUE TITLE
Generate and include in app.module.ts

### ISSUE THREAD

**Issue by NiltonFelicio** [driftyco/ionic-cli#1784]
No error.
Only one function request.

It would be possible? Example: generate page and the file would automatically be included in app.module.ts. Or generate component and the file would automatically be included in app.module.ts. Cli Angular works this way.

**Comment by IroNEDR** [comment]
I am currently working on doing this for my own project. If you have already scripted something yourself let me know.

**Comment by NiltonFelicio** [comment]
Did I post in the wrong place?
I thought this was from the CLI.

Should I close this problem?

**Comment by IroNEDR** [comment]
Hey @NiltonFelicio sorry for answering so late.
So when I search for the term "generate" in the issues I found this: https://github.com/driftyco/ionic-cli/issues/1728
this issue was moved to the link that I have posted before.

**Comment by NiltonFelicio** [comment]
#1728
