### ISSUE TITLE
deviceready did not fire within 2000ms. 

### ISSUE THREAD

**Issue by rainygoblin** [driftyco/ionic-cli#1790]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

V2.1.17
#### Short description of the problem:
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode. cordova.js:1223 
deviceready has not fired after 5 seconds. main.js:104706 
Native: deviceready did not fire within 2000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.(anonymous function) @ main.js:104706
t.invokeTask @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3e.args.(anonymous function) @ polyfills.js:2 main.js:104701 
**DEVICE READY FIRED AFTER 8636 ms**

#### What behavior are you expecting?
Device Ready costs a long time.

**Steps to reproduce:**
1. On the Mac, lastest npm.
2. >ionic start cutePuppyPics --v2
3.> cd cutePuppyPics
4.> ionic platform add android 
5.> ionic run android

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
This issue is more relevant to the framework. Please follow this thread/issue on speeding up initial loading. https://github.com/driftyco/ionic/issues/6776

**Comment by rogeliotrejo13** [comment]
I have a problem similar when run app in android, debug and release version

main.js:110393 Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them.

Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.3 Build version 8E162
