### ISSUE TITLE
"Ionic Serve" Error - Please Help Me!!

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic-cli#1793]
Mac-mini-de-teste:eventos Devign$ ionic serve --l

Running 'serve:before' npm script before serve

> ionic-hello-world@ watch /Users/teste/Desktop/Ionic/eventos
> ionic-app-scripts watch

/Users/teste/Desktop/Ionic/eventos/node_modules/node-sass/lib/index.js:13
    throw new Error(errors.unsupportedEnvironment());
    ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (51)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.10.1
    at Object.<anonymous> (/Users/teste/Desktop/Ionic/eventos/node_modules/node-sass/lib/index.js:13:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/teste/Desktop/Ionic/eventos/node_modules/@ionic/app-scripts/dist/sass.js:11:19)
    at Module._compile (module.js:571:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/teste/Desktop/Ionic/eventos/npm-debug.log
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Mac-mini-de-teste:eventos Devign$ ionic info
--------------------------------
--------------------------------

Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: Mac OS X El Capitan
Node Version: v7.3.0
Xcode version: Xcode 8.2 Build version 8C23

**Comment by jthoms1** [comment]
No exact evidence on this and I couldn't find much, but that said I am pretty sure the version of node-sass being installed does not work with node 7.3.  Try switching to use the latest LTS node and the problem will probably resolve. https://nodejs.org/en/download/

**Comment by ptmagalhaes** [comment]
But my node version is node v7.3.0. is the last

**Comment by ptmagalhaes** [comment]
Now i see this error::

Mac-mini-de-teste:eventos Devign$ ionic serve

Running 'serve:before' npm script before serve

> ionic-hello-world@ watch /Users/teste/Desktop/Ionic/eventos
> ionic-app-scripts watch

[12:00:02]  ionic-app-scripts 0.0.48
[12:00:02]  watch started ...
[12:00:02]  build dev started ...
[12:00:02]  watch failed: "main.dev.ts" and "main.prod.ts" have been deprecated. Please create a new file "main.ts"
            containing the content of "main.dev.ts", and then delete the deprecated files. For more information, please
            see the default Ionic project main.ts file here:
            https://github.com/driftyco/ionic2-app-base/tree/master/src/app/main.ts
[12:00:02]  ionic-app-script task: "watch"
[12:00:02]  Error: "main.dev.ts" and "main.prod.ts" have been deprecated. Please create a new file "main.ts" containing
            the content of "main.dev.ts", and then delete the deprecated files. For more information, please see the
            default Ionic project main.ts file here:
            https://github.com/driftyco/ionic2-app-base/tree/master/src/app/main.ts

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: `ionic-app-scripts watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/teste/Desktop/Ionic/eventos/npm-debug.log
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
I recent change occured in `ionic-app-scripts`. 
```
Please create a new file "main.ts" containing the content of "main.dev.ts", and then delete  the deprecated files.
```

Rename the `src/app/main.dev.ts` file to `src/app/main.ts` and then delete `src/app/main.prod.ts`.
