### ISSUE TITLE
Please Help Me!!!    Error watch failed: "main.dev.ts".  

### ISSUE THREAD

**Issue by ptmagalhaes** [driftyco/ionic-cli#1794]
Mac-mini-de-teste:eventos Devign$ ionic serve

Running 'serve:before' npm script before serve

ionic-hello-world@ watch /Users/teste/Desktop/Ionic/eventos
ionic-app-scripts watch
[12:00:02] ionic-app-scripts 0.0.48
[12:00:02] watch started ...
[12:00:02] build dev started ...
[12:00:02] watch failed: "main.dev.ts" and "main.prod.ts" have been deprecated. Please create a new file "main.ts"
containing the content of "main.dev.ts", and then delete the deprecated files. For more information, please
see the default Ionic project main.ts file here:
https://github.com/driftyco/ionic2-app-base/tree/master/src/app/main.ts
[12:00:02] ionic-app-script task: "watch"
[12:00:02] Error: "main.dev.ts" and "main.prod.ts" have been deprecated. Please create a new file "main.ts" containing
the content of "main.dev.ts", and then delete the deprecated files. For more information, please see the
default Ionic project main.ts file here:
https://github.com/driftyco/ionic2-app-base/tree/master/src/app/main.ts

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v7.3.0
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ watch: ionic-app-scripts watch
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ watch script 'ionic-app-scripts watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! ionic-app-scripts watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /Users/teste/Desktop/Ionic/eventos/npm-debug.log
Caught exception:
undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jthoms1** [comment]
I replied to this issue in https://github.com/driftyco/ionic-cli/issues/1793.

**Comment by nidhivc** [comment]
I also face same error
