### ISSUE TITLE
[Feature] Allow to see the used crosswalk version

### ISSUE THREAD

**Issue by apavillet** [driftyco/ionic-cli#181]
New CLI with crosswalk integration is awesome, to be sure the version of crosswalk is installed would it be possible to add a command to check it ?

Thanks

**Comment by jbavari** [comment]
@apavillet  - Yep, this is easy to implement. I'll add it in ASAP.

**Comment by jbavari** [comment]
@apavillet - i've [committed this](https://github.com/driftyco/ionic-cli/commit/b8d482350928944b4c65e0009bc497253fc962a9) this in my v1_3_3 branch i'm working on. It should be rolling out very soon.

**Comment by apavillet** [comment]
Thanks a lot ! :)

**Comment by jbavari** [comment]
This is out in 1.3.3! Try it out!

**Comment by apavillet** [comment]
Thanks i'll try it !
