### ISSUE TITLE
ionic resources upload issue

### ISSUE THREAD

**Issue by n40jpj** [driftyco/ionic-cli#183]
I'm having issues using ionic resrouces, I have used the psd templates, and produced pngs, both of which have failed to upload.  The first time I did this about 2 weeks ago worked like a charm but trying over the last couple of days it's failed each time, my system info is as follows

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.32
Cordova CLI: 4.1.2
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.0.0 

ionic resources
Ionic icon and splash screen resources generator 
 uploading icon.psd...
 uploading android/splash.png...
 uploading ios/splash.png...
 ✗ Error parsing upload response: 

I have tried creating a new project from scratch but I'm getting no joy.

**Comment by softBarbarian** [comment]
Same here!!!

Here is the `ionic info` output:
```
OS: Mac OS X Yosemite
Node Version: v0.10.34
Cordova CLI: 4.1.2
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1 
```

**Comment by softBarbarian** [comment]
Here is my terminal output:
Ionic icon and splash screen resources generator 
 uploading icon.png...
 uploading splash.png...
 ✗ Error parsing upload response:

**Comment by softBarbarian** [comment]
Not sure if this matters but @n40jpj 's images are psd, and mine are png

**Comment by n40jpj** [comment]
I've used both image types, and images that worked a couple of weeks ago if that helps narrow down the issue

**Comment by softBarbarian** [comment]
Please see #180 for more details. However that issue was closed, but people still experiencing `parse erorr`.

Anything i can do to help?

**Comment by n40jpj** [comment]
I tried updating ionic and running again but still no joy, is there any further info I can supply to find the issue and resolve it?

**Comment by zckrs** [comment]
@adamdbradley Body response returned by service is empty. Then `JSON.parse(body)` throw `Error parsing upload response`

**Comment by jbavari** [comment]
Thanks for reporting it.

We've got a hunch that it is the back end service handling the resources, rather than the CLI. Hang tight while we get it fixed up.

**Comment by adamdbradley** [comment]
Should be fixed now, thanks
