### ISSUE TITLE
[Feature] Add the missing plugin update function

### ISSUE THREAD

**Issue by crissi** [driftyco/ionic-cli#184]
It would be nice if ionic implemented at update function for plugins

So we could write:
ionic plugin update <plugin name>

instead of the way we have to do it today:
ionic plugin remove <plugin name>
ionic plugin add <plugin name>

**Comment by jbavari** [comment]
This looks like something I can tackle in the near future. Thank you for the suggestion.

**Comment by jbavari** [comment]
@crissi This is now available in a sorts using the `ionic state` command.

First populate your package.json file with a `cordovaPlugins` attribute and list the plugin `id`'s you want, then just run `ionic state reset`.
