### ISSUE TITLE
Better gulpfile.js

### ISSUE THREAD

**Issue by josephfinlayson** [driftyco/ionic-cli#189]
I'd like to see a more advanced gulpfile (which e.g. features gulp-inject, and angular filesort) which encourages more modular app development. Would you accept PRs on this? Where is the template located?

**Comment by jbavari** [comment]
@josephfinlayson - I would take PRs. This is something we've been eyeing for a while, our focus has been more on the framework side of things.

The starter template can be found at [this repository](https://github.com/driftyco/ionic-app-base)
