### ISSUE TITLE
Ionic start seems to be incompatibel with ionic serve

### ISSUE THREAD

**Issue by ch-weiss** [driftyco/ionic-cli#1898]
#### Short description of the problem:
If I follow the steps described in getting started to create a new app with ionic start and lauch myApp with ionic serve then the terminal commands are not shown nor is it possible to type any terminal commands like q for quitting. But the app is running in the browser.
If I lauch an app created with an earlier version of ionic cli then ionic serve works as expected.

#### What behavior are you expecting?
The terminal command are listed and available for apps created with ionic start of the current cli version.

**Steps to reproduce:**
1. Try a clean install of Node, Cordova and Ionic. For doing this follow the steps described in getting started to create a the standard tabbed myApp:
https://ionicframework.com/getting-started/

2. Change to the new app directory and launch the app with ionic serve. The terminal does not show the possible commands nor does it accept further commands

**Post the output of `ionic info` below please**
The problem occurs on Windows 10 as well as on MacOs Sierra
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.5
Xcode version: Not installed

or 
Cordova CLI: Not installed
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002

**Other information:**
After ionic serve the terminal looks like this (no commands listed nor possible):
```
C:\Users\ch-weiss\Documents\Projekte\myApp>ionic serve
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

> ionic-hello-world@ ionic:serve C:\Users\ch-weiss\Documents\Projekte\myApp
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

[21:05:09]  ionic-app-scripts 1.0.0
[21:05:10]  watch started ...
[21:05:10]  build dev started ...
[21:05:11]  clean started ...
[21:05:11]  clean finished in 15 ms
[21:05:11]  copy started ...
[21:05:11]  transpile started ...
[21:05:18]  transpile finished in 7.19 s
[21:05:18]  webpack started ...
[21:05:18]  copy finished in 7.61 s
[21:05:29]  webpack finished in 11.28 s
[21:05:29]  sass started ...
[21:05:31]  sass finished in 1.59 s
[21:05:31]  build dev finished in 20.28 s
[21:05:31]  watch ready in 20.52 s
[21:05:31]  dev server running: http://localhost:8100/

```

**Comment by danbucholtz** [comment]
`ionic serve` functionality was changed to be simplified. I think the behavior is working as intended.
It should build you project and establish a live-reloading server for you to build out your application.

Please let me know if that's not the case.

Thanks,
Dan

**Comment by globalepub** [comment]
Can you check your app on **http://localhost:8100/** or  **http://localhost:8100/ionic-lab**?
To have another terminal for your commands please open a new or use your **Visual Studio Code** by opening your project in **Command Prompt**

**Comment by ch-weiss** [comment]
@danbucholtz, @globalepub: Thank you very much for your help!
Currently I am using Ionic cli version 2.2.1. The app is being served, this is not the problem. But I am not able to quit it anymore in the terminal window using q. Nor does the terminal window list the possible commands as it did before or accept other commands.

Here is my Ionic info:

> Cordova CLI: Not installed
> Ionic Framework Version: 2.0.0-rc.5
> Ionic CLI Version: 2.2.1
> Ionic App Lib Version: 2.2.0
> Ionic App Scripts Version: 1.0.0
> ios-deploy version: 1.9.0
> ios-sim version: 5.0.13
> OS: macOS Sierra
> Node Version: v6.9.2
> Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by danbucholtz** [comment]
We deprecated that functionality. Please use command-c or control-c. Those will exit the process.

Thanks,
Dan

**Comment by ch-weiss** [comment]
@danbucholtz Well, then it works as expected ;-) 

Thanks for the hint and for sharing your time,
Chris
