### ISSUE TITLE
Add www/css/ionic.app.* to .gitignore

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic-cli#190]
`ionic start myproject blank --sass` sets up a gulp workflow to automatically generate css files (`www/css/ionic.app.css` and `www/css/ionic.app.min.css`) from a source sass file (`scss/ionic.app.scss`). It also includes a .gitignore file with various sensible defaults.

`.gitignore` could include `www/css/ionic.app.*` (or perhaps rather: name both files explicitly), since it is generally a more useful workflow to track changes in the .scss file and let the other files follow implicitly from there, than to track all three files (redundant, unnecessarily involving a build each time, slightly confusing as to which files you're supposed to edit).

**Comment by jbavari** [comment]
@tomsun - I agree. The same could be said for the platforms and plugins folders, since they are (mostly) generated as well.

This feels very much like a preference thing - some prefer to check in everything, and some are picky. 

Let me talk to the team about this and see what the pulse is.
