### ISSUE TITLE
[V3] Need to manually add @ionic/cli-plugins-core to project on Windows

### ISSUE THREAD

**Issue by jsayol** [driftyco/ionic-cli#1924]
CLI version: 3.0.0-alpha.106
App-scripts version: 1.1.2

#### Short description of the problem:
When running `ionic serve` on Linux I get a nice prompt telling me the `@ionic/cli-plugin-core` plugin is missing and offering to install it. If I do the same on a Windows machine I just get an npm error telling me that said package couldn't be found:

```
C:\path\to\project>ionic serve
Dependency missing for @ionic/cli-plugin-core:

  [ERROR]: Cannot find module 'C:\path\to\project\node_modules\@ionic\cli-plugin-core'
```

#### What behavior are you expecting?
Same as on Linux.
If for any reason that's not possible, then maybe a more explicit error message giving instructions on how to proceed. For example, the same one you get if you answer "no" to the prompt on Linux:

```
$ ionic serve
? This command's plugin @ionic/cli-plugin-core is not installed would you like to install it and continue? No
[ERROR] This plugin is not currently installed. Please execute the following to install it.
        
            npm install --save-dev @ionic/cli-plugin-core@canary
```

**Steps to reproduce:**
1. Be on Windows
2. `npm -g i ionic@3.0.0-alpha.106`
3. `ionic serve`

**Post the output of `ionic info` below please**
Win:
```
  Your system information:

    Cordova CLI: 6.4.0
    Ionic Framework Version: 2.0.1
    Ionic CLI Version: 3.0.0-alpha.106
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.3.0
    Xcode version: Not installed
```

Linux:
```
  Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.0.1
    Ionic CLI Version: 3.0.0-alpha.106
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.9
    Node Version: v7.5.0
    Xcode version: Not installed
```

**Comment by jsayol** [comment]
As a side note, what's the reason of having to install a CLI plugin on the project itself instead of globally?

**Comment by jsayol** [comment]
As a second side note, the rewrite of the CLI rocks! I've been trying it out and, overall, everything works fine. Great job 👌

**Comment by jthoms1** [comment]
In future versions we have removed cli-plugin-core and integrated it into the base CLI install.  This will be released in beta3.  Closing this for now.
