### ISSUE TITLE
[V3] cordova:platform always prompts

### ISSUE THREAD

**Issue by jsayol** [driftyco/ionic-cli#1933]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.1

#### Short description of the problem:
Running `ionic cordova:platform` always prompts for a platform even if one is supplied:
```
$ ionic cordova:platform remove ios
? What platform would you like to add (ios, android): android
✔ Executing cordova command: cordova platform remove android --save - done!
```

Besides that, the prompt always says "add" even if the action was to "remove". The right action takes place, though.

#### What behavior are you expecting?
 No prompt if platform is provided

```
  Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.0.1
    Ionic CLI Version: 3.0.0-beta.1
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.9
    Node Version: v7.5.0
    Xcode version: Not installed
```

**Comment by jthoms1** [comment]
Fix will be in beta2.
