### ISSUE TITLE
cordova:resources hangs indefinitely if no platform is added

### ISSUE THREAD

**Issue by seiyria** [driftyco/ionic-cli#1934]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.1

#### Short description of the problem:
If you have created a new project but added no platforms and try to generate resources, cordova:resources will hang and you need to ctrl-c to cancel it.

#### What behavior are you expecting?
It spits out an error message, it should also probably not try to generate resources.

**Steps to reproduce:**
1. ionic start myapp blank
2. ionic cordova:resources -i -s

**Post the output of `ionic info` below please**
  Your system information:

    Cordova CLI: 6.3.1 
    Ionic Framework Version: 2.0.1
    Ionic CLI Version: 3.0.0-beta.1
    ios-deploy version: 1.9.0 
    ios-sim version: 3.1.1 
    OS: OS X El Capitan
    Node Version: v6.5.0
    Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by jthoms1** [comment]
Fixed and will be released in beta2.
