### ISSUE TITLE
cordova:resources for browser platform

### ISSUE THREAD

**Issue by seiyria** [driftyco/ionic-cli#1935]
It would be nice to also be able to generate resources for the browser platform and have that be considered when serving or building the application in a non-lab setting. It would be nice if it generated similarly to [real favicon generator](http://realfavicongenerator.net/) which generates for every possible platform, size, etc.

**Comment by dwieeb** [comment]
@seiyria This has been added along the way. Please try the latest release: 3.0.0-rc.2

**Comment by cdelgadob** [comment]
@dwieeb How does it work? I can generate all resources for ios and android from spalsh.png and icon.png, but nothing is generated for the browser.

In the docs there's nothing related to browser support neither: https://ionicframework.com/docs/cli/cordova/resources/

I am running Ionic CLI v3.10.3 and Cordova v7.0.1

Thanks!

**Comment by dwieeb** [comment]
@cdelgadob I actually don't know what I was talking about. We don't support the browser platform, officially. See this issue: https://github.com/ionic-team/ionic-cli/issues/2312
