### ISSUE TITLE
ionic build:cordova ios --prod

### ISSUE THREAD

**Issue by wbhob** [driftyco/ionic-cli#1937]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.1

#### Short description of the problem:
I am trying to build an app for production with the new CLI, but I don't know how. Apparently, `--prod` is not a valid flag anymore.

#### What behavior are you expecting?
A production build that is optimized.

**Steps to reproduce:**
1. ionic cordova:build ios --prod
```
ionic cordova:build ios --prod
```

**Post the output of `ionic info` below please**
   Cordova CLI: 6.5.0
    Ionic Framework Version: 2.0.1-201702212251
    Ionic CLI Version: 3.0.0-beta.1
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.9.4
    Xcode version: Xcode 8.2.1 Build version 8C1002

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Please install 3.0.0-beta.2. Released a few days ago. This issue is resolved in that release.

https://github.com/driftyco/ionic-cli/tree/v3#latest-beta-release-versions
