### ISSUE TITLE
OPTIONS 405 (Method Not Allowed)The requested resource does not support http method 'OPTIONS'

### ISSUE THREAD

**Issue by gayathri777** [driftyco/ionic-cli#1938]
I don't know why I'm getting this 405 response. I tried to do a GET request with postman with the same information and it worked, but it doesn't work with my Angular2 code.
![image](https://cloud.githubusercontent.com/assets/16623094/23259322/8908b70a-f9f2-11e6-830b-4ad193f5cd8d.png)
![image](https://cloud.githubusercontent.com/assets/16623094/23259326/8c630cca-f9f2-11e6-8c42-0b4e79380159.png)

Here's my angular service:

![image](https://cloud.githubusercontent.com/assets/16623094/23259334/96fb9fda-f9f2-11e6-86d2-91facc9e49fd.png)

and here's the error I'm getting when I run the ionic app(in Google Chrome or FireFox) and working fine in IE(Internet Explorer):

![image](https://cloud.githubusercontent.com/assets/16623094/23259340/a119f8ea-f9f2-11e6-9fdb-12f6309bf7f8.png)

**Comment by jthoms1** [comment]
Sorry, but this issue is not related to the Ionic CLI. You might be able to get help on our forums. https://forum.ionicframework.com/
