### ISSUE TITLE
ionic resources 9-patch

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic-cli#194]
Please add the possibility to create 9-patch android splash screens via ionic resources 

http://developer.android.com/tools/help/draw9patch.html

**Comment by rvanbaalen** [comment]
Why would you need that if the ionic resources command already generates all possible screen sizes?

**Comment by schnti** [comment]
9-Patch is the recommended format for phonegap apps.
https://github.com/phonegap/phonegap/wiki/App-Splash-Screen-Sizes

Often generated images are stretched or compressed on special android screen sizes.

**Comment by joshbuchea** [comment]
+1 for 9-patch Android splash screen images please

**Comment by guanxun** [comment]
+1, testing on a Nexus 4 (15:9 aspect ratio) shows a `ionic resources`-generated splash screen displayed in a vertically compressed fashion.

**Comment by guanxun** [comment]
How I'm working around this right now is:

1) Creating my own 9-patch versions of each density.
2) Manually replacing the `screen.png`s for each density in `/platforms/android/res/` with `screen.9.png`.
3) Updating `config.xml` with updated filenames.

**Comment by piernik** [comment]
+1

**Comment by murilloflores** [comment]
+1

**Comment by malaniz** [comment]
+1

**Comment by gastoncesarf** [comment]
+1

**Comment by rvanbaalen** [comment]
All these +1's only add noise to the conversation. 

How exactly would you expect `ionic resources` to generate a 9-patch image, @schnti? Generating all assets based on a high res image easily done in an automated program but generating a 9 patch image needs custom ajustments for each splashscreen. I don't see how an automated tool could do that.

You're not forced to use `ionic resources` -- just add your 9-patch splashscreens manually and you're good to go.

**Comment by Torquin** [comment]
Something like this : http://community-sites.fr/9patch/ ?

**Comment by joshbuchea** [comment]
I don't see why it wouldn't be possible to generate a 9 patch image with an automated tool. Assuming a splash screen with a centered logo/image and solid background color...

**Comment by m-vdv** [comment]
+1
