### ISSUE TITLE
ionic package command:  Add support for setting version and note 

### ISSUE THREAD

**Issue by ncapito** [driftyco/ionic-cli#1942]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
2.2.1

#### Short description of the problem:
This is an enhancement request. It would be nice when creating a "package".  e.g. `ionic package build ios --profile prod --release`  to be able to attach a note or version via command line .  Currently all packages are uploaded with the message: "Ionic Package Upload"

#### What behavior are you expecting?
Right now we run the package command.  Go to the ionic.io cloud site.  We then go to the deploy tab and click edit.  On that modal they give you options to "add a note" which defaults to "Ionic Package Upload".  In our case we change the note to "<PROFILE> <VERSION>".  e.g. "Test 1.2.1" or  "Prod 1.2.1".  The next thing we do is then update the Version tab and set the version.  It would be nice for this to be pulled from the version in the cordova.xml file.  Our ideal state is to set the version based on cordova.xml and then we can set the note when we run the package command:

`ionic package build ios --profile prod --release --note "Test 1.2.3 ` 

**Steps to reproduce:**
1. ionic package build ios --profile prod --release
2. go to your ionic.io site and look at what was uploaded

**Comment by ncapito** [comment]
Where is the documentation for some of the api's that ionic-app-lib/package.js references?  I'm trying to find out what  the package/build api accepts in the post.


lib/package.js:sendToPackageServie(390)

  url: settings.IONIC_DASH_API + 'apps/' + appId + '/package/builds/',

**Comment by jthoms1** [comment]
https://docs.ionic.io/services/package/#building

**Comment by ncapito** [comment]
That does not show how to add a note @jthoms1 ?

**Comment by jthoms1** [comment]
Sorry that was in reference to not finding the documentation. @dwieeb Do you have any information on whether this could be intetegrated into the CLI?

**Comment by ncapito** [comment]
I think I saw something similar in the upload command.  I can find the file
and line number.

**Comment by kaszona** [comment]
"version": ""

add this leaving blank.

**Comment by ncapito** [comment]
@kaszona  what does your comment mean?

**Comment by kaszona** [comment]
leave this  blank. No need to add any version there.

**Comment by kaszona** [comment]
Either you can write there like this **"version": "1.0.0"**

**Comment by dwieeb** [comment]
@ncapito @kaszona This functionality will be in the latest beta release of CLI v3 soon. Good idea!

**Comment by ncapito** [comment]
@dwieeb  i just used this!  Thanks again.  Such a helpful change.

**Comment by dwieeb** [comment]
@ncapito You're welcome 😄 Thanks for following up. I'll close the issue.
