### ISSUE TITLE
Allow passing --prod to the  ionic-app-scripts build command

### ISSUE THREAD

**Issue by ncapito** [driftyco/ionic-cli#1943]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
2.2.0

#### Short description of the problem:
When we are running our prepare command:  `ionic build ios --prod `  one of the first thing ionic build does is perform a `ionic-app-scripts` build.  Our issue is the  --prod command is not being passed to the app scripts build command.  So whenever we want to do a prod build vs a debug build we have to modify our npm build script and include / or remove the flags.

#### What behavior are you expecting?
We expect executing:  

` ionic build ios --prod ` to spawn `ionic-app-scripts build ios --prod` 

or

` ionic build ios --debug ` to spawn `ionic-app-scripts build ios --debug` 

**Steps to reproduce:**
1. execute any of the above commands and notice the output:
"build prod started .."

or 

"build dev started .."

Will display.

```
#package.json file: 
"scripts": {
    "build": "ionic-app-scripts build",
    "emulate": "ionic emulate ios --release --prod --target=iPad-Air-2",
    "watch": "ionic-app-scripts watch",
    "serve": "ionic-app-scripts serve",
    "package-dev": "ionic package build ios --profile dev --debug",
    "copy": "ionic-app-scripts copy",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build"
  },

```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by ncapito** [comment]
Ugh, in trying to create a PR for this i checked a look at the code and all i needed to do was create an "ionic:build" command.  The other issue was i had build:before: build and that was causing it to call the default build command.  



Where is the documentation for suggested npm scripts or how this is supposed to work?

**Comment by jthoms1** [comment]
https://github.com/driftyco/ionic-app-scripts#npm-scripts

**Comment by ncapito** [comment]
@jthoms1  I'm assuming you are talking about:

>Instead of depending on external task runners, Ionic App Scripts now prefers being executed from npm scripts. Ionic's npm scripts come preconfigured in the project's package.json file. For example, this is the default setup for npm scripts in each starter:

That does not do justice to the issue I was having.    If there was something out there that described what happens when i type in `ionic build` it would have bypassed me needing to go into ionic-cli to figure out what happens when i run the command.   The reality is `ionic build` is dependent on the configuration of your npm scripts.  If it's not configured correctly it's going to end up frustrating people and not everyone is going to dive into the source to figure out how to use it.  

Please dont take any of this the wrong way, I'm not trying to be rude / mean and I also dont know what the future is of the `ionic-cli` project so if everything is moving to just using app-scripts this convo might be moot.
