### ISSUE TITLE
CLI Generate Function Is Case Sensistive

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic-cli#1946]
So I tried to run **ionic g page myPageComponent** it works just as it should.

However, I tried to run the same command this way **ionic g Page myPageComponent** and the CLI got very confused. The difference was that the P was uppercase. Can anyone please refer me to the place in the CLI where the params are gotten so I can just call a sanitization method that sanitizes params to lowercase to fix this?

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-generators#9
