### ISSUE TITLE
Can't start a new project

### ISSUE THREAD

**Issue by JaviRpo** [driftyco/ionic-cli#1947]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
ionic -> 2.1.0
npm -> 4.1.2
node -> v7.6.0

#### Short description of the problem:
I'm trying to start a project with template  *super* like in the url explain `https://ionicframework.com/docs/v2/intro/tutorial/` but I have this problem
![image](https://cloud.githubusercontent.com/assets/8562436/23336601/58bad7f2-fba2-11e6-92a6-dbfbd58d2af0.png)

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
https://github.com/driftyco/ionic-starter-super

The super starter requires Ionic CLI 2.1.18 or greater.
