### ISSUE TITLE
ionic resources phonegap build support

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic-cli#195]
Please add to `ionic resources`  phonegap build support.

PhoneGap Build requires different attributes:

Cordova example:
```
<platform name="android">
  <splash src="resources/android/splash/drawable-land-ldpi-screen.png" density="land-ldpi"/>
</platform>
```

PhoneGap Build example:
```
<gap:splash gap:density="ldpi" src="res/android/splash/drawable-land-ldpi-screen.png" gap:platform="android" gap:qualifier="land-ldpi" />
```

**Comment by jbavari** [comment]
I'll see what I can do about this. I've got some other issues to address first.

I do accept PR's though :)
