### ISSUE TITLE
ionic serve and ionic serve --lib command not launching browser in ionic cli beta 4

### ISSUE THREAD

**Issue by vksgautam1** [driftyco/ionic-cli#1960]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
     Cordova CLI: 6.5.0
    Ionic Framework Version: 2.1.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.10.0
    Xcode version: Not installed

#### Short description of the problem:
i am using ionic serve command and it is showing

E:\PiderWeb>ionic serve
✔ Starting server - done!
but it is not launching browser

same for command ionic serve --lib 

#### What behavior are you expecting?
 want that same behavior from command which we used to get in ionic cli 2.2

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
@vksgautam1 Take a look at the docs.  There was a significant change to plugins between beta3 and beta4.  You need to run `npm install --save-dev @ionic/cli-plugin-ionic-angular` within your project directory to resolve.

https://github.com/driftyco/ionic-cli/tree/v3#upgrading-from-a-previous-beta-release-to-beta4
