### ISSUE TITLE
Automatic builds fail because of rxjs

### ISSUE THREAD

**Issue by FunnyGhost** [driftyco/ionic-cli#1962]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
2.1.14

#### Short description of the problem:
Automatic builds fail

#### What behavior are you expecting?
On a CD/CI server, when I push I want the app to run npm install and not fail

**Steps to reproduce:**
1. Create new project
2. Push to a CD/CI server( I use BitBucket with Pipelines) - free service
3. Enable Pipelines
4. Use the default build script that just runs npm install
5. The process will start and it will fail

```
npm info postinstall ionic-hello-world@
npm info prepublish ionic-hello-world@
npm ERR! Linux 4.9.9-coreos-r1
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package rxjs@5.0.0-beta.12 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.2.1 wants rxjs@5.0.0-beta.12
```

**Post the output of `ionic info` below please**
Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 2.1.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1
ios-deploy version: Not instal
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.2.0
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
This is most likely an issue with using npm2.  You should be using npm3 on your CI server. Peer dependencies are handled different in npm3 should not provide this error with your CI server.
