### ISSUE TITLE
Error while ionic start - "There was an error with the spawned command: npminstall"

### ISSUE THREAD

**Issue by RElric** [driftyco/ionic-cli#1965]
Hi,

I searched an answer but don't find any concrete solution to my problem.
I work on Linux Ubuntu (latest) and on Windows 10 as well on DualBoot.

Commands that doesn't work
* ionic start
* ionic start projectName
* sudo ionic start
* sudo ionic start projectName

#### What version of softwares are you using?

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.6.0
Xcode version: Not installed

#### Short description of the problem:

When I try to create a new project with CLI passing his name, I have this issue:
Creating an Ionic app in /mydocs/APP/testIonic based on the tabs template.

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
Installing npm packages (may take a minute or two)...
Running exec command: npminstall
Spawn command completed
Error with start undefined
Error Initializing app: There was an error with the spawned command: npminstall
There was an error with the spawned command: npminstall

When i try with ionic start wizard, after a few minutes it return "undefined" in red on the webpage.

#### What behavior are you expecting?
Try to create a project.

---

I have got any more informations as a npmdebug.log or anything. The folder exists and there's some files in it.

**Comment by RElric** [comment]
My windows ionic info

******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please update your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

Your system information:

Cordova CLI:
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed


******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please update your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

**Comment by RElric** [comment]
Cordova is installed but ionic don't want to give me version, may be an installation problem

**Comment by RElric** [comment]
Hi, I'm upping this issue because I still have the problem.

**Comment by ray925** [comment]
I have same problem....

**Comment by ray925** [comment]
I fexed it is. useing "npm cache clean"  and then "ionic start myApp --v2"

**Comment by RElric** [comment]
It's finally working.

To make it work, I just have to set my global node_modules folder restrictions to 777. It can be an issue for security.

However, thank you.
Elric Reffuveille
