### ISSUE TITLE
ionic 2 generator filenames don't follow naming conventions

### ISSUE THREAD

**Issue by jaufgang** [driftyco/ionic-cli#1968]
When you create a component, page, service, etc with the cli generator, the filenames of the TypeScript files do not follow the naming conventions recommended in the official [Angular Style Guide](https://angular.io/docs/ts/latest/guide/style-guide.html), in particular [Style 02-02](https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-02) and [Style 02-03](https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-03).  The files are missing the conventional suffix for the file type.  

This may not be a crucial or pressing issue, but for the sake of promoting best practices, I think it would be a good idea for the generator to conform to these standard conventions.

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-generators#14
