### ISSUE TITLE
"WARNING: No target specified" error when running "$ ionic run android"

### ISSUE THREAD

**Issue by sedusa** [driftyco/ionic-cli#197]
Hi everyone,

I followed all the suggestions in issue #179 but still get the **error below** 
when I run `$ ionic run android`

```
Running command: /Users/drsedusa/Desktop/temp/my_app/hooks/after_prepare/010_add_platform_class.js /Users/drsedusa/Desktop/temp/my_app
add to body class: platform-android
Running command: /Users/drsedusa/Desktop/temp/my_app/platforms/android/cordova/run 
WARNING : No target specified, deploying to emulator
WARNING : no emulator specified, defaulting to AVD_for_s4
```

I can't seem to figure out why I get the `WARNING: No target specified` error message even though my <strong>platforms/android</strong> folder seems complete.

![1ffd6556-a09b-11e4-9cf1-9c31c4893d29](https://cloud.githubusercontent.com/assets/5447546/5823826/f1538e7a-a0ad-11e4-85d0-0c82b844f1ea.png)

Below is a copy of my system info.

```
$ ionic info

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.30
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.0.0 
```

I'd really appreciate the help figuring out what's going on.  Thanks!!

**Comment by jbavari** [comment]
Do you have an android device attached or a simulator running?

Something like an AVD or [Genymotion](http://genymotion.com)

**Comment by sedusa** [comment]
@jbavari  I do have Genymotion installed on my machine but I don't have it running nor do I have my Samsung Galaxy S2 attached.  Thanks for the reply :smile: Still trying to figure out what's going on (scratching my head)....grrrr!

**Comment by sedusa** [comment]
@jbavari Here's a log of all the steps I took...just created a new test project.  Thanks for your help. 

```
$ mkdir temp
$ cd temp/
$ ionic start new_app
Creating Ionic app in folder /Users/drsedusa/Desktop/temp/new_app based on tabs project

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s

Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s

Update config.xml
Initializing cordova project
Fetching plugin "org.apache.cordova.device" via plugin registry
Fetching plugin "org.apache.cordova.console" via plugin registry
Fetching plugin "com.ionic.keyboard" via plugin registry

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd new_app

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or visit the Ionic docs: http://ionicframework.com/docs

$ cd new_app/
$ ls
bower.json    gulpfile.js   ionic.project plugins       www
config.xml    hooks         package.json  scss
$ clear

$ ionic browser add crosswalk@10.39.235.15
Adding crosswalk browser

Downloading: https://github.com/driftyco/cordova-crosswalk-engine/archive/v0.8.zip
[=============================]  100%  0.0s

Downloaded cordova-crosswalk-engine

Downloading: https://github.com/driftyco/cordova-android/archive/crosswalk.zip
[=============================]  100%  0.0s

Finished downloading cordova-android v4.0.x

Altered permissions for Android Paths

Downloaded Cordova Android for Crosswalk

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable/10.39.235.15/arm/crosswalk-webview-10.39.235.15-arm.zip

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable/10.39.235.15/x86/crosswalk-webview-10.39.235.15-x86.zip
[=============================]  100%  0.0s
[=============================]  100%  0.0s

Downloaded Crosswalk webviews

Fetching Android SDK API 19.1.0

Downloaded Android runtime (API 19)

Removed old Cordova Android platform

Added Cordova Android 4.0

Added Crosswalk Webview Engine

Ionic Browser Add completed for Crosswalk
$ ionic run android
Running command: /Users/drsedusa/Desktop/temp/new_app/hooks/after_prepare/010_add_platform_class.js /Users/drsedusa/Desktop/temp/new_app
add to body class: platform-android
Running command: /Users/drsedusa/Desktop/temp/new_app/platforms/android/cordova/run 
WARNING : No target specified, deploying to emulator
WARNING : no emulator specified, defaulting to AVD_for_s4
Waiting for emulator...
emulator: ERROR: This AVD's configuration is missing a kernel file!!
^C$ 
```

**Comment by jbavari** [comment]
When you run `ionic run android` - it is trying to run the application on a simulator or a device. If there is not a simulator or device running, you will most likely get that error.

**Comment by sedusa** [comment]
I thought running ** ionic run android ** would launch the crosswalk browser or am I totally confused.  Could you please explain how ionic's crosswalk implementation works.

**Comment by jbavari** [comment]
I think you might be a bit confused on whats going on here.

Crosswalk is simply a browser that runs inside of an android app. Launching an android application has nothing to do with crosswalk. You must be running a device or simulator to 'run' an app.

**Comment by sedusa** [comment]
Thanks for clearing this up for me.  Appreciate it.

**Comment by satish11nov** [comment]
same issue here..i have device connected using usb debugging but getting below error message

![image](https://cloud.githubusercontent.com/assets/5130534/7106832/b1c682a8-e16c-11e4-8ba5-dfe5ae6ae7c5.png)

**Comment by cnmboy** [comment]
@satish11nov solve u r issue?
that's issue can solve to install usb driver :)

**Comment by alexsandracodes** [comment]
@satish11nov , I had the same issue. The problem is that you have to set up an AVD for the android and install the USB drivers. I didn't listen to the directions they gave for me, instead I ran the AVD Manager in the android-sdk folder. 

Here are the references I used to get rid of that error you had:
http://developer.android.com/tools/devices/managing-avds.html
and you also need to enable debugging on the phone:
http://developer.android.com/tools/device.html#setting-up

**Comment by mtpultz** [comment]
Thanks @alexsandracodes I definitely didn't know to do those steps you provided in the links, but I'm still getting this `WARNING : No target specified, deploying to emulator` and `WARNING : no emulator specified, defaulting to Nexus5` where now it loads using my Nexus5 AVD.  I've completed steps 2 and 3 from http://developer.android.com/tools/device.html#setting-up, but I don't know what to do with regards to step 1.  Is the manifest file supposed to be in my ionic project?

**Comment by helmiruza** [comment]
@mtpultz I'm using Genymotion as the emulator. I got the same problem, than I realized that I had to:-
1. Open Genymotion, load the device (I chose Nexus 5), than click play so that a virtual android loads in Genymotion.
2. After its loaded, I opened settings > about phone, and tapped "build number" 7 times to enable the "Developer Options". Developer options was hidden by default, so you have to tap build number to make it available.
3. Go to Developer Options ( Settings > Developer Options) and enable USB Debugging.
4. After its all set, in CMD rerun ionic run android.

Please note that the error comes out because ionic can not find any emulator (which must be turned on, and USB Debugging enabled).

Hope it helps~

**Comment by mtpultz** [comment]
@helmiruza Geez, can you believe it just took a phone reboot...

**Comment by alexsandracodes** [comment]
@mtpultz So, you got it working now?

**Comment by mtpultz** [comment]
Hi @alexsandracodes, yes thanks :)

**Comment by alswamy** [comment]
Restarting the devices works :)

**Comment by askanhan** [comment]
i would write the same with @alswamy :)

althought the device is listed when you write `adb devices`, it cannot be accessed i think. I still see "No target found" message but though its working after restarting.

**Comment by FrEaKmAn** [comment]
in my case I had to disable and reenable developer mode to recognize the connected device...

**Comment by kevinclarkra** [comment]
If it helps, I did adb kill-server, then adb start-server.  I looked at adb-devices and the device was showing again and the app deployed.  Just an alternative to either the two above solutions.  Hope it helps someone too.

**Comment by ifeltsweet** [comment]
Disabling and then re-enabling developer options on the phone made it work again for me.

**Comment by btdevn** [comment]
For me killing and restarting adb server solved the issue
`adb kill-server
adb start-server`
