### ISSUE TITLE
bug(v3): Error after ionic start and other ionic commands

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic-cli#1973]
#### What version of the CLI are you using? Output of `ionic --version`
v3 beta.4

#### Short description of the problem:
after read  your blog I run on a windows system a fresh install with the new installed ionic@beta
In these very rare case I'm  using WINDWOS 10 64bit
I did
```
npm install -g ionic@beta
ionic start ionic3-blank blank
```
After installing everything (which takes a lot) I get this error
```
{ Error: ENOENT: no such file or directory, open 'C:\Users\michi\.ionic\config.json'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\michi\\.ionic\\config.json' }
```

This i the same error I get  launching only `ionic --version ` I get this error also if I launch the ionic help or  anything  else.

If I launch ionic help by doing only `ionic`  outside from a ionic project, which should be valid, someone can need help for start a new projeckt, there  iis also at the beginning an other error
```

{ Error: Cannot find module 'node_modules\@ionic\cli-plugin-cordova'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (C:\Users\michi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:8547:25)
    at Object.<anonymous> (C:\Users\michi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:2179:35)
    at next (native)
    at C:\Users\michi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:2155:71
    at __awaiter (C:\Users\michi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:2151:12)
    at Object.loadPlugin (C:\Users\michi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:2175:12)
    at HelpCommand.<anonymous> (C:\Users\michi\AppData\Roaming\npm\node_modules\ionic\dist\ionic.js:7164:48)
    at next (native) code: 'MODULE_NOT_FOUND' }
```

After all I tried to serve the app, but nothing happens and this  is the  output
```
ionic serve
✔ Starting server - done!
{ Error: ENOENT: no such file or directory, open 'C:\Users\michi\.ionic\config.json'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\michi\\.ionic\\config.json' } 
```

#### What behavior are you expecting?
I think there should not the error for  the **config.json** and I think also the **cli-plugin-cordova** error should not be, it is legit call ionic autside from a project
Probably this errors are only on windows :), I have never used windows do developing anything, and thats the reason why LOL

**Post the output of `ionic info` below please**
```
>ionic info

  Your system information:

    Cordova CLI: Not installed
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.10.0
    Xcode version: Not installed
{ Error: ENOENT: no such file or directory, open 'C:\Users\michi\.ionic\config.json'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\michi\\.ionic\\config.json' }
```

**Comment by tomsun** [comment]
Same here (in a Docker container based on node:6.10)

```
ionic info

  Your system information:

    Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.9
    Node Version: v6.10.0
    Xcode version: Not installed
{ Error: ENOENT: no such file or directory, open '/root/.ionic/config.json'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/.ionic/config.json' }
```

**Comment by jthoms1** [comment]
Thanks for reporting this.  I will work on reproducing/fixing tomorrow.

**Comment by jthoms1** [comment]
This issue is fixed with commit 576de8a8f47. We will be releasing an update tomorrow.

**Comment by mburger81** [comment]
This does only resolve one bug described in my issue.  Or not?

**Comment by pe1o2pl** [comment]
The same error after installing:
npm install -g ionic@beta
ionic start ionic3-blank blank

{ Error: ENOENT: no such file or directory, open '/Users/artur/.ionic/config.json'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/artur/.ionic/config.json' }

ionic info

  Your system information:

    Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: macOS Sierra
    Node Version: v6.10.0
    Xcode version: Not installed
{ Error: ENOENT: no such file or directory, open '/Users/artur/.ionic/config.json'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/artur/.ionic/config.json' }
