### ISSUE TITLE
When i update Ionic to 2.2.1 . run ionic serve is error!

### ISSUE THREAD

**Issue by YyItRoad** [driftyco/ionic-cli#1975]
$ ionic serve
Caught exception:
 SyntaxError: Unexpected token <
    at Object.parse (native)
    at /usr/local/lib/node_modules/ionic/lib/utils/npmScripts.js:125:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by YyItRoad** [comment]
Today, I reload ionic to 2.2.1 ，Find it can run。thx
