### ISSUE TITLE
[ERROR] Unknown plugin: @ionic/cli-plugin-.

### ISSUE THREAD

**Issue by jhrfeng** [driftyco/ionic-cli#1977]
npm install -g ionic@beta

For Ionic2 Project
npm install --save-dev @ionic/cli-build-ionic-angular@beta @ionic/cli-plugin-cordova@beta

run ionic serve

That`s OK

but i run cmd:  ionic g component xxx

CMD console ERR:

[ERROR] Unknown plugin: @ionic/cli-plugin-.

**Comment by jthoms1** [comment]
g is currently not an alias for `generate`.  This is likely something we will add in the future.  Please me sure to take a look at the help and documentation.  The commands in v3 are not 1-to-1 parity for v2.  More documentation on the generate command can be found here: https://github.com/driftyco/ionic-cli/blob/v3/docs/generate.md
