### ISSUE TITLE
Using Crosswalk - Splash Screen is always white on Android.

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic-cli#198]

**Comment by jbavari** [comment]
@do-web - I've been pulling in some commits from the new version of cordova-android that we are using underneath to drive Crosswalk. 

I'll be pushing some changes out Monday for 1.3.3, and I'm hoping this may address your issue.

Thank you for reporting.

**Comment by jbavari** [comment]
@do-web are you also using [the splashscreen plugin](https://github.com/apache/cordova-plugin-splashscreen)?

**Comment by jbavari** [comment]
@do-web - any update here? What I hear is you have to add the plugin via its git url:
`cordova plugin add https://github.com/apache/cordova-plugin-splashscreen.git`

**Comment by jesper** [comment]
Installing the plugin fixed it for me!
