### ISSUE TITLE
Feature request allow building for production

### ISSUE THREAD

**Issue by eikooc** [driftyco/ionic-cli#1982]
When running `ionic serve` it is currently running angular in development mode which is as intended. 

I would like to be able to build the project in production mode without building it for android or iOS. Making it possible to serve the minified and optimised build on the desktop

**Comment by jthoms1** [comment]
You can do this currently if I am not mistaken CC: @danbucholtz.

**Comment by danbucholtz** [comment]
Hi @eikooc,

You cannot currently do this and it isn't going to be on our road map for the next several months. We have a long backlog of things related to speed up Ionic 😄 . This is something we could consider in late 2017 or 2018 perhaps. This may not be what you want to hear, but I think it's important to be honest.

Thanks,
Dan
