### ISSUE TITLE
Ionic Package not working

### ISSUE THREAD

**Issue by sansan88** [driftyco/ionic-cli#1988]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:

C:\Users\Sandro\CloudStation\Development\_PROJEKTE\unihockey.club.app\unihockeyclub>ionic package build ios --profile prod --release
[ERROR] Unknown plugin: @ionic/cli-plugin-.

#### What behavior are you expecting?
Uploading the app to the cloud and package them

**Steps to reproduce:**
1. install latest cli (beta3)
2. run command :
3. ionic package build ios --profile prod --release

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

 Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.1
    Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
Package is currently not available in v3.  This is a current gap that we will be fixing in the coming weeks.

**Comment by dwieeb** [comment]
@sansan88 Please try 3.0.0-rc.2 with package support added back in. 

Thank you!
