### ISSUE TITLE
(v2) ionic serve --watch-poll for webpack is needed

### ISSUE THREAD

**Issue by pdobrigkeit** [driftyco/ionic-cli#1993]
#### What version of the CLI are you using? Output of `ionic --version`
2.2.1

#### Short description of the problem:
Using ionic on a NFS Vagrant virtual machine
#759 
driftyco/ionic-app-lib#73

#### What behavior are you expecting?
That I can change how polling works, when using `ionic serve`

**Steps to reproduce:**
1. Create a Vagrant machine
2. Enable sharing through SMB
3. Create an ionic environment
4. Start the project and change a file on the host system

**Post the output of `ionic info` below please**
# ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.9.4
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I tried to apply the patch from driftyco/ionic-app-lib#73 but the structure of the ionic-app-lib has completly changed and I am unable to find the proper places to change.

I am also running several plain Angular 2 projects and there polling and recompiling on the fly works in this setup.

@tomsun Did you get it working in any current versions? Would be super helpful to solve this problem

**Comment by pdobrigkeit** [comment]
As mentioned in Slack, app-scripts will be more appropriate, so opened the issue there again

driftyco/ionic-app-scripts#817

**Comment by jthoms1** [comment]
Thanks!
