### ISSUE TITLE
Ionic cli 3 - iOS app immediately restarts when using app switcher.

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic-cli#2005]
#### What version of the CLI are you using? Output of `ionic --version`
```
Davids-MacBook-Air:AddVideo2 daveshirman$ ionic --version
3.0.0-beta.4
```

#### Short description of the problem:
I load my app, do nothing but switch to photos app for example, then immediately in the app switcher view, I can see my Ionic 2 app is restarted.  This is confirmed when selecting the app from the preview.

#### What behavior are you expecting?
App not to restart immediately after app switching in iOS

Behaviour does not happen in Android.

**Steps to reproduce:**
1. Build app for iOS
2. Run it, switch to another app.
3. Observe app immediately restarting

**Post the output of `ionic info` below please**
```
Davids-MacBook-Air:AddVideo2 daveshirman$ ionic info

  Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.8 
    OS: OS X El Capitan
    Node Version: v6.10.0
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by mhartington** [comment]
Can you provide any more information regarding this? 
Can you make this happen with a default starter project? 
What are the exact steps to take to reproduce?

**Comment by daveshirman** [comment]
Ok, I've tried with the starter project and it doesn't happen.  Is there a config setting that could cause this or something?

The exact steps to reproduce are:

1. open my app
2. double click home button to get app switcher OR just single click to return home
3. go back into my app, either through app switcher or app icon on home screen.
4. note the app has restarted immediately.
