### ISSUE TITLE
Split personality Split Pane

### ISSUE THREAD

**Issue by snortblt** [driftyco/ionic-cli#2014]
**Feature Request**

I love the new split pane component, guys! And I'm super glad to hear you're pursuing more desktop-related features. It's not always fun trying to make Ionic play nicely there as it stands.

I'm guessing you guys may have thought of something like this, but what I've really wanted for a hybrid desktop/mobile app span the desktop and mobile worlds is a master/detail a la split pane, but on a phone it would behave like two different pages in a nav hierarchy. In virtually any case where I have some kind of simultaneous master detail thing going on for a larger display, I'm not simply going to want to hide the master column on a smaller display--I'm going to want to show it as its own page where selecting an item now navigates to the detail page (and of course the drill-down chevrons would automatically show up and hide as appropriate for the platform). 

I'm actually going to try to hack this together myself, but since it seems kind of an obvious common pattern, it would certainly make a great framework component if you can work out the navigation kinks in a generic way.

Keep these things coming! Great stuff!

**Comment by mburger81** [comment]
@snortblt I think you should close this thread and open it on https://github.com/driftyco/ionic
the cli doesn't matter with your feature request.

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic#10968
