### ISSUE TITLE
Ionic-Plugin-Cordova Not Post Installing

### ISSUE THREAD

**Issue by saniyusuf** [driftyco/ionic-cli#2015]
I tried an NPM install after upgrading to latest CLI & Ionic. I get 

129914 error @ionic/cli-plugin-cordova@0.0.9 postinstall: `node ./bin/postinstall`
129914 error Exit status 1
129915 error Failed at the @ionic/cli-plugin-cordova@0.0.9 postinstall script 'node ./bin/postinstall'.
129915 error Make sure you have the latest version of node.js and npm installed.
129915 error If you do, this is most likely a problem with the @ionic/cli-plugin-cordova package,
129915 error not with npm itself.

Any Ideas guys? Im on a MAC by the way

**Comment by jthoms1** [comment]
So this is an issue with the postinstall script trying to display a message about what global depedencies are required.  I am probably going to remove the postinstall, but this failure should have no impact on functionality.

**Comment by jthoms1** [comment]
Fix is in should be out with next release.
