### ISSUE TITLE
Ionic generate issue with tabs

### ISSUE THREAD

**Issue by Langstra** [driftyco/ionic-cli#2016]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:
When generating tabs, using `ionic generate`, then choosing a name, using 2 tabs the "Generating tabs *name here*" is displayed over the questions on how you want to name the tabs. "Enter the first tab name:"

#### What behavior are you expecting?
That the question is displayed.

**Steps to reproduce:**
When generating tabs, using `ionic generate`, then choosing a name, using 2 tabs the "Generating tabs *name here*" is displayed over the questions on how you want to name the tabs. "Enter the first tab name:"

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.4
    Node Version: v7.3.0
    Xcode version: Not installed

**Comment by dwieeb** [comment]
@Langstra I just looked at this and I think it's no longer an issue with 3.0.0-rc.2. Can you verify?

**Comment by Langstra** [comment]
Appears to be working (Y)
