### ISSUE TITLE
Ionic generate tabs generates wrong boilerplate

### ISSUE THREAD

**Issue by Langstra** [driftyco/ionic-cli#2017]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:
After generating tabs I found that the name of the TabPages was wrong in the Tab root page. The tabs are named NameTabPage, where in the Tab root page they are being imported as NameTab.

#### What behavior are you expecting?
Either the tabs should be called NameTab or NameTabPage and so accordingly in the boilerplate code.

**Steps to reproduce:**
When generating tabs, using `ionic generate`, then choosing a name, using 2 tabs the "Generating tabs *name here*" is displayed over the questions on how you want to name the tabs. "Enter the first tab name:"

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.4
    Node Version: v7.3.0
    Xcode version: Not installed

**Comment by jthoms1** [comment]
There have been significant changes to how generate works.  This is now only available for Ionic-angular 3+ projects. I am going to close this ticket because of these changes.
