### ISSUE TITLE
cordova.js not loading properly with last version of crosswalk

### ISSUE THREAD

**Issue by kno** [driftyco/ionic-cli#202]
When loading cordova.js in crosswalk 10.39.235.15 it launches this error:
```
    Uncaught Error: Error calling method on NPObject
    Lines 924: var messages = nativeApiProvider.get().exec(service, action, callbackId, argsJson);
```
And it doesn't load
It works fine with version 9.38.208.10

**Comment by jbavari** [comment]
@kno - I'll be updating some of the cordova-android libraries and pushing them out for a 1.3.3 release on Monday.

Hang tight, that may help with that error.

**Comment by jbavari** [comment]
1.3.3 is out - please confirm @kno

**Comment by kno** [comment]
I've updated, remove crosswalk browser, add again without specifing version, and it works. 
Thanks
