### ISSUE TITLE
'ionic start myproject tabs --v2' faild，Error with start undefined...

### ISSUE THREAD

**Issue by YepFury** [driftyco/ionic-cli#2020]
**when i 'ionic start myPro tabs --v2', it always show:**

> Installing npm packages (may take a minute or two)...
> Error with start undefined
> Error Initializing app: There was an error with the spawned command: npminstall
> There was an error with the spawned command: npminstall

**I found some online methods, for example 'npm install npm -g' , but does not work,**

**my version:**

> node  6.10.0
> npm 3.10.10
> ionic 2.2.1
> cordova 6.5.0

**who can help me to resolve this problem?????**

**Comment by Gengjun-VVU** [comment]
@YepFury 
I am getting the same error since a few hours ago. Don't know if it is Ionic CLI problem or npm problem.

**Comment by jthoms1** [comment]
Could you provide me with the output from `ionic info` from within your project directory? Thanks, this should help in troubleshooting.

**Comment by Gengjun-VVU** [comment]
@YepFury @jthoms1 It seems that my problem is due to out of space, as I am using c9.io online ide, the issue resolves when I free up some space. Thanks.

**Comment by YepFury** [comment]
@jthoms1 
I think it might be because of the company's network,  the same project directory,when I at home can be successful but in the company can't. Thanks so much.
