### ISSUE TITLE
Auth login basic (Ionic Cloud) not working after ionic build android --prod

### ISSUE THREAD

**Issue by adsonrocha** [driftyco/ionic-cli#2022]
I am using the following code to signin inside a provider:

```
 signIn(details): Promise<any[]>{
    return new Promise((resolve, reject) => {
      this.auth.login('basic', details).then(() => {
        resolve(someData);
      }, (err: any) => {
        reject(err);
      });
    });
  }
```
I have properly imported Auth at my provider constructor.
It works when I preview on browser and Ionic View, but triggers this error after install an apk generated by "ionic build android --prod":

`Error: Request has been terminated. Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is been unloaded, etc.
`

My internet connection is on. 
Can anybody help me?

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-cloud#192
