### ISSUE TITLE
V3-beta.4 Using alias g for generate causes error

### ISSUE THREAD

**Issue by HairyCream** [driftyco/ionic-cli#2023]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta.4

#### Short description of the problem:
Using alias "g" for "generate" causes [ERROR]

#### What behavior are you expecting?
command _ionic g page whatever_ to give same result as _ionic generate page whatever_

**Steps to reproduce:**

```
D:\dev\bpApp>ionic g page Friends
[ERROR] Unknown plugin: @ionic/cli-plugin-.

D:\dev\bpApp>ionic generate page Friends
✔ Generating page named Friends - done!

```

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.10.0
    Xcode version: Not installed

**Comment by jthoms1** [comment]
I agree that this should be implented. It appears that command aliases are not working.

**Comment by jthoms1** [comment]
commit b79e8c72ca6c429514d42456cf4f9d05c20a4747 fixed this issue. It will be in the next release.
