### ISSUE TITLE
Show output of Cordova Tasks ran by the CLI

### ISSUE THREAD

**Issue by coreyroth** [driftyco/ionic-cli#2029]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta.4

#### Short description of the problem:

Output of cordova tasks such as build or run is not displayed.

#### What behavior are you expecting?

To see the output of the cordova tasks.  This is important because there have been times when I ran into an error when building to Android or iOS and there is not enough information to see what the cause of the issue is.  

**Steps to reproduce:**
For example on commands such as ionic cordova:build android --prod --release

I'm not sure that I'm a fan of the new "cordova:" prefix on all of the cordova commands from the Ionic CLI but I am sure you all have a good reason for it.

**Comment by jthoms1** [comment]
I think we will continue to keep this output hidden, but we should implement a flag like `--verbose` to allow devs to see the output if they would like.

**Comment by coreyroth** [comment]
I think that is a good solution with a flag.

**Comment by dwieeb** [comment]
@coreyroth Cordova output should be much improved in the latest release: 3.0.0-rc.2

Please give it a try!
