### ISSUE TITLE
Ionic Upload return an error.

### ISSUE THREAD

**Issue by b0jan** [driftyco/ionic-cli#203]
I'm testing Ionic View but it seems there is a problem with Ionic CLI.
Take a look at the screenshot:

![screen shot 2015-01-23 at 13 34 31](https://cloud.githubusercontent.com/assets/2690106/5874657/a6b79e84-a304-11e4-9cc5-c510df79e36c.png)

**Comment by jbavari** [comment]
Could you please run `ionic info` and paste that information here?

**Comment by b0jan** [comment]
Sure!
![screen shot 2015-01-23 at 22 24 57](https://cloud.githubusercontent.com/assets/2690106/5883006/ba62fcc2-a34e-11e4-8bf7-fd2a4b6ebcc9.png)

**Comment by jbavari** [comment]
Aha. Please update your CLI. That will solve the upload issues. `npm install -g ionic`.

Ensure you're on Ionic CLI Version 1.3.2. That should fix your errors.

**Comment by b0jan** [comment]
Yep! Outdated version :)
Solved, thanks!
