### ISSUE TITLE
[V3] "serve" fails if there are no external network interfaces

### ISSUE THREAD

**Issue by jsayol** [driftyco/ionic-cli#2030]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:
If no external network interfaces are present, running `ionic serve` fails with the following error: `It appears that you do not have any external network interfaces. In order to use livereload with emulate you will need one.`

#### What behavior are you expecting?
`serve`, unlike `emulate`, should run even if only localhost is available.

**Steps to reproduce:**
1. Disable any external network interfaces
2. `ionic serve`

**Post the output of `ionic info` below please**
```
  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.7.1
    Xcode version: Not installed
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

https://github.com/driftyco/ionic-cli/blob/3a4441347d17abdcb46a4024034858cfa5fc663f/packages/cli-build-ionic-angular/src/serve.ts#L16-L20

**Comment by astec** [comment]
Disabling livereload also does not help:

```
$ ionic serve browser -d
Error: It appears that you do not have any external network interfaces. In order to use livereload with emulate you will need one.
```
Makes impossible to develop while offline.

**Comment by jthoms1** [comment]
commit a83cc8b1bccc4384b749438141e304284d85b256 fixes this issue.

**Comment by Kanyango** [comment]
$ ionic serve  --address 127.0.0.1 -p 8800
specify a port of your choice i.e -p 8100
This worked for me
