### ISSUE TITLE
Cannot use ionic-app-scripts custom config files in command line

### ISSUE THREAD

**Issue by alfabetagama** [driftyco/ionic-cli#2032]
#### What version of the CLI are you using? 
2.2.1

#### Short description of the problem:
Cannot use ionic-app-scripts custom config files path in command line.

If you run 

ionic build android --release --prod -s ./config/sass.config.js -r ./config/rollup.config.js

Build fails with error

Error: Unknown platforms: ./config/sass.config.js, ./config/rollup.config.js

#### What behavior are you expecting?
Ionic command line should accept ionic app scripts parameters

**Steps to reproduce:**
1. copy  config files from \node_modules\@ionic\app-scripts\config to config directory
2. run

```
ionic build android --release --prod -s ./config/sass.config.js -r ./config/rollup.config.js
```

**Post the output of `ionic info` below please**

 ordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.4.0
Xcode version: Not installed

**Workaround:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

You can change  \node_modules\@ionic\app-scripts\config directly

**Comment by jthoms1** [comment]
This issue was moved to driftyco/ionic-app-scripts#862
