### ISSUE TITLE
CLI 3.0.0-beta.4 ionic upload Authentication failed, type unauthorized error

### ISSUE THREAD

**Issue by CoderBrad** [driftyco/ionic-cli#2038]
I used the information in this blog post http://blog.ionic.io/ionic-cli-v3-beta/ to update to ionic CLI v3.0.0-beta.4 3 days ago and since updating I haven't been able to perform an ionic upload. It fails with the following API Error 401:

$ ionic upload
✖ Requesting snapshot - failed!
API Error 401: POST https://api.ionic.io/deploy/snapshots
{ message: 'Authentication failed',
  link: null,
  type: 'Unauthorized' }

I've made sure to perform an ionic login and re-entered my email and credentials to ensure I've been logged into my account.

So basically so far I'm not able to get my app into Ionic View. The good part is that the new CLI is much more responsive and builds faster as well. It also allows me to perform **ionic cordova:run android** without issue so I am still able to test on devices, but is obviously a slower process than using Ionic View.

I also have an open thread on the ionic forum about this issue here:
https://forum.ionicframework.com/t/updated-cli-3-beta-4-ionic-upload-doesnt-show-up-in-ionic-view/84173?source_topic_id=84299

For completeness, I'm using Linux MiNT (Latest Stable v18.1), which I doubt makes a difference in this case.

**Comment by javico2609** [comment]
same error on CLI 3.0.0-beta.5

```
λ ionic upload
✖ Requesting snapshot - failed!
API Error 401: POST https://api.ionic.io/deploy/snapshots
{ link: null,
  message: 'Authentication failed',
  type: 'Unauthorized' }
```
Ionic Info
```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 8.1
    Node Version: v7.7.3
    Xcode version: Not installed
```

**Comment by CoderBrad** [comment]
I'm no longer having this issue. CLI 3.0.0-beta.9 seems to have resolved all of my issues with ionic upload.

Reference: https://github.com/driftyco/ionic-cli/issues/2100

**Comment by dwieeb** [comment]
@CoderBrad Thanks for the update. I honestly can't say what the original issue was, but I'm glad it has been fixed along the way.

Please let me know if you have any other issues.

**Comment by campsjos** [comment]
I'm having the same issue on version 3.1.2, I tried installing ionic@beta and ionic@canary with the same results...
This happens in my workplace (Ubuntu 16.04), but in home works fine (Windows 10).

```
$ ionic upload

Running app-scripts build: 

[10:39:46]  build dev started ... 
[10:39:46]  clean started ... 
[10:39:46]  clean finished in 3 ms 
[10:39:46]  copy started ... 
[10:39:46]  transpile started ... 
[10:39:49]  transpile finished in 2.32 s 
[10:39:49]  preprocess started ... 
[10:39:49]  deeplinks started ... 
[10:39:49]  deeplinks finished in 18 ms 
[10:39:49]  preprocess finished in 19 ms 
[10:39:49]  webpack started ... 
[10:39:49]  copy finished in 2.63 s 
[10:39:57]  webpack finished in 8.21 s 
[10:39:57]  sass started ... 
[10:39:58]  sass finished in 851 ms 
[10:39:58]  postprocess started ... 
[10:39:58]  postprocess finished in 5 ms 
[10:39:58]  lint started ... 
[10:39:58]  build dev finished in 11.48 s 
✖ Requesting snapshot upload - failed!
Request: POST https://api.ionic.io/deploy/snapshots
Response: 401
Body: 
{ link: null,
  message: 'Authentication failed',
  type: 'Unauthorized' }

```
```
$ ionic info

global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Linux 4.8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by campsjos** [comment]
I nedded to downgrade to ionic@2.2.3 in order to upload the app :(

**Comment by theo4u** [comment]
The solution was just to simply re-link the application with `ionic link`
