### ISSUE TITLE
EPIPE error when running ionic upload

### ISSUE THREAD

**Issue by olivierlesnicki** [driftyco/ionic-cli#204]
I've managed to run `ionic upload` once successfully. 
Attempting to update the app results in the following error:

`````
$ ionic upload

Uploading app...
Error uploading: Error: write EPIPE (CLI v1.3.2)
```

**Comment by olivierlesnicki** [comment]
This seems to be linked to my internet connection as I'm an unable to replicate the issue when I switch networks. Is it worth displaying a user-friendly message instead?

**Comment by jbavari** [comment]
Ahhh. Good find. I'll add this to the list to provide better error messages.
