### ISSUE TITLE
ionic serve stay freeze after update to 2.2.1

### ISSUE THREAD

**Issue by wgbn** [driftyco/ionic-cli#2044]
#### What version of the CLI are you using? Output of `ionic --version`
2.2.1

#### Short description of the problem:
After upgrading from Ionic-cli to 2.2.1 and Ionic Framework 2.3.0, when creating a project from scratch by CLI, and running Ionic serves, the command line gets frozen and nothing runs.
I kept running for 1 hour to see if something was happening in time, but even after 1 hour, the cli was still the same.

The cli is only with:
```
$ ionic serve

> ionic-hello-world@ ionic:serve /home/walter/Workspace/0-javascript/2-ionic/lfdev-checkin-ionic
> ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
```

#### What behavior are you expecting?
I expected the server to be raised so I could eat the application.

**Steps to reproduce:**
1. `$ npm install -g ionic cordova gulp typescript`
2. '$ ionic start my-app blank --v2`
3. `$ ionic serve`

**Post the output of `ionic info` below please**
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.1
Xcode version: Not installed
```

**Comment by Gengjun-VVU** [comment]
Seems like lots of people start getting this error, me too, the app-scripts changed from version 1.1.4 to 1.2.2, then everything stops working.

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.2.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.9
Node Version: v6.10.0
Xcode version: Not installed
```

**Comment by Gengjun-VVU** [comment]
Hi @wgbn 

It seems that if you update your Ionic CLI to v3 beta version, this issue disappears. Just run the following command:
```
sudo npm install -g ionic@beta
```
Hope this helps.

**Comment by wgbn** [comment]
Yes, thank you @Gengjun-VVU!
Really this problem disappears with the beta v3 of ionic-cli!
