### ISSUE TITLE
Wording issue when remove Cordova plugin

### ISSUE THREAD

**Issue by DeanmvSG** [driftyco/ionic-cli#2047]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.5

#### Short description of the problem:
When running `ionic Cordova:plugin` I get a list of if I would like to add, remove or list plugins.  Selected `remove` then asks me the question "What plugin would you like to ADD"
![screen shot 2017-03-29 at 13 02 19](https://cloud.githubusercontent.com/assets/15265711/24453502/124d5a78-1480-11e7-81c3-af697bce2da6.png)

#### What behavior are you expecting?
The CLI to ask me what plugin I would like to remove, not add

**Steps to reproduce:**
1. run `ionic Cordova:plugin`
2. Select `remove` from the list

**Post the output of `ionic info` below please**
```
    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.0-beta.3
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: 1.9.1 
    ios-sim version: Not installed
    OS: macOS Sierra
    Node Version: v6.10.1
    Xcode version: Xcode 8.3 Build version 8E161
```

**Comment by jthoms1** [comment]
commit 77a2270ae4d271e4d05d4cb99436f337545ab31a fixes this issue.
