### ISSUE TITLE
v3.beta.4 ionic serve --address not working

### ISSUE THREAD

**Issue by HairyCream** [driftyco/ionic-cli#2048]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.4

#### Short description of the problem:
The Windows 10 system has three network interfaces defined.
_ionic serve_ with no flags shows the three interface addresses and prompts for one to be selected.
```
D:\dev\bpApp>ionic serve
? Multiple addresses available. Please select which address to use: (Use arrow keys)
> 169.254.77.12
  192.168.2.40
  169.254.17.140
```
_ionic serve --address 192.168.2.40_ also prompts for an interface address to be selected
```
D:\dev\bpApp>ionic serve --address 192.168.2.40
? Multiple addresses available. Please select which address to use: (Use arrow keys)
> 169.254.77.12
  192.168.2.40
  169.254.17.140
```
#### What behaviour are you expecting?
Maybe I'm interpreting the documentation incorrectly, but I was expecting that when the --address flag is specified the prompt to select an interface address would be skipped. 

**Steps to reproduce:**
1. ionic serve --address xxx.xxx.xxx.xxx on a system with multiple network interfaces

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta.4
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.10.1
    Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by rubyjedi** [comment]
+1.  It would be fantastic if we could specify a default listen address in a configuration file, versus menu-selection or command-line parameter. Thanks!

**Comment by jthoms1** [comment]
This is exactly what should be happening.  It appears that there is a bug around this.

**Comment by jthoms1** [comment]
commit 92dbcd868af7878289d848b325195a1fdf2faecb fixes this issue and will be released next week.
