### ISSUE TITLE
ionic build android --release ALWAYS produces one file instead of two builds 

### ISSUE THREAD

**Issue by crissi** [driftyco/ionic-cli#205]
I have BUILD_MULTIPLE_APKS set.

ionic build android produces two apks.

while 
ionic build android --release only produces one.

I am running:
Ionic CLI Version: 1.3.2
Cordova CLI: 4.2.0

**Comment by jbavari** [comment]
@crissi - this has been updated from some of the changes in cordova-android. Please install 1.3.3 and see if you can get two builds now.

**Comment by jbavari** [comment]
@crissi - this should be updated now in 1.3.4. Please get latest `npm install -g ionic` and run `ionic browser add crosswalk`
