### ISSUE TITLE
native plugin installation after updating ionic cli beta 3

### ISSUE THREAD

**Issue by San10694** [driftyco/ionic-cli#2050]
i am facing problem after updating the Ionic CLI v3 Beta verson of ionic cli globally and within existing project  , i am unable to install ionic native plugines , why am i facing this trouble while installing the native plugin it shows -"[ERROR] Unknown plugin: @ionic/cli-plugin-." , help me

**Comment by jthoms1** [comment]
Can you provide me with the command that you are trying to execute as well as the output from running `ionic info` within your project directory.

**Comment by JuergsPona** [comment]
Hi @San10694 

Try running the command as "ionic cordova:plugin add"

e.g. ionic cordova:plugin add cordova-plugin-geolocation

**Comment by San10694** [comment]
@JuergsPona  thanks it works fine :)
