### ISSUE TITLE
Ionic builds not executing with Cordova commands (3.0.0-beta.5)

### ISSUE THREAD

**Issue by FdezRomero** [driftyco/ionic-cli#2051]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.5

#### Short description of the problem:
Cordova commands like `ionic cordova:build [platform]` and `ionic cordova:run [platform]` no longer execute the Ionic build.

#### What behavior are you expecting?
To build the Ionic v2 project and then execute the Cordova command.

**Steps to reproduce:**
1. Run `ionic cordova:run [platform] --prod --device`.
2. The message `Starting build - done!` appears instantly without actually triggering a build.

```
$ ionic cordova:run android --prod --device
✔ Starting build - done!
⠹ Executing cordova command: cordova run android --device
```

**Post the output of `ionic info` below please**
```
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.10.1
    Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I have the following `devDependencies`. I was using `@ionic/cli-build-ionic-angular@0.0.3` and noticed that the package name changed in the readme from `build` to `plugin`.

```json
  "devDependencies": {
    "@ionic/app-scripts": "1.2.3",
    "@ionic/cli-plugin-cordova": "0.0.10",
    "@ionic/cli-plugin-ionic-angular": "0.0.4",
    "typescript": "2.0.9"
  }
```

**Comment by FdezRomero** [comment]
Adding that `ionic serve` doesn't work either. I have to run `npm run serve` for it to work, which is set to `ionic-app-scripts serve`.

**Comment by jthoms1** [comment]
Appologizes on this. The plugins will be changing names in beta6 release, but I prematurely updated the README.md.  I just fixed this. Please ensure that your devDependencies look like the following.

```
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9",
    "@ionic/cli-plugin-cordova": "0.0.10",
    "@ionic/cli-build-ionic-angular": "0.0.4"
  }
```

**Comment by FdezRomero** [comment]
@jthoms1 Thanks a lot for pointing out my mistake :+1:
