### ISSUE TITLE
cannot installed using npm 'sudo npm install -g ionic'

### ISSUE THREAD

**Issue by jxzly229190** [driftyco/ionic-cli#2057]
Npm version:4.4.4
Node version:v6.9.1

I tried it at windows10 and Mac both failed. 

The error is below:
npm WARN In ionic@2.2.2 replacing bundled version of mime-types with mime-types@2.0.14
npm WARN In ionic@2.2.2 replacing bundled version of cross-spawn with cross-spawn@4.0.2
npm WARN In ionic@2.2.2 replacing bundled version of semver with semver@4.2.0
npm WARN In ionic@2.2.2 replacing bundled version of form-data with form-data@0.2.0
npm WARN In ionic@2.2.2 replacing bundled version of request with request@2.51.0
npm WARN In ionic@2.2.2 replacing bundled version of ionic-app-lib with ionic-app-lib@2.2.1
npm ERR! path /usr/local/lib/node_modules/.staging/ansi-392b32ed
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/ansi-392b32ed' -> '/usr/local/lib/node_modules/ionic/node_modules/cordova-lib/node_modules/ansi'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhanglianyin/.npm/_logs/2017-04-02T02_11_17_898Z-debug.log

**Comment by rapropos** [comment]
I strongly suggest never running npm as root and instead using [nvm](https://github.com/creationix/nvm), but that aside, if you had searched older issues and/or [the support forums](https://forum.ionicframework.com/) for "enoent rename", you probably would have found many suggestions to uninstall ionic and cordova completely before reinstalling them.

**Comment by jxzly229190** [comment]
@rapropos .  Thank you for your suggestion. I am go to close this issue.
