### ISSUE TITLE
documentRoot on ionic.project doesn't work for me

### ISSUE THREAD

**Issue by eve-amandine** [driftyco/ionic-cli#206]
I've changed my app folder with the code/resources from **www** to **app**. I would like to use *ionic serve* with the **app** folder. I have added in my ionic.project: 
`"documentRoot": "app"`
But I have the error:
**"www" directory cannot be found. Please make sure the working directory is an Ionic project. (CLI v1.3.2)**
Isn't this property working?

**Comment by jbavari** [comment]
This hasn't been released yet. It should be done today.

**Comment by jbavari** [comment]
1.3.3 is out - please try it out @eve-amandine and let me know if it worked.

**Comment by massue** [comment]
It seems still doesn't work with 1.3.3 :(

`"www" directory cannot be found. Make sure the working directory is at the top level of an Ionic project. (CLI v1.3.3)`

**Comment by jbavari** [comment]
Can you post your ionic.project file?

**Comment by jbavari** [comment]
I've got it working.

My steps:

```bash
ionic start j1 sidemenu
cd j1
```

I then made my `ionic.project` file as follows:

```json
{
  "name": "j1",
  "app_id": "",
  "documentRoot": "app",
  "watchPatterns": ["app/**/*", "!app/lib/**/*"]
}
```

Following up with `ionic serve`:

```bash
03:22:51 ~/Development/testing/j1$ ionic serve
Running dev server: http://localhost:8100
Running live reload server: http://localhost:35729
Watching : [ 'app/**/*', '!app/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

**Comment by eve-amandine** [comment]
Now it works perfectly thx :D

**Comment by jbavari** [comment]
No problem. Cheers!
