### ISSUE TITLE
Ionic3 Beta cli errors

### ISSUE THREAD

**Issue by jlcarvalho** [driftyco/ionic-cli#2063]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta.5

#### Short description of the problem:
Since I updated to Ionic3 beta, I am getting this error:

```
$ ionic generate provider myProvider
$ Error: The generate command is only available for projects that use ionic-angular >= 3.0.0
```

#### What behavior are you expecting?
Generate the desired provider.

**Steps to reproduce:**
1. Update to the new CLI
2. Run `ionic generate provider myProvider`

**Post the output of `ionic info` below please**
```
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.0-beta.3
Ionic CLI Version: 3.0.0-beta.5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.7.4
Xcode version: Xcode 8.3 Build version 8E162
```

**Comment by dwieeb** [comment]
@jlcarvalho This has been fixed with the latest beta release. Thank you!
