### ISSUE TITLE
using ionic-cli to generate splash screens

### ISSUE THREAD

**Issue by alexkb** [driftyco/ionic-cli#207]
Maybe this is a documentation issue or maybe its a bug in ionic-cli, but currently subsequent runs of `ionic resources` and `ionic run` doesn't seem to update the resource files that get used in an ionic app.

`ionic resources` definitely updates splash images stored in `resources\android\splash` every then if you run `ionic run`, it only uses what's found in `resources\android\drawable-<orientation>-<display-type>/` which stores the old file.

To get things working (for now), I'm just deleting all the `resources/android/drawable*` folders, and that does the trick of triggering `ionic run` to recreate these all based on the contents of `resources/android/splash` and `resources/android/icon`. Is this typical workflow?

Besides that, great job on [creating the resources tool](http://ionicframework.com/blog/automating-icons-and-splash-screens/) - it saves a lot of time in photoshop!

**Comment by jbavari** [comment]
@alexkb - I'll take a look into this real soon! Hang tight!
