### ISSUE TITLE
[cli beta3] --buildConfig arg not taken into account anymore

### ISSUE THREAD

**Issue by theomathieubhvr** [driftyco/ionic-cli#2072]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta.5

#### Short description of the problem:

Since I updated my ionic cli version to 3, my buildConfig arg is not taken into account anymore.

**Steps to reproduce:**
1. ionic cordova:build ios --prod --device --release --buildConfig config/build.json
2. Failed to run on android (cannot sign APK)

It shows
```
Executing cordova command: cordova run ios --release --device
```

**Post the output of `ionic info` below please**
 (ionic info fails Error: spawn ENOTDIR)

Thanks !

**Comment by dwieeb** [comment]
Fixed! This will be in the next beta version. Thank you!

**Comment by theomathieubhvr** [comment]
I'm so glad you fixed it !

Thanks !
