### ISSUE TITLE
Cli plugin error

### ISSUE THREAD

**Issue by calcelli** [driftyco/ionic-cli#2079]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta.5

#### Short description of the problem:

I am trying to add cordova plugin to project and get error:  Unknown plugin: @ionic/cli-plugin-

#### What behavior are you expecting?
Adding plugin to project

**Steps to reproduce:**
1. npm install @ionic-native/core --save   
2. npm install @ionic-native/camera --save
3. ionic plugin add cordova-plugin-camera

**Post the output of `ionic info` below please**
 Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.0
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.8
    Node Version: v6.10.2
    Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
@calcelli This has been fixed in the latest beta release. Thank you!
