### ISSUE TITLE
Cannot change device in iOS Simulator

### ISSUE THREAD

**Issue by davisford** [driftyco/ionic-cli#208]
When I run `ionic emulate ios -l -c -s` it works great for me, but always defaults to `iPhone 6 / iOS 8.1 (12B411)`.  I'd like to emulate it on a different device to ensure layout issues, etc., but when I go to `Hardware -> Device -> iPhone 5s` for example, it reloads the sim with that device's profile but the app is not installed.

I've tried restarting the ionic command, but it always goes back to the 6.  It seems to be hard-coded?  Doesn't look like the CLI options take a particular device profile.

Is there a way to accomplish this?

**Comment by davisford** [comment]
[I found a related forum thread](http://forum.ionicframework.com/t/how-to-emulate-iphone-6/10287/8).  Unfortunately the recommended fix, e.g. `ionic emulate ios --target="iPhone (Retina 4-inch)"` no longer appears to work.  Not sure if this is an issue -- whether it is supposed to work (i.e. pass through the target name to `ios-sim`, so I'll leave the issue open and let you all decide if it is worth investigating.

I can confirm the workaround -- just using `ios-sim` directly -- does the trick for me; unfortunately you lose the nice ability of livereload and logs.

Get list of installed device types:
```sh
$ ios-sim showdevicetypes
```

Pick one and run the app on it, e.g.
```sh
ios-sim launch platforms/ios/build/emulator/appName.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.0"
```

**Comment by jbavari** [comment]
@davisford - This was recently identified as an issue with the `ionic run` command as you've mentioned. What was happening were args were being eaten.

This is fixed in 1.3.3 - I'm trying to get it out the door. Hopefully this solves your issue.

**Comment by jbavari** [comment]
@davisford - 1.3.3 is out - please install latest and see if this fixes it for you.

**Comment by davisford** [comment]
awesome...will do

**Comment by jbavari** [comment]
I usually look at [this post](http://stackoverflow.com/questions/22310526/cordova-start-specific-ios-emulator-image)

Try running `ionic emulate ios --target="iPhone-4s"`

**Comment by davisford** [comment]
Works for me @jbavari -- thanks for the push to get the fix out.

**Comment by isathish** [comment]
What about iPad ......?

**Comment by irvingellan** [comment]
@davisford  Thanks!
