### ISSUE TITLE
ionic push --ios-prod-cert not work

### ISSUE THREAD

**Issue by santo76** [driftyco/ionic-cli#2081]
Hi, i use ionic cli to create my apps.
I execute 'ionic security profiles add push_production' to create new profile, it works ok.
Then, i execute 'ionic push --ios-prod-cert' and in the promt i put a cer file and a message show 'Successfully uploaded certificate' but, if i go to 'https://apps.ionic.io/app/fa3243f5/config/credentials' and enter in the profile, the certificate don't exsist.

I think upload certifcates not work and, the same for 'ionic push --google-api-key serverkey', it not saved in profile.

thanks

**Comment by dwieeb** [comment]
This is a very old command. It has been removed in CLI v3 (beta) Please review the new push documentation: http://docs.ionic.io/services/push/
