### ISSUE TITLE
Invalid argument has an unclear response

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#2086]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta.5

#### Short description of the problem:

Given I supply an unsupported argument, like `ionic foo`, the result is a bit weird:

[ERROR] Unknown plugin: @ionic/cli-plugin-.

#### What behavior are you expecting?

Something like, "foo is not a valid command."

**Steps to reproduce:**
1. Pass an unknown argument to the CLI.
2. Hit enter.
3. Profit.

**Post the output of `ionic info` below please**
  Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta.5
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v6.9.2
    Xcode version: Not installed

**Comment by dwieeb** [comment]
@cfjedimaster This has been fixed in the latest beta release. Thank you!
