### ISSUE TITLE
Adding (temporary) aliases (or interception) for old commands?

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2088]
Users testing the v3 beta CLI seem to often forget the new syntax and use old commands:

https://forum.ionicframework.com/t/native-3-x-installing-geolocation-plugin-error/86334
https://stackoverflow.com/questions/43232826/ionic-platforms-update-returns-an-error
https://forum.ionicframework.com/t/error-unknown-plugin-ionic-cli-plugin/85483

ALL documentation out there now will use the old commands, probably forever. Using the old syntax shouldn't lead the users into a non-explained error the CLI certainly could anticipate.

Wouldn't it be useful to map the old commands to a helper that outputs an information about the new syntax but also aliases to the new one (or intercepts the request so at least there is no error)?

**Comment by piotrowski** [comment]
Ok seems syntax in CLI v3 beta changed again, so this may not be necessary or useful. Let's see what it settles on.

**Comment by dwieeb** [comment]
We are mapping legacy commands to their respective equivalents. build, compile, emulate, platform, plugin, prepare, resources, and run all give helpful error messages.

Let me know if something could be better here. The goal is to prepare ourselves for future platform support, and a command like `ionic build` is very ambiguous.
