### ISSUE TITLE
Allow the CLI to post recent updates

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#209]
This should be something to inform users of new features or changes to help them answer any questions before they come up.

**Comment by mlynch** [comment]
Just to put my slack though in here, I think keeping it static and simple for now is the right approach, considering we can always just change the text for the next version, and it's really the new devs we want to have see this stuff.

Maybe a colored table of stuff?

![screenshot 2015-01-27 12 54 03](https://cloud.githubusercontent.com/assets/11214/5927132/53f46ee0-a636-11e4-941a-b2b4987f22bb.png)

**Comment by jbavari** [comment]
This is now out in 1.3.4.
