### ISSUE TITLE
serve, run , generate page command not working in ionic cli 3 beta 7

### ISSUE THREAD

**Issue by vksgautam1** [driftyco/ionic-cli#2091]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### What version of the CLI are you using? Output of `ionic --version`
 Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.7.1
    Xcode version: Not installed

#### Short description of the problem:
for every command i am getting this error.
TypeError: cli_utils_1.load is not a function
    at Object.<anonymous> (E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:35:40)
    at Generator.next (<anonymous>)
    at E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:7:71
    at __awaiter (E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:3:12)
    at Object.serve (E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:16:12)
    at Object.<anonymous> (E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\index.js:19:24)
    at Generator.next (<anonymous>)
    at E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\index.js:7:71
    at __awaiter (E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\index.js:3:12)
    at emitter.on (E:\Pider_Web\node_modules\@ionic\cli-plugin-ionic-angular\dist\index.js:18:35)

#### What behavior are you expecting?
working .

  
**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
  Cordova CLI: 6.5.0
    Ionic Framework Version: 2.2.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.7.1
    Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by davidqqq** [comment]
Hi I just encountered this problem myself after upgrading to Ionic CLI@beta today. No error will occur if you ionic serve a newly generated page by v3 CLI but it will fail if you try on v2 project. So upon inspecting and comparing various new and old files, I found `"@ionic/cli-plugin-cordova": "0.0.12", "@ionic/cli-plugin-ionic-angular": "0.0.6"` are missing in old v2 package.json. Put them in, run npm install and you are ready to go! :)

**Comment by SVANNER** [comment]
Hi, how did you get the **cli-plugin-ionic-angular** at 0.0.6. I can install 0.0.4, but said  

`ERR! notarget No compatible version found: @ionic/cli-build-ionic-angular@0.0.6`

when **npm install** after changing my package.json.

Thanks  a lot !

**Comment by jthoms1** [comment]
https://github.com/driftyco/ionic-cli/tree/v3#existing-ionic2-project

Please execute the commands listed. This should solve the issue it appears that you do not have the new plugins installed. The plugins have changed.  Seems like we should have done a better job of communicating this. Thanks!

**Comment by vksgautam1** [comment]
i think this app script depedancy issue.
npm uninstall @ionic/cli-plugin-core @ionic/cli-build-ionic-angular
npm WARN @ionic/cli-plugin-ionic-angular@0.0.4 requires a peer of @ionic/app-scripts@^1.2.2 but none was installed.

if update to 1.2.2 then it shows message of  UNMET PEER DEPENDENCY typescript@2.0.9

**Comment by vksgautam1** [comment]
updated my app script and typescript too.
"devDependencies": {
    "@ionic/app-scripts": "^1.2.2",
    "@ionic/cli-build-ionic-angular": "0.0.4",
    "@ionic/cli-plugin-cordova": "0.0.12",
    "@ionic/cli-plugin-ionic-angular": "0.0.4",
    "typescript": "2.2.1"
  },


. now lost the path
 --npm WARN @ionic/app-scripts@1.2.2 requires a peer of typescript@~2.2.1 but none was installed.


i

**Comment by mujib2953** [comment]
After updating to Ionic3, When I run the command to generate  the page i.e
>> npm g page Test
creating an extra ngModule file inside the page folder.
i.e the newly created test folder under the pages folder consist of on .ts file, one .scss file, one .html file and one extra file is being generated named test.module.ts in the same folder.
please help me to sort it out.

**Comment by ujjwal2516** [comment]
After cli update 3.0.0-beta7 errors are shown in serve.js while ionic serve command

**Comment by vksgautam1** [comment]
@mujib2953  that module ts file is for lazy loading, if you are not implementing that feature you can remove that file.
https://www.youtube.com/watch?v=7j-P-ElAqe8

**Comment by dwieeb** [comment]
If you still have a project with old CLI plugins installed, uninstall them and install the new ones with these steps: https://github.com/driftyco/ionic-cli/tree/v3#upgrading-from-a-previous-beta-release-to-beta7

I'm closing this--please create new issues if the above doesn't solve it.

**Comment by ujjwal2516** [comment]
@vksgautam1 Thanx
