### ISSUE TITLE
v3-beta7: `ionic cordova platform` outputs error / `cordova` commands broken

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2094]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta7

#### Short description of the problem:

Calling `ionic cordova platform` outputs an error:

```
> ionic cordova platform
[ERROR] Command not found: cordova
```

#### What behavior are you expecting?

Calling a command without the required parameters should either give you an interactive prompt or the help output to discover the parameters.

**Steps to reproduce:**
1. Install the v3-beta7 CLI
2. Start project, go into directory
3. Execute `ionic cordova platform`

**Post the output of `ionic info` below please**

```
  Your system information:
    Cordova CLI: Not installed
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Windows 10
    Node Version: v7.9.0
    Xcode version: Not installed
```

**Comment by piotrowski** [comment]
Same output for `ionic cordova platform list` although it is mentioned in `ionic cordova platform --help` as a valid action.

**Comment by piotrowski** [comment]
Same for `ionic cordova platform add android`:

```
> ionic cordova platform add android
\ Executing cordova command: cordova platform add android --save [ERROR] Command not found: cordova
```

I suspect all `cordova` commands are broken :/

**Comment by jthoms1** [comment]
https://github.com/driftyco/ionic-cli/tree/v3#existing-ionic2-project

Please execute the commands listed. This should solve the issue it appears that you do not have the new plugins installed.

**Comment by piotrowski** [comment]
I actually created a new project using the v3-beta7 CLI `ionic start`, so this shouldn't be necessary, right?

Part of the `package.json` of the project:

```
  "devDependencies": {
    "@ionic/app-scripts": "1.3.0",
    "typescript": "~2.2.1",
    "@ionic/cli-plugin-cordova": "0.0.12",
    "@ionic/cli-plugin-ionic-angular": "0.0.6"
  },
```

**Comment by piotrowski** [comment]
I executed the command from the link anyway (`npm install --save-dev @ionic/cli-plugin-ionic-angular@beta @ionic/cli-plugin-cordova@beta`), just to be sure:

1. No change to package.json (but reordering)
2. Some interesting output, maybe:

```
PS C:\Users\Jan\Documents\cliBeta7> npm install --save-dev @ionic/cli-plugin-ionic-angular@beta @ionic/cli-plugin-cordov
a@beta

> @ionic/cli-plugin-cordova@0.0.12 postinstall C:\Users\Jan\Documents\cliBeta7\node_modules\@ionic\cli-plugin-cordova
> node ./bin/postinstall

You will need to install the following global dependencies in order to use this plugin.
npm install -g cordova ios-deploy ios-sim

cliBeta7@0.0.1 C:\Users\Jan\Documents\cliBeta7
+-- UNMET PEER DEPENDENCY @ionic/app-scripts@1.3.0
+-- @ionic/cli-plugin-cordova@0.0.12
`-- @ionic/cli-plugin-ionic-angular@0.0.6

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN @ionic/cli-plugin-ionic-angular@0.0.6 requires a peer of @ionic/app-scripts@^1.3.1 but none was installed.
PS C:\Users\Jan\Documents\cliBeta7>
```

**Comment by dwieeb** [comment]
@piotrowski Do you have Cordova installed globally? The CLI seems to think you don't. You seem to be on Windows, perhaps it's an issue with that.

**Comment by piotrowski** [comment]
Oh, you're right! Sorry...

For testing the CLI I switched to a new node version with nvm - and of course nuked my Cordova along the way. Now I installed it, and of course all the cordova commands are working.

I created #2103 as a request to improve this error message.

**Comment by dwieeb** [comment]
@piotrowski No worries! 😄
