### ISSUE TITLE
v3-Beta7: Ionic serve error

### ISSUE THREAD

**Issue by SVANNER** [driftyco/ionic-cli#2095]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`
**2.2.2**

#### What version of the CLI are you using? Output of `ionic --version`
**3.0.0-beta7**

#### Short description of the problem:

When running **ionic serve**, i get:

[ERROR] No listeners for serve event. Did you install the appropriate plugin?

#### What behavior are you expecting?
See my project running in Google Chrome 

**Steps to reproduce:**
1. ionic start test blank --v2
2. ionic serve

```
insert any relevant code between the above and below backticks
```
No specific code - rjust ran the blank template

**Post the output of `ionic info` below please**

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: Linux 4.4
    Node Version: v7.9.0
    Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by jthoms1** [comment]
https://github.com/driftyco/ionic-cli/tree/v3#existing-ionic2-project

Please execute the commands listed. This should solve the issue it appears that you do not have the new plugins installed.

**Comment by vkniazeu** [comment]
See #2089 too.

**Comment by SVANNER** [comment]
Thanks a lot,
 I had to re-install, but it works now !
