### ISSUE TITLE
v3-beta7: /docs doesn't match released CLI

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2096]
The content of /docs at https://github.com/driftyco/ionic-cli/tree/v3/docs doesn't match the current state of the CLI very well: 

https://github.com/driftyco/ionic-cli/blob/v3/docs/cordova-build.md says to use e.g. `ionic build android`:

```
> ionic build android
The build command is no longer available. To find out more about the equivalent please run:

  ionic cordova build --help
```

https://github.com/driftyco/ionic-cli/blob/v3/docs/download.md, example `ionic download` doesn't exist:

```
> ionic download --help
[ERROR] Unable to find command: download.
```

**Comment by jthoms1** [comment]
You are correct it appears that docs did not get updated correctly.  The command should say `ionic cordova build android`.

**Comment by dwieeb** [comment]
Thank you, this has been fixed. The documentation should better. I'll be taking a look at improving the markdown docs in this repo, but the documentation in the CLI itself should be the preferred documentation. Especially during beta/RC.
