### ISSUE TITLE
v3-beta7: No support for Ionic Package?

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2098]
I couldn't find any command that are equivalent to the v2 Package commans:

* `ionic package list`
* `ionic package build PLATFORM_TAG --profile PROFILE_TAG`
* `ionic package download BUILD_ID`

https://github.com/driftyco/ionic-cli/blob/v3/docs/ionic.md mentions `build`, `download`, `list` and `info` but these don't exist or do different stuff.

**Comment by dwieeb** [comment]
@piotrowski We just needed to regenerate the documentation. I've fixed that issue. As for package, we're going to wait to implement it in the CLI. The package service itself also has work that needs to be done. 

Thanks for reporting the issue!

**Comment by piotrowski** [comment]
Adding a few sentences about what is and what isn't supported in the v3 beta CLIs to the README would be great for us playing with it - especially if the docs are not always up to date.

**Comment by dwieeb** [comment]
@piotrowski Great idea. I will be updating the readme!
