### ISSUE TITLE
CLI 3.0.0-beta7 throws error when running help commands

### ISSUE THREAD

**Issue by afgallo** [driftyco/ionic-cli#2099]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta7

#### Short description of the problem:
Running most `--help` commands results in the error below:
```
ionic cordova platform --help

Add or remove a platform target for building an Ionic app

    Usage
      $ ionic cordova platform [action] [platform]

    Inputs
      action ................... add, remove, or update a platform; list all project platforms
      platform ................. The platform that you would like to add (e.g. ios, android)

    Options
      --noresources, -r ........ Do not add default Ionic icons and splash screen resources (corresponds to add)
      --nosave, -e ............. Do not update the config.xml (corresponds to add, remove, update)

    Examples
      $ ionic cordova platform add android

TypeError: Cannot read property 'private' of undefined
    at inputs.filter (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:91:31)
    at Array.filter (native)
    at HelpCommand.getCleanInputsForTelemetry (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:90:18)
    at HelpCommand.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:63:48)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/ionic/node_modules/@ionic/cli-utils/dist/lib/command/command.js:4:58)
```

#### What behavior are you expecting?
No errors when `--help` commands are run.

**Steps to reproduce:**
1. Install the latest CLI beta version as per http://blog.ionic.io/ionic-cli-v3-beta/
2. Run any command and append `--help` flag

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0
    Ionic Framework Version: 2.3.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v7.7.4
    Xcode version: Xcode 8.2 Build version 8C38

Guys, thanks for your work on this. Even though I am getting this minor issue everything is apparently working as expected. I will continue to test the beta version and report any other errors I might come across.

**Comment by dwieeb** [comment]
Let's track this issue here: https://github.com/driftyco/ionic-cli/issues/2092#event-1042033927
