### ISSUE TITLE
iPhone 6+ plus support in ionic resources

### ISSUE THREAD

**Issue by softBarbarian** [driftyco/ionic-cli#210]
Hello,
Maybe i am missing something, but when i run `ionic resources` all icons and splashscreens are being generated except the ones for iPhone 6+. However I noticed that `icon-60@3x.png` for iPhone 6+ is generated.
![screen shot 2015-01-27 at 8 05 40 pm](https://cloud.githubusercontent.com/assets/1832398/5930630/ef2ce3d2-a65f-11e4-8970-2f809831618f.png)

Missing icons and splashscreens:
```
Icon:
icon-small@3x.png

Splash:
Default-Portrait-736h@3x.png
Default-Landscape-736h@3x.png

```

**Comment by softBarbarian** [comment]
Anyone else can confirm same behavior?

**Comment by mhartington** [comment]
What version of the cordova cli do you have? 

```bash
$ cordova -v
```
you should have version 4.2.0

**Comment by softBarbarian** [comment]
i have 
`3.5.0-0.2.7`
will update and report

**Comment by softBarbarian** [comment]
updated to cordova 4.2.0
removed ios platform
readded ios platform
ran ionic resources 

And i am still missing `@3x` images. However i noticed that this time i ran the `ionic resources` command all images where from cache.
@mhartington is there a way to clear the cache?

Thanks

**Comment by mhartington** [comment]
So `Default-Portrait-736h@3x.png` is being generated as 
```
Default-736h.png
```
Its generating a portrait image, but not a landscape. 
As for the spotlight images, it seems that it isn't in the list of images to make. 
Will add this to the list of images to be made.

**Comment by mhartington** [comment]
Just to verify, @jbavari we need to add the follow to [settings.js](https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/resources/settings.js#L54)

```
{ name: 'icon-small@3x.png',    width: 87,    height: 87 }
```

**Comment by softBarbarian** [comment]
Understood. Thanks

**Comment by NicholasMerrill** [comment]
Updating Cordova from 4.0 to 4.2.0, removing ios platform, adding ios platform worked for me.

**Comment by hanhuizhu** [comment]
when i use cordova-ios@4.x  the splash is notwork in iphone6 plus. and i make cordova-ios@3.9.2 ,the splash is working
