### ISSUE TITLE
v3-beta7: Ionic upload succesfull, build not showing up on Ionic View

### ISSUE THREAD

**Issue by Luukschoen** [driftyco/ionic-cli#2100]
**v3 beta7 testing**

#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta7

#### Short description of the problem:
Whenever uploading a build with ionic upload command (with or without --note), the build doesn't show up in Ionic View. It does show up under deploys on Ionic.io, it doesn't come through on Ionic View. 

#### What behavior are you expecting?
If I upload a build with ionic upload, I expect it to be available within Ionic View. Right now, the build shows up under deploys on Ionic.io, but it doesn't come through in Ionic view.

**Steps to reproduce:**
1. link a project to an Ionic.io project
2. run ionic upload command 
3. notice no errors on the CLI, the build showing up as a snapshot underneath deploys
4. the build doesn't become available on Ionic View

**Post the output of `ionic info` below please**

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1 
    ios-sim version: 5.0.11 
    OS: macOS Sierra
    Node Version: v7.7.2
    Xcode version: Xcode 8.2.1 Build version 8C1002

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

[https://forum.ionicframework.com/t/does-anyone-have-ionic-upload-working-in-cli-3-beta/86342/13](https://forum.ionicframework.com/t/does-anyone-have-ionic-upload-working-in-cli-3-beta/86342/13)

**Comment by CoderBrad** [comment]
Just as an FYI addon, Luuk and I have both been experiencing this issue. I first noticed this in Ionic CLI 3.0.0-beta.4.

Luuk has since downgraded to CLI v2.2.2 and ionic upload does work as expected in that version so there something has definitely changed in the new v3 beta CLI.

**Comment by dwieeb** [comment]
@Luukschoen @CoderBrad Thanks for reporting the issue. Ionic View will need an update. I'll keep track of this issue with the beta8 milestone. 👍

**Comment by CoderBrad** [comment]
Thanks, Dan. Great stuff! Keep up the good work.

**Comment by patwaswapnil** [comment]
Mine is not even getting uploaded. :(
```
ionic upload
✔ Requesting snapshot upload - done!
- Uploading snapshot
C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\progress\lib\node-progress.js:131
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\progress\lib\node-progress.js:131:14)
    at ProgressBar.tick (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\progress\lib\node-progress.js:86:8)
    at Task.progress (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\utils\task.js:52:34)

    at deploy.uploadSnapshot (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\dist\lib\upload.js:32:24)
    at Request.http_1.createRequest.field.field.on (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils
\dist\lib\utils\aws.js:19:21)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Transform.progress._transform (C:\Users\Swapnil\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:9
48:16)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
```

**Comment by dwieeb** [comment]
@patwaswapnil That's a different issue and can be tracked in your original issue: https://github.com/driftyco/ionic-cli/issues/1984

**Comment by ThomasKientz** [comment]
Same for me, I had to downgrade to the CLI v2 to upload.

**Comment by dwieeb** [comment]
Because Ionic View needs the update, the fix can happen independently of any CLI releases, so I am going to push this back to get beta8 out the door.

**Comment by CoderBrad** [comment]
Yep, that's understandable. Who's working on Ionic View? If you/they need any help with coding the fix or testing let me know - I'll volunteer some of my time to working on it.

**Comment by dwieeb** [comment]
@tlancina will be working on Ionic View. We're hoping for next week, but no promises! 😄 

@CoderBrad if you wouldn't mind, can you hit me up on Ionic Worldwide (https://ionicworldwide.herokuapp.com/) to chat? I'm `@dan`.

**Comment by dwieeb** [comment]
@CoderBrad @Luukschoen Please update your CLIs to beta9 and verify if this fixes the issue. We didn't need to update View after all.

**Comment by CoderBrad** [comment]
@dwieeb I don't know what it took to get this working but great job! My app showed up instantly in ionic view after this beta.9 update and runs perfectly. I can't thank you enough.

**Comment by Luukschoen** [comment]
@dwieeb I can confirm it's working and I would very much would like to thank you! Good job, keep up the good work. If you ever need a hand, let me know.

**Comment by Luukschoen** [comment]
@dwieeb Or I didn't test thoroughly, or it got broken again. Updated to rc.0 didn't fix it either. Snapshot get's uploaded, shows up on Ionic Cloud but doesn't on Ionic View. Same issue as before as far as I can tell..

**Comment by CoderBrad** [comment]
@Luukschoen @dwieeb I can also confirm that it's broken again with rc.0. I was able to get it working with beta.10 though. I think this issue needs to be re-opened. Others are messaging me on the ionic forum with this same issue.

**Comment by dwieeb** [comment]
@Luukschoen @CoderBrad This is likely one of two things: 1) A build wasn't performed before uploading. 2) You didn't click "Clear app data" inside Ionic View. 

To address #1, I'll be having `upload` perform a build by default, with a flag to disable the behavior.
To address #2, we'll be updating View soon.

**Comment by Luukschoen** [comment]
Just FYI, I'm now on rc1 of the CLI. I can see a build is performed, still not showing up on view. Keep up the good work, I've got faith in you guys 😄

**Comment by dwieeb** [comment]
@Luukschoen Can you test again?

**Comment by Luukschoen** [comment]
I can confirm it's working again! Wonderful @dwieeb . Again if you need a helping hand, let me know. Or if you just need me to test that's also fine with me 😃

**Comment by dwieeb** [comment]
@Luukschoen If you want to test "nightlies" instead of beta versions, please `npm i -g ionic@canary`. That would be helpful 😄

**Comment by CoderBrad** [comment]
@dwieeb @Luukschoen Sorry I haven't been able to test in a while - it's been a crazy week. I've been testing the rc2 ionic upload and it does indeed work! Thanks again, Dan for the good work.
