### ISSUE TITLE
ionic generate component create a wrong module

### ISSUE THREAD

**Issue by shprink** [driftyco/ionic-cli#2101]
#### What version of the CLI are you using? Output of `ionic --version`

2.2.2

#### Short description of the problem:

`ionic g component test` generate a wrong module:

```
import { NgModule } from '@angular/core';
import { IonicModule } from 'ionic-angular';
import { Test } from './test';

@NgModule({
  declarations: [
    Test,
  ],
  imports: [
    IonicModule.forChild(Test),
  ],
  exports: [
    Test
  ]
})
export class TestModule {}
```

`forChild` does not exist on `IonicModule`

**Steps to reproduce:**
1. run `ionic g component test`
2. open `test.module.ts`
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 3.0.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Not installed
````

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by piotrowski** [comment]
Change `IonicModule` to `IonicPageModule` both times to fix.
There already was an issue for this, but I can't find it. Hope Ionic ppl will.

**Comment by dwieeb** [comment]
I saw this just recently. Unfortunately, with how generators work at the moment, it will require a new release of framework (as templates are tied to the framework version). For now, @piotrowski's fix is the right way to work around this issue.

Here is the fix: https://github.com/driftyco/ionic/commit/4fa17a2f5930a22190404024a1f98fc3ea54c64d

Thank you!
