### ISSUE TITLE
Ionic 2 on Android showing me the blank-black screen after adding the cordova crosswalk plugin.

### ISSUE THREAD

**Issue by sachinrkeche** [driftyco/ionic-cli#2102]
Hello Ionic players,
I am trying to run simple Ionic app on android platform here i am getting the issue ,
First time i was issue when i run app on Android device i got the error  "web page not available", then i add  plugin after adding the crosswalk plugin by   "add cordova-plugin-crosswalk-webview", it show me the black screen, i have device android 4.3 on which i run the app, I am not gettting the what is the exact issue here.

My ionic info 
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 3.10
Node Version: v6.10.0
Xcode version: Not installed

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by piotrowski** [comment]
This sounds more like a problem for the forum: https://forum.ionicframework.com/

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo's issues are reserved for bug reports and feature requests of the Ionic CLI. For general Ionic support questions, please see our [Support Page](https://ionicframework.com/support).
