### ISSUE TITLE
v3-beta7: Better error messages when Cordova is not installed

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2103]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta7

#### Short description of the problem:

Calling `ionic cordova platform` outputs a non-descript error when Cordova is not installed:

```
> ionic cordova platform
[ERROR] Command not found: cordova
```

#### What behavior are you expecting?

Calling a cordova sub-command on a project when Cordova is not installed should output this error message but also point the user in the right direction to install Cordova on his machine.

**Comment by dwieeb** [comment]
Hi! In the next beta release you should see this:

![image](https://cloud.githubusercontent.com/assets/236501/25212801/468883c0-2552-11e7-9286-94fa8b0cf2f8.png)

Along with a super helpful, huge error message during preinstall of the plugin:

![image](https://cloud.githubusercontent.com/assets/236501/25212841/8d6d75d4-2552-11e7-881a-bf567be24ff6.png)

Thank you! 🎉
