### ISSUE TITLE
v3beta7 - Unable to find command: cordova build ios.

### ISSUE THREAD

**Issue by zoinkydoink** [driftyco/ionic-cli#2105]
**v3 beta7 testing**

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

This command returns 2.2.2  but my `ionic info` returns 3.0.0beta7, what is the diff between the two?

#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta7

#### Short description of the problem:
I copied a folder from my windows machine to Mac (the windows one was using beta5) and after installing latest version of everything on my Mac by doing `sudo nom install -g ionic@latest
When I run command `ionic cordova build ios` I get the unable to find command: cordova build ios

#### What behavior are you expecting?
For the build to success

**Steps to reproduce:**
1.run the command `ionic cordova build ios`
2. error message
3.

**Post the output of `ionic info` below please**
  Your system information:

    Cordova CLI: 6.5.0 
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: Not installed
    ios-sim version: 5.0.13 
    OS: macOS Sierra
    Node Version: v7.9.0
    Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by qiluo** [comment]
same error, already updated to beta7 and re-installed related plugins

**Comment by dwieeb** [comment]
@zoinkydoink @qiluo  Our blog post (which you likely used to install the CLI beta) is outdated. I'll have it updated tomorrow.

The correct plugins are listed in the [README](https://github.com/driftyco/ionic-cli/blob/v3/README.md). This section may solve your issue: https://github.com/driftyco/ionic-cli/blob/v3/README.md#upgrading-from-a-previous-beta-release-to-beta7

**Comment by zoinkydoink** [comment]
`npm install --save-dev @ionic/cli-plugin-ionic-angular@beta @ionic/cli-plugin-cordova@beta` this fixed it for me
