### ISSUE TITLE
v3 cordova emulate fails on old cordova version

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-cli#2116]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta7-alpha.d32d569c

#### Short description of the problem:

running `ionic cordova emulate` fails when cordova is out of date, with this error:

<img width="819" alt="screenshot 2017-04-18 10 26 38" src="https://cloud.githubusercontent.com/assets/11214/25139301/7ad770cc-2422-11e7-893d-09ca9c05dff2.png">

#### What behavior are you expecting?

**Steps to reproduce:**
1.
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

I updated cordova after this and before running `ionic info` so this doesn't reflect old cordova version:

```
max@ionitron:~/apps/awsMobile$ ionic info

npm (global):

    @ionic/cli-utils : 0.0.11-alpha.d32d569c
    cordova          : 6.5.0
    ionic            : 3.0.0-beta7-alpha.d32d569c

npm (local):

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 0.0.12-alpha.d32d569c
    @ionic/cli-plugin-ionic-angular : 0.0.6-alpha.d32d569c
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002
    ios-deploy : not installed
    ios-sim    : 5.0.8

max@ionitron:~/apps/awsMobile$
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
I think this is due to us swallowing some errors from Cordova, which I've just fixed. beta8 out soon!
