### ISSUE TITLE
ionic resources iPad Pro?

### ISSUE THREAD

**Issue by pcrombach** [driftyco/ionic-cli#2118]
#### What version of the CLI are you using? Output of `ionic --version`
Installed ionic 2.2.2

#### Short description of the problem:
resources for iPad Pro are not generated.

splash ios Default-Landscape@~ipadpro.png (2732x2048) skipped, source image splash.png (2295x3000) too small

splash ios Default-Landscape@~ipadpro.png (2732x2048) skipped, source image splash.png (2295x3000) too small

#### What behavior are you expecting?
IMHO Generate proper sizes for iPad Pro

**Steps to reproduce:**
1. run ionic resources

**Post the output of `ionic info` below please**
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.1 Build version 8E1000a

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
Thank you, this is a known issue. We have to update our base starter with a large enough image and pre-generated sizes. I've marked this for the next beta release (v3), but mostly as just a reminder. When I fix it for v3, it will be fixed for v2.

**Comment by dwieeb** [comment]
This has been fixed and beta8 will be out soon! Thank you!
