### ISSUE TITLE
target-device handset still has iPad enabled using ionic package

### ISSUE THREAD

**Issue by R2D221** [driftyco/ionic-cli#2120]
#### What version of the CLI are you using? Output of `ionic --version`

2.2.2

#### Short description of the problem:

Setting `<preference name="target-device" value="handset"/>` on config.xml and running `ionic package build ios` generates a binary with iPad enabled

#### What behavior are you expecting?

Setting target-device handset to only enable iPhone and iPod Touch, while iPad remains disabled

**Steps to reproduce:**
1. Add `<preference name="target-device" value="handset"/>` to config.xml
2. Build using `ionic package build ios` and the appropriate profile
3. Load generated .ipa to iTunes Connect
4. Try to publish the app to the App Store without iPad screenshots. The publish will fail.

**Post the output of `ionic info` below please**

Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by dwieeb** [comment]
Thanks for posting your issue. Unfortunately, this repo is reserved for bug reports and feature requests of the Ionic CLI. For Ionic Services support, please [file a ticket here](https://ionic.zendesk.com/hc/en-us/requests/new).
