### ISSUE TITLE
ionic3: '@ionic/cli-plugin-proxy' is not in the npm registry.

### ISSUE THREAD

**Issue by Schwobaland** [driftyco/ionic-cli#2126]
**v3 beta7 testing**

#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta7

#### Short description of the problem:
When i run any ionic command (e.g. `ionic serve`) following output is given

```
? https_proxy environment variable detected, but the plugin @ionic/cli-plugin-proxy is required to proxy requests. Would you like to install it and continue? (Y/n)
```

When i type `Y`following output is generated:

```
✖ Executing npm command: npm install --save-dev @ionic/cli-plugin-proxy - failed!
[ERROR] An error occurred while running the above command (exit code 1):

        npm ERR! Darwin 16.5.0
        npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "@ionic/cli-plugin-proxy"
        npm ERR! node v7.9.0
        npm ERR! npm  v4.2.0
        npm ERR! code E404

        npm ERR! 404 Not found : @ionic/cli-plugin-proxy
        npm ERR! 404
        npm ERR! 404  '@ionic/cli-plugin-proxy' is not in the npm registry.
        npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
        npm ERR! 404
        npm ERR! 404 Note that you can also install from a
        npm ERR! 404 tarball, folder, http url, or git url.
```

**Post the output of `ionic info` below please**
    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.1
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v7.9.0
    Xcode version: Xcode 8.3.2 Build version 8E2002

**Comment by dwieeb** [comment]
@Schwobaland Sorry about that, please try again.

**Comment by Schwobaland** [comment]
thanks - its working now!

**Comment by ajdnass** [comment]
hi
I faced same problem, what is the solution that work with you??

**Comment by Schwobaland** [comment]
@ajdnass what version of ionic-cli have you installed. Please show your `ionic info` output.
