### ISSUE TITLE
page generated by cli v3 beta3 contains error code

### ISSUE THREAD

**Issue by qiluo** [driftyco/ionic-cli#2136]
#### What version of the CLI are you using? Output of `ionic --version`
v3 beta 8

#### Short description of the problem:
I generated a page, and I found beta8 generated a module as well, here's module code
```
import { NgModule } from '@angular/core';
import { IonicModule } from 'ionic-angular';
import { TabContainerPage } from './tab-container';

@NgModule({
  declarations: [
    TabContainerPage,
  ],
  imports: [
    IonicModule.forChild(TabContainerPage),
  ],
  exports: [
    TabContainerPage
  ]
})
export class TabContainerPageModule {}
```
but TS compiler told me `Property 'forChild' does not exist on type 'typeof IonicModule'.`

#### What behavior are you expecting?
I don't know why there's a module by default and there should not be error

**Post the output of `ionic info` below please**
```
npm (global):

    @ionic/cli-utils : 0.0.12
    cordova          : 6.5.0
    ionic            : 3.0.0-beta8

npm (local):

    @ionic/app-scripts              : 1.3.3
    @ionic/cli-plugin-cordova       : 0.0.13
    @ionic/cli-plugin-ionic-angular : 0.0.7
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by vksgautam1** [comment]
shld be IonicPageModule

**Comment by dwieeb** [comment]
Thanks. This is a known issue. See https://github.com/driftyco/ionic-cli/issues/2070

**Comment by judsonmusic** [comment]
Did this ever get resolved? If so what do I need to update to see the change?
