### ISSUE TITLE
Running `ionic package release android` fails after upload

### ISSUE THREAD

**Issue by rvanbaalen** [driftyco/ionic-cli#214]
I get this error message:

```
Error upload callback: TypeError: Cannot read property '0' of undefined (CLI v1.3.3)
```

After running `ionic package release android`:

```
X:projectname Robin$ ionic package release android
Loading projectname...
Android Keystore File (.keystore): /full/path/to/projectname.keystore
Keystore Alias: projectname
Keystore Password: 
Key Password (optional): 

Uploading app...
Successfully uploaded (e6b4980d)

Error upload callback: TypeError: Cannot read property '0' of undefined (CLI v1.3.3)
```

**Comment by jbavari** [comment]
@rvanbaalen I've seen this when some have an invalid config.xml document or ionic.project file.

I'm trying to lock down which it is. Could you look at those files and see if they are ok? Id love to help you figure this out.

**Comment by rvanbaalen** [comment]
Thanks @jbavari 

How am I supposed to verify if I have an invalid config.xml or ionic.project?

When I build locally, with cordova, there is no problem.

**Comment by jbavari** [comment]
Thats a good question, ha! A user before had same error as you with some invalid characters in their config.xml, which is why I asked.

Ah, ok, that helps. Let me dig around a bit more.

**Comment by rvanbaalen** [comment]
Ok keep me posted. And let me know if you need anything.

**Comment by dallasclark** [comment]
I'm having this same issue as well, checked the config.xml or ionic.project files and they don't appear to have an issue (visibly).

**Comment by jbavari** [comment]
@dallasclark @rvanbaalen - I've found the error with the help of @jeff-french.

I'll be trying to patch it up today or tomorrow and get another release out.

**Comment by rvanbaalen** [comment]
That would be great. By now Ive written my own bash scripts for building signing and deploying with Cordova but Im always keeping an eye on the Ionic tools. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by softBarbarian** [comment]
@rvanbaalen or @jbavari can someone share a build sh scipt?
I've been trying to create my own to get an ad-hoc ipa crated but had no luck.
Here is my apptempt: https://gist.github.com/781bccbd8a581a21b888.git

**Comment by rvanbaalen** [comment]
@softBarbarian As far as building for iOS goes, I stop when Cordova created the xcode project. The tools out there that create an IPA from the command line are somewhat buggy in my experience (ios-deploy). They crash for unknown reasons. Therefore, my build script stops when Cordova created the xcode project file and opens that file. From there on the only thing I have to to is click 'Product -> Archive' to build the IPA. That's not so hard ;-)

On the Android side if things, I've fully automated the process from building the release-ready APK to signing it. I only have to upload the output APK to Google Play Store when the script is done.

I'll see if I can share anything soon.

**Comment by softBarbarian** [comment]
@rvanbaalen cool, thanks a lot.
the gist that i posted actually uses OS X's tools to archive and sign the IPAs (if i get it to work)

**Comment by jbavari** [comment]
Unfortunately, we will be suspending this feature and removing it currently from the CLI until some time in the future.

Sorry for the inconvenience.

**Comment by rvanbaalen** [comment]
Not production ready yet?
