### ISSUE TITLE
v3-beta8: Running `ionic serve` in non-project directory doesn't output any error message

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2140]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

Running `ionic serve` in non-project directory doesn't output any error message, has no output at all.

#### What behavior are you expecting?

Same output you get when running any of the other project commands outside a project directory:

```
[ERROR] Could not determine project type.

        For Ionic Angular projects, make sure 'ionic-angular' exists in the dependencies attribute of package.json.
        For Ionic 1 projects, make sure 'ionic' exists in the devDependencies attribute of bower.json.

        Alternatively, set type attribute in ionic.config.json to one of: 'ionic-angular', 'ionic1'
```

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Run `ionic serve` in a directory that contains no Ionic project

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
Thanks @piotrowski! This fix will go out soon.

**Comment by Allan-Nava** [comment]
I had this problem
`ionic info
? Looks like a fresh checkout! No ./node_modules directory found. Would you like to install project dependencies? Yes
[INFO] Installing dependencies may take several minutes!
> npm install
✔ Running command - done!
[ERROR] Could not determine project type (project config: ./ionic.config.json).
        
        For Ionic Angular projects, make sure 'ionic-angular' exists in the dependencies attribute of package.json.
        For Ionic 1 projects, make sure 'ionic' exists in the devDependencies attribute of bower.json.
        
        Alternatively, set type attribute in ionic.config.json to one of: 'ionic-angular', 'ionic1'`
