### ISSUE TITLE
v3-beta8: `ionic start` shows no visual feedback for running `npm install`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2142]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

`ionic start` shows no visual feedback for running `npm install` but a simple "cursor" (blinking _). It did show this nice spinny thing for all the previous steps.

```
PS C:\Users\Jan\Documents> ionic start
? What would you like to name your project: beta8test
? What starter would you like to use: conference
? The directory beta8test contains file(s) that could conflict. Would you like to overwrite the directory with this new project? Yes
✔ Creating directory C:\Users\Jan\Documents\beta8test - done!
✔ Downloading 'conference' starter template - done!
✔ Updating project dependencies to add required plugins - done!
✔ Creating configuration file for the new project - done!

Installing dependencies may take several minutes!

> npm install

_
```

#### What behavior are you expecting?

Spinny thing.

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Run `ionic start`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
Tougher than it sounds. The library we're using to render the spinny thing requires that the _bottom_ line of output is the one being re-rendered, and I also want to show the commands that are actually being run. I'll look into it, but I think there are other priorities.

**Comment by dwieeb** [comment]
I did it
