### ISSUE TITLE
v3-beta8: `ionic help` only lists `ionic cordova *` commands in project directory

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2143]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

`ionic help` only lists `ionic cordova *` commands in project folder, not when you are outside of a project folder. 

#### What behavior are you expecting?

It should either display all project commands all the time or show none of them but replace the list with a message "you are not in a project directory".

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. `ionic info`
3. Go to project directory
4. `ionic info`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
I agree. I will hide project commands outside of project directories. 👍

**Comment by qasimraza1979** [comment]
What exactly this mean
"You are not in an Ionic project directory. Project context may be missing."

I am already in the project directory. Do I need to go to some specific folder. As I am in a folder where I can see
src folder
node_modules folder
package.json
protractor.conf.js
Readme.md
etc...

**Comment by piotrowski** [comment]
Step 1: Create a new issue and don't reply to an old, closed one that is totally unrelated to your problem. Thank you.
