### ISSUE TITLE
v3-beta8: `ionic login` doesn't tell me that I already am logged in

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2147]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

When I run `ionic login`twice it just does the same thing two times.

#### What behavior are you expecting?

Small information "You are already logged in. Do you want to log out and log in to another account?"

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. `ionic login`
3. `ionic login`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
Good idea, thanks!
