### ISSUE TITLE
v3-beta8: `ionic start` also works when already in a project directory

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2148]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

When I run `ionic start` in a project directory it does exactly the same thing as when I am not.

#### What behavior are you expecting?

Small error message "You are already in a project directory. Please go somewhere else". Or "You are already in a project directory. Do you really wont to create another Ionic project here?" (if this makes sense in any case)

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. `ionic start test`
3. `cd test`
4. `ionic start test2`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
Doooone 🎉
