### ISSUE TITLE
Running app with live reload from a directory that is not a project hangs

### ISSUE THREAD

**Issue by gnomeontherun** [driftyco/ionic-cli#215]
If you run the `ionic run -l` command without being in an Ionic project, it will just wait. I suspect it is waiting for the livereload server to start, but doesn't have a timeout or check if there is a project.

**Comment by jbavari** [comment]
I'm on it. Thanks for reporting.

**Comment by jbavari** [comment]
@gnomeontherun This should be fixed in the latest version, 1.3.14. Thanks again for reporting.
