### ISSUE TITLE
v3-beta8: `ionic g` generates "wrong" import path on Windows

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2150]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

Calling `ionic g component meh` on Windows add this line to `app.module.ts`:

`import { MehComponent } from '..\components\meh/meh';`

#### What behavior are you expecting?

`import { MehComponent } from '../components/meh/meh';`

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Go to project directory
3. `ionic g component meh`
4. Look at changed files

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by piotrowski** [comment]
(Same for pipes, providers and directives)

**Comment by piotrowski** [comment]
Follow up error in `ionic serve`

![bildschirmfoto am 2017-04-26 um 17 16 03](https://cloud.githubusercontent.com/assets/183673/25442000/1de84840-2aa4-11e7-8d40-4bc24894c41f.png)

**Comment by jgw96** [comment]
Hello @piotrowski , thanks for opening an issue with us. I just pushed a fix for this and would love if you could test it as I do not have access to a windows machine. Would you mind running `npm install @ionic/app-scripts@1.3.5-201704261923 --save-dev` and seeing if that fixes the issue for you? That is a nightly release of app-scripts that i just published that has my fix.

**Comment by piotrowski** [comment]
I did and this fixed it.

**Comment by jgw96** [comment]
Awesome, thanks for testing!

**Comment by piotrowski** [comment]
Problems exists again in v3-rc0 and app-scripts 1.3.6:

Complete `ionic info` where I got wrong paths again:


global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
@piotrowski This will be fixed in the next app-scripts release.
