### ISSUE TITLE
v3-beta8: `ionic help g` is missing `provider` in help text

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2151]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

`ionic help g` is missing `provider` in help text. It is one of the examples, but the help text doesn't list it:

> Generate pipes, components, pages, directives, and tabs (ionic-angular >= 3.0.0)

#### What behavior are you expecting?

> Generate pipes, components, pages, directives, providers and tabs (ionic-angular >= 3.0.0)

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. run `ionic help g`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
Picky, I love it! 😄
