### ISSUE TITLE
v3-beta8: `ionic info` is missing Cordova data outside project directoy

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2153]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

If you run `ionic info` outside a project directory it is missing the "Cordova" line:

```
PS C:\Users\Jan\Documents> ionic info

npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

#### What behavior are you expecting?

Cordova info should be present, too:

```
PS C:\Users\Jan\Documents\beta8test2> ionic info

npm (global):

    @ionic/cli-utils : 0.0.12
    cordova          : 6.5.0
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```` 

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Run `ionic info` outside and inside project directory

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
But outside of a Cordova project, we don't necessarily care about the Cordova version. I will update our issue template to say "run ionic info inside your project directory"
