### ISSUE TITLE
v3-beta8: `ionic cordova platform update` doesn't work

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2155]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-beta8

#### Short description of the problem:

I think `ionic cordova platform update` currently doesn't run the cordova command as it checks if the platform is already there. Of course it is, I want to update it:

```
PS C:\Users\Jan\Documents\beta8test2> ionic cordova platform update android
[OK] Platform android already exists.
```

```
PS C:\Users\Jan\Documents\beta8test2> cordova platform update android
Updating android project...
Subproject Path: CordovaLib
Android project updated with cordova-android@6.1.2
```

#### What behavior are you expecting?

Same as directly calling `cordova`.

**Steps to reproduce:**
1. Install v3.0.0-beta8 CLI
2. Go to project directory
3. `ionic cordova platform add android`
4. `ionic cordova platform update android`

**Post the output of `ionic info` below please**

```
npm (global):

    @ionic/cli-utils : 0.0.12
    cordova          : 6.5.0
    ionic            : 3.0.0-beta8

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by piotrowski** [comment]
Problem **persists** after running npm i @ionic/cli-utils@beta as we talked about on Slack. Probably more a logic error.

**Comment by dwieeb** [comment]
That was embarrassing...
