### ISSUE TITLE
feature: generate ressources for specific paltform

### ISSUE THREAD

**Issue by MTechDE** [driftyco/ionic-cli#2157]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta8

#### Short description of the problem:
In CLI 2.0 it was possible to generate the icons and splash screen for a specific platform with the platform tag like `ionic resources android`

In V3 it should also be possible because I use different Icons for Android and iOS. Otherwise, the command always overrides the icons and splash screens of both platforms.

`ionic cordova resources android`

**Comment by dwieeb** [comment]
This will be in the next release of the CLI. Thank you!
