### ISSUE TITLE
How To Solved Ionic  Run Command No Longer Available ?

### ISSUE THREAD

**Issue by romandahidayat** [driftyco/ionic-cli#2158]
When I Try to run my ionic project the terminal giving some error ? how to solved this ? any suggession. thanks.
$ sudo ionic run android
The run command is no longer available. To find out more about the equivalent please run:

  ionic cordova run --help

My ionic Info
>   Your system information:

    Cordova CLI: 6.5.0
    Ionic Framework Version: 3.0.0
    Ionic CLI Version: 3.0.0-beta7
    ios-deploy version: 1.9.1
    ios-sim version: 5.0.13
    OS: macOS Sierra
    Node Version: v6.9.5
    Xcode version: Xcode 8.3.1 Build version 8E1000a

**Comment by dwieeb** [comment]
Can you update your CLI? beta8 is out and beta9 will soon be out.

Next, did you run `ionic cordova run --help`?

**Comment by romandahidayat** [comment]
@dwieeb solved after im update Ionic CLI to latest version ..Thankyou
