### ISSUE TITLE
Application Error "File:///android_asset/www/index.html"

### ISSUE THREAD

**Issue by romandahidayat** [driftyco/ionic-cli#2162]
After i build to Android and i run the apps , some error show, "Aplication Error , The connection server unsuccesfully "File:///android_asset/www/index.html", 

this my ionic info

> Your system information:

Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.5
Xcode version: Xcode 8.3.1 Build version 8E1000a

a was add in config.xml 
`<preference name="loadUrlTimeoutValue" value="700000" />`

but nothing solved ? 
any suggestion guys ? thanks

**Comment by zindelluib** [comment]
Are you using Google Maps or you are calling css/js from a CDN ?

**Comment by romandahidayat** [comment]
no im just using get image or json from url ....? how to solved this ? in fast connection its working but in low connection error showed.  @zindelluib

**Comment by zindelluib** [comment]
@romandahidayat  I already encountered that before ... where do you load your image/json in the <head>?
If that is the case you have to check if there is an active connection before loading that external resources...

**Comment by fashmadetecheasy** [comment]
i created img folder in the www folder and i used simple html tag lo load all my images 

"<img src="img/subjectImg/fina18.png">" 

after  add in config.xml
<preference name="loadUrlTimeoutValue" value="700000" />

still see the same error ..i need help pls to same my job am running out of time..

Thanks in advance

**Comment by romandahidayat** [comment]
do you mean is i must create condition to check the connection ? @zindelluib

**Comment by romandahidayat** [comment]
issue was solved when i build <platform> --prod and i add <preference name="loadUrlTimeoutValue" value="700000" /> in config.xml  thanks all

**Comment by siddhartha84** [comment]
In my case this path is working:

var file = 'file:///android_asset/www/assets/lolc.html';
