### ISSUE TITLE
No TS sourcemaps with ionic serve

### ISSUE THREAD

**Issue by nfantone** [driftyco/ionic-cli#2165]
#### What version of the CLI are you using? Output of `ionic --version`

```sh
→ ionic --version
3.0.0-beta9
```

#### Short description of the problem:

Running `ionic serve` generates es5 sourcemaps instead of mapping to original Typescript sources.

![image](https://cloud.githubusercontent.com/assets/476069/25498693/eaece56c-2b80-11e7-8941-54c0b558f27e.png)

#### What behavior are you expecting?

Typescript sourcemaps to be able to debug original code.

**Steps to reproduce:**
1. `ionic start myApp blank`
2. `cd myApp`
3. `ionic serve`

**Post the output of `ionic info` below please**
```sh
npm (global):

    @ionic/cli-utils : 1.0.0-beta0
    cordova          :  You have been opted out of telemetry. To change this, run: cordova telemetry on. 6.5.0
    ionic            : 3.0.0-beta9

npm (local):

    @ionic/app-scripts              : 1.3.5
    @ionic/cli-plugin-cordova       : 1.0.0-beta0
    @ionic/cli-plugin-ionic-angular : 1.0.0-beta0
    Ionic Framework                 : ionic-angular 3.1.0

System:

    Node       : v7.9.0
    OS         : macOS Sierra
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by nfantone** [comment]
Perhaps this belongs in https://github.com/driftyco/ionic-app-scripts? Unsure. Please, let me know if it is so.

**Comment by danbucholtz** [comment]
This is fixed in the latest `@ionic/app-scripts`.

Thanks,
Dan
