### ISSUE TITLE
ionic serve does not work on v3.beta10

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic-cli#2169]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta10

#### Short description of the problem:
I had several problems with latest release of cli v3, app-scripts and ionic-angular.
Now on beta.10 it seems that this bug is resolved https://github.com/driftyco/ionic-app-scripts/issues/927
but now there are other problems.

On running `ionic serve` I get no error as described in the bug before but, it is incredible fast and there is building nothing. So on change a file there is no live reload and also the ionic serve command is serving only the OLD cached app, so there is no running app-scripts.

```
/web-client-ionic$ ionic serve
Starting server: --port=8100 --livereload-port=35729 --address=0.0.0.0

Proxy added:/api => http://abc.dev/blablla/api
dev server running: http://localhost:8100

```
That's all

#### What behavior are you expecting?
Ionic serve should rebuild the code on launch and also live reload should work

#### Info
```
npm (global):
    @ionic/cli-utils : 1.0.0-beta1
    cordova          : 6.5.0 
    ionic            : 3.0.0-beta10

npm (local):
    @ionic/cli-plugin-cordova : 1.0.0-beta1
    @ionic/cli-plugin-ionic1  : 1.0.0-beta1
    Ionic Framework           : unknown

System:
    Node       : v6.10.2
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by mburger81** [comment]
I created a completely new ionic project with beta10 by doing a new `ionic start`, after that I copied my project files in the new created project and adapt any configuration files I changed before.
And there I noticed config.xml changed a lot, and doing this it seems this is resolving me the problem.

So for beta10 there is a migration problem!

Same as for error: #2170

**Comment by dwieeb** [comment]
Your project seems to have been identified as an Ionic 1 project, is that correct? You have the `@ionic/cli-plugin-ionic1` plugin installed.

**Comment by mburger81** [comment]
@dwieeb no I don't had the @ionic/cli-plugin-ionic1 installed, from a beta.11 this bug was resolved for me, I don't know why and how.
