### ISSUE TITLE
ionic info runs in error on 3.0.0-beta10

### ISSUE THREAD

**Issue by mburger81** [driftyco/ionic-cli#2170]
#### What version of the CLI are you using? Output of `ionic --version`
3.0.0-beta10

#### Short description of the problem:
On running `ionic info` I get this output
```
[ERROR] Error with ionic version.json file: FILE_NOT_FOUND

npm (global):
    @ionic/cli-utils : 1.0.0-beta1
    cordova          : 6.5.0 
    ionic            : 3.0.0-beta10

npm (local):
    @ionic/cli-plugin-cordova : 1.0.0-beta1
    @ionic/cli-plugin-ionic1  : 1.0.0-beta1
    Ionic Framework           : unknown

System:
    Node       : v6.10.2
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

As you can see there is an error on reading version.json file and also there is an unknown Ionic Framework in npm (local)

**Comment by piotrowski** [comment]
What version of Ionic Framework _is_ the project using? Maybe past the content of your `package.json`here.

**Comment by mburger81** [comment]
I used 3.1.0 and also 3.0.1

**Comment by mburger81** [comment]
I created a completely new ionic project with beta10 by doing a new ionic start, after that I copied my project files in the new created project and adapt any configuration files I changed before.
And there I noticed config.xml changed a lot, and doing this it seems this is resolving me the problem.

So for beta10 there is a migration problem!

Same as for error: #2169
