### ISSUE TITLE
v3: `ionic info` outputs `ionic` version as `ionic`, `ionic-angular` as `Ionic Framework`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2172]
Maybe "ionic" could also be changed to "Ionic CLI" to avoid confusion with super newb users that can'T distinguis between Ionic (CLI) and Ionic (Framework)? 

In the forum every few days there are super confused users that use `ionic info` after they installed stuff and are confused they are not seeing the version they want to, expect to etc.

Same for `ionic --version`by the way, having it output "Ionic CLI version is: 3.0.0-beta10" would help a lot.

**Comment by dwieeb** [comment]
Great input, thanks.

**Comment by dwieeb** [comment]
I think we're going to leave `ionic --version` alone--it serves its purpose and generally for beginners we ask for `ionic info` anyway. But the next version of the CLI will have more descriptive names (ionic -> Ionic CLI, cordova -> Cordova CLI). Thanks!
