### ISSUE TITLE
v3-rc0: Make (temporary) removal of Ionic Services/Cloud commands clearer in docs

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2177]
Right now the only place where I learn that `ionic package` will come back later, is in the changelog. As a Ionic Services/Cloud user that would make me insecure. Same for `push`, `security` etc - I think those are not needed any more? Then why not write this in the changes?

**Comment by mlynch** [comment]
Hey @piotrowski and others. We are working on a tweak of the "cloud" product that uses git as a core fabric, changing the way you interact with package and some of the other cloud features. So, the functionality will still be there, but through slightly different command sets.

Also, for push and security specifically, we are moving that configuration to the dashboard instead. Once we are closer we will have instructions on how to work with that.

Thanks for the patience as work through a bit of a transition period. More updates soon.
