### ISSUE TITLE
v3-rc0: Explain why CLI commands get removed

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2178]
Related to #2177: It would be great for users coming from v2 to understand *why* some CLI commands (not limited to Services/Cloud stuff) are removed. I am sure there are good reason, so why not state them?

**Comment by dwieeb** [comment]
We were going to explain this in the blog post, but I could probably put it in the changelog or something.

**Comment by dwieeb** [comment]
How's this? https://github.com/driftyco/ionic-cli/blob/v3/CHANGELOG.md

FYI Package support is coming.

**Comment by piotrowski** [comment]
Perfect!
