### ISSUE TITLE
v3-rc0: Add output to `ionic signup`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2179]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc.0

#### Short description of the problem:

`ionic signup`doesn't output anything:
```
PS C:\Users\Jan\Documents> ionic signup
```

#### What behavior are you expecting?

Something like `ionic docs`:
```
PS C:\Users\Jan\Documents> ionic docs
[OK] Launched Ionic docs in your browser!
```

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Ionic CLI        : 3.0.0-rc.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Thanks!
