### ISSUE TITLE
Gradle-wrapper fails to download gradle when behind a proxy

### ISSUE THREAD

**Issue by jabyrd3** [driftyco/ionic-cli#218]
Hey,

I'm seeing an issue where gradle is not honoring the proxy environment variable when trying to build with Crosswalk added. It looks like the connect library is timing out.

I attempted to add proxy settings to the gradle-wrapper.properties file as reccomened here in example 20.1: https://gradle.org/docs/current/userguide/build_environment.html.

The properties file gets overwritten by the build process itself and it doesn't respect my proxy settings in there either.

**Comment by jbavari** [comment]
Alright, i'll look into it. Thanks for reporting.

**Comment by jbavari** [comment]
@jabyrd3 - have you tried using the `gradle.properties` file in `platforms/android` instead? That file shouldn't get over-ridden.

**Comment by oyevtushok** [comment]
I used to have the same problem and indeed adding http/https proxy settings to `platforms/android/gradle.properties` helped

**Comment by phearme** [comment]
also fixed on my side updating proxy info in the platforms/android/gradle.properties.

**Comment by ruslan-kurkebayev** [comment]
putting my proxy details in ` platforms/android/gradle.properties` file helped me.
```
systemProp.http.proxyHost=www.somehost.org
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=userid
systemProp.http.proxyPassword=password
systemProp.http.nonProxyHosts=*.nonproxyrepos.com|localhost
systemProp.https.proxyHost=www.somehost.org
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=userid
systemProp.https.proxyPassword=password
systemProp.https.nonProxyHosts=*.nonproxyrepos.com|localhost
```

**Comment by tacoben** [comment]
hey folks - for a number of reasons I dont want to set things on the gradle.properties file and want to put these props in a commandline arguement... 

anyone have any luck figuring out how to do this?  I am dead in the water.  Cant use D or P inputs at commandline..

**Comment by TudorIoanMarin** [comment]
Hi, for ionic 3 there is no gradle.properties file in platforms/android, only a project.properties and setting the proxy there is not working for me. Any thoughts?

**Comment by spainFAN** [comment]
@TudorIoanMarin did you manage to configure the proxy in Ionic 3?

**Comment by hron84** [comment]
@TudorIoanMarin proxy config should go to `gradle.properties`  in your home folder
