### ISSUE TITLE
v3-rc0: How can I be logged in on a new node + npm + Ionic CLI installation?

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2180]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc.0

#### Short description of the problem:

When I `ionic login` the first time on a new node+npm and Ionic CLI installation I get this:

```
PS C:\Users\Jan\Documents> ionic login
? You are already logged in! Do you want to log in to another account? (Y/n)
```

Where is this login saved that it survives a completely new installation of everything?

#### What behavior are you expecting?

Not logged in after installing everthing.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Ionic CLI        : 3.0.0-rc.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
We store the tokens in `~/.ionic`. This is pretty standard CLI behavior.

**Comment by piotrowski** [comment]
Learn something every day.
