### ISSUE TITLE
v3-rc0: `ionic start` with missing Cordova tells me to install cordova plugin - but not where, and doesn't tell me if anything else is missing

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2182]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc.0

#### Short description of the problem:

When I `ionic start` with missing Cordova the output tells me to install cordova plugin - but not where (which should be IN the newly created project directory)

```
PS C:\Users\Jan\Documents> ionic start
? What would you like to name your project: rc0test
? What starter would you like to use: blank
✔ Creating directory C:\Users\Jan\Documents\rc0test - done!
✔ Downloading blank starter template - done!
✔ Updating project dependencies to add required plugins - done!
✔ Creating configuration file for the new project - done!
Installing dependencies may take several minutes!
✔ running command: npm install - done!
✔ running command: npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@beta - done!
✖ running command: npm install --save-dev --save-exact @ionic/cli-plugin-cordova@beta - failed!
[ERROR] An error occurred while running npm install --save-dev --save-exact @ionic/cli-plugin-cordova@beta (exit code 1):


        > @ionic/cli-plugin-cordova@1.0.0-rc.0 postinstall C:\Users\Jan\Documents\rc0test\node_modules\@ionic\cli-plugin-cordova
        > node ./bin/postinstall

        ###########################################################################################
        >>>>>                                                                                 <<<<<
        >>>>>                    Cordova CLI was not found on your PATH.                      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>    This plugin needs Cordova intalled globally. Please try the following:       <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                            npm install -g cordova                               <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>              If that doesn't work, see the installation docs:                   <<<<<
        >>>>> https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                               Sorry about that!                                 <<<<<
        >>>>>     When Cordova is installed, please try re-installing the plugin again:       <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                 npm install --save-dev @ionic/cli-plugin-cordova                <<<<<
        >>>>>                                                                                 <<<<<
        ###########################################################################################
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (curren
t: {"os":"win32","arch":"x64"})
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--s
ave-dev" "--save-exact" "@ionic/cli-plugin-cordova@beta"
        npm ERR! node v6.10.2
        npm ERR! npm  v3.10.10
        npm ERR! code ELIFECYCLE

        npm ERR! @ionic/cli-plugin-cordova@1.0.0-rc.0 postinstall: `node ./bin/postinstall`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the @ionic/cli-plugin-cordova@1.0.0-rc.0 postinstall script 'node ./bin/postinstall'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the @ionic/cli-plugin-cordova package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./bin/postinstall
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs @ionic/cli-plugin-cordova
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls @ionic/cli-plugin-cordova
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\Jan\Documents\rc0test\npm-debug.log
```

Also it is not clear if the project was started successfully anyway? Are any other steps missing?

#### What behavior are you expecting?

1. Tell me where to run the command
2. Tell me if `ionic start` was finished successfully

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Ionic CLI        : 3.0.0-rc.0

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
It's going to be hard to catch this error. Maybe if we didn't pre-install the plugins...

**Comment by piotrowski** [comment]
With "catch" you mean not exiting the process?

**Comment by dwieeb** [comment]
I just mean handle it nicely.

**Comment by chenbobowu** [comment]
I am having this problem. Has this issue been fixed?

**Comment by chenbobowu** [comment]
ChenDamins-MacBook-Air:george chendamin$ sudo ionic info
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

ChenDamins-MacBook-Air:george chendamin$ sudo npm install -g typescript
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
/usr/local/lib
└── typescript@2.3.2 

ChenDamins-MacBook-Air:george chendamin$ sudo ionic start myApp tabs
✔ Creating directory /Users/chendamin/Desktop/George/myApp - done!
Fetching app base (https://github.com/driftyco/ionic2-app-base/archive/master.tar.gz)
✔ Downloading - done!
Fetching starter template tabs (https://github.com/driftyco/ionic2-starter-tabs/archive/master.tar.gz)
✔ Downloading - done!
✔ Updating package.json with app details - done!
✔ Creating configuration file ionic.config.json - done!
Installing dependencies may take several minutes!
> npm install
✔ Running command - done!
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✔ Running command - done!
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
✖ Running command - failed!
[ERROR] An error occurred while running npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest (exit code 1):
        
        
        > @ionic/cli-plugin-cordova@1.0.0 postinstall /Users/chendamin/Desktop/George/myApp/node_modules/@ionic/cli-plugin-cordova
        > node ./bin/postinstall
        
        ###########################################################################################
        >>>>>                                                                                 <<<<<
        >>>>>                    Cordova CLI was not found on your PATH.                      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>    This plugin needs Cordova installed globally. Please try the following:      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                            npm install -g cordova                               <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>              If that doesn't work, see the installation docs:                   <<<<<
        >>>>> https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                               Sorry about that!                                 <<<<<
        >>>>>     When Cordova is installed, please try re-installing the plugin again:       <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                 npm install --save-dev @ionic/cli-plugin-cordova                <<<<<
        >>>>>                                                                                 <<<<<
        ###########################################################################################
        npm ERR! Darwin 16.5.0
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "--save-exact" "@ionic/cli-plugin-cordova@latest"
        npm ERR! node v6.10.3
        npm ERR! npm  v3.10.10
        npm ERR! code ELIFECYCLE
        
        npm ERR! @ionic/cli-plugin-cordova@1.0.0 postinstall: `node ./bin/postinstall`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the @ionic/cli-plugin-cordova@1.0.0 postinstall script 'node ./bin/postinstall'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the @ionic/cli-plugin-cordova package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./bin/postinstall
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs @ionic/cli-plugin-cordova
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls @ionic/cli-plugin-cordova
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /Users/chendamin/Desktop/George/myApp/npm-debug.log
