### ISSUE TITLE
v3-rc0: `npm i @ionic/cli-plugin-cordova` tells me I need to `npm install -g ios-deploy ios-sim` on Windows

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2183]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc.0

#### Short description of the problem:

```
PS C:\Users\Jan\Documents\rc0test> npm install --save-dev @ionic/cli-plugin-cordova

> @ionic/cli-plugin-cordova@0.0.12 postinstall C:\Users\Jan\Documents\rc0test\node_modules\@ionic\cli-plugin-cordova
> node ./bin/postinstall

You will need to install the following global dependencies in order to use this plugin.
npm install -g ios-deploy ios-sim

rc0test@0.0.1 C:\Users\Jan\Documents\rc0test
`-- @ionic/cli-plugin-cordova@0.0.12
  `-- @ionic/cli-utils@0.0.11
    +-- cross-spawn@4.0.2
    `-- string-width@2.0.0
      `-- is-fullwidth-code-point@2.0.0
```

I don't think this is useful on Windows, right?

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
You installed an old version. It no longer says that.

**Comment by piotrowski** [comment]
Ah, because I just did what the other error message said...
