### ISSUE TITLE
v3-rc0: `ionic start` with missing Cordova tells me to install wrong cordova plugin

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2184]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc.0

#### Short description of the problem:

When I `ionic start` with missing Cordova the output tells me to install cordova plugin - but without the `@beta` behind it needed to get the correct version.

```
PS C:\Users\Jan\Documents> ionic start
? What would you like to name your project: rc0test
? What starter would you like to use: blank
✔ Creating directory C:\Users\Jan\Documents\rc0test - done!
✔ Downloading blank starter template - done!
✔ Updating project dependencies to add required plugins - done!
✔ Creating configuration file for the new project - done!
Installing dependencies may take several minutes!
✔ running command: npm install - done!
✔ running command: npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@beta - done!
✖ running command: npm install --save-dev --save-exact @ionic/cli-plugin-cordova@beta - failed!
[ERROR] An error occurred while running npm install --save-dev --save-exact @ionic/cli-plugin-cordova@beta (exit code 1):


        > @ionic/cli-plugin-cordova@1.0.0-rc.0 postinstall C:\Users\Jan\Documents\rc0test\node_modules\@ionic\cli-plugin-cordova
        > node ./bin/postinstall

        ###########################################################################################
        >>>>>                                                                                 <<<<<
        >>>>>                    Cordova CLI was not found on your PATH.                      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>    This plugin needs Cordova intalled globally. Please try the following:       <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                            npm install -g cordova                               <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>              If that doesn't work, see the installation docs:                   <<<<<
        >>>>> https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                               Sorry about that!                                 <<<<<
        >>>>>     When Cordova is installed, please try re-installing the plugin again:       <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                 npm install --save-dev @ionic/cli-plugin-cordova                <<<<<
        >>>>>                                                                                 <<<<<
        ###########################################################################################
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (curren
t: {"os":"win32","arch":"x64"})
        npm ERR! Windows_NT 10.0.15063
        npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--s
ave-dev" "--save-exact" "@ionic/cli-plugin-cordova@beta"
        npm ERR! node v6.10.2
        npm ERR! npm  v3.10.10
        npm ERR! code ELIFECYCLE

        npm ERR! @ionic/cli-plugin-cordova@1.0.0-rc.0 postinstall: `node ./bin/postinstall`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the @ionic/cli-plugin-cordova@1.0.0-rc.0 postinstall script 'node ./bin/postinstall'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the @ionic/cli-plugin-cordova package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./bin/postinstall
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs @ionic/cli-plugin-cordova
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls @ionic/cli-plugin-cordova
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     C:\Users\Jan\Documents\rc0test\npm-debug.log
```

Maybe side effect: Even after installing this version, `ionic info` doesn't list this plugin.

#### What behavior are you expecting?

Maybe nothing as this only is relevant to rc0 and will be correct for release?

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
I can't know which dist tag you're using in a post install hook...

This won't be a problem with the stable release.

**Comment by Ritzlgrmft** [comment]
I had the same issue today on a clean machine with the stable release. Fortunately, the error is quite self-explaining: since I just installed everything I needed, I had forgotten to add my `npm` directory (where is `cordova.cmd`) to the `PATH`. 

After adding the directory to the `PATH`, I was able to `npm install @ionic/cli-plugin-cordova` without problems.

**Comment by cozzbie** [comment]
A stable release is out and I am having the same issues. @dwieeb 

```
global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : not installed
    ios-sim    : not installed

```

Everything is installed and is accessible via `sudo <command> -v` but for some reason `npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest` always throws a  `Cordova CLI was not found on your PATH.` error meanwhile `sudo cordova -v` shows `7.0.1` meaning its installed. [Heres the npm error output](https://drive.google.com/file/d/0B63viywfAl9jY2hjWjBTSmRGRms/view?usp=sharing)

**Comment by dwieeb** [comment]
@cozzbie You didn't read the issue. I was referring to the output of the differing dist tag. `@beta` vs `@latest`.

**Comment by chenbobowu** [comment]
@dwieeb 

ChenDamins-MacBook-Air:helpdesk-app chendamin$ sudo ionic cordova
? Looks like this is an Ionic Angular project, would you like to install @ionic/
cli-plugin-ionic-angular and continue? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
✔ Running command - done!
? The plugin @ionic/cli-plugin-cordova is not installed. Would you like to insta
ll it and continue? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
✖ Running command - failed!
[ERROR] An error occurred while running npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest (exit code 1):
        
        
        > @ionic/cli-plugin-cordova@1.0.0 postinstall /Users/chendamin/Desktop/George/helpdesk-app/node_modules/@ionic/cli-plugin-cordova
        > node ./bin/postinstall
        
        ###########################################################################################
        >>>>>                                                                                 <<<<<
        >>>>>                    Cordova CLI was not found on your PATH.                      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>    This plugin needs Cordova installed globally. Please try the following:      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                            npm install -g cordova                               <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>              If that doesn't work, see the installation docs:                   <<<<<
        >>>>> https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                               Sorry about that!                                 <<<<<
        >>>>>     When Cordova is installed, please try re-installing the plugin again:       <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                 npm install --save-dev @ionic/cli-plugin-cordova                <<<<<
        >>>>>                                                                                 <<<<<
        ###########################################################################################
        npm WARN @ionic/cli-plugin-ionic-angular@1.0.0 requires a peer of @ionic/app-scripts@^1.3.1 but none was installed.
        npm ERR! Darwin 16.5.0
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "--save-exact" "@ionic/cli-plugin-cordova@latest"
        npm ERR! node v6.10.3
        npm ERR! npm  v3.10.10
        npm ERR! code ELIFECYCLE
        
        npm ERR! @ionic/cli-plugin-cordova@1.0.0 postinstall: `node ./bin/postinstall`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the @ionic/cli-plugin-cordova@1.0.0 postinstall script 'node ./bin/postinstall'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the @ionic/cli-plugin-cordova package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./bin/postinstall
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs @ionic/cli-plugin-cordova
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls @ionic/cli-plugin-cordova
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /Users/chendamin/Desktop/George/helpdesk-app/npm-debug.log
        

ChenDamins-MacBook-Air:helpdesk-app chendamin$ sudo npm install --save-dev --save-exact @ionic/cli-plugin-cordova@beta

> @ionic/cli-plugin-cordova@1.0.0-rc.2 postinstall /Users/chendamin/Desktop/George/helpdesk-app/node_modules/@ionic/cli-plugin-cordova
> node ./bin/postinstall

###########################################################################################
>>>>>                                                                                 <<<<<
>>>>>                    Cordova CLI was not found on your PATH.                      <<<<<
>>>>>                                                                                 <<<<<
>>>>>    This plugin needs Cordova installed globally. Please try the following:      <<<<<
>>>>>                                                                                 <<<<<
>>>>>                            npm install -g cordova                               <<<<<
>>>>>                                                                                 <<<<<
>>>>>              If that doesn't work, see the installation docs:                   <<<<<
>>>>> https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli <<<<<
>>>>>                                                                                 <<<<<
>>>>>                               Sorry about that!                                 <<<<<
>>>>>     When Cordova is installed, please try re-installing the plugin again:       <<<<<
>>>>>                                                                                 <<<<<
>>>>>                 npm install --save-dev @ionic/cli-plugin-cordova                <<<<<
>>>>>                                                                                 <<<<<
###########################################################################################
npm WARN @ionic/cli-plugin-ionic-angular@1.0.0 requires a peer of @ionic/app-scripts@^1.3.1 but none was installed.
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "--save-exact" "@ionic/cli-plugin-cordova@beta"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! @ionic/cli-plugin-cordova@1.0.0-rc.2 postinstall: `node ./bin/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ionic/cli-plugin-cordova@1.0.0-rc.2 postinstall script 'node ./bin/postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @ionic/cli-plugin-cordova package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @ionic/cli-plugin-cordova
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @ionic/cli-plugin-cordova
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chendamin/Desktop/George/helpdesk-app/npm-debug.log

**Comment by chenbobowu** [comment]
Having problem of installing Cordova. It should be path's problem.

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : not installed
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : not installed

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
@chenbobowu The best resource for you will be this: https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli

**Comment by chenbobowu** [comment]
@dwieeb Thanks for your reply. I am still having this issue.

ChenDamins-MacBook-Air:myApp chendamin$ sudo ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 

ChenDamins-MacBook-Air:myApp chendamin$ sudo ionic cordova add ios
? The plugin @ionic/cli-plugin-cordova is not installed. Would you like to insta
ll it and continue? Yes
> npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
✖ Running command - failed!
[ERROR] An error occurred while running npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest (exit code 1):
        
        
        > @ionic/cli-plugin-cordova@1.0.0 postinstall /Users/chendamin/Desktop/George/myApp/node_modules/@ionic/cli-plugin-cordova
        > node ./bin/postinstall
        
        ###########################################################################################
        >>>>>                                                                                 <<<<<
        >>>>>                    Cordova CLI was not found on your PATH.                      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>    This plugin needs Cordova installed globally. Please try the following:      <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                            npm install -g cordova                               <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>              If that doesn't work, see the installation docs:                   <<<<<
        >>>>> https://cordova.apache.org/docs/en/latest/guide/cli/#installing-the-cordova-cli <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                               Sorry about that!                                 <<<<<
        >>>>>     When Cordova is installed, please try re-installing the plugin again:       <<<<<
        >>>>>                                                                                 <<<<<
        >>>>>                 npm install --save-dev @ionic/cli-plugin-cordova                <<<<<
        >>>>>                                                                                 <<<<<
        ###########################################################################################
        npm ERR! Darwin 16.5.0
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "--save-exact" "@ionic/cli-plugin-cordova@latest"
        npm ERR! node v6.10.3
        npm ERR! npm  v3.10.10
        npm ERR! code ELIFECYCLE
        
        npm ERR! @ionic/cli-plugin-cordova@1.0.0 postinstall: `node ./bin/postinstall`
        npm ERR! Exit status 1
        npm ERR! 
        npm ERR! Failed at the @ionic/cli-plugin-cordova@1.0.0 postinstall script 'node ./bin/postinstall'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the @ionic/cli-plugin-cordova package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./bin/postinstall
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs @ionic/cli-plugin-cordova
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls @ionic/cli-plugin-cordova
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /Users/chendamin/Desktop/George/myApp/npm-debug.log

**Comment by chenbobowu** [comment]
@dwieeb Hi, Dan, I install back the older version **(npm install -g ionic@2.2.3 cordova@6.5.0)**, everything works fine. I will just wait for a more stable version. Thanks.

**Comment by piotrowski** [comment]
@chenbobowu Your problem is not Cordova, but you are missing the CLI plugins. 

If you have a v2+ project, do this https://github.com/driftyco/ionic-cli#existing-project and if you have a v1 project do this: https://github.com/driftyco/ionic-cli#existing-project-1

If this doesn't work you have an unrelated problem, please open a new issue and describe the problem.

PS: All the output you posted is missing vital information as you don't format the output as "code" using the `<>` button.
