### ISSUE TITLE
v3-rc0: `ionic g` first asks for name, then tells me I chose invalid generator type

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2185]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc.0

#### Short description of the problem:

```
PS C:\Users\Jan\Documents\rc0test> ionic g com
? What should the name be? foo
[ERROR] com is not a valid generator type.
```

#### What behavior are you expecting?

```
PS C:\Users\Jan\Documents\rc0test> ionic g com
[ERROR] com is not a valid generator type.
```

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Haha, that's silly. Fixed.
