### ISSUE TITLE
v3-rc0: Entering non-number to `ionic tabs` "How many tabs?" question crashes

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2186]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

```
PS C:\Users\Jan\Documents\rc0test> ionic g tabs
? What should the name be? Name
? How many tabs? Five
TypeError: Cannot read property 'find' of undefined
    at Object.tabsModuleManipulation (C:\Users\Jan\Documents\rc0test\node_modules\@ionic\app-scripts\dist\generators\util.js:171:31)
    at C:\Users\Jan\Documents\rc0test\node_modules\@ionic\app-scripts\dist\generators.js:36:16
```

#### What behavior are you expecting?

Error message that only numbers are valid reponse, retry.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Thanks!
