### ISSUE TITLE
v3-rc0: `ionic upload` without `ionic serve` first fails

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2187]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

When running `ionic upload` without `ionic serve` first the upload fails with this unfriendly error message:

```
PS C:\Users\Jan\Documents\rc0test> ionic upload
✔ Requesting snapshot upload - done!
Assertion failed: 0, file src\win\stream.c, line 200
```

#### What behavior are you expecting?

`You have to run `ionic serve` or `npm run build` first before you can upload the app to Ionic`

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Likely because the actual www files just aren't built yet.

**Comment by piotrowski** [comment]
Yes, /www is empty at that moment.

**Comment by dwieeb** [comment]
Addressed in https://github.com/driftyco/ionic-cli/commit/5262b4d9762e90d1ce25c715e00283f714fbffa6

Thanks!
