### ISSUE TITLE
v3-rc0: No information on how to cleanly exit `ionic serve`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2188]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

Running `ionic serve` gives no information on how to cleanly exit this process. Especially for GUI users on Windows using Ctrl+C to exit a running process is not common knowledge. I think many of them have to close the command line or open a new one to get back to the shell - I know I did for a long time ;)

(Or is there even a better, cleaner way to exit `ionic serve` I don't know about?)

#### What behavior are you expecting?

`Starting process build process, server and then opening project in browser. Use Ctrl+C to quit this process and go back to command line.`

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Thanks, that's a good bit of info to put in any long-running terminal process
