### ISSUE TITLE
v3-rc0: Old commands hang

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2190]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

Executing any of the old commands don't give me my command line back:

```
PS C:\Users\Jan\Documents\rc0test> ionic build
The build command has been renamed. To find out more, run:

  ionic cordova build --help

```
I have to stop the process using Ctrl+C.

#### What behavior are you expecting?

```
PS C:\Users\Jan\Documents\rc0test> ionic build
The build command has been renamed. To find out more, run:

  ionic cordova build --help

PS C:\Users\Jan\Documents\rc0test> 
```

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Whoops!

**Comment by charmaine** [comment]
I'm still having the exact same problem as listed above. Any suggestions for fixes?
