### ISSUE TITLE
v3-rc0: `ionic cordova platform * ios` should work on Windows

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2191]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

CLI doesn't let me add the ios platform:

``` 
PS C:\Users\Jan\Documents\rc0test> ionic cordova platform add ios
[ERROR] You cannot use Cordova for iOS unless you are on macOS.
```

#### What behavior are you expecting?

Shouldn't it be possible to `platform add`, `platform update` and `platform remove` the ios platform on Windows too, but only `emulate`, `run`, `compile` and `build` should be disabled?

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
I might be missing something. Why would you want to add the platform if you can't use it?

**Comment by piotrowski** [comment]
Because I want to later build it on my Mac where I check out the project from Git when I am "done" or use Ionic Package. I think not having the platform there also might have negative effects on plugin installation etc.

**Comment by piotrowski** [comment]
Another reason: Becuase `cordova` lets me:

```
PS C:\Users\Jan\Documents\rc0test> cordova platform add ios
WARNING: Applications for platform ios can not be built on this OS - win32.
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms\ios
        Package: io.ionic.starter
        Name: MyApp
iOS project created with cordova-ios@4.3.1
Installing "cordova-plugin-console" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-whitelist" for ios
Installing "ionic-plugin-keyboard" for ios
PS C:\Users\Jan\Documents\rc0test>
```

and then later:

```
PS C:\Users\Jan\Documents\rc0test> cordova run ios
Error: xcodebuild was not found. Please install version 7.0.0 or greater from App Store
PS C:\Users\Jan\Documents\rc0test> cordova build ios
Error: xcodebuild was not found. Please install version 7.0.0 or greater from App Store
PS C:\Users\Jan\Documents\rc0test> cordova compile ios
Error: xcodebuild was not found. Please install version 7.0.0 or greater from App Store
```

**Comment by dwieeb** [comment]
We just won't do this check, haha
