### ISSUE TITLE
v3-rc0: Add `cordova platform check` and `cordova platform save` to `ionic cordova platform`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2192]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

To have a full replacement of `ionic state` I think `cordova platform check` and `cordova platform save` should be added to `ionic cordova platform`.

```
PS C:\Users\Jan\Documents\rc0test> cordova help platform
Synopsis

    cordova platform <command> [options]

Manage project platforms
    [...]
    check ............................. List platforms which can be updated by `cordova platform update`
    save .............................. Save version of all platforms added to config.xml
```

#### What behavior are you expecting?

Directy proxy to Cordova commands.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by piotrowski** [comment]
Same for `cordova plugin save`.

**Comment by dwieeb** [comment]
Alrighty!

**Comment by piotrowski** [comment]
I think this didn't make it into the `--help`, possible?
