### ISSUE TITLE
v3-rc0: `ionic cordova resources` changes indendation of `config.xml`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2193]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

Executing `ionic cordova resources` changes the indendation of the whole `config.xml` file and marks all lines as changed in git. (Tested on newly created Ionic project created with `ionic start` and blank starter template)

#### What behavior are you expecting?

`ionic cordova resources` only changes entries that actually were changed in the file.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Known issue--I blame xml2js. We are looking into using elementtree, which is the package Cordova uses to modify config.xml.

**Comment by dwieeb** [comment]
I can't seem to find a decent library in node for xml parsing. I don't think I'm gonna worry about this for now. The CLI will use 4 spaces for indentation of config.xml because that's what Cordova uses. It will need to rewrite significant portions of the file, especially when dealing with resources, unfortunately.

**Comment by piotrowski** [comment]
Then maybe we should just adapt the indentation of configure.xml in the base and starter templates? Or will this break other, unrelated stuff?

**Comment by dwieeb** [comment]
Yep, I am working on it.
