### ISSUE TITLE
v3-rc0: Ionic View doesn't work

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2198]
#### What version of the CLI are you using? Output of `ionic --version`

3.0.0-rc0

#### Short description of the problem:

Apps uploaded using the v3 CLI are not visible in Ionic view and trying to load them using their App ID gives the error message "PLEASE ENTER A VALID APP ID".

#### What behavior are you expecting?

Apps show up and can be added via their App ID.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0-rc.0

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
@piotrowski I am going to be releasing the next RC without resolving this issue. Neither myself nor a coworker were able to reproduce this issue. Could you please try again?

**Comment by piotrowski** [comment]
As we tested with rc1 canary this seems to have been caused by the broken `ionic upload` on Windows.

**Comment by impactcolor** [comment]
I experienced the same issue.  After testing it I realized there is a new ionic view app which needed to be download that shows the apps in my Pro account.
