### ISSUE TITLE
'Ionic Cordova Resources' ignores Orientation preference in config.xml for Splashscreen

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2199]
_From @MarkErik on April 30, 2017 10:9_

**Short description of the problem:**
ionic cordova resources command creates and includes landscape splash screen images even when none are requested or desired.

In my config.xml I have set the preference for our app to only be in Portrait mode.
<preference name="Orientation" value="portrait"/>
And in the <platform name="android"> section, I have no entries for any landscape  <splash src="resources/android/splash/drawable-land-...

When I execute the 'resources' command it generates the landscape resources and adds the <splash src=...> for landscape resources. Thus increasing the app size.

**What behavior are you expecting?**
That the 'ionic cordova resources' command would respect the orientation preference and only generate and include the required assets.

I did not encounter this with the Ionic v2 CLI.
And from the V1 docs: http://ionicframework.com/docs/v1/cli/icon-splashscreen.html
"Additionally, when the Orientation preference config is set to either landscape or portrait mode, then only the necessary images will be generated."

**Steps to reproduce:**
1. Set the preference for Portrait in the config.xml <preference name="Orientation" value="portrait"/>
2. Check that there are no splash src references to landscape assets in the config.xml
3. Run 'ionic cordova resources'
4. See that now there are references to landscape splash screens in the config.xml
5. Build for Android --prod, and see that the landscape assets are included in the APK (and the /res directory)

**Which @ionic/app-scripts version are you using?**
global packages:
    @ionic/cli-utils : 1.0.0-rc.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0-rc.0

local packages:
    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.0.0-rc.0
    @ionic/cli-plugin-ionic-angular : 1.0.0-rc.0
    Ionic Framework                 : ionic-angular 3.1.0

System:
    Node       : v7.7.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.0 
    ios-sim    : 5.0.11 

_Copied from original issue: driftyco/ionic-app-scripts#945_

**Comment by dwieeb** [comment]
Thanks @MarkErik! This should be fixed in the next version
