### ISSUE TITLE
v3: Template/Starter URLs not visible in `ionic start`?

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2202]
So while testing v3 I noticed that the URLs of the base and starter templates are not visible during the execution of `ionic start` any more by default. 

That might not be the best idea, as there seems to quite some users that actually can't download from Github and so are getting errors right now - but at least the errors contain the URL that they are trying to download:

https://forum.ionicframework.com/t/unable-to-start-an-application-using-ionic/88629

How will this be in CLI v3?

**Comment by MTechDE** [comment]
The CLI should detect this problem and should explain to the user what he should do because at the end it is just a proxy problem I guess.

**Comment by dwieeb** [comment]
I think some of this is mitigated with the detection of proxy environment variables (and the subsequent prompting to install the `@ionic/cli-plugin-proxy` module, which automatically makes use of them). We should, however, be catching such connection errors and offering solutions, such as how to proxy, and debugging steps.

**Comment by piotrowski** [comment]
Totally agree on the handling of proxy stuff.

I still think surfacing the URLs of the base and starter templates being downloaded would be useful (if only educating what is happening).

**Comment by dwieeb** [comment]
I agree. One of our goals was to provide more guidance/education. Showing the download URL is aligned with that goal.

**Comment by dwieeb** [comment]
Okay, we're all set! Thank you!
