### ISSUE TITLE
v3-rc1: `ionic link` could warn if project is already linked to ID

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2207]
Right now `ionic link` outputs the same list of projects no matter if the project is already connected to an app from apps.ionic.io or not. Maybe the command could output a warning "Your project is already connected to app id 12345" if the project is already connected to an app id.

**Comment by dwieeb** [comment]
We were actually doing this, but it makes more sense to put this at the start of the process 👍
