### ISSUE TITLE
v3: Preparation for Cordova 7?

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2208]
Just stumbled over a draft for the release blog post for Cordova 7, which changes some stuff:

https://github.com/apache/cordova-docs/pull/699/files

This could be relevant for Ionic CLI.

**Comment by piotrowski** [comment]
From a first reading:

- State management is duplicated to `package.json` (from `config.xml`) - might get confusing with the Ionic stuff already in there
- `--save` is now default behaviour, so not needed as a param any more (`--nosave` was added for previous behaviour)

**Comment by dwieeb** [comment]
Yeah, I heard about them wanting to move dependencies to `package.json`. These aren't issues for us, we'll still enforce `--save` for Cordova 6. The Ionic platform/plugin stuff in `package.json` can be deleted.

I like all these changes. 😄

**Comment by piotrowski** [comment]
Me too.

Shouldn't you maybe already add `--nosave` for the current default case so functionality doesn't change when Cordova 7 is released?

**Comment by danielehrhardt** [comment]
But i do not understand why i have to add the cordova plugins in the package.json and the config.xml
