### ISSUE TITLE
feature(package): --prod flag

### ISSUE THREAD

**Issue by danielsogl** [driftyco/ionic-cli#2210]
#### Short description of the problem:
I noticed that when you want to build your Ionic app with the cloud package service, you can't use the --prod flag.

#### What behavior are you expecting?
1. If you build your app with the package service and the --release flag, the CLI should run the prod build. Otherwise, the build app is very slow.
2. The --prod flag should be optional

Related to:
https://forum.ionicframework.com/t/ionic-services-package-cloud-build-does-not-respect-the-prod-flag/84827/26

**Comment by roryza** [comment]
It looks like I submitted a duplicate #2211. I guess you submitted while I was typing it up.

**Comment by dwieeb** [comment]
Thanks @danielsogl and @roryza ! The flag will be in the next v3 release.

**Comment by roryza** [comment]
Fantastic. Thanks very much. I think this will help a lot with people getting started with ionic and slow load times etc.
