### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by ricardo-mello** [driftyco/ionic-cli#2216]
There is any doc to let us know how to setup a fork of ionic cli on a local machine so we can contribute with the project? Tried do it by myself without success.

**Comment by dwieeb** [comment]
@ricardo-mello We're probably not going to be accepting pull requests on v2 of the CLI anymore. Please start using v3. See v3's [CONTRIBUTING.md](https://github.com/driftyco/ionic-cli/blob/v3/CONTRIBUTING.md)

Thanks for your interest!
