### ISSUE TITLE
[feature request] add .ionignore for www files

### ISSUE THREAD

**Issue by AliMD** [driftyco/ionic-cli#222]
In lot of project we have some file like un minified js or sass files and we dont want to included in apk files even in debug mod
could you please add something like `git ignore` for `www` folder in `ionic build` process
Thank you in advance

**Comment by jeveloper** [comment]
This would be a great feature, Anyone noticed how many files are loaded from momentjs 
thanks

**Comment by AliMD** [comment]
After 2 mount, I forgoted this issue!
I solve my problem by chance gulp structure use customer hook
I'm happy with my customization but how this feature accepted officially
