### ISSUE TITLE
'ionic serve -al' on ionic1 project opens error page not Ionic lab, using Ionic CLI 3.0.0-rc.1

### ISSUE THREAD

**Issue by jsanta** [driftyco/ionic-cli#2222]
#### What version of the CLI are you using? Output of `ionic --version`
```
→ ionic --version
3.0.0-rc.1
```

#### Short description of the problem:
Executing 
`ionic serve -al`
opens a browser on _http://localhost:8100/ionic-lab_ with this message:

> Error: ENOENT: no such file or directory, stat '/project_path/node_modules/@ionic/cli-plugin-ionic1/lab/index.html'

#### What behavior are you expecting?
Browser should open the Ionic lab page.

**Steps to reproduce:**
1. Go to any Ionic1 project folder
2. Run ionic serve -al

**Post the output of `ionic info` below please**
```
→ ionic info

global packages:

    @ionic/cli-utils : 1.0.0-rc.1
    Ionic CLI        : 3.0.0-rc.1

local packages:

    @ionic/cli-plugin-ionic1 : 1.0.0-rc.1
    Ionic Framework          : ionic1 1.3.0

System:

    Node       : v7.7.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.6
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Pointing  directly to _http://localhost:8100_ works as expected and the app is opened on the browser.

**Comment by dwieeb** [comment]
Thanks @jsanta , this will be fixed in the next RC.

Sort of irrelevant question, but can I ask what `-a` is in your command? 

Lab should just be `ionic serve -l`

**Comment by jsanta** [comment]
Thanks @dwieeb 
The -a parameter is inherited from my ionic1-cli usage. I had to use it so my computer linked the ionic server on all network interfaces, otherwise I had to use the real IP to open Ionic Lab.

**Comment by dwieeb** [comment]
I didn't see it in the help of the ionic cli v1/v2. That's why I asked. It won't do anything in v3. We do offer an `--address` flag, though. It defaults to `0.0.0.0` which should be sufficient.

3.0.0-rc.2 is out by the way. Please test and see if your issue is resolve 😄

**Comment by jsanta** [comment]
After removing node_modules/@ionic folder and running ionic serve -l -c -s everything worked as expected.
Thanks! :)
