### ISSUE TITLE
I can not create a Ionic V1 project

### ISSUE THREAD

**Issue by onigetoc** [driftyco/ionic-cli#2223]
I have the Ionic V2 Cli, but i want to install a V1 Ionic project.
It always install a V2 project 
even if i do: `ionic start myapp --v1`

**Comment by ricardo-mello** [comment]
Can you send the output of `ionic --version`?

**Comment by onigetoc** [comment]
To be sure, i did a copy paste of `--v1` and it worked.

**Comment by onigetoc** [comment]
I it worked only in the same time when i choosed the blank app.

**Comment by JavMendoza** [comment]
Hi, 
im having the same problem while trying to start v1 project, i tried with blank sidemenu and tabs templates and it always creates v2 structure.
im not sure if i need to create a new issue, let me know if thats the case.
My ionic --version is 3.0.0
Thanks.

**Comment by renanss** [comment]
For Ionic 1 projects, use ionic start project_name blank --type ionic1

**Comment by VitorHFLopes** [comment]
Thank @renanss it works :)

**Comment by ajielee** [comment]
Thanks @renanss, that's the best answer I got over all the others on Google.

**Comment by danielsogl** [comment]
@ajielee Reading the docs would save you from searching with Google :)

**Comment by renanss** [comment]
Hello friends, it actually changed and it seems that they don't updated the documentation.
It's now:  **ionic start project_name template_name --v1**
Where template_name can be **: blank, tabs or sidemenu**

**Comment by dwieeb** [comment]
@renanss That's incorrect. With the latest V3 CLI, the command is `ionic start project_name template_name --type=ionic`. Please see `ionic start --help`, there are plenty of examples. To which documentation are you referring? Can you send a link?

**Comment by hreimer** [comment]
Hi, I tried your suggestion (`ionic start project_name blank --type ionic1`) but still got the same Invalid command (CLI v2.2.0) error - my ionic info:

```
Cordova CLI: 6.5.0 
Ionic CLI Version: 2.2.0
Ionic App Lib Version: 2.2.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v6.9.5
Xcode version: Xcode 8.2.1 Build version 8C1002
```

I just need to create a sample v1 project to compare/find out, what the problem in another old v1 project could be. Does anyone have a suggestion?

**Comment by dwieeb** [comment]
You have an old CLI version. Upgrade to the latest: `npm i -g ionic@latest`

**Comment by lionelquellery** [comment]
I just update this closed conversation for anyone that searching how to create an Ionic v1 project.

Just copy/past this command in your terminal -> **ionic start myApp blank --type=ionic1**

**Comment by sdns** [comment]
`ionic start myApp blank --type=ionic1` not working for me!
use below codes:
`ionic start myApp blank --v1`

**Comment by dwieeb** [comment]
@sdns You must have a very old CLI version. 

## If you find this issue and want to create a v1 app:

1. Update to the latest Ionic CLI: `npm i -g ionic@latest`
1. Start your app: `ionic start myApp blank --type=ionic1`
