### ISSUE TITLE
Support Windows for Local CLI Development

### ISSUE THREAD

**Issue by ricardo-mello** [driftyco/ionic-cli#2225]
#### Short description of the problem:
I forked the project following CONTRIBUTING.md instructions, but the `npm run bootstrap` command fails on Windows giving me the following error:

`Error: '..' is not recognized as an internal or external command`

#### What behavior are you expecting?
Expecting package dependencies to be installed and linked

**Steps to reproduce:**
1. On Windows, fork the v3 repo & clone it locally
2. run `npm install`
3. run `npm run bootstrap`

**Comment by dwieeb** [comment]
@ricardo-mello Sorry, that stuff is hot off the press. You're likely the first person to try using it. I also haven't tested local setup in Windows yet.

I suspect it's this issue: https://github.com/npm/npm/issues/13789 and how we're using `../../node_modules ...` in our packages' npm scripts: https://github.com/driftyco/ionic-cli/blob/v3/packages/cli-utils/package.json#L10-L21

We definitely want to support Windows for our local setup. Looks like people in that thread are suggesting node-based build systems. Yarn looks attractive.

**Comment by dwieeb** [comment]
@ricardo-mello In the meantime, you could dissect what the npm scripts are doing.

Install Typescript 2.3 and lerna globally: `npm i -g typescript@latest lerna@beta`

* Try running `lerna bootstrap` in the repo's root directory.
* Run `tsc -w` in each packages' root directories. (You may also need to run the JS portion of the build for printing proper plugin names and versions. If this is an issue, I can give further directions)

Use the bin file: `packages/ionic/bin/ionic` for running the locally built CLI.

**Comment by ricardo-mello** [comment]
@dwieeb Yeah! That's the point. npm runs scripts on cmd, which doesn't work very well with forward slashes, then `../../node_modules` commands doesn't work. 

I could set up my environment by addind "bash" before each entry that runs `../../node_modules ...` to force it run on mingw or ubuntu subsystem. With this trick I was able to run the entire bootstrap script and use the CLI, but it's not right because the scripts stopped to work on my Linux machine haha.

I'm reading about node-based build systems but will take a look at yarn too. I'll try implement it on the project and see the result.

Installed typescript and lerna globally as you said, but it breaks at the same point for each package. Pasting only the first below:


```NpmUtilities.execInDir        ("run prepublish", [], "C:\\Users\\Ricardo\\Projects\\Github\\ionic-cli\\packages\\cli-utils")
Error: Command failed: npm run prepublish
'..' is not recognized as an internal 
or external command, operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/cli-utils@1.0.0-rc.2 build-ts: `../../node_modules/.bin/tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ionic/cli-utils@1.0.0-rc.2 build-ts script '../../node_modules/.bin/tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @ionic/cli-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ../../node_modules/.bin/tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @ionic/cli-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @ionic/cli-utils
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ricardo\AppData\Roaming\npm-cache\_logs\2017-05-06T19_06_13_853Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/cli-utils@1.0.0-rc.2 build: `npm run clean && npm run build-ts && npm run build-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ionic/cli-utils@1.0.0-rc.2 build script 'npm run clean && npm run build-ts && npm run build-js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @ionic/cli-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build-ts && npm run build-js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @ionic/cli-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @ionic/cli-utils
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ricardo\AppData\Roaming\npm-cache\_logs\2017-05-06T19_06_13_874Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/cli-utils@1.0.0-rc.2 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ionic/cli-utils@1.0.0-rc.2 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @ionic/cli-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @ionic/cli-utils
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @ionic/cli-utils
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ricardo\AppData\Roaming\npm-cache\_logs\2017-05-06T19_06_13_906Z-debug.log

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) 

...
```

**Comment by dwieeb** [comment]
Ahh, `lerna bootstrap` runs a build--I forgot. 

So you'll need to do some `npm link` trickery to manually link all the packages together. 

* `cd packages/cli-utils` and build it with `tsc` and then `npm link` it globally
* Enter each packages' root directory and link them globally as well (`npm link`) and **also** link the cli-utils package in each packages' node_modules folder with `npm link @ionic/cli-utils`. Then build each one with `tsc`

**Comment by ricardo-mello** [comment]
Hahaha, that's ok.

I followed your instructions to `npm link` and added a alias to call the CLI globally. With it, was able to generate and run an application from the forked build. 

Now I'm trying to find a way to run `lerna bootstrap` without mingw.

**Comment by dwieeb** [comment]
Sorry, a bit of miscommunication there. All `lerna bootstrap` really does is install the packages' dependencies and link them together. You should be all set :+1:

**Comment by ricardo-mello** [comment]
Yeah! I really am.

In the meantime, I've read in lerna's docs that dependencies providing binary executables still need to be installed directly in each package they're used. [(reference)](https://github.com/lerna/lerna#common-devdependencies)

I changed the package.json files at each package to follow their instructions. I created the PR #2227 so you can check.

**Comment by dwieeb** [comment]
@ricardo-mello Can you do a fresh clone/install, follow the [CONTRIBUTING.md](https://github.com/driftyco/ionic-cli/blob/master/CONTRIBUTING.md) docs for local setup and let me know what issues you have?

**Comment by ricardo-mello** [comment]
@dwieeb To be more accurate when testing, I removed all my nodejs/npm environment and reinstalled the latest version of node on my environment. Everything works as expected without any errors.

The only problem now is that Windows unfortunately doesn't support `.bashrc` to create an alias :cry: and doskey doesn't keep the aliases when the user closes the `cmd` window. But I see it as a minor problem.

**Comment by ricardo-mello** [comment]
@dwieeb I was able to create an "alias" to the `ionic-local` command by creating a `ionic-local.cmd` file at 
`C:\Users\<myuser>\AppData\Roaming\npm`. 

The file has the following content:
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "C:\path\to\ionic-cli\packages\ionic\bin\ionic" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "C:\path\to\ionic-cli\packages\ionic\bin\ionic" %*
)
```

It works if the file is inside any folder that's on `PATH` variable.

**Comment by dwieeb** [comment]
@ricardo-mello An alternative to the alias in Windows would just be to run `npm link` with in `packages/ionic`. Then npm will link the `ionic` binary to your local version.

**Comment by ricardo-mello** [comment]
OMG I really forgot the `npm link` option @dwieeb , but my intention is to run the latest production release side by side with the dev version, because it is tedious to keep changing the environment often. As a Linux user, I wouldn't forgive myself if I could not create an alias.

About `npm link`, I tried to test it, but it's giving me this error:

```
C:\Users\Ricardo\Projects\Github\ionic-cli\packages\ionic>npm link
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> ionic@3.0.0 prepublish C:\Users\Ricardo\Projects\Github\ionic-cli\packages\ionic
> in-publish && npm run build || not-in-publish

'in-publish' is not recognized as an internal 
or external command, operable program or batch file.
'not-in-publish' is not recognized as an internal 
or external command, operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic@3.0.0 prepublish: `in-publish && npm run build || not-in-publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic@3.0.0 prepublish script 'in-publish && npm run build || not-in-publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     in-publish && npm run build || not-in-publish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ricardo\AppData\Roaming\npm-cache\_logs\2017-05-12T01_04_45_648Z-debug.log
```

**Comment by dwieeb** [comment]
ugh. this is the npm prepublish issue.

workaround: `npm i -g in-publish`

**Comment by ricardo-mello** [comment]
Thanks! It works!

**Comment by dwieeb** [comment]
Sure, if you like 😄 

I am hoping npm 5 is out soon. Then we can require it for local development because it fixes the issue and we won't need that `in-publish` module

**Comment by ricardo-mello** [comment]
Hahaha, just created the PR #2278 with it 😁

I think that npm 5 will not take too much time to be launched. Don't need `in-publish` will be cool. One step less.
