### ISSUE TITLE
Ionic info reports error after upgrading from beta to 3.0 release

### ISSUE THREAD

**Issue by jamesgroat** [driftyco/ionic-cli#2236]
#### Short description of the problem:

Ionic info reports error.

```
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[ERROR] No updates found after plugin error--please report this issue.

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v7.8.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Steps to reproduce:**
1. Seems related to old versions of the listed plugins.

```
"@ionic/app-scripts": "1.1.4",
"@ionic/cli-build-ionic-angular": "0.0.4",
"@ionic/cli-plugin-cordova": "0.0.10",
```

Was able to fix locally by upgrading to versions that v3 cli starts a new project with.

**Comment by dwieeb** [comment]
Yes, those plugins are very old. Please make sure you have `1.0.0` of all the plugins installed locally.

**Comment by jamesgroat** [comment]
@dwieeb yes fixed locally as noted. Created an issue because of this: "No updates found after plugin error--**please report this issue.**"

**Comment by dwieeb** [comment]
@jamesgroat Yep, sorry. The blame is on me. The message is intended for new installs--it may be an inaccurate for beta testers with old plugins. 

If you're curious, the error is caused by an exception from a plugin because the API changed frequently during beta. Going forward, the API changes shouldn't be breaking, but if it is, that's the message users will get and hopefully we'll be able to resolve issues quickly.

**Comment by dwieeb** [comment]
Again, thanks for the issue! 👍

**Comment by yuricamara** [comment]
I saw the same message except from my Node version that is older. v.6.9.1

This happened after that I reproduced the steps from this link: [
Announcing Ionic CLI v3](http://blog.ionic.io/announcing-ionic-cli-v3/)

From my package.json

>     "@ionic/app-scripts": "1.3.6",
>     "@ionic/cli-plugin-cordova": "1.0.0",
>     "@ionic/cli-plugin-ionic-angular": "1.0.0"
