### ISSUE TITLE
FILE_INVALID_JSON

### ISSUE THREAD

**Issue by karlpatrickespiritu** [driftyco/ionic-cli#2238]
#### Short description of the problem:
When running `ionic` on my ionic root project directory, this gives me `FILE_INVALID_JSON` and it stuck.

**Steps to reproduce:**
1. run `ionic` command

**Post the output of `ionic info` below please**
Can't. Gives me `FILE_INVALID_JSON`.

**Comment by karlpatrickespiritu** [comment]
reverted back to `ionic@2.1.15` and it fixed my issue. my project still uses the 3.x versions.

**Comment by dwieeb** [comment]
@karlpatrickespiritu This leads me to believe you're using an old version. What version did you install?

**Comment by karlpatrickespiritu** [comment]
Sorry, I meant 2.x versions. Lol. Anyways, Thanks.
