### ISSUE TITLE
Adding crosswalk fail

### ISSUE THREAD

**Issue by r1l4r** [driftyco/ionic-cli#224]
Seems to be a bug with the new CLI version. Me and my colleagues can´t add crosswalk anymore. 

"ionic browser add crosswalk" will result in:

There was an error adding the Cordova Android library
Running command: /PATH/app/hooks/before_platform_add/init_directories.js /PATH/app
Creating android project...
Error: /PATH/app/engine/cordova-android-c0.5.5/bin/create: Command failed with exit code EACCES
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:808:12)
 (CLI v1.3.8)

My system information:

OS: Mac OS X Yosemite
Node Version: v0.10.31
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.8
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1

**Comment by whiff** [comment]
+1

**Comment by bicpi** [comment]
This was a workaround for me:

    $ chmod -R 777 engine/

**Comment by jbavari** [comment]
During the `ionic browser add crosswalk` process, it should be making those files executable already.

[See this line of code](https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/browser.js#L251)

What's weird is, it doesnt seem to be setting the permissions correctly for some reason.

As @bicpi pointed out, the instant cure is to correct the permissions - `chmod +x engine/cordova-android-c0.5.5/bin/`

NOTE: You might have a different version of cordova-android - the `c0.5.5` part. 

Also, you may want to try `rm -rf engine` and then running `ionic browser add crosswalk`.

Let me know if that helps.

**Comment by jbavari** [comment]
Ok - this should be fixed and rolled out soon! 

This commit on next-release should help set permissions correctly.

https://github.com/driftyco/ionic-cli/commit/9e3af93ca2aa254902579d757f8d0a8c14b0df42

**Comment by jbavari** [comment]
1.3.9 is out. Please try the update and let me know if that fixes the issue. Thanks!

**Comment by bicpi** [comment]
@jbavari I've done a fresh Crosswalk installation using 1.3.9 and there were no more permission issues, thank you!

But there are (as before) tons of warnings when building an app:

```
~  ᐅ ionic run --target=192.168.40.44:5555 android       
...
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavawarning: android/annotation/TargetApi.class(android/annotation:TargetApi.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: android/app/Activity.class(android/app:Activity.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: android/app/AlertDialog.class(android/app:AlertDialog.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
...
...
:org.crosswalk.engine:myapp767062-xwalk_core_library:processDebugManifest
:org.crosswalk.engine:myapp767062-xwalk_core_library:processDebugResources
:org.crosswalk.engine:myapp767062-xwalk_core_library:generateDebugSources
:org.crosswalk.engine:myapp767062-xwalk_core_library:compileDebugJavawarning: java/lang/Object.class(java/lang:Object.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: java/lang/String.class(java/lang:String.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: java/lang/Boolean.class(java/lang:Boolean.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
...
...
:processArmv7DebugManifest
:processArmv7DebugResources
:generateArmv7DebugSources
:compileArmv7DebugJavawarning: org/json/JSONArray.class(org/json:JSONArray.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: org/json/JSONException.class(org/json:JSONException.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
warning: android/content/Context.class(android/content:Context.class): major version 51 is newer than 50, the highest major version supported by this compiler.
It is recommended that the compiler be upgraded.
...
...
```

**Comment by jbavari** [comment]
@bicpi - try updating your Android Build Tools.

**Comment by bicpi** [comment]
@jbavari Everything seems to be up-to-date.

![image](https://cloud.githubusercontent.com/assets/301163/6132238/803fff98-b151-11e4-9e30-24708b53defa.png)

**Comment by jbavari** [comment]
From my little research, are you running Java 7? Try `javac --version`

I currently have: 

```
$ javac -version
javac 1.8.0_25
```

From this [SO Post](http://stackoverflow.com/questions/24807117/android-studio-what-compiler-settings-when-including-google-maps)

"Major version" means Java version. Java 7 = 51, Java 6 = 50. The code is written for Java 7, and that is something that Android's dex supports. I am not sure what you are building with that is not set for Java 7, but that's the problem. The Maven build in the project works correctly. I don't see the error you mention, and it may be related to Java 6 vs 7 too.

**Comment by bicpi** [comment]
@jbavari You were absolutely right, it was Java 6 on my machine. I think it came with PHPStorm back then. I've updated to Java 8, the warnings are gone when reinstalling everything.

I got two notes on the first build if this is interesting for you:

````
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
...
:mergeArmv7DebugResources
:processArmv7DebugManifest
:processArmv7DebugResources
:generateArmv7DebugSources
:compileArmv7DebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
...
```

**Comment by jbavari** [comment]
I've seen that some myself. I'm not sure what is triggering it, to be honest.

Thanks for confirming the upgrade to Java fixed it.

**Comment by armikhael** [comment]
Hello , I have this version of javac javac 1.6.0_34 and gives me the same problem as you might upgrade to a higher version

**Comment by yves-s** [comment]
Thanks @jbavari, updating the java version worked for me.

**Comment by fakhrizaki** [comment]
Thanks! That was a real help!
