### ISSUE TITLE
Don't like the new style: can I go back to the old CLI?

### ISSUE THREAD

**Issue by 1BJK903** [driftyco/ionic-cli#2244]
Hi all,

I just updated the CLI with this:

`sudo npm install --save-dev --save-exact @ionic/cli-plugin-ionic1@latest @ionic/cli-plugin-cordova@latest`

Yet, this has changed my whole Ionic serve --lab experience. I can see the lay-out of it changed and I can choose Android, Windows and iOS, yet I don't like it at all... and I want to go back to the previous state.

How can I do that, please? I was using: Ionic CLI Version: 2.2.1

**Comment by jthoms1** [comment]
You would need to go back to the older version of the CLI to get the old design.
