### ISSUE TITLE
Ionic info reports error after upgrading to 3.0 release

### ISSUE THREAD

**Issue by yuricamara** [driftyco/ionic-cli#2246]
From ionic info:
> [ERROR] Error occurred while loading plugins. CLI functionality may be limited.
> [ERROR] No updates found after plugin error--please report this issue.
> 
> global packages:
> 
>     @ionic/cli-utils : 1.0.0
>     Ionic CLI        : 3.0.0
> 
> System:
> 
>     Node       : v6.9.1
>     OS         : Windows 10
>     Xcode      : not installed
>     ios-deploy : not installed
>     ios-sim    : not installed

This happened after that I reproduced the steps to upgrade from this link: [
Announcing Ionic CLI v3](http://blog.ionic.io/announcing-ionic-cli-v3/)

From package.json

>     "@ionic/app-scripts": "1.3.6",
>     "@ionic/cli-plugin-cordova": "1.0.0",
>     "@ionic/cli-plugin-ionic-angular": "1.0.0",
>     "ionic-angular": "3.1.1"

I saw this warn too after install the cli-plugins:
> npm WARN @ionic/cli-utils@1.0.0 requires a peer of strip-ansi@^3.0.1 but none was installed.

This was my first install of Ionic cli v3.

**Steps to reproduce:**
From this link to Ionic Angular : [Announcing Ionic CLI v3](http://blog.ionic.io/announcing-ionic-cli-v3/)

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Suggestion:
In package.json of cli-utils, change from:
```
  "peerDependencies": {
    "strip-ansi": "^3.0.1"
  }
```

to:
```
  "peerDependencies": {
    "strip-ansi": "^3.0.0"
  }
```

**Comment by dwieeb** [comment]
@yuricamara Please also update your plugins.

For Ionic Angular:

```bash
npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
```

For Ionic 1:

```bash
npm install --save-dev --save-exact @ionic/cli-plugin-ionic1@latest
npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
```

**Comment by yuricamara** [comment]
@dwieeb , I had already the last versions of these plugins.

" For Ionic Angular projects, make sure 'ionic-angular' exists in the dependencies attribute of package.json."
The problem was that. I had moved ionic-angular to devDependencies. When I put it back to dependecies the issue was solved.

Why do you impose that? I think we could decide between  place it in 'devDependencies' or 'dependencies'. I don't put any front-end dependency as 'dependecies'. 

I use AWS Beanstalk with a command that install automatically only the packages in 'dependecies'. So, only back-end packages are placed there. It will be lost of time to install ionic-angular in my server.

Could you consider to change that?

**Comment by dwieeb** [comment]
@yuricamara Unless I'm misunderstanding, you're combining your front-end and back-end into a single package. That's not what `dependencies` and `devDependencies` were meant to differentiate. 

That error goes on to explain an alternative option you can do to bypass it.

**Comment by yuricamara** [comment]
Yes! In package.json. 

Unless I'm misunderstanding, it is possible to have a "package.json" to front-end and another "package.json" to a Node back-end. I did't even know that. I will search information about it. It would be great to separate them.
