### ISSUE TITLE
Error: app-scripts serve unexpectedly failed

### ISSUE THREAD

**Issue by Aaron-Sterling** [driftyco/ionic-cli#2247]
Cross-posting an issue I put on app-scripts yesterday in case you guys are a different team.
[ionic-app-scripts issue #975](https://github.com/driftyco/ionic-app-scripts/issues/975)

Problem arose on both existing and new projects. I'm using nvm-for-windows, in case that has any effect.  package,json, tsconfig.json and ionic info are at the crosspost.  Ionic serve would bring up the homepage of the app, then crash, with this error:
[DEBUG] !!! ERROR ENCOUNTERED !!!
Error: app-scripts serve unexpectedly failed.
[DEBUG] Error: app-scripts serve unexpectedly failed.
at Object. (C:\Users\Aaron\IonicDevelop\ActionSearch\node_modules@ionic\cli-plugin-ionic-angular\dist\serve.js:50:19)
at Generator.next ()
at fulfilled (C:\Users\Aaron\IonicDevelop\ActionSearch\node_modules@ionic\cli-plugin-ionic-angular\dist\serve.js:4:58)

Thanks very much.

**Comment by tnovau** [comment]
I had the same issue, please i need a solution.

> ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Error: app-scripts serve unexpectedly failed.**

[DEBUG] !!! ERROR ENCOUNTERED !!!
Error: app-scripts serve unexpectedly failed.
[DEBUG] Error: app-scripts serve unexpectedly failed.
            at Object.<anonymous> (C:\Users\tnovau\client\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:50:19)
            at Generator.next (<anonymous>)
            at fulfilled (C:\Users\tnovau\client\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:4:58)

**Comment by dwieeb** [comment]
@Aaron-Sterling @tnovau Does this happen with app-scripts 1.3.6?

**Comment by tnovau** [comment]
1.3.7 is the version i have.

**Comment by dwieeb** [comment]
Can you try with 1.3.6?

`npm install --save-dev @ionic/app-scripts@1.3.6`

**Comment by tnovau** [comment]
I run npm instal --save-dev @ionic/app-scripts@1.3.6,and then when i run ionic serve, I get this message after [15:29:50]  dev server running: http://localhost:8100/: 

**[DEBUG] !!! ERROR ENCOUNTERED !!!**
Error: app-scripts serve unexpectedly failed.
**[DEBUG] Error: app-scripts serve unexpectedly failed.**
            at Object.<anonymous> (C:\Users\tnovau\Documents\proyectos\ionic3project\ADX\client\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:50:19)
            at Generator.next (<anonymous>)
            at fulfilled (C:\Users\tnovau\Documents\proyectos\ionic3project\ADX\client\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:4:58)

**Comment by Aaron-Sterling** [comment]
@dwieeb I created a new project (blank) and started adding libraries until I encountered the error.  I hit the error at the same point with both 1.3.6 and 1.3.7.  Libraries in order of addition were:

npm install @angular/animations
npm install @ngrx/core @ngrx/store --save
ionic cordova plugin add cordova-plugin-inappbrowser@latest
npm install --save @ionic-native/in-app-browser
ionic cordova plugin add call-number
npm install --save @ionic-native/call-number
npm install angularfire2 firebase --save
npm install immutable --save

After installing immutable, I got the error.  Up until that point, I had run ionic serve after every install, and it was fine, in both 1.3.6 and 1.3.7.

**Comment by quentinchap** [comment]
I made the same action than @Aaron-Sterling and on my side i had an error after this installation of angular/animation

**Comment by aditya1027** [comment]
I had this issue when i executed command: ionic cordova run android --livereload -c -s. If you are doing the same, just try to run ionic cordova run platform.

I hope this will solve your issue,

**Comment by hsxfjames** [comment]
I also have this issue, but I found an error at very early:
```bash
[10:15:28]  preprocess started ... MEM: 292.3MB 
[ DEBUG! ]  error loading core compiler: /home/hsxfjames/文档/repo/ionic/ionicTest/node_modules/ionic-angular/compiler, 
            Error: Cannot find module '/home/hsxfjames/文档/repo/ionic/ionicTest/node_modules/ionic-angular/compiler'  
            MEM: 292.3MB 
[ DEBUG! ]  skipping core component bundling  MEM: 292.3MB 
```
And I reinstall the ionic-angular module, checked again that there is no any file or folder named compiler.

**Comment by JulioCesarCeron** [comment]
I had the same error message 

> Error: app-scripts serve unexpectedly failed.

 when i executed `ionic serve`

so i try to run `npm install -g ionic cordova`, and the problem is solved,

**Comment by dwieeb** [comment]
@Aaron-Sterling @tnovau @JulioCesarCeron I still haven't been able to reproduce this, but I am launching the next version of the CLI with the debugging information you can see in the commit above ^

Hopefully this will shed some light on this issue.

**Comment by NicolasBehra** [comment]
I have no longer this error in sudo:

> sudo ionic serve

**Comment by realfreebird** [comment]
Here is a way to reproduce the bug: 
https://github.com/realfreebird/reproduce-ionic-cli-bug-2247

steps to reproduce:
1. add to package.json
```
"config": {
    "ionic_copy": "./config/copy.config.js"
  },
```
2. copy  node_modules\@ionic\app-scripts\config\copy.config.js to .\config\
3. edit .\config\copy.config.js, add the following lines

```
module.exports = {
...
reproduce_ionic_cli_bug_2247: {
    src: ['{{ROOT}}/node_modules/non_exiting_file.txt'],
    dest: '{{BUILD}}'
  }
...
}
```

**Comment by dwieeb** [comment]
@realfreebird Thanks for being a champ and making that repo 👍 Unfortunately I'm still unable to reproduce. Are you on Windows as well? Does an error occur if you try `npm run ionic:serve` in that repo?

**Comment by realfreebird** [comment]
@dwieeb I get this error with `ionic serve`.
`npm run ionic:serve` works fine.

Here is my configuration:

> ionic info

global packages:

```
    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0
```

local packages:

```
    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1
```

System:

```
    Node       : v6.10.1
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Comment by dwieeb** [comment]
@realfreebird Okay. Would you mind trying this with the alpha CLI? `npm i -g ionic@canary`

**Comment by paulonbastos** [comment]
Worked around this problem by adding an empty file to src/service-worker.js.

it seems that _(the below code is started from line 53 of @ionic\app-scripts\dist\serve.js)_ in the function serve is not return the object config when a non fatal error occurs, such as not find a file in the watch list.

`
       .then(function () {

        bonjour_1.createBonjourService(config);

        onReady(config, context);          // <---- Note1 : Returning the config object

        return config;

    }, function (err) {

        throw err;

    })

        .catch(function (err) {

        if (err && err.isFatal) {

            throw err;

        }

        else {

            onReady(config, context);

           // Note 2 <---- Not returning the config as in note 1

        }
    });
`

I hacked the server.js to write to the console (sorry still learning the in and outs of this platform, possible a better way to do this.)
`
P:\nau21\ws1\git\fp-app>ionic serve

Starting app-scripts server: --port 8100 --livereload-port 35729 --address 0.0.0.0 - Ctrl+C to cancel

[19:26:30]  watch started ...

.....

[19:26:48]  lint finished in 605 ms
errError: A watch configured to watch the following paths failed to start. It likely that a file referenced does not exist: P:\nau21\ws1\git\fp-app\src\assets\**\*, P:\nau21\ws1\git\fp-app\src\index.ht
ml, P:\nau21\ws1\git\fp-app\src\manifest.json, P:\nau21\ws1\git\fp-app\src\service-worker.js, P:\nau21\ws1\git\fp-app\node_modules\ionicons\dist\fonts\**\*, P:\nau21\ws1\git\fp-app\node_modules\ionic-angular\fonts\**\*, P:\nau21\ws1\git\fp-app\node_modules\ionic-angular\polyfills\polyfills.js,P:\nau21\ws1\git\fp-app\node_modules\sw-toolbox\sw-toolbox.js

[19:26:51]  dev server running: http://localhost:8100/
`

For my ionic info
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

Hope this helps.

**Comment by dwieeb** [comment]
@paulonbastos I think I see the error in the app-scripts code. We'll see if it's still an error when the next version of app-scripts is released. Thanks for diving deep, very helpful.

**Comment by thornch** [comment]
Possible solution: **npm install --save sw-toolbox**

The plugin @ionic/cli-plugin-ionic-angular@1.0.0-rc.2 requires @ionic/app-scripts
Console-Message: npm WARN @ionic/app-scripts@1.3.7 requires a peer of sw-toolbox@* but none was i
nstalled.

I've got the same problem for "**ionic serve**" - after installing the missing package it works as excepted.

**Comment by giovannipds** [comment]
@thornch `sw-toolbox` didn't solve to me.

@dwieeb neither did `ionic@canary`.

`npm run ionic:serve` runs ok.

`ionic info`:

    global packages:

        @ionic/cli-utils : 1.4.0
        Ionic CLI        : 3.4.0

    local packages:

        @ionic/app-scripts              : 1.0.0
        @ionic/cli-plugin-ionic-angular : 1.3.1
        Ionic Framework                 : ionic-angular 2.0.0

    System:

        Node       : v6.11.0
        OS         : Windows 10
        Xcode      : not installed
        ios-deploy : not installed
        ios-sim    : not installed
        npm        : 3.10.10

Tried `npm update` and didn't solve as well.

After seeing some `UNMET PEER DEPENDENCY @ionic/app-scripts@1.3.6 invalid` 'cause of `sw-toolbox`, tried installing `@ionic/app-scripts@1.3.6` and running `ionic serve` later worked.

--> `npm i @ionic/app-scripts@^.1.3.7 --save-dev` solves. <--
