### ISSUE TITLE
Crosswalk build works, but no debugging available

### ISSUE THREAD

**Issue by bicpi** [driftyco/ionic-cli#225]
Hi,
after fiddling with some errors I was able to install Crosswalk with Ionic.

But the resulting APK (ARM or x86) is only 8MB (I think it should be 2-4 times bigger) and there's no debugging available in ChromeDevTools. The device (Samsung Galaxy S3, Android 4.3) shows up, but not the web view to inspect (app is running). Out of the box Chrome debugging works fine with Android 4.4.4 on my Moto G 2nd Gen. and with an S4 on Genymotion, and I would love to see this working with 4.3 using Crosswalk.

Any idea how what could be wrong?

    ~/ ᐅ ionic info

    Your system information:

    OS: Mac OS X Yosemite
    Node Version: v0.10.32
    Cordova CLI: 4.0.0
    Ionic CLI Version: 1.3.8
    Xcode version: Xcode 6.1.1 Build version 6A2008a 
    ios-sim version: 2.0.1 

During some build I was spammed by warning like:

    ...
    warning: javax/net/ssl/SSLContext.class(javax/net/ssl:SSLContext.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    It is recommended that the compiler be upgraded.
    warning: javax/net/ssl/SSLSession.class(javax/net/ssl:SSLSession.class): major version 51 is newer than 50, the highest major version supported by this compiler.
    It is recommended that the compiler be upgraded.
    warning: javax/net/ssl/SSLSocketFactory.class(javax/net/ssl:SSLSocketFactory.class): major version     51 is newer than 50, the highest major version supported by this compiler.
    It is recommended that the compiler be upgraded.
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    100 warnings

Thank you.

**Comment by jbavari** [comment]
@bicpi - due to the latest changes in cordova android, this may require you to update your cordova tools to 4.2.0.

Try running `npm install -g cordova`

**Comment by bicpi** [comment]
@jbavari thanks for the tip, I've just update everything, now I have:

    ~  ᐅ ionic info

    Your system information:

    OS: Mac OS X Yosemite
    Node Version: v0.10.36
    Cordova CLI: 4.2.0
    Ionic CLI Version: 1.3.8
    Xcode version: Xcode 6.1.1 Build version 6A2008a 
    ios-sim version: Not installed

But unfortunately still no luck with the ChromeDevTool, it looks like the screenshot below, the devices are running the very same app built with crosswalk (still 8MB in size):

![image](https://cloud.githubusercontent.com/assets/301163/6083580/fc08de36-ae29-11e4-937e-43584576bbc6.png)

No debugging available for Android < 4.4.

**Comment by jbavari** [comment]
Correct. Once CW is installed, you should be able to use chrome debugging. It seems like something went bonkers. I'm here to help!

Further info - what does the following give:

`cordova platform ls`
`cordova plugin ls`

**Comment by bicpi** [comment]
I really appreciate your help, thank you :-)

I've just reinstalled the Crosswalk browser and now ... it works! Great.

But the follow-up issue now is that the `org.apache.cordova.file-transfer` causes a crash of the app (worked before without issues).

My plugins:

````
~ ᐅ ionic plugin ls
com.ionic.keyboard 1.0.3 "Keyboard"
org.apache.cordova.camera 0.3.4 "Camera"
org.apache.cordova.console 0.2.12 "Console"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.file 1.3.2 "File"
org.apache.cordova.file-transfer 0.4.8 "File Transfer"
org.crosswalk.engine 0.0.1-dev "Crosswalk Engine"
````

I can give some output of `adb logcat` if it helps?

**Comment by jbavari** [comment]
@bicpi - right now they are working on porting over that plugin. Please note, that we are using an unreleased version of Cordova to do this. 

Just to keep you up to speed with the cordova team, here's their discussion:

```
The file transfer plugin uses the Android webview cookie manager. When
you're using a Crosswalk webview (or GeckoView presumably), in the
best case there are no cookies with file transfer requests and in the
worst case it will cause the app to crash on Android 4.2.x.
```

Follow along the thread [here](http://markmail.org/search/?q=cordova+file+transfer+plugin+crosswalk#query:cordova%20file%20transfer%20plugin%20crosswalk+page:1+mid:4cgelkj7ytyz4y5q+state:results)

**Comment by bicpi** [comment]
@jbavari thank you very much for clarifying the current status. Too bad, I'll need to wait for the update because that's the nucleus of my app. But Crosswalk is just too tempting.

**Comment by jbavari** [comment]
@bicpi - how are your java skills? We could hop in and figure it out, the beauty of open source.

**Comment by bicpi** [comment]
Unfortunately I'm coming from PHP. I know Java but I've no practice at all – that's why I use Ionic ;-)

**Comment by jbavari** [comment]
@bicpi - when is your targeted release date? I can help you push out the latest cordova android and file plugins as they come in.

**Comment by bicpi** [comment]
@jbavari Actually there's no hurry as there's no release date yet. But my testing devices are an S3 (only 4.3 support) and a Moto G 2nd Gen (with 4.4, so debugging included, but taking pictures is awful because it crashes almost every time when trying to render the taken picture – not enough RAM). So I would really love to use such a solution Crosswalk provides to get it running on my S3 and to know it look the same on every 4.x device.

Do you have any idea when a official fix will be available? And what needs to be done to fix it before?

**Comment by jbavari** [comment]
@bicpi - it's coming. The team is working on it.

I do not know when the cordova team will fix it. [This jira issue](https://issues.apache.org/jira/browse/CB-8431) covers what needs to be done to fix it.

**Comment by jbavari** [comment]
The plugin should have been updated. Closing for now.
