### ISSUE TITLE
Error: app-scripts serve unexpectedly failed.

### ISSUE THREAD

**Issue by tnovau** [driftyco/ionic-cli#2251]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:
I get an error when i run ionic serve.

#### What behavior are you expecting?
Use **ionic serve** command

**Steps to reproduce:**
1. 
2.
3.

I had the same issue, please i need a solution.

> ionic info

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v7.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Error: app-scripts serve unexpectedly failed.**

On an ionic 2 project:
1. npm uninstall -g ionic 
2. npm install -g ionic@latest
3. npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest
npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest
4. try to run ionic serve

**Post the output of `ionic info` below please**
> ionic info                                                 
                                                             
global packages:                                             
                                                             
    @ionic/cli-utils : 1.0.0                                 
    Cordova CLI      : 7.0.0                                 
    Ionic CLI        : 3.0.0                                 
                                                             
local packages:                                              
                                                             
    @ionic/app-scripts              : 1.3.7                  
    @ionic/cli-plugin-cordova       : 1.0.0                  
    @ionic/cli-plugin-ionic-angular : 1.0.0                  
    Ionic Framework                 : ionic-angular 3.2.0    
                                                             
System:                                                      
                                                             
    Node       : v7.10.0                                     
    OS         : Windows 10                                  
    Xcode      : not installed                               
    ios-deploy : not installed                               
    ios-sim    : not installed                               

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

[DEBUG] !!! ERROR ENCOUNTERED !!!
Error: app-scripts serve unexpectedly failed.
[DEBUG] Error: app-scripts serve unexpectedly failed.
            at Object.<anonymous> (C:\Users\tnovau\client\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:50:19)
            at Generator.next (<anonymous>)
            at fulfilled (C:\Users\tnovau\client\node_modules\@ionic\cli-plugin-ionic-angular\dist\serve.js:4:58)

**Comment by dwieeb** [comment]
Thanks! Gonna track in this issue: https://github.com/driftyco/ionic-cli/issues/2247
