### ISSUE TITLE
Generators are only available for Ionic 2 projects (CLI v2.2.3)

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic-cli#2252]
#### Short description of the problem:
Unable to generate 

#### What behavior are you expecting?
Generating components and pages

**Steps to reproduce:**
1. use `ionic g page mypage`
Error apepars:

```
Generators are only available for Ionic 2 projects (CLI v2.2.3)

Your system information:

 ordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Post the output of `ionic info` below please**

 ordova CLI: 6.5.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed

**Comment by dwieeb** [comment]
Please update your CLI to v3: https://blog.ionic.io/announcing-ionic-cli-v3/
