### ISSUE TITLE
Ionic CLI V3 serving wrong app

### ISSUE THREAD

**Issue by yannbf** [driftyco/ionic-cli#2255]
#### Short description of the problem:
So I just updated to the latest version of the cli and for some weird reason, every single time I serve or update my app with livereload, it actually serves another app that I was developing earlier. So when running on MyApp, it servers MyOtherApp. It's really annoying, as every update I have to hard reload the browser. 

This must be related to cache or something. It's really weird.  

#### What behavior are you expecting?

**Steps to reproduce:**
I'm not sure how one could reproduce it, but what I did was I developed one app, then updated and served another app after the update.

Here's a video showing what I mean:
![weird-behavior](https://cloud.githubusercontent.com/assets/1671563/25926914/a1686fa4-35c8-11e7-8870-2d95c9a4f5ed.gif)

**Post the output of `ionic info` below please**
```    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.9.1
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed```

**Comment by jthoms1** [comment]
@yannbf Was the application that you were working on a PWA? I know that I have had issues in the past with working on PWAs on localhost.

**Comment by yannbf** [comment]
Hey @jthoms1 not necessarily. I was building .apk out of it, but I did run `npm run ionic:build --prod` to publish it as PWA.

**Comment by dertuerke** [comment]
@yannbf in Chrome in the Developer-Tools
- click on the tab "Application"
- on the left side "Clear Storage"
- click all and then "Clear selected"

**Comment by yannbf** [comment]
hey @dertuerke I've done that plenty of times, same result

**Comment by yannbf** [comment]
The problem was with the service worker I had enabled. Nothing to do with the cli, so I'm closing this issue.

**Comment by dwieeb** [comment]
@yannbf Thanks for following up!
