### ISSUE TITLE
Ionic Upload Fails on Progress Bar Tick

### ISSUE THREAD

**Issue by Inlustra** [driftyco/ionic-cli#2257]
#### Short description of the problem:

Running ionic upload under a process which does not have access to a TTY results in the following error:

```
[go@cd ionic-switch-energy]$ ionic upload --nobuild
✔ Requesting snapshot upload - done!
Uploading snapshot
⠹ Uploading snapshot
ionic: ../deps/uv/src/unix/core.c:888: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
Aborted
```

After digging through the code and trying to find the issue, we've narrowed it down to the ticking of the progress bar (The assumption is there is an issue with the `new term.WriteStream();`) as the process does not necessarily have a terminal to write to.

#### What behavior are you expecting?
```
✔ Uploading snapshot - done!
[OK] Uploaded snapshot {{UUID HERE}}!
```

**Steps to reproduce:**
1. Run ionic upload under go-cd

**ionic-cli/packages/cli-utils/src/lib/utils/task.ts**
```
progress(prog: number, total: number): this {
    if (this.running && process.platform !== 'win32') {
      if (!this.progressBar) {
        const term = <any>tty; // TODO: type def issue
        const ProgressBar = load('progress');
        const s = new term.WriteStream();
        s.columns = s.columns || 80;
        this.progressBar = new ProgressBar('[:bar] :percent', {
          total: total,
          width: 30,
          stream: s,
        });
      }

      const progbar = <any>this.progressBar; // TODO: type def issue
      progbar.curr = prog;

      if (prog < total) {
        this.progressBar.tick(0); // <-------------- Offending line which causes error
      }

      this.tick();
    }

    return this;
  }
```

**Post the output of `ionic info` below please**
```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.4
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.9.5
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Removing the line noted above results in a successful build.

**Comment by dwieeb** [comment]
That progress bar library has been nothing but troubles. I will look into options to fix this.

**Comment by dwieeb** [comment]
@Inlustra Thanks! I just replaced with a simple percentage.
