### ISSUE TITLE
ionic emulate ios broken

### ISSUE THREAD

**Issue by willyboy** [driftyco/ionic-cli#226]
Running ionic emulate ios builds the app but when it opens I see "ERROR: Start Page at 'www/index.html' was not found". Looking in platforms/ios/www I don't see any of my files which implies that they weren't copied into the platform folder (which I think in previous versions they were). They do still exist in the root www folder. Maybe you now reference this folder but if that's the case, this reference has somehow been broken in the most recent release.

**Comment by jbavari** [comment]
Check your config.xml file 
Do you have something like:

`<content src="index.html"/>`
