### ISSUE TITLE
CLI v3: Sass not working for Ionic 1 projects when using `ionic serve`

### ISSUE THREAD

**Issue by fiznool** [driftyco/ionic-cli#2264]
#### Short description of the problem:

When authoring an Ionic 1 project, changes to `ionic.app.scss` are not reflected in the app when running `ionic serve` with v3 of the CLI.

#### What behavior are you expecting?

Updates to `ionic.app.scss` should be reflected in the app.

**Steps to reproduce:**
1. Run `ionic start myapp blank --type ionic1`
2. `cd myapp`
3. Run `ionic serve`
4. In `scss/ionic.app.scss`, on line 17 add a colour variable `$stable: #ff9933`

I'm expecting the colour of the header bar in the app to change, but it doesn't.

This is also reproducible with classes, etc - basically anything that is changed in `ionic.app.scss` won't be reflected in the app.

**Post the output of `ionic info` below please**

```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/cli-plugin-cordova : 1.0.0
    @ionic/cli-plugin-ionic1  : 1.0.0
    Ionic Framework           : ionic1 1.3.3

System:

    Node       : v6.10.3
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

This is related to #1358 but all workarounds suggested in that issue do not work:

- Running `gulp watch` in a separate terminal - the SASS seems to be compiled but changes are not reflected in the app, even when restarting `ionic serve`
- Adding a `serve:before` gulp task doesn't work as gulp hooks no longer work with v3 of the CLI (#1989)

**Comment by fiznool** [comment]
Ok, so after further digging I realised that I needed to make some changes in the `index.html` file so that the CSS files generated by the SASS compiler are picked up. The changes that are needed are commented in the `index.html` file. I don't remember having to do this before, but I guess the now removed `ionic setup sass` command used to perform this change for you?

Once the changes to `index.html` are made, you can run `gulp sass` or `gulp watch` in another terminal and the SASS changes will propagate to the app.

**Comment by dwieeb** [comment]
@fiznool We'll likely be pushing people towards using sass for new apps, so this line will need to be commented out: https://github.com/driftyco/ionic-app-base/blob/master/www/index.html#L12

This is something I need to think about. It's on my radar, I'm going to condense it to the original issue, though: https://github.com/driftyco/ionic-cli/issues/1989

**Comment by fiznool** [comment]
Thanks for the quick reply and the consideration. Looking forward to the
resolution. ☺

**Comment by DevNIX** [comment]
I've been struggling with this issue too. 

With the Ionic 3 CLI, the events are prefixed.

```javascript
gulp.task('ionic:watch:before', ['default', 'watch']);
```

But this was not enough in my case. Make sure you have gulp installed in your propject's devDependencies.

```bash
npm install --save-dev gulp
```

**Comment by mrhieu** [comment]
@DevNIX that prefix thing saved my months! Thanks buddy a lllot

**Comment by jackvial** [comment]
Thanks @DevNIX! The gulp update was what I was missing
