### ISSUE TITLE
Adding / Upgrading Crosswalk fails

### ISSUE THREAD

**Issue by S0lll0s** [driftyco/ionic-cli#227]
First I tried updating crosswalk (was on ionic-cli=1.3.3 before), got this error:

    ✗ (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

    util.js:35
      var str = String(f).replace(formatRegExp, function(x) {
                          ^
    RangeError: Maximum call stack size exceeded

then ran `rm -rf engine` and `ionic browser add crosswalk`; now I get:

    Removed old Cordova Android platform
    There was an error adding the Cordova Android library
    Running command: /home/s0lll0s/dub-me/client/hooks/before_platform_add/init_directories.js /home/s0lll0s/dub-me/client
    The provided path does not seem to contain a Cordova platform: ./engine/cordova-android-.5.5/
    Cannot find module '/home/s0lll0s/dub-me/client/engine/cordova-android-c0.5.5/package'
     (CLI v1.3.8)

Luckily I didn't update my actual project and VM...

**Comment by S0lll0s** [comment]
`ionic browser add crosswalk` also often gets stuck on

    Adding crosswalk browser

    Downloading: https://github.com/driftyco/cordova-crosswalk-engine/archive/c0.6.1.zip
    [=============================]  100%  0.0s

**Comment by zarko-tg** [comment]
I can confirm, it's a big issue. In other attempts I get a different message:

/Users/zarko/.nvm/v0.10.36/lib/node_modules/ionic/node_modules/colors/colors.js:125
    return str + '';
               ^
RangeError: Maximum call stack size exceeded

___
Environment:
node 0.10.36, npm 2.5.0, cordova 4.2.0 (with android platform 3.7.1), ionic 1.3.8 on OSX 10.10.2

**Comment by SidneyS** [comment]
I also get the same errors, the current Ionic CLI build cannot be used for creating Crosswalk based projects.

**Comment by jbavari** [comment]
I'm looking into this issue today. I've been running node 0.10.33 with no problems. I'm upgrading now to see if I run into the same issue.

**Comment by jbavari** [comment]
@SidneyS That's interesting that 1.3.4 fixed it.

I just bumped to v0.12 and smoothed things out for CLI 1.3.9, I was previously on v0.10.33.

I'm wondering if some updates to some modules we've used have changed that? I'll look through the changelogs of some of those modules that have been updated between 1.3.4 and now.

@zarko-tg - I see you're using Node 0.10.36, would you mind bumping to node v0.12 and seeing if that fixes it? I'm just curious.

@SidneyS @S0lll0s - What version of node are you all running? Could you copy/paste the `ionic info` command to help me zero in on the issue?

**Comment by zarko-tg** [comment]
Hey @jbavari ! I just did a quick check.
Adding Crosswalk when using ionic-cli 1.3.10 on top of Node 0.12.0 appears to be back to normal.

**Comment by jbavari** [comment]
Awesome, thanks @zarko-tg! Waiting to hear back from @S0lll0s before closing the issue.

**Comment by S0lll0s** [comment]
@jbavari seems to be working perfectly now!
