### ISSUE TITLE
v3: Cordova CLI not found on your PATH

### ISSUE THREAD

**Issue by cozzbie** [driftyco/ionic-cli#2271]
#### Short description of the problem:

In trying to update an existing project that has been working fine from v2 to v3, I get the above error when I try to do `npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest`.

I have also noticed that Cordova is not listed in my global packages under `ionic info` even though `sudo cordova -v` works just fine outputting `7.0.1`

#### What behavior are you expecting?

Packages should install normally

**Post the output of `ionic info` below please**
```
global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002
    ios-deploy : not installed
    ios-sim    : not installed

```

**Comment by awss123** [comment]
same problem !!

**Comment by cozzbie** [comment]
So I just reinstalled v2.2.3 and this is my ionic info

```
Your system information:

Cordova CLI: 7.0.1
Ionic Framework Version: 3.2.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: 5.0.13
OS: macOS Sierra
Node Version: v7.10.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```
as you can see, my cordova is listed properly showing the issue is with ionic cli v3

**Comment by dwieeb** [comment]
Duplicate issue. See https://github.com/driftyco/ionic-cli/issues/2214
