### ISSUE TITLE
"Task 'wrapper' not found in root project 'android'."

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2279]
https://forum.ionicframework.com/t/ionic-connectivity/88882

Probably nothing with the CLI but Cordova and Android.
(Note the different CLI versions)

**Comment by dwieeb** [comment]
Yep, definitely Cordova/Android issue. I would mess with the installed SDK, Cordova versions, and Cordova Android platform versions, preferring the latest versions. That generally clears up weird build errors for me.

**Comment by hadrien-toma** [comment]
A Cordova issue [here](https://issues.apache.org/jira/browse/CB-12819) about this error.

**Comment by isacfernando** [comment]
Go to the site https://gradle.org/releases, download the lastest version in some folder.
Unpack the zipfolder and create a symbolic link: sudo ln -sf /PATH-TO-BIN-FOLDER/gradle /usr/bin/gradle

**Comment by LuisEstebanArango** [comment]
Issue resolved by upgrading Gradle version to 3.5.

**Comment by akshaypunchh** [comment]
Following code works for me 
just put following lines at app/build.gradle

`task wrapper(type: Wrapper) {
    gradleVersion = '2.14.1'
}`
