### ISSUE TITLE
Update v1 docs

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2280]
People still use v1 of Ionic, so the CLI part should probably be updated (or at least a notice to the current docs be added):
https://ionicframework.com/docs/v1/cli/start.html

**Comment by dwieeb** [comment]
Thanks for noticing that, @piotrowski. That surprises me... I will talk with @perrygovier and get this updated.

**Comment by piotrowski** [comment]
Another one:
> For v1 projects, use the --v1 flag.
http://ionicframework.com/getting-started/

**Comment by piotrowski** [comment]
(Shame that Google can't search for `--v1` :/

**Comment by piotrowski** [comment]
Ah, Github allows can search for this: 
https://github.com/driftyco/ionic-site/search?utf8=%E2%9C%93&q=%22--v1%22&type=

**Comment by perrygovier** [comment]
fixed in 6923547e4ec3155bbe2a2e4ac3e387cc2d1a5545
