### ISSUE TITLE
Ionic time out error

### ISSUE THREAD

**Issue by 1374hamed** [driftyco/ionic-cli#2281]
Hi - I'm new to ionic . I get this error on start blank app
✔ Creating directory C:\projects\noteit - done!
Fetching app base (https://github.com/driftyco/ionic2-app-base/archive/master.tar.gz)
✖ Downloading - failed!
Error: Timeout of 25000ms reached for https://github.com/driftyco/ionic2-app-base/archive/master.tar.gz
 can anyone help ?

**Comment by dwieeb** [comment]
@1374hamed This will be solved in the next version. See https://github.com/driftyco/ionic-cli/issues/2256 

Thanks.
