### ISSUE TITLE
Support serve browser platform locally over https

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2282]
_From @padgettrowell on May 15, 2017 13:13_

**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Ionic does not currently support serving locally over https when targeting the browser platform. 

**Expected behavior:**

Being able to serve an Ionic project locally over https allow for real world testing of applications targeting the browser platform. For example, testing CSP policies. For example, it's not possible to locally test the following policy:
Content-Security-Policy: upgrade-insecure-requests

**Steps to reproduce:**

In your index.html file, add the following <head> element:
```
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```
All content fails to load.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

_Copied from original issue: driftyco/ionic#11674_

**Comment by piotrowski** [comment]
Hm, as a curious bystander here @padgettrowell: 
What kind of certificate would that require to be served?

**Comment by dwieeb** [comment]
@padgettrowell Can you use haproxy?

**Comment by padgettrowell** [comment]
@piotrowski I'm only thinking about the development process, so a self signed certificate for localhost would suffice.

**Comment by padgettrowell** [comment]
@dwieeb I could use a proxy, but it's a short term solution to what I think is a larger problem.

With Ionic2+ supporting the browser as a first class platform, I think an out of the box solution to serving HTTPS locally would be beneficial. I get this hasn’t been an issue to date, as mobile platforms serve from disk on the local device, so (local) HTTPS isn’t an issue. 

With the browser platform, it’s really important to be able to serve and test your application locally over https. As a developer, I want to test things like CSP policies, HSTS, HTTP/S redirects on my local machine, before deploying to a server.  Being able to do this via the Ionic CLI (and not needing to setup a proxy) would be great.

**Comment by dwieeb** [comment]
Consolidating to https://github.com/driftyco/ionic-cli/issues/2312
