### ISSUE TITLE
bug: Create app using ionic 1

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2286]
_From @hiren443 on May 15, 2017 11:1_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>How can I create app using ionic v1.

I have tried using ionic start firstProject blank --v1. But it always create with latest version of ionic. 
Currently I have Angular app which is in Angular 1 and i want to replicate same with ionic 1.

How can I create the app with ionic version 1?

Thanks,</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#11669_

**Comment by jgw96** [comment]
Hello @hiren443, would you mind running `ionic --version` and posting the output here, please?

**Comment by piotrowski** [comment]
Command to create Ionic v1 projects are documented here:
https://github.com/driftyco/ionic-cli#ionic-1

**Comment by dwieeb** [comment]
Did this to hopefully cut down on this very common question: https://github.com/driftyco/ionic-cli/commit/d5c193669dd2505e695afca511b623f4068a5890

**Comment by hiren443** [comment]
@jgw96 

Hirens-MacBook-Pro:Cordova Hiren$ ionic --version
3.0.0

**Comment by hiren443** [comment]
@jgw96 
Hirens-MacBook-Pro:Cordova Hiren$ ionic --version
3.0.0

@piotrowski Thanks for the link. It works now.

Thanks,
Hiren
