### ISSUE TITLE
Non zero exit with @ionic/cli-plugin-cordova causes CI environment failure

### ISSUE THREAD

**Issue by admosity** [driftyco/ionic-cli#2287]
#### Short description of the problem:
I'm running unit tests in an environment (maintained by a corporate IT team) that I don't have control over. `npm install` is giving a non zero exit causing the CI testing pipeline to fail. They're running the following process  `npm install && whatever-else-scripts-go-here && other-script`.

`npm install` causes 

![image](https://cloud.githubusercontent.com/assets/4655972/26061951/65aee794-3957-11e7-96fa-23f3ebe95a5b.png)

Is there any way around this?

#### What behavior are you expecting?
Expect `npm install` to exit with 0. 

**Steps to reproduce:**
`npm install` on fresh clone without ionic or cordova installed globally.

**Post the output of `ionic info` below please**
local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

#2015 #2103

https://github.com/driftyco/ionic-cli/blob/master/packages/cli-plugin-cordova/bin/postinstall#L54

**Comment by dwieeb** [comment]
There's an environment variable you can set in your CI servers: https://github.com/driftyco/ionic-cli/blob/master/packages/cli-plugin-cordova/bin/postinstall#L5

I added it to the message to make this clearer: https://github.com/driftyco/ionic-cli/commit/fca165958bfb0f5d10a82787c5066c2bd26fcf67

Thanks

**Comment by admosity** [comment]
Thanks! I can get that request through.
