### ISSUE TITLE
--nolivereload not working

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2288]
_From @rashnk on May 4, 2017 13:2_

**Short description of the problem:**

I tried this, `ionic serve --nolivereload` but it does not seem to be working, it still detects changes and reloads the browser.

 
**What behavior are you expecting?**

when file change is detected, do not build and do not reload
 
**Steps to reproduce:**

1. run` ionic serve --nolivereload`
1. Make changes in some .ts or .html file

**Ionic Info**

Your system information:

 ordova CLI: 6.4.0
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v7.7.4
Xcode version: Not installed 

_Copied from original issue: driftyco/ionic-app-scripts#962_

**Comment by jgw96** [comment]
_From @rashnk on May 6, 2017 10:27_

how to disable live reload when run ionic serve ? i hope someone in ionic team will look into this issue

**Comment by dwieeb** [comment]
@jgw96 This is an app-scripts issue.
