### ISSUE TITLE
"ionic resources" without adding platform

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic-cli#229]
Please add support for run `ionic resources` without having local platform files for iOS and Android.
I don't need them when I'm using PhoenGap Build and it would be nice to create icons for iOS on a windows machine.

**Comment by AliMD** [comment]
:+1:

**Comment by itrond** [comment]
+1

**Comment by tomchiverton** [comment]
+1

**Comment by walfro** [comment]
+1

**Comment by rpignolet** [comment]
:+1:

**Comment by tomchiverton** [comment]
FYI this is done.
