### ISSUE TITLE
Please restore support for --aot build flag

### ISSUE THREAD

**Issue by rapropos** [driftyco/ionic-cli#2291]
#### Short description of the problem:

ionic cordova build [platform] --aot no longer works.

#### What behavior are you expecting?

app-scripts has an --aot flag that uses ngc but not minification. I find it very useful. CLI v3 seems not to want to pass this flag through, so --aot builds become just JiT --dev builds. If I do nothing but downgrade CLI to 2.2.3 (keeping app-scripts version identical), `ionic build [platform] --aot` works again.

**Steps to reproduce:**
1. install CLI v3
2. try to run `ionic cordova build [platform] --aot
3. note that `ngc` does not run

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.0
    OS         : Linux 4.9
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
@rapropos I'm not an expert with the build config, but would this be achievable with `--prod` ?

**Comment by rapropos** [comment]
Thank you for taking the time to respond. The problem with `--prod` is that it enables minification, which makes debugging nigh-impossible. The `--aot` option provides use of `ngc` without minification. If there is another way to say `--prod --no-minify` (or whatever you consider an appropriate name), that would work, but as of now I do not know how to enable AoT without minification.

**Comment by dwieeb** [comment]
Thanks, @rapropos! That sums it up nicely.

@danbucholtz / @jthoms1 Can you weigh in? I see `--aot` is still an option in app-scripts. What do devs do for debugging AoT builds?

**Comment by danbucholtz** [comment]
@rapropos, cat man 😸 , this is working for me if I run `npm run ionic:build --aot`. Is it working for you? Trying to identify if this is in the CLI or in app-scripts.

Thanks,
Dan

**Comment by rapropos** [comment]
@danbucholtz: confirmed that `npm run ionic:build --aot` does indeed invoke `ngc`, but `npm run ionic:build android --aot` does not build an android package. I am unsure whether that syntax is supposed to work, and do not know what syntax is intended for CLIv3: I thought it was `ionic cordova build [platform]`. I believe the issue is not with app-scripts, but with CLI.

**Comment by dwieeb** [comment]
@rapropos Yeah, we're just not passing some flags to app-scripts. I think `--aot`, `--minifyjs`, and `--minifycss` will be common enough that I'll add it to the CLI "whitelist" for now, but we need a better solution soon for all these options that end up all over the place (Cordova, Gradle, xcode, app-scripts???)

**Comment by dwieeb** [comment]
Thanks, @rapropos !! 🎉
