### ISSUE TITLE
Ability to disable interactivity (--no-interactive)

### ISSUE THREAD

**Issue by rapropos** [driftyco/ionic-cli#2292]
#### Short description of the problem:

Interactivity is not always desirable. In CI systems or other automated environments (that may not even have a viable terminal), it can be a complete deal-breaker. I think it would be great to make non-interactive mode the default, but realize that since there is so much more interactivity in the v3 CLI than in previous releases, that is probably not going to be in line with your design decisions. Could you please at least add a command-line option that completely eliminates any possibility of prompting for interactive input?

**Comment by dwieeb** [comment]
@rapropos On my todo list for sure. Many human-facing CLIs offer a global `--no-interactive` flag to entirely disable prompts.

**Comment by rasharab** [comment]
Just hit this in testing v3 with buddybuild.
Basically we're going to recommend to our customers to avoid using cli 3 until this flag is available as it breaks any CI.

-Rashin

**Comment by dwieeb** [comment]
@rapropos @rasharab Please test `--no-interactive` functionality with the latest alpha CLI: `npm i -g ionic@canary`
