### ISSUE TITLE
`ionic cordova` should check for `/www` and offer assistance

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2297]
#### Short description of the problem:

I checked out an Ionic project from Github. I first had to run `ionic serve` before `ionic cordova` recognized the project as a Cordova project (it's probably checking for availability of `/www` which is not there because of `.gitignore`). Until then I got this error:

```
PS C:\Users\Jan\Documents\Tenlan> ionic cordova build android
> cordova platform add --save android
✖ Running command - failed!
[ERROR] An error occurred while running cordova platform add --save android (exit code 1):

        Error: Current working directory is not a Cordova-based project.
```
or
```
PS C:\Users\Jan\Documents\Tenlan> ionic cordova build android --verbose
> cordova platform add --save android
Error: Current working directory is not a Cordova-based project.

[DEBUG] !!! ERROR ENCOUNTERED !!!
[ERROR] An error occurred while running cordova platform add --save android (exit code 1).
```
or
```
> cordova build android
Error: Current working directory is not a Cordova-based project.
```

#### What behavior are you expecting?

Using `ionic cordova` instead of `cordova` directly can help catch such cases. Something like:

> Seems you have just checked out a project and not build locally yet, so `/www` is missing. Run `ionic serve` or `npm run build` first before using Cordova commands to populate `/www`.

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.2
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
Thanks @piotrowski !

We should only need to create the directory to get past that Cordova check. The commands that need stuff in www should call a build before the Cordova commands start

**Comment by piotrowski** [comment]
> We should only need to create the directory to get past that Cordova check.

True, but this of course won't help the standard user that just cloned an Ionic project from Github ;)

> The commands that need stuff in www should call a build before the Cordova commands start

I start to disagree with this more and more:
Build times are quite long with all the stuff going on in them. I woul actually prefer if builds would have to be triggered manually and the "I use the stuff in `/www` commands" just should make it explicit what they are doing (and surface e.g. when the build was done that is being used etc.).

**Comment by dwieeb** [comment]
@piotrowski I have plans for checking whether a build is necessary. It's twofold: we check whether an active "watch" task is running for the build (thus no build required) OR we check whether a build is necessary via file modified times, checksums, etc.
