### ISSUE TITLE
Undefined port on ionic run with livereload

### ISSUE THREAD

**Issue by calebeaires** [driftyco/ionic-cli#2298]
#### Short description of the problem:
Command `ionic cordova run android -l` writes config.xml and put undefined port on content index.html tag. This is the automatically inserted text on config.xml

`<content original-src="index.html" src="http://192.168.1.3:undefined" />`

#### What behavior are you expecting?
This problems dont let the app entirely load on real device. Here is the print from the app after it is opened.

**Steps to reproduce:**
1. call livereload from ionic command
2. wait build and app launch

**Ionic Info**
```
global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/cli-plugin-cordova : 1.0.0
    @ionic/cli-plugin-ionic1  : 1.0.0
    Ionic Framework           : ionic1 1.3.3

System:

    Node       : v6.9.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.8.6 
    ios-sim    : 5.0.8 
```

**Comment by dwieeb** [comment]
Thanks, this was fixed in this commit: https://github.com/driftyco/ionic-cli/commit/fbaccd5d16c50fe0ce15f6cca6a5734a33133028

It will be in 3.1.0.
