### ISSUE TITLE
Ionic Login <Username> <Password> Prompt Makes Scripting Unusable

### ISSUE THREAD

**Issue by RyanHow** [driftyco/ionic-cli#2299]
#### Short description of the problem:

ionic login <username> <password> will prompt if the user is already logged in.

This would normally be ok, but I run this as part of a script, and it blocks the script.

#### What behavior are you expecting?

No prompt - simply log in using the username / password when they are passed using the command line.

**Steps to reproduce:**
1. Ionic Login <username> <password>
2. Ionic Login <username> <password> (Yes again)
3. Prompt is displayed

#### Alternative solution

Add a flag such as --force or --quiet which will suppress the prompt.

**Comment by dwieeb** [comment]
Thanks for the feedback. I'm removing the prompt in favor of just a warning. You may also be interested in this: https://github.com/driftyco/ionic-cli/issues/2293
