### ISSUE TITLE
bug: CLI "ionic info" shows incorrect information

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#230]
Type: bug

Platform: desktop browser

Not a major issue but on OSX, I typed "ionic info" into the terminal and it returned the OS as "OS: Mac OS X Yosemite". I've not taken the Yosemite plunge yet so I'm still running 10.9.5 . Here's the full output:

```
$ ionic info

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.1.2
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.1
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1 

```

See [this issue](https://github.com/driftyco/ionic/issues/2938#event-232551043) by @docherty

**Comment by jbavari** [comment]
@docherty - In the Node `os` module, 14.0.0 is Yosemite, and 13.0.0 is Mavericks. I've used [this as a reference](http://en.wikipedia.org/wiki/Darwin_%28operating_system%29#Release_history)

Just to help me out, can you run a quick node script? 

```javascript
var os = require('os')
console.log('Version:', os.release())
```
Please comment with the result!

**Comment by docherty** [comment]
Hi @jbavari Here's the output:
```
Version: 13.4.0
```
My version of OSX is 10.9.5

**Comment by jbavari** [comment]
@docherty - the code's been updated to fix this! Thanks!

**Comment by panchazo** [comment]
This seem to happen again in Mac OS Sierra. 
ionic info shows Os X El Capitan instead...

Cordova CLI: 6.3.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a
