### ISSUE TITLE
Reg:Calling Native SDK through Hybrid ionic2

### ISSUE THREAD

**Issue by SellvakumarSS** [driftyco/ionic-cli#2301]
We tried calling Native android code and from android we called native sdk for fingerprint scanner.But we end up in recreating native android code into cordova plugin.
Is it possible to create cordova plugin without rewriting native android code which should access native android SDK. We have already developed working native android code. 

Any Help Will be Appreciated.

Thanks in advance.

**Comment by piotrowski** [comment]
This is not an issue, but a question better posed at the Ionic Forum at https://forum.ionicframework.com/

**Comment by SellvakumarSS** [comment]
The environment is:
Your system information:

 ordova CLI: 6.5.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 8.1
Node Version: v7.4.0
Xcode version: Not installed
