### ISSUE TITLE
I can't use the command "ionic generate [type] [name]".

### ISSUE THREAD

**Issue by ffey** [driftyco/ionic-cli#2303]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

I'm sure that my local ionic version is 3.1.2

#### Short description of the problem:
G:\gitsoure\test\src\pages>ionic g pipe NewPipe
Error: ENOENT: no such file or directory, open 'G:\gitsoure\test\src\pages\src\app\app.module.ts'

It likes the the command used wrong templateDir.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
none

**Comment by piotrowski** [comment]
Can you try running `ionic g pipe NewPipe` in `G:\gitsoure\test\` please? 

Seems to be a path problem. Probably nobody thought about running this command in a subdirectoryyet.

**Comment by ffey** [comment]
thanks!

**Comment by piotrowski** [comment]
This could actually be a real bug - I don't know if this command is expected to be run everywhere or only in the project root.

**Comment by dwieeb** [comment]
@piotrowski noted. app-scripts doesn't work well in project subdirectories.

**Comment by ffey** [comment]
But.I remember that it works well in  project subdirectories  at the version of ionic 2.2.1.

**Comment by ffey** [comment]
what can I do if I want to create a new page in the folder pages's subdirectories ? how to use the command ?
