### ISSUE TITLE
Can't specify port with ionic cordova run browser --port=8100

### ISSUE THREAD

**Issue by dfa1234** [driftyco/ionic-cli#2307]
**Ionic version**
[ ] 1.x
[ ] 2.x
[X] 3.x

**I'm submitting a ...** 
[X] bug report
[ ] feature request
[ ] support request 

#### Short description of the problem:

`ionic cordova run browser --port=8100` don't listen on the specified port, but rather on 8000
and neither `ionic cordova run --port=8100 browser` works
(I have nothing on 8100, and I know its the port of ionic serve but thats not linked, could be 8200 or whatever... same result)
Some result from my cli:

```
dfa$ ionic cordova run browser --port=8200
Running app-scripts build: --port 8200 --p 8200 --address 0.0.0.0 --livereload-port 35729 --r 35729 --iscordovaserve --externalIpRequired --nobrowser
[....]
Static file server running @ http://localhost:8000/index.html
```
#### What behavior are you expecting?

Listening to the specified port

**Steps to reproduce:**
1. type `ionic cordova run browser --port=8100`
2. looking in the terminal and on the browser (in my case chrome) to see that the port is not 8100

**ionic info**
```

global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.0
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.0.1

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.1 Build version 8E1000a 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 


```

**Comment by dwieeb** [comment]
Consolidating to https://github.com/driftyco/ionic-cli/issues/2312

**Comment by dulajsan** [comment]
It's working. run the command except the keyword "cordova"

> ionic run browser --port=8100
