### ISSUE TITLE
bug: Unknown error with adding Crosswalk browser

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#231]
_From @hyyan on February 1, 2015 17:36_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.x</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi , Thanks for the great work , I am trying to use crosswalk with ionic , I followed the steps described here [Ionic and Crosswalk](http://ionicframework.com/blog/crosswalk-comes-to-ionic/) but I keep getting an error which I don't know how to resolve.

```
$ ionic browser add crosswalk
Adding crosswalk browser

Downloaded cordova-crosswalk-engine

Downloading: https://github.com/driftyco/cordova-android/archive/crosswalk.zip
[=============================]  100%  0.0s

Finished downloading cordova-android v4.0.x

Altered permissions for Android Paths

Downloaded Cordova Android for Crosswalk

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/8.37.189.14/arm/crosswalk-webview-8.37.189.14-arm.zip

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/8.37.189.14/x86/crosswalk-webview-8.37.189.14-x86.zip
unzipRepo writeStream: Error: invalid signature: 0x4f44213c
Crosswalk webviews failed to download -

An error with adding Crosswalk browser occured
```

```
$ ionic info

Your system information:

OS: Windows 7 SP1
Node Version: v0.10.25
Cordova CLI: 4.2.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.2
```

Any idea will be helpfull ? Thanks in advance</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3015_

**Comment by jbavari** [comment]
@hyyan - does this happen every time you run the command? Does it always fail to unzip the package?

**Comment by jbavari** [comment]
_From @hyyan on February 3, 2015 22:12_

@jbasinger , @jbavari  Yes , every time I run this command

**Comment by jbavari** [comment]
_From @jbasinger on February 4, 2015 12:42_

I think you @'d me by accident @hyyan =)

But, all is well, I think I see your problem. It looks like you're pulling an old version of Crosswalk.
Try this command instead:
`ionic browser add crosswalk@10.39.235.15`

**Comment by jbavari** [comment]
_From @hyyan on February 4, 2015 12:46_

@jbasinger , @jbavari  I tried this before I submit the issue , and I got the same result .

I don't know if this can help or related but I am using git bush to run my commands

**Comment by jbavari** [comment]
_From @jbasinger on February 4, 2015 12:52_

@hyyan Do you get the same error when you run from a regular window command prompt?
I have no idea how this download works, honestly, but this:
```
unzipRepo writeStream: Error: invalid signature: 0x4f44213c
Crosswalk webviews failed to download -
```
Looks like it might be a checksum of some kind? Maybe it's using the wrong tool to hash what you pull down or something silly.

**Comment by jbavari** [comment]
_From @jbasinger on February 4, 2015 12:58_

Just looked at the code a bit
https://github.com/driftyco/ionic-cli/blob/master/lib/ionic.js#L760
Looks like it's having trouble unzipping it. Do you have permissions to the folder it's trying to unzip to?

**Comment by jbavari** [comment]
_From @hyyan on February 4, 2015 13:11_

@jbasinger , @jbavari  I have just tried the default windows cmd and got the same result ,  and yes I have permission to the folder I am working on it , Is there any requirement that I might not be aware of ?

here is the result 

```
C:\Users\Hyyan\Desktop\fdg>ionic start my_app
Creating Ionic app in folder C:\Users\Hyyan\Desktop\fdg\my_app based on tabs pro
ject

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s

Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================]  100%  0.0s

Update config.xml
Initializing cordova project
Fetching plugin "org.apache.cordova.device" via plugin registry
Fetching plugin "org.apache.cordova.console" via plugin registry
Fetching plugin "com.ionic.keyboard" via plugin registry

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd my_app

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html


 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or visit the Ionic docs: http://ionicframework.co
m/docs

C:\Users\Hyyan\Desktop\fdg>ionic browser add crosswalk@10.39.235.15
Adding crosswalk browser

Downloading: https://github.com/driftyco/cordova-crosswalk-engine/archive/v0.8.z
ip

Downloaded cordova-crosswalk-engine

Downloading: https://github.com/driftyco/cordova-android/archive/crosswalk.zip


Finished downloading cordova-android v4.0.x

Altered permissions for Android Paths

Downloaded Cordova Android for Crosswalk

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/10.39.235.15/arm/crosswalk-webview-10.39.235.15-arm.zip

Downloading: https://download.01.org/crosswalk/releases/crosswalk/android/stable
/10.39.235.15/x86/crosswalk-webview-10.39.235.15-x86.zip


unzipRepo writeStream: Error: invalid signature: 0x4f44213c
Crosswalk webviews failed to download -

An error with adding Crosswalk browser occured
```

**Comment by jbavari** [comment]
_From @jbasinger on February 4, 2015 13:25_

@hyyan That is really odd. I found this bug in the unzip library being used, the message is similar but not exactly the same:
https://github.com/EvanOxfeld/node-unzip/issues/32

I'm using Crosswalk and those commands are working fine for me. The only other thing I can think of is that you don't have access to the URL it's trying to download? 
If you copy and paste the download.01.org link into a browser does it let you download the file?
Or maybe the version of unzip it's using is out of date somehow? Not sure how that could happen though.

**Comment by jbavari** [comment]
_From @hyyan on February 4, 2015 13:33_

@jbasinger , @jbavari  I have already tried to open the url in the browser with proxy and without proxy and it is fine , probably as you said it is a bug related to library used to unzip the file .

**Comment by jbavari** [comment]
_From @hyyan on February 4, 2015 13:53_

@jbasinger , @jbavari  I have just updated the ionic to version 1.3.7 and I got an infinity warning message 

```
ext version of node. Please use setImmediate for recursive deferral.
 ✗ (node) warning: Recursive process.nextTick detected. This will break in the n
ext version of node. Please use setImmediate for recursive deferral.

util.js:35
  var str = String(f).replace(formatRegExp, function(x) {
                      ^
RangeError: Maximum call stack size exceeded
```

Should I submit a new issue related to ionic 1.3.7 ?

**Comment by jbavari** [comment]
_From @matthewkremer on February 9, 2015 15:37_

@hyyan @jbavari @jbasinger I too am experiencing the "Maximum Call stack size exceeded" error when trying to add Crosswalk.

**Comment by hyyan** [comment]
@jbavari Updating Ionic to 1.3.10 solved the ""Maximum Call stack size exceeded" Error but the "invalid signature: 0x4f44213c" error still there

**Comment by jbavari** [comment]
@hyyan are you running node version greater than 0.10.33?

**Comment by hyyan** [comment]
@jbavari Sure I am running node 0.12.0

**Comment by jbavari** [comment]
It's looking like this might be an issue with the unzip module. 

I just had it ran on Win7 SP1, Node v0.12, Cordova 4.2.0, and Ionic CLI 1.3.10, and it worked fine.

I was thinking it was the unzip module with Windows, however, it worked fine.

I'll keep looking into it.

**Comment by jbavari** [comment]
@hyyan 

Can you grab a test version of the CLI i published to see if that fixes your issues you're having?

`npm install -g ionic@unzip`

**Comment by hyyan** [comment]
@jbavari Thank you for not giving up in this issue , I have just grapbed the test version , but now I am unable to create project .

Here is the response : 

```
Command line stuff: [ 'c:\\Program Files\\nodejs\\node.exe',
  'c:\\Users\\Hyyan\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic',
  'start',
  'my_app' ]
```

Is there something I should do , something I've missied ?

**Comment by jbavari** [comment]
Were there any other errors that were output?

**Comment by hyyan** [comment]
@jbavari  No , the cli didn't show any other errors .

**Comment by jbavari** [comment]
@hyyan Are you still having issues with this?

**Comment by hyyan** [comment]
@jbavari sorry for taking time to response , the issue still exists using the latest version of ionic-cli and node .
