### ISSUE TITLE
Ionic Cordova failed to build android

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2310]
_From @rooton on May 17, 2017 20:25_

**Ionic version:** 
[x] **3.x**

**I'm submitting a ...**
[x] bug report

**Current behavior:**
Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle
in your path, or install Android Studio

**Steps to reproduce:**
ionic cordova run --emulator

**Other information:**
Im an Android Developer.
So i have latest Android Studio (with latest gradle) installed on PC.
How can I just set path to my Android Studio?

**Ionic info:**

global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

_Copied from original issue: driftyco/ionic#11707_

**Comment by dwieeb** [comment]
http://stackoverflow.com/questions/19986214/setting-android-home-enviromental-variable-on-mac-os-x

**Comment by rooton** [comment]
Why you give me link to Mac OS X ?

My enviroment

Node       : v6.10.3
OS         : Windows 7

**Comment by shariajoe** [comment]
Why would an ionic 3.1.2 start template fail to run a build giving an error of system cannot find the path specified
.i.e. JAVA_HOME and ANDROID_HOME. 
My previous project versions were and are still running well without this error. Kindly advise
