### ISSUE TITLE
Constant Logging

### ISSUE THREAD

**Issue by RussellAFisher** [driftyco/ionic-cli#2311]
#### Short description of the problem:
When executing an `ionic cordova` command in CircleCI, like ```ionic cordova platform add ios``` it logs every single dot move of the spinner. 

#### What behavior are you expecting?
Feature Request:
Some way to block non-issue logging, --silence or disable the spinner

### Example of the log window output
```
ionic cordova platform add ios
> cordova platform add ios --save
⠙ Running command ⠹ Running command ⠸ Running command ⠼ Running command ⠴ Running command ⠦ Running command ⠧ Running command ⠇ Running command ⠏ Running command ⠋ Running command ⠙ Running command ⠹ Running command ⠸ Running command ⠼ Running command ⠴ ...you get the idea
```

**Comment by piotrowski** [comment]
Hihi, that's actually pretty funny.

**Comment by dwieeb** [comment]
Thanks @RussellAFisher 

With the next version of the CLI, there will be two ways to disable the constantly logging spinner:

1. Use `--quiet`, a global option that suppresses log messages "below" `WARN` (where as `--verbose` logs ALL log message levels).
1. (The preferred way for CI) Use `--no-interactive` mode, which disables the spinner as well as any prompts that might pop up.
