### ISSUE TITLE
Add list of installed Cordova platforms to `ionic info` (if Cordova plugin is present)

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#2313]
When people use Ionic with Cordova, their problems with Ionic (or whatever they implemented) often boil down to the Cordova version but also the Cordova platform version(s) they are using. Too old `cordova-android` breaks Gradle or Android Tools, too old `cordova-ios` breaks... everything. 

Right now we can only tell them to run `cordova platform list`. It would be great if the list of installed Cordova platforms could also (optionally, if the Cordova plugin is present) be output inside `ionic info`.

**Comment by dwieeb** [comment]
Easy enough. Great idea.
