### ISSUE TITLE
Ionic cordova resources:  Uploading source images to prepare for transformations - failed! Error: Timeout of 25000ms exceeded

### ISSUE THREAD

**Issue by nicksmithr** [driftyco/ionic-cli#2318]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`
**ionic -v
3.1.2**

#### Short description of the problem:
When running `ionic resources`
```
 Uploading source images to prepare for transformations - failed!
Error: Timeout of 25000ms exceeded
```

#### What behavior are you expecting?

**Steps to reproduce:**
1. Saved icon.ps & splash.ps
2. `Ionic cordova resources`
3.` Uploading source images to prepare for transformations - failed! Error: Timeout of 25000ms exceeded`

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by barroyo** [comment]
I am having this issue, only way to workaround it is to optimize the file size of the splash and icon images. Or get into decent high speed Internet connection. Nevertheless it would be a good idea that the CLI supports a possible timeout flag for those like me with not decent connection at home a high quality splash screen images.

**Comment by dwieeb** [comment]
@nicksmithr @barroyo The resources server that does the image manipulation is hosted on Heroku, which has a hard server timeout at 30 seconds. If an image can't be uploaded in 25 seconds (keeping in mind the stock images are all lossless PNGs under 200KB, so ~64kbits/s), then it might be better to generate the various sizes manually using imagemagick or photoshop or gimp.

Still, we can implement the `--no-timeout` flag, but you'll see a server error 5 seconds afterwards: https://github.com/driftyco/ionic-cli/issues/2337

Perhaps also we can look into getting non-US servers, which may help.

**Comment by barroyo** [comment]
Thank you @dwieeb, makes a lot of sense .. another improvement that will help is that the cli tell the server to only generate the assets required based on the `target-device` preference, so it only generates the real required ones, in some of my failed attempts the process end up generating only a few of the splash screens and then I get the timeout after some time. I have been trying to compress the splash screen but can't get it below 3mb, I guess we need to use less quality stock images.

Thanks

**Comment by JoyBhalla** [comment]
i'm getting the same error,will it lead to problems further in the build of the app?

**Comment by barroyo** [comment]
It may, since some of those assets are required by the the App store to succesfully upload the build to Testflight for example.
