### ISSUE TITLE
ionic package list shows dates in incorrect format

### ISSUE THREAD

**Issue by roryza** [driftyco/ionic-cli#2320]
#### Short description of the problem:

Date formats in the list are currently in "american" eg. "5/19/2017, 3:14:42 PM" and not according to the regional settings of the system.

#### What behavior are you expecting?

**Steps to reproduce:**
1. Have some packages built
2. Run `ionic package list`

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.1
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
@roryza Node doesn't ship with internationalization support built-in. As an alternative to including 20+ additional megabytes from a package such as [intl](https://www.npmjs.com/package/intl), we could print them in ISO format for everybody. What do you think?

**Comment by roryza** [comment]
ISO sound great to me...
One other minor note is that the cli includes the profile used, while the website doesn't. Pretty handy to have though.

**Comment by dwieeb** [comment]
Thanks
