### ISSUE TITLE
Cordova minSdkVersion parameter doesn't work

### ISSUE THREAD

**Issue by fttx** [driftyco/ionic-cli#2323]
#### Short description of the problem:
the command `ionic cordova build android --release -- --minSdkVersion=21` generates an apk with the minSdkVersion set to 15

**Post the output of `ionic info` below please**
```
global packages:

    @ionic/cli-utils : 1.1.2
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.6
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.1.1

System:

    Node       : v6.10.3
    OS         : OS X El Capitan
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

**Other information:** 
Before v3 update it was working properly.

**Comment by dwieeb** [comment]
Hi, please try `ionic cordova build android --release -- -- --minSdkVersion=21`

See https://github.com/driftyco/ionic-cli/issues/2254 as to why.

I added examples to the output of `ionic cordova build --help`: https://github.com/driftyco/ionic-cli/commit/8677e8ffd301aa41775027f661670f4a7f18691f

Thanks!
