### ISSUE TITLE
about timeout...

### ISSUE THREAD

**Issue by CacheTechLtd** [driftyco/ionic-cli#2328]
packages/ionic/src/lib/start.ts
`const archiveRequest = createRequest('get', url)
23	      .timeout(180000) // 3 minutes
24	      .on('response',`

and other place...

why did you make them???
if i wouldn't await, i will quit it.
this code is really disgusting and stupid...

**Comment by piotrowski** [comment]
> this code is really disgusting and stupid...

Yep, that's exactly how we are going to invest our time to help you. Please motivate us more!

**Comment by dwieeb** [comment]
@CacheTechLtd Trying to find that happy medium. We want it to time out when an erroneous download sits and spins indefinitely (which we've seen before) and the user just waits for hours before trying again. We also don't want to inconvenience those on slower connections. Considering our `tar.gz` files range between 1MB and 2MB, is it unreasonable to assume connections are faster than ~90kbit/s ? Maybe it is. I will increase it to a 15 minute timeout, which will support even the slowest of dialup speed internet.

**Comment by CacheTechLtd** [comment]
@dwieeb u should think about other place of the world, like China...r u heard of the great firewall of China(GFW)??

**Comment by CacheTechLtd** [comment]
@dwieeb @piotrowski thanks all of you, and apologize for my words...
