### ISSUE TITLE
[ERROR] Could not determine project type. Ionic 3 CLI

### ISSUE THREAD

**Issue by rflorat07** [driftyco/ionic-cli#2329]
sudo npm install -g cordova ionic
ionic start helloWorld blank

[ERROR] Could not determine project type.
        
        For Ionic Angular projects, make sure 'ionic-angular' exists in the dependencies attribute of package.json.
        For Ionic 1 projects, make sure 'ionic' exists in the devDependencies attribute of bower.json.
        
        Alternatively, set type attribute in ionic.config.json to one of: 'ionic-angular', 'ionic1'

**Comment by piotrowski** [comment]
What does `ionic info` give you? (Inside and outside project directory please)

**Comment by rflorat07** [comment]
Inside:
rflorat$ cd 2.Sonido/
rflorat$ ionic info

global packages:

    @ionic/cli-utils : 1.1.2
    Ionic CLI        : 3.1.2

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13

**Comment by rflorat07** [comment]
outside:
rflorat$ cd ..
rflorat$ ionic info
[ERROR] Could not determine project type.
        
        For Ionic Angular projects, make sure 'ionic-angular' exists in the dependencies attribute of package.json.
        For Ionic 1 projects, make sure 'ionic' exists in the devDependencies attribute of bower.json.
        
        Alternatively, set type attribute in ionic.config.json to one of: 'ionic-angular', 'ionic1'

**Comment by rflorat07** [comment]
rflorat$ nvm ls
       v0.10.32
         v4.4.2
->      v6.10.0
         system
default -> 6.10.0 (-> v6.10.0)
node -> stable (-> v6.10.0) (default)
stable -> 6.10 (-> v6.10.0) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.2 (-> N/A)
lts/boron -> v6.10.2 (-> N/A)

**Comment by dwieeb** [comment]
Do you have a stray `ionic.config.json` file outside your project directory?

**Comment by rflorat07** [comment]
I have this setting: 

nvm ls
       v0.10.32
        v6.10.0
->      v7.10.0
         system
default -> 7.10.0 (-> v7.10.0)

ionic info
[ERROR] Error occurred while loading plugins. CLI functionality may be limited.
        Checking for CLI updates now...
[WARN] The Ionic CLI has an update available! Please upgrade (you might need sudo):
       
           npm install -g ionic@latest
       
       

global packages:

    @ionic/cli-utils : 1.0.0
    Ionic CLI        : 3.0.0

System:

    Node       : v7.10.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 


After upgrade:  sudo npm install -g ionic@latest
 
ionic info

[ERROR] Could not determine project type.
        
        For Ionic Angular projects, make sure 'ionic-angular' exists in the dependencies attribute of package.json.
        For Ionic 1 projects, make sure 'ionic' exists in the devDependencies attribute of bower.json.
        
        Alternatively, set type attribute in ionic.config.json to one of: 'ionic-angular', 'ionic1'

**Comment by piotrowski** [comment]
No, he is asking if you have a `ionic.config.json` file in the folder where you are executing `ionic info`. This shouldn't be there if it's not an actual Ionic project directory.

**Comment by rflorat07** [comment]
OK, piotrowski, thanks very much.

**Comment by erassynathingo** [comment]
insert this line in your ionic.config.json file
<"type": "ionic-angular"> or <"type": "ionic1"> (without the tags)

worked for me

**Comment by chenHungTzu** [comment]
thanks @erassynathingo  you resolve my problem!! thanks you !

**Comment by Eliseuplugin** [comment]
thank you brother, it helped me a lot
it's working perfectly
