### ISSUE TITLE
Error at FatalException.Exception 

### ISSUE THREAD

**Issue by Hadard753** [driftyco/ionic-cli#2333]
I downloaded Ionic 3 few days ago and everything worked just fine when all of the sudden yesterday this error showed up after every ionic command I tried to use inside and outside my project dir (ionic info, ionic serve, ionic start etc.):

{ Error at FatalException.Exception (C:\Users\X\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\errors.js:8:23) at FatalException (C:\Users\X\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\errors.js:17:9) at Config. (C:\Users\X\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\config.js:41:31) at throw (native) at rejected (C:\Users\X\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\dist\lib\config.js:5:65) name: 'Exception', exitCode: 1, fatal: true }
I have tried to delete ionic and cordova and reinstall many times using many different instructions I found online:

npm uninstall -g cordova ionic
npm cache clean -f
npm install npm -g
npm uninstall node
apt-get purge npm
apt-get install npm
npm install node -g
npm install -g ionic cordova

I made sure they were really installed and uninstalled via npm -g list --depth=0

I've also tried to delete and reinstall node (following this [instructions](https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows)) but this error stay with every version of ionic 3.X I tried. 
ionic 2 on the other hand work great. any Idea what might have caused that and how to fix it?

I'm using:

Windows 10
npm : 4.6.1
node: v6.10.3
cordova: 7.0.1

version of ionic 3 I tried:
3.0.0
3.1.0
3.1.1
3.1.2
3.2.0

**Comment by dwieeb** [comment]
I'm guessing you have a super old plugins installed in your project.

For Ionic Angular:

```bash
$ npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest @ionic/cli-plugin-cordova@latest
```

For Ionic 1:

```bash
$ npm install --save-dev --save-exact @ionic/cli-plugin-ionic1@latest @ionic/cli-plugin-cordova@latest
```

**Comment by Hadard753** [comment]
still same error...

**Comment by yanxiaojun617** [comment]
https://github.com/ionic-team/ionic-cli/issues/2334

**Comment by dwieeb** [comment]
Anyone getting this issue should update their CLI to the latest. `npm i -g ionic`
