### ISSUE TITLE
Ionic CLI v3.1.2 command did not finish immedietly, but 'pause' for a while.

### ISSUE THREAD

**Issue by YaoaY** [driftyco/ionic-cli#2335]
Alomost every command delays for a while,except 'ionic --verbose' .
I recorded a gif to show this issue:

![ionic2](https://cloud.githubusercontent.com/assets/8706312/26352530/c8e5e996-3fee-11e7-9ef0-3a6a3725eb25.gif)

OS: Windows 10.0.15063
node: v7.8.0
npm: v4.6.1
ionic: v3.1.2

**Comment by dwieeb** [comment]
@YaoaY I'm guessing this has something to do with a slow connection to our telemetry servers. If it's a better experience for you, please try `ionic telemetry off`.

**Comment by YaoaY** [comment]
@dwieeb Thank you! It worked!

**Comment by netsesame2** [comment]
It cost me so much time on this issue to trace reason. So this post resolve my jobs!
