### ISSUE TITLE
ionic cordova build - build.json error

### ISSUE THREAD

**Issue by kesozjura** [driftyco/ionic-cli#2338]
#### Short description of the problem:
Running:
ionic cordova build ios --prod --release --device --buildConfig build.json

ionic web app is complied successfully, but cordova build is failing with error:
Error: The platform "build.json" does not appear to have been added to this project.

because ionic cli generates wrong cordova command:
cordova build ios _build.json_ --release --device --build-config build.json

There is build.json inserted after cordova build ios.

#### What behavior are you expecting?
Generated command should look like this:
cordova build ios --release --device --build-config build.json

I am using cli v3.2.0 and cordova plugin v1.2.0

**Comment by aemr3** [comment]
I have the same issue.
Ionic cli v3.2.0

**Comment by theomathieubhvr** [comment]
I confirm this issue as well.

To help you fix this, it appears on 3.2.0, 3.1.2, but **it works** on 3.1.1.

**Comment by dwieeb** [comment]
Thanks all, we're automatically parsing these options and it's kind of a mess. I apologize. It should be fixed in the next release.
