### ISSUE TITLE
run `ionic cordova run android` went wrong

### ISSUE THREAD

**Issue by ffey** [driftyco/ionic-cli#2339]
ionic version 3.2.0  run `ionic cordova run android`

#### Short description of the problem:
> cordova run android
Error: Unexpected end
Line: 0
Column: 0
Char:

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova run android (exit code 1).

There has no other error message.

**Post the output of `ionic info` below please**
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment]
I'm guessing some config file is empty. Running `cordova run android` as recommended in the error message would confirm that it's the Cordova CLI that has the issue, not the Ionic CLI. Try deleting your `platforms/` directory and running it again.
