### ISSUE TITLE
perf: ionic setup sass

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#234]
_From @mifama on February 6, 2015 23:16_

**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I updated the ionic version to last version, and now when I do 'ionic setup sass' it's return 
![npm install](https://cloud.githubusercontent.com/assets/9626717/6089152/91687b1a-ae5e-11e4-819c-47f96ecdb2d4.PNG)
</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3049_

**Comment by jbavari** [comment]
Could you paste the contents from `ionic info`?

Scanning the node-sass issues, it looks like theres [an issue filed](https://github.com/sass/node-sass/issues/490) about this and Node v0.12

**Comment by toby1kenobi** [comment]
I have this issue too, ionic info shows:

    Your system information:
    
    OS: Windows 8.1
    Node Version: v0.12.0
    Cordova CLI: 4.3.0
    Ionic Version: 1.0.0-rc.0
    Ionic CLI Version: 1.3.14

**Comment by jbavari** [comment]
@toby1kenobi can you post some of the error log as you saw them? It'd help to see that.

Or, did you have the same output as the original poster?

**Comment by jbavari** [comment]
@toby1kenobi and @mifama - Try updating your package.json file - change gulp-sass to be this:

`"gulp-sass": "^1.3.3",`

This should bump gulp-sass to use node-sass 2.x, which should resolve that issue.

**Comment by jbavari** [comment]
Closing - since this is more of a node-sass and gulp-sass issue.

**Comment by toby1kenobi** [comment]
Sorry for delay, will try your suggestion

**Comment by jbavari** [comment]
Please do. I was able to recreate it last night on my Windows machine like you had, and bumping that version solved the issue.

One other thing to note - at first I had trouble since Python is required, I installed 3.5, that had some issues. I found a stackoverflow post that specified using Python 2.7, which also helped.

Not sure if that is absolutely required though.

**Comment by toby1kenobi** [comment]
Brilliant, that did it - thanks!

**Comment by jbavari** [comment]
Yep. Were you running python 2.7 or 3.5?

**Comment by toby1kenobi** [comment]
2.7 - I was anyway, but as a result of some previous node-related situation
