### ISSUE TITLE
TypeError: Cannot read property 'F_OK' of undefined

### ISSUE THREAD

**Issue by CaptainMM** [driftyco/ionic-cli#2341]
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

**Note: for build related issues you can open up an issue on the ionic-app-scripts repo**

https://github.com/driftyco/ionic-app-scripts

Please ensure that you are on the latest version of the CLI.
`npm view ionic@latest version`

#### Short description of the problem:
Cannot execute command 'ionic' from an ionic3 project directory. Command works when outside of an ionic project dir. 

#### What behavior are you expecting?
Error displays "TypeError: Cannot read property 'F_OK' of undefined"

**Steps to reproduce:**
1. Run 'ionic' from any ionic3 project
2.
3.

```
insert any relevant code between the above and below backticks
```

**Post the output of `ionic info` below please**
[WARN] You are not in an Ionic project directory. Project context may be missing.

global packages:

    @ionic/cli-utils : 1.2.0
    Ionic CLI        : 3.2.0

System:

    Node       : v6.2.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.4

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

**Comment by Oliviercreativ** [comment]
Hello I have the same problem and I do not know how to do to solve it.

Ionic info:
[WARN] You are not in an Ionic project directory. Project context may be missing.

Global packages:

     @ Ionic / cli-utils: 1.2.0
     Ionic CLI: 3.2.0

System:

     Node: v6.1.0
     OS: macOS Sierra
     Xcode: Xcode 8.3.2 Build version 8E2002
     Ios-deploy: not installed
     Ios-sim: 5.0.8

  Olivier @ olivier-2 $ sudo ionic start myAPP sidemenu
TypeError: Can not read property 'F_OK' of undefined

Thanks in advance for the help !

**Comment by Petzall** [comment]
Had the exact same issue but updating nodejs itself to **LTS version 6.10.3** with NPM version **3.10.10** seemed to solve the problem. 
Does it for you guys too maybe?

**Comment by Oliviercreativ** [comment]
Hello,
I have just updated node js (on macOS) and i have this version:

Olivier @ olivier-2 $ ~ / Sites / playernorine / myApp> node -v
V6.1.0
  Olivier @ olivier-2 $ ~ / Sites / playernorine / myApp> npm -v
4.6.1

And I still have the same mistake …

**Comment by TwixD** [comment]
Ty @Petzall updated node v7.10.0 and works!

**Comment by Petzall** [comment]
@Oliviercreativ the latest version of node is v7.10.0 like TwixD got, but the LTS (Long Term Support) version could be more stable. 

If you're on MacOS or Windows the simplest way to upgrade is via [nodejs.org](https://nodejs.org/), download the install package and run the installer!

**Comment by Oliviercreativ** [comment]
Work for me 👍  but i'm rebuilded node-sass !
Thx you ;)

**Comment by dwieeb** [comment]
Hey all, yep, the recommendations to upgrade node and npm are correct. You might only get this error if your node version is old (in this case, 6.1 and 6.2 are from mid-2016). In these days, even a year is an eternity for JS 😄

**Comment by CaptainMM** [comment]
FYI, nvm was holding back my currently installed v7.10.0 so this was just a mistake on my part not realizing the current running version of node was out of date. Thanks for catching that!

**Comment by sameera207** [comment]
I had the same issue, upgrading my node from `v6.1.0` to `v7.10.0` fixed it 😄 

```
brew update
brew upgrade node
npm install -g npm
```

[this SO answer](https://stackoverflow.com/a/11298299)

I'm on
```
OS X EL Capital 10.11.6
```

**Comment by dwieeb** [comment]
Yep, latest 6 or 7 works.
