### ISSUE TITLE
Console.log in Hook not displayed

### ISSUE THREAD

**Issue by TheHighriser** [driftyco/ionic-cli#2342]
**Ionic version: (check one with "x")**
[ ] 1.x
[ ] 2.x
[x ] 3.x

**I'm submitting a ... (check one with "x")**
[x ] bug report
[ ] feature request
[ ] support request

#### Short description of the problem:

When I use a hook and do a simple console.log in the hook it will not be shown in the command line. I tried to use a hook when I start a build via "ionic cordova build android". It did not work. But the Hook itself is working. So only the Output is missing.

#### What behavior are you expecting?

I would like to see my output again like in V2.

**Steps to reproduce:**
1. Make a Hook
2. Insert Console.log in Hook
3. Run the Hook and see that output will not happen.

**Comment by TheHighriser** [comment]
Using only Cordova and not Ionic fixes this issue for me. This means Ionic CLI is the problem.

**Comment by dwieeb** [comment]
Thanks @TheHighriser ! In the next release we will forward the entire output from Cordova.

**Comment by lytieunuong1** [comment]
I got the same issue when I use hook through hook/ directory. Then I read the Cordova document https://cordova.apache.org/docs/en/7.x/guide/appdev/hooks/index.html and see that way was deprecated. So I try to use config.xml way https://cordova.apache.org/docs/en/7.x/guide/appdev/hooks/index.html#configxml
and write a node js file 
https://cordova.apache.org/docs/en/7.x/guide/appdev/hooks/index.html#javascript
and it's working perfectly. so you can show log by console.log('') in that file
