### ISSUE TITLE
Failed for ionic start

### ISSUE THREAD

**Issue by derekstwong** [driftyco/ionic-cli#2344]
At ionic forum, I raised one issue for ionic start.

I know that I am working behind company proxy, I don't know the proxy address nor password.

I was working fine at ionic v2, but once I got the great update from ionic v3, nightmare began....

ionic start -> error in self certificate chain...OMG....
tried: npm config strict-ssl false, registry...

I am quiet sure I have tried "general" configuration for npm, not work.

Found one TEMPORARY solution,
https://github.com/driftyco/ionic-cli/issues/2317

Dear Dev. Team, could we have solution for this ionic v3?

**Comment by dwieeb** [comment]
The solution is to get the proxy address from your company. Then, follow these steps: https://github.com/driftyco/ionic-cli#using-a-proxy
