### ISSUE TITLE
Ionic cordova resources Does not generate Windows 10 UWP resources

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#2346]
_From @tryadelion on May 25, 2017 14:13_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/driftyco/ionic-v1)
[ X] **2.x**
[X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Running "ionic cordova resources" does  not generate the desired resources, it says "no platforms installed", even when the platform is correctly listed on "ionic cordova platform ls"

_Copied from original issue: driftyco/ionic#11785_

**Comment by dwieeb** [comment]
Duplicate. Also not a bug...

https://github.com/driftyco/ionic-cli/issues/2174

**Comment by tryadelion** [comment]
@dwieeb  Windows **is** a platform supported by the ionic 2 **RELEASE**, and thus, it should be working accordingly. As i stated, it doesn't work on any of the CLI's, be it 2.0 or 3.0. 

Here is the size of what the generator should generate, cutting around the central XY axis, on every SCALE-100 setting:

ICONS
24x24
44x44
50x50
71x71
150x150
310x150
310x310

SPLASH
620x300

there's also each size scaled to 125%, 150%, 200%, and 400%, but those are optional.

**Comment by dwieeb** [comment]
The _framework_ has full support for Windows. The completely free image resizing service we offer in the CLI has a different support policy. You can track this feature request in https://github.com/driftyco/ionic-cli/issues/2174.
