### ISSUE TITLE
CLI v3: Cannot build the app using a CI server

### ISSUE THREAD

**Issue by datencia** [driftyco/ionic-cli#2347]
#### Short description of the problem:

I'm using Jenkins to integrate automated testing, building, etc.

My CI stops building the app due a new available update for `@ionic/cli-plugin-cordova` & `@ionic/cli-plugin-ionic-angular`

#### What behavior are you expecting?

CLI commands should not ask any confirmation to allow CI/CD.

Is there any way to avoid these questions?

**Steps to reproduce:**
1. Create a new Ionic 2 project and ensure you have the next library versions (package.json):
```
...
"devDependencies": {
  "@ionic/cli-plugin-cordova": "1.1.2",
  "@ionic/cli-plugin-ionic-angular": "1.1.2",
  ...
}
```
2. Run `ionic cordova build --prod android` (or any other command, e.g. `ionic info`)
3. The build stops asking a confirmation to the user to continue.

```shell
$ ionic cordova build --prod android
? Local plugin @ionic/cli-plugin-cordova has an update available (1.1.2 => 1.2.1)! Would you like to install it? No
[OK] Not automatically updating @ionic/cli-plugin-cordova. You can update manually:

     npm install --save-dev --save-exact @ionic/cli-plugin-cordova@latest

? Local plugin @ionic/cli-plugin-ionic-angular has an update available (1.1.2 => 1.2.0)! Would you like to install it? No
[OK] Not automatically updating @ionic/cli-plugin-ionic-angular. You can update manually:

     npm install --save-dev --save-exact @ionic/cli-plugin-ionic-angular@latest

Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[16:15:56]  build prod started ...
...
```

**Post the output of `ionic info` below please**

````shell
$ ionic info

global packages:

    @ionic/cli-plugin-proxy : 1.2.0
    @ionic/cli-utils        : 1.2.0
    Cordova CLI             : 6.5.0
    Ionic CLI               : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.1.2
    @ionic/cli-plugin-ionic-angular : 1.1.2
    Ionic Framework                 : ionic-angular 3.2.1

System:

    Node       : v6.10.3
    OS         : Windows 8.1
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
````

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

I think this feature should be optional (maybe via command line arguments), CLI commands should not ask any confirmation to allow CI/CD.

**Comment by dwieeb** [comment]
You can run the CLI in non-interactive mode: https://github.com/driftyco/ionic-cli#persistent-flags

**Comment by datencia** [comment]
cool, I didn't see that option, thx
