### ISSUE TITLE
Ionic commands hangs. Not terminated properly.

### ISSUE THREAD

**Issue by malwatte** [driftyco/ionic-cli#2352]
Hi,
I use Jenkins to build the Mobile app. But ionic commands hangs and does not terminate.
`ionic platform add ios --verbose`
![platform](https://cloud.githubusercontent.com/assets/2534778/26481584/b1a143d0-41ff-11e7-81d0-47423dab1559.png)

`ionic build ios --verbose`
![build](https://cloud.githubusercontent.com/assets/2534778/26481589/ba5f3270-41ff-11e7-9457-b19853c190c1.png)

Because of this Jenkins build takes long time (more than 30mins) and even fails.
But if I use 
```
cordova platform add ios
cordova build ios
```
build works fine. Takes less than 5 mins.

I have two questions,
1. Anyone knows reason why ionic commands hangs and not getting terminated properly?
2. Can I use cordova commands instead of ionic commands?

This is the ionic info:
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v0.12.18
Xcode version: Xcode 7.2.1 Build version 7C1002

Thank you.

**Comment by dwieeb** [comment]
That CLI version is ancient. We're only supporting CLI v3 going forward. If this is still an issue once you upgrade, let me know.

**Comment by malwatte** [comment]
@dwieeb ,
I cannot upgrade for the moment and it takes time to get the dependancies upgraded (e.g. node, cordova, ionic). 
Do you think I can use Cordova commands to build until I upgrade to newer version?

**Comment by dwieeb** [comment]
@malwatte Is there something that is incompatible? Why can't you upgrade?

Also, yes. For Ionic 1, you should be fine just running the cordova commands.

**Comment by malwatte** [comment]
@dwieeb ,
It is a remote MAC mini.and I do not have permissions to update it. It might take few days to get it updated.
I'll use the Cordova commands for the moment.
Thank you.
