### ISSUE TITLE
Deploy service ("ionic upload") renders "ionic emulate ios --livereload" useless

### ISSUE THREAD

**Issue by pwagner** [driftyco/ionic-cli#2353]
#### Short description of the problem:
Ionic Deploy service interferes with `ionic cordova emulate` (in general, but especially affecting the `--livereload` option).
The app that I get served in iOS Simulator is not based on my local code, but rather reflects the latest snapshot that was deployed via `ionic upload` to the production channel.

#### What behavior are you expecting?
When I run `ionic cordova emulate ios --livereload`, change something in a given file, and save that file, then I expect iOS Simulator to reload the app and present it with the changes applied.
Apparently this is no longer the case, once the Ionic Deploy service was used for this project (e.g. `ionic upload --note "0.0.1" --deploy production`).

**Steps to reproduce:**
1. Start new project, e.g. `ionic start ionic-emulate-test tabs`
2. Link project to Ionic Dashboard (`ionic link` etc.)
3. Set up Deploy service (`cordova plugin add ionic-plugin-deploy --save` etc.)
4. Upload snapshot and deploy to production channel (`ionic upload --note "0.0.1" --deploy production`)
5. Emulate, e.g. `ionic cordova emulate ios --livereload`
6. Change a file (e.g. a paragraph in home.html) and you will see that iOS Simulator will not display this change until it was deployed and the app subsequently has loaded and extracted the new snapshot.

I've created an example repo to reproduce the issue: https://github.com/pwagner/ionic-emulate-test

The Deploy service logic is implemented in app.component.ts's constructor based on examples from the docs (https://docs.ionic.io/services/deploy/):

```
platform.ready().then(() => {
      this.deploy.check().then((snapshotAvailable: boolean) => {
        console.log('snapshotAvailable', snapshotAvailable);
        if (snapshotAvailable) {
          this.deploy.download().then(() => {
            console.log('snapshot downloaded');
            return this.deploy.extract();
          }).then(() => {
            console.log('loading snapshot');
            this.deploy.load();
          });
        }
      });
});
```

**Post the output of `ionic info` below please**

global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 6.5.0
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : ios 4.3.1
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.1 Build version 8E1000a
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13

**Other information:**
See example project: https://github.com/pwagner/ionic-emulate-test
Related question on Ionic forum: https://forum.ionicframework.com/t/ionic-emulate-ios-livereload-and-ionic-upload/91455/6

**Comment by dwieeb** [comment]
The logic of when an app updates is up to you. If you have it check for updates from your deploy channel when your app boots up, it's going to update the app with the latest snapshot from that channel. That example is to show the simplest example of deploy functionality.

If you want to continue updating when the app boots up, I suggest you look into setting up different environments (dev vs prod) for your app.

**Comment by pwagner** [comment]
Shouldn't `ionic cordova emulate ios --livereload` always build and display the app based on the actual code on my development machine?

In my example repo, the existence of the lines of code implementing the deploy logic does no harm to the functionality of "emulate" ([relevant commit](https://github.com/pwagner/ionic-emulate-test/commit/c9ddbba39bf28d5bc0ebd625fc37fff9d5e445b4)).
In the "Steps to reproduce" section above, this corresponds to the state between step 3 and step 4. Here, the app is live-reloading in iOS Simulator as expected. As soon as I save a changed file, I can see the app reloading in Simulator and reflecting that change.

But once I start using the Deploy service by executing something like `ionic upload --note "0.0.1" --deploy production`, it looks like the behavior of "emulate" is changed. From then onwards, `ionic cordova emulate ios --livereload` no longer serves the app based on the current state of the code on my machine. Instead, the only way to get Simulator to show me the app based on the new code, is to "ionic upload..." again (and rely on the deploy logic to load and extract the new uploaded snapshot).

IMHO, this beats the purpose of emulation with live-reloading. 
To me it looks like "ionic upload" renders "ionic emulate ios --livereload" useless. 

Perhaps I'm missing something or got something completely wrong, in which case I'm sorry for wasting your attention. If there is a valid point to my issue, please consider re-opening it.

**Comment by pwagner** [comment]
Nevermind, I found my mistake: My deploy-logic caused the latest uploaded snapshot (if available) to get downloaded each time the app is started. It was basically overwriting my more recent changes with an older version, after the emulation correctly started up the app based on my machine's code in iOS Simulator.
