### ISSUE TITLE
Feature request: custom starter template

### ISSUE THREAD

**Issue by boye** [driftyco/ionic-cli#2356]
Hi guys,

Are there any plans to implement a feature that allows a custom starter template being passed to `ionic start`?

For example: `ionic start demoApp custom` and maybe (I am just thinking out loud here) `custom` can be defined in `package.json` or `ionic.config.json` like so:
```js
"starterTemplates":  [{
    name: 'custom',
    type: 'ionic-angular',
    description: 'My own custom Ionic template',
    path: 'user/repo-name',
    archive: 'https://github.com/user/repo-name/archive/<BRANCH_NAME>.tar.gz'
}]
```
This `starterTemplates` object then can be merged with the default templates that are already available when one runs the `ionic start` command.

Cheers!

**Comment by piotrowski** [comment]
See #2343

**Comment by boye** [comment]
@piotrowski thanks for pointing it out! I did a search myself...but couldn't find this particular issue. I guess this can be closed then.

Cheers
