### ISSUE TITLE
bug: Unable to create a release APK-webview is debugabl

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#236]
_From @luckyycool on September 4, 2014 16:6_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Unable to create a release APK (m able to debug) - 
Followed each steps of - http://ionicframework.com/docs/guide/publishing.html

except - 'Then, we can find our unsigned APK file in platforms/android/bin' , its wrong path it should be 'platforms\android\ant-build', 

When I install the released built apk in genymotion, i am able to debug the webview in chrome</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#2139_

**Comment by jbavari** [comment]
_From @luckyycool on September 6, 2014 4:10_

isn't anyone aware of this issue....can anyone help? Its has been a week am trying different steps to stop the debug mode of webviews????

**Comment by jbavari** [comment]
_From @perrygovier on October 1, 2014 20:33_

Hey @luckyycool, could you verify that it's signed? 
`jarsigner -verify -verbose -certs my_application.apk`

**Comment by jbavari** [comment]
_From @luckyycool on October 2, 2014 3:35_

Yes this is signed, and Important is it is not debuggable in real devices as it should be but in genymotion it is debuggable no matter what you do.

**Comment by jbavari** [comment]
@luckyycool - do you have a version of android that allows chrome debugging, Android 4.4 or greater?

**Comment by luckyycool** [comment]
Jbavari, yes I have but you won't need it. Just download any cordova app from app store, it's debuggable so I am sure it's actually cordova should be fixing this bug .
