### ISSUE TITLE
Release password prompt does not work in android build

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#238]
_From @kristianbenoit on November 7, 2014 15:21_

Building with `ionic build --release` while the build system is configured to use a keystore and alias, prompts for a password, but the password is never sent to the underlying tools.

To reproduce the problem
=====================
create a file `platforms/android/ant.properties` with the following content:

    key.store=/path/to/release_store.keystore
    key.alias=alias_name

Generate your keystore (see: http://developer.android.com/tools/publishing/app-signing.html#signing-manually):

    keytool -genkey -v -keystore /path/to/release_store.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000

Build with ionic:

    ionic build --release

Temporary solution
===============
Use cordova instead of ionic:

    cordova build --release

_Copied from original issue: driftyco/ionic#2512_

**Comment by jbavari** [comment]
_From @linagee on January 9, 2015 6:54_

Did you mean:
```
cordova build android --release
```
(Or does it just use the first available platform it has which might be Android?)

(Also, +1, this issue affects me too.)

**Comment by Fabii23** [comment]
I am having the same issue w/ no password prompt, any solutions?
