### ISSUE TITLE
perf: Seed projects take foreover due to extremely slow speed of github.com pull, push outside USA

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#239]
_From @vikrantrathore on February 3, 2015 3:51_

**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Trying to use ionic from Singapore with a extremely fast 100 mbps fibre connection. When try to initiate a ionic project using either:
ionic start project_name blank
ionic start project_name tabs
ionic start project_name sidemenu
It takes foreover to initialize the project and its always stuck at:

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=                            ]  6%  1994.4s

I complained about the speeds to github.com support staff and they mentioned they cannot do anything about it since their target market is USA and its only optimized for that market. For other markets they need to rely on their own services.

I wanted to use ionic outside of USA and the speeds are very very slow to a point that seed projects are unusable. 

Needed to wait for 3-4 hours for one seed project to initialize due to slow github.com speeds. Indeed other sides are working very well that includes watching HD quality videos, which are much bigger bandwidth hungary then source code.

**Is it possible if ionic cli can have option or configuration option to use some other service either local github repository or kiln or bitbucket.org for seed projects?**

</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3019_

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I have tried the install process over a VPN in Australia. Although it was slower than in the US the time it took was much more reasonable than reported last year.

If you feel that this is still an issue please feel free to reopen.
