### ISSUE TITLE
bug: App crash on screenshot with Android

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#247]
_From @CedNet on October 5, 2014 19:21_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Phone: Samsung Alpha
Android: 4.4.4
Ionic: 1.2.6
Build methods: both via Eclipse and Ionic build / run

Simply trying to take a screenshot of the app and it dies while holding in the buttons to take a screenshot. The app dies, and After it dies, android does indeed take a screenshot. 

Here's the dump-log from Eclipse:

10-05 21:14:26.967: D/SmartClipDataCropperImpl(3627): doExtractSmartClipData : Extraction start! reqId = -1  Cropped area = Rect(0, 0 - 720, 1280)  Package = se.xxx.xxxxxx
10-05 21:14:26.967: W/WebView(3627): extractSmartClipData is called
10-05 21:14:26.977: A/libc(3627): !@Fatal signal 11, thread 3708
10-05 21:14:26.977: A/libc(3627): Fatal signal 11 (SIGSEGV) at 0x000002dc (code=1), thread 3708 (Chrome_InProcRe)
10-05 21:14:26.982: D/SmartClipDataCropperImpl(3627): getOpaqueBackgroundRect : opaqueRect=Rect(0, 0 - 720, 1280)  element=com.samsung.android.smartclip.SmartClipDataElementImpl@41fa27e8
10-05 21:14:26.982: D/SmartClipDataCropperImpl(3627): getOpaqueBackgroundRect : opaqueRect=Rect(0, 0 - 720, 1280)  element=com.samsung.android.smartclip.SmartClipDataElementImpl@41fa2430
10-05 21:14:26.982: D/SmartClipDataCropperImpl(3627): addAppMetaTag : package name is se.xxx.xxxxxx</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#2350_

**Comment by jbavari** [comment]
_From @CedNet on October 5, 2014 19:56_

Oh, forgot to mention. The screenshot does appear to show the app. But the action and sound, appears after the app dies. So I guess it takes the screenshot, then dies, then does the animation, and stores the image.

**Comment by jbavari** [comment]
_From @marcsyp on October 6, 2014 16:39_

+1 I have also had this issue.

I am seeing a LOT of bugs with Android 4.4.4.  This is just one of many.  I am seeing missing images, touch screen swipe/scroll problems, etc.

**Comment by jbavari** [comment]
_From @gylippus on December 29, 2014 21:56_

I'm seeing the same thing. What version of cordova are you all using? I'm on 3.6.3. I'm trying to determine if this is Ionic related or cordova.

**Comment by mattezell** [comment]
Was there a resolution on this or was it simply closed due to inactivity?  I am also having this issue when snapping screenshots of my Ionic apps... Just as the OP stated, the screenshot is capture of the app, but the application crashes.  For what it's worth, I am running Cordova 4.2.0 and Ionic 1.3.2.

**Comment by jbavari** [comment]
@mattezell  - it was closed for inactivity. If you're having the issue, then it's definitely getting opened.

I'd love to help you hunt this down. I've got to figure out how to recreate the issue though. 

Are you deploying to a device or an emulator? 

If an emulator, one from Genymotion or a simple AVD?

If a device, which? And what version of Android?

**Comment by CedNet** [comment]
Update from myself is that on Lollipop, it appears to work just fine.

Cordova 4.2.0 and Ionic CLI v1.4.0 alpha 2.

**Comment by jbavari** [comment]
@CedNet - Awesome, thanks for the update. So in 4.4.4 for sure its happening. I'll try to recreate again.

Do you have any additional plugins you're using as well?

**Comment by CedNet** [comment]
A lot of plugins. So that shouldn't be it. 

I just tested on a 4.4.4 device with same CLI and Cordova, it worked. So I think it comes down to the Cordova version.

**Comment by x26xbb** [comment]
Hi, 

I'm having the same issue even though I'm not using Ionic at all, I'm currently on a Native development and for some reason when I take a screenshot on a very specific WebView I'm getting the same error. 

Phone: Samsung Galaxy S5
Android: 4.4.4
SDK: 21

Log: 

D/SmartClipDataCropperImpl﹕ doExtractSmartClipData : Extraction start! reqId = -1  Cropped area = Rect(0, 0 - 1080, 1920)  Package = com.mypackage
D/SmartClipDataCropperImpl﹕ getOpaqueBackgroundRect : opaqueRect=Rect(969, 96 - 1059, 186)  element=com.samsung.android.smartclip.SmartClipDataElementImpl@42c56ad8
W/WebView﹕ extractSmartClipData is called
D/SmartClipDataCropperImpl﹕ getOpaqueBackgroundRect : opaqueRect=Rect(0, 75 - 1080, 1920)  element=com.samsung.android.smartclip.SmartClipDataElementImpl@42c55b80
D/SmartClipDataCropperImpl﹕ getOpaqueBackgroundRect : opaqueRect=Rect(0, 75 - 1080, 1920)  element=com.samsung.android.smartclip.SmartClipDataElementImpl@42c557c8
D/SmartClipDataCropperImpl﹕ addAppMetaTag : package name is com.mypackage
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x000002dc (code=1), thread 6758 (Chrome_InProcRe)

Is there any workaround on this thread? 

PD: I have tested this on other devices and other Android, versions and it worked just fine, it is only this device specific where my issue stands. 

Thanks and best regards,
Kevin V.

**Comment by andypotts** [comment]
Just to clarify, was the fix to upgrade the Cordova version?

**Comment by rogerscg** [comment]
Still having an issue with this.

**Comment by jgw96** [comment]
Hello @rogerscg ! What version of cordova is your app using?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Franco-Alejandro** [comment]
Hi! I've been running into a problem with a specific device (Motorola G6). The thing is that I'm trying to take a screenshot on a screen that has a map (agm-map). Only on this screen, I'm experiencing some kind of crash or app freezing... the app just stops responding. I don't really know if it's related, but if any of you have an idea of what might be going on it'd be of great help!

Note: the debugger just doesn't log anything
