### ISSUE TITLE
bug: Bridge not enabled when using Crosswalk with livereload

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic-cli#248]
_From @ChrisLoer on January 28, 2015 18:0_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>I tried updating my Ionic app to use Crosswalk, following the [instructions provided in the blog post][1], and it seems to be working fine when I simply run it with `ionic run android`. However, if I try to use the "livereload" feature by running `ionic run android -l`, plugins stop working within the app. If I break inside `cordova.js:androidExec`, I can see that there's a call to `nativeApiProvider.get().exec` that simply doesn't return anything when I'm running in livereload.

It looks to me like the reason the bridge isn't working is this code in CordovaBridge.promptOnJsPrompt():

         if (origin.startsWith("file:") ||
             origin.startsWith(this.appContentUrlPrefix) ||
             (origin.startsWith("http") && loadedUrl.startsWith(origin))) {
             // Enable the bridge
             int bridgeMode = Integer.parseInt(defaultValue.substring(9));
             jsMessageQueue.setBridgeMode(bridgeMode);
             // Tell JS the bridge secret.
             int secret = generateBridgeSecret();
             return ""+secret;
         } else {
             Log.e(LOG_TAG, "gap_init called from restricted origin: " + origin);
         }

My origin is `http://192.168.1.42:8100/`, while the loadedUrl is `http://192.168.1.42:8100`, so the bridge secret never gets generated.

Without Crosswalk, essentially the same code runs, but the loadedUrl is set to `http://192.168.1.42:8100/`. I haven't been able to figure out where in the code this happens, but as a workaround I've just added a trailing slash in the content src of my config.xml. I think it would be better to modify the CordovaBridge code to do something like:

    URL originURL = new URL( origin );
    URL loadedURL = new URL( loadedUrl );
    if ( originURL.getProtocol().equals( "http" ) 
      && loadedURL.getProtocol().equals( "http" ) 
      && originURL.getAuthority().equals( loadedURL.getAuthority() )  )
    // Enable the bridge

  [1]: http://ionicframework.com/blog/crosswalk-comes-to-ionic/</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#2999_

**Comment by mattezell** [comment]
Curious if there's been any progress on this one?  

Is Crosswalk + Live Reload working for anyone or is it possible I am just doing something incorrectly?

I first introduced Crosswalk to an existing project, but quickly discovered I couldn't lean on my crutch - Live Reload... 

Figuring it was something with my existing codebase causing the problem in some capacity, I spun up a new test project using the tabs template.  Even with a template generated clean ionic app, I am unable to get Live Reload to work with the Crosswalk app - just a white screen...

**Comment by jbavari** [comment]
Hey @mattezell - I was reviewing this issue. I'm working great with crosswalk and live reload. 

Are you still having issues with CW & live reload?

**Comment by mattezell** [comment]
Same here - working with Crosswalk in my project without issue... Sorry I didn't update here - most of my conversation on this has been in the Ionic forums... 

Turns out my issue came as a result of the changes to Cordova - namely the split out of Whitelist to a plugin from Cordova core... After manually adding the plug in and adding a little to the index.html, Crosswalk works with live reload without issue...  We actually talked about it over here a bit - https://github.com/driftyco/ionic-cli/issues/361

I've not tried the latest updates to Ionic/CLI, so I can't personally speak to if it all just works out of the box or not just yet...

**Comment by jbavari** [comment]
Yep, I remember we hashed that issue out.

It's working for me, I'll close for now. Feel free to re-open if there's still issues. Thanks again.
