### ISSUE TITLE
Important 010_install_plugins.js concurrency problem

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic-cli#252]
It happens more often than not that one or more plugins don't get installed after adding a platform.

010_install_plugins.js does not even show any warnings or errors, which is only part of the problem. As a developer you end up thinking that all is fine until you run the app and get surprised if/when some plugin-dependent feature is broken. This has also been keeping me from updating to the latest Ionic CLI because of unreliability.

Things seems to go haywire for some reasons known to the "cordova plugin add" command internally, but what you try to do in the hook in question is running "cordova plugin add" asynchronously in a forEach. The command itself triggers bunch on actions on its own, and you run other things/hooks in addition. Such an execution makes the chances for something to go wrong pretty high.

Not sure how this hasn't been noticed yet since you introduced the new hooks.

Now, having spent some time with the issue, the problem goes away when resorting to a sync. execution of "cordova plugin add", for example:
```javascript
var exec = require('child_process').execSync;
...
sys.puts( exec('cordova plugin add ' + plugin) );
```

Parallel operations are great/faster but you need to be aware what you may step on.

Environment:
OSX 10.10.2
nvm 0.7.0 / 0.23.3 with node 0.12.0, npm 2.5.1
cordova 4.2.0, ionic cli 1.3.10

I my case I have around 10 plugins specified in package.json.
Command used: ionic platform add ios

cc @jbavari

**Comment by jbavari** [comment]
@zarko-tg I certainly agree. 

Part of the problem is, most of our users now are still running on Node 0.10.33-36.

Right now I'm thinking to get the Node 0.12.0 users:

`var exec = require('child_process').execSync || require('child_process').exec;`

I'd love some help in thinking through how to handle the sync execution for our users of older versions of node.

However, if it's an older version node user, they will still run into the error where plugins step on each other. Any ideas?

**Comment by zarko-tg** [comment]
I had already written a small piece of code and used it with older (and latest) Node versions. The execution of plugin adding was done via grunt-shell but it shouldn't matter, cause you'll be calling a system command. It'll give you serial execution and stop if any of the chained commands fail. It works across OSes.

Example:
```
cordova plugin add <path1> && cordova plugin add <path2> && cordova plugin add <path2> ...
```

Might be sufficient to execute that as a single command using child_process.exec 

For reference I'll provide you with my grunt-shell task (Ignore any specifics):
```javascript
      add_plugins : {
        command : function () {
          var
            plugin_map,
            commands_list = [],
            config        = grunt.config.get( 'plugins_config' );

          // parse plugins.json according to its own format and populate
          // a list of commands
          Object.keys( config.plugins ).forEach( function( plugin ) {
            var disabled_plugin;

            plugin_map = config.plugins[ plugin ];
            disabled_plugin = plugin_map.hasOwnProperty( 'disabled' )
              ? plugin_map.disabled
              : false;

            if ( ! disabled_plugin ) {
              if ( ! plugin_map.versionTag || plugin_map.versionTag.length === 0 ) {
                commands_list.push( node_util.format(
                  'cordova plugin add %s', plugin_map.url
                ));
              }
              else {
                commands_list.push( node_util.format(
                  'cordova plugin add %s#%s', plugin_map.url, plugin_map.versionTag
                ));
              }
            }
          });

          return commands_list.join( ' && ' );
        },
        options : {
          stdout      : true,
          failOnError : true,
          execOptions : { cwd : globalConfig.cordova_dir }
        }
      }
```

**Comment by jbavari** [comment]
[Here's](https://github.com/driftyco/ionic-cli/blob/eccba8557ce3a3b9d873e39f2101cf9064464dba/lib/hooks/after_platform_add/010_install_plugins.js) what I came up with

**Comment by jbavari** [comment]
@zarko-tg as an update, I'm thinking of removing these hooks since the cordova-cli will now track these via the config.xml file.

See [this announcement](http://cordova.apache.org/news/2015/03/02/tools-release.html).

What do you think? Have you been using the `--save` command yet?

**Comment by zarko-tg** [comment]
I have a relatively neutral opinion on the matter. Personally I have my own json file for plugins, Ionic puts them in package.json and Cordova now wants to keep them in config.xml.

So, whatever works.

**Comment by deuxpi** [comment]
Now that hooks have been added back to the templates, this bug still occurs and most of build will eventually fail if there are plugins that are missing to the plugins/fooplatform.json files.

**Comment by jbavari** [comment]
Did you try out the `ionic hooks remove` command?

**Comment by deuxpi** [comment]
@jbavari My problem is indeed solved by removing the hooks, but that doesn't mean that the concurrency problem doesn't exist for people wanting to use them.
