### ISSUE TITLE
bug: ionic start under proxy problem

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#254]
_From @diegorsd on February 11, 2015 11:59_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>npm works correctly under proxy.

"ionic start xxx" gives error: 
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ? Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip
 Error: tunneling socket could not be established, cause=Parse Error
 ? Error: Unable to initalize app: Error: tunneling socket could not be established, cause=Parse Error

PROXY and HTTPS_PROXY environment variable have been set as
"http://user:pass@host:port"</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3081_

**Comment by adamdbradley** [comment]
_From @diegorsd on February 11, 2015 12:4_

Ionic info

Your system information:

OS: Windows 7 SP1
Node Version: v0.12.0
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.10

**Comment by diegorsd** [comment]
Solved.

First, modify configuration file .npmrc as:
proxy=http://DOMAIN%5CUSER:PASSWORD@HOST:PORT
https-proxy=http://DOMAIN%5CUSER:PASSWORD@HOST:PORT
registry=http://registry.npmjs.org/
strict-ssl=false

Second, apply first step solution described in 
http://jasonwatmore.com/post/2014/04/02/Ionic-Framework-Getting-ionic-start-appName-Working-Behind-a-Proxy.aspx

Behind 2 lines found with the text "if (self.proxy) {"  in request.js add:
self.proxy = 'http://DOMAIN%5CUSER:PASSWORD@HOST:PORT';

The character \ encoded as %5C made the difference.

**Comment by jbavari** [comment]
Thanks for reporting the fix!

**Comment by thakurarun** [comment]
wow!, work like charm
