### ISSUE TITLE
resources: AI to Android loses the transparency and add masks

### ISSUE THREAD

**Issue by FMCorz** [driftyco/ionic-cli#257]
Steps:

* Generate an AI file at recommended size
* Type ionic resources
* Inspect the Android icons

Actual:

* The generated .png's are not transparent
* A mask was applied to the icons

Expected:

The icons look as they original.

PS: Using a PNG instead of an AI file produces the expected result.

**Comment by adamdbradley** [comment]
Would you be able to provide screen shots? What's the background color you're receiving? Do you have an AI I could take a look at? thanks

**Comment by FMCorz** [comment]
Sure, here goes: https://drive.google.com/a/moodle.com/folderview?id=0Bww43zw3J7yjfi1TSC10N2pfWHZFZ1pfcS11YjljcnEwV2JITUtqWDgxeWVlaG5QUTg0OGM&usp=sharing

**Comment by uofmmike** [comment]
I've also seen this, same idea. (.ai worked fine on IOS) fails to a white background on android

**Comment by ThomasDalla** [comment]
Similar issue, even with PNG: only the generated drawable-xxxhdpi-icon is transparent...

**Comment by adrianbj** [comment]
Same here, although in my case, the iOS icons lose their transparency also. The other issue I am seeing is that the icons are pixilated. It looks like the resizing is taking place after rasterizing, rather than before.

**Comment by FMCorz** [comment]
I can confirm that this affects PNGs as well. I have added 2 images to confirm it.

NOTE: You should download the imags and not compare them online.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I believe that AI are no longer a supported format for ionic resources. I was also able to test with a transparent png file and received them resized correctly with transparency intact.

I am going to close this issue but please feel free to reopen another issue if this occurs again.
