### ISSUE TITLE
App doesn't run on device after last update

### ISSUE THREAD

**Issue by joseadrian** [driftyco/ionic-cli#258]
After the last `ionic-cli` update, and  `cordova` plus `node runtime` (because it wouldn't let me run `ionic browser add crosswalk`), the app won't open on a device. 

I started a blank project and the same result. Emulator :white_check_mark: Device :x:. 

#### Steps:

```sh
ionic start example blank
cd example
ionic platform add android
ionic browser add crosswalk
ionic build android 
...
# BUILD SUCCESSFUL
```

#### Test device info
```
Platform: Android
Versión: 4.4.4 
Model: XT1032 & Moto G
```

#### > ionic info

```
OS: Mac OS X Yosemite
Node Version: v0.12.0
Cordova CLI: 4.2.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.10
Xcode version: Xcode 6.1.1 Build version 6A2008a
ios-sim version: 3.1.1
```

[This error log](https://gist.github.com/joseadrian/149d0b9a05e242210539) was taken from one of the apps after the update.

**Comment by jbavari** [comment]
Do you have a line in your `platforms/android/res/xml/config.xml` file that looks like the following:

`<preference name="webView" value="org.crosswalk.engine.XWalkCordovaWebView" />`

**Comment by joseadrian** [comment]
Yes, that line is in the `config.xml` file. Should I do something with it?

**Comment by jbavari** [comment]
No just checking to see if it was missing, that might have been the cause of the issue.

**Comment by joseadrian** [comment]
Well... this is odd. We've been using the **x86** version since the started using crosswalk but now we have to use the **arm** one. We've been renaming the x86 and arm apk files but I don't think we've made any mistake while renaming the files since we only prepend the name of the app at the beginning and because there is a difference of 2-3MB in each build (x86 > armv7) so it is easy to recognise.

On https://appthwack.com the blank project for the x86 version on 10 different devices, shows the same errors as in the previous error log and the arm doesn't. The error they highlight is `java.lang.RuntimeException: Use SharedXWalkView if you want to support shared mode`. I guess this is related to **crosswalk** and not to **ionic-cli**.

**Comment by astechnolabs-fullstack** [comment]
> Do you have a line in your `platforms/android/res/xml/config.xml` file that looks like the following:
> 
> `<preference name="webView" value="org.crosswalk.engine.XWalkCordovaWebView" />`

in my case, it's different : ` <preference name="webView" value="com.ionicframework.cordova.webview.IonicWebViewEngine" />`
