### ISSUE TITLE
Emulate with livereload doesn't give choice of addresses

### ISSUE THREAD

**Issue by kwoxford** [driftyco/ionic-cli#260]
Running "ionic emulate ios -l" gives this:

    Multiple addresses available.
    Please select which address to use by entering its number from the list below:

But the address options aren't shown and there's no way to select an address. After a short while the network IP address is automatically selected.

**Comment by jbavari** [comment]
Can you please run `ionic info` and let me know what versions you're running? That will help me help you.

**Comment by kwoxford** [comment]
Thanks

     OS: Mac OS X Yosemite
     Node Version: v0.12.0
     Cordova CLI: 4.2.0
     Ionic CLI Version: 1.3.10
     Xcode version: Xcode 6.0 Build version 6A313 
     ios-sim version: 3.1.1

**Comment by jbavari** [comment]
Aha, after a little digging, I'm seeing that before it serves, it checks your ionic.config file to see if you have any saved settings.

It saves them in a settings file located at ~/.ionic/ionic.config

See if your file has something like below by running `cat ~/.ionic/ionic.config`

```
{
  "versionCheck": 1424279168948,
  "ank": "19af5c3f-9dde-46c9-c116-fb99f6346715",
  "ionicServeAddress": "localhost",
  "platformServeAddress": "192.168.3.223"
}
```

**Comment by kwoxford** [comment]
ionic.config had a value of null for platformServeAddress so I changed it to localhost. I now get this:

    Setup Live Reload
    Running dev server: http://localhost:8100
    Running live reload server: http://localhost:35729

I.e. no mention of multiple addresses. 

But I'm getting a CORS problem, which I don't when running the emulator without livereload. 

    [Error] XMLHttpRequest cannot load file:///blah... Cross origin requests are only supported for HTTP.

The app accesses JSON files using httpQuery. It looks like the livereload server has messed this up. I've seen this raised previously (something to do with platform config.xml?) but I thought it had been fixed.

**Comment by jbavari** [comment]
Can you just remove that line in your `ionic.config`, and make it like below:

```
{
  "versionCheck": 1424279168948,
  "ank": "19af5c3f-9dde-46c9-c116-fb99f6346715"
}
```

Your running device may try to access `localhost`, which is itself, and not your computer per se.

**Comment by kwoxford** [comment]
Sadly that takes us back to square one, with the multiple address warning (but no way to choose an address). Dev server and reload server are running on my Mac's local IP address. And the CORS problem is still there!

**Comment by jbavari** [comment]
@kwoxford - lets take a minute to discuss the problem.

When you run `ionic run -l` - you have the app loading from your local ip `http://192.168.1.6:8100/` for example. Then, any AJAX request that goes out, has an `origin` set as your local IP.

If that API end point does not allow CORS requests, you might want to try out the ionic proxy.

[Look here](https://github.com/driftyco/ionic-cli#advanced-serve-options) at the section, 'service proxies'

**Comment by kwoxford** [comment]
Thanks. I've thought about proxies but what beats me is that livereload doesn't seem to work out of the tin. I set  access origin="*" in config.xml and then make a call such as this:

    var request = $http({
      method: "GET",
      url: "model/config.json",
      cache: false
    })

The app works OK in the emulator until I add -l to the command line, when it falls over. and screams CORS. Obviously there's a bug somewhere. I can see a lot of people have mentioned this fairly recently but I don't see that any solution has been posted other than using a proxy as a workaround, which is kludgy.

**Comment by jbavari** [comment]
Whats the exact error you're getting?

You're right, a lot of users have been having issues with this. I've got a blog post I'm writing up to help users like yourself understand the issue and why it comes up.

The access origin="*" is for the cordova webview, and that would not trigger CORS.

Are you accessing a file from the server with the same `origin` right? There shouldn't be any CORS going on there.

**Comment by kwoxford** [comment]
Yes, that's what beats me. These are files that are internal to the app! I have a bunch of json files in the models folder and I'm accessing them with $http. Standard, simple stuff that's worked on my last 20 apps without any problems. 

With the simulator the files are stored in the Devices folder on my Mac at

    Users/kwoxford/Library/Developer/CoreSimulator/[app ID] 

In the normal run of things when I make an $http request for those files the simulator gets them without any CORS issues. It looks like livereload has interfered with the simulator in some way so it now appears like a cross-domain request. But that's as far as my limited understanding goes.

**Comment by jbavari** [comment]
Ohh, Ok I understand now.

When you run `ionic run -l`, you're specifying it to run the app natively on your device, however, it loads the files from your server, not from the device itself. 

The reason is - when you make a change to one of your files (controllers.js, for example), it does not reload that file on your device. It reloads the browser that is loading the files from your ionic server.

That may be a reason for the CORS issues.

**Comment by kwoxford** [comment]
Well, I've tried everything and got nowhere. In a completely new vanilla installation of ionic, xcode and all the rest <code>ionic run ios</code> works but <code>ionic run ios -l</code> has CORS problems.

**Comment by jbavari** [comment]
@kwoxford - take a look over [this blog post](http://ionicframework.com/blog/handling-cors-issues-in-ionic/), let me know if that helps you understand how to work around the problem.

**Comment by jbavari** [comment]
@kwoxford I think I've got this figured out. I'll be pushing this out tomorrow.

**Comment by kwoxford** [comment]
Excellent!

**Comment by jbavari** [comment]
It's released! Try it out!
