### ISSUE TITLE
Error creating test application

### ISSUE THREAD

**Issue by arun8283** [driftyco/ionic-cli#262]
I am trying to create my first ionic app on windows 7.
This is where I started with installation: http://ionicframework.com/docs/guide/installation.html
All installations were complete (from DOS command prompt) and when I tried to create a new sample application, I got the following error from Git Bash, command prompt and Console2.

>Downloading: https://github.com/driftyco/ionic-app-base/archive/master.z
>[=============================]  100%  0.0s
>unzipRepo writeStream: Error: invalid signature: 0x4f44213c
> ? Error: Unable to initalize app: Error: invalid signature: 0x4f44213c

I am able to download the zip file through browser and open/unzip with winrar.

![image](https://cloud.githubusercontent.com/assets/11063359/6252648/cd113544-b769-11e4-85f6-19520ef94d8c.png)

Any help is highly appreciated.

**Comment by jbavari** [comment]
@arun8283 can you supply me with the information from `ionic info`?

**Comment by arun8283** [comment]
Ionic Info is here:

>Your system information:
>
>OS: Windows 7 SP1
>Node Version: v0.12.0
>Cordova CLI: 4.2.0
>Ionic CLI Version: 1.3.10
>
>
>
>------------------------------------
>Ionic CLI is out of date:
> * Locally installed version: 1.3.10
> * Latest version: 1.3.11
> * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
> * Run npm install -g ionic to update
>------------------------------------

I guess that makes it clear. Lemme try and update and post the result. 
Thanks!

**Comment by arun8283** [comment]
Nope, update didn't work. same error:
![image](https://cloud.githubusercontent.com/assets/11063359/6288617/323d3218-b8e8-11e4-98df-dfb800ea241d.png)

**Comment by jbavari** [comment]
@arun8283 would you be willing to test something out for me? 

I;ve been unable to recreate the issue you're having now. If I publish a test version of the app, will you test it out for me to see if that fixes the issue?

**Comment by jbavari** [comment]
Try installing the test version I have:

`npm install -g ionic@unzip`

**Comment by jbavari** [comment]
@arun8283 - any response? Did you try it out?
