### ISSUE TITLE
Upload Crash

### ISSUE THREAD

**Issue by nativeapps** [driftyco/ionic-cli#263]
I tried to use ionic view but the upload crashed after a view minutes.

$ ionic upload

Uploading app...
Error malformed response: SyntaxError: Unexpected token <
Response: Not Found The requested URL /api/v1/app/upload/***** was n (CLI v1.3.11)

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.1.2
Ionic CLI Version: 1.3.11
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.0.0

**Comment by jbavari** [comment]
@nativeapps I haven't seen this error yet.

Does the app run just fine in the simulator/device?

**Comment by nativeapps** [comment]
Yes. It runs on all variations (android, iOS, device and simulator) without any problems. 
I created another app from tabs template and it works fine. 
Maybe there is a bug when a project was updated to current ionic version.

**Comment by jbavari** [comment]
Can you post the contents of your `ionic.project` file?

**Comment by jamesgroat** [comment]
I was able to fix this issue by clearing my app_id field in ionic.project file and then uploading. The app_id got filled in by a value from the service I think.

**Comment by jbavari** [comment]
All working now?

**Comment by jamesgroat** [comment]
For me it is. Not sure about OP.

**Comment by jbavari** [comment]
@nativeapps - can you confirm you dont have an app_id in your ionic.project file? If you do, can you remove and try again?

**Comment by jamesgroat** [comment]
@jbavari If you check your server logs for 404's hitting https://apps.ionic.io/api/v1/app/upload/[some id that wasn't generated by ionic] you'll probably see other users w/ this issue.

**Comment by jbavari** [comment]
Yep, it's an on-going issue.

Many users open this file, then plop in an ID for `app_id`, then have issues with upload.

**Comment by louiswilbrink** [comment]
I ran into this issue today, but my `app_id` was already empty.

I downgraded node to v0.10.33 and the upload went through successfully (v0.12.0 threw the Error malformed response)

**Comment by orthodoc** [comment]
I had a similar problem. I repeated about two times, and on the third time the upload was sucessful without any error output.

**Comment by inzi** [comment]
I'm seeing this issue
OS: Mac OS X Yosemite
Node Version: v0.12.2
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.20
Xcode version: Xcode 6.3.1 Build version 6D1002 
ios-sim version: 3.0.0 
ios-deploy version: 1.5.0

**Comment by rainboxx** [comment]
Some notes:

* Better error message would be good, ran into this, too.
* We had a prefilled `app_id` but haven't used Ionic View previously, so it was filled with something a developer thought would be appropriate.
* Not having the key `app_id` in the `ionic.project` at all results in an error (because the `app_id` will result in `undefined` as string)

Resolution: clear your `app_id` in your `ionic.project` *but leave an empty string* for it!

**Comment by donald-s** [comment]
My app ID was filled in for whatever reason as well. Setting it to an empty string did the trick. Thanks @rainboxx for noting that. A better error message would be really nice.

**Comment by aaronprojects** [comment]
Setting the app_id to an empty string did the trick for me as well. Thanks a lot!

**Comment by demianh** [comment]
Simply setting the app_id to empty string did not work for me. I needed to do the following steps to get it working:

- set app_id to empty string
- updated node to 4.2.1
- updated cordova cli to 5.3.3
- updated ionic cli 1.7.6
- updated ionic framework with bower to 1.1.0
- deleted files in ~/.ionic/

**Comment by cawoodm** [comment]
I had the same issue: 404 on upload (though I had to hack upload.js to get this message) - BUG plus bad error handling?

I certainly did not fill in the app_id in ionic.project manually but clearing it allowed me to upload.

Is it normal that this URL returns 404:
https://apps.ionic.io/api/v1/app/
How can I see a list of apps I uploaded?
