### ISSUE TITLE
ionic run ios with 2 Dev Accounts set up in XCode

### ISSUE THREAD

**Issue by ibewugb** [driftyco/ionic-cli#264]
Hi, I habe the following problem: I have set up 2 Developer Accounts in XCode for iOS Development:
Acc1 and Acc2

When I connect my iPhone and then run the command 'ionic run ios' ionic takes Acc1 and usere its development provisioning profile to run the app.

BUT, what if I just want to use Acc2 for this? Where do I specify which account is selected?

**Comment by jbavari** [comment]
I'm not sure, I've never run into that issue before. Perhaps open XCode and specify the provisioning profile there, and then try running it.
