### ISSUE TITLE
Facebook plugin creates issues with the plugin installation hook

### ISSUE THREAD

**Issue by mrgirishrao** [driftyco/ionic-cli#268]
The facebook [plugin](https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/android/README.md) requires additional arguments while installation. 
Below is the command for installing the plugin 
`cordova -d plugin add /path/to/cloned/phonegap-facebook-plugin --variable APP_ID="123456789" --variable APP_NAME="myApplication"`

Unfortunately only the plugin gets added and not the arguments, this results in incorrect facebook plugin installation and errors in the project. 
This is how the package.json looks
  `"cordovaPlugins": [
    "org.apache.cordova.camera",
    "../fb_git/phonegap-facebook-plugin/"
  ]`

The correct way to populate the package.json would be

  `"cordovaPlugins": [
    "org.apache.cordova.camera",
    "../fb_git/phonegap-facebook-plugin/  --variable APP_ID='123456789' --variable APP_NAME='myApplication' "
  ]`

**Comment by jbavari** [comment]
Yes, I'm aware of this. I'm trying to work on a fix for the hooks to be able to handle local file installations of plugins, as well as handling variables. 

Thanks for the heads up!

**Comment by jbavari** [comment]
@mrgirishrao I've worked on this. The challenge was how to update users hooks without over writing their changes, much less, how to keep them updated.

Instead, I've added a few things to assist in this very problem.

First off, if you want to rid of those original hooks: `ionic hooks remove`.

Then, if you have your set up good to go - try doing `ionic state save`.

Alternatively, you can add this to your package.json (replace your variables):

```
"cordovaPlatforms": [
  "ios",
  "android"
],
"cordovaPlugins": [
  "org.apache.cordova.device",
  "org.apache.cordova.console",
  "com.ionic.keyboard",
  "org.apache.cordova.splashscreen",
  {
    "locator": "https://github.com/MobileChromeApps/cordova-crosswalk-engine.git",
    "id": "org.cordova.croswalk"
  },
  {
    "locator": "/path/to/cloned/phonegap-facebook-plugin",
    "id": "",
    "variables": {
        "APP_ID": "some_id",
        "APP_NAME": "some_name"
    }
  }
]
```

Then simply run `ionic state restore` or `ionic state reset`.

Let me know if that helps with the issue you are having.

**Comment by leonprou** [comment]
In my case there is other process that installing the plugins. It goes like this

>Leons-MacBook-Pro:cordova leonprouger$ ionic platform add ios
running cordova platform add ios
Running command: /Users/leonprouger/workspace/rakki/cordova/hooks/before_platform_add/init_directories.js /Users/leonprouger/workspace/rakki/cordova
Adding ios project...
iOS project created with cordova-ios@3.8.0
Running command: /Users/leonprouger/workspace/rakki/cordova/hooks/after_prepare/010_add_platform_class.js /Users/leonprouger/workspace/rakki/cordova
add to body class: platform-ios
Running command: /Users/leonprouger/workspace/rakki/cordova/hooks/after_prepare/020_remove_sass_from_platforms.js /Users/leonprouger/workspace/rakki/cordova
Running command: /Users/leonprouger/workspace/rakki/cordova/hooks/after_prepare/030_update_plist.js /Users/leonprouger/workspace/rakki/cordova
Installing "com.ccsoft.plugin.CordovaFacebook" for ios
Installing "com.ionic.keyboard" for ios
Installing "com.phonegap.plugins.PushPlugin" for ios
Installing "nl.x-services.plugins.launchmyapp" for iOS

It also doesn't read the plugins from `package.json`. But installing all plugins in `./plugins` directory. I'd like to disable this behaviour and use the `install_plugin.js` hook.

**Comment by jbavari** [comment]
@leonprou What you are running into is primarily due to the Cordova CLI operating the way it should.

That won't be easy to override the default behavior.

First off you install plugins - they go to the plugins folder. From there, when you install other platforms, those plugins are added from that folder.

You can still continue to use the `install_plugin.js` hook, nothing stops you from that.
