### ISSUE TITLE
Draw more attention to to gulpStartupTasks in the README

### ISSUE THREAD

**Issue by vasconcelloslf** [driftyco/ionic-cli#269]
Hello.

I was just about to implement the serve and livereload feature inside my gulp pipeline to improve my workflow and avoid running two commands (gulp and ionic serve), when by accident I stumble upon the awesome "gulpStartupTasks" option somewhere in the README. 

This options allows me not only to run gulp pipeline through ionic serve but also to remove one more command/thread (gulp dev in my case) from my workflow. Given that, I think the README could be improved to draw more attention to this amazing ionic-gulp integration. This option is just to useful to be "lost" (it is not lost but I don't have a better word for it) in the README. Maybe a section with some kind of "Gulp integration" headline.

What do you guys think?

**Comment by jbavari** [comment]
Yea you bet. Good call. I'll hop on this now.

**Comment by jbavari** [comment]
Done. Let me know what you think! Thanks again.

**Comment by vasconcelloslf** [comment]
Hey, it looks great! This will surely help all the gulp people! Tks.
