### ISSUE TITLE
"No newline at end of file" after run "ionic plugin add"

### ISSUE THREAD

**Issue by zckrs** [driftyco/ionic-cli#271]
After use CLI `ionic.project` and `package.json` lost the last new line at end of file.

I`m not sure that is real issue but I need your notice.

**Comment by jbavari** [comment]
That should be fine. It just calls `JSON.stringify` on the results and writes that to a file.

**Comment by zckrs** [comment]
Thanks for reply. 
If I write a PR who add a `\n` at end of `JSON.stringify`. Do you accept it ?

**Comment by jbavari** [comment]
Sure, that wouldn't hurt.

**Comment by zckrs** [comment]
https://github.com/zckrs/ionic-cli/commit/d6a43ebe9cf2df323199cdbd56d7977532a4e873

I create PR after local testing
