### ISSUE TITLE
Livereload triggers a page load before all watch tasks have ended (pebkac?)

### ISSUE THREAD

**Issue by mrthehud** [driftyco/ionic-cli#275]
The Ionic default is to run the "watch" task on server startup, but it seems that the page is reloaded before all of my tasks have been completed. E.g, I change some sass, livereload runs, but the browser loads the old css. If I hit ctrl+r, I get the updated sass.

Could this be an issue with ionic-cli / livereload, or am I the issue?

```javascript
// gulpfile.js
// ...
gulp.task('watch', function(done) {
    gulp.watch(paths.sass, ['sass']); // Sass from src to www
    gulp.watch(paths.js, ['js']); // Concatenate all js files from src to www
    gulp.watch(paths.html, ['html']); // Copy templates from src to www
});

// ionic.project
{
  //...
  "gulpStartupTasks": [ "sass", "js", "html", "watch" ],
  "watchPatterns": [
    "www/**/*",
    "src/**/*",
    "!www/lib/**/*"
  ]
}
```

Thanks Guys, great work.

**Comment by OClement** [comment]
+1

Experiencing the same issue here
Trying to use `ionic serve`, running a few task compiling/copying files over the `www` folder
Because files are copied "gradually", ionic's server is notified of a file change before all files get copied over and reload too soon

**Comment by briananderson1222** [comment]
+1 Any news on having the ionic server wait for my gulp task to complete before firing?

**Comment by peterholcomb** [comment]
:+1:

**Comment by barocsi** [comment]
+1

**Comment by mtpultz** [comment]
+1

**Comment by toru-sean** [comment]
+1

**Comment by cScarlson** [comment]
+1 on uglification

**Comment by toru-sean** [comment]
I had this problem but figured out a fix. 

The watch patterns in ionic.project to only watch the javascript/css files that your index.html loads. So if you load the minified versions of css & js then the project file should be something like this...

{
  "name": "myApp",
  "app_id": "",
  "gulpStartupTasks": [
    "watch"
  ],
  "watchPatterns": [
    "www/index.html",
    "www/css/*.min.css",
    "www/js/*.min.js"
  ]
}

and if you load the un-minified versions it should look something like this...

{
  "name": "myApp",
  "app_id": "",
  "gulpStartupTasks": [
    "watch"
  ],
  "watchPatterns": [
    "www/index.html",
   "www/css/*.css",
    "www/js/*.js",
    "www/css/!*.min.css",
    "www/js/!*.min.js"
  ]
}

I think this is something that Ionic could be clearer about in their docs.

**Comment by tlancina** [comment]
Yeah I'm not sure this is a bug, the watch patterns should only be matching the output, not the source files, as @toru-sean said.  If you are watching the source files then livereload will trigger as soon as you make a change to them, before the build finishes.

So the solution is to only watch files that indicate that the build has finished.  For more information on glob patterns, take a look at: https://github.com/isaacs/node-glob#glob-primer.

Just a heads up as well, `gulpStartupTasks` and `gulpDependantTasks` will most likely be deprecated in the 2.0 release of the CLI.  We haven't hashed out all the details yet, but gulp will either be more tightly integrated with the CLI (as in, it always looks for tasks with certain names) or will be more configurable from `ionic.project`.

Going to close as not a bug, but feel free to comment if you're still having issues or feel that this is not the case, thanks!

**Comment by toru-sean** [comment]
I think that the problem people here are having isn't because their watch patterns are matching their source code. It's because they have multiple output files - i.e. script.min.js AND script.js. The first file to be outputted triggers the livereload, but it isn't necessarily the one being loaded into the view they are seeing in their browser.

**Comment by toru-sean** [comment]
Although just re-read original post and he is watching src folder, so that's a different think i guess
