### ISSUE TITLE
Push notifications "send" needs to reflect new API key strategy

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-cli#279]
Right now it just asks for "API Key", but we have a public/private keypair now, so it's not obvious which is being asked for:

![screenshot 2015-03-03 14 21 26](https://cloud.githubusercontent.com/assets/11214/6471437/9faa365e-c1b0-11e4-9b79-df12e36c8522.png)

**Comment by jthoms1** [comment]
This issue has been resolved with commit 009f6305a991.
