### ISSUE TITLE
Error packaging project

### ISSUE THREAD

**Issue by KarontePhonegap** [driftyco/ionic-cli#280]
Hi,

When i tried package my project with command "ionic package release ios" from my Mac, the console show error:

"Uploading app...
Successfully upload (65344f84)

ios release building ...
ERROR PACKAGING PROJECT, PLEASE TRY AGAIN LATER"

..., some solution ??
Thanks.

**Comment by jbavari** [comment]
Hello @KarontePhonegap - we're still in the early stages of developing this. Please hang tight while we finish it up for release. Thanks.

**Comment by KarontePhonegap** [comment]
Hi jbavari, 
Thanks for your info.
Good work!!

**Comment by murilolobato** [comment]
So, if I understood this, I will be able to generate a build for iOS even if I'm using a windows platform? This is just amazing!!! There is a estimate to when this will be available? I really need this ;)

**Comment by jbavari** [comment]
@murilolobato yep - this is correct. We're working hard on it!
