### ISSUE TITLE
feat: Connect to API when behind proxy server

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#281]
_From @samithaf on March 4, 2015 3:58_

**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi guys,
Thanks for adding proxy request feature which allows to connect to external API. However when we are working behind a (company) proxy this won't work. After reading the source I figured it out that Ionic is using proxy-middleware plugin to do the proxying. 

Do you have any plan to support this feature in a upcoming release?

</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3229_

**Comment by samithaf** [comment]
Can someone please suggest at least a workaround for this particular issue? I try to use https://github.com/goinstant/global-tunnel however i was unsuccessful. Thanks

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
