### ISSUE TITLE
Don't print error info on SIGINT (control-c)

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-cli#284]
If the user kills the ionic cli with control-c, don't print the error info.

I think we just need to catch SIGINT

```javascript
function exitHandler(options, err) {
   // Don't print
  dontPrint = true;
  process.exit();
}

process.on('SIGINT', exitHandler.bind(null, {exit:true}));
```

**Comment by jgw96** [comment]
Gonna close this as it does not seem to be an issue with the latest release of the ionic-cli.
