### ISSUE TITLE
possibility of using either gulp or grunt

### ISSUE THREAD

**Issue by cyprusglobe** [driftyco/ionic-cli#285]
I'm wondering how we can use grunt with ionic-cli
@mlynch @jbavari

**Comment by jbavari** [comment]
As of right now, Ionic focuses on using Gulp. 

If there are grunt tasks you cannot live without, you might want to try [gulp-grunt](https://www.npmjs.com/package/gulp-grunt) - which will let you run grunt tasks from gulp.

Other than that, we dont have much plans to support grunt, as we feel the streaming builds gulp provides are superior to the file staging that grunt provides.
