### ISSUE TITLE
Commands after starting ?

### ISSUE THREAD

**Issue by sgentile** [driftyco/ionic-cli#286]
I just installed the latest cli - and before I could type 'r' or 'c' after it started to run the livereload commands - now they only work on initial startup

ie.
ionic emulate ios --livereload

then after it starts, type 'c'  or 'r'

1.3.13   (previous version worked)

**Comment by sgentile** [comment]
fyi - Just when back to confirm by installing 1.3.10 to test - 1.3.10 works - you can type commands after starting

**Comment by cdes** [comment]
I second that.

Commands after starting does not work in 1.3.13, but it does work in 1.3.10

**Comment by jbavari** [comment]
I'll have a hot fix out for this shortly. Thanks for reporting!
