### ISSUE TITLE
Is ionic-cli support build with shared mode crosswalk?

### ISSUE THREAD

**Issue by pewh** [driftyco/ionic-cli#288]
It seems `crosswalk-cordova-android` had implement [shared mode](https://github.com/crosswalk-project/crosswalk-cordova-android/pull/160). How I enable ionic-cli to build with shared mode crosswalk? Thanks.

**Comment by jbavari** [comment]
We currently do not support this. There is no road map to include this feature.

**Comment by sebrojas14** [comment]
+1

**Comment by ajrnz** [comment]
BTW you can do this via:

    ionic plugin add cordova-plugin-crosswalk-webview --variable XWALK_MODE="shared" --save
