### ISSUE TITLE
Issue with V 1.3.13

### ISSUE THREAD

**Issue by tlkiong** [driftyco/ionic-cli#289]
I just updated to 1.3.13 and my live reload seems to be broken somewhere.
At times it reloads properly - which is RARELY.
Most of the time, it does not reload the new file at all. I have to stop the server and then restart it 
"ionic serve"
Is there anyway I can downgrade to version 1.3.1 which I have been using without much issue at least on this end?

**Comment by jbavari** [comment]
If you'd like, I'd help you figure out the issue.

Do you specify an alternate path to watch in your `ionic.project` file?

Or -

Are the files you are changing in the default watched directories, `www`?

If not, what directories are you currently watching? 

Are those files being shown in the console when you watch them?

Feel free to install whichever version you like - using `npm install -g ionic@1.3.1`.

**Comment by tlkiong** [comment]
Hi jbavari,

Thanks a lot for the method to install a previous version!

1) I did not specify an alternate path
2) All my files are under the folder "www"

Most of the time it will just load the html file but do not load the controller. Do you know why that would happen?

**Comment by jbavari** [comment]
Is the controller included as a <script> tag for the controller? 

Is the routing correct for the view in `app.js`?

**Comment by tlkiong** [comment]
As a? @@

**Comment by jbavari** [comment]
Is the controller included as a `<script>` tag.

Somehow the response got cut off. Sorry about that.

**Comment by sgg90** [comment]
I have the same issue. Since I updated from 1.3.11 I have not been able to do live reload:
My issue: https://github.com/driftyco/ionic-box/issues/41

I use:
ionic serve --live-reload

and when I try to access http://localhost:8100 or http://10.0.2.15:8100 I can't see the pages.

**Comment by edmondchui** [comment]
In 1.4.2, the live reload works, but entering any commend like restart or quit do not work.

**Comment by jbavari** [comment]
@edmondchui please run `ionic info` and paste that information here.

Currently its working for me in all three environments - windows, linux, and mac.

**Comment by edmondchui** [comment]
```bash
$ ionic info

Your system information:

Cordova CLI: 5.0.0
Ionic CLI Version: 1.4.2
Ionic App Lib Version: 0.0.19
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.10.32
Xcode version: Xcode 6.3.1 Build version 6D1002 
```
