### ISSUE TITLE
ionic emulate ios live reload

### ISSUE THREAD

**Issue by schnti** [driftyco/ionic-cli#291]
Since a few days I have problems with the `ionic emulate ios -lcs --target="iPhone-6"`. Live reload and logging isn't working.

If I start `ionic serve` my server address is `Running dev server: http://localhost:8100` if I start `ionic emulate` my dev server is `Running dev server: http://10.5.19.92:8100`although I change via `ionic address` the address to `localhost`. iOS-Simulator prevents all addresses except http://localhost...

Since the latest versions of Ionic CLI, it is not possible to connect the same app on the local IP address or localhost at the same time

OS: Mac OS X Yosemite
Node Version: v0.10.32
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.14
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1 

Thanks for help.

**Comment by jbavari** [comment]
Looking into this now.

**Comment by jbavari** [comment]
Ok I've found out how to reproduce. Working on it now. Thanks for reporting!

**Comment by jbavari** [comment]
@schnti can you try to test the latest CLI to see if it fixes the issue for you? `npm install -g ionic@readline`.

**Comment by concongo** [comment]
Hello! Is this issue finally resolve? I'm running into the same problem. How could I solve it? Thanks for the help.

**Comment by drwicked** [comment]
I'm also still getting this problem. There seems to be no way to specify localhost when running livereload and I haven't found a way to specifically allow my IP address.
