### ISSUE TITLE
bug: Terminating app due to uncaught exception

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#292]
_From @ziobudda on March 7, 2015 1:20_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi all, when I try to "run" my app for my iphone4/ios7 via XCODE6/Yosemite I get this:

2015-03-04 01:18:43.879 FindYourItaly[512:60b] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIApplication 0x15672c90> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key view.'
*** First throw call stack:
(0x2e21cf4b 0x3865d6af 0x2e21cc61 0x2eb5c18b 0x2eb6ddd5 0x2e18ce6f 0x30ceef87 0x30cf07eb 0x30c0894b 0x309fa265 0x3099541f 0x30994721 0x309f9b3d 0x32e7870d 0x32e782f7 0x2e1e79df 0x2e1e797b 0x2e1e614f 0x2e150c27 0x2e150a0b 0x309f8dd9 0x309f4049 0xf3c9b 0x38b65ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException

What is this ? Where is my error?

On Android I have no problem.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3249_

**Comment by jbavari** [comment]
This appears to be a native error from one of the plugins you may be using.

You may find better answers looking into what plugin is crashing and posting an issue to the maintainers. They would be better suited helping you with your issue.
