### ISSUE TITLE
feat: Support svg as ressource type.

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#293]
_From @kristianbenoit on March 10, 2015 14:40_

**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>res.ionic.io only support 'psd', 'ai' and 'png'. psd and ai are proprietary and only have editor under Windows and OSX. There should be support for an open scalable format like svg which has editor on every platforms.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3273_

**Comment by exos** [comment]
Why close this issue? The best way to keep image quality after resize is the used of vectorized files, and the SVG is the standar format.

**Comment by chron0** [comment]
Agreed, I'd also wish there was at least one FOSS vector-format available and SVG has become pretty common and "web-ready" with inkscape grown into a great drawing tool. Resizing from pngs will always come at  a certain quality loss/compromise - which could be mitigated with SVG as a resource.

**Comment by kristianbenoit** [comment]
@jthoms1 is it done or wont be supported, why ?
