### ISSUE TITLE
feat: switching to nativescript

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#294]
_From @jonathanobino on March 9, 2015 13:18_

**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>are you planning to switch from cordova to nativescript ? https://www.nativescript.org/</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3258_

**Comment by jbavari** [comment]
For now, we will be sticking with Cordova due to the main integrations we have with Cordova and the native plugins that exist, are tested, and widely used.

**Comment by NathanWalker** [comment]
Just curious if this has been reconsidered (or at least revisited the thought) with the impressive integration the {N} team has done with Angular 2 in past 2 months even. 

Seems it would be amazing to have the choice to use Ionic with {N} or web views.

**Comment by DanailMinchev** [comment]
@adamdbradley @jbavari 

I was wondering the same: integration with NativeScript ..
It would be great if Ionic team has plans to integrate with NativeScript, this way it will be the best solution for me not only in WebViews world.
IMHO, currently (one year later) `React Native` and `NativeScript` are emerging as the new standard and if you look at [Angular 2 website](https://angular.io/features.html):

> 
> CROSS PLATFORM section
> 
> Learning Angular 2 gives you the tools you need to build apps for desktop, mobile web, Android, and iOS.
> Angular Universal provides for server-side rendering for fast initial views on mobile web.
> Ionic and NativeScript let you build hybrid and native UI mobile apps.
> Web worker support keeps your app UI fully responsive no matter how heavy the load.

So, are there any news about Ionic 2 + Angular 2 and NativeScript?

Thank you very much!

**Comment by gembin** [comment]
+1
Also interested in Ionic 2 + Angular 2 + NativeScript

**Comment by weupagency** [comment]
+1
I just saw that : https://www.nativescript.org/angular
It would be very awesome to be able to create a ionic-nativescript starter based on that project directly with the ionic cli.

**Comment by ciekawy** [comment]
I've found https://github.com/cjpearson/cordova-plugin-nativescript but it seems to not be actively developed. Anyway this seems to be interesting approach.

**Comment by volkrass** [comment]
I would suppose a complete different approach. Instead of switching to NativeScript a much natural fit from me would be to use react-native-render (https://github.com/angular/react-native-renderer). Ionic2 is heavily using Angular2, so in combination with react-native-render you can get the best of both worlds. Still using ionic but you can choose in which world your app lives (WebView vs Native Views).

**Comment by ciekawy** [comment]
@volkrass, does react-native-render offers same as nativescript or are there some differencies? here is some comment regarding this - there is also angular2-react-native mentioned :)
https://github.com/angular/angular/issues/3458#issuecomment-128156026

**Comment by jdnichollsc** [comment]
@adamdbradley @jbavari @NathanWalker @DanailMinchev @gembin @weupagency @ciekawy @volkrass https://github.com/proyecto26/nativescript-ionic-template

**Comment by jdnichollsc** [comment]
@adamdbradley @jbavari @NathanWalker @DanailMinchev @gembin @weupagency @ciekawy @volkrass People, I want to share a template I'm doing, any star or feedback is totally welcome, I hope you enjoy it! :D https://github.com/proyecto26/nativescript-ionic-template
