### ISSUE TITLE
Support a blank template that doesn't include documentation

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#296]
I like the blank template (https://github.com/driftyco/ionic-starter-blank) and frankly *need* the documentation inside, but consider adding a "blank-pro" template with the comments removed. Not all of them per se, but explanatory stuff that a decent Ionic dev wouldn't really need anymore.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
