### ISSUE TITLE
cli login fails when email contains upper case letters

### ISSUE THREAD

**Issue by DEllingsworth** [driftyco/ionic-cli#298]
If an account has an email such as FirstLast@gmail.com, you can login fine to ionic.io.  However, the cli will report 'invalid email or password' when you try to login; even if you use all lower case or exactly as entered into Ionic.io upon registration.

Workaround: Change your email in Ionic.io to be all lower case.

**Comment by jbavari** [comment]
@DEllingsworth - I see where this is happening. I'm on it.

**Comment by DEllingsworth** [comment]
This still seems to imply that the email is case sensitive when being compared server side. I think the code here is/was ok, but what ever is doing the actual validation should be doing a .toLowerCase() on the stored email look up for comparison.

**Comment by jbavari** [comment]
@DEllingsworth roger, we're on it.
