### ISSUE TITLE
"ionic serve" is too slow if too many files exist

### ISSUE THREAD

**Issue by lamrongol** [driftyco/ionic-cli#300]
I use ionic with Visual Studio and found  `ionic serve` becomes too slow.
The cause is Visual Studio generates too many files(>1000) when building, I confirmed the problem doesn't occur after deleting bin and bld folders.

I also confirmed this problem occurs without any relation to Visual Studio if there are too many files.

Of course, this is not an ordinary usage and not an urgent problem, I think.

**Comment by jbavari** [comment]
What is visual studio building?

Its my understanding that the ionic serve command only serves up the contents in the `www` folder. Is Visual Studio building files and putting them there?

If so, you may want to change that.

**Comment by lamrongol** [comment]
Ah, of course it will be solved if building files are put to other place, in my case.
Sorry, I meant to say, this problem will occur without relation to visual studio if a user put too many files by mistake, for example, http://forum.ionicframework.com/t/ionic-serve-is-very-slow/9017

Tentatively, only showing message "it takes long time because of too many files" would suffice, I think.
