### ISSUE TITLE
Re-install crosswalk?

### ISSUE THREAD

**Issue by lydell** [driftyco/ionic-cli#304]
Running `ionic browser add crosswalk@version` installs crosswalk just fine. It also adds crosswalk to "browsers" in ionic.project and "cordovaPlugins" in package.json. However, those seem never to be used. I'd expect the correct crosswalk version to be installed when `ionic platform add android` is run. Seems like hooks/after_platform_add/010_install_plugins.js needs to be updated. Right now, the only way to properly install a freshly cloned project seems to be to also run `ionic browser add crosswalk@version` again.

**Comment by jbavari** [comment]
@lydell - these hooks will be removed in the next release or so. 

Sorry for the inconvenience!

**Comment by jbavari** [comment]
@lydell Can you get latest and see if that fixes your issue?

**Comment by lydell** [comment]
I see that the hooks to save plugins to package.json as well as install plugins from package.json have been removed. Then what's the recommended way to save plugins? I've made a .sh file with a `cordova plugin add ...` line for each plugin needed for the project, which does the job.

I see that crosswalk is still added to "browsers" in ionic.project, but that information still seems not to be used, neither when `ionic platform add` nor `ionic run android` is run.

**Comment by lydell** [comment]
Possibly off-topic, but I also noticed that with the latest version having config.xml in www/ as opposed to in the project root seems not to be supported anymore. I don't know why it is in www/ in my project, but updating ionic was now a breaking change.

**Comment by lydell** [comment]
In 1.3.19 crosswalk is no longer added to "browsers" in package.json when running `ionic browser add`. Instead, `"android"` in "cordovaPlatforms" changes to:

```json
    {
      "platform": "android",
      "locator": "./engine/cordova-android-c0.6.1/"
    }
```

I've tried playing with the new `ionic state` command, and it is awesome. It just does not seem to handle crosswalk. The locator above refers to the ./engine directory, which does not exist until I run `ionic browser add ...`, which means that I cannot simple run `ionic state reset` after a fresh clone of my project.

**Comment by jbavari** [comment]
@lydell - This has been fixed in the latest beta. Try updating to get that beta and let me know if that works.

`npm install -g ionic@beta`.

**Comment by lydell** [comment]
I never got the chance to try the beta, but in 1.4.3, when I run `ionic state clear && ionic browser add crosswalk` the following is added to package.json:

```
  "cordovaPlugins": [
    {
      "locator": "engine/cordova-crosswalk-engine-c0.7.1",
      "id": "cordova-plugin-crosswalk-webview"
    }
  ],
  "cordovaPlatforms": [
    {
      "platform": "android",
      "locator": "./engine/cordova-android-c0.6.1/"
    }
  ]
```

So the problem does unfortunately not seem to be fixed ...
