### ISSUE TITLE
Installing crosswalk - cordova plugins getting removed

### ISSUE THREAD

**Issue by do-web** [driftyco/ionic-cli#305]
If i install crosswalk i must reinstall all cordova plugins

**Comment by jbavari** [comment]
@do-web have you tried doing the new cordova `--save` setting?

It will save all your current plugins to your config.xml file - then can restore them once done - see [this blog post](http://cordova.apache.org/news/2015/03/02/tools-release.html)

Snip: 
> You can now save your list of installed plugins and platforms using the --save command when adding platforms and plugins to your project. Saved platforms and plugins are automagically restored during prepare. Ex. cordova platform add android --save. This should make it easier developing cordova projects among a team.


If not, we can get something to help you alleviate these problems.

**Comment by do-web** [comment]
ok but ionic browser add crosswalk will re-add the android platform, so it is recommended that in the ionic cli you have to add the --save parameter

**Comment by jbavari** [comment]
I'm considering putting the --save parameter in there for `ionic platform` commands.

Thoughts?

**Comment by jbavari** [comment]
Closing. It's added in latest beta.
