### ISSUE TITLE
Ionic share became invalid

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#307]
This may be my fault, but I did 2 shares with one email address - I was testing to see if the CLI would recognize that I had already invited a person. (It did not.) I just clicked on the invite and I was told it was invalid. I'm wondering if it is because I did two shares. I can easily see someone forgetting that they invited, or just doing a second/third invite anyway, and in those cases, I don't think the initial invite should become invalid. (Again though I'm just guessing thats why my invite became invalid.)

**Comment by cfjedimaster** [comment]
Ok, my second email just came in, and neither link works.

**Comment by cfjedimaster** [comment]
Ok wait - the second link DOES work - but not if you are already logged in apparently. I'm logged in as my main ionic.io account and that confused the invite logic. Imo, it should work even if I'm already logged in as the person who sent it. It may be dumb for me to invite myself, but it should still work.

**Comment by larpo1** [comment]
same problem
