### ISSUE TITLE
Signing a release android apk fails on Windows

### ISSUE THREAD

**Issue by jkirsch** [driftyco/ionic-cli#316]
I noticed a problem building a release apk on Windows while entering the keystore password.

Issuing `ionic build --release` works up to the point of entering the password

```
-release-prompt-for-password:
    [input] Please enter keystore password
```

Here the console input is not directed to the ant input task and blocks forever.

If I just run `cordova build --release` it works, which leaves me to think that the stdin is used by ionic and not forwarded to the child task. 

ionic info output

> Your system information:
>
> OS: Windows 7 SP1
> Node Version: v0.12.0
> Cordova CLI: 4.3.0
> Ionic CLI Version: 1.3.16

**Comment by yutaihara** [comment]
me, too.

OS: Mac OS 10.9.5
Node Version: v0.10.35
Cordova CLI: 4.2.0
Ionic CLI Version: 1.4.3

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
