### ISSUE TITLE
Custom path for the lib

### ISSUE THREAD

**Issue by samouss** [driftyco/ionic-cli#318]
Hello,

In my ionic project, I updated the project architecture.
So i move the ionic dependency (`www/lib`) to another folder, but I still want use the ionic-cli and the `ionic lib` command.

Is it possible to add a config option for specific path to the lib ?

```json
{
  "name": "myApp",
  "libPath": "path/to/lib/folder
}
```

**Comment by jthoms1** [comment]
I believe that we are going to keep the structure as is.  Thanks for opening the issue but we think that this convention is important to keep.
