### ISSUE TITLE
Cannot listen to 0.0.0.0

### ISSUE THREAD

**Issue by Maistho** [driftyco/ionic-cli#322]
Ionic-cli seems to listen to the localhost interface only as default for me.
I can set the address to my local IP using `ionic serve --address <my-local-ip>`, but using 0.0.0.0 just gives me the following message:
```
$ ionic serve --address 0.0.0.0
Address 0.0.0.0 not available. (CLI v1.3.16)

Your system information:

OS: /bin/sh: lsb_release: command not found 
Node Version: v0.12.0
Cordova CLI: 4.1.2
Ionic CLI Version: 1.3.16
```

**Comment by jbavari** [comment]
Aha - see what's causing this.

I'll get it patched up soon. Thanks for reporting.

**Comment by cef62** [comment]
Yep I'm having same issue. There are workaround waiting for the fixed version?

**Comment by marcosinger** [comment]
I was fighting with this issue too.
My workaround was add this line on my Dockerfile:

```bash
sed -i 's/localhost/0.0.0.0/' /usr/lib/node_modules/ionic/lib/ionic/serve.js
```

**Comment by marcosinger** [comment]
see https://github.com/driftyco/ionic-cli/issues/331

**Comment by jbavari** [comment]
Thanks for the help responding, @marcosinger 

The beta version of the CLI fixes this with `ionic serve --all`

`npm install -g ionic@extlib`

**Comment by marcosinger** [comment]
@jbavari  :heart:
