### ISSUE TITLE
Build Failed with Crosswalk and PushPlugin

### ISSUE THREAD

**Issue by neeg** [driftyco/ionic-cli#323]
Hi, 

sadly my build failed with com.phonegap.plugins.PushPlugin and Crosswalk

```
BUILD FAILED

Total time: 47.356 secs

/Users/mayer/apps/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /Users/mayer/apps/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/mayer/apps/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
```

```
Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.16
Xcode version: Xcode 6.2 Build version 6C131e
ios-sim version: 3.0.0
```

**Comment by jbavari** [comment]
This might be related to some of the flags being passed to gradle.

It looks like the `cdvBuildDebug` flag is causing some issues. I'll look into this.

**Comment by neeg** [comment]
Some other guys have the same problem. See here:
http://forum.ionicframework.com/t/reporting-bug-crosswalk-issue-with-other-plugins/18028

**Comment by jbavari** [comment]
@neeg Thanks for reporting this.

At a quick glance, it looks like the plugin authors haven't updated the plugin to work with other webviews than the default one. In this case, the XWalkWebView. 

This is more an issue to be handled from the plugin authors. Closing for now.

**Comment by kcedric** [comment]
Any update on this ?

**Comment by kcedric** [comment]
For the ones interested, I managed to solve this issue by changing my build.gradle file.
Change this :
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar') ...}
To
dependencies {
    compile fileTree(dir: 'libs', include: 'gcm.jar') ...}

The * was making gradle to take all the libs in the folder which was including android-support-v13.jar as well.
As Pushplugin uses support-v4 there was an incompatibility.
So now only support-v4 is included and it's ok.

**Comment by prisonier** [comment]
@kcedric this solution is not working for me. How can I use push notifications with ionic if Ionic relies on a not up-to-date dependencies ? I don't understand why this issue is closed.
