### ISSUE TITLE
Ionic add command fails when dependency has conflict version

### ISSUE THREAD

**Issue by samouss** [driftyco/ionic-cli#324]
`ionic add` command fails when the component has a dependency with a version conflict.

```js
bower                                 ECONFLICT Unable to find suitable version for angular
Failed to find the bower component "<component name>".
```

**Comment by jbavari** [comment]
@samouss - can you put more information?

Try running `ionic info` and pasting that information.

Also, what command did you type exactly? `ionic add <what_went_here>` ??

**Comment by samouss** [comment]
I updated the CLI and the problem seems to be disappeared.

Thanks.
