### ISSUE TITLE
ionic upload error, no ID generated.

### ISSUE THREAD

**Issue by nileshlg2003** [driftyco/ionic-cli#325]
Hi,
I am trying to upload my ionic app using "ionic upload " command, after login succcessfull, it says uploading app.. but then nothing happens. No ID genered or upload successful message. I also checked my ionic.project file but app.id field is blank.
SO I was wondering if I have to create some ID and then upload or it only works with the app created with ionic creator? Is there any guideline or instruction on how to do it, that could help me solve this issue?
![ionic](https://cloud.githubusercontent.com/assets/4803667/6797002/9cf2e602-d215-11e4-8b5b-73dc1078ea0c.jpg)

**Comment by cfjedimaster** [comment]
I had the same thing. I think you hit the same issue I did. If you do not add a platform, then upload silently fails. The CLI should notice the lack of a platform and tell the user. (If this is NOT your issue, let me know and I'll file a new ticket.)

**Comment by nileshlg2003** [comment]
@cfjedimaster I think its not the same because I did add android platform before as well as after running upload command. For more info, I checked my proxy settings in environment settings and works fine too. Does it have some thing to do with Ionic CLI version? I use CLI version 1.3.18.

**Comment by cfjedimaster** [comment]
I'm on an Alpha. I'll go ahead and log a new bug so as to not interfere with yours!

**Comment by bradlund** [comment]
Do you have any other command windows open with ionic commands active?  I ran into this behavior when i had "ionic serve" running in one window. When I ran "ionic upload" while serve was running, i just saw "Uploading app..".   When i stopped serve and then ran upload, it reported the ID.

**Comment by cfjedimaster** [comment]
I honestly don't remember.

On Tue, Apr 7, 2015 at 11:58 AM, bradlund <notifications@github.com> wrote:

> Do you have any other command windows open with ionic commands active? I
> ran into this behavior when i had "ionic serve" running in one window. When
> I ran "ionic upload" while serve was running, i just saw "Uploading app..".
> When i stopped serve and then ran upload, it reported the ID.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-cli/issues/325#issuecomment-90646006>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by nileshlg2003** [comment]
I had only one command windows open (Just tried again), still same issue.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
