### ISSUE TITLE
ionic setup sass failure

### ISSUE THREAD

**Issue by mrpenguin** [driftyco/ionic-cli#326]
I got this series of errors when running the command: 

C:\Work\GitRepos\Mobile-Ionic>ionic setup sass
npmWARN package.json kaleidacare@1.0.0 No README data

> node-sass@0.9.6 install C:\Work\GitRepos\Mobile-Ionic\node_modules\gulp-sass\n
ode_modules\node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.

C:\Work\GitRepos\Mobile-Ionic\node_modules\gulp-sass\node_modules\node-sass>node
 "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Work\GitRepos\Mobile-Ionic\node_modules\gulp-sass\node_modules\n
ode-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\GitRepos\Mobile-Ionic\npm-debug.log

Error running npm install

**Comment by mrpenguin** [comment]
Now that I have set up Python and set the environment variable, I am getting the following error: 
C:\Work\GitRepos\Mobile-Ionic>npm install
npm WARN package.json kaleidacare@1.0.0 No repository field.
npm WARN package.json kaleidacare@1.0.0 No README data
\
> node-sass@0.9.6 install C:\Work\GitRepos\Mobile-Ionic\node_modules\gulp-sass\n
ode_modules\node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.

C:\Work\GitRepos\Mobile-Ionic\node_modules\gulp-sass\node_modules\node-sass>node
 "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn C:\Python34 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046
:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Work\GitRepos\Mobile-Ionic\node_modules\gulp-sass\node_modules\n
ode-sass
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\GitRepos\Mobile-Ionic\npm-debug.log

**Comment by jbavari** [comment]
@mrpenguin 

In your ionic app's package.json file - try changing out this:

From:

"gulp-sass": "^0.7.1",
To:

"gulp-sass": "^1.3.3",
Let me know if that works to solve your issue.

**Comment by mrpenguin** [comment]
Yes, that did fix it. Thanks so much.
