### ISSUE TITLE
Set a default browser to open with `ionic serve`

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#328]
_From @jbavari on March 20, 2015 20:54_

Let the user set a default browser (chrome, safari, firefox) when using the `ionic serve` command.

Maybe something like `ionic serve -f safari` 

That way whenever they run `ionic serve` it goes with their default unless they specify a browser with `-b`.

_Copied from original issue: driftyco/ionic#3367_

**Comment by perrygovier** [comment]
_From @rikvanderkemp on March 20, 2015 21:7_

Would it be possible to add an attribute to the ionic.project file as well? 

    {
        .....
        "serve" :  {
           "defaultBrowser" :  "chrome"
       }
        .....
    }

**Comment by perrygovier** [comment]
_From @jbavari on March 20, 2015 22:19_

Yep, great suggestion.

**Comment by skotturi** [comment]
I would like to use this nifty feature, is the flag --d? -f?

**Comment by quoideneuf** [comment]
@skutturi - try adding a "default_browser" entry to ionic.project. That worked for me.

**Comment by lekhnath** [comment]
It would be great if it was mentioned in docs also. I was searching for the availability of this feature in this page `http://ionicframework.com/docs/cli/test.html`

**Comment by rbecheras** [comment]
I added it in my fork, you can check merge my pull request : https://github.com/driftyco/ionic-site/pull/271

**Comment by louisdoe** [comment]
so should we add 

"defaultBrowser":

or 

"serve": { 
    "defaultBrowser": 
}

to ionic.project ?

Thanks

**Comment by eljuanchosf** [comment]
Hi! I confirmed that simply adding `"defaultBrowser":"yourBrowser"` to `ionic.project` does the trick.

**Comment by raelb** [comment]
Hi,
Is it possible to add support for Firefox Developer Edition? (on Windows).
(C:\Program Files (x86)\Firefox Developer Edition\firefox.exe)

It's nice to use a browser that I don't usually use for this purpose, otherwise there is the frequent need to resize the browser window to mobile dimensions, then back again for browsing...
Thanks

**Comment by dafyk** [comment]
In Ionic2 project `"defaultBrowser":"yourBrowser"` can be placed in `ionic.config.json` file. There are also `--browser` and `--browseroption` command line parameters for ionic-cli but its unclear to me how to pass additional parameters for browser. I want to start Chromium.app with `--allow-file-access --allow-file-access-from-files` parameters

**Comment by Fakkio** [comment]
Hi,
upgrading to "ionic": "2.1.7" and to "@ionic/app-scripts": "0.0.42" seems have broken something. Default browser doesn't work anymore.

**Comment by RezaRahmati** [comment]
try `ionic serve -w {yourbrowser}`

**Comment by thewodros** [comment]
Ionic server lab in crome:

`ionic serve --lab -w "google chrome"`
