### ISSUE TITLE
1.3.17 potential interference with setup/build for Crosswalk

### ISSUE THREAD

**Issue by zarko-tg** [driftyco/ionic-cli#329]
We have a custom build system covering iOS, Android and Android Crosswalk. One of the things we do ourselves is generating app icon and splash screen images.

After updating the ionic-cli to 1.3.17 it is no longer possible to build for Crosswalk.

Without posting all the specifics of the build chain or output, here's what seems to be the error, either as a cause or a consequence: 
```
Checking Project & Icon
  ✗  No cordova platforms found. Make sure you are in the root folder of your Cordova project and add platforms with 'cordova platform add'
```

"ionic platform list" says:
```
Installed platforms: android
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ios
```
At this time I have no indication of the cause of the problem, might as well be on our side. But please keep this open until I dig in.

___
OS: Mac OS X Yosemite
Node Version: v0.12.1
Cordova CLI: 4.3.0
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.3.17
Xcode version: Xcode 6.2 Build version 6C131e 
ios-sim version: 3.1.1 
ios-deploy version: 1.4.0

**Comment by jbavari** [comment]
@zarko-tg - I think I know exactly what is going on. I'm super sorry you ran into this!

I'll get a hot fix out for you shortly. Can you downgrade to 1.3.16 in the meantime? `npm install -g ionic@1.3.16`

**Comment by zarko-tg** [comment]
No worries @jbavari.
I had to downgrade as soon as I noticed the issue.

**Comment by jbavari** [comment]
@zarko-tg - i pushed 1.3.18 - this should fix your issue. You asked to leave the issue open, so I'll open it back for you to close!

Let me know if that works for you.

**Comment by zarko-tg** [comment]
Thanks. I guess this addresses the reported issue since I don't get the same failure anymore. I am closing this even though the latest version (1.3.18) opened a different set of issues for me regarding the hooks, plugins, etc, etc...
Need to look at the changes related to "resources" as well.
By the time I get some free time to investigate and accommodate to the aforementioned I'll be staying on 1.3.16.

**Comment by jbavari** [comment]
What did you mean, the issues with hooks and plugins?

In the latest build, I've got a task to remove those old plugin hooks. The plugins should be un-affected by that.
