### ISSUE TITLE
Viewing ionic serve from network

### ISSUE THREAD

**Issue by DominikVogt** [driftyco/ionic-cli#331]
So i updated my ionic CLI and now i cannot access the ionic server from outside my computer.

Ionic CLI is out of date:
 * Locally installed version: 1.3.11
 * Latest version: 1.3.17

Before i was reaching the server from my iphone, but now i cannot view it anymore. On 1.3.11 it was enabled. What do i need to configure?

**Comment by jbavari** [comment]
What I did was made the serve command focus on a specific address instead of listening to all addresses on `0.0.0.0`.

What address are you choosing to run the server at? If you're running and listening only to `localhost`, then your phone wont be able to see it.

Does `ionic serve --addres 192.168.1.101` with your IP entered allow it to keep working?

**Comment by DominikVogt** [comment]
This doesnt fix the problem.

**Comment by christophermiles** [comment]
I'm also having this problem after updating Ionic CLI. I used to be able to use my phone to access Ionic projects being served locally by pointing my phone's browser to the IP address of the machine running the Ionic server (eg. 192.168.1.X:8100) but with the new CLI this no longer works.

**Comment by marcosinger** [comment]
+1

**Comment by Hebbian** [comment]
No fix yet?

**Comment by jbavari** [comment]
Currently in the beta release for 1.4.0, there will be an option to serve on all addresses. 

`ionic serve --all`

Try it out - `npm install -g ionic@extlib`

**Comment by marcosinger** [comment]
works like a charm!
:clap:

**Comment by zjx** [comment]
npm install -g ionic@extlib
ionic serve --all
this works fine!

**Comment by raynoppe** [comment]
Ionic 4 with Angular 7/8 use:

ionic serve --address=0.0.0.0 
or if you want to change the port as well
ionic serve --address=0.0.0.0 --port=8102
