### ISSUE TITLE
ionic resources behind proxy

### ISSUE THREAD

**Issue by phearme** [driftyco/ionic-cli#335]
`ionic resources` doesn't seem to work on my side behind proxy. to make it work, I have to prefix the command with proxy information : 

`PROXY=http://myProxy:port ionic resources`

note that my `/.ionic/ionic.config` file does contain the correct information on my proxy.

**Comment by jonmikelm** [comment]
Duplicated:
https://github.com/driftyco/ionic-cli/issues/290

**Comment by jbavari** [comment]
@phearme I'm sorry you are dealing with this! The way you are stating (by passing PROXY information before the command) is how I understand it is supposed to work.

You can also [set up an environment variable](https://github.com/driftyco/ionic-cli#working-around-proxies) to avoid placing it before every command.

To my knowledge, the proxies specified in the `ionic.config` file focus on serving through a proxy, not so much as specify your proxy information.

Just a FYI - this article helped me understand how npm uses proxies:

http://jjasonclark.com/how-to-setup-node-behind-web-proxy/

Would you post the contents of your ionic.config file?

**Comment by phearme** [comment]
@jbavari thanks for your answer. my environment is already set up with proxy. also, here is the content of my ionic.config:
`
{
  "ank": "xxxxxxxx",
  "versionCheck": 000000000,
  "ionicServeAddress": "localhost",
  "proxy": "http://myproxy:3128",
  "https-proxy": "http://myproxy:3128",
  "newsId": 1,
  "accountPrompt": "y"
}
`

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
