### ISSUE TITLE
feat: Support for Chocolatey Package Manager

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#336]
_From @Purus on March 27, 2015 7:16_

**Type**: <span ionic-type>feat</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Chocolatey is a package manager for windows. It can help us to setup Ionic CLI.

Windows 10 is going to use Chocolatey in its OneGet Package for package management.

https://chocolatey.org/</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3420_

**Comment by jthoms1** [comment]
I believe that we will be staying with NPM for the foreseeable future.
