### ISSUE TITLE
short version of --livereload-port not working

### ISSUE THREAD

**Issue by leonprou** [driftyco/ionic-cli#337]
If I try:  `ionic emulate -l -r 35730 ios'`, the port is changing to 35730 but I've got a

> ionic $ Unknown platforms: 35730

When I giving the full syntax i.e. `ionic emulate -l --livereload-port 35730 ios` it is working as supposed.

Also, there's some inconsistencies between the website [docs](http://ionicframework.com/docs/cli/run.html) and the output of `ionic help emulate`.

Difference I've found:
 > ionic emulate ios [options] 
> ionic emulate [options] <PLATFORM>

and
>  [--livereload-port|-r] 
>  [--livereload-port|-i] 

(I tried also -i but it didn't help)

OS: OS X
Node Version: v0.12.1
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.18

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
