### ISSUE TITLE
bug: ionic emulate ios shows white/basic screen

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#338]
_From @Icehunter on March 30, 2015 19:43_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>When I use:

"ionic serve" (browser based) it works fine.
"ionic emulate ios -l" works fine.
"ionic emulate ios" does not work.
"ionic run android" does not work.

What I see on android is a white screen, and when I press the hardware back button it flashes the blue background I have.

What I see on iOS is that the screen shows the login button and a image placeholder but it does not load anything else at all and buttons fail to function.

Everything was working fine up until we went home last Friday. This issue is now presenting itself to other developers and it was after we removed the platforms and re-added them back with the cli that this affected them.

Is there any information I can provide that would assist with an investigation or something private that can be discussed as the application is not public.

Ironically if I use the starter apps it just works fine.

Plugins:
org.apache.cordova.device
org.apache.cordova.console
com.ionic.keyboard
org.apache.cordova.globalization
org.apache.cordova.inappbrowser
org.apache.cordova.statusbar

Between the time we had it working just fine on fresh clones and this morning there have been no code changes to the repo.

I appreciate your time and thanks!</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3434_

**Comment by Icehunter** [comment]
I think I might have narrowed it down.

```javascript
$rootScope.$on('$stateChangeStart', function (event, next) {
    if (next.data) {
        var authorizedRoles = next.data.authorizedRoles;
        if (!AuthService.isAuthorized(authorizedRoles)) {
            event.preventDefault();
            if (AuthService.isAuthenticated()) {
                $rootScope.$broadcast(AUTH_EVENTS.notAuthorized);
            }
            else {
                $rootScope.$broadcast(AUTH_EVENTS.notAuthenticated);
                $window.location.href = $window.location.origin + '/#/login';
            }
        }
    }
});
$rootScope.$on('$stateChangeSuccess', function (event, next, toParams, from, fromParams) {
    $rootScope.$previousState = {
        from: from,
        fromParams: fromParams
    };
    if (AuthService.isAuthenticated()) {
        if (next.name === 'login') {
            if (from.name) {
                $state.go(from.name, fromParams);
            }
            else {
                $state.go('app.feed');
            }
        }
    }
    else {
        $window.location.href = $window.location.origin + '/#/login';
    }
});
```

The $window is breaking it; login is not part of the app.X router and just lives at /login. If I use $state.go('login'); it will now work on the devices but it won't update the actual location path. 

Is that a moot point as the customer will never see it and or is that expected behaviour when using the $window variable?

**Comment by jbavari** [comment]
@Icehunter I'm struggling a little to follow (bear with me, i'm a slow learner).

Is the question about this breaking the emulate/run commands?

Regarding your last question - this may be a moot point. The users wont see the address bar on the device.

**Comment by Icehunter** [comment]
It was appearing at the time that $window was not accessible where I was using it in the change events. It would cause a white screen. I solved it by just not using it.

**Comment by YonasBerhe** [comment]
I'm getting a white screen error as well. Willing to share any info to get this app running on my emulator for IOS.
