### ISSUE TITLE
bug: Capitalise icon resources generated for iOS

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#339]
_From @romainfrancez on March 29, 2015 22:32_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>cli</span>

<span ionic-description>When generating the resources with the command `ionic resources` iOS icons names are generated with a lowercase `i`. However iOS apps expect the name to be with an uppercase `i` e.g `Icon.png`.

I can take care of the fix as it seems small.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3428_

**Comment by jthoms1** [comment]
It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
