### ISSUE TITLE
Ion-checkbox wrongly showing selected in collection-repeat

### ISSUE THREAD

**Issue by nvashish123** [driftyco/ionic-cli#340]
As described in the forum here -

 http://forum.ionicframework.com/t/ion-checkbox-wrongly-showing-selected/19914

The collection-repeat items list shows the checkbox pre-selected wrongly, when an item is deleted from the list.

here is the pen - http://codepen.io/anon/pen/yywwxN

**Comment by jbavari** [comment]
This issue was moved to driftyco/ionic#3435
