### ISSUE TITLE
Ionic upload w/o platform silently fails

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#341]
If you do ionic upload and do NOT have a platform yet, the CLI says your app has uploaded but it actually silently failed.

**Comment by jbavari** [comment]
When I follow these commands, it appears to work:

```
ionic start uploader
cd uploader
ionic upload
# *log in with ionic login*
```

For me, that works great. I see my app in the dashboard as well with the app ID it shown after the upload.

What am I doing differently than you to make it fail?

**Comment by cfjedimaster** [comment]
I just tested and it worked, so, not sure what to say. I can definitely confirm it was NOT working right for me.

**Comment by jbavari** [comment]
@cfjedimaster Going to close for now unless we can confidently reproduce this.
