### ISSUE TITLE
Cordova Crosswalk - error after ionic and Android SDK udpate. Plugin doesn't support this project's cordova-android version. 

### ISSUE THREAD

**Issue by manfromshadow** [driftyco/ionic-cli#342]
I Just updated Android SDK and the Ionic dependencies in my app.

After the running command:
```
cordova build android
cordova run android
```
I get this error message:
```
Plugin doesn't support this project's cordova-android version. cordova-android: 3.7.1, failed version requirement: >=4.0.0-dev
I tried to change target SDK value in AndroidManifest and config back into SDK v. 19, but without luck.
```
I tried also add new crosswalk using :
```
 ionic browser add crosswalk 
 and then
 cordova platform add android, but after cordova run i always get same error message.
```
How can i solve this issue please?

Thanks for any help.

Ionic info:
```
OS: Mac OS X Yosemite
Node Version: v0.12.0
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.18
Xcode version: Xcode 6.2 Build version 6C131e 
ios-sim version: 3.1.1 
ios-deploy version: Not installed
```

**Comment by jbavari** [comment]
What is your output when you try:

`ionic platform ls`?

It looks like the `ionic browser add crosswalk` command isnt properly adding the Cordova android 4.0 version that is required.

You might try this:

Remove the android platform:
`ionic platform rm android`

Get the directory name for the cordova android 4.0 version (ex cordova-android-c.0.50):
`ls ./engine`

Then add the platform with the path from the `ls` command:
`ionic platform add ./engine/cordova-android-c0.5.0`

That should give you the 4.0.0 version it is requiring from the cordova crosswalk engine plugin.

Otherwise, to start over - try `rm -rf engine platforms plugins` - then running `ionic browser add crosswalk`.

**Comment by pencilcheck** [comment]
I'm getting this error as well, no matter how many times I do `rm -rf engine platforms plugins` whenever I try to reset platforms using cordova commands like `cordova platform add android` I will always get this error.

**Comment by jbavari** [comment]
Can you supply me some more information?

First off, what is the output from `ionic info`?

What are the contents of your `package.json` file?

Do you have any directories/files in the `hooks` directory?

**Comment by pencilcheck** [comment]
@jbavari I figured out that `cordova platform add android` will create android not from modified cordova-android but the stable version on npm. I noticed that `ionic browser add crosswalk` adds the platform for you using the downloaded modified android-cordova plugin in the engine folder. So this is an ionic-cli issue where it doesn't explain or at least shows the users what's really going on.

**Comment by shuyye** [comment]
Is the installation different in windows? I'm battling for hours with this, I don't get how to add the platform from the engine folder either... No matter what variation I enter, it always says 'cannot read property icon of undefined'.
I have the latest cordova version, and it keeps on saying that the cordova-android version is 3.7.1 when I try 'ionic add platform android' and it cannot be installed... Any ideas? Please!

**Comment by jbavari** [comment]
@shuyye the installation is the same on windows.

To add the platform from the engine folder, try: `ionic platform add ./engine/cordova-android-c0.6.1`.

Otherwise, just try running `ionic browser add crosswalk` or `ionic browser remove crosswalk`.

**Comment by sidchilling** [comment]
So should I be using the command `ionic platform add android` or not? Because this uses the stable android version and not the crosswalk engine. On the other hand, this works `ionic platform add ./engine/cordova-android-c0.6.1`
