### ISSUE TITLE
Feature Request: goto state

### ISSUE THREAD

**Issue by kirrg001** [driftyco/ionic-cli#347]
hey,

goto 'state' does not work, only goto url. 
i need to translate my state into url. 

close the ticket if not relevant to you or if goto state already exists (then tell me how :+1: )

thanks!

**Comment by jbavari** [comment]
@kirrg001 currently the way the `goto` command works is by sending a request to the server that the browser reads from inline javascript. That javascript that runs has no access (currently) to the angular context to get the states.

As of right now, I don't think this will be a priority for us to add in.
