### ISSUE TITLE
Bug: goto does not work if page not found

### ISSUE THREAD

**Issue by kirrg001** [driftyco/ionic-cli#348]
hey,

if i type in

````
goto /something/else
````

browser shows me URL ... not found. which is correct.
ok fine, wrong syntax. then i do:

````
goto /#/something/else
````

goto does not work anymore. does not react.

if this is a duplicate, close me.

thanks,
kate

**Comment by jbavari** [comment]
@kirrg001 this seems to be working fine for me. 

If you'd like more help, please run `ionic info` and post that information here, and re-open the issue with more output.

As of version 1.3.22, the goto command is working.
