### ISSUE TITLE
bug: Stretched splashscreen on Moto X when using resources generator

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#350]
_From @kaumac on April 2, 2015 4:24_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi there! I'm using the cli tool to generate both splashscreens and icons for my app. I followed every instruction for the dimensions of the images and everything is working perfectly, except for the splashscreen specifically on Moto X. On moto x the splashscreen is stretched to the sides (the icon works just fine tough). On iOS emulator, Android Emulator em Galaxy S4, both splashscreen and icons works just fine.

The image as you can see in the screenshot is 2208x2208 and the main content centered inside it has a 1200x1200 area. I really don't know what it can be. Can anyone confirm this?

![captura de tela 2015-04-02 as 01 21 48](https://cloud.githubusercontent.com/assets/1170740/6957736/b998ca3e-d8d6-11e4-8059-9ec9d2b1c01d.png)

</span>

<span is-issue-template></span>

Edit: I tested it on android 4.4 and 5.0.2

_Copied from original issue: driftyco/ionic#3456_

**Comment by mhartington** [comment]
@kaumac is the image being used a png?

**Comment by kaumac** [comment]
@mhartington it is a png file

**Comment by kaumac** [comment]
Here is how it looks on Moto X
![screenshot_2015-04-04-20-18-15](https://cloud.githubusercontent.com/assets/1170740/6995090/1740b1c8-db08-11e4-99be-d947c1516764.png)

**Comment by aliocha** [comment]
Same problem on Nexus 4

**Comment by mhartington** [comment]
Hmm, seeing this two, but have isolated it to only a issue for png images. Will look at the server side code for this

**Comment by kaumac** [comment]
@mhartington isn't .png the only valid format? I tried with jpeg but it doesn't work

**Comment by mhartington** [comment]
Nope, png, .ai, .psd are supported formats

Mike Hartington

**Comment by kaumac** [comment]
So, I tried with a .psd and got the same result. I can't confirm about .ai because I don't have illustrator here

**Comment by AlexYankee** [comment]
Same thing for nexus 4 (768x1280). Tested in Genymotion.

**Comment by Edwardzyc** [comment]
Having the same issue here for nexus 5

**Comment by FdezRomero** [comment]
Same here with a .png made in Sketch, similar to @kaumac.

**Comment by youssmak** [comment]
Same issue with a Moto G, 4G, First generation

**Comment by mhartington** [comment]
If you install the splashscreen plugin from github, you could try this

`<preference name="SplashMaintainAspectRatio" value="true|false" />`

**Comment by dotenorio** [comment]
@mhartington Solved for me, thanks!

**Comment by kaumac** [comment]
It works! Thanks a lot @mhartington :smile:

**Comment by Edwardzyc** [comment]
Why isn't this pulled into ionic resources though?

**Comment by kaumac** [comment]
As I understand it, Ionic Resources just processes the images in Ionic servers and the workaround suggested by @mhartington depends on a plugin, I think this is the reason.

This info could be more clear in resources docs though, it would be definitely helpful for new users.

**Comment by mhartington** [comment]
Yeah, the splashscreen plugin handles all the splashscreen logic now, so things like this will require it be added. See what I can do about getting the splashscreen in as a default plugin and adding the aspect ratio config in there as well. Closing this for now.
