### ISSUE TITLE
Crosswalk 12 whitelist issue (Url blocked even allowing * in config.xml)

### ISSUE THREAD

**Issue by luofan189** [driftyco/ionic-cli#352]
Hi,
I added crosswalk@12 to the android project, it builds fine except that I am getting 404 and Url blocked by errors when accessing a server. I have the access whitelist origin="*"  in config.xml.  If without the crosswalk, the app could access the server properly but of course the performance is bad. Anybody encounters this as well? How could I fix it? Thanks!

**Comment by aliocha** [comment]
Same problem here, after 3 days of headache, i found that the ionic-cli v1.4.0-alpha.5 works well to add crosswalk.

**Comment by b8rother** [comment]
:+1:

**Comment by luofan189** [comment]
Thanks for all the replies. I will give a try today and confirm if this is an issue of 1.3.19 or not.

**Comment by jbavari** [comment]
@luofan189 - you can specify a different version of crosswalk.

List versions:

`ionic browser ls`

Then:

`ionic browser add crosswalk@11.40.277.7`

**Comment by luofan189** [comment]
I think I could confirm this is an issue of 1.3.19. I used 1.3.19 with crosswalk@11, it has the same issue. I reverted ionic-cli to 1.3.18 and added crosswalk@11, the issue is gone. I think @aliocha already confirmed that 1.4.0-alpha5 fixes this issue, so I will close this issue for now.

**Comment by aliocha** [comment]
I tried every versions of crosswalk with ionic-cli 1.3.19, sama result. The problem is not crosswalk but the way to install and configure it (ionic-cli)
