### ISSUE TITLE
ionic build ios generates wrong XCode productType

### ISSUE THREAD

**Issue by buunguyen** [driftyco/ionic-cli#353]
In config.xml, I set app name (i.e. `<name>`) to "test", then run `ionic build ios`. The build fails with this error:

```
target specifies product type 'com.testle.product-type.testlication', but there's no such product type for the 'iphonesimulator' platform
```

Looking into the generated `project.pbxproj`, I see the followings:

```
name = "test";
productName = "test";
productReference = 1D6058910D05DD3D006BFB54 /* test.test */;
productType = "com.testle.product-type.testlication";
```

If I change `<name>` to "app", the build would work, and the `project.pbxproj` looks like this:

```
name = "app";
productName = "app";
productReference = 1D6058910D05DD3D006BFB54 /* app.app */;
productType = "com.apple.product-type.application";
```

It looks like the CLI takes the app name and does a string replace to everything, causing all the occurrences of "app" inside `productType` to be replaced with "test".

Please help investigate. 

*Env info:*
OS: Mac OS X Yosemite
Node Version: v0.10.36
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.19
Xcode version: Xcode 6.2 Build version 6C131e
ios-sim version: 3.1.1
ios-deploy version: 1.4.0

**Comment by jbavari** [comment]
Yes. Cordova is a generator that generates those various files for ios/android. That's intended, hence the `<name>` attribute in the config.xml goes to both android manifest and the `pbxproj` file.

**Comment by stuartford** [comment]
While this may be true, the OP left out the bit about the iOS build failing if the app name is set to anything other than "app". I can reliably reproduce this. "app" - builds. Change it to something else, build fails. Change it back to "app", builds.
