### ISSUE TITLE
bug: Android + Crosswalk issue in 1.3.19

### ISSUE THREAD

**Issue by AlexYankee** [driftyco/ionic-cli#355]
Using CLI 1.3.19, after adding crosswalk browser on android, every http request to real world will get 404 (from cache).
Doesn't matter if it's ajax request, image download, whatever. You will always get 404 from cache.  
Tried to locate problem source by myself, but no luck. Maybe it's sort of permission thing, i don't know.
This bug doesn't exist in 1.3.10

Steps to reproduce:
```bash
$ npm update -g ionic (to be sure you have latest 1.3.19)
$ npm start --appname="Crosswalk test" --id="com.crosswalk.test" crosswalk_test && cd crosswalk_test
$ ionic platform add android
$ ionic browser add crosswalk@10.39.235.15
$ ionic run android
```
Crosswalk version is not a thing, same error with any other version
You will miss avatar images on Chats page because of this bug, you can prove that with Chrome Inspector.  
Tested with Genymotion and Android Emulator.  
 
Doing same steps with CLI 1.3.10 you will not get this error.

**Comment by clauderic** [comment]
I have the same issue, changing crosswalk versions did not help. Any input on this?

**Comment by lydell** [comment]
I have the same problem. I'll just stay with 1.3.18 for now.

**Comment by jonathandion** [comment]
I have the same problem.

**Comment by krik** [comment]
Also ran into this :(

**Comment by willnewii** [comment]
thx @krik  I'll just stay with 1.3.19. is OK ~

**Comment by jbavari** [comment]
The blog post for Crosswalk was updated to have instructions about the whitelist plugin:

http://blog.ionic.io/crosswalk-comes-to-ionic/
