### ISSUE TITLE
Provide --nogulp option to `ionic serve`

### ISSUE THREAD

**Issue by cbeams** [driftyco/ionic-cli#360]
The `gulpStartupTasks` property in `ionic.project` is an big help in ensuring that running an app locally "just works" with regard to starting watches behind the scenes (e.g. for sass), etc. Some developers on the team, however, may prefer to use IDE-based plugins to watch and process files while still wishing to use `ionic serve` for the http server, live reload, etc.

An `ionic serve --nogulp` option would allow these users to opt-out without requiring local changes to `ionic.project`.

Alternatively (or additionally), providing a mechanism to override properties in `ionic.config` via environment variables and/or in the user's `~/.ionic/ionic.config` file would provide a way to set this preference once and be done with it.

**Comment by jbavari** [comment]
@cbeams Great suggestion. I've added this. It should be rolling out in 1.4.0 tomorrow.

**Comment by cbeams** [comment]
Thanks, Josh.

**Comment by jvitor83** [comment]
@jbavari 
This should be allowed for v3 of CLI too.
