### ISSUE TITLE
Feature: Fork cordova-plugin-whitelist and include in Crosswalk add process

### ISSUE THREAD

**Issue by mattezell** [driftyco/ionic-cli#361]
Apparently, whitelist has been pulled out of Cordova into it's own plugin: https://github.com/apache/cordova-plugin-whitelist

I believe that this new plugin should be automatically added to the project, as it's a dependency - without which, --livereload doesn't work with Crosswalk.

I will be happy to create a branch and add the required 'ionic plugin add https://hithub...' code, but this currently lives at the above URL and isn't a registry.cordova.io resolvable plugin just yet...

I also was uncertain if it was desired that driftyco maintain a fork of this codebase (like some other related dependencies) or if merely adding the 3rd party library was acceptable.

Happy to assist, if someone would point me in the preferred direction.

Edit: credit due http://forum.ionicframework.com/t/crosswalk-integration-beta-in-ionic-cli-v1-3-2/15190/270

**Comment by jbavari** [comment]
@mattezell thanks for the input. I'll look at it today.

Regarding the whitelist plugin - the cordova team has been discussing releasing that very soon. I was hoping it had been released by now so we could not have to first have the CLI install the plugin via `http`.

This is a tough scenario - two ways I see it:

We can install it now via http and do a release, then when it goes on registry, we update the CLI and release. This would cause users to deal with those two plugins and how they were installed (http vs registry).

We can instruct users how to install the plugin now, and when the plugin is released, update the browser command and release for the registry version.

I'd rather wait for it to be released to install it and update the `browser`, so we don't have to change *again* once they release it.

What are your thoughts?

**Comment by mattezell** [comment]
Thanks, @jbavari!

Yeah, I agree completely - it would far be preferred that CLI just use the official registry for this plugin...   There'd be a lot less 'back and forth' required for the CLI project as well as developers using the intermediary http-plugin-release of CLI.

Admittedly, since we're now rocking into week 2 of this process having been broken, I'd kind of hoped that the whitelist plugin would have made its way into the repo by now...   But I know that things take time...   But just think of how many people have come across this blog post (http://blog.ionic.io/crosswalk-comes-to-ionic/) and the various other official Ionic Crosswalk mentions, tutorials and documentation pages who've walked away scratching their head and cussing at the hours lost chasing the blank screen issue stemming from the Whitelist Plugin split...  

And it is what it is - this is just part of the process.. But we all know that wrestling with these things leaves a bitter taste in people's mouths regarding the Ionic Framework.. Which is something that I hope to see and help Ionic avoid as much as possible at this phase in its life - as an increasingly popular and rapidly growing framework...  I mean, the framework has a lot of attention right now - it's safe to say that the Ionic Framework is currently at front and center stage for many medium to large corporate R&D initiatives as 'the new framework going forward' (I can attest to being part of one such initiative)...

Fortunately, I am seeing that since this all has become a bit more widely documented in forums threads and SO posts of late, that it's showing up a bit more in the related Google results.. So hopefully the amount of people leaving ultimately confused from this issue and cussing the framework as a result is a bit less than it was a week ago.

I guess my proposal for a stopgap answer would be: 
1) to update all official documentation and blog posts to include this info regarding the whitelist split so that people aren't left chasing their tails (I am trying to do my part by getting it in SO threads and the sort)
2) do as you've suggested and wait for the official repo release..  

How difficult would it be to get a note out there on the highest profile pages (I guess, the Blog post really being the top registering one - http://puu.sh/hcvmZ/e672753c54.png)? I feel that a simple addendum summarizing how to manually install the github plugin and how to add a sensible Content-Security-Policy to your index.html would go a long way to easing frustrations surrounding this temporary problem (which, to an extent, are often misdirected at Ionic).

**Comment by jbavari** [comment]
@mattezell You're absolutely on point.

Thanks for the insight as well, we really appreciate it. 

We'll be updating the blog post and getting a new one out with the communication you're suggesting. @mhartington and I will be coming up with some better documentation on the feature to help out to developers like yourself.

I'm on it now. Thanks again.

**Comment by mattezell** [comment]
Awesome!  You guys rock!

I really appreciate you guy's "can do", "we got this" attitude... While it's all of our responsibilities to maintain and enhance the open source projects that we love, unfortunately, a 9-to-5 doesn't leave as much time for this as we'd often like...  I contribute where I can, but often times, my primary mandate is "work around to get it out the door" first, "fix" second(after hours, in your freetime)... And this is often the bane of working with an open source solution in your 9-to-5 (which may be in a corp-type environment) - you just don't have time to code towards your project as well as write the library... Most of the time, that's why you picked a 3rd party open source lib to begin with...

I was assigned an exploratory Ionic Framework backed project a few months ago and I fell in love with not only the framework, but the ecosystem and community as well...  If I have anything to do with it, we will be using Ionic a lot going forward. I've encountered a lot of super heroes (like you guys) and very few trolls, which is always GREAT (and not always the case) when working with open source projects...  Since my first interaction with anyone in the Ionic community, it's been nothing but a vibe of positivity and helpfulness.

Since getting my feet wet, I've used Ionic everywhere that I can - it's been a breath of fresh air for me... Having previously fooled around with Cordova "vanilla" a couple of years back and then having later evaluated Mono as a "code once, deploy everywhere" solution for our org, the Ionic Framework has been a heavensent for me.  While I know that every solutions has its pros and cons, the enhancements that Ionic adds to the Cordova way of doing things has proven invaluable for myself and many others in the community.  

The Ionic Framework development process for hybrid apps is far superior to anything else out in this arena that I am aware of - and I truly do appreciate it and I appreciate all of the hard work that you guys do to make this a reality.

Please let me know if there's anything that I can do to be of assistance.

**Comment by jbavari** [comment]
@mattezell thanks again for the glowing reviews.

The blog post has been updated: http://blog.ionic.io/crosswalk-comes-to-ionic/

**Comment by jbavari** [comment]
@mattezell I shared your words with the team and everyone is very humbled by your words. We try our hardest to help developers - we all understand development is hard. Everyone on the team really appreciates your words of encouragement. It further drives our passion!

I'd love to get some more of your feedback on a few other topics I've known you've posted on and issues you've encountered. Please, shoot me an email - josh@drifty.com. Thanks again!

**Comment by mattezell** [comment]
Supafast!

If there's only one clarification that I would make, it would be to include something along the lines of "adding crosswalk to your project broke live reload" as well.. 

I believe that a lot of people who encounter this issue don't necessarily equate or relate this issue with "crosswalk not loading external resources"...  Not initially at least.. Personally, I had to take the long road around to get to that conclusion...

I believe the process for many to be: read the post, introduce crosswalk to your project, run your beloved 'ionic run -lcs android' command, see your app load as a white screen (grit your teeth), conclude that you've messed something up, remove crosswalk, retest and find that live reload works again, start back at the beginning of the crosswalk post taking care to read more slowly this time..., introduce crosswalk as documented again, 'fail' again, begin frantically searching to figure out how you've messed up (as crosswalk is clearly working - otherwise, why would have my pals at Ionic have taken time to write about it?!)... 

The rub finding it this way is that since Cordova is no longer loading ANY external resources, and so none of your app via the live reload server, you don't even get the first console message (terminal nor remote debugging) to indicate a possible cause (disclaimer: I've not checked logcat - possible Cordova would' have squawked it there, I suppose).

Now I am aware that everything is external when you're using live reload.. And so "Issues with Crosswalk not loading external resources" makes sense.. But I'd likely have scrolled right on past that 2 or 3 times before just trying it due to it containing the word "crosswalk" in the header...  

But I may also not be the sharpest pointy object in the pointy object box, so take this all for what it's worth...  Perhaps everyone's respective paths here could also be based on the maturity of our respective projects...  Mine still being very much in development and so live reload significant.. Theirs being more mature and less live reload dependent - at a phase that's more 'external resource significant'.  But that's just a guess.. 

Anywhos.. Just a suggestion...

---

Also, no thanks due to me - I'm the dude giving minimally, while using fully!  

All thanks go to you guys!    You guys deserve more credit and thanks than you get.. You've taken a valuable, but very difficult to use project (Cordova) and made it not only easy to use, but fun to use as well!  

I've just been along for the ride for just the past 6ish months (10/2014).. In this short time, people have gone from "Ioni-what?" to "Oh, yeah - I've heard a lot about that lately. How do you like it?" when I'm talking about what I'm working on...  

I'm pretty certain that you guys are altering the landscape of hybrid application development with the waves that you've been generating... 

So again - Thanks!   

I'd be happy to communicate some of my observations with you guys about the project and community - I'll drop you a line in the next day or so if that works.

**Comment by jbavari** [comment]
@mattezell since they haven't updated that plugin yet - I've gone and included it as the HTTP plugin request. It's in the beta `npm install -g ionic@beta`.
