### ISSUE TITLE
ionic build --release --device exits immaturely without signal BUILD SUCCEED for a clean build

### ISSUE THREAD

**Issue by luofan189** [driftyco/ionic-cli#362]
Not sure if this is ionic-cli bug or cordova-cli bug, I could move to cordova-cli if it is confirmed that this is not ionic-cli issue

ionic version: 1.3.18

Steps to reproduce:
1. ionic platform remove ios
2. ionic platform add ios
3. make sure no build folder is in platforms/ios
4. run ionic build ios --release --device
5. notice that build finishes without signal BUILD SUCCEED
6. run ionic build ios --release --device again w/o removing the platforms/ios folder
7. notice that build finishes with signal BUILD SUCCEED

This currently causes issue that after_build hooks are not triggered for the first run.

**Comment by luofan189** [comment]
Could somebody comment on this issue please?

**Comment by jbavari** [comment]
Is there any error output from the command? Or does it just not show 'BUILD SUCCEEDED'?

You might also try running `cordova build ios --verbose` - and see if that adds any more output that helps.

**Comment by laylaaitlaaraj** [comment]
same issue here does anyone found a solution?

**Comment by luofan189** [comment]
running cordova build ios works fine. I did see BUILD SUCCEEDED. I think this is a bug of ionic-cli

**Comment by briananderson1222** [comment]
:+1: Any word here?

**Comment by penrillian-chrisa** [comment]
FWIW I've just observed the same behaviour. The first "ionic build --release --device ios" didn't produce an IPA; the second one did.

**Comment by pbassut** [comment]
+1

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
