### ISSUE TITLE
Crosswalk lite?

### ISSUE THREAD

**Issue by pewh** [driftyco/ionic-cli#363]
When I compile APK using Crosswalk, the size is too big. I think using crosswalk lite will reduce the size of compiled APK. But I have no idea to hack ionic-cli to use [crosswalk lite](https://github.com/crosswalk-project/crosswalk-cordova-android/tree/crosswalk-lite).

My question is:
1. Will this support crosswalk lite?
2. Is there any hack (or temporary solution) to use crosswalk lite?

Thanks.

**Comment by wfsm** [comment]
+1

**Comment by piernik** [comment]
+1

**Comment by Stiveknx** [comment]
+1

**Comment by jbavari** [comment]
Hello all,

I've added this in the Ionic CLI beta.

Go ahead and try it out - `npm install -g ionic@beta`

`ionic browser add crosswalk-lite`

I can't promise it works 100%, since its marked as *experimental* from the Crosswalk team.

**Comment by Stiveknx** [comment]
It  builds, but doesn't run on any devices ...
logcat:
http://pastebin.com/TmSKUP22

Also, it's missing on ``browser list``

**Comment by jbavari** [comment]
I've added it to browser list, just hadn't pushed that out to beta. I'll do that here shortly.

As far as not running on any devices, I dont have any handy right now to run on other than the simulator im using, Genymotion. It's working just fine on that.

**Comment by johannds** [comment]
I'm keen to test this, please let me know when the beta goes out. We're having issues with Android 4.1.2 freezing up on older devices when textboxes get focus and I'm hoping for a miracle that this fixes the issue. I know it doesn't make an logical sense that it would fix the problem we're having, but I'm keen to try in any event.

**Comment by pewh** [comment]
I got same errors like @Stiveknx too although I use ionic starter & genymotion.

```
ionic start myApp tabs
npm install
bower install
ionic serve # <-- I test on browser & it's work
ionic browser add crosswalk-lite
ionic build android # <-- success to compile
ionic run android # <-- run on genymotion, and it's crash
```

I build with:

 - node v0.10.36
 - ionic 1.4.5
 - cordova 4.3.0

Plugin:

 - com.ionic.keyboard 1.0.4
 - cordova-plugin-crosswalk-webview 1.0.1-dev
 - cordova-plugin-whitelist 1.0.0
 - org.apache.cordova.console 0.2.13
 - org.apache.cordova.device 0.3.0
 - org.apache.cordova.splashcsreen 1.0.0

**Comment by jbavari** [comment]
@johannds Crosswalk lite is out in latest CLI version.

@pewh What happens when you replace `ionic` with `cordova` and run those same commands?

**Comment by pewh** [comment]
When I use `cordova`, it's work but the size of APK is not like crosswalk-lite. It seems `cordova` build with crosswalk although I use crosswalk-lite. Below is what I do:

```
ionic browser add crosswalk-lite
cordova build android  # <-- generate APK with size 20 MB
cordova  run android
```

and

```
ionic browse revert android
ionic browser add crosswalk-lite
cordova build android   # <-- still generate APK with size 20 MB
cordova  run android
```

**Comment by junkoro** [comment]
The browser.js of ionic cli 1.5.0 is ignoring version parameter and isLiteVersion parameter If you are cordova 5.0.x installed. ( https://github.com/driftyco/ionic-app-lib/blob/master/lib/browser.js#L453 )

Workaround: just comment L453.

This will install correct version of crosswalk. But, I tried crosswalk-lite, it's still over 20MB. I don't know why ┐(´д｀)┌

**Comment by janckerchen** [comment]
crosswalk-lite  dont reduce the size, confirm still above 20M for blank project

Cordova CLI: 5.1.1
Gulp version:  Requiring external module coffee-script/register
Gulp local:   CLI version 3.8.11
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: 1.4.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.1
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by ouani** [comment]
Would love an update on this issue :)..

**Comment by ffabreti** [comment]
+1

**Comment by ffabreti** [comment]
still an issue on Jul/2015
ionic info:
>Cordova CLI: 4.3.1
>Ionic Version: 1.0.1
>Ionic CLI Version: 1.5.0
>Ionic App Lib Version: 0.1.0
>OS: Distributor ID:	Fedora Description:	Fedora release 21 (Twenty One) 
>Node Version: v0.12.6

**Comment by cihadhoruzoglu** [comment]
+1

**Comment by souly1** [comment]
+1

**Comment by gaguirre** [comment]
+1

**Comment by souly1** [comment]
+1

**Comment by nicon-dev** [comment]
+1 same problem here...

**Comment by bleuscyther** [comment]
+1

**Comment by abdoutelb** [comment]
+1 i would love to see an apk less than 20 M

**Comment by sajjad-shirazy** [comment]
+1

**Comment by gerardcarbo** [comment]
+1

**Comment by ouani** [comment]
Why is this issue even closed ?

**Comment by dkro** [comment]
+1

**Comment by BojDom** [comment]
I made a tutorial of i succesfully integrated crosswalk-lite with an ionic project

http://stackoverflow.com/questions/35091350/crosswalk-lite-with-cordova

**Comment by abdoutelb** [comment]
a.telb@snap4soft.com

**Comment by cinder92** [comment]
+1

**Comment by lucasmendonca** [comment]
+1

**Comment by prijindal** [comment]
+1

**Comment by prijindal** [comment]
Found a solution
Instead of doing 
``` ionic plugin add cordova-plugin-crosswalk-webview ```

Do this

``` ionic plugin add cordova-plugin-crosswalk-webview --variable XWALK_MODE="lite" ```

**Comment by matheo** [comment]
@prijindal It installs nicely, thanks, but:
Have you checked if your app is running on Crosswalk as the [docs](https://crosswalk-project.org/documentation/cordova.html) says checking `navigator.userAgent`:
https://crosswalk-project.org/assets/cordova-with-devtools.jpg

Mine doesn't show Crosswalk :(
```
Mozilla/5.0 (Linux; Android 6.0.1; Moto G Build/MOB30M; wv) AppleWebKit/537.36
(KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36
```
I wonder if it's because I have Android 6 CM13

**Comment by vivek1729** [comment]
@prijindal, I followed your advice and Crosswalk-lite seems to be installed and configured as it reflects in `ionic.project` file. But no changes in `config.xml`. If I modify the `config` file as suggested by @matheo, I get a compilation error. Also, I tried compiling with the normal crosswalk and the lite version but the size of the `apk` output remains exactly the same. Has anyone else gotten this plugin to work successfully reducing their apk size?

My `ionic.info` yields:

     Cordova CLI: 6.0.0
     Gulp version:  CLI version 3.9.1
     Gulp local:   Local version 3.9.1
     Ionic Version: 1.2.4
     Ionic CLI Version: 1.7.14
     Ionic App Lib Version: 0.7.0
     ios-deploy version: Not installed
     ios-sim version: Not installed 
     OS: Mac OS X El Capitan
     Node Version: v5.3.0
     Xcode version: Not installed
