### ISSUE TITLE
crosswalk 14

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic-cli#364]
I want to use crosswalk browser with Google maps plugin.
Problem is that google maps needs crosswalk ver 14 - https://github.com/wf9a5m75/phonegap-googlemaps-plugin/wiki/Tutorial-for-CrossWalk-(Android)
ionic cli gives only 13
```
Available - Crosswalk - ionic browser add crosswalk
         Version 8.37.189.14 Published Fri Oct 10 2014 03:26:00 GMT+0200 (Środkowoeuropejski czas letni)
         Version 9.38.208.10 Published Tue Nov 25 2014 11:45:00 GMT+0100 (Środkowoeuropejski czas stand.)
         Version 10.39.235.15 Published Wed Dec 31 2014 13:16:00 GMT+0100 (Środkowoeuropejski czas stand.)
         Version 11.40.277.7 Published Thu Feb 26 2015 07:03:00 GMT+0100 (Środkowoeuropejski czas stand.)
         Version 12.41.296.5 Published Thu Mar 05 2015 13:19:00 GMT+0100 (Środkowoeuropejski czas stand.)
(canary) Version 13.41.318.0 Published Wed Mar 11 2015 09:22:00 GMT+0100 (Środkowoeuropejski czas stand.)
```
Can You update?

**Comment by piernik** [comment]
What about this?

**Comment by pewh** [comment]
+1 very very need this

**Comment by jbavari** [comment]
This is currently available in our beta of the CLI.

Feel free to use it in the meantime until the official release is out - `npm install -g ionic@extlib`.

**Comment by piernik** [comment]
@jbavari thanks it works. How about using `latest` not specific version? Crosswalk 14 is in alpha so it could be very important

**Comment by jbavari** [comment]
@piernik Yep, i've updated the list to have the latest 14 version. Try it out with the beta `npm install -g ionic@beta`.

`ionic browser ls`

**Comment by piernik** [comment]
I see that v14 is in beta canal now https://download.01.org/crosswalk/releases/crosswalk/android/beta/

**Comment by piernik** [comment]
I'm using now ionic-cli 1.4.3 and on `ionic browser list` I see crosswalk 14.43.334.0 - nothing about `latest` - https://download.01.org/crosswalk/releases/crosswalk/android/canary/latest/
Now latest is v15

**Comment by jbavari** [comment]
@piernik are you using Cordova CLI 5.0?

**Comment by piernik** [comment]
yes
