### ISSUE TITLE
Missing Cordova plugins

### ISSUE THREAD

**Issue by antonshevchenko** [driftyco/ionic-cli#365]
After installing all required Cordova plugins from the `package.json` when doing `ionic platform add ios`, in actuality some of them are missing from the build.

By checking in Xcode -> Build Phases -> Compile sources there are some that are missing. Similarly, in the `/Plugins` directory the same ones are missing.

Doing a `cordova plugins ls` however, does list all plugins as if they were installed properly.

Any help would be appreciated!

**Comment by tabrindle** [comment]
I believe this is an ongoing issue with Cordova's CLI, which ionic is calling from their CLI. 

Check this link to see if this sounds familiar. 

https://issues.apache.org/jira/browse/CB-4971

**Comment by jbavari** [comment]
Cordova plugin ls just lists the directories in the `plugins` directory.

Try out `ionic state reset` to get a fresh start, or remove platforms/plugins and re-adding them.
