### ISSUE TITLE
ionic login/upload/share on version 1.3.17/18/19 does not work

### ISSUE THREAD

**Issue by emotu** [driftyco/ionic-cli#370]
I created an account and i cannot login or upload or share my code from the cli. This means the only place i can test the app is on my browser. I think there's a problem somewhere (either with ionic or the web service responsible for authentication).

**Comment by jbavari** [comment]
Please try latest. If it continues to not work, please open a new issue. We cannot modify older builds, hence the title is the reason for closing. :)
