### ISSUE TITLE
bug: ionic login from cli doesn't work

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#371]
_From @emotu on April 13, 2015 6:19_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>After signing up for an ionic account via http://apps.ionic.io running the following commands do not work:

$ ionic login
$ ionic upload
$ ionic share

they all respond with the following error:

Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.3.19)

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.3.0
Ionic Version: 1.0.0-rc.2
Ionic CLI Version: 1.3.19
Xcode version: Xcode 6.3 Build version 6D570
ios-sim version: 3.1.1
ios-deploy version: 1.5.0

However, using teh same credentials online works just fine.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3514_

**Comment by seacucumba** [comment]
Hello guys. I have exactly the same problem - ionic cli won't log me in.
Any ideas to fix or workaround?

$ ionic login

To continue, please login to your Ionic account.
Don't have one? Create a one at: https://apps.ionic.io/signup

Email:
Password: 
Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.3.20)

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.32
Cordova CLI: 5.0.0
Ionic CLI Version: 1.3.20
Xcode version: Xcode 6.3.1 Build version 6D1002 
ios-sim version: 3.1.1 
ios-deploy version: Not installed

**Comment by hameedraha** [comment]
Any development in this issue?

**Comment by jbavari** [comment]
@seacucumba  @hameedraha - there was some change on the upload/login backend systems.

We've since updated those endpoints.

Would you mind trying with the latest (1.4.x) CLI?

**Comment by hameedraha** [comment]
Looks like the issue got fixed in last CLI version itself when I tried resetting my password purposefully from Ionic Forum. Anyway, I will take a look again.

**Comment by roysaad** [comment]
I'm still having the same issue. CLI version 4.2.0.

**Comment by mikeLspohn** [comment]
I'm having this issue with CLI version 1.5.4 on Yosemite.

**Comment by pierrybos** [comment]
+1, other version
Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.6.5)

**Comment by pierrybos** [comment]
So, now its working for me, but first i needed change my password and so all work back. If pwd has a expiration date, i believe is better change password error information and say about this too.

**Comment by laurencehoess** [comment]
Could you add login to the ionic --help. I din't realize I was logged into a different account and couldn't upload a previous project I was working on because I didn't realize I was in a different account and login wasn't shown in the help.

**Comment by razam217** [comment]
I'm having the same issue, in Mac OS X, Ionic CLI v-1.7... 

Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.7.12)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2 Build version 7C68

**Comment by razam217** [comment]
Can anyone please help me out of this heck? I'm stuck from 2 days... :(

**Comment by anupkumar05** [comment]
hey yes i am too getting the same error both in mac and windows, please help me .
I am not able to upload required certificate and keys to server.

Regards,
Anup

**Comment by anupkumar05** [comment]
after investigating why that is happening I found that it is due to in response of API login we are receiving cloudfare captach  , is there a way to auto fill that captach  or skip it ?

**Comment by pierrybos** [comment]
Its make sense for me. I put my login info inside shell scripts and automatize somethings, so, i dispatch sometimes and probably a server can identify like a robot behavior.

**Comment by Seao** [comment]
Hi, I'm having same issue with `ionic upload` in Mac OS X (Ionic CLI v1.7.14). I tried to downgrade the version of Ionic and reset my password but this does not solved the problem. No idea how to fix it ...

**Comment by coderhut** [comment]
This seems like consistent issue of Ionic. Ionic team needs to work on it seriously.

**Comment by coderhut** [comment]
lolzz....I had stopped using this solution since long time ago and before sleeping last night I thought to implement that. So in morning I did the most used solution under such circumstances and you all know that well...restarted my laptop and it worked :D I jumped yayyyy :P

**Comment by KaraAJC** [comment]
Having similar problem with above commands, raised issue #1064 because I'm not getting the ``invalid password`` response others are getting.

**Comment by makdas** [comment]
Same Issue. Cant upload my build to ionic.io
Email or Password incorrect. Please visit https://apps.ionic.io for help. (CLI v1.7.16)

Your system information:
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
OS:
Node Version: v4.4.1

I'm currently logged into the apps.ionic.io website.

**Comment by ahayder** [comment]
same issue here. CLI version 2.0 Mac OS X El Capitan

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by anikwai** [comment]
Still got the issue! Ubuntu 17.10

**Comment by dwieeb** [comment]
@anikwai If you're trying to log in to Ionic Pro, you'll need to make sure your CLI is configured for it:

```
ionic config set -g backend pro
```

**Comment by aacassandra** [comment]
2021, can't login with ionic cli. why this problem is closed ?
