### ISSUE TITLE
Add command to disable pull to refresh on crosswalk

### ISSUE THREAD

**Issue by Rakonda** [driftyco/ionic-cli#376]
Hello guys, i succeeded to run crosswalk on my android device, i notice that the pull to refresh used in chrome is also active on crosswalk and that is not correct for an application that should behave like a native one, i looked for a command to disable this and i found  --disable-pull-to-refresh-effect.
i don't know how to inject this command to be used while build the crosswalk.

**Comment by clauderic** [comment]
I'd also like to have some info on how to use this flag, anyone have some insight into how to use this?

**Comment by lfrodrigues** [comment]
In cordova I managed to fix this (see referenced ticket)

**Comment by b8rother** [comment]
+1

**Comment by Rakonda** [comment]
Thanks Ifrodrigues, i checked your reference but it already closed with latest [cordova-closswalk](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview) update, and pull-down-to-refresh is disabled by default

**Comment by jbavari** [comment]
@Rakonda is right, it's been disabled by default. I've tested it now and it's behaving without the pull to refresh.

**Comment by kevz93** [comment]
how do you enable it ?
