### ISSUE TITLE
Live-reload using bad IP address

### ISSUE THREAD

**Issue by sylzys** [driftyco/ionic-cli#378]
Hi,

After I configured the address with `ionic address` and selected localhost, I'm trying to use `ionic serve -l` to run my app with livereload, on my browser at first. 
The compilation goes, the first page opens, on /ioniclab. I then browse to `http://localhost:8100` and problems start. The browser tries to connect to 192.168.1.10:8100... If I refresh my page, the localhost is used, I can access my app, and do some changes on my files.

On my terminal, I can see that Ionic is watching he changes made, displaying like `HTML changed: www/partials/home/home.html`.
BUT : nothing changes in the browser, and Ionic doesn't start to re-serve the modified files. Plus, the browser tries (and fails) to connect to `ws://192.168.1.10:35729/livereload.`, when Ionic says `Running live reload server: http://localhost:35729`...

It may be worth mentionning that my www folder is generated with Brunch.io, I don't know if that comes in the way. It seems strange anyway since Ionic watchs `[ 'www/**/*', '!www/lib/**/*' ]`

I tried with another project, with everything directly into the `www` folder and no task runners, and the livereload seems to work smoothly. But that one is really simple, and I really need Brunch system on my real app :/

Anybody has a clue on what it could be ?
Thanks in advance

**EDIT**: after a second try, even the simple app with no task runner fails... :( Still a try on 192.168.1.10 which does not exist...

```
$ ionic -v                                                                                                                                                               
1.3.19
```

**Comment by sylzys** [comment]
some bugs :
```
21    819237   error    Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.13/$rootScope/infdig?p0=10&p1=%5B%5D
minErr/<@http://localhost:8100/js/vendor.js:63:12
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8100/js/vendor.js:14281:1
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8100/js/vendor.js:14506:13
timeout/timeoutId<@http://localhost:8100/js/vendor.js:16232:25
completeOutstandingRequest@http://localhost:8100/js/vendor.js:4905:7
Browser/self.defer/timeoutId<@http://localhost:8100/js/vendor.js:5285:7

22    819239   error    Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.3.13/$rootScope/infdig?p0=10&p1=%5B%5D, http://localhost:8100/js/vendor.js, Line: 63
```

My vendor.js file contains AngularJs files

**Comment by jbavari** [comment]
Please try out latest (1.4.0) and let me know if that clears it up.
