### ISSUE TITLE
ionic upload Error: certificate not trusted

### ISSUE THREAD

**Issue by quanghoc** [driftyco/ionic-cli#381]
If I do `ionic upload` within firewall and some url certificate not approved by the company, I got this error:

```
Uploading app...
There was an error trying to upload your app.
The specific error message: Error: certificate not trusted (CLI v1.3.19)

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.12.2
Cordova CLI: 4.3.0
Ionic Version: 1.0.0-beta.11
Ionic CLI Version: 1.3.19
Xcode version: Xcode 6.3 Build version 6D570 
ios-sim version: 3.1.1 
ios-deploy version: Not installed
```

Is there a way to find out exact URL? I approved ionicframework.com and ionic.io and still not working.

**Comment by jbavari** [comment]
I've never encountered this before @quanghoc, so please bear with me!

The outbound URl is [https://apps.ionic.io/api/v1/app/direct-upload](https://apps.ionic.io/api/v1/app/direct-upload).

You might check with your administrator and have them add that host `apps.ionic.io`.

**Comment by emve-dev** [comment]
Same problem possibly after updating Ionic CLI (v.1.4.5).
Tried different wifi connections and same error. 

> C:\Users\...\WebstormProjects\app>ionic upload 
> Uploading app...
> Upload Failed: [Error: CERT_UNTRUSTED]

**Comment by sharifbdp** [comment]
I try to Upload a APP. It appear the same error..


$ ionic upload
Uploading app...
Upload Failed: [Error: CERT_UNTRUSTED]

anybody here :(

**Comment by rbokhari** [comment]
I am also facing same issue 

Uploading app...
Upload Failed: [Error: CERT_UNTRUSTED]

This error occurs specially after upgrading to cli 1.4.5

Any help ?

**Comment by emve-dev** [comment]
Funny thing.
Despite the fact that running `ionic upload` gives me this error `Upload Failed: [Error: CERT_UNTRUSTED]` the app is uploaded!

**Comment by patrickmcd** [comment]
I get the same failure, but then the app shows up in the Ionic View App on iOS, but the size for the app is NAN UNDEFINED. After clicking the View App button, the same button temporarily says Connection Error.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
