### ISSUE TITLE
using Crosswalk : Wrong language returned (always "en-US")

### ISSUE THREAD

**Issue by phearme** [driftyco/ionic-cli#382]
When using crosswalk in ionic project through `ionic browser add crosswalk`, I want to get the OS language (tested on Android 5.0). Here are the results with Crosswalk webview

    navigator.languages -> undefined in crosswalk
    navigator.language -> always returns "en-US" even though my OS is in french
    navigator.userLanguage -> undefined
    navigator.browserLanguage -> undefined

I have currently no way of getting the device language with Crosswalk. Although I'm pretty sure (but could be wrong) that this is a Crosswalk issue, maybe there is a workaround on the ionic side.

EDIT: follow up on this. This is a Crosswalk issue
https://crosswalk-project.org/jira/browse/XWALK-2132

**Comment by hafeyang** [comment]
+1 ,hope solved soon

**Comment by ivandroid** [comment]
+1 waiting for a solution

**Comment by jbavari** [comment]
From the ionic side, I'm not sure there's much we can do if thats a core call.

Have you tried out [the globalization plugin](https://github.com/apache/cordova-plugin-globalization)?

**Comment by phearme** [comment]
the crosswalk bug seems to be fixed in version 13:
https://crosswalk-project.org/jira/browse/XWALK-2132

currently, available Crosswalk versions can be obtained with `ionic browser list` with following result:
```
Available - Crosswalk - ionic browser add crosswalk
	 Version 8.37.189.14 Published Fri Oct 10 2014 03:26:00 GMT+0200 (CEST)
	 Version 9.38.208.10 Published Tue Nov 25 2014 11:45:00 GMT+0100 (CET)
	 Version 10.39.235.15 Published Wed Dec 31 2014 13:16:00 GMT+0100 (CET)
	 Version 11.40.277.7 Published Thu Feb 26 2015 07:03:00 GMT+0100 (CET)
	 Version 12.41.296.5 Published Thu Mar 05 2015 13:19:00 GMT+0100 (CET)
(beta)	 Version 13.42.319.6 Published Tue Apr 14 2015 14:24:00 GMT+0200 (CEST)
(canary) Version 14.42.334.0 Published Mon Apr 13 2015 09:16:00 GMT+0200 (CEST)
result:
```

also, it is possible through ionic to use specific version of crosswalk, for exemple:
`ionic browser add crosswalk@10.39.235.15`

although I haven't tested it yet, I assume using the beta or canary version will get the fix.

**Comment by sanmaozhao** [comment]
+1, same issue on crosswalk 14.43

**Comment by baleboy** [comment]
I just tried this with Crosswalk 14.43.343.24 and plain cordova, and navigator.language returned the correct value.
