### ISSUE TITLE
bug: id is not case sensitive

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic-cli#384]
using `ionic start myapp -i com.name.myName` converts to `com.name.myname` - should stay myName

**Comment by jbavari** [comment]
Ahh, yes I see this issue. Let me ask around to make sure there wasn't a specific reason that this was set the way it was.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
