### ISSUE TITLE
docs: Getting time out error on creating an ionic project

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#385]
_From @GSPriya on April 20, 2015 10:9_

**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>
$ ionic start todo blank
Creating Ionic app in folder /Users/priti/todo based on blank project

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
 ✗ Error fetching: https://github.com/driftyco/ionic-app-base/archive/master.zip Error: connect ETIMEDOUT
 ✗ Error: Unable to initalize app: Error: connect ETIMEDOUT
</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3565_

**Comment by adamdbradley** [comment]
_From @GSPriya on April 20, 2015 10:36_

It is fixed with the command PROXY=http://myproxy.com:8081 ionic start myApp as I was behind a proxy.

**Comment by adamdbradley** [comment]
_From @GSPriya on April 20, 2015 10:54_

Now i'm getting a time out error after this

Update config.xml
Initializing cordova project
running cordova plugin add org.apache.cordova.device
Fetching plugin "org.apache.cordova.device" via plugin registry
npm http GET http://registry.cordova.io/org.apache.cordova.device
npm http GET http://registry.cordova.io/org.apache.cordova.device

Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

**Comment by jbavari** [comment]
This looks to be an npm issue with timing out. Closing.

**Comment by sunilpwyd** [comment]
Try this. It worked for me
1. Open a command prompt
Run this
set PROXY=http://myproxy.xyz:80
Run this
ionic start myApp tabs

**Comment by gururajmbhandarkar** [comment]
Running with sudo worked for me. for the same issue

**Comment by gitshubh** [comment]
This still isn't working for me.
I have set up proxy, http_proxy and https_proxy in windows environment variables.
I have also set up the proxies in "npm config"

Still Error Timed Out

**Comment by ChrisMcNulty91** [comment]
Same issue as @gitshubh All my proxies are configured, still receiving timeout issue. I've seen other solutions which modify request.js within the node_modules folder of ionic but I do not have the request module in the node_modules. I have ionic version 3.2.0 insatlled

**Comment by joesleiman** [comment]
i have this error : timeout of 25000ms reached for https://res.ionic.io/api/v1/transfom 
when doing : ionic cordova resources  ios --splash .
anyone know what the issue.
also my internet is low. but i can't increase the speed so how can i solve it?

**Comment by gitshubh** [comment]
Its a proxy issue.
My network team was able to solve it using Fiddler Proxy.
