### ISSUE TITLE
feature: Ionic serve command option to wait for gulp.

### ISSUE THREAD

**Issue by mikehaas763** [driftyco/ionic-cli#387]
I use a build system with gulp as well as some gulp watching to trigger new builds. Essentially, the build occurs and then dumps a final build into the "www" directory. There are no static resources directly in the www directory, it is entirely the result of the build process.

I have one "gulpStartupTasks" task listed. That tasks triggers a full build, and then watches some files so that a new build can be triggered when appropriate. It all works great with one little quirk. My problem is that the initial first build takes a few seconds but in the meantime the LiveReload server has already started. So I get an error message from the server because index.html does not exist yet because the build is still occurring. Unless there is already a good way to handle this, I propose defining a new property in the ionic.project file.

Maybe something like this:

```javascript
{
    "livereload": {
        "waitForGulp": boolean
    }
}
```

I will gladly work on this if it ends up being a viable option. Just want to get some discussion going.

**Comment by mikehaas763** [comment]
This may be a duplicate of #275.

**Comment by hcentelles** [comment]
:+1:

**Comment by leonardobazico** [comment]
+1

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
