### ISSUE TITLE
Not possible to use "npm install ionic" without -g

### ISSUE THREAD

**Issue by jacargentina** [driftyco/ionic-cli#388]
May be the npm package is not prepared to handle a local installation of cordova + ionic?

I've tried doing:

    mkdir ionic-app && cd ionic-app
    npm install cordova ionic --save
    ionic start ionic-client sidemenu

And it starts building the app, but it fails later. The output as is:

````
Creating Ionic app in folder /home/USER/javascript/ionicapp/ionicclient based on sidemenu project

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s

Downloading: https://github.com/driftyco/ionic-starter-sidemenu/archive/master.zip
[=============================]  100%  0.0s

Update config.xml
Initializing cordova project
/bin/sh: ionic: no se encontró la orden
Unable to add plugins. Perhaps your version of Cordova is too old. Try updating (npm install -g cordova), removing this project folder, and trying again. (CLI v1.3.20)

Your system information:

OS: Distributor ID:	Fedora Description:	Fedora release 21 (Twenty One) 
Node Version: v0.10.36
Cordova CLI: Not installed
Ionic Version: 1.0.0-rc.3
Ionic CLI Version: 1.3.20
````

I want to avoid a npm global (-g) install, to avoid messing up my actual global packages/etc.
BTW, to make it work without global install, i've added to my .bash_profile this:

    PATH=./node_modules/.bin:$PATH

So , if i'm inside /home/USER/javascript/ionicapp/, i can run "cordova" or "ionic" without problem.

**Comment by jbavari** [comment]
The CLI is set up to run as a global and we dont have much plans to change this. :8ball:

**Comment by vance** [comment]
You can install locally now. just make sure to make a script "ionic":"ionic" in your package.json to map it to the local version. Make sure to install Cordova locally as well.

**Comment by dwieeb** [comment]
`ionic` will also look for a locally installed CLI and then use it, much like how Angular CLI or gulp CLI works.
