### ISSUE TITLE
Ionic serve w/ lab uses external resources

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#390]
(Ugh, horrible wifi here - forgive me if this posts twice.)
I noticed that when I used `ionic serve -l` it was *extremely* slow to load. Turns out there are 2 remote resources that - under bad/poor wifi - delay the load of the browser preview. Those resources should be moved to a local copy.

**Comment by jbavari** [comment]
It looks to me there are about 3 resources total. 

Angular.min.js, angular.min.js.map, and analytics.js.

I can include angular.min.js and map, but it looks like analytics will have to stay remote.

**Comment by cfjedimaster** [comment]
Can I ask though why Analytics has to stay? I know it benefits yall of course. What about adding defer/async (or whatever it is) to the <script> tag you use?

**Comment by jbavari** [comment]
@cfjedimaster We'd like to keep getting statistics of who is using the Lab feature.

As far as the defer/async, how do you mean?

**Comment by cfjedimaster** [comment]
Maybe you already have done this, but see here - https://developers.google.com/analytics/devguides/collection/gajs/asyncMigrationExamples#migrationInstructions

**Comment by jbavari** [comment]
@cfjedimaster Ahhhh, ok I gotcha.

It looks as if the google analytics are already set up that way, see that [here](https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/assets/preview.html#L178)

**Comment by cfjedimaster** [comment]
Cool - then maybe once the others are corrected it won't be an issue. :)

On Mon, May 11, 2015 at 3:26 PM, Josh Bavari <notifications@github.com>
wrote:

> @cfjedimaster <https://github.com/cfjedimaster> Ahhhh, ok I gotcha.
>
> It looks as if the google analytics are already set up that way, see that
> here
> <https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/assets/preview.html#L178>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-cli/issues/390#issuecomment-101038048>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by jbavari** [comment]
I've got a ton of changes coming out in 1.4.0. I'm both excited and nervous to release. So many changes at once.

Any chance I can bother you for an exhaustive run through?

**Comment by cfjedimaster** [comment]
Not at all, drop me a line personally, and please remember I kinda suck at
npm. Like, I just checked and I'm on 1.4.0-beta.7 and I have no idea how to
check if there is a newer beta and how to switch to it. (Upgrading to
'release' I get - betas - not so much.) Also be sure to let me know if
there is anything I can't blog about. (And I'd assume you would let me know
via email and not public Git tracker. ;)

On Mon, May 11, 2015 at 3:43 PM, Josh Bavari <notifications@github.com>
wrote:

> I've got a ton of changes coming out in 1.4.0. I'm both excited and
> nervous to release. So many changes at once.
>
> Any chance I can bother you for an exhaustive run through?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-cli/issues/390#issuecomment-101041891>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
