### ISSUE TITLE
Automatically adding iOS on OSX

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#392]
In the beta version I have, when I create a new project, it automatically adds iOS. To me, this feels wrong. Not, "Oh my god!" wrong, but... I don't know. Even though I pretty much use 99% of the time, it just seems like Ionic shouldn't be assuming this. I figured I'd file an issue and see what people think. I'm pretty sure I'm in the minority here, but I figured I'd start the discussion. :)

**Comment by jbavari** [comment]
This is the default behavior going forward - as a team, we've decided most users are using Ionic to build ios and android apps. If they are using a Mac, chances are they will type the command to add ios.

Most use cases are - 

```
ionic start someapp
cd someapp
ionic run ios
//Message telling them to type platform add
```

To avoid typing yet *another* command, we're just going to have it auto-installed.
