### ISSUE TITLE
bug: ionic CLI share command doesn't send emails

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#394]
_From @carpiediem on April 24, 2015 4:57_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I last tried a week ago, running the `ionic upload` command would ask me if I wanted to share with others.  It doesn't do that anymore.

When I type in `ionic share me@isp.net`  the response says `Sharing app null with me@isp.net` but nothing ever shows up in my inbox.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3604_

**Comment by jbavari** [comment]
The ionic cli sends a request to our ionic services, which in turn sends the email. This isnt so much a CLI issue as it is an Ionic.io issue. It should be fixed in the next day or so. Closing for now.

**Comment by carpiediem** [comment]
It is working now.  Thanks for the follow-up.

**Comment by ib84** [comment]
hi,
I'm using ionic 2.1.8 on debian jessie, and want to report that sharing with emails doesn't work for me. I tried with two adresses: one used for an ionic account and one without an ionic account.
