### ISSUE TITLE
bug: `ionic state reset --plugins` resets platforms

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#399]
_From @RangerRick on April 25, 2015 16:10_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When I run `ionic state reset --plugins` it also resets platforms:

```
Sin:~/git/opennms-compass ranger$ ionic state reset --plugins
Removed platforms and plugins
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android
cordova platform add browser
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add org.apache.cordova.console
cordova plugin add org.apache.cordova.geolocation
cordova plugin add org.apache.cordova.inappbrowser
cordova plugin add org.apache.cordova.network-information
cordova plugin add org.apache.cordova.splashscreen
cordova plugin add org.apache.cordova.statusbar
cordova plugin add com.google.cordova.admob
cordova plugin add cc.fovea.cordova.purchase
cordova plugin add com.ionic.keyboard
cordova plugin add https://github.com/RangerRick/cordova-certificate-plugin.git 
cordova plugin add com.ohh2ahh.plugins.appavailability
cordova plugin add com.google.playservices
Restore plugins is complete

Ionic state restore completed

Ionic reset state complete
```</span>

<span is-issue-template></span>


_Copied from original issue: driftyco/ionic#3617_

**Comment by jbavari** [comment]
This has been fixed in the latest branch. It'll be available in the next release.

**Comment by surfjedi** [comment]
This seems to still happen..

**Comment by skattyadz** [comment]
+1 Still getting this

**Comment by jakub-g** [comment]
using ionic@1.7.14 I can reproduce the opposite scenario, i.e. I run ` ionic state reset --platforms` but it also resets plugin.

Note the first line of the output which says `Removed platforms and plugins`

So, while only the one passed via command line (`--platforms` or `--plugins`) is restored, **both** are removed

**Comment by jakub-g** [comment]
I sent a PR for this, it would be pretty useful to have this working.

In my use case I want to do `ionic state reset --platforms` as a part of a script instead of `cordova platform rm android && cordova platform add android`, so that the proper platform version is taken from `package.json`. I don't need to reset plugins but this is the more expensive part; platform reset takes ~30s while plugins 1minute+

**Comment by jakub-g** [comment]
As a temporary fix I'm using `restore` instead of `reset` and remove things myself:

        cordova platform rm android && ionic state restore --platforms

instead of

        ionic state reset --platforms

**Comment by rob3c** [comment]
The same problem happens with the `clear` command:
`ionic state clear --platforms`
also clears plugins, and vice versa.

**Comment by slzr** [comment]
this still happening... 😞 
```
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.4.0
Xcode version: Not installed
```

**Comment by helixhuang** [comment]
Try .https://www.npmjs.com/package/ionic-reset .
