### ISSUE TITLE
Ionic CLI - error running ionic commands  on Mac

### ISSUE THREAD

**Issue by aasavad** [driftyco/ionic-cli#401]
Hi,

I am getting the below error while running any ionic commands on Mac.I tried re-installing node/cordova/ionic but no luck

Can you please advise?

![ionicerror](https://cloud.githubusercontent.com/assets/11210283/7371296/cbf1ec2e-edb7-11e4-8b2e-b244316a6c15.png)

**Comment by jbavari** [comment]
Please run `ionic info` and report the output of the command.

**Comment by aasavad** [comment]
Hi,

I commented out the below code in config.js and tried ionic -v it showed the version.

this.data = JSON.parse(fs.readFileSync(path.join(home, this.file)));

Reverted the comment and tried few ionic commands and everything started working fine.Not sure what happend.It works fine anyway  :)
