### ISSUE TITLE
CPU incompatible after add Crosswalk to my project

### ISSUE THREAD

**Issue by danielfpedro** [driftyco/ionic-cli#402]
I add Crosswalk with `ionic browser add crosswalk` and `ionic build android`, both commands run ok with no error but when I run `ionic run android` I had an issue when the app is installed:

    Failure [INSTALL_FAILED_CPU_ABI_INCOMPATIBLE]

I already tried to copy the apks to phone and execute but both x86 and armv7 resulted an `app not installed.`

**Comment by jbavari** [comment]
Can you supply more information?

Run `ionic info` and post that information.

You are running genymotion, correct?
