### ISSUE TITLE
Critical issue with gradle build

### ISSUE THREAD

**Issue by ag-secret** [driftyco/ionic-cli#403]
Since I updated my CLI it is building my project with Gradle instead Ant. I had a project that was working fine but now they is returning all $hhtp requests with 404 and is not loading any image that is loaded from web. I test all the url that is returning 404 on browser and all is returning 200.

So I did the final teste,Ii just created an project with `ionic start test-ionic sidemenu` and in the ` playlists` template I just put this `<img src="http://dreamatico.com/data_images/car/car-6.jpg">`.. so.. yes.. the image is not being loaded.

At beginning I thouth the issue could be about a conflict with something from my old project, but with the fresh project I think could be something else.

Can I build my project with `ant` until you guys fix this?

**Comment by jbavari** [comment]
Specifically, which CLI did you update?

Did you upgrade your Cordova CLI to 5.0.0 or Ionic CLI?

**Comment by ag-secret** [comment]
I just updated both to the newest.. how can I check the current version of then?

**Comment by ag-secret** [comment]
I tried `npm ionic -v` and `npm cordova -v` and both of then returned 2.7.4

**Comment by jbavari** [comment]
Run: `ionic info`

**Comment by ag-secret** [comment]
OS: Windows 7 SP1
Node Version: v0.12.2
Cordova CLI: 5.0.0
Ionic Version: 1.0.0-rc.5
Ionic CLI Version: 1.3.20

**Comment by jbavari** [comment]
Cordova 5.0.0 now specifies Gradle to be default build system for Android. I'm not too sure how to use ant.

However, in Cordova Android 4.0.0, they specify that you need to use the Whitelist plugin:
Try this:

`ionic plugin add https://github.com/apache/cordova-plugin-whitelist.git#r1.0.0`

**Comment by ag-secret** [comment]
The issue persists... I just need install the plugin or I need to make some extra configuration?

**Comment by jbavari** [comment]
From what I understand - just install the plugin.

**Comment by ag-secret** [comment]
Now worked bro.. thanks.. I don't know if you are from Ionic team but if you are I think it could be alerted at docs or something like that.. thanks
