### ISSUE TITLE
Black screen on iOS after Ionic CLI 1.3.21 update.

### ISSUE THREAD

**Issue by calebfaruki** [driftyco/ionic-cli#407]
Prior to updating to v1.3.21, I was able to view my app in Ionic View without issue. Now, when I load the app, I get a black screen. The app works perfectly in my Chrome browser, however.

When I launch the app, the hand and "Swipe down three fingers to exit" prompt still displays and I can navigate back to the My Apps page of Ionic View without issue. The app I've created is simply not displaying.

I am testing the app on both iPhone 5 and iPhone 6.

**Comment by jbavari** [comment]
What version of the CLI did you have before the update?

Nothing changed in 1.3.21 to modify anything to do with the ionic view app.

Does the app run in the emulator?

**Comment by tlancina** [comment]
Sounds like issues with the cachebuster fix, which should be resolved in
the develop branch. I have a feeling all uploads might be broken in 1.3.21.

**Comment by sodatea** [comment]
I just came across the same bug, too.
It seems that the `ionic upload` command automatically adds a `src="undefined"` attribute for inline scripts in www/index.html. A temporary solution is to keep all scripts external.

**Comment by calebfaruki** [comment]
I updated from 1.3.20 to 1.3.21.

**Comment by jbavari** [comment]
We're looking into it and coming up with a resolution.

**Comment by jbavari** [comment]
@calebfaruki 1.3.22 is out now. Please try that out and let @tlancina and myself know if that fixes the issue.

**Comment by calebfaruki** [comment]
The cache buster works great and the Ionic View app preview is back to normal. Thanks for the quick fix!
