### ISSUE TITLE
Browser info

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic-cli#410]
Can You add which browser is used?
Ex in `ionic info` or `ionic browser info`

**Comment by jbavari** [comment]
Currently there is the `ionic browser versions` but I'll add in an alias for `info`.

**Comment by piernik** [comment]
Better solution would be add info about that to doc;) 
http://ionicframework.com/docs/cli/browsers.html

**Comment by jbavari** [comment]
`ionic help browser` also works.
