### ISSUE TITLE
Warn when gulp is not installed

### ISSUE THREAD

**Issue by kanerogers** [driftyco/ionic-cli#413]
Hey, guys!

Firstly, Ionic is **awesome**. Incredible work, guys. :smile: 

Just went to create an app with Sass support today, and realised I didn't have ```gulp``` installed!

```
/bin/sh: gulp: command not found

Error running gulp sass
```

Maybe checking to see if idiots like me have ```gulp``` installed, then maybe prompting them to install it would be a cool idea? 

Thanks!

**Comment by jbavari** [comment]
@kanerogers There is a gulp installed check in the CLI. However, it only checks for if gulp is installed before running the `serve` command.

I'll go ahead and wire this up to the sass command as well.

Thank you for reporting.

**Comment by kanerogers** [comment]
One is glad to be of service.
