### ISSUE TITLE
Remove resolved dependency to open and replace it with version number

### ISSUE THREAD

**Issue by fifafu** [driftyco/ionic-cli#414]
Hi,

in the package.json is this line:
    "open": "https://registry.npmjs.org/open/-/open-0.0.5.tgz",
Is there a reason for this? I'm behind a corporate firewall and we are trying to get Ionic up and running. However to achieve this we use our own private npm cache (Artifactory). Unfortunately this does not work if there are resolved dependencies like this.

It would be great if you could remove this and replace it with the version number. As a temporary solution I edited it and uploaded a modified version to our registry, however it would be great to have this fixed here :-)

Thanks a lot!

**Comment by jbavari** [comment]
Hang tight. There was an open PR for this that got manually merged in. It should be released in the next 1.4.0 release.

This should be out in the next day or two.
