### ISSUE TITLE
Proxy server not able to authenticate using cookies

### ISSUE THREAD

**Issue by RonB** [driftyco/ionic-cli#415]
I am using a proxy to redirect calls during development to our application server.

I need to login using a login form submit and a returned cookie to be sent on every next request to the server.

I had to adjust the serve.js file and add 
    
    opts.rejectUnauthorized = !(proxy.rejectUnauthorized === false); // create setting in ionic.project
    opts.cookieRewrite = proxy.proxyUrl; // my application server needing authentication

for every proxy specified otherwise the cookie is not set in the browser and thus not redirected thru the proxy. The ionic.project configuration:

    "proxies": [
        {
          "path": "/api",
          "proxyUrl": "https://app.ontwikkeling.webbergen.local/api",
          "rejectUnauthorized": false
        }
    ]

**Comment by jbavari** [comment]
@RonB this fixes it for you entirely? I'll patch it in, mind testing a beta version?

**Comment by RonB** [comment]
You also should enable cookieRewrite on the http-proxy options to make sure that authentication can be enabled. Next to that an option to configure the local hostname is something we would appreciate. It can be achieved by using the --address param but specifying this in the ionic.project seems like a good idea.

I will test the beta if you want.

Thanks.

**Comment by RonB** [comment]
@jbavari Can you shine a light on this issue as I cannot find the previous code anymore where you create the proxies from the ionic.project config?

**Comment by josephmeiring** [comment]
Same issue here? What exactly is the fix? When will this be merged in?

**Comment by josephmeiring** [comment]
I can't find the code referenced in the posts above, is there a way to implement this at the moment?

**Comment by RonB** [comment]
@josephmeiring 
I am puzzled just like you. The place where the proxy server was created (used to be in serve.js) is no longer there  in the sourcecode.

This is the code I' ve adjusted to get it working but now itseems that this code has disappeared in the entire project:
    Serve.setupProxy = function setupProxy(options, app) {
      if(options.useProxy) {
        for (var x=0; x < options.proxies.length; x++) {
        var proxy = options.proxies[x];
        var opts = url.parse(proxy.proxyUrl);
        if (proxy.proxyNoAgent)
            opts.agent = false;
            opts.rejectUnauthorized = !(proxy.rejectUnauthorized === false);
            // adjustment InProces to rewrite cookies
            console.log('InProces Adjustment authentication enabled for proxy ' + proxy.proxyUrl);
            opts.cookieRewrite = proxy.proxyUrl;
            // end adjustment
            app.use(proxy.path, proxyMiddleware(opts));
            events.emit('log', 'Proxy added:'.green.bold, proxy.path + " => " + url.format(proxy.proxyUrl));
          }
       }
    };

**Comment by blackjid** [comment]
@RonB they moved a lot of stuff to ionic-app-lib
https://github.com/driftyco/ionic-app-lib/blob/b24b47c8a95a0dd7881b6cfc7a91492d5e5d0070/lib/serve.js#L341

**Comment by RonB** [comment]
@blackjid 
Thanks for pointing me toward that library.

@jbavari 
Could you add the cookieRewrite property to the proxy options?
I've tested this with my local application and it works like a charm. Thank you.

**Comment by zambien** [comment]
I have this same issue.  The solution to use the following also fixed my issue.  Could this be added permanently?

`opts.cookieRewrite = proxy.proxyUrl; // my application server needing authentication`

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
