### ISSUE TITLE
bug: Ionic serve should listen on all addresses on linux

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#416]
_From @MichaelBitard on May 10, 2015 12:14_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When using ```ionic serve``` for the developments, It prompts for an interface selection: 

```bash
Multiple addresses available.
Please select which address to use by entering its number from the list below:
 1) 192.168.0.20 (wlan0)
 2) localhost
```

Why not listen by default on 0.0.0.0 so it will be available both locally and remotely?</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3693_

**Comment by jbavari** [comment]
In 1.4.0, you will be able to run the server on 0.0.0.0. :) :8ball:

**Comment by MichaelBitard** [comment]
That's great news, I can't wait for it to be released ;)
