### ISSUE TITLE
bug: Can create and build cordova but ionic troughs hooks error 

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#417]
_From @super-coder on May 12, 2015 2:4_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>cordova build

Running command: C:\Windows\system32\node C:\_Learn\ionic\firstIonicApp\hooks\after_prepare\010_add_platform_class.js C:\_Learn\ionic\firstIonicApp
Error: Hook failed with error code ENOENT: C:\_Learn\ionic\firstIonicApp\hooks\after_prepare\010_add_platform_class.js

![1431395914399](https://cloud.githubusercontent.com/assets/2155554/7578884/42a82a50-f88e-11e4-90d5-9d407a5b669f.jpg)
![1431395947983](https://cloud.githubusercontent.com/assets/2155554/7578885/42acebd0-f88e-11e4-9c1c-c0f86cab2798.jpg)
![untitled](https://cloud.githubusercontent.com/assets/2155554/7578886/42b06170-f88e-11e4-89c2-7541b0942998.png)</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3701_

**Comment by perrygovier** [comment]
_From @super-coder on May 12, 2015 3:23_

if i rename after_prepare folder everything works. So looks like the problem is with 010_add_platform_class.js

**Comment by jbavari** [comment]
Could you run `ionic info` and paste that information here @super-coder?

**Comment by super-coder** [comment]
C:\_Learn\ionic\firstIonicApp>ionic info

Your system information:

OS: Windows 8.1
Node Version: v0.12.1
Cordova CLI: 5.0.0
Ionic Version: 1.0.0-rc.5
Ionic CLI Version: 1.3.22

**Comment by gvolkan** [comment]
I've got same isseu, its fixing with giving permission hooks and it's child folders. 

Also my system info;

OS: Mac OS X Yosemite
Node Version: v0.12.2
Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.3.22
Xcode version: Xcode 6.3.1 Build version 6D1002
ios-sim version: 3.1.1
ios-deploy version: 1.5.0

**Comment by super-coder** [comment]
what permissions? to what user? I am already running cmd as admin and added all permissions to all users to C:\_Learn\ionic\firstIonicApp\hooks
C:\_Learn\ionic\firstIonicApp\hooks\after_prepare also inherited all permissions

**Comment by jbavari** [comment]
Try running `ionic hooks permissions` - does that help?

**Comment by super-coder** [comment]
no, it doesn't help. It tells **Updated the hooks directory to have execute permissions** but anyway when I do **ionic build** at the beginning it tells the same

**Comment by jbavari** [comment]
Can you try running the node script directly to get more output?

Something like:
`C:\Windows\system32\node C:\_Learn\ionic\app1\hooks\after_prepare\010_add_platform_class.js C:\_Learn\ionic\app1`

**Comment by super-coder** [comment]
I've run it, there is no output or errors

**Comment by jbavari** [comment]
What happens when you start a new project? Same errors?

**Comment by super-coder** [comment]
i tested several, all the same. If I rename the after_prepare folder it all works OK

**Comment by jbavari** [comment]
I might suggest using `ionic hooks remove` and seeing if that helps you work around those issues.

**Comment by super-coder** [comment]
nope, *ionic hooks remove* then *ionic build* - same stuff

**Comment by jbavari** [comment]
Can you supply a listing of those files permissions? 

Also try listing the permissions in `platforms/ios/cordova`

**Comment by super-coder** [comment]
i have all permissions for all users to app1 folder, so all child folders and files inherit

**Comment by prolink007** [comment]
Having the same issue as @super-coder . All suggestions did not fix the issue.

**Comment by zhuzhuxia556868** [comment]
All suggestions doesn't work. Rename after_prepare folder seems to be helpless choice.@super-coder

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
