### ISSUE TITLE
cant use ionic server commands in version 1.4

### ISSUE THREAD

**Issue by 5uper** [driftyco/ionic-cli#425]
when I run this command:
`ionic run ios --device -l`

in version 1.3.22
```
Setup Live Reload
Updated the hooks directory to have execute permissions
Proxy added: /api => http://...
Running dev server: http://...
running cordova run ios --device
Running live reload server: http://...
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```
i can use ionic server commands

but since version 1.4 i cant use them

**Comment by jbavari** [comment]
Roger - patching it now. Thanks for reporting!

**Comment by jbavari** [comment]
Fixed in 1.4.3 - thanks again for reporting.

**Comment by 5uper** [comment]
I tried it with version 1.4.3, does not work

**Comment by jbavari** [comment]
Could you provide more info? Are there errors? 

Does it not print out the server commands? What about your environment? Run `ionic info` and paste that here.

**Comment by jbavari** [comment]
![screen shot 2015-05-15 at 11 19 28 am](https://cloud.githubusercontent.com/assets/1414692/7658073/4cb6d04c-faf4-11e4-9128-d6d9ccbeb5cb.png)

I've included a screen shot that shows after the process exits, it lists the server commands. Do you not have these commands either?

**Comment by 5uper** [comment]
```
My system information:
Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.3
Ionic App Lib Version: 0.0.19
ios-deploy version: 1.5.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.3
Xcode version: Xcode 6.3.1 Build version 6D1002
```

I've tested it in the simulator and there it works and server commands printed at the end

but on device it stops in 47%
![bildschirmfoto 2015-05-15 um 19 37 32](https://cloud.githubusercontent.com/assets/2557532/7658376/e1cdd2b2-fb39-11e4-827e-7fcc7d4706fc.png)

then the commands do not work

**Comment by edmondchui** [comment]
I have the same issue. The live reload works but not the commands. Here is my ```ionic info``` output

```bash
$ ionic info

Your system information:

Cordova CLI: 5.0.0
Ionic CLI Version: 1.4.2
Ionic App Lib Version: 0.0.19
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.3
Xcode version: Xcode 6.3.1 Build version 6D1002 
```

**Comment by 5uper** [comment]
@edmondchui update your ionic cli to version 1.4.3

**Comment by 5uper** [comment]
@jbavari can you put the server commands at the beginning in Setup Live Reload?
like in version 3
```
Setup Live Reload
Updated the hooks directory to have execute permissions
Proxy added: /api => http://...
Running dev server: http://...
running cordova run ios --device
Running live reload server: http://...
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit
```

**Comment by edmondchui** [comment]
@5uper Version 1.4.3 works for me on Mac now. Thanks.

**Comment by jbavari** [comment]
@5uper I was hoping it would show the commands *after* it listed all the output from the build command.

We can put them at the beginning, you sure bet. Do you think it would be helpful to put the output in both locations? That way users are reminded just incase it scrolls out of view?

**Comment by 5uper** [comment]
The problem is not the print of the commands. 
but the activation of the commands happens after ## Run Succeeded ##

it would be great if you could activate the commands at the start

**Comment by AaronKS** [comment]
I'm getting a similar error after updating to 1.4.3.  It looks like it is looking at the config.xml in the www directory instead of the main app directory.

Error updating www/config.xml: Error: 
Your config.xml file does not have a <content> element. 
Add something like: <content src="index.html"/> (CLI v1.4.3)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0-rc.0
Ionic CLI Version: 1.4.3
Ionic App Lib Version: 0.0.19
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by programming-kid** [comment]
i get following error in browser 

```javasceipt 
Cannot GET /ionic-lab?ionicplatform=true 
```

**Comment by 5uper** [comment]
the way to walk around this bug, change your url path to /ionic-lab

`http://ipaddress:port/ionic-lab`

**Comment by programming-kid** [comment]
@5uper thanks it works  but ```ionic serve -l``` servers this url ```http://localhost:8100/ionic-lab?ionicplatform=true```

**Comment by jbavari** [comment]
@programming-kid Patching this now. My mistake.

**Comment by programming-kid** [comment]
Cool @jbavari  :+1:

**Comment by 5uper** [comment]
hey @jbavari you forgot update npm package to version 1.4.4 
`https://www.npmjs.org/package/ionic`

**Comment by jbavari** [comment]
@5uper no sir - I'm still testing things out on Windows. Almost done.
