### ISSUE TITLE
ionic start: include cordova-plugin-whitelist by default

### ISSUE THREAD

**Issue by mirkonasato** [driftyco/ionic-cli#426]
See this pull request https://github.com/driftyco/ionic-cli/pull/409

Looks like things have changed with the 1.4 branch merge so not sure where the default plugin list is now but please update it to work with Cordova 5.0.

Just do a search on the forums to see how many people get bitten by http requests not working in Android.

**Comment by jbavari** [comment]
@mirkonasato You bet. This was one of the merges I was trying to be conscious of and clearly dropped the ball. Patching now.

**Comment by jbavari** [comment]
@mirkonasato 1.4.4 is out - please confirm its working for you.

**Comment by mirkonasato** [comment]
Happy to confirm it's working fine, thanks!

**Comment by jbavari** [comment]
Glad to have helped. Thanks again for keeping me honest!
