### ISSUE TITLE
Too much CPU cycles & memory on Gulp watch after the latest cli updates

### ISSUE THREAD

**Issue by SecuriTeam** [driftyco/ionic-cli#428]
Hello,

I'm experiencing too much CPU & memory usage after the latest cli updates..

I've come to notice that it occurs when there are rapid notifications to the gulp watch process due to rapid change/save.

It happens a lot and each time I have to kill the live reload and initiate another because my browser tab/window become unresponsive.

If there is anyway to provide you with logs or something, please help me help you.

```
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic CLI Version: 1.4.3
Ionic App Lib Version: 0.0.19
OS: Windows 7 SP1
Node Version: v0.12.2
```

**Comment by SecuriTeam** [comment]
Upgrading to CLI 1.4.4 to see if it makes any difference.

**Comment by SecuriTeam** [comment]
I'm upgrading Chrome to latest stable release, and updated node to 0.12.3 .. will test and return.

**Comment by SecuriTeam** [comment]
Still occurs with Chrome 43.0.235x, Ionic CLI 1.4.4, node 0.12.3.
I can't nail the reason yet.
Chrome tab becomes unresponsive and I have to kill the page to kill the overload.

**Comment by jbavari** [comment]
@SecuriTeam Is the slowness with gulp watch?

What version was this working fine in before you noticed the slowness?

What tasks are outlined in your `gulpfile.js`? The default task takes 11 seconds.

I'd like to compare what changes have been made since then.

**Comment by SecuriTeam** [comment]
Hello,

I've just compiled and pushed a new dev/release version to my phone..
I'm experiencing the same issue as well.. not always.. but yes, the app`s CPU usage spikes up to 25% on my phone.

Perhaps it's bad coding on my side, so I'll get a closer look on logcat first.

@jbavari apparently it's not gulp or the watcher fault.. I was using *afair* 1.3.x (can't remember the exact version), but whenever cli warned me about new versions I would go ahead and install them immediately. Can't say if it happened because an update but it only started very recently.
Chrome updated auto couple of days ago, and today I even upgraded it to version 43.x.
I haven't updated node until today, after the issue started bugging me.. crosswalk is still the same version I installed (12.41.296.5).

my gulp default task only runs 'sass' task which is as follow
```
gulp.task('sass', function(done) {
	gulp.src(['./scss/style.scss'])
	.pipe(sass())
	.pipe(gulp.dest('./www/assets/css/'))
	.pipe(minifyCss({
	  keepSpecialComments: 0
	}))
	.pipe(rename({ extname: '.min.css' }))
	.pipe(gulp.dest('./www/assets/css/'))
	.on('end', done);
});
```
my custom scss file might be a bit big (with lots of imports) so it might take a little longer than 11sec (depends on my hardware after all).

Anyway, with the unexpected results that I started experiencing recently showing up on my phone, I'm starting to think it might be some bad coding.. logcat should def. give me a better insight.

Will keep you posted.
Thanks.

**Comment by SecuriTeam** [comment]
OK, I've noticed this so far..
If I open the app for the first time, it runs fine all the way until I press the back button and send it to background; this is when things get messy, I try to bring it foreground and the CPU usage spikes.

Logcat shows this as the last [ERROR] captured.

```
E/chromium(14586): [ERROR:runtime_javascript_dialog_manager.cc(69)] Not implemented reached in virtual void xwalk::RuntimeJavaScriptDialogManager::WebContentsDestroyed(content::WebContents*)
```

**Comment by jbavari** [comment]
Just taking a wild stab at this.. are you using the local notifications plugin? If so, have you seen [this issue](https://github.com/katzer/cordova-plugin-local-notifications/issues/426) on the local notifications issue tracker?

[Or this one?](https://github.com/MobileChromeApps/mobile-chrome-apps/issues/320)

Perhaps its related?

**Comment by SecuriTeam** [comment]
Hey man,

No I'm not using the local notification plugin.. here is a list of my plugins:
```
com.brodysoft.sqlitePlugin 1.0.4 "Brodysoft SQLitePlugin"
com.ionic.keyboard 1.0.4 "Keyboard"
cordova-plugin-camera 1.1.1-dev "Camera"
cordova-plugin-crosswalk-webview 1.0.1-dev "Crosswalk WebView Engine"
cordova-plugin-whitelist 1.0.1-dev "Whitelist"
hu.dpal.phonegap.plugins.SpinnerDialog 1.3.1 "SpinnerDialog"
io.github.pwlin.cordova.plugins.fileopener2 1.0.11 "File Opener2"
io.securiteam.plugins.screen 0.1.0 "DeviceScreen"
nl.x-services.plugins.socialsharing 4.3.18 "SocialSharing"
nl.x-services.plugins.toast 2.0.4 "Toast"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.dialogs 0.3.0 "Notification"
org.apache.cordova.file 1.3.4-dev "File"
org.apache.cordova.file-transfer 0.5.1-dev "File Transfer"
org.apache.cordova.inappbrowser 0.6.0 "InAppBrowser"
org.apache.cordova.network-information 0.2.15 "Network Information"
org.apache.cordova.splashscreen 1.0.0 "Splashscreen"
org.apache.cordova.statusbar 0.1.10 "StatusBar"
org.pbernasconi.progressindicator 1.1.0 "Progress Indicator"
```

I have seen [this](https://github.com/MobileChromeApps/mobile-chrome-apps/issues/320) issue yesterday while searching for the error messages that I've noticed in logcat..
However, I'm not receiving a black screen.. my interface shows up but not the content that is supposed to be fetched from the server.

I haven't had an issue with my app's root state code, (which all my ngRoutes inherit from), but I'm starting to wonder if my network status monitoring functionality is related, or not.. I'll keep searching for a root cause because it hit me out of nowhere.

Thanks for the follow up.

**Comment by SecuriTeam** [comment]
argh..
Been digging into this since morning and I'm yet to figure out what's wrong.

Here is [my app's logcat](http://pastebin.com/raw.php?i=UDiKYzSh) .. maybe you can see something interesting to help us out :(

**Comment by SecuriTeam** [comment]
Low and behold!
The problem was an `i` where it should have been a `j` in multi nested loops...
If it wasn't for the nested loops my jsLint task would have found the problem 2 days ago :warning: 

Man!

Closing this now as resolved, and thank you for your time into trying to look into this.
