### ISSUE TITLE
The ionic-cli is not saving the variables to package.json on plugin add

### ISSUE THREAD

**Issue by maksymilian-majer** [driftyco/ionic-cli#429]
Plugin variables aren't being saved to the `package.json` after running `ionic plugin add submodules/phonegap-facebook-plugin --variable APP_ID=SOMEID --variable APP_NAME=someName`.

I checked the source of `State` in ionic-app-lib and it takes a `variables` arguments ([source](https://github.com/driftyco/ionic-app-lib/blob/master/lib/state.js#L598)), but the ionic-cli does not pass it along ([source](https://github.com/driftyco/ionic-cli/blob/d5ad577e426f8c089e68a3201ebde752f69f095c/lib/ionic/cordova.js#L82)).

**Comment by jbavari** [comment]
Nice catch. I'll patch it today. Thanks for reporting!

**Comment by jbavari** [comment]
@maksymilian-majer Mind double checking for me - `npm install -g ionic@beta` 

The beta version should be passing along variables now.

**Comment by maksymilian-majer** [comment]
@jbavari I checked it and it works as expected :+1:

**Comment by jbavari** [comment]
Awesome. I'll merge this into master and be pushing it out later. Thanks again for reporting!

**Comment by maksymilian-majer** [comment]
No problem. You're doing amazing work with ionic, glad to be helpful!

**Comment by yankustefan** [comment]
I ran into the same issue. I'm using CLI 1.5.5

**Comment by eroh92** [comment]
Ran into this issue today using CLI 1.5.5 as well when I tried:

    ionic plugin add https://github.com/Telerik-Verified-Plugins/Stripe --variable API_KEY=STRIPE_SECRET_API_KEY

**Comment by eroh92** [comment]
Note, I'm assuming that this thread is reporting that when you use the `--variable` flag, the variable doesn't get saved to the root package.json so you can use `ionic state restore` on other team's machines, build boxes, etc.

**Comment by keyvanfatehi** [comment]
in my experience trying to use this with the [facebook plugin](https://github.com/Wizcorp/phonegap-facebook-plugin) i discovered that `ionic add` does edit the package.json correctly, however a `restore` or even a `reset` does not install the plugin correctly. the facebook plugin directly actually becomes completely empty. i did use the http url. for now I am installing the plugin via bash script immediately after `ionic restore`

**Comment by eroh92** [comment]
The facebook plugin is an exception as you need to have a copy of it
locally in order for it to install:
https://github.com/Wizcorp/phonegap-facebook-plugin#-----cordova-registry-warning-ios

**Comment by keyvanfatehi** [comment]
i would argue that because the `locator` attribute is set to a git repository, it is expected that under the hood ionic would locally clone the repo down and try to add it, thereby complying with that warning.

**Comment by peek4y** [comment]
Ionic: v1.6.4
Cordova: v5.1.1

It isn't working, when I tried to add the google plugin.

Command: ionic plugin add ionic plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=<CLIENT_ID>

And below was the result in package.json, variables object is pretty much empty

"locator": "https://github.com/EddyVerbruggen/cordova-plugin-googleplus",
      "id": "cordova-plugin-googleplus",
      "variables": {
            "": ""
      }

**Comment by BennettSmith** [comment]
@peek4y I believe you are running into the same issue I was having with using --variable.  See https://github.com/driftyco/ionic-app-lib/pull/26 for the details and a possible solution.

**Comment by yankustefan** [comment]
Hi @maksymilian-majer @jbavari 

Just a quick question.
This has been closed but I'm not sure if this resolved.
If I add a plugin with variables, it saves to config.xml but not to package.json

Is it supposed to work that way and do we need to add the config to package.json manually?

Thank you for your input.

**Comment by yankustefan** [comment]
With the command `ionic state save` the plugins are saved to config.xml
But the variables are ignored. Is that okay?
