### ISSUE TITLE
bug: Error runing ionic build for crosswalk 

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#431]
_From @jacargentina on April 28, 2015 13:35_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I've added crosswalk browser to my project, and when i try to build i get this.

````
ionic build
running cordova build
Running command: /home/my_user/javascript/mobile-ionic/hooks/after_prepare/010_add_platform_class.js /home/my_user/javascript/mobile-ionic
Running command: /home/my_user/javascript/mobile-ionic/platforms/android/cordova/build 
ANDROID_HOME=/opt/android-sdk-linux
JAVA_HOME=/usr/java/jdk1.8.0_05/
Running: /home/my_user/javascript/mobile-ionic/platforms/android/gradlew cdvBuildDebug -b /home/my_user/javascript/mobile-ionic/platforms/android/build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

/home/my_user/javascript/mobile-ionic/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/my_user/javascript/mobile-ionic/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/my_user/javascript/mobile-ionic/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/my_user/javascript/mobile-ionic/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /home/my_user/javascript/mobile-ionic/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
````

**But**, if i do 

    cordova build android

it first downloaded all the "gradle" things, and everything builds just fine.

Maybe its something about "paths" when running from inside **ionic build** ?</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3635_

**Comment by perrygovier** [comment]
_From @Stiveknx on April 30, 2015 17:50_

Try with the last version of ionic-cli, for me it works fine.
Also, removing crosswalk and crosswalk plugin, then adding it again may solve the problem too (once it happened to me.

Also you my try to report this issue to:
https://github.com/driftyco/ionic-cli

Since it's more specific to the cli ...

**Comment by perrygovier** [comment]
_From @jacargentina on April 30, 2015 18:14_

@Stiveknx I 've tried updating ionic-cli to latest (CLI v1.3.21) and then:

    ionic browser rm crosswalk
    ionic browser add crosswalk
    ionic build

I get the very same error. Also i dont understand the part you wrote "crosswalk plugin". May be there is something missing on my "delete and reinstall crosswalk" sequence?

**Comment by perrygovier** [comment]
_From @jacargentina on May 7, 2015 12:49_

More info about this: It is somehow related to IPv6/IPv4. I've found the error from gradle when it doesnt work (running **ionic build**):

    09:38:30.718 [ERROR] [org.gradle.messaging.remote.internal.inet.TcpIncomingConnector] Cannot accept connection from remote address /192.168.1.5.

But launching with cordova (running **cordova build**):

    09:42:22.620 [DEBUG] [org.gradle.messaging.remote.internal.inet.TcpIncomingConnector] Accepted connection from /0:0:0:0:0:0:0:1:46102 to /0:0:0:0:0:0:0:1:55250.

So, when running from ionic, it tries to connect to gradle via IPv4, but when doing via plain cordova, somehow it uses an IPv6.... Any advice?

**Comment by perrygovier** [comment]
I'm going to hand this off to the CLI Repo

**Comment by mankindsoftware** [comment]
### Corrupted "gradlew.bat" File
I get a similar error that may pertain to this issue. I found that the "android/gradlew.bat" file that is generated after "ionic run android" is corrupt, as below:

``` bat
:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto init

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail
```
Removing the first 'set JAVA_HOME...' line allows me to continue my workflow.

``` bat
:findJavaFromJavaHome
set JAVA_EXE=%JAVA_HOME%/bin/java.exe

if exist "%JAVA_EXE%" goto init

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.

goto fail
```
### Ionic Info

``` bat
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic CLI Version: 1.4.3
Ionic App Lib Version: 0.0.19
OS: Windows 7 SP1
Node Version: v0.10.35
```

### Original Error
``` bat
C:\ionic\ionC3>ionic build android
Updated the hooks directory to have execute permissions
Running command: "C:\Program Files\nodejs\node.exe" C:\ionic\ionC3\hooks\after_prepare\010_add_platform_class.js C:\ionic\ionC3
add to body class: platform-android
Running command: C:\ionic\ionC3\platforms\android\cordova\build.bat
ANDROID_HOME=C:\android\android-sdk\
JAVA_HOME=C:\Progra~1\Java\jdk1.8.0_45
Running: C:\ionic\ionC3\platforms\android\gradlew cdvBuildDebug -b C:\ionic\ionC3\platforms\android\build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\ionic\ionC3\platforms\android\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [id 'android']
   > Plugin with id 'android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.926 secs

C:\ionic\ionC3\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\ionic\ionC3\platforms\android\gradlew cdvBuildDebug -b C:\ionic\ionC3\platforms\android\build.gradle -Dorg.gr
adle.daemon=true"
ERROR building one of the platforms: Error: C:\ionic\ionC3\platforms\android\cordova\build.bat: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: C:\ionic\ionC3\platforms\android\cordova\build.bat: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\Mark\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

**Comment by HriBB** [comment]
+1

I had the exact same error today, had to remove platforms folder to make it work.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of the ionic cli?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by Wahid-Abdul** [comment]
Adding and removing platforms solved it for me

**Comment by tusharkkumar** [comment]
**fix is here** (FOR WINDOWS ONLY)

I am facing the same problem of Build then i finally found out the solution.<br><br>


**SOLUTION**<br>
So You must have the Android Api 23 in order for this command to work.<br>
Error of Daemon process will be solve after installing the Api 23 and extra <br>build tools and run command <br>
COMMAND : cordova build android --release<br>
I am sure this fix would help you to solve the problem.


**STEPS**<br>
1. First check the version of android through this COMMAND:
   cordova platform help <br>
2. Run the build command after installing the Api 23 and extra build tools.<br>
3. If Even this not work then Try add the variable in the <br>
 Environment variables > System variables > <br>
 add _JAVA_OPTIONS and value = -Xmx512M

Then Run cordova build android --release

BUT FIRSTLY SET UP THE ENVIRONMENT VARIABLES <br>
[Environment Variable setup Image][2]<br>
[android API 23][1]


**COPY FROM HERE** <br>
ENVIRONMENT VARIABLES:-

1. **USER VARIABLES**<br>
 **PATH** <br>
 C:\Ruby23\bin;C:\Users\kumar\AppData\Roaming\npm;C:\ANDROID_SDK\tools;%SystemRo
 ot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;


2.  **SYSTEM VARIABLES** <br>
  **ADD NAME AND VALUE** <br>
  2.1  **_JAVA_OPTIONS**   -Xmx512M <br>
  2.2  **ANDROID_HOME**    C:\ANDROID_SDK <br>
  2.3  **PATH** -> <br>
 	C:\ProgramFiles\Java\jdk1.8.0_60\bin;C:\ProgramFiles\nodejs;C:\Gradle\gradle-4.0\bin;C:\ANDROID_SDK\tools;%SystemRoot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;%SystemRoot%\system32; %SystemRoot%; %SystemRoot%\System32\Wbem;


  [1]: https://i.stack.imgur.com/wLI0J.png
  [2]: https://i.stack.imgur.com/M5InU.png
