### ISSUE TITLE
ionic: command not found

### ISSUE THREAD

**Issue by l-ll** [driftyco/ionic-cli#432]
after install ionic with `sudo npm install ionic -g` in mac,
can't run  ionic command.
also can't find ionic in /usr/lcoal/bin/ 
Please help me  :sob:

**Comment by l-ll** [comment]
probably due to network..   - -##

**Comment by XKushal** [comment]
same issue. were u able to figure out?

**Comment by XKushal** [comment]
> after install ionic with `sudo npm install ionic -g` in mac,
> can't run ionic command.
> also can't find ionic in /usr/lcoal/bin/
> Please help me 😭

same issue. were u able to figure out?

**Comment by Sachinbekre** [comment]
same issue
-bash: ionic: command not found

**Comment by abarkhuysen** [comment]
same issue
-bash: ionic: command not found
