### ISSUE TITLE
Live Reload failed to start, error:  (CLI v1.4.5)

### ISSUE THREAD

**Issue by mark-veenstra** [driftyco/ionic-cli#434]
I have several Ionic projects on the same laptop. If I try to run `ionic serve` on the biggest and most important project I get the following error:

    Live Reload failed to start, error:  (CLI v1.4.5)

	Your system information:

	Cordova CLI: 4.3.0
	Gulp version:  CLI version 3.8.11
	Gulp local:   Local version 3.8.11
	Ionic Version: 1.0.0-beta.14
	Ionic CLI Version: 1.4.5
	Ionic App Lib Version: 0.0.22
	OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.04 
	Node Version: v0.10.25

Strange thing is if I run `ionic serve` on a different project it just starts serving the project. Above serving error appears since today. Yesterday I had no problem at all on the same project.

What can I do to debug the issue? Because the project that does serve also has exact same versions for all tools/libs/cli. So no difference there.

I also tried to change the address and serving port or setting them manual, but all without success.

**Comment by jbavari** [comment]
Can you try running it with `--verbose` and see if any more helpful output comes about?

**Comment by mark-veenstra** [comment]
Well today I tried to get some debug logging, but all works on all projects. I will see in the next days if the issue arises again if not I will close this issue.

**Comment by unek** [comment]
Had the same problem, ran `ionic serve` with `--verbose` and got an "ENOSPC" error. [This fix](https://github.com/gruntjs/grunt-contrib-watch/issues/236#issuecomment-58895341) worked.

**Comment by mark-veenstra** [comment]
This could be the case on that moment for me also. I did had some errors in PHPStorm that day which also referenced to the `fs.inotify.max_user_watches`. So this issue seems to be fixed.

**Comment by LBenzahia** [comment]
The post suggest running this to increase the number of watches that are available.
please run this command line and all will be work fine 
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by paladini** [comment]
@LBenzahia Your command worked for me.
