### ISSUE TITLE
bug: ionic upload does not consider anchor when adding cachebusters

### ISSUE THREAD

**Issue by simplesmiler** [driftyco/ionic-cli#435]
Original asset url:
```html
<script src="asset.js#hash"></script>
```
Expected to turn into:
```html
<script src="asset.js?ionicCachebuster=<number>#hash"></script>
```
But instead turns into:
```html
<script src="asset.js#hash?ionicCachebuster=<number>"></script>
```

Causes https://github.com/driftyco/ionic-view-issues/issues/107.

**Comment by jbavari** [comment]
@simplesmiler I see what's going on. I've talked to @tlancina about it, and we've come up with a solution.

I've got a few other tasks to tend to before getting to this.

If you have any ideas or solutions in the meantime, I'd be happy to work with you on them.

Thanks for reporting the issue!

**Comment by simplesmiler** [comment]
Should I make a PR?

**Comment by jbavari** [comment]
I would really appreciate if you did, I'd be able to help you out with it as well once my time frees up a bit more.

I've got to port the setup command to the ionic app lib, get some tests in place, get some comm stuff out about the CLI, doc updates, then I can get to this.

**Comment by simplesmiler** [comment]
Possible solution: https://github.com/simplesmiler/ionic-cli/commit/0016e425d25f3cbec549f6ca405ce03380e62bbd

Should I submit PR against master or against develop?

**Comment by emve-dev** [comment]
Funny thing.
Despite the fact that running `ionic upload` gives me this error `Upload Failed: [Error: CERT_UNTRUSTED]` the app is uploaded!

**Comment by simplesmiler** [comment]
@emve-dev wrong issue?

**Comment by emve-dev** [comment]
@simplesmiler yes. sorry :)

**Comment by jbavari** [comment]
@simplesmiler I'll be pulling this commit in manually. I've just written some tests to verify this works correctly, and it does!

Thanks for the submission!

**Comment by simplesmiler** [comment]
@jbavari glad to help!
