### ISSUE TITLE
ionic serve option for pointing to a default app state/url on automatic restart

### ISSUE THREAD

**Issue by Lorthirk** [driftyco/ionic-cli#436]
Hello. I think that ionic serve should have an option to specify a default url to be used when an automatic restart occurs due to a save to an html or js file, or at least an option to go to the root state of the app. In my app, when I edit a js file, i manually have to point to the main state/url or the necessary initialization won't occur.

**Comment by jbavari** [comment]
@Lorthirk Thanks for the idea. Can you provide a little more concept clarification? I think I understand what you're getting at, something like:

Start server
Set start url/state
Make changes in JS
Page reloads to url/state

Is that what you are suggesting?

**Comment by Lorthirk** [comment]
exactly, and sorry if I wasn't so clear in the first place... I was in a little hurry :)

even better could be a startup parameter, like

```
ionic serve --default-path=/#/path/to/main/state 
```
or something similar

**Comment by jthoms1** [comment]
I do not believe that this is an enhancement that we would like to include in future releases of the CLI.  It is a simple convenience that could add some unneeded complexity. Thanks!
