### ISSUE TITLE
bug: Hooks Folder Not Found (Windows)

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#437]
_From @cgosiak on May 21, 2015 14:55_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>command:
ionic build android

results:
Error { [Error: ENOENT, no such file or directory 'C:\Users\cgosiak\Documents\hoonuit_app\hooks']
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\Users\\cgosiak\\Documents\\hoonuit_app\\hooks',syscall: 'scandir' }
Updated the hooks directory to have execute permissions

further info:
pulling code using 'git', same 'git' used on mac and no issues are found. I have tried pulling the repository multiple times to different local locations on machine. All resulting in the same outcome.

Works on mac fine with identical code, does not work on windows</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3798_

**Comment by jasperkuperus** [comment]
I have the same issue on mac.

**Comment by jbavari** [comment]
A few questions for @cgosiak and @jasperkuperus 

Does the `hooks` folder exist and the command fails for it not existing? Or does the folder not exist?

**Comment by jasperkuperus** [comment]
Ok, yesterday I had this problem. Somehow it got fixed, not sure how. But when I had this problem yesterday, the `hooks` folder did not exist. If I made the `hooks` folder myself, it somehow got deleted, rendering this same error. I played around with these commands yesterday:

`ionic platform add ios`, `ionic platform add android` and `ionic emulate -l --livereload-port=35728 ios --all --tall`

Unfortunately I can not reproduce it at this time, maybe @cgosiak can diagnose some more?

**Comment by cgosiak** [comment]
I believe I have found a fix, after uninstalling everything and restarting from a new OS I have fixed my issues. In MY CASE anyways...

Cordova was at too new of a version; I downgraded to Cordova V4.3.0 and retried everything. In the case the Hooks directory is not found/created simply run: `ionic hooks add`

You can use NPM to install a certain version of Cordova that will automatically rewrite the old "newer" version.

After this everything should be working again...

**Comment by sum7k** [comment]
I was typing the command in the wrong folder :(

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of the ionic cli and the latest version of cordova?

**Comment by jasperkuperus** [comment]
Haven't encountered this error in a long while!

**Comment by jgw96** [comment]
Awesome! Gonna go ahead and close this issue for now. If anyone is still having this issue feel free to comment and ill reopen. Thanks for using Ionic!

**Comment by Monikashri** [comment]
now am facing the same issue, for me Hooks folder was created. can you pls tell me the fix?

**Comment by saurabhgoyal12** [comment]
Make sure you are running command from project directory.

**Comment by totallytotallyamazing** [comment]
To solve this problem on macOS Sierra 10.12.3 I had to place myproject in the root directory. This is not ideal but it is currently working for me.

**Comment by alkheyal** [comment]
hi i have problem 

 Hooks Folder Not Found in my (Windows)

**Comment by animeshbuie** [comment]
Same issue here

```
> ionic start
Starting Ionic Project wizard...
Using directory as root: D:\xampp7\htdocs\ionic
√ Running start wizard:  http://localhost:8900/
Creating an Ionic 2.x app in D:\xampp7\htdocs\ionic\inspectionSuite based on the sidemenu template.

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Creating an Ionic 2.x app in D:\xampp7\htdocs\ionic\inspectionSuite based on the sidemenu template.

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip
Installing npm packages (may take a minute or two)...
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip
Installing npm packages (may take a minute or two)...
Error: %s Error: ENOENT: no such file or directory, scandir 'D:\xampp7\htdocs\ionic\inspectionSuite\hooks'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.setHooksPermission (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\hooks.js:120:24)
    at Object.Start.initCordova (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\start.js:767:9)
    at C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\start.js:112:20
    at _fulfilled (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
npm WARN deprecated cordova-plugin-console@1.1.0: This plugin has been deprecated since it is now included in the latest versions of cordova-ios
Error: %s Error: ENOENT: no such file or directory, scandir 'D:\xampp7\htdocs\ionic\inspectionSuite\hooks'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.setHooksPermission (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\hooks.js:120:24)
    at Object.Start.initCordova (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\start.js:767:9)
    at C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\start.js:112:20
    at _fulfilled (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Users\Animesh\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
^CTerminate batch job (Y/N)?y
```

**Comment by dwieeb** [comment]
This is a very old issue. Please ensure you have the latest Ionic CLI (3.20.0 at time of writing). If the issue persists, please create a new issue and fill out the issue template. Thanks!
