### ISSUE TITLE
bug: CLI doesn't set exit code properly

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#438]
_From @fahhem on May 22, 2015 0:4_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If I have some invalid Android code and I run "ionic build", the exit code is set to 0 despite red build errors littering the screen. With it set to 0, I can't do something like this:

ionic build && notify-send Build worked || notify-send Build failed</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3806_

**Comment by tsubik** [comment]
+1 for this

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
