### ISSUE TITLE
No access to "ionic serve" location from "outside"?

### ISSUE THREAD

**Issue by ibewugb** [driftyco/ionic-cli#442]
Hi there I tried to run "ionic serve -ad" and then access the server from my iPhone which is in the same network.

It can not load the page (<computer_ip:8100>) the server is not responding. When I open <computer_ip:8100> on the machine running the command, its all fine.

I know that it was possible a while ago. Did you change s.th.?

**Comment by jbavari** [comment]
I'm investigating the issue.

**Comment by jbavari** [comment]
Would you mind leaving the output from your `ionic info` command here?

It appears to be working fine in version 1.4.5 of the Ionic CLI.

I can access it from my machine, which is a Mac, on these addresses:

http://localhost:8100
http://0.0.0.0:8100
http://172.16.1.124:8100

**Comment by ibewugb** [comment]
Hi, I tried it on my mac and it's working fine. The problem is just on my windows 8 computer.
The output is: ionic serve -a
Running live reload server: http://localhost:35729
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Running dev server: http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $

**Comment by ibewugb** [comment]
Here is my ionic info:
Your system information:

Cordova CLI: 5.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
OS: Windows 8.1
Node Version: v0.12.2


When I run it via a local XAMPP it's all fine

**Comment by jbavari** [comment]
@ibewugb I understand. I will try out on my Windows 8 machine now.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of the ionic cli?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by carlosrodrigome** [comment]
ionic serve --all works well on ionic 2 beta 11
