### ISSUE TITLE
Error packaging project, please try again later

### ISSUE THREAD

**Issue by ibewugb** [driftyco/ionic-cli#443]
Hi, every time I try to use the ionic package command I get the message: Error packaging project, please try again later

It does not matter if I select ios android debug or release.

# My settings:
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.4.0 
ios-sim version: 3.0.0 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.1 Build version 6D1002 

# Console output:
ionic package debug ios 
Loading Foo...
iOS Certificate File (.p12): /Volumes/xxx.p12 
Certificate Password: 
iOS Mobile Provisioning Profile (.mobileprovision): /Volumes/xxx.mobileprovision 

Uploading app...
ios debug building...
Error packaging project, please try again later

**Comment by facconi** [comment]
I have the same error.

My system information are:

Your system information:

```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.10.29
Xcode version: Xcode 6.3.2 Build version 6D2105 
```

**Comment by linkito** [comment]
I have the same problem 

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.4.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.0
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by jbavari** [comment]
Unfortunately, we will be suspending this feature and removing it currently from the CLI until some time in the future.

Sorry for the inconvenience.
