### ISSUE TITLE
body is not defined (CLI v1.4.5)

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic-cli#449]
when I do ionic share, the following error shows up.

    An uncaught exception occured and has been reported to Ionic

    body is not defined (CLI v1.4.5)

    Your system information:

    Cordova CLI: 5.0.0
    Gulp version:  CLI version 3.8.11
    Gulp local:   Local version 3.8.11
    Ionic Version: 1.0.0
    Ionic CLI Version: 1.4.5
    Ionic App Lib Version: 0.0.22
    ios-deploy version: 1.5.0
    ios-sim version: 3.1.1
    OS: Mac OS X Yosemite
    Node Version: v0.12.0
    Xcode version: Xcode 6.3.2 Build version 6D2105

after digging into the source code, found out that the http request returned 403 Forbidden

    POST https://apps.ionic.io/api/v1/app/my_app_name/share

tried the share feature on website, worked fine which used the same endpoint.
suspect it is the csrftoken not setup in the correct place in the share cli form submithttps://apps.ionic.io/api/v1/app/uberforhealthcare/share

**Comment by sambranco** [comment]
you forgot to upload your app. `ionic upload` and then you can share it with `ionic share`

**Comment by jbavari** [comment]
@3dd13 Did you upload the app before trying to share it?

@sambranco - This [commit](https://github.com/driftyco/ionic-cli/commit/8fbaa5c9f27b96eb84738c32fff8e02be098e8fc) should alert the user to upload the app first before attempting to share it.

**Comment by 3dd13** [comment]
I was not able to upload because of another issue #450
now everything is working fine.

thanks for following up !
