### ISSUE TITLE
perf: Problem in USB Debugging

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#457]
_From @rizvanhaider on June 2, 2015 15:19_

**Type**: <span ionic-type>perf</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi! you are working great! 
I am getting a problem after my new installation of window and up-gradation of ionic+cordova. When I run the command [ionic run android] to debug the app directly with device it does not installs the app on the device but the command prompt shows the message that launch successful but actually the app is not installed.
I can only test the app by manually copying and installing of .apk file from the platforms\android\build\outputs\apk directory to my phone.
![screenshot 9](https://cloud.githubusercontent.com/assets/9403438/7939384/4225619c-0964-11e5-97f6-28e1b9ddc7cf.png)
. </span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3876_

**Comment by mhartington** [comment]
Can you try `ionic run android --device`

**Comment by mhartington** [comment]
_From @rizvanhaider on June 2, 2015 18:25_

having still same issu... :(

**Comment by mhartington** [comment]
Could you provide the output of `ionic info`

**Comment by mhartington** [comment]
_From @rizvanhaider on June 3, 2015 11:5_

Following is the ionic info



![screenshot 10](https://cloud.githubusercontent.com/assets/9403438/7958616/611341ea-0a0a-11e5-9a50-35a785c71d0e.png)

**Comment by rizvanhaider** [comment]
I recognized that this is the problem with cordova-cli, any suggestion that how to deal with this problem now?

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
