### ISSUE TITLE
ionic add fails with unhelpful message if bower is not already installed

### ISSUE THREAD

**Issue by mirkonasato** [driftyco/ionic-cli#458]
$ npm uninstall -g bower
$ ionic add ionic-service-core
Failed to find the bower component "ionic-service-core".
Are you sure it exists? (CLI v1.5.0)

$ npm install -g bower
$ ionic add ionic-service-core
Bower component installed - ionic-service-core

It probably displays the same "failed to find" message for other conditions as well, see
http://forum.ionicframework.com/t/failing-to-install-ionic-service-core/25766

**Comment by bizmate** [comment]
I have just seen the same, after installing bower all works, thanks mirko. not a node guy but it should be auto installing bower if the problem is its dependency

**Comment by anderson631** [comment]
It worked after his instructions. Thanks!

**Comment by wblondel** [comment]
Thank you! You solved my problem :-)

**Comment by rhenosan** [comment]
i think is about blocked internet connection. try installing using other network, or u can use app hotspot shield , after activate hotspot shiled, try again, its work.

**Comment by wblondel** [comment]
@rhenosan I don't think so, because I had the same error message and I solved the problem by installing bower

**Comment by RahulBhammarker** [comment]
I had the same error on Ubuntu 14.04. I fix it changing ownner in both .config and .cache directories with this command sudo chown -R [user name] ~/.config and sudo chown -R [user name] ~/.cache hope works for others.

**Comment by amacfie** [comment]
Thanks @RahulBhammarker - I'm on Ubuntu 14.04 and `npm install -g bower` didn't solve the problem but your suggestion did

**Comment by cre80vty** [comment]
Had the same issue on OSX, fixed it using 
`chmod 755 .config`
This changes the permissions of the folder to rwxr-xr-x

**Comment by jgw96** [comment]
Hello all! I am going to close this as we do not use bower anymore. Thanks for using Ionic!
