### ISSUE TITLE
`ionic emulate` doesn't populate the `CORDOVA_PLATORMS` environment variable for `before_prepare` hook.

### ISSUE THREAD

**Issue by markomarkovic** [driftyco/ionic-cli#463]
I've noticed this with the `before_prepare` hook, but it's possible that others are also affected. See [this gist](https://gist.github.com/markomarkovic/adcae0aae5b356561b5f) for a simple test.

```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.2 Build version 6D2105 
```

**Comment by jbavari** [comment]
Currently the Ionic CLI is just wrapping up the Cordova CLI.

What happens when you do `cordova emulate ios`? Does that populate the variables correctly?

**Comment by markomarkovic** [comment]
I've just replicated the issue on linux with android platform, and indeed, the error seems to be in cordova. When running `cordova emulate android`, the `before_prepare` hook does not populate the variables.

**Comment by markomarkovic** [comment]
I've opened [the issue on cordova issue tracker](https://issues.apache.org/jira/browse/CB-9142).

**Comment by jgw96** [comment]
Hello all! Is this still an issue?

**Comment by markomarkovic** [comment]
I've just tested it with cordova 6.1.1 and it appears to be fixed.
