### ISSUE TITLE
Sending to an ios device and lldb issue

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#466]
Sorry for the somewhat vague title. If I do:

    ionic run ios --device

I can't exit lldb by typing exit. I can type, but nothing happens. I have to ctrl+c and then kill the process.

Doing:

    cordova run ios --device

lets me exit lldb cleanly.

**Comment by bholmes451** [comment]
I can confirm the above is correct. If you launch from within Ionic keystrokes are not being passed through to the lldb application.

**Comment by fabiosussetto** [comment]
same here

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
