### ISSUE TITLE
bad network

### ISSUE THREAD

**Issue by iMohammadd** [driftyco/ionic-cli#467]
i cant install with npm because i have a bad internet connection

npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "-d" "ionic"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

can i download your package in a single file and install that offline?

**Comment by fancyer** [comment]
same problem

**Comment by Chumomo** [comment]
me too!

**Comment by xuelvming** [comment]
Right, It's really really annoying, that I have to connect to the internet and download the Master.zip everytime I run a simple Cli command, can't just be cached.

**Comment by spaquet** [comment]
I just want to let you know that I have the same issue, as reported in https://github.com/npm/npm/issues/8196\#issuecomment-162336470, on OS X version 10.11 with nam 3.3.12, **but, in my case, network is working super and there is no proxy....**

Ionic is so far the only nam package that does not install or upgrade.

**Comment by super-coder** [comment]
same here. Everything except Ionic install. It's not a network issue

**Comment by nileshlg2003** [comment]
same problem here on OS X,

``` npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.144:80 - Local (192.168.1.111:49542)
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/npm-debug.log ```

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
