### ISSUE TITLE
ionic upload failed

### ISSUE THREAD

**Issue by herve1976** [driftyco/ionic-cli#470]
$ ionic upload
Uploading app....

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:185:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Unexpected token < (CLI v1.5.0)

Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by markphillips100** [comment]
I had similar issues but a different character: SyntaxError: Unexpected token /

I had some comments in my config.xml and my fetch.json file.  Removed the comments and the upload worked.

**Comment by triniwiz** [comment]
getting the same error

**Comment by triniwiz** [comment]
ok did some digging the problem only happens if i set an  --io-app-id or ionic link  if left blank upload works fine

**Comment by triniwiz** [comment]
The response in Upload.getDirectUploadKey is generating a 404 only if the app_id is set

**Comment by jbavari** [comment]
Is this good to close?

**Comment by triniwiz** [comment]
no still getting the same error

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:186:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Unexpected token < (CLI v1.5.5)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.2 LTS 
Node Version: v0.12.5

```

**Comment by LunarDevelopment** [comment]
:+1:  
I'm getting this issue too, I'll try and verbose it later when I'm home, but all mine was saying was
``` 
Uploading app....
Upload failed.

Your system information:
<< to be updated >> 

```

**Comment by medinarodelsamson** [comment]
+1 on error

Uploading app....

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:186:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Unexpected token < (CLI v1.5.5)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.0
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by medinarodelsamson** [comment]
Follow up: I re-run the `ionic upload` and worked successfully.

**Comment by LunarDevelopment** [comment]
I've tested ionic upload since issue started and it seems to be the internet connection, Ionic refuses upload from dynamic ips, e.g starbucks, my work where we use complicated proxy server set ups. While it works fine on home connection / static IP server at work.

**Comment by triniwiz** [comment]
upload only works if you don't assign a --io-ap-id

**Comment by smoj** [comment]
Just had the same upload failed problem (upload.js). Running a Windows 8 machine.
I solved it by running **npm update** in my node_modules folder at 
**C:\Users\<Your WIndows account>\AppData\Roaming\npm**.

It worked after that.

**Comment by fionagithub** [comment]
i have a error ,when i use ionic upload app,it shows ' An uncaught exception occurred and has been reported to Ionic  Unexpected token / (CLI v1.6.5)'!i need ur help.plz give me some suggestion.thx~

**Comment by tiarebalbi** [comment]
+1 

Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:296:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

Unexpected token < (CLI v1.7.13)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.4.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by jspenc72** [comment]
+1 
Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:296:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Unexpected token < (CLI v1.7.14)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.4.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68

**Comment by mfkenson** [comment]
$ ionic upload
Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:296:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

Unexpected token < (CLI v1.7.14)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by yadunandan004** [comment]
guys I had the same problem, but then tried building it in ios and android via commands:

ionic build ios
ionic build android

Later ionic upload worked fine.

**Comment by Flofie** [comment]
I think ionic had some backend troubles. I also had this issue. So I tried the web-login and got an application error. After a few minutes the login worked again. So the problems seems to be fixed.

**Comment by ishanika** [comment]
i had the same issue. But when you re run "ionic upload" again it work fine. so weird.

**Comment by mluis** [comment]
+1

Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:296:25)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)

Unexpected token < (CLI v1.7.14)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by z-lake** [comment]
+1 

Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:296:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Unexpected token < (CLI v1.7.14)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.3
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68

**Comment by jorisw** [comment]
+1

```
$ ionic upload
Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:296:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

Unexpected token < (CLI v1.7.14)

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.0 Build version 7A218 
```

**Comment by jorisw** [comment]
FWIW, to other readers: what's happening is that `ionic upload` expects a JSON formatted response from the ionic.io API, but instead gets something beginning with a `<`, most likely something like a `<html><body>Error 502: Bad Gateway</body></html>`. Best to sit it out and try again later.

**Comment by jorisw** [comment]
In my case, this happened because I set my own `app_id` in `ionic.project`, thinking it should be a bundle identifier. Remove it (set it to `""`) and try again, or see if you might have deleted the app from your dashboard.

**Comment by zulhfreelancer** [comment]
Running `ionic upload` again works for me.

**Comment by kishorekumaru** [comment]
+1Uploading app....
An error occurred uploading the build: SyntaxError: Unexpected token <

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:296:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Unexpected token < (CLI v1.7.14)

Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.5
Xcode version: Xcode 7.2 Build version 7C68

**Comment by kishorekumaru** [comment]
`$ ionic upload `worked after running `$ionic build ios`

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of the ionic cli? Thanks for using Ionic!

**Comment by jspenc72** [comment]
I have experienced the issue with the latest version when re-uploading a project which was already previously uploaded by another user. 

Steps to replicate the error :
1. Create an ionic app, run ionic upload..
2. Delete the json file containing the Ionic app Id.
3. Rerun ionic upload. 

Best, 
Jesse

**Comment by cnngraphics** [comment]
**Solution**
ionic platform remove android

now in your ionic.config.json file on line 3, remove the app id string
example if you have
`{
                    "name": "appName",
                    "app_id": "com.appbuilingr.httplocalbuilderpagedashboard.blogjobs"
                }`
This becomes
`{
                    "name": "appName",
                    "app_id": ""
                }`

Then run "ionic plarform add android"
then 
"ionic upload"

**Comment by mmahgoub** [comment]
Getting this:
```
Caught exception:
 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/io-config.js:169:24
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by mmahgoub** [comment]
For some reason `/.io-config.json` got replaced by an empty string did a git diff and recovered the contents of the file which contains app_id and api_key 
`{"app_id":"myid","api_key":"mikey"}`

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
