### ISSUE TITLE
ionic build --release browser generates broken zip archive

### ISSUE THREAD

**Issue by caiiiycuk** [driftyco/ionic-cli#472]
How to reproduce:
* ionic start myApp maps
* cd myApp
* ionic platform add browser
* ionic build --release browser
* zip -T platforms/browser/build/package.zip

Error:
```sh
error:  invalid compressed data to inflate ./lib/ionic/fonts/ionicons.ttf
test of platforms/browser/build/package.zip FAILED
```

We want to build CI system for our ionic app, but we can`t because exit code of unzip process is not zero.

**Comment by mrthehud** [comment]
I'm seeing something similar, mostly affecting a selection of images. It's consistently affecting the same images, which I've attached, though I'm not sure if it's the images, or their position in the zip which has problems.

```
james@tower:~/Jobs/Kafoodle/Code/App$ zip -T platforms/browser/build/package.zip
  error:  invalid compressed data to inflate ./css/fonts/ionicons.eot
  error:  invalid compressed data to inflate ./img/default-dish-icon.png
  error:  invalid compressed data to inflate ./img/default-outlet-icon.png
  error:  invalid compressed data to inflate ./img/fhrs-images/FHIS/fhis_improvement_required.jpg
  error:  invalid compressed data to inflate ./img/fhrs-images/FHRS/fhrs_0_en-gb.jpg
  error:  invalid compressed data to inflate ./img/fhrs-images/FHRS/fhrs_4_en-gb.jpg
  error:  invalid compressed data to inflate ./img/fhrs-images/FHRS/fhrs_5_en-gb.jpg
  error:  invalid compressed data to inflate ./img/map/sprites.png
test of platforms/browser/build/package.zip FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
```
I've attached both img/fhrs-images/FHRS/fhrs_0_en-gb.jpg and img/fhrs-images/FHRS/fhrs_1_en-gb.jpg - 0 fails, 1 has no problems (as well as many others) - in case they help.
![fhrs_0_en-gb](https://cloud.githubusercontent.com/assets/140144/8875635/859a9272-3212-11e5-86ff-852c64a9a2c3.jpg)
![fhrs_1_en-gb](https://cloud.githubusercontent.com/assets/140144/8875636/85a00928-3212-11e5-8098-b671c1bfe6d5.jpg)

**Comment by adamdbradley** [comment]
Greetings @caiiiycuk!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by mark-veenstra** [comment]
Errors are still there with ionic 1.2.1, when I test a zip file on Ubuntu I still have the same errors on a build browser release.

**Comment by caiiiycuk** [comment]
+1

**Comment by electrobabe** [comment]
same with 1.2.4 on windows7, extracting the zip with winrar 5.31:

    \platforms\browser\build\package.zip: Checksum error in audio\shaker.wav. The file is corrupt
    \platforms\browser\build\package.zip: Checksum error in img\ic_reload.png. The file is corrupt
    \platforms\browser\build\package.zip: Checksum error in lib\ionic\release\fonts\ionicons.eot. The file is corrupt
    \platforms\browser\build\package.zip: Checksum error in lib\ionic\release\fonts\ionicons.woff. The file is corrupt
    \platforms\browser\build\package.zip: The archive is corrupt

**Comment by monavari-lebrecht** [comment]
for me the same with  1.7.16

**Comment by icopp** [comment]
This is definitely still a problem. I just ran into it myself.

**Comment by caiiiycuk** [comment]
I think someone should open new issue instead of this. I don`t want to open issue, because i don't use ionic anymore.

**Comment by bsavelev** [comment]
ionic --version
2.0.0
cordova --version
6.3.1

same here:
```bash
zip -T platforms/browser/build/package.zip  ;  echo $?
  error:  invalid compressed data to inflate ./build/fonts/noto-sans-bold.ttf
  error:  invalid compressed data to inflate ./build/fonts/noto-sans-regular.ttf
  error:  invalid compressed data to inflate ./build/fonts/roboto-light.ttf
  error:  invalid compressed data to inflate ./build/fonts/roboto-medium.ttf
  error:  invalid compressed data to inflate ./build/fonts/roboto-regular.ttf
  error:  invalid compressed data to inflate ./img/appicon.png
  error:  invalid compressed data to inflate ./img/themes/1/001.jpg
  error:  invalid compressed data to inflate ./img/themes/1/002.png
test of platforms/browser/build/package.zip FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
8
```

**Comment by bitperbit** [comment]
+1

**Comment by aszmyd** [comment]
The same with the most recent ionic cli `2.1.13`

**Comment by jameslan** [comment]
Still closed and won't be fixed?

**Comment by Flink91** [comment]
I also have this problem

**Comment by soumak77** [comment]
I'm having the same issue

**Comment by Richie765** [comment]
Please reopen, this is still a problem.

**Comment by reyazucar** [comment]
+1

**Comment by Sh1d0w** [comment]
FYI this is not an ionic bug, rather than Cordova-browser bug. In order to have not broken zip archive you can install the patched version from this PR https://github.com/apache/cordova-browser/pull/25

IDK why the original maintainers haven't fixed it yet.

**Comment by Richie765** [comment]
In case it wasn't clear yet, a work around is to just use the files located in `platforms/browser/www/`. They seem to be just fine.

**Comment by dsyrstad** [comment]
Still package.zip still has the same issue in ionic 3.0.1. It cannot be unzip. Using Ubuntu 16.04. Working around by manually zipping platforms/browser/www/.
