### ISSUE TITLE
how to bust the cache for `ionic resources`

### ISSUE THREAD

**Issue by mzarella** [driftyco/ionic-cli#473]
I made a few tweaks to my icon and my splash screen, rerain `ionic resources` and nothing changed

```
$ ionic resources --icon
Ionic icon resources generator ✓ 
icon android drawable-ldpi-icon.png (36x36) from cache ✓ 
icon android drawable-mdpi-icon.png (48x48) from cache ✓ 
icon android drawable-hdpi-icon.png (72x72) from cache ✓ 
...etc
```

How do you bust the cache to generate new icons and splash screens?

**Comment by mzarella** [comment]
Looks like this is the same as #420

**Comment by Allan-Nava** [comment]
In ionic v2 doesn't work this command `ionic resources --clean-cache`

**Comment by dwieeb** [comment]
@Allan-Nava Please always make sure you're using the latest CLI. See https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#upgrading-from-cli-v2
