### ISSUE TITLE
Ionic start command fails to complete after node and ionic-cli where updated

### ISSUE THREAD

**Issue by jamiegood** [driftyco/ionic-cli#481]
Hello there, 

Since I upgraded node and ionic-cli,  the 'ionic start' command fails to complete.

Here is the output when I run 'ionic start'

$ ionic start myApp tabs
Creating Ionic app in folder /export/www/myApp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================] 100% 0.0s
Downloading: https://github.com/driftyco/ionic-starter-tabs/archive/master.zip
[=============================] 100% 0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project
Adding in iOS application by default
npm http GET https://registry.npmjs.org/cordova-ios/3.8.01
An uncaught exception occured and has been reported to Ionic

Request path contains unescaped characters. (CLI v1.5.0)

Your system information:

Cordova CLI: 5.1.1
Gulp version: CLI version 3.9.0
Gulp local:
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by jamiegood** [comment]
So I've removed ionic, reinstalled and tried 'ionic start' again.

Now I get the following error - 

LP-MAC-JG-0415:www jgood$ ionic start jamieTestIonic
Creating Ionic app in folder /export/www/jamieTestIonic based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error updating config.xml file: Error: ENOENT, no such file or directory '/export/www/jamieTestIonic/config.xml'
There was an error finalizing the package.json file. { [Error: Cannot find module '/export/www/jamieTestIonic/package.json'] code: 'MODULE_NOT_FOUND' }
 ✗ Unable to save settings file: Error: ENOENT, no such file or directory '/export/www/jamieTestIonic/ionic.project'

looks like this is related to the same issue as #480

**Comment by jamiegood** [comment]
hmmm, it's working again for me. Strange.

**Comment by sunjoong85** [comment]
It's not working for me. I cleared all ionic npm modules and config file. But still not working

**Comment by bradcliffe** [comment]
I'm experiencing the same issue here.

**Comment by sunjoong85** [comment]
I add my stack trace.

1. error on finding config.xml and package.json  
  -> it might have something to do with the start.js promise logic

2. New! Add push notifications to your Ionic app with Ionic Push (alpha)!
 -> I checked false to use Ionic server push.  but  It's not going to work what I meant.

<Stack Trace>
D:\workspace>ionic start tt3
Creating Ionic app in folder D:\workspace\tt3 based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error updating config.xml file: Error: ENOENT, no such file or directory 'D:\workspace\tt3\config.xm
l'
There was an error finalizing the package.json file. { [Error: Cannot find module 'D:\workspace\tt3\
package.json'] code: 'MODULE_NOT_FOUND' }
 ✗ Unable to save settings file: Error: ENOENT, no such file or directory 'D:\workspace\tt3\ionic.pr
oject'

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd tt3

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs


New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
An uncaught exception occured and has been reported to Ionic



Cannot read property 'statusCode' of undefined (CLI v1.5.0)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
OS: Windows 7 SP1
Node Version: v0.12.4

**Comment by jamiegood** [comment]
FYI I removed the ionic npm module and reinstalled it
npm uninstall -g ionic
npm install -g ionic

I can now do 'ionic start myApp'

However I do see another error appear:
"An uncaught exception occured and has been reported to Ionic
Cannot read property 'statusCode' of undefined (CLI v1.5.0)"

But I have not noticed any issues caused by this.

**Comment by dizzy** [comment]
I have the same issue on a Windows machine and reinstalling ionic didn't do it. I also have an Ubuntu install where I don't have experience this problem.

**Comment by dizzy** [comment]
Here's my output

C:\Users\niculge\AndroidProjects>ionic start todo blank
Creating Ionic app in folder C:\Users\niculge\AndroidProjects\todo based on blan
k project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error updating config.xml file: Error: ENOENT, no such file or directory 'C:\Use
rs\niculge\AndroidProjects\todo\config.xml'
There was an error finalizing the package.json file. { [Error: Cannot find modul
e 'C:\Users\niculge\AndroidProjects\todo\package.json'] code: 'MODULE_NOT_FOUND'
 }
 ? Unable to save settings file: Error: ENOENT, no such file or directory 'C:\Us
ers\niculge\AndroidProjects\todo\ionic.project'

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd todo

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html


 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs


New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
An uncaught exception occured and has been reported to Ionic



Cannot read property 'statusCode' of undefined (CLI v1.5.0)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
OS: Windows 7 SP1
Node Version: v0.12.2

**Comment by tpalmer75** [comment]
Was getting this same error when running ionic setup sass

Fixed it with @jamiegood recommendation.

npm uninstall -g ionic
npm install -g ionic

**Comment by peterfei** [comment]
not working for me too...strange

**Comment by peterfei** [comment]
not working for me too...strange

**Comment by bsraju** [comment]
not working for me in windows 8.1

**Comment by pauloesantos** [comment]
Hi! Not Working for me too...

Creating Ionic app in folder D:\started based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error updating config.xml file: Error: ENOENT, no such file or directory 'D:\Pes
soais Paulo\Projetos\IONIC\Teste02\started\config.xml'
There was an error finalizing the package.json file. { [Error: Cannot find modul
e 'D:\started\package.json'] code: 'MODULE
_NOT_FOUND' }
 ? Unable to save settings file: Error: ENOENT, no such file or directory 'D:\started\ionic.project'

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd started

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html


 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs


New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
An uncaught exception occured and has been reported to Ionic



Cannot read property 'statusCode' of undefined (CLI v1.5.5)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Windows 7 SP1
Node Version: v0.12.5

**Comment by landed1** [comment]
I am getting this issue as well since updating my node runtime after being advised to do so.
Have tried restarting the mac.
Will try reinstall of ionic and perhaps cordova.
But in the meantime if anyone can help me I would be most glad I am really shooting in the dark now.

**Comment by landed1** [comment]
I think it could in my case be the latest grunt-concurent build - see here https://github.com/diegonetto/generator-ionic/issues/223

This affects us who use yeoman and the generator-ionic scaffolding.

**Comment by sunjoong85** [comment]
It' all about proxy problem. Ionic request.js dose not reference node proxy setting.

**Comment by maowuu** [comment]
Same problem here with "ionic setup sass", restart terminal worked.

**Comment by svimal** [comment]
Please help 

$ ionic start frontEndAwesome sidemenu
=======================================================

New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
An uncaught exception occurred and has been reported to Ionic

Cannot read property 'statusCode' of undefined (CLI v1.6.4)

Your system information:

Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.2 Build version 6C131e

**Comment by sv400** [comment]
Please help 

$ ionic start frontEndAwesome sidemenu
=======================================================

New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
An uncaught exception occurred and has been reported to Ionic

Cannot read property 'statusCode' of undefined (CLI v1.6.4)

Your system information:

Cordova CLI: 5.2.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.2 Build version 6C131e

**Comment by syedrazanaqvi** [comment]
SOLUTION FOR PROBLEM

Please check your environment variables, if C:\Windows\System32; is missing just add it in PATH and Restart cmd....all will work!!!!

**Comment by SamuelMarks** [comment]
@syedrazanaqvi C:\Windows\System32 is in my `PATH`, but I still get this error.

**Comment by abhilash0001** [comment]
Uninstall and installing ionic worked for me! Thanks :)

**Comment by zhangle** [comment]
I getting this same error when running ionic serve.

I solved by killed ionic process.

**Comment by tanya355** [comment]
I am running on OSX El Capitan 10.11.3 and have node LTS version 4.3.1.. after running `npm install -g ionic` i have a console output ending as `> spawn-sync@1.0.15 postinstall /Users/tanya/.npm-packages/lib/node_modules/ionic/node_modules/spawn-sync
> node postinstall

ionic@1.7.14 /Users/tanya/.npm-packages/lib/node_modules/ionic` 
so i assume everything is fine but running cli `ionic` gives me `-bash: ionic: command not found`

**Comment by SamuelMarks** [comment]
@tanya355 That's a different error. Check your `PATH`.

**Comment by mpurham** [comment]
+1 @jamiegood. Thanks!

**Comment by dimuthudrw** [comment]
`npm uninstall -g ionic

npm install -g ionic

ionic start myApp`

This was my saviour

**Comment by abdallahnh** [comment]
@jamiegood 
Thanks. 

npm uninstall -g ionic
npm install -g ionic

worked form me

**Comment by Atta-Ur-Rehman** [comment]
Thanks @jamiegood
 npm uninstall -g ionic
npm install -g ionic 

Its working :+1:
