### ISSUE TITLE
Error adding Crosswalk to existing ionic project

### ISSUE THREAD

**Issue by mhd999** [driftyco/ionic-cli#491]
I followed the article here : http://blog.ionic.io/crosswalk-comes-to-ionic/

and tried both : ionic browser add crosswalk@10.39.235.15 and ionic browser add crosswalk
in both cases i got this error:

An error with adding Crosswalk browser occured Error: There was an error adding
the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:

Error: There was an error adding the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:
    at C:\Users\Vascular\AppData\Roaming\npm\node_modules\ionic\node_modules\ion
ic-app-lib\lib\browser.js:332:11
    at _rejected (C:\Users\Vascular\AppData\Roaming\npm\node_modules\ionic\node_
modules\q\q.js:797:24)
    at C:\Users\Vascular\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q
.js:823:30
    at Promise.when (C:\Users\Vascular\AppData\Roaming\npm\node_modules\ionic\no
de_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\Vascular\AppData\Roaming\npm\no
de_modules\ionic\node_modules\q\q.js:741:41)
    at C:\Users\Vascular\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q
.js:557:44
    at flush (C:\Users\Vascular\AppData\Roaming\npm\node_modules\ionic\node_modu
les\q\q.js:108:17)
    at process._tickCallback (node.js:419:13)

There was an error adding the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:  (CLI v1.5.2)

Here is my system information:
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.2
Ionic App Lib Version: 0.2.0
OS: Windows 7
Node Version: v0.10.33

I don't know if it's because the version of my cordova however i update my cordova to latest version using cordova platform update android since am using ngCordova.

**Comment by jbavari** [comment]
On it now.

**Comment by mhd999** [comment]
Thank you for your fast response it's working now, but according to your commit i had to update my ionic cli just if anyone else run to the same problem with same system information.
