### ISSUE TITLE
ionic upload broke app update on ionic 1.5.4

### ISSUE THREAD

**Issue by rex79** [driftyco/ionic-cli#494]
After upgrade my ionic installation from 1.5.0 to latest 1.5.4 I found out that the auto upload of app with ionic-upload is broken.

My app find the new version, extract it but then after reload the app return ERR_FILE_NOT_FOUND on index.html

After downgrade to 1.5.0 the issue is gone.

**Comment by jbavari** [comment]
@rex79 How do you mean exactly? 

Can you provide more information? What commands were you running? 

Paste contents: `ionic info`

**Comment by rex79** [comment]
I Mean that after a successful upload and extraction of the app it cannot start anymore. 

The error is about a missing index.html file when the app start. I try to reproduce The error and then post a screenshot of it.

**Comment by rex79** [comment]
Here the error with an app uploaded with ionic 1.5.4

![2015-06-18 11 15 37](https://cloud.githubusercontent.com/assets/200989/8228096/73ebe88c-15ac-11e5-9df5-1e1d3aee8b96.jpg)


Here my ionic-info:
-> % ionic info

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0-rc.5
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by Wallacy** [comment]
I'm having the same problem, but go back to version 1.5.0 did not solve.

**Comment by jbavari** [comment]
@rex79 @Wallacy 

We've identified the issue. From issue #445 - we had the module `archiver` bump from `0.5.1` to `0.14.4` which seems to have caused the issue.

We'll be finding a working version and cutting a new CLI release with that working version in the mean time. 

Thank you for the quick feedback.

**Comment by jbavari** [comment]
@rex79 @Wallacy 

Please install the beta version of the CLI and confirm it fixes the issue:

`npm install -g ionic@beta`

**Comment by QimatLuo** [comment]
Failed to find the bower component "ionic-service-deploy".
Are you sure it exists? (CLI v1.6.0-beta.1)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.6.0-beta.1
Ionic App Lib Version: 0.3.1
OS: Distributor ID:     Ubuntu Description:     Ubuntu 15.04 
Node Version: v0.12.2

**Comment by Wallacy** [comment]
In main main app the problem still occurs.
In try using the main template from Quick Start (ionic start myApp io ) and not working too...

**Comment by benjpip** [comment]
I'm having exactly this problem. Everything works fine on iOS, but on Android I'm getting exactly the error in the image rex79 posted above. The application downloads the update successfully, then crashes (I'm assuming due some problem unzipping the file). This is marked as closed, but somehow I'm running into it. Here is my system info after running ionic info:

Cordova CLI: 5.3.3
Ionic Version: 1.1.1
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: 1.8.2 
ios-sim version: 5.0.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68 

Is there some modification I can make to get this working? Any help at all would be greatly appreciated. Thanks.
