### ISSUE TITLE
Getting Invalid upload: unable to read uploaded image

### ISSUE THREAD

**Issue by softBarbarian** [driftyco/ionic-cli#495]
Hello, i am getting following error when i am trying to generate resources:
```
ionic resources
Ionic icon and splash screen resources generator 
 uploading icon.png...
 uploading splash.png...
 ✗ Invalid upload: unable to read uploaded image
 ✓ splash.png (2208x2208) upload complete
```

here are my two files in /resources directory:
![icon](https://cloud.githubusercontent.com/assets/1832398/8213894/69dfae46-14f3-11e5-86ad-691d7b2b6b22.png)

![splash](https://cloud.githubusercontent.com/assets/1832398/8213903/72d85944-14f3-11e5-81ef-6dd9783ae6f5.png)

**Comment by softBarbarian** [comment]
here is my info
```
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.8
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.4
Ionic App Lib Version: 0.2.1
ios-deploy version: 1.6.2 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.2 Build version 6D2105 
```

**Comment by softBarbarian** [comment]
Recreated images and everything worked

**Comment by mjunaidsalaat** [comment]
@softBarbarian  Recreation didn't worked for me, However after exporting the images with interlacing turned off fixed it and Ionic accepted the file.

**Comment by fxbayuanggara** [comment]
change your png to default ionic icon and splash png, if it works, try to change your photo resolution and format exactly as png, not jpeg that saved as png.
