### ISSUE TITLE
Community contribution to Ionic ions?

### ISSUE THREAD

**Issue by arvindr21** [driftyco/ionic-cli#498]
Hello,

Is there a way that the community can contribute by adding more ions (_Apart from PR to the CLI_)? If not would you consider accepting ions as bower packages with `"ionic-ion"` as one of the keywords (along with `"ionic-ion-addon"`, `"ionic-ion-component"` or `"ionic-ion-ux"`)?.

Thanks.

**Comment by jbavari** [comment]
Let me ask the team and i'll get back with you an answer.

**Comment by jbavari** [comment]
@arvindr21 I've been told this will be available with the [Ionic Marketplace](http://market.ionic.io/)
