### ISSUE TITLE
Cannot Add/Remove CrossWalk Ionic CLI 1.5.5

### ISSUE THREAD

**Issue by cahara** [driftyco/ionic-cli#501]
I'm having issues when trying to add or remove crosswalk. It was working fine this morning but now nothing's working. I've tried adding Crosswalk on existing projects and new projects without success. This appears to be shared with the issue at https://github.com/driftyco/ionic-cli/issues/500

I'm using ionic CLI version 1.5.5 and getting:

Adding crosswalk browser
You are running Cordova CLI 4.3.0 - installing Cordova Android and Crosswalk manually

Downloaded cordova-crosswalk-engine

Downloaded Cordova Android for Crosswalk

Copying over Crosswalk Webview (arm) to the Crosswalk Engine

Finished copying Crosswalk Webview (arm) to the Crosswalk Engine

Copying over Crosswalk Webview (x86) to the Crosswalk Engine

Finished copying Crosswalk Webview (x86) to the Crosswalk Engine

Downloaded Crosswalk webviews

Removed old Cordova Android platform
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.hndld.hndld648394
        Name: HNDLD
        Activity: MainActivity
        Android target: android-21
Copying template files...
Android project created with cordova-android@4.0.0-dev
add to body class: platform-android
4.0.0-dev
 ?
An error with adding Crosswalk browser occured Error: There was an error adding
the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:

Error: There was an error adding the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:
    at C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\browser.js:332:11
    at _rejected (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:797:24)
    at C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:
823:30
    at Promise.when (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:741:41)
    at C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\node_modules\
q\q.js:108:17)
    at process._tickCallback (node.js:419:13)

There was an error adding the Cordova Android library
There was an error adding the platform:TypeError: Invalid Version:  (CLI v1.5.5)

Your system information:

Cordova CLI: 4.3.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Windows 7 SP1
Node Version: v0.10.33

**Comment by cahara** [comment]
This issue may be linked to https://github.com/driftyco/ionic-cli/issues/493. However my version of the Cordova CLI is 4.3.0.

I've tried the following with no luck:
-Downgrading ionic to 1.5.4, and 1.5.3
-Running "cordova platform update android" to update the Cordova CLI
-Adding and removing the android platform from the project

**Comment by cahara** [comment]
A work around is to downgrade the Ionic CLI to 1.5.0 with "npm uninstall ionic -g" and then "npm install ionic@1.5.0 -g"

https://github.com/driftyco/ionic-cli/issues/497

**Comment by yanzhihong23** [comment]
1.5.0 has the same issue.

**Comment by cahara** [comment]
I've seen some people having to downgrade to Ionic CLI v1.4.8 or lower to get Crosswalk working.

**Comment by jbavari** [comment]
I'll dig into this later this week.

**Comment by jgw96** [comment]
Hello all! Are you still having this issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by bansalsonam22** [comment]
when i run ionic serve

TypeError: Invalid Version: Not installed
    at new SemVer (/usr/local/lib/node_modules/ionic/node_modules/semver/semver.js:295:11)
    at Range.test (/usr/local/lib/node_modules/ionic/node_modules/semver/semver.js:1049:15)
    at Function.satisfies (/usr/local/lib/node_modules/ionic/node_modules/semver/semver.js:1098:16)
    at Object.checkRuntime (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/info.js:295:32)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:54:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Invalid Version: Not installed (CLI v1.6.4)

Your system information:

Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.12.0
Xcode version: Xcode 7.2 Build version 7C68
