### ISSUE TITLE
ionic upload fail - no specific error message

### ISSUE THREAD

**Issue by arnav28** [driftyco/ionic-cli#502]
ionic upload command is failing without any specific error message. I have tried this on my existing project as well as with new/blank project!! 

Forum link:  http://forum.ionicframework.com/t/ionic-upload-error-with-no-specific-error-message/26609/9

------------------------------------------------
Uploading app....

Upload Failed: (CLI v1.5.5)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.10
Gulp local:  
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.10.34
Xcode version: Xcode 6.3.2 Build version 6D2105 

------------------------------------------------

**Comment by oprog** [comment]
Same here, just created a new project and tried to upload it.
No error details, any log to look into?

That's what I get:
>Upload Failed: (CLI v1.5.5)

>Your system information:

>Cordova CLI: 5.1.1
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Mavericks
Node Version: v0.10.34
Xcode version: Xcode 6.2 Build version 6C131e

**Comment by hughred22** [comment]
Same here. Tried brand new project as well as previous successfully uploaded project, both fail with no specific error message: 

Uploading app....

Upload Failed: (CLI v1.5.5)

Your system information:

Cordova CLI: 5.0.0
Gulp version: CLI version 3.8.11
Gulp local:
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.10.34
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by ericb** [comment]
This looks to be resolved now. Are any of you facing the issue still?

**Comment by patrickmcd** [comment]
No dice for me. I was getting a CERT_UNTRUSTED error about a month ago, and reported here:
https://github.com/driftyco/ionic-cli/issues/381#issuecomment-106648497

Like before, my app shows up in the Ionic View App, but the size says NAN UNDEFINED, and attempting to view the app shows a connection error.

I've tried uploading both the app I've been developing as well as creating a new project from scratch. And I've tried both ways from the Quick Start; starting from Step 1 and the Step 0 version by creating an app in the dashboard first.

My info from the CLI:

Upload Failed: (CLI v1.5.5)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.34
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by ericb** [comment]
@patrickmcd What happens if you try an older ionic cli version such as `npm install -g ionic@1.5.0`

**Comment by patrickmcd** [comment]
Looks like the same result.

Upload Failed: (CLI v1.5.0)

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.0
Ionic App Lib Version: 0.1.0
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.34
Xcode version: Xcode 6.3.2 Build version 6D2105

**Comment by arnav28** [comment]
Same result. Tried with both older and latest cli versions.

Upload Failed: (CLI v1.5.0)

Your system information:

**Comment by arnav28** [comment]
it looks like..we all were using node v 0.10.34
But after updating the node to v 0.12.5 
the problem was solved!!! Try updating ur node version

**Comment by patrickmcd** [comment]
Yep, updating to v0.12.5 worked for me. Thanks @arnav28

**Comment by oprog** [comment]
Updating to 0.12.5 worked here too. Thanks @arnav28 !

**Comment by jbavari** [comment]
In addition to this - the next version of the CLI will include a message to users with a warning (and suggestion) to update their node version.

Thank you all for your help.

**Comment by jbavari** [comment]
Again, thanks to all for reporting.

Added [an update warning](https://github.com/driftyco/ionic-cli/commit/4e521ab06a2e5c844248af73090a02a2da279cf0) for node to help others avoid this error.

**Comment by jbavari** [comment]
Fixed in 1.6.0.

**Comment by DraguiN8** [comment]
It happened to me while using cli 1.6.1
Any suggestion why?

**Comment by sjaanus** [comment]
Error logging in: Error: certificate not trusted (CLI v1.6.4)

**Comment by Istanbouly** [comment]
I guess I knew the solution for me this error happened when I delete the app from my ionic view App 
so when if you delete an app and try to re-upload it probably you are going to face the same error since you are trying to upload your app to non existing app id anymore here is the steps that I walk through to solve the problem 

1- login to your account at https://apps.ionic.io
2- click create new app name it what ever doesn't matter 
3- once the new app is created copy its ID 
4-go back to the app you want to upload 
5- replace your app ID with the add you just copied you have to replace twice in these files
**io-config.json
**ionic.config.json 
6- save changes and re-upload again good luck 

Notice that the new app that you created should be created in the same account that the previous app where registered to :)
