### ISSUE TITLE
Crosswalk shared mode

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic-cli#503]
Do You plan to support crosswalk shared mode? https://crosswalk-project.org/blog/crosswalk-shared-mode.html

**Comment by baleboy** [comment]
aside from Ionic's plans, note that shared mode is not yet supported in the Crosswalk webview plugin, used by Ionic and Cordova. We are working on it.

**Comment by piernik** [comment]
Oh... ok - keep up great work!

**Comment by baleboy** [comment]
Shared mode for webview plugin is now supported in Crosswalk 14 and later

**Comment by pewh** [comment]
It's good news. But I've googling and still no news about that. Can you share us where you get the link? :)

**Comment by baleboy** [comment]
Sorry, it looks like I jumped the gun. We still need to release a new version of the webview plugin before this is usable.
