### ISSUE TITLE
Ionic Upload changes remote script url

### ISSUE THREAD

**Issue by AdamCaviness** [driftyco/ionic-cli#504]
Ionic Upload mutates a remote script url by suffixing it with an equals sign.

    <script src="http://jsconsole.com/remote.js?FAE031CD-74A0-46D3-AE36-757BAB262BEA"></script>

Is mutated to:

    <script src="http://jsconsole.com/remote.js?FAE031CD-74A0-46D3-AE36-757BAB262BEA="></script>

I am using [remotejs.com][1] for Ionic View so I need the remote script (dev only).  It's annoying because I have to change it back each time in order for my next upload not to send the wrong script path.  I presume this is because of how the paths are changed temporarily during Upload and then reverted.  This is easy to reproduce on a clean tab templated app from the machines I attempted it on.  Thanks for the wonderful work you've done, it is very impressive.

  [1]: http://jsconsole.com/remote-debugging.html

**Comment by jbavari** [comment]
We'll look into it. Thanks for reporting.

**Comment by jbavari** [comment]
@AdamCaviness I've got a fix for this in place here: https://github.com/driftyco/ionic-app-lib/commit/a3cbc85bcbb16fe596d689936e8b0bb225cc61fd

**Comment by AdamCaviness** [comment]
@jbavari Thanks for addressing this.

**Comment by jbavari** [comment]
Fixed in 1.6.0.
