### ISSUE TITLE
crosswalk version

### ISSUE THREAD

**Issue by piernik** [driftyco/ionic-cli#508]
On https://crosswalk-project.org/documentation/downloads.html I see that 14 is in beta with version `14.43.343.7`.
You have still canary `14.42.*` version. Can You keep it updated?

**Comment by jbavari** [comment]
Correct. Previously, I've been updating that list manually. 

What would be optimal is to scan the downloads page and provide those as available versions. I'll get to that when I have time.

**Comment by baleboy** [comment]
You could also use the "latest" link in the stable channel:

https://download.01.org/crosswalk/releases/crosswalk/android/stable/latest/

**Comment by eliashdezr** [comment]
Are we able to use the ones that are not listed in `ionic browser list`? For example, we can use the `v17.45.424.0` in the canary  channel.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
