### ISSUE TITLE
Creating a new empty directory kills Ionic CLI livereload

### ISSUE THREAD

**Issue by budda** [driftyco/ionic-cli#510]
If i had the Ionic CLI providing livereload for the browser (serve) or iOS simulator and then create a new empty directory under www/ it will cause the CLI tool to explode:

```
File changed: www/js/untitled folder/
An uncaught exception occured and has been reported to Ionic



watch ENOENT (CLI v1.5.5)

Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.26
Xcode version: Xcode 6.3.2 Build version 6D2105
```

**Comment by jbavari** [comment]
I couldn't get it reproduce.

What am I doing differently?

Here's my steps: 
<img width="470" alt="screen shot 2015-07-04 at 11 43 05 am" src="https://cloud.githubusercontent.com/assets/1414692/8508892/e8a34f84-2241-11e5-96d0-23cfb4eaa2c1.png">

**Comment by budda** [comment]
Just tried again, same process killed the Ionic CLI - this time i did it whilst using the Android emulator in --livereload mode.

```
HTML changed: www/index.html

r
Loading: /?restart=740908
ionic $ File changed: www/untitled folder/
An uncaught exception occured and has been reported to Ionic



watch ENOENT (CLI v1.5.5)

Your system information:

Cordova CLI: 5.0.0
Ionic Version: 1.0.0
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.26
Xcode version: Xcode 6.4 Build version 6E35b
```

However what might help recreate this is that i was creating the new directory via my IDE. And the way it works is to create a new directory always called 'untitled folder' and then quickly rename that after i've entered my desired name and hit return.

So maybe the CLI has identified the 'File changed: www/js/untitled folder/' event and prepares to scan inside but then finds the folder has gone due to it being renamed?

**Comment by HassanCehef** [comment]
When I checkout a branch on git (say, from featureXXX to master), the CLI seems to crash if too many files have been moved/created/deleted between the two commits.

` 22 files changed, 81 insertions(+), 75 deletions(-)`

My ionic version is out of date, so is my Ubuntu. I'll be able to update both of them this week-end, I'll try again next week.

```
An uncaught exception occured and has been reported to Ionic



watch ENOENT (CLI v1.5.5)

Your system information:

Cordova CLI: 5.1.1
Ionic Version: 1.0.1
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Distributor ID:	Ubuntu Description:	Ubuntu 13.10 
Node Version: v0.10.15

------------------------------------
Ionic CLI is out of date:
 * Locally installed version: 1.5.5
 * Latest version: 1.6.1
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update
------------------------------------
```

**Comment by vamsivarikuti** [comment]
Can anyone help me about this issue?

    ionic emulate ios -l -c -s --target="iPad-2"
    Setup Live Reload
    Running live reload server: http://192.168.234.183:35729
    Watching : [ 'www/**/*', '!www/lib/**/*' ]
    Running dev server: http://192.168.234.183:8100
    Ionic server commands, enter:
      restart or r to restart the client app from the root
      goto or g and a url to have the app navigate to the given url
      consolelogs or c to enable/disable console log output
      serverlogs or s to enable/disable server log output
      quit or q to shutdown the server and exit
    
    ionic $ Running command: /Users/vvarikuti/Desktop/mocc-ui/hooks/before_emulate/010_grunt_build.js /Users/vvarikuti/Desktop/mocc-ui
    HTML changed: www/404.html
    File changed: www/favicon.ico
    HTML changed: www/index.html
    HTML changed: www/login.html
    File changed: www/robots.txt
    File changed: www/images/22.5da80b67.jpg
    File changed: www/images/23.2a72f72a.jpg
    File changed: www/images/alllon.00599e98.jpg
    File changed: www/images/christy.2b1d9bdc.jpg
    File changed: www/images/christyon.7879f46b.jpg
    File changed: www/images/dollar-slice.66fbc5e1.png
    File changed: www/images/downarrow.d271be98.png
    File changed: www/images/janelle.2a72f72a.jpg
    File changed: www/images/janellon.a9a8fac6.jpg
    File changed: www/images/person-black.dcea474f.png
    File changed: www/images/person-slice.442a32e2.png
    File changed: www/images/person.1388384b.png
    File changed: www/images/peter.5da80b67.jpg
    File changed: www/images/peteron.44937c8e.jpg
    File changed: www/images/yeoman.8cb970fb.png
    An uncaught exception occurred and has been reported to Ionic
    
    
    
    watch ENOENT (CLI v1.6.5)
    
    Your system information:
    
    Cordova CLI: 5.2.0
    Ionic CLI Version: 1.6.5
    Ionic App Lib Version: 0.3.9
    ios-deploy version: Not installed
    ios-sim version: 5.0.1
    OS: Mac OS X Mavericks
    Node Version: v0.12.7
    Xcode version: Xcode 6.2 Build version 6C131e

**Comment by cfjedimaster** [comment]
Just a +1 that I'm seeing this too. Hit me a bunch of times today while I was moving some files around while testing.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
