### ISSUE TITLE
Ionic Deploy Crashing the App (1.6.0)

### ISSUE THREAD

**Issue by Wallacy** [driftyco/ionic-cli#513]
Steps to reproduce:

ionic start myApp io
cd myApp/
ionic platform add android
ionic run android

**/// Run Ok Now...

ionic plugin add https://github.com/driftyco/ionic-plugins-deploy
ionic add ionic-service-deploy
ionic run android

**/// Crash after few seconds...

//** 

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.0
Ionic App Lib Version: 0.3.2
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.4 Build version 6E35b 

**/

**Comment by jbavari** [comment]
I wasn't able to reproduce with those steps.

Did it fail before it ran on the device? 

Or it failed once the simulator began running?

**Comment by Wallacy** [comment]
Im Deploy on Android tablet (4.4.2). No Simulator.

**Comment by jbavari** [comment]
It looks like you missed a few steps in the set up. Specifically, `ionic-service-core`.

Did you follow the [set up guide](http://docs.ionic.io/v1.0/docs/deploy-from-scratch) entirely?

**Comment by Wallacy** [comment]
Yes....

Just as a note, I already have another application that worked very well with the ionic deploy in version 1.5.0, but the version 1.5.5 was the problem with the upload, and now in version 1.6.0 it just hangs.

The example above works very well with the CLI 1.5.0.

The " io " template used has already all code setups made, imports, data provider, etc...

**Comment by Wallacy** [comment]
Using old versions of the cli still crash.... 

So i look from my deploy folder and select a old apk with works fine in the past and... crash...

Then i comment this line:

$ionicDeploy.watch().then(function() {}, function() {},
function(hasUpdate) {
  // Handle response
});

And works fine.... So the problem is not the CLI, but something on the server side.

Using  alert(JSON.stringify($ionicDeploy));

{"channel_tag":"production"}

With of course is newer.... Wish my app and the io template does not now.

I will dig a little bit more.

**Comment by Wallacy** [comment]
Just to know: Using new version of the components solve the problem for me:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.1
Ionic App Lib Version: 0.3.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.12.6
Xcode version: Xcode 6.4 Build version 6E35b
