### ISSUE TITLE
gulpStartupTasks async to ionic initialization

### ISSUE THREAD

**Issue by jayrmotta** [driftyco/ionic-cli#519]
ionic-cli version: 1.6.1
gulp version: 3.9.0
node version: 0.12.4
npm version: 2.10.1

I have this ionic.project file:

```javascript
{
  "name": "foobar",
  "app_id": "com.foo.bar",
  "gulpStartupTasks": [
    "styles",
    "source",
    "watch"
  ],
  "watchPatterns": [
    "www/**/*",
    "!www/lib/**/*"
  ],
  "sourceModules": {
    "ionic": "git://github.com/driftyco/ionic.git",
    "ng-cordova": "git://github.com/driftyco/ng-cordova.git"
  }
}
```

But I've detected that the gulpStartupTasks are being executed asynchronously with the Ionic initialization, so when Ionic tries to find the www folder and don't find it (because my startup tasks haven't run yet) it fails and kill the process

if I create an empty www folder to trick Ionic it works but opens a browser with an error saying that the index.html haven't been found

However, some seconds after that I see the startup tasks being executed in my shell

And if I refresh the page it works

How can I make these startup tasks run before ionic tries to find the www folder?

**Comment by leonardobazico** [comment]
+1

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
