### ISSUE TITLE
Crosswalk - XWalkCordovaCookieManager - error: cannot find symbol import org.xwalk.core.internal.XWalkCookieManager

### ISSUE THREAD

**Issue by thim81** [driftyco/ionic-cli#521]
Hi,

We were using Ionic and Crosswalk and for some reason we now always get this error.
While nothing has changed with regards to Crosswalk, but suddenly we get complaints about a missing 
import org.xwalk.core.internal.XWalkCookieManager.

## Error output
```
/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:22: error: cannot find symbol
import org.xwalk.core.internal.XWalkCookieManager;
                              ^
  symbol:   class XWalkCookieManager
  location: package org.xwalk.core.internal
/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:26: error: cannot find symbol
    protected XWalkCookieManager cookieManager = null;
              ^
  symbol:   class XWalkCookieManager
  location: class XWalkCordovaCookieManager
/platforms/android/src/org/crosswalk/engine/XWalkCordovaCookieManager.java:29: error: cannot find symbol
        cookieManager = new XWalkCookieManager();
                            ^
  symbol:   class XWalkCookieManager
  location: class XWalkCordovaCookieManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJava'.
> Compilation failed; see the compiler error output for details.
```

## Stack used:
- Cordova CLI: 5.0.0
- Ionic Version: 1.0.1
- Ionic CLI Version: 1.6.1
- Ionic App Lib Version: 0.3.3
- Crosswalk "version": "14.42.334.0"

**Comment by thim81** [comment]
We got great assistance and input from @honry from Crosswalk.

In our config.xml, we had the following: 

```
<preference name="xwalkVersion" value="14+"/>
```

Honry's input: 
> I guess you are trying the latest webview plugin, this is caused by recently commit crosswalk-project/cordova-plugin-crosswalk-webview#34, and relative fix has been ported to Crosswalk 13 and Crosswalk 14 branch.
you can refer to the issue https://crosswalk-project.org/jira/browse/XWALK-4568, and you can wait for new beta version or trying the latest canary version.

We applied the fix like you referenced: crosswalk-project/cordova-plugin-crosswalk-webview#34 which solved the issue immediately.

**Comment by Elijax** [comment]
+1
