### ISSUE TITLE
Wrong script in package.json when you add new platforms

### ISSUE THREAD

**Issue by fairsayan** [driftyco/ionic-cli#524]
I have ionic 1.6.1 and I have these plugins in package.json:
"cordovaPlugins": [
    "cordova-plugin-whitelist@1.0.0",
    "com.ionic.keyboard",
    {
      "locator": "https://github.com/phonegap-build/PushPlugin.git",
      "id": "com.phonegap.plugins.PushPlugin"
    },
    "cordova-plugin-console",
    "nl.x-services.plugins.toast"
  ], "cordovaPlatforms": []

now if I run in sequence:
ionic platform add ios
ionic platform add android
ionic platform add browser

here my new package.json:
  "cordovaPlugins": [
    "cordova-plugin-whitelist@1.0.0",
    "com.ionic.keyboard",
    {
      "locator": "https://github.com/phonegap-build/PushPlugin.git",
      "id": "com.phonegap.plugins.PushPlugin"
    },
    "cordova-plugin-console",
    "nl.x-services.plugins.toast"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "android",
      "locator": "browser"
    }
  ]

that is wrong. So that we I download a cleaned copy from my repo and I run "ionic state restore"
I have a mess.

Here the code working for me:
"cordovaPlugins": [
    "cordova-plugin-whitelist@1.0.0",
    "com.ionic.keyboard",
    {
      "locator": "https://github.com/phonegap-build/PushPlugin.git",
      "id": "com.phonegap.plugins.PushPlugin"
    },
    "cordova-plugin-console",
    "nl.x-services.plugins.toast"
  ], "cordovaPlatforms": []

now if I run in sequence:
ionic platform add ios
ionic platform add android
ionic platform add browser

here my new package.json:
  "cordovaPlugins": [
    "cordova-plugin-whitelist@1.0.0",
    "com.ionic.keyboard",
    {
      "locator": "https://github.com/phonegap-build/PushPlugin.git",
      "id": "com.phonegap.plugins.PushPlugin"
    },
    "cordova-plugin-console",
    "nl.x-services.plugins.toast"
  ],
  "cordovaPlatforms": [
    "ios", "android", "browser"  ]

**Comment by adamdbradley** [comment]
Greetings @fairsayan!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
