### ISSUE TITLE
CLI doesn't install github template to the correct location in the project

### ISSUE THREAD

**Issue by aaronksaunders** [driftyco/ionic-cli#525]
when I am trying to use another repo as the starter template, the `www` directory is installed in the wrong place

```
IMac27Quad-9:ionic-projects aaronksaunders$ ionic start parseTemplateApp https://github.com/aaronksaunders/Ionic-CameraTest6Plus
Creating Ionic app in folder /Users/aaronksaunders/WebstormProjects/ionic-projects/parseTemplateApp based on https://github.com/aaronksaunders/Ionic-CameraTest6Plus project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/aaronksaunders/Ionic-CameraTest6Plus/archive/master.zip
[=============================]  100%  0.0s
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project
Adding in iOS application by default
iOS project created with cordova-ios@3.8.0
add to body class: platform-ios
3.8.0
3.8.0
3.8.0
3.8.0
3.8.0
all done with platform add stuffs
```
this is my project after the install, notice the nested `www` directories. it appears the default `www` directory is not being overwritten

![screenshot 2015-07-12 22 40 30](https://cloud.githubusercontent.com/assets/524953/8641670/15729884-28e7-11e5-99ad-b4d1a7a7eb6b.png)

**Comment by mhartington** [comment]
Took a look at the repo you were using, seems to be off a bit.

https://github.com/driftyco/ionic-starter-tabs

A starter template should just contain the contents of the www directory, not a whole project root.

**Comment by aaronksaunders** [comment]
@mhartington i was looking at the ionic-app-base template for guidance, thx
