### ISSUE TITLE
Support downloading any zip file for a project starter template

### ISSUE THREAD

**Issue by aaronksaunders** [driftyco/ionic-cli#526]
currently the template option looks for a codePen project, a named starter template provided in the JSON file or a master.zip file from a specified github project.

I am putting together a series of templates for training materials and that includes the github project for the work, BUT I also would like the student to user the templates to start there own projects.

if I used the current CLI start command and point it at a repo, it assumes that I am looking for this url

`https://github.com/aaronksaunders/parse-starter-ionic/archive/master.zip`

it appears the code takes the repo and looks for the `master.zip`  file,  I want the code to look for a specific zip file include with the project.

For an example, look at my starter project here - [`https://github.com/aaronksaunders/parse-starter-ionic`](https://github.com/aaronksaunders/parse-starter-ionic)

I want to be able to use this command

`ionic start newTemplateApp -t https://github.com/aaronksaunders/parse-starter-ionic/app-template.zip`

**Comment by aaronksaunders** [comment]
thanks in advance for your assistance @jbavari

**Comment by jbavari** [comment]
Ah, I understand now.

A quick explanation as to why `archive/master.zip` is used: the url `https://github.com/aaronksaunders/parse-starter-ionic/archive/master.zip` is a github API url to zip up the repository at the `master` commit for download.

It is not specifying a zip file in the repository, per se.

Is `app-template.zip` just the repository zipped up? If yes, you can remove that file and place the entire contents of `www` at the base of the repo.

For example, I did that [here](https://github.com/jbavari/parse-starter-ionic): `ionic start ParseTemplate https://github.com/jbavari/parse-starter-ionic`.

A great example of how starter projects are seen in [this repo](https://github.com/driftyco/ionic-starter-salesforce).

This ionic-starter-salesforce repo is the `www` folder in an ionic app, so to speak.

HOWEVER, that being said, having the CLI download a zip from a specific URL wouldn't be a bad feature.

I'd suggest looking here in the [`ionic-app-lib`](https://github.com/driftyco/ionic-app-lib/blob/master/lib/start.js#L66) to see where it grabs the template, and uses that url to download and extract.

I'd suggest adding an option, `-z`, to avoid having to parse out the URL from current `-t` option.

Something like what you had: `ionic start newTemplateApp -z https://github.com/aaronksaunders/parse-starter-ionic/app-template.zip`

**Comment by aaronksaunders** [comment]
thanks, I understood what was going on... and the structure of the folder, it just seems like extra work to have one repo for the template and one repo for the actual project that supports the template; that is my motivation for creating and additional option for using templates getting started with building your apps.

I will poke around and see if I can pull this off, thanks again... you guys are doing great work!

**Comment by jbavari** [comment]
In that case, yep, I'd advise adding a new option to specify a zip URL with a `-z` option to keep things backward compatible for other users.

A little help to point you in the right direction with how to modify, back at [ionic-app-lib](https://github.com/driftyco/ionic-app-lib/blob/master/lib/start.js#L66):

```
return Start.fetchWrapper(options)
.then(function(data){
   if (options.downloadZipUrl) {
    return Start.fetchZip(options);
   }
   return Start.fetchSeed(options);
})
//.. snip ..
var fetchZip = function(options) {
   return utils.fetchArchive(options.targetPath, options.downloadZipUrl)
   .then(function() {
    //do whatever you need
   });
};

```

**Comment by aaronksaunders** [comment]
thanks... will give it a go after-hours tonight!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
