### ISSUE TITLE
bug: updating to ionic 1.01 and cli 1.6.1 breaks ionic serve

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#529]
_From @alexweber on July 19, 2015 14:50_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>All of a sudden `ionic serve` stopped working and serves up a blank page.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4108_

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
