### ISSUE TITLE
bug: ionic cli add does not find bower packages

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#530]
_From @gpolyn on July 19, 2015 13:42_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>Components that a 'bower search' can find sometimes result in the following error message after executing 'ionic add'

Failed to find the bower component [...]
Are you sure it exists? (CLI v1.6.1)</span>

<span is-issue-template></span>

Try, for example, well-known and useful packages angularfire and firebase: they appear in bower searches, but result in the error above.

_Copied from original issue: driftyco/ionic#4107_

**Comment by mhartington** [comment]
This is odd, since `ionic add` is just an alias for `bower install --save-dev`

https://github.com/driftyco/ionic-cli/blob/master/lib/ionic/add.js#L16

Could you paste the out put from `ionic info` @gpolyn

**Comment by zackhall** [comment]
Hi Mike, 

I am also seeing this trying to run 'ionic add angularfire' 

Here's my output of 'ionic info': 
Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.1.0
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.7.0 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.4
Xcode version: Xcode 6.4 Build version 6E35b

**Comment by zackhall** [comment]
Weirdly enough, 'bower install --save-dev angularfire' did work without hitch.

**Comment by mhartington** [comment]
Hmm, just gave `ionic add angularfire` a try and it worked fine.
Please update your ionic cli to the latest and try again.

```
Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.40
Xcode version: Xcode 6.4 Build version 6E35b

```

**Comment by vibhoo** [comment]
ionic platform add android 
worked for me instead of 
```node```
ionic add platform android

**Comment by Diliz** [comment]
Actually this is occuring when bower is not installed on your computer, ionic don't say it if it's the case

So, you can do:

npm install -g bower
ionic add angularfire

Think it should work now :)

**Comment by jthoms1** [comment]
Looks liked the latest beta release of the CLI handles this scenario. Closing this issue.
![screen shot 2016-04-21 at 9 23 54 am](https://cloud.githubusercontent.com/assets/1425431/14712484/eca75642-07a2-11e6-8774-6fbef3c4f9e0.png)

**Comment by Forge0100** [comment]
Simple use the command `ionic start myapp [template]`
