### ISSUE TITLE
Error: "It is recommended that the compiler be upgraded."

### ISSUE THREAD

**Issue by kaumac** [driftyco/ionic-cli#532]
I'm getting a lot of errors when building for android, all of them say:
"It is recommended that the compiler be upgraded."

I have no idea the cause of this so I'll describe what I have:
Fully updated node.js and npm modules (Ionic-cli, Cordova, Node and NPM)
New Ionic project (just started it, no plugins, only Ionic Services and Crosswalk)

Running "ionic build android --release"

Heres a screenshot:

<img width="1920" alt="captura de tela 2015-07-21 as 16 00 10" src="https://cloud.githubusercontent.com/assets/1170740/8809994/50f3f3f8-2fc2-11e5-8429-e668b1a0023f.png">

**Comment by kaumac** [comment]
I forgot to mention, the build is successful even after the erros.

**Comment by qutek** [comment]
any news about this?
i was experienced with this too

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
