### ISSUE TITLE
lldb is left hanging when running to an ios device

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#539]
When I do ionic run ios --device, I can't use "q" to quit lldb like I can with the cordova cli. While I think that should work, at minimum ctrl-c should kill lldb. It is not currently.

**Comment by jbavari** [comment]
We'll look into it. Thanks for reporting.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
