### ISSUE TITLE
Bad ion-Nav-view screen distribution after recent update

### ISSUE THREAD

**Issue by DaniloCouto** [driftyco/ionic-cli#542]
After the recent update my ion-nav-view have some top distance in every platform.

![ionic](https://cloud.githubusercontent.com/assets/12234405/8958490/767394d4-35db-11e5-90af-7711e429ccf6.png)

Any workaround?

**Comment by jbavari** [comment]
Which recent update? Did you update your ionic-cli?

Or did you update the ionic framework files (javascript, css, etc)?

**Comment by DaniloCouto** [comment]
I have Update my Ionic-CLI... and suddenly this happens...
However, it is easy to fix, just add a Style on ion-nav-view with top: 0.
Thanks for the attention @jbavari

**Comment by jbavari** [comment]
Glad to help out. Closing if you're good.
