### ISSUE TITLE
Command failed with exit code 1 while adding iOS platform after recent update

### ISSUE THREAD

**Issue by DaniloCouto** [driftyco/ionic-cli#543]
Simple as that:

> ionic platform add ios

Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\Tecnico\AppData\Roaming\npm\node_modules\
cordova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by jbavari** [comment]
Please type in `ionic info` and paste that information here.

You might also try `cordova platform add ios`. It seems that the cordova-cli is having an issue (\npm\node_modules\
cordova\node_modules\cordova-lib\src\cordova\superspawn.js).

**Comment by DaniloCouto** [comment]
>cordova platform add ios 

Well , it works..
And sorry about this simple issue, I'll try harder next time. (x

And if you want to go depply at this issue...

>Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.0.1
Ionic CLI Version: 1.6.3
Ionic App Lib Version: 0.3.7
OS: Windows 7 SP1
Node Version: v0.12.4

**Comment by adamdbradley** [comment]
Greetings @DaniloCouto!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by avnnet** [comment]
Just Installed PhoneGap on mac and y try to create HelloWorld Project and ...

Command failed with exit code 1

( time wasting ... )

**Comment by santanubankura** [comment]
gulp --cordova "build ios" return error

fatal error: 'Cordova/CDVViewController.h' file not found
#import <Cordova/CDVViewController.h>

** BUILD FAILED **
The following build commands failed:
CompileC /var/root/Library/Developer/Xcode/DerivedData/ADDA_Pay-cxngvlinjhvyssfhdmqvhttlrmza/Build/Intermediates.noindex/ADDA\ Pay.build/Debug-iphonesimulator/ADDA\ Pay.build/Objects-normal/x86_64/AppDelegate.o ADDA\ Pay/Classes/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/MobileApp/albatross-adda-pay/platforms/ios/cordova/build-debug.xcconfig,-workspace,ADDA Pay.xcworkspace,-scheme,ADDA Pay,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/MobileApp/albatross-adda-pay/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/MobileApp/albatross-adda-pay/platforms/ios/build/sharedpch
[16:04:37] 'cordova-with-build' errored after 7.91 s
[16:04:37] Error in plugin 'gulp-shell'

Any one please help ME
