### ISSUE TITLE
Extra 'uses-sdk' in Android Manifest

### ISSUE THREAD

**Issue by jfkoch** [driftyco/ionic-cli#549]
I am getting this extra uses sdk in my android manifest whenever I add the android platform

< uses-sdk android:minSdkVersion="16" android:targetSdkVersion="17"/>

This is in addition to the correct uses sdk of 

< uses-sdk android:minSdkVersion="10" android:targetSdkVersion="22"/>

Of course this causes the linter to throw a fatal error when building a release. I've tried to manually remove it from the manifest but it gets added back in when the project is rebuilt.

**Comment by mattalco** [comment]
I am also having a problem here starting today. I am getting a second uses-sdk line for version 19 of android. Any ideas what this could be?

<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="22" /> //I specify this in ionic config.xml
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="19" /> // this shows up magically

**Comment by jfkoch** [comment]
It appears one of my plugin was triggering this and I saw it ended up getting added to android.json under plugins. I deleted <uses-sdk android:minSdkVersion=\"16\" android:targetSdkVersion=\"17\" /> from android.json and then from androidmanifest.xml and when I built again it didn't get added anymore. Hope this helps!
