### ISSUE TITLE
Issue with Ionic project from Github

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#550]
Please note that I am not sure ionic-cli is the best place for this. Also, this may not be a bug at all. I ran into it and figured I'd log it to see what others think.

So - I checked in an Ionic project into Github today (https://github.com/cfjedimaster/IonicBluemixDemo), and as a test, I cloned the repo elsewhere and tried to work with the mobile folder as an Ionic project. It does not have a platforms folder so I tried to add ios, but when I did, it told me that the project already had ios as a platform.

And here is the crazy part. I can somehow run it on iOS - but when I do, it uses some other project (it looks like the default template.) It isn't using the code from my actual repo. 

What I'm seeing here is that based on the default .gitignore values, if you check a project into GitHub and then check it out later, you have something that doesn't seem to be a proper Ionic/Cordova project. 

Since the Ionic CLI doesn't let you use the source of a folder (afaik) for a project, I'd have to make a new Ionic project than copy the www folder over. That isn't a big deal, but it feels like something is off here.

So I guess the summary is - how would you recommend someone submit to Github a project and then reuse it again in a new project? Right now the process seems like it is a bit clunky, and it could be better.

For now, I'm going to update my Git repo to include *nothing* but the www assets. (Maybe - still thinking about it.)

**Comment by cfjedimaster** [comment]
As an FYI, speaking to @mhartington on Slack, I realize I'm wrong about how to source a new Ionic project. But that doesn't speak to the issue as a whole of course.

**Comment by cfjedimaster** [comment]
I spoke with @mhartington on Slack more and we observed something odd. When he got the repo and did "ionic platform add ios" it worked perfectly, adding a new platforms and plugins folder. That definitely did not work for me. We're keeping this open to see if others can reproduce it.

**Comment by mhartington** [comment]
I wasn't able to recreate this, but @cfjedimaster and I have the same environment but got different results. Will keep an eye on this one.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
