### ISSUE TITLE
Command failed with exit code 2     at ChildProcess.whenDone (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)     at ChildProcess.emit (events.js:110:17)

### ISSUE THREAD

**Issue by d0f** [driftyco/ionic-cli#559]
Error: /root/workspace/web/myApp/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/node/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by jbavari** [comment]
Could you provide information from `ionic info`.

Also, could you tell more about what command you typed in?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by d0f** [comment]
tks

**Comment by Yuvanes** [comment]
**I am getting this error.......!!!!!!!**
Skipping build...
Built the following apk(s):
        C:\Users\w2s-pc\helloWorld\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Using apk: C:\Users\w2s-pc\helloWorld\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Package name: io.ionic.starter
LAUNCH SUCCESS

[ERROR] An error occurred while running cordova run android (exit code 1).

**Comment by shriharip** [comment]
same here!!..

 at ChildProcess.whenDone (/Users/hari/getshared/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:21200) UnhandledPromiseRejectionWarning: Unhandled promise rejection.

**Comment by wowbob396** [comment]
I ran into the same issue as @shriharip , but the solution did not work for me.  I am still receiving the same error.

Here is my ionic project configuration:

cli packages: (C:\Users\Brandon Ly\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v9.11.1
    npm               : 5.8.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Android\sdk

Misc:

    backend : pro


Any help would be greatly appreciated !

**Comment by marvinug** [comment]
one more... please help
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForRelease'.
> A problem occurred starting process 'command '/Users/desarrollo/Library/Android/sdk/ndk-bundle/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/bin/mips64el-linux-android-strip''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
44 actionable tasks: 2 executed, 42 up-to-date
(node:755) UnhandledPromiseRejectionWarning: Error: /Users/desarrollo/Desktop/ionicProyectos/Carbox/carboxDrive/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithStripDebugSymbolForRelease'.
> A problem occurred starting process 'command '/Users/desarrollo/Library/Android/sdk/ndk-bundle/toolchains/mips64el-linux-android-4.9/prebuilt/darwin-x86_64/bin/mips64el-linux-android-strip''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 41s
    at ChildProcess.whenDone (/Users/desarrollo/Desktop/ionicProyectos/Carbox/carboxDrive/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dwieeb** [comment]
Locking this issue as it's 3 years old and has a generic title. None of the posted issues are likely the same issue because superspawn is a utility for spawning child processes, and Cordova uses it _a lot_.

The underlying issue is likely a misconfigured or corrupt native Cordova platform. Try this:

```
rm -rf platforms/ plugins/
cordova prepare
```

This will force Cordova to create a clean platform. If this doesn't work, try updating to the latest Cordova CLI, `cordova-ios`, `cordova-android`. If that doesn't work, please  utilize our [support page](https://ionicframework.com/support).
