### ISSUE TITLE
bug: Which NodeJS version should I use for Ionic?

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#560]
_From @NgYueHong on August 9, 2015 15:27_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I was using Node version 0.10.40 to run Ionic. It seems running fine, however ionic shows this message every-time I run it:

    ******************************************************
     Upgrade warning - for the CLI to run correctly,
     it is highly suggested to upgrade the following:

     Please update your Node runtime to version  >=0.12.x

    ******************************************************

So, I update my Node to version 0.12.7. But then when I try to reinstall cordova & ionic, I get a series of warning & errors such as:

    npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
    npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.7","npm":"2.11.3"})
    npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
    npm ERR! node v0.12.7
    npm ERR! npm  v2.11.3

    npm ERR! unexpected eof
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

It end up fail to install. So, what version of NodeJS should I use?</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4207_

**Comment by mhartington** [comment]
@jbavari would be able to better explain this.

**Comment by adityasaxena** [comment]
Could someone update this thread, please?

I'm getting the following warnings:

```
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.14.1"})
npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.7","npm":"2.14.1"})
```

The installation works fine, though. Just wanted to check if there are things people already know to look out for ?

**Comment by bdeanindy** [comment]
I received similar warnings while trying to install with Node 4.0.0.

```
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.0.0","npm":"2.14.2"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bundled package wasn't found in unpacked tree
```

Will report if I hit any issues with development moving forward.

**Comment by jbavari** [comment]
Everything is fine. Those are just warnings.

What you're seeing is NPM warning you that one of our dependencies, cordova, has these node version and npm versions specified.
