### ISSUE TITLE
ios emulator doesnt have window.device

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#561]
_From @roine on January 15, 2014 15:7_

use a good old regex to detect ios7 on emulator.

_Copied from original issue: driftyco/ionic/pull/422_

**Comment by mhartington** [comment]
_From @mlynch on January 16, 2014 18:34_

I'm going to close this since this works with the `org.apache.cordova.device` plugin is installed properly. And if you have it installed but this isn't firing, that is a separate issue that Adam is working on right now. Thanks!

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
