### ISSUE TITLE
execvp(): Permission denied and events.js:72 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by LeoAref** [driftyco/ionic-cli#565]
Hi there,

I'm trying to run android platform `ionic run android --emulator`

then I got these errors:

```
execvp(): Permission denied
Waiting for emulator...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by jbavari** [comment]
Do you have an emulator running when you run this command?

**Comment by LeoAref** [comment]
Yes

**Comment by jbavari** [comment]
What version of android emulator are you running? I think there is an open issue for 4.1.2 devices.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
