### ISSUE TITLE
Unable to add android or iOS platform for ionic on mac OS X

### ISSUE THREAD

**Issue by shreyvats** [driftyco/ionic-cli#571]
These are system Detail -Please help
ordova CLI: 5.2.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 6.4 Build version 6E35b 
✔ Xcode is installed at /Applications/Xcode.app/Contents/Developer
✔ Xcode Command Line Tools are installed.
✔ DevToolsSecurity is enabled.
✔ The Authorization DB is set up properly.
✔ Node binary found at /usr/local/bin/node
✔ iOS Checks were successful.
Running Android Checks
✔ ANDROID_HOME is set to "/Applications/android-sdk-macosx"
✔ JAVA_HOME is set to "/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home."
✔ ADB exists at /Applications/android-sdk-macosx/platform-tools/adb
✔ Android exists at /Applications/android-sdk-macosx/tools/android
✔ Emulator exists at /Applications/android-sdk-macosx/tools/emulator

**Comment by jbavari** [comment]
What is the output when you type `ionic platform add ios` or `ionic platform add android`?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
