### ISSUE TITLE
Consider re-organizing, slimming the post-creation dialog

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#573]
I kinda like that the CLI provides helpful info after creating a project, but it really feels like it is becoming a bit too much. Here is what I have after just making a new project:

Your Ionic project is ready to go! Some quick tips:

 * cd into your project: $ cd aug26

 * Setup this project to use Sass: ionic setup sass

 * Develop in the browser with live reload: ionic serve

 * Add a platform (ios or Android): ionic platform add ios [android]
   Note: iOS development requires OS X currently
   See the Android Platform Guide for full Android installation instructions:
   https://cordova.apache.org/docs/en/edge/guide_platforms_android_index.md.html

 * Build your app: ionic build <PLATFORM>

 * Simulate your app: ionic emulate <PLATFORM>

 * Run your app on a device: ionic run <PLATFORM>

 * Package an app using Ionic package service: ionic package <MODE> <PLATFORM>

For more help use ionic --help or ionic docs

Visit the Ionic docs: http://ionicframework.com/docs

New! Add push notifications to your Ionic app with Ionic Push (alpha)!
https://apps.ionic.io/signup
+---------------------------------------------------------+
+ New Ionic Updates for August 2015
+
+ The View App just landed. Preview your apps on any device
+ http://view.ionic.io
+
+ Invite anyone to preview and test your app
+ ionic share EMAIL
+
+ Generate splash screens and icons with ionic resource
+ http://ionicframework.com/blog/automating-icons-and-splash-screens/
+
+---------------------------------------------------------+

That is a *butt load* of info. All of it... good... but it really is too much. I'd also argue that this line:

 * cd into your project: $ cd aug26

Is somewhat important and should be moved lower, or actually, should be the very last line. Or something like:

* Your project was created FULLPATHHERE

In my case, I had fired off a creation and forgot what I named the folder, I had to look back over a sea of text (ok, I'm being a bit dramatic) to find the folder name.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
