### ISSUE TITLE
Custom gulpTasks when ionic serve's watch triggers

### ISSUE THREAD

**Issue by ThorstenHans** [driftyco/ionic-cli#577]
I've hooked up a custom gulp task using `gulpStartupTasks` and `documentRoot` is set to a custom `dist` folder. That said, I currently run into the issue that once I change a file in `www` the internal `watch` task is fired within `ionic serve` but right now I can't figure out how to hook custom gulp tasks for exactly that `watch` tasks configured by using `watchPatterns`

Workaround for now is having a second terminal session watching the `www` folder and building new versions to `dist` which works when excluding everything from www using `watchPaterns` for ionic serve

I think something like `gulpWatchTasks` would be helpful here

**Comment by jbavari** [comment]
This is an excellent suggestion.

I'll add it to the list of enhancements.

**Comment by jthoms1** [comment]
Thanks for opening this issue but I believe that we have dropped gulp support for Ionic2.
