### ISSUE TITLE
A new bower/npm task for building out a checked in project in full

### ISSUE THREAD

**Issue by vincpa** [driftyco/ionic-cli#578]
After cloning a repository, the steps I usually follow are:

* npm install
* bower install
* ionic state restore

A single task or command to bring a project up to a working state would be nice. Not all of these commands (especially ionic state restore) are obvious for someone cloning your repo. Most tutorial sites just mention the first two.

An added bonus of a single task or command is that more steps can be added to the standard Ionic build process later.

**Comment by jbavari** [comment]
This is an excellent suggestion.

We'll put it in the queue for enhancements.

**Comment by vincpa** [comment]
Is this something that would be better fit for the `ionic` command or a gulp task?

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
