### ISSUE TITLE
Consider caching of https://github.com/driftyco/ionic-app-base/archive/master.zip

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#580]
I've been doing some Ionic presentations on the other side of the planet (Australia and now Malaysia), and I'm finding that it can take 1-2 minutes to get https://github.com/driftyco/ionic-app-base/archive/master.zip. Obviously that isn't the end of the world, but it might be nice to do some caching of that zip and only fetch it when it is updated. Certainly my use case (making a bunch of demos) is not the norm, but for a developer learning, it may impact them.

**Comment by cfjedimaster** [comment]
Just an FYI, as I continue to present on Ionic across Asia, this just gets worse and worse. The CLI really should cache this locally and reuse it. Or consider using a CDN for the file.

**Comment by jthoms1** [comment]
This might be something we have talked about doing in the future, but probably not within the generic CLI code. Thanks for the suggestion!
