### ISSUE TITLE
ionic run ios & ionic emulate ios fail on node 4.0 on OSX

### ISSUE THREAD

**Issue by mhoffmeyerDC** [driftyco/ionic-cli#584]
Running either `ionic run ios` or `ionic emulate ios` on OSX silently fail with no output. Somewhat related to #560 but seems to be a different issue.

[Relevant forum post](http://forum.ionicframework.com/t/ionic-build-emulate-ios-does-nothing/32280/3)

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0
ios-sim version: 5.0.0
OS: Mac OS X Yosemite
Node Version: v4.0.0
Xcode version: Xcode 7.0 Build version 7A152u

Reverting back to node 0.12.7 and it works correctly.

**Comment by ravishtiwari** [comment]
It seems to be issue with Node 4.0, ionic documentation does not mention required node version, but, since it worked with older version of Node, it looks issue with Node 4.0 issue.

**Comment by mhoffmeyerDC** [comment]
Seems to have been working on the 4.2.1 LTS release of Node.

**Comment by saurabhskhetan** [comment]
Doesnt work on Node 5.0.0

**Comment by sumitk** [comment]
Same here ... does not work with Node 5.0.0
