### ISSUE TITLE
ionic emulate ios doing nothing (sometimes)

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#586]
I've reproduced this in two Ionic apps now but I can't tell you where it happens in some but not all. I do 

    ionic emulate ios

and nothing happens. No error - nothing. I also tried --debug, but nothing shows up.

**Comment by cfjedimaster** [comment]
It seems to be all new apps. :(

**Comment by cfjedimaster** [comment]
So I removed ios, added it, and it worked.

**Comment by mithun-daa** [comment]
I am facing this exact same issue. I upgraded to the newest Ionic by running the following command:
```
npm install -g ionic
```
How did you remove iOS?
```
ionic remove platform ios
```
??

**Comment by cfjedimaster** [comment]
ionic platform rm ios


On Mon, Sep 21, 2015 at 2:03 PM, Mithun Patel <notifications@github.com>
wrote:

> I am facing this exact same issue. I upgraded to the newest Ionic by
> running the following command:
>
> npm install -g ionic
>
> How did you remove iOS?
>
> ionic remove platform ios
>
> ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-cli/issues/586#issuecomment-142078458>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by mithun-daa** [comment]
Sweet!! that did it. Thank you.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
