### ISSUE TITLE
bug: should not execute command in non-ionic directory

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-cli#588]
_From @ohfang on September 16, 2015 2:21_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all platforms</span>  <span ionic-webview>cli</span>

<span ionic-description>I accidentally execute this command "ionic platform add adnroid" in the PARENT directory of my ionic project folder, and it continues running, and "Downloading: https://github.com/driftyco/ionic-default-resources/archive/master.zip" , and create a resources directory.
It should have stopped executing immediately.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4366_

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
