### ISSUE TITLE
ionic start with zip file

### ISSUE THREAD

**Issue by skyfitz79** [driftyco/ionic-cli#592]
Using Continuous Integration, I would like to recreate and build my app with Jenkins.

In my build script, I do not want to download each time the blank template so I try to create a new Ionic app with this command : 

ionic start -z <path-to>/ionic-starter-blank-master.zip <app-name>

It does not work and still try to download start template from: https://github.com/driftyco/ionic-app-base/archive/master.zip

I've also try the following command according to "start" help command:

ionic start -t <path-to>/ionic-starter-blank-master <app-name> (with zip uncompressed)
ionic start -t blank -z <path-to>/ionic-starter-blank-master.zip <app-name>

I can not find the solution

Please help me :)

**Comment by jbavari** [comment]
Have you tried just pulling your files from git and rebuilding them instead of starting a new app each time?

**Comment by jawache** [comment]
+1 

-z doesn't seem to work at all (perhaps should be removed from the docs if it's intended).

From investigations so far it seems like it's getting parsed and then completely ignored by https://github.com/driftyco/ionic-app-lib/blob/master/lib/utils.js#L188 i suspect it needs to add it as options.zipFileDownload but trying that out locally I seem to be missing quite a few other steps as well (the zip files downloading but the end project is still a blank starter project).

**Comment by jawache** [comment]
Oh and as an explanation, i'm looking for a way to let people start projects based off a zip file.

**Comment by skyfitz79** [comment]
@jbavari the main purpose for me is to rebuild from scratch the application with continuous integration...

@jawache I managed to create my own template by not using "ionic start" but instead merging those 2 zip from : 
https://github.com/driftyco/ionic-app-base
and 
https://github.com/driftyco/ionic-starter-blank

then you can replace resources, www or any content and use ionic commands (do not forget to do npm install & bower install if necessary)

@jbavari if -z or any other option could work from zip or local directory it would be nice ! Perhaps you have a better idea for continuous integration process ?

To both of you, thanks for your help !!!

**Comment by adamdbradley** [comment]
Greetings @skyfitz79!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
