### ISSUE TITLE
bug: Failing hook does not fail build (exit code)

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#594]
_From @NicholasTuck on September 23, 2015 19:50_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>If I have a failing hook that exits non 0 (like a before_build doing a webpack build), ionic will recognize the hook failed, and will stop building, but it exits with code 0. This makes my automated build tool, Jenkins, not know it's actually failing.  

cordova build fails in a nearly identical way, but it does exit code 1 as expected.

Ionic reporting exit 0: 
![image](https://cloud.githubusercontent.com/assets/5945021/10056785/69896aa2-6202-11e5-90eb-3de49aca7338.png)

Cordova reporting exit 1: 
![image](https://cloud.githubusercontent.com/assets/5945021/10056799/79346f6a-6202-11e5-9d38-f84ee30aca14.png)
</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4417_

**Comment by mhartington** [comment]
whats the hook?

**Comment by mhartington** [comment]
_From @NicholasTuck on September 23, 2015 20:0_

It's a before_build hook that does our webpack build, that's just a node script that runs webpack.  
Fairly simple: 
```
#!/usr/bin/env node
'use strict';

process.env['NODE_ENV'] = 'production';

var webpack = require('webpack');
var webpackConfig = require('../../webpack.config');

webpack(webpackConfig, function(error, stats) {
    if (error) {
        console.error('Webpack build failed: ' + error);
        if(stats) {
            console.error('Webpack Stats: ' + stats.toString({ colors: true}));
        }
        process.exit(1);
    }
});
```

**Comment by NicholasTuck** [comment]
Any expectation of this being fixed in ionic1?  We continue to use cordova build and we haven't discovered side effects, but it is in the back of my mind the day ionic build does something special.

**Comment by aszmyd** [comment]
+1

**Comment by jakub-g** [comment]
+1

**Comment by jakub-g** [comment]
I found the culprit here... 
https://github.com/driftyco/ionic-cli/blob/957596cecf029184f097778aef89ebe95072d56b/lib/ionic/cordova.js#L75-L78

    .then(function() {
      return self.runCordova(cmdName, argv);
    })
    .then(function(runCode) {
      //We dont want to do anything if the cordova command failed
      if(runCode !== 0 || argv.nosave) {
        return
    }

I guess instead of `return` we should `throw`?

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
