### ISSUE TITLE
ionic state save not saving version info to package.json

### ISSUE THREAD

**Issue by ravishtiwari** [driftyco/ionic-cli#596]
Hi, 
I recently install version 1.1.0 of **cordova-plugin-whitelist** using:
```
cordova plugin add cordova-plugin-whitelist@1.1.0
```
I did this to tag the specific version of whitelist plugin. after this, I saved the state using 
```
ionic state save
```
However, I found that tag was not there for plugin in **package.json**, manually updating the package.json installs the correct version with ** ionic state restore **, but, sate save is not saving version information to package.json

-Ravish

**Comment by ravishtiwari** [comment]
any update on this?

**Comment by poornerd** [comment]
this is unsettling for me, too

Is there any new status on it?

**Comment by jakub-g** [comment]
related: #665

**Comment by ravishtiwari** [comment]
I have found a workaround for this, which I am going to try, in Apache Cordova documentations, here : https://cordova.apache.org/docs/en/dev/platform_plugin_versioning_ref/

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
