### ISSUE TITLE
Ionic 2.0.0-alpha.3 npm installation fails on node@4.1.1, npm@2.14.4

### ISSUE THREAD

**Issue by martysmind** [driftyco/ionic-cli#597]
This is probably low priority, but the Ionic installation is failing for 2.0.0-alpha.3 on node@4.1.1, npm@2.14.4.  It apears to be dependencies that are failing.  When I upgrade all of the dependencies to the latest version in the package.json everything builds without error.

Errors start with indirect dependenncy on older bufferutil...

> In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^

**Comment by imsingh** [comment]
Yeah. That is happening on Node 4.x. I can confirm it is happening on Ubuntu too.

**Comment by cismous** [comment]
+1

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
