### ISSUE TITLE
`ionic upload` tampers with meta tags in index.html

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#600]
When I call `ionic upload` my index.html is changed and subsequently breaks:

Original:
`<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' 'unsafe-eval'">`

Changed:
`<meta http-equiv="Content-Security-Policy" content="default-src * &apos;unsafe-inline&apos; &apos;unsafe-eval&apos;">`

My system information:
```
> ionic info

Your system information:

Cordova CLI: 5.3.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
OS: Windows 7 SP1
Node Version: v0.12.7
```

**Comment by robksawyer** [comment]
+1

This is still an issue in `1.6.5` CLI.

**Comment by johnfake** [comment]
yep, it's annoying

**Comment by robksawyer** [comment]
I agree.

**Comment by tlancina** [comment]
This should be fixed in the latest version of the CLI. Let us know if you're still having issues, thanks!
