### ISSUE TITLE
ionic build does not reflect cordova's exit code

### ISSUE THREAD

**Issue by Azenet** [driftyco/ionic-cli#609]
If cordova fails to build when I run e.g. `ionic build android`, the log will say that cordova exited with a certain exit code but ionic will exit with code 0.

**Comment by danydev** [comment]
+1 This is really silly when you want to integrare `ionic build android` on your CI system and you rely on the status code to stop the script

**Comment by danydev** [comment]
@jthoms1 you closed it because it has been fixed or because it won't be fixed?

**Comment by pvdyck** [comment]
Please reopen, this is obviously a bug.
The same happens for all the ionic commands.
