### ISSUE TITLE
Error opening .apk in device, after making ionic build

### ISSUE THREAD

**Issue by bogoquiz** [driftyco/ionic-cli#612]
After you create an apk with ionic build command does well, but get this message in red

: compileDebugJavaNote: C: \ Users \ alman \ ionic \ test \ platforms \ android \ src \ org \ ap
ache \ Cordova \ splashscreen \ SplashScreen.java use or overrides a deprecated API.
Note: Rebuild With -Xlint: deprecation for details.

after trying to open the apk generate the device and I get error opening the file.

What could be the problem?

**Comment by fabulous-fab14** [comment]
This is not a bug with Ionic, it has something to do with cordova. I stumble across this post and I have the same issue, but I am not using Ionic!

**Comment by jgw96** [comment]
Hello, i would recommend updating to the latest version of cordova. This seems to be an issue iwth cordova that has been fixed with the latest version. Thanks for using Ionic!
