### ISSUE TITLE
ionic-cli npm package always ahead of release

### ISSUE THREAD

**Issue by kamilbrk** [driftyco/ionic-cli#613]
Hi,

Probably just a nitpick, but when an "Ionic CLI is out of date" message is shown with a link to CHANGELOG.md on GitHub, the master branch is always out of date, so it does not include information about the suggested update.

Example:

```
Ionic CLI is out of date:
 * Locally installed version: 1.6.5
 * Latest version: 1.7.0
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update
```

With that message, master branch is still on 1.6.5, so I have to switch to develop branch to see v1.7.0 in changelog.md file.

Why is the npm package published before the release is signed off and merged to master?

Cheers!

**Comment by Neophy7e** [comment]
+1 I just experienced the same issue

**Comment by schurig** [comment]
+1

**Comment by wundo** [comment]
+1
