### ISSUE TITLE
npm install -g ionic throws "unexpected eof" on Ubuntu 14.4

### ISSUE THREAD

**Issue by susobhan** [driftyco/ionic-cli#614]
Hi,
I am getting following issue on Ubuntu. Cleaning tmp file or clearing cache does not work , same result. Please help.

```
npm verb fstream_stack Extract.Reader.resume (/usr/lib/node_modules/npm/node_modules/fstream/lib/reader.js:249:34)
npm verb fstream_stack Entry.<anonymous> (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:261:8)
npm verb cwd /tmp
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic" "--verbose"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4

npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

**Comment by gautamchitnis** [comment]
i am seeing the same error on windows 8.1 please help someone...i have tried 32/64 bit versions of nodejs. i have tried changing registry url as well.. no luck...

**Comment by jgw96** [comment]
Hello all! Are you all still having this issue? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
