### ISSUE TITLE
ionic.project shouldn't be required

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-cli#615]
Right now when you do something like `ionic serve`, you get this error unless you're in an ionic project:

`Unable to locate the ionic.project file. Are you in your project directory? (CLI v1.6.5)`

We might want to restrict that to certain commands that actually need that

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
