### ISSUE TITLE
Export from 'Creator' broken

### ISSUE THREAD

**Issue by AntonRand** [driftyco/ionic-cli#619]
I've created several projects using Ionic creator and executed:

ionic start [appName] creator:[MY_ID]

The project downloads but the contents of the index page in the www directory is blank. If I do the same with a non-existent project I get the same result so it looks like the CLI isn't picking up my project.

I've done a download as ZIP and this contains my index page which isn't blank. Is there anything I can look for to see what's going wrong here?

The result of the URL in the log line saying 'Downloading Creator Prototype' is empty.

Version is 1.7.1
OS is Windows 7

**Comment by AntonRand** [comment]
Something weird is happening with the URLs.

Ionic CLI is calling the following URL: 
https://apps.ionic.io\api\v1\creator\[MY_ID]\download\html

Ionic Creator provides the following download URL: https://creator.ionic.io/api/v1/creator/[MY_ID]/download/html

The Ionic CLI URL returns an empty zip file. Whereas the Creator URL contains my app.

 Have the URLs recently changed?

**Comment by AntonRand** [comment]
I've upgraded from 1.7.2 to 1.7.6 today and it's now working.

It's using the following URL now - 

https://creator.ionic.io/api/v1\creator\[ID]\download-start\cordova?sid=[SID]

**Comment by sciencefyll** [comment]
I'm having the same problem. After using the cli to download the project and using ionic start, nothing happens. The app jumps to its default route, which is something like /#/sidemenu-21. And i hav eno idea why.
