### ISSUE TITLE
Ionic loses track of build process on OSX

### ISSUE THREAD

**Issue by mariusmarais** [driftyco/ionic-cli#622]
When running `ionic build ios`, Ionic loses track of the Cordova process, exiting prematurely (without any errors), while the actual build process continues in the background.  This can be seen by keeping an eye on the Activity Monitor.

The hook scripts defined for `after_prepare` and `before_compile` run correctly and a lot of `xcodebuild` output is shown, but the command exits early.  This is most noticeable when running a `--device` build while watching the Activity Monitor, which shows many `clang` processes being created and completing.  

Repeating the command usually gives the expected result, probably because the second compilation is a lot shorter than the first as everything has already compiled.

Running `cordova build ios [--device]` directly has the correct behaviour.

Versions:
  * OSX: 10.11, but reproduced on 10.10
  * ionic-cli: 1.6.4 & 1.7.6
  * cordova cli: 5.2.0 & 5.3.3

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
