### ISSUE TITLE
spawn google chrome ENOENT

### ISSUE THREAD

**Issue by herrerodani** [driftyco/ionic-cli#623]
After updating to ionic@alpha, 'ionic serve' gives me 'spawn google chrome ENOENT' error and I have to init it using 'ionic serve -b'.

**Comment by thelonecabbage** [comment]
I am having the same problem

**Comment by jbavari** [comment]
What version of the CLI are you using?

**Comment by herrerodani** [comment]
I have 2.0.0-alpha.9

**Comment by irhabi** [comment]
The same problem here...

**Comment by tlancina** [comment]
This should be fixed in latest version of the CLI (`ionic@alpha`), please re-open https://github.com/driftyco/ionic-app-lib/issues/37 if it's not, thanks!
