### ISSUE TITLE
ionic platform add iOS and ionic build iOS doesn't work correctly. all plugins are not compiled when opened in Xcode

### ISSUE THREAD

**Issue by boyfunky** [driftyco/ionic-cli#624]
So i am running my project and each time i do ionic build iOS. sometimes some of my cordova plugins do  not compile and appear on the iOS/Project Name/Plugins folder. And in the event whereby they all compile, when i open the built xcodeproject, in the Plugins folder, it doesn't compile all the plugins and some are left out. I have tried various things. 

i have deleted my ios.json file in my ProjectName/plugins folder as suggest and done ionic platform remove ios and then ionic platform add iOS but still no avail, i have repeated the same process but with cordova platform remove iOS and cordova platform add ios but still no luck. 

Thought maybe something wrong with my Xcode. I am now using 
xcode 7.1, 
ionic -v 1.6.5.
cordova 3.9.1
Sox El capitan 10.11 
but it is also still happening. 

at all times, the plugin cordoba-plugin-whitelist never gets compiled to the ios/Project name/Plugins folder.  I have also tried rebuilding the project but still same issues. All works fine on Android. only ios having issues. 

Any ideas why?

**Comment by jbavari** [comment]
I'd suggest updating to the latest Cordova CLI version, as many of those new plugins require latest cordova CLI:

`npm install -g cordova`

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by immnk** [comment]
This is my ionic info : 
Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.9.0 
ios-sim version: 5.0.10 
OS: Mac OS X El Capitan
Node Version: v7.0.0
Xcode version: Xcode 8.1 Build version 8B62 

And I have the same problem
