### ISSUE TITLE
bug: installation failed with npm install -g ionic

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-cli#627]
_From @elhamsarikhani on October 21, 2015 14:54_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>I'm trying to install ionic  using
npm install -g ionic
but I get this error:
![s](https://cloud.githubusercontent.com/assets/14323843/10640305/b4c67c4e-7846-11e5-8c10-b01083a1763d.png)
</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#4547_

**Comment by mhartington** [comment]
_From @MesutGulecen on October 21, 2015 16:23_

you must  to  download node.js and cordova first.

**Comment by mhartington** [comment]
_From @elhamsarikhani on October 22, 2015 4:13_

Thank you I installed node.js and now it's fine : ]

**Comment by mhartington** [comment]
_From @MesutGulecen on October 22, 2015 7:37_

You're welcome :)

**Comment by hitmantb** [comment]
I am having the same exact issue, I could not resolve this until I downgraded NodeJS and NPM to 0.10.4.  I spent hours uninstall/reinstall NodeJS and NPM.  

Did you manage to resolve this issue on latest NodeJS and NPM versions?  What did you do exactly?  I just downloaded NodeJS x64 (I tried x86, same thing), installed Cordova (works every time), and got the unexpected eof error every time.

**Comment by TheMattRay** [comment]
+1

**Comment by elhamsarikhani** [comment]
Guys installing the latest version of nodeJS solved my issue

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
