### ISSUE TITLE
ios info-plist overriding

### ISSUE THREAD

**Issue by surfjedi** [driftyco/ionic-cli#632]
Is there a command or flag to run "ionic build ios"  but have it not overwrite the plist?

I need to set the allowed orientations in xcode(since the cli can't accept them from config.xml).

Every time i run the build command it resets my plist?

**Comment by mhartington** [comment]
This is done at the cordova level of things, which should be fixed in cordova-ios 4.0.

An alternative is to install this plugin which you can add those back after everything has been done.

https://www.npmjs.com/package/cordova-config-utils
