### ISSUE TITLE
ERROR: npm install -g ionic   in Windows 8.1

### ISSUE THREAD

**Issue by yypccc** [driftyco/ionic-cli#633]
2210 error Windows_NT 6.3.9600
2211 error argv "D:\\Program Files (x86)\\Node.js\\node.exe" "D:\\Program Files (x86)\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
2212 error node v4.2.1
2213 error npm  v2.14.7
2214 error code ECONNRESET
2215 error errno ECONNRESET
2216 error syscall read
2217 error network read ECONNRESET
2217 error network This is most likely not a problem with npm itself
2217 error network and is related to network connectivity.
2217 error network In most cases you are behind a proxy or have bad network settings.
2217 error network
2217 error network If you are behind a proxy, please make sure that the
2217 error network 'proxy' config is set properly.  See: 'npm help config'
2218 verbose exit [ 1, true ]

**Comment by mhartington** [comment]
The error message tells you the problem. Looks like a network connectivity issue on your end.

**Comment by yypccc** [comment]
Thanks,I'm in China and no proxy.Maybe network issue.What should i do?
