### ISSUE TITLE
ionic state restore modifies package.json

### ISSUE THREAD

**Issue by gaboesquivel** [driftyco/ionic-cli#637]
As you can see here the `ionic state restore` command modifies package.json, in ionic 1.7.7

![](http://bit.ly/1RTAlC7)

and it duplicates entries
```diff
diff --git a/mobile/package.json b/mobile/package.json
index 7da6eaf..ad39da3 100644
--- a/mobile/package.json
+++ b/mobile/package.json
@@ -57,9 +57,15 @@
   "cordovaPlugins": [
     "org.apache.cordova.device",
     "org.apache.cordova.console",
+    "com.ionic.keyboard",
+    "com.ionic.keyboard",
+    "org.apache.cordova.device",
+    "org.apache.cordova.console",
+    "org.apache.cordova.device",
+    "org.apache.cordova.console",
     "com.ionic.keyboard"
   ],
   "cordovaPlatforms": [
     "ios"
   ]
-}
+}
```

**Comment by bendetat** [comment]
I found that this was a bug in `/hooks/after_plugin_add/register_plugins.js`so it's more likely a fixed issue in `ionic-generator` - https://github.com/diegonetto/generator-ionic/commit/db42a4ac9e1fd4fdc130ebe7e8990409c1b6571e

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
