### ISSUE TITLE
ionic build ios, ionic run ios & ionic emulate ios fail on node 5.0 on OSX

### ISSUE THREAD

**Issue by saurabhskhetan** [driftyco/ionic-cli#639]

**Comment by osahner** [comment]
Seems to be cordova/node 5.0 related. 
cordova -d build ios fails without any output.

**Comment by jbavari** [comment]
Please try updating your cordova CLI to 5.4.0 - as the new update should fix things for Node 5.0.

News update: http://cordova.apache.org/news/2015/11/06/tools-release.html

**Comment by troyanskiy** [comment]
node v5.1.1
cordova 5.4.1
That works for me

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
