### ISSUE TITLE
`ionic upload` adds '﻿&#xFEFF;' in beginning of index.html

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#640]
Every time I run `ionic upload` it messes with my index.html. I already documented the changes to my meta tags in #600, now I noticed other strange behaviour: ﻿`<!DOCTYPE html>` is replaced by `&#xFEFF;<!DOCTYPE html>`.

**Comment by tlancina** [comment]
Does this help? https://github.com/driftyco/ionic-view-issues/issues/10#issuecomment-103950080

**Comment by piotrowski** [comment]
I don't have Visual Studio, but I used Notepad++ to change the encoding of the file to "UTF-8 without BOM" and now `ionic upload` doesn't add the strange characters any more, just did something strange with whitespace. After committing this to git, `ionic upload` doesn't trigger any changes to the doctype any more. Thanks.

(Let's hope none of my editor changes the encoding back...)

(#600 is still happening of course)

**Comment by tlancina** [comment]
This should be fixed in the latest version of the CLI. Let us know if you're still having issues, thanks!
