### ISSUE TITLE
(/plugins as own git repository) `ionic platform add *` tries to install plugin ' .git'

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#642]
When you have /plugins in its own git repository and try to `ionic platform add *` you get the following error message:

> Cannot find plugin.xml for plugin '.git'. Please try adding it again.

**Comment by jbavari** [comment]
Most people do not check in the platforms or plugins folder. Those are generated folders.

However, i've gone ahead and fixed this issue with [this commit](https://github.com/driftyco/ionic-app-lib/commit/cecf648a5b47bb394cbaea2eb665518ddca2066c).

**Comment by piotrowski** [comment]
:+1:
