### ISSUE TITLE
IPAs are not accepted by Apple anymore because of CFBundleResourceSpecification in plist

### ISSUE THREAD

**Issue by mohsinjk** [driftyco/ionic-cli#643]
The final Info.plist contains the "CFBundleResourceSpecification" which is not longer accepted by Apple.

Application Loader error message: ERROR ITMS-90339: "This bundle is invalid. The Info.plist contains an invalid key 'CFBundleResourceSpecification' in bundle <myApp> [myApp.app]"

Any solution or up coming release to fix this problem?

**Comment by jbavari** [comment]
First I'd ask what version of cordova CLI you have - and if not 5.3.3 or later, i'd suggest updating that. Cordova controls most of the Info.plist entries, and I think they've updated that.

Try running `ionic info` or `cordova -v` to get more version information.

**Comment by mohsinjk** [comment]
I am using IONIC.IO service to build my app package (.ipa) http://docs.ionic.io/docs/package-ios
I don't know that service have the latest cordova CLI. I hope ionic will fix this issue so that I can publish my app to app store.

**Comment by piotrowski** [comment]
http://docs.ionic.io/docs/issues

**Comment by jbavari** [comment]
@mohsinjk Aha, that helps us deduct the issue. I was assuming you were just building locally.

I'll report your issues about the package service to our team that handles that.

**Comment by mohsinjk** [comment]
@jbavari thanks. I looking forward.

**Comment by dwieeb** [comment]
@mohsinjk I updated the iOS build servers to the latest xcode and cordova-ios. Can you try again?

**Comment by mohsinjk** [comment]
@dwieeb @jbavari Thanks a lot. Perfect! Now I can submit my App to App store. Thanks IONIC :)

**Comment by jbavari** [comment]
Yep. Closing.
