### ISSUE TITLE
`ionic resources` removes comments from config.xml

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#645]
When I run `ionic resources` all comments are removed from my config.xml that I put there to be able to understand better what all the different tags actually do, why I added them etc.

**Comment by PhilHuot** [comment]
I have a similar issue where `ionic resources` breaks the `<config-file>` block in the `config.xml` file.


See this example where `<key>anotherinsecurehttp.com</key>` is moved right next to `<key>insecurehttp.com</key>` which becomes invalid once it gets to the .plist file.

Before ionic resources

       <config-file parent="NSAppTransportSecurity" platform="ios" target="*-Info.plist">
            <key>NSAppTransportSecurity</key>
            <dict>
                <key>NSExceptionDomains</key>
                <dict>
                    <key>insecurehttp.com</key>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                    <key>anotherinsecurehttp.com</key>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                </dict>
            </dict>
        </config-file>

After ionic resources:

       <config-file parent="NSAppTransportSecurity" platform="ios" target="*-Info.plist">
            <key>NSAppTransportSecurity</key>
            <dict>
                <key>NSExceptionDomains</key>
                <dict>
                    <key>insecurehttp.com</key>
                    <key>anotherinsecurehttp.com</key>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                </dict>
            </dict>
        </config-file>

**Comment by tomkeble** [comment]
Is there any update on this issue please? I am also facing the problem of it removing all comments from config.xml. It's marked as important but nothing appears to have been done in the 18 months since it was raised!

**Comment by kaiukdevelopment** [comment]
We are also having the same problems where it is re-ordering the config-file list. This causes issues as when building for iOS, if they are not in the right order then the builder will ignore them and as we are using this to tell iOS that we need permissions to the camera and gallery, our app crashes!

**Comment by piotrowski** [comment]
@kaiukdevelopment Could you maybe also post your starting values and what it gets transformed into?

**Comment by kaiukdevelopment** [comment]
Before
`        <config-file parent="" target="*-Info.plist">
            <array>
                <key>NSCameraUsageDescription</key>
                <string>blah blah blah</string>
                <key>NSPhotoLibraryUsageDescription</key>
                <string>blah blah blah</string>
                <key>NSLocationWhenInUseUsageDescription</key>
                <string>blah blah blah</string>
            </array>
        </config-file>`

After

`        <config-file parent="" target="*-Info.plist">
            <array>
                <key>NSCameraUsageDescription</key>
                <key>NSPhotoLibraryUsageDescription</key>
                <key>NSLocationWhenInUseUsageDescription</key>
				<string>blah blah blah</string>
				<string>blah blah blah</string>
                <string>blah blah blah</string>
            </array>
        </config-file>`

It has changed from 'key, string, key, string, key, string' to 'key, key, key, string, string, string'

**Comment by piotrowski** [comment]
Excuse my ignorance, but is the "before" valid and working? Such a strange format... 
(Still, what `ionic cordova resources` does of course shouldn't happen - XML library probably)

**Comment by dwieeb** [comment]
Everything in this issue likely has to do with our usage of xml2js. I made this issue: https://github.com/driftyco/ionic-cli/issues/2332 There are a number of other reasons to switch to elementtree. 

@piotrowski The `<key>`/`<dict>` usage is plist configuration format. It's strange, but yes, it's valid. The ordering of XML should be maintained, but for some reason xml2js defaults this to off, thus **breaking** an XML read/write cycle.

**Comment by dwieeb** [comment]
Closing in favor of my grouped issue: https://github.com/driftyco/ionic-cli/issues/2332
