### ISSUE TITLE
Setup sass requires sudo on OSX El Capitan

### ISSUE THREAD

**Issue by soniyj** [driftyco/ionic-cli#649]
After the creation of a new project, the sass setup fails while tries to create the lock under the .npm directory
```
ionic setup sass
```
```
npm WARN locking Error: EACCES, open '/Users/soniyj/.npm/_locks/gulp-concat-b305b5df9ec4ad00.lock'
```

No problem if you run the command with sudo
```
sudo ionic setup sass
```
```
Successful sass build
Ionic setup complete
```

**Comment by mlynch** [comment]
Sounds like you've got incorrect permissions on your local directory. This happens often with npm so I'm going to close since it's not related to Ionic from what I can tell. Thanks!

**Comment by soniyj** [comment]
Actually I got the problem only with ionic, whilst other npms software are working correctly. Anyway thanks for the response.
