### ISSUE TITLE
ionic state restore: silently ignores cordova plugin add errors

### ISSUE THREAD

**Issue by jopelkey** [driftyco/ionic-cli#650]
I updated my package.json to try out a new cordova-custom-config@1.1.5 version.
Turns out that this version of the plugin has a dependency issue and fails to add, but when running
'ionic state restore', the underlying error from the 'cordova plugin add cordova-custom-config@1.1.5' is not displayed and is silently ignored, leading it to look like the ionic command was indeed successful.  I'd prefer to see that error so I know there are issues with the underlying plugins.  Not seeing that makes troubleshooting/debugging much more difficult and misleading.

**i.e. if I run 'ionic state restore' I get this output - which makes it look like everything is ok:**
% ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios@3.9.2

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-custom-config@1.1.5
cordova plugin add cordova-plugin-console@1.0.1
cordova plugin add cordova-plugin-device@1.0.1
cordova plugin add cordova-plugin-dialogs@1.1.1
cordova plugin add cordova-plugin-globalization@1.0.1
cordova plugin add cordova-plugin-media@1.0.1
cordova plugin add cordova-plugin-screen-orientation@1.4.0
cordova plugin add cordova-plugin-splashscreen@2.1.0
cordova plugin add cordova-plugin-vibration@1.2.0
cordova plugin add cordova-plugin-whitelist@1.1.0
cordova plugin add ionic-plugin-keyboard@1.0.7
cordova plugin add phonegap-plugin-push@1.4.2
Restore plugins is complete

Ionic state restore completed

**But when I run 'ionic plugin add cordova-custom-config@1.1.5 I see the expected errors**
Fetching plugin "cordova-custom-config@1.1.5" via npm
Installing "cordova-custom-config" for ios
Failed to install 'cordova-custom-config':Error: Cannot find module 'read-package-json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at getPackagesFromJson (/src/aa/push/devo/mobile/plugins/cordova-custom-config/hooks/resolveDependencies.js:17:18)
    at installRequiredNodeModules (/src/aa/push/devo/mobile/plugins/cordova-custom-config/hooks/resolveDependencies.js:77:5)
    at module.exports (/src/aa/push/devo/mobile/plugins/cordova-custom-config/hooks/resolveDependencies.js:97:3)
    at runScriptViaModuleLoader (/src/aa/push/devo/mobile/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:151:18)
    at runScript (/src/aa/push/devo/mobile/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:129:16)
    at /src/aa/push/devo/mobile/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:114:20
Error: Cannot find module 'read-package-json'

**Comment by jbavari** [comment]
Yep, we just patched that [in this PR](https://github.com/driftyco/ionic-app-lib/pull/27).

We'll release it soon. Thanks for reporting.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
