### ISSUE TITLE
upload success but size "nan undefined" in ionic view

### ISSUE THREAD

**Issue by apokalupsis** [driftyco/ionic-cli#654]
Hi, i am in china and I upload my project with CLI, 3 week ago it was working but now is not.
event when I get a upload successful, I can't download on the app in ionic view, It write SIZE: NAN UNDEFINED.
I try a lot for a week already, and in diffrent place.
I try with a new project, same problem.
If i use VPN I get a error with CLI.
    ionic/node_modules/ionic-app-lib/lib/upload.js:276
    response.setEncoding('utf8');
   TypeError: Cannot read property 'setEncoding' of undefined

There is my environment:
Cordova CLI: 5.1.1
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.8
Ionic App Lib Version: 0.6.4
ios-deploy version: 1.8.2 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.0.1 Build version 7A1001 

Thanks.

**Comment by lmolema** [comment]
Have the same problem

**Comment by alissonbovenzo** [comment]
have the same problem too

**Comment by skokaina** [comment]
Have the same problem

**Comment by LaneTwo** [comment]
Have the same problem.

**Comment by sagarora77** [comment]
Hey All, just delete the www.zip and it will be fine...

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
