### ISSUE TITLE
invalid exit code for hooks after an error

### ISSUE THREAD

**Issue by aszmyd** [driftyco/ionic-cli#655]
When we have some error in hook (even simple `throw 'Error'`) and we use ionic-cli to i.e. add new platform or plugin, the exit code after the command is 0 but it should not be because of error thrown in hook.
Using normal `cordova` command line tool, it breaks as it should.

Example:

**hooks/after_plugin_add/hook.js**
``` 
#!/usr/bin/env node

throw 'Error'
```

Shell script to execute:
```
ionic plugin add foo
ionic plugin add bar
```

this **DOES NOT** break. But this:

```
cordova plugin add foo
cordova plugin add bar
```

breaks and it should. 

Above behavior does not allow CI build script to work as expected - break on errors.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
