### ISSUE TITLE
More descriptive error when running project commands outside of project

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-cli#658]
Running `ionic build ios` throws ENOENT `config.xml` not found, which we can definitely make more descriptive

**Comment by brandyscarney** [comment]
I opened a similar issue on ionic2, do you want me to close it? https://github.com/driftyco/ionic2/issues/514

**Comment by tlancina** [comment]
You can leave it open. The more issues, the more likely it gets fixed :)

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
