### ISSUE TITLE
Bug: `ionic config set` crashes silently when file is missing

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#661]
I tried `ionic config set app_id 09....f2` to change my app_id. I also got output `Saved app_id, writing to ionic.io.bundle.min.js...` but in git I noticed that this file wasn't modified.

I remembered I just removed `ionic.io.bundle.js`as I didn't use it. So I restored it, and after running `ionic config set app_id` this and the .min file are modified with the app_id.

So seems `ionic config set` crashes with no message when one of these files is missing, and also doesn't tell me on the console that it is modifying the non-.min version.

PS: This could also be a ionic-platform-web-client bug, but as this is triggered from the CLI I think it probably belongs here.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
