### ISSUE TITLE
Feature Request: `ionic state save --pin`

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#665]
`ionic state save` currently builds the `cordovaPlugin` list in `package.json` by collecting the plugin names from `plugins/fetch.json`. It would be nice if we could indicate, that we want to "pin" the current version of the plugins and the CLI somehow figures out a way to get the current version of the plugin and adds it as `@x.y.z` after the plugin name so future `ionic state restore` will restore exactly that version.

(Idea how to get plugin version: package.json and config.xml of plugin folder both contain the `version`)

**Comment by jakub-g** [comment]
+1

**Comment by poornerd** [comment]
+1

**Comment by ravishtiwari** [comment]
I think alternatively, we should be able to use Cordova commands for this:
https://cordova.apache.org/docs/en/dev/platform_plugin_versioning_ref/

of course, we would love to see ionic state save/restore doing this.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
