### ISSUE TITLE
`ionic state save` doesn't save the plugin version even when I explicitly mentioned it in the package.json

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#666]
I have set the plugin version of multiple cordovaPlugins explicitly in `package.json` after the big update to Cordova plugins. `plugins/fetch.json` also contains the version numbers as it should. 

But when I do `ionic state save` my package.json gets recreated without all these versions, so a future `ionic state restore/reset` won't work as intended. Is this intended that this information is ignored or is this a bug and should be fixed?

**Comment by poornerd** [comment]
I have the same problem

**Comment by tomsun** [comment]
Same issue here when using Git urls with refs.

Attempting to target tag `r1.0.0` in this example, which `plugins/fetch.json` captures correctly, but which `ionic state save` omits in `package.json`, which means `ionic state restore` picks the latest version:

```
$ ionic plugin add https://github.com/apache/cordova-plugin-console.git#r1.0.0
Fetching plugin "https://github.com/apache/cordova-plugin-console.git" via git clone
Repository "https://github.com/apache/cordova-plugin-console.git" checked out to git ref "r1.0.0".
Installing "cordova-plugin-console" for android
Installing "cordova-plugin-console" for ios
Saving plugin to package.json file
```
```
$ cat plugins/fetch.json
...
    "cordova-plugin-console": {
        "source": {
            "type": "git",
            "url": "https://github.com/apache/cordova-plugin-console.git",
            "subdir": ".",
            "ref": "r1.0.0"
        },
        "is_top_level": true,
        "variables": {}
    }
...
```
```
$ ionic state save
```
```
$ cat package.json
...
    {
      "locator": "https://github.com/apache/cordova-plugin-console.git",
      "id": "cordova-plugin-console"
    }
...
```
```
$ cordova plugin remove cordova-plugin-console
Uninstalling cordova-plugin-console from android
Uninstalling cordova-plugin-console from ios
Removing "cordova-plugin-console"
```
```
$ ionic state restore
Attempting to restore your Ionic application from package.json

...

cordova plugin add https://github.com/apache/cordova-plugin-console.git 
Restore plugins is complete

Ionic state restore completed
```

```
$ cat plugins/cordova-plugin-console/package.json |grep version
  "version": "1.0.3-dev",
```

**Comment by tomsun** [comment]
Letting npm fetch the source locally can be a viable workaround sometimes (requires a package.json in the plugin repo):
```
npm install --save git+https://github.com/apache/cordova-plugin-console.git#r1.0.0
ionic plugin add ./node_modules/cordova-plugin-console
ionic state save
```

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
