### ISSUE TITLE
`ionic state save` changes the list of platforms in `package.json` even when no changes

### ISSUE THREAD

**Issue by piotrowski** [driftyco/ionic-cli#667]
Before:

    "cordovaPlatforms": [
      "android",
      "ios"
    ]

After:

    "cordovaPlatforms": [
      "android",
      "ios",
      {
        "platform": "android",
        "version": "",
        "locator": "android"
      },
      {
        "platform": "ios",
        "version": "",
        "locator": "ios"
      }
    ]

This is not a real problem, but causes a change to the file (obviously) and so shows modified files in git. Also it's just more characters for the same information, that is now duplicated.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
