### ISSUE TITLE
Document compatibility with nodejs

### ISSUE THREAD

**Issue by jakub-g** [driftyco/ionic-cli#668]
Hi,

with node versions changing quickly recently, I think it's important to document which versions of node you support (at least the oldest one). It would be a good information for the users and also the contributors to know what APIs and language features they can use. I glance briefly though readme, wiki, package.json but did not find anything.

I'm using node 0.12 for now and it works fine. Maybe I'd like to contribute one day but I don't know if I have to be compatible with node 0.10 etc.

I think compat info in README is one of very undervalued things in JS community in general. Would be great to see it better documented :)

Regards
Jakub

**Comment by jgw96** [comment]
Hello, you can find the docs for this [here](http://ionicframework.com/docs/v2/cli/). Thanks for using Ionic!
