### ISSUE TITLE
 ionic start error:  Not found: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip (404)

### ISSUE THREAD

**Issue by jQrgen** [driftyco/ionic-cli#669]
I get the following error running this command: 

<b>jqrgen@jQrgenpc:~$ ionic start MyIonic2Project tutorial --v2</b>
Creating Ionic app in folder /home/jqrgen/MyIonic2Project based on tutorial project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip
 ✗ Not found: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip (404)
 ✗ Please verify the url and try again.

**Comment by InnerPeaceStudios** [comment]
Same for me today

**Comment by Thommas** [comment]
See http://stackoverflow.com/questions/24721917/unable-to-create-ionic-project
