### ISSUE TITLE
ionic cli not respecting --id and --appname 

### ISSUE THREAD

**Issue by jdat82** [driftyco/ionic-cli#673]
If I understand correctly, you can give an app name and id when creating your app. It make your life easier by not forcing you to change it manually in every file after. 

I tried several dozens of combination and can't get it to work. The app is created but always with a default bundle id and name. 

ionic-cli: 1.7.10
ionic: 1.1.1

Here is my command : 

```bash
ionic start myapp sidemenu -a MyApp -i com.me.myapp
```

I also tried will long names and with `-t`…

Here is the default bundle id in `config.xml` : `com.ionicframework.starter`
Default app name in `package.json` and several other files : `ionic-project`.

I'm wondering also if the `xcodeproj` file shouldn't be renamed too based on app name ?

I'm also wondering why the latest git tag for 1.7.x releases on github is `1.7.7` when I have `1.7.10`?
 
Thanks a lot. It seems like a very simple task but I can't get it to work.

**Comment by mlynch** [comment]
Looking into this...

**Comment by mlynch** [comment]
I think I see what's going on here. The actual project config.xml is not updated to match the root one. Not sure if that's an issue as ionic build will fix that. Thinking...

**Comment by jdat82** [comment]
In fact that's not true, the root one is not updated at all. But I found a hack. I run my command twice.

You run the command, then you go inside your generated folder and rerun command. For whatever reason I don't understand, the second time, config.xml, packge.json and xcodeproj files are uptodate. 

One very surprising thing too, is that if you run a command like `ionic platform add …` inside the second generated folder, it will modify platforms in the first one !

So here is a final tree : 
- myapp
  - hooks
  - platforms
  - www
  - myapp
    - hooks
    - www

Then of course you just have to extract the second generated app elsewhere, get rid of the first one and work normally.

**Comment by jdat82** [comment]
I didn't say that I work with latest version of node : 5.1.0. Didn't try with older ones though.

**Comment by kelvindart** [comment]
I am also having the same issue; I raised the issue here: http://stackoverflow.com/questions/34123700/ionic-cli-ignoring-flags-parameters and here: https://forum.ionicframework.com/t/ionic-cli-ignoring-flags-parameters/38610.

**Comment by kelvindart** [comment]
This is Node v5.x related - having rolled back to Node v4.2.3, the above command runs fine and creates everything as expected the first time, using supplied arguments.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
