### ISSUE TITLE
Yosemite gets detected as El Capitan (Wrong OS detection)

### ISSUE THREAD

**Issue by mrzmyr** [driftyco/ionic-cli#678]
![screen shot 2015-12-03 at 20 22 06](https://cloud.githubusercontent.com/assets/746429/11571323/09bde198-99fc-11e5-88e3-bdb2ff0a4d69.jpg)

```bash
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.10
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.7.0
ios-sim version: 4.1.1
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.1.1 Build version 7B1005
```

**Comment by JayBizzle** [comment]
Yes, i also noticed this the other day

**Comment by aparkerw** [comment]
I get the incorrect OS detection as well.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
