### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by TheMattRay** [driftyco/ionic-cli#679]
Can someone please update the changelog? It's way behind I feel!

**Comment by jimmont** [comment]
As are the release tags, mentioned it here in #681 before seeing this issue. A bit slack on the details at drifty. Makes me worry.

**Comment by adamduren** [comment]
:+1: It peculiar when the CLI tells you to update and links to an outdated changelog.

**Comment by troyanskiy** [comment]
+1

**Comment by ibewugb** [comment]
+1

**Comment by domharrington** [comment]
:+1: Slightly confusing when the CLI notifies that you're out of date, but i can't see a note in the changelog or a tag in the releases.

**Comment by JeremyPlease** [comment]
+1

**Comment by SMERKY** [comment]
+1

**Comment by johnmcase** [comment]
+1

**Comment by palaniraja** [comment]
No update yet...

![screen shot 2016-02-29 at 8 23 26 pm](https://cloud.githubusercontent.com/assets/124864/13407839/6607847a-df22-11e5-9d36-301d8b2002ec.png)

**Comment by TheMattRay** [comment]
Still a thing.

**Comment by mlynch** [comment]
Changelog should stay updated now, sorry about this.
