### ISSUE TITLE
Ionic-cli install err

### ISSUE THREAD

**Issue by MutoMagic** [driftyco/ionic-cli#680]
I get the following error when run "npm install -g ionic":

    134723 info install ionic-cordova-lib@5.1.10
    134724 info postinstall ionic-cordova-lib@5.1.10
    134725 verbose unlock done using C:\Users\MuTo\AppData\Roaming\npm-cache\_locks\ionic-cordova-lib-ce4c6a9d6f1bab02.lock for C:\Users\MuTo\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib
    134726 info node-sass@3.4.2 Failed to exec postinstall script
    134727 verbose unlock done using C:\Users\MuTo\AppData\Roaming\npm-cache\_locks\node-sass-12bd046c7f703398.lock for C:\Users\MuTo\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\node-sass
    134728 verbose about to build C:\Users\MuTo\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib
    134729 verbose unlock done using C:\Users\MuTo\AppData\Roaming\npm-cache\_locks\ionic-app-lib-0a71c8fea32e0860.lock for C:\Users\MuTo\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib
    134730 verbose about to build C:\Users\MuTo\AppData\Roaming\npm\node_modules\ionic
    134731 verbose unlock done using C:\Users\MuTo\AppData\Roaming\npm-cache\_locks\ionic-9e947323b442f4e9.lock for C:\Users\MuTo\AppData\Roaming\npm\node_modules\ionic
    134732 verbose stack Error: node-sass@3.4.2 postinstall: `node scripts/build.js`
    134732 verbose stack Exit status 1
    134732 verbose stack at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
    134732 verbose stack at EventEmitter.emit (events.js:110:17)
    134732 verbose stack at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
    134732 verbose stack at ChildProcess.emit (events.js:110:17)
    134732 verbose stack at maybeClose (child_process.js:1016:16)
    134732 verbose stack at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
    134733 verbose pkgid node-sass@3.4.2
    134734 verbose cwd C:\Users\MuTo
    134735 error Windows_NT 6.3.9600
    134736 error argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
    134737 error node v0.12.8
    134738 error npm  v2.14.9
    134739 error code ELIFECYCLE
    134740 error node-sass@3.4.2 postinstall: `node scripts/build.js`
    134740 error Exit status 1
    134741 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
    134741 error This is most likely a problem with the node-sass package,
    134741 error not with npm itself.
    134741 error Tell the author that this fails on your system:
    134741 error node scripts/build.js
    134741 error You can get their info via:
    134741 error npm owner ls node-sass
    134741 error There is likely additional logging output above.
    134742 verbose exit [ 1, true ]
    134743 verbose unbuild node_modules\ionic\node_modules\ionic-app-lib\node_modules\node-sass
    134744 info preuninstall node-sass@3.4.2
    134745 info uninstall node-sass@3.4.2

thanks in advance

**Comment by junyuz** [comment]
I have a same error,I install node@1.10.36 still error

**Comment by MutoMagic** [comment]
At first I thought it was the cause of nodejs, but I was wrong. when I tried "npm install -g ionic@1.7.9" in node@5.1.1, it was successful. I saw a lot of build err in ionic@1.7.10/1.7.11.

Please give me some advice. Thanks.

**Comment by MutoMagic** [comment]
I have solved this problem. If the node-sass compiler error occurs, please upgrade vs to 2015, install successfully in node@5.1.1.
