### ISSUE TITLE
bug: Neither "ionic platform update ios" nor "ionic build ios" updates plugins in the "platforms/ios" directory

### ISSUE THREAD

**Issue by matthewlloyd** [driftyco/ionic-cli#682]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Example:

```
macbook-pro-2:ionic-app mil$ diff plugins/ionic-plugin-deploy/src/ios/IonicDeploy.m platforms/ios/UAV\ Forecast/Plugins/ionic-plugin-deploy/IonicDeploy.m
242d241
<             [self updateVersionLabel:NOTHING_TO_IGNORE];

macbook-pro-2:ionic-app mil$ ionic platform update ios
...
macbook-pro-2:ionic-app mil$ ionic build ios
...

macbook-pro-2:ionic-app mil$ diff plugins/ionic-plugin-deploy/src/ios/IonicDeploy.m platforms/ios/UAV\ Forecast/Plugins/ionic-plugin-deploy/IonicDeploy.m
242d241
<             [self updateVersionLabel:NOTHING_TO_IGNORE];

```

The line added to the file in the ```plugins/``` directory was added in v0.4.1, to fix a bug which broke deploys on iOS.</span>

<span is-issue-template></span>

**Comment by SMERKY** [comment]
Would this possibly be the reason my ionic app in ios is not detecting any of the plugins? How can I check to see if the plugins are getting popuated in the platform correctly?

**Comment by matthewlloyd** [comment]
Possibly, yes. Look in the platforms/ios/<app_name>/Plugins directory, and compare with the plugins directory.
