### ISSUE TITLE
how create ionic app ?: Resolve problem: Cannot find module 'config-chain' (CLI v1.7.11)

### ISSUE THREAD

**Issue by VERKYSSE** [driftyco/ionic-cli#689]
first :download and install : node js ; git ; apache ant ; and java .
second:install cordova and ionic with this cmd : npm install -g cordova and after do : npm install -g ionic@alpha

last :ionic start appName.

I had the same problem but I can not find resolved the module 'config- chain '
how i PROCESS I had version 5 node js and I have moved Ionic (2): Ionic @ alpha .but I had to go back on version 4.2.3 node js to create my first application with Ionic .
Je eu le même problème, que j'ai  résolu 
comment j'ai resolus j'etait a la version  5 de node js et jai installé ionic 2: Ionic@alpha .mais je suis revenir sur la version 4.2.3 de node  pour créer ma première application avec ionic

**Comment by tlancina** [comment]
Hey there, did this get resolved? If not, could you post the output of `ionic info` please?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
