### ISSUE TITLE
--sass flag doesn't seem to have any effect

### ISSUE THREAD

**Issue by jawache** [driftyco/ionic-cli#690]
Running `ionic start --sass myapp tabs` I would expect to create the project already setup for sass.

Instead it seems to ignore the --sass completely and sets up a normal project and we have to run "ionic setup sass" in the project instead.

➜  mt  ionic info

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.8
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v0.12.2
Xcode version: Xcode 7.2 Build version 7C68

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
