### ISSUE TITLE
Allow for creation in current directory w/o wiping out .git metadata

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#694]
I started a new project where the client already had a new, empty Git repo. I cloned into foo. I then CDed into foo, and did: ionic start ./ sidemenu. (As an aside, I tried to use "." instead of "./" and the CLI thought I meant it as a name.) The CLI downloaded the template but blew away existing code in the project, which included the .git subdirectory. So now I need to do: re-clone the dir. Make a new ionic project outside the folder. Copy it in. Not the end of the world, but it would be nice if I didn't need to do that.

**Comment by jthoms1** [comment]
This will be resolved in the next CLI release v3.
