### ISSUE TITLE
SocketException: Connection reset

### ISSUE THREAD

**Issue by julmot** [driftyco/ionic-cli#695]
<span ionic-description>After running `ionic build android` I get the following error:
![ionic-err](https://cloud.githubusercontent.com/assets/8310677/11719454/2f87e932-9f5b-11e5-8447-95eebf1823bc.png)
Unfortunately I am not able to solve the issue without some instructions. Is anyone familar with such an issue?</span>

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by julmot** [comment]
@jthoms1 Where has this issue been resolved?
