### ISSUE TITLE
`ionic generate` commands broken

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic-cli#696]
After upgrading to the latest beta CLI using the:

ionic g page MyPage

and others don't work. I'm receiving the following error:

You do not appear to have a compatible version of Ionic v2 installed.
Ionic Framework v2 version 2.0.0-alpha.31 or later is required to use the generators.
Please run: "npm install ionic-framework" (CLI v2.0.0-beta.12)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.7.0
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by 3dd13** [comment]
did a brief digging in the code
so it was the line that require the PROJECT_FOLDER/node_modules/ionic_framework that causes the error
 
https://github.com/driftyco/ionic-cli/blob/v2-beta/lib/ionic/generate.js#L54

**Comment by 3dd13** [comment]
ok, found this patch https://github.com/driftyco/ionic2/commit/8c421116fe117407df4ee492679033bab73a497d

in theory, it will work soon when the latest ionic2 master branch (ionic-framework) is released to npm
- this patch included the tooling directory (which includes the generators)
- the package.json main is already pointing to tooling/index.js

**Comment by 3dd13** [comment]
just tested on running the latest ionic master in my local machine, the generator works.
so, just wait for the ionic2 / ionic-framework release ~

![screen shot 2015-12-21 at 20 00 35](https://cloud.githubusercontent.com/assets/223555/11930337/8eca559a-a81d-11e5-946f-2612a395ac0b.png)

**Comment by joshuamorony** [comment]
Generate commands seem to be working again, however they are still generating at www/app/module even though the app folder has been moved outside of the www folder.

**Comment by 3dd13** [comment]
Luchillo has fixed that in master:
https://github.com/driftyco/ionic2/commit/c59d07df44619d7fed8a07384df592f3b626109a

but not yet released to npm registry

**Comment by jgw96** [comment]
Hello all! As this seems to have been fixed in the latest release i am going to close this for now. Feel free to comment if you are still having this issue with the latest version of the cli and i will reopen. Thanks for using Ionic!

**Comment by vsouto** [comment]
I'm also having this problem. 
I tried using ionic 2.0.0 and the last release 2.1.15 , both gave me the same error.

![image](https://cloud.githubusercontent.com/assets/2797129/21144510/1dd742b0-c132-11e6-8ef2-12848a81e00a.png)
