### ISSUE TITLE
Docs: Ionic Generate Error Message

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic-cli#698]
kind of related to another issue: https://github.com/driftyco/ionic-cli/issues/696

when you run ionic g somethingsomething,
the error message was confusing that it catches every exception and blamed the ionic version not match.
the code is at this line: https://github.com/driftyco/ionic-cli/blob/v2-beta/lib/ionic/generate.js#L68

I think return the exception message and the stack would be helpful for debugging.
if you do want to hide the exception from general users, perhaps printing the help message ?

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
