### ISSUE TITLE
I have a React.JS application.

### ISSUE THREAD

**Issue by export-mike** [driftyco/ionic-cli#701]
Hi I have a react.js app thats bundled into a cordova app. We're using a fair amount of cordova plugins but what we really are missing is a build thats controlled by a tool the rest of the community is using. It feels to me the rest of the cordova landscape use custom scripts to install stuff to repeat developer environments and automate on CI for builds. Its always felt that its been left out, and ionic has it, but has a hard dependency on its web tooling. 

Currently we have a custom gulp script which accesses cordova lib directly and grabs the cordova modules and puts them into our dist/bundle.js and runs the cordova platform add and plugin install.

I want ionic state restore and save equivalent. Is there anything stopping me? is this feature isolated? Will it bring in any unecessary dependencies? ideally I want to have  ```cordova restore``` with no dependency on angular as we're not using it.

feel free to delete this issue, I won't mind, I just don't feel a question like this will be picked up on SO. 

I guess the hard dependency on angular is the issue (any chance of pulling restore out of ionic?).

**Comment by mhartington** [comment]
The state command isn't really tied to angular, but just saves the plugin name to the package.json under a custom property. So when they run `ionic plugin add cordoba-plugin-device`, it will save the plugin name, included any version tags under a `cordovaPlugins` array in your package.json

This is possible already without the ionic-cli though. `cordova plugin add cordoba-plugin-device --save` will save it to the config.xml. Then the next time you build, it will see you have a plugin in the config.xml, and automatically install it for you

**Comment by export-mike** [comment]
Hey thanks for replying, I wasn't aware of the --save flag. that's really useful. Cheers!
