### ISSUE TITLE
bug: XCode T&C causes incorrect error message during a build

### ISSUE THREAD

**Issue by budda** [driftyco/ionic-cli#704]
Type: bug

Platform: ios 8 webview
```
$ ionic build ios
The provided path ".../platforms/ios" is not a Cordova iOS project.
```
I had to agree to the latest XCode update terms to get past this stupid and incorrect error message.

I'm guessing this is a Cordova CLI problem being passed through Ionic?
Can we improve error messages?

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
