### ISSUE TITLE
only upload,  No icon and splash screen generated in folders !

### ISSUE THREAD

**Issue by cispune** [driftyco/ionic-cli#706]
Ionic icon and splash screen resources generator
 uploading icon.png...
 uploading splash.png...

after that nothing happens and no any icon created in resources folder, whats the issue

**Comment by Artimuss** [comment]
Hi.

Same issue.

My images were too big. Extract them with option "File smaller (8 bits)" (Fichier plus petit 8 bits in french) in photoshop has solved the problem.

Guess it can help you.

**Comment by blablapolicja** [comment]
+1
@Artimuss 's hint doesn't work
my icon's size is 15 kb. splash - 856 kb

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.4.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by evancillo** [comment]
same issue here... that's weird, i'm pretty sure it was working some days ago

**Comment by jgw96** [comment]
Hello all! Unfortunately I am having some trouble reproducing this on my machine. Is there anything specific that seems to cause the issue?

**Comment by evancillo** [comment]
Hey!, 

it did work a few days after this issue was published..    it’s all ok now!. 

Best,

**Comment by jgw96** [comment]
Awesome, thanks for the update! I will close this issue for now, but if you have the same issue again feel free to comment and ill reopen (: Thanks for using Ionic!
