### ISSUE TITLE
Can't create app for v1 by using v2 ionic-cli

### ISSUE THREAD

**Issue by bagusflyer** [driftyco/ionic-cli#707]
Got the following error message:

> [=============================]  100%  0.0s
{ [Error: Command failed: /bin/sh -c ionic plugin add cordova-plugin-device && ionic plugin add cordova-plugin-console && ionic plugin add cordova-plugin-whitelist && ionic plugin add cordova-plugin-splashscreen && ionic plugin add cordova-plugin-statusbar && ionic plugin add cordova-plugin-statusbar && ionic plugin add ionic-plugin-keyboard

> Couldn't find ionic.project file. Are you in an Ionic project? (CLI v2.0.0-beta.15)

> ]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c ionic plugin add cordova-plugin-device && ionic plugin add cordova-plugin-console && ionic plugin add cordova-plugin-whitelist && ionic plugin add cordova-plugin-splashscreen && ionic plugin add cordova-plugin-statusbar && ionic plugin add cordova-plugin-statusbar && ionic plugin add ionic-plugin-keyboard' } '\n\u001b[1m\u001b[31mCouldn\'t find ionic.project file. Are you in an Ionic project?\u001b[39m\u001b[22m\u001b[1m\u001b[31m (CLI v2.0.0-beta.15)\u001b[39m\u001b[22m\n\n'

> Unable to add plugins. Perhaps your version of Cordova is too old. Try updating (npm install -g cordova), removing this project folder, and trying again: (CLI v2.0.0-beta.15)

> Your system information:

> Cordova CLI: 5.4.1
> Gulp version:  CLI version 3.9.0
> Gulp local:  
> Ionic Version: 1.2.1
> Ionic CLI Version: 2.0.0-beta.15
> Ionic App Lib Version: 2.0.0-beta.8
> ios-deploy version: 1.8.2 
> ios-sim version: 4.1.1 
> OS: Mac OS X El Capitan
> Node Version: v5.3.0
> Xcode version: Xcode 7.2 Build version 7C68

**Comment by mnewmedia** [comment]
+1

**Comment by architruc** [comment]
+1
I have Ionic 1 and Ionic 2 projects. Installing back Ionic 1 to create a sample project (to test/isolate an issue for example) and reinstalling Ionic 2 is not convenient (and veeery long from China :) )

**Comment by jgw96** [comment]
Hello all! Are you all still having this issue with the latest version of the ionic-cli (beta.25)?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by alexcoroza** [comment]
Im always seeing tutorials about creating ionic1 project with command "ionic start projectName". I used this command and it dwonloads files for ionic 2. This is still a problem now!!!!!

**Comment by danielsogl** [comment]
Because they use the old CLI version. Read the docs and you will understand how to use the new CLI :)

**Comment by alexcoroza** [comment]
oh I see. Im using the latest ionic cli right now then I saw that you have to add "--v1" in the command. So "ionic start projectName --v1" is how to create a new ionic 1 project
