### ISSUE TITLE
ionic framework instalation  module.js error 340

### ISSUE THREAD

**Issue by kumar269** [driftyco/ionic-cli#711]
![error](https://cloud.githubusercontent.com/assets/6340047/12073676/42109c72-b151-11e5-8109-92a2e3da5fa2.JPG)
Hi friends...

       i am using windows xp platform and i am install all supporting software nodejs,cordova but ionic frameworks is not installing. two day's on wards i am trying to install ionic in my pc.. environment varibles(C:\Program Files\nodejs\;C:\Program Files\nodejs\node_modules;C:\Program Files\nodejs\node_modules\npm;C:\Program Files\nodejs\node_modules\npm\bin\;C:\Program Files\nodejs\node_modules\npm\node_modules;C:\Program FilesJava\jdk1.8.0_45\bin;C:\prasad\ionic\adt-bundle-windows-x86_64-20140702\sdk\platform-tools;C:\prasad\ionic\adt-bundle-windows-x86_64-20140702\sdk\tools;C:\prasad\ionic\apache-ant-1.9.4\bin;C:\Documents and Settings\Kumar\Application Data\npm;C:\Program Files\nodejs\node_modules\npm\bin;C:\Program Files\WinAntbin;C:\Documents and Settings\Kumar\node_modules). any one know this problem solution pls tell me..

**Comment by jgw96** [comment]
Referencing #810

**Comment by jgw96** [comment]
Hello! We do not currently support windows xp anymore. Thanks for using Ionic!
