### ISSUE TITLE
ionic install error 

### ISSUE THREAD

**Issue by kumar269** [driftyco/ionic-cli#712]
ionic install error 
![npm](https://cloud.githubusercontent.com/assets/6340047/12089839/0d66e976-b30f-11e5-8805-de43d9bfa563.JPG)
pls solve this proble any one...........

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
