### ISSUE TITLE
Create resources for iPad pro

### ISSUE THREAD

**Issue by Manduro** [driftyco/ionic-cli#713]
The `ionic resources` command does not create the app icon needed for the new iPad Pro:
iPad Pro (@2x) App icon required 167x167

Also an icon of 60x60@1x is created which is not used by XCode (7.2).

**Comment by jpike88** [comment]
This is important, there's no point building all icons but one, as it makes the tool useless as this is required for iPad apps to build.

**Comment by danmichaelo** [comment]
I looked into if I could submit a pull request for this, but while the sizes are defined in https://github.com/driftyco/ionic-app-lib/blob/master/lib/resources.js , Ionic uses an API at http://res.ionic.io to generate the files :( I could get it to generate the 167x167 icon, but the 2732x2048 splash screen fails with `{"Error":"invalid height: 2732"}`… so the API needs to be updated.

**Comment by youssmak** [comment]
+1

**Comment by ArjenBroeze** [comment]
+1

**Comment by fanals** [comment]
+1

**Comment by geo242** [comment]
+1

**Comment by jawgardner** [comment]
+1

**Comment by kalilmaciel** [comment]
+1

**Comment by owurman** [comment]
+1 =D

**Comment by gsanjeevkumar** [comment]
+1 will this be resolved soon, or do we have a work around ?

**Comment by evoshawkins** [comment]
+1

**Comment by DrewK289** [comment]
+1

**Comment by karser** [comment]
+1

**Comment by HOllarves** [comment]
+1

Any news on this issue?

**Comment by ThinkGraphical** [comment]
+1

**Comment by antulik** [comment]
+1

**Comment by irthos** [comment]
+1

**Comment by wuman01** [comment]
+1

**Comment by Senen** [comment]
+1

**Comment by lhristov** [comment]
+1

**Comment by CyrixInstead** [comment]
+1

**Comment by emilyemorehouse** [comment]
+1

**Comment by marcandreappel** [comment]
+1

**Comment by seand88** [comment]
+1

**Comment by leonardobazico** [comment]
+1

**Comment by emilyemorehouse** [comment]
I made some traction on this today. I'm working on a PR to ionic-app-lib and got someone on the Ionic team to look into what needs to be updated with res.ionic.io so we can get this fixed.

**Comment by ArjenBroeze** [comment]
New to this. So how do I use this, do I need to update ionic or its libs or will this automatically get into a next update?

**Comment by luco** [comment]
+1

**Comment by LebToki** [comment]
+1
