### ISSUE TITLE
Ionic serve error, after switching to SASS

### ISSUE THREAD

**Issue by unostella** [driftyco/ionic-cli#714]
Built a new project and when switched to SASS, couldn't run `ionic serve` anymore.
Installed CLI 2.0.0-beta.16 and now this error still comes up but at least gets ignored so that allows me to run `gulp watch` in other tab and actually keep using SASS.

Error I am getting:

```javascript
$ ionic serve
Gulp startup tasks: 0=sass, 1=watch
Running live reload server: undefined
Watching: 0=www/**/*, 1=!www/lib/**/*
 ✗ Caught exception:
 Error: spawn gulp ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

√ Running dev server:  http://localhost:8100
```

I've checked previous posts with similar problem but nothing worked for me.

Here is also what I got installed:

```bash
$ npm list --depth=0
tdguide-app@1.1.1 /Users/admin/Drive/_local/test-app
├── bower@1.7.2
├── gulp@3.9.0
├── gulp-concat@2.6.0
├── gulp-minify-css@0.3.13
├── gulp-rename@1.2.2
├── gulp-sass@2.1.1
├── gulp-util@2.2.20
└── shelljs@0.3.0
```

![screen shot 2016-01-08 at 20 03 26](https://cloud.githubusercontent.com/assets/5081340/12206762/f5bd0e4a-b642-11e5-8684-36759de6c0af.png)

Any idea?
Thanks

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
