### ISSUE TITLE
SplashScreen low resolution on android tablet

### ISSUE THREAD

**Issue by mrzmyr** [driftyco/ionic-cli#715]
The splashscreen image is fuzzy (look like low resolution) only on Android.
I used the Ionic splashscreen PSD template and then `ionic resources`.

I guess I'm not the first who came across that issue:
https://forum.ionicframework.com/t/splashscreen-low-resolution-on-android-tablet/20064

**Comment by Sentence** [comment]
+1

**Comment by m0nzderr** [comment]
+1

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
