### ISSUE TITLE
ionic resources still creating icons with black backgrounds for IOS

### ISSUE THREAD

**Issue by alexkb** [driftyco/ionic-cli#716]
For those using `ionic resources` to generate icons, icons with transparent backgrounds work perfectly for Android, but it seems those same icons in iOS cause a black background to be shown. I used the `ionic resources` tool back in April 2015, and it must of set those transparent backgrounds to white back then, as we didn't have that issue.

For the time being, we have to create our icons to white, or manually create the iOS versions (perhaps a batch task in photoshop will be another quick way around it).

This was originally raised via #547 but closed for some reason. Thanks.

**Comment by barocsi** [comment]
+1

**Comment by mhjam** [comment]
As far as I see `ionic resources` produces icons with transparent icons, but they become black on the iPhone. Looks like Apple is to "blame" for that: See https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/AppIcons.html ("Avoid transparency: ... If .. you use transparency ... the resulting icon can appear to float on a dark background") .

Anyway, the solution for me was to read the ionic documentation twice, and then follow it ;-) See http://blog.ionic.io/automating-icons-and-splash-screens/, section "Platform Specifics":

> To use different source images for individual platforms, place the source image in the respective platform’s directory.

So I produced two icon.psd with different background color (transparent for Android, white for iOS), put them in android and ios subfolders - and enjoyed getting icons generated with different background colors.
