### ISSUE TITLE
serve from a different address than localhost

### ISSUE THREAD

**Issue by seiyria** [driftyco/ionic-cli#720]
I'v seen [this thread](https://forum.ionicframework.com/t/ionic-serve-set-host-and-port-number/3876/3) and [this issue](https://github.com/driftyco/ionic/issues/1295). I'm not sure my particular case was addressed, nor can I find anything in the docs.

Right now, if I run `ionic serve` it will open `localhost:8100`. However, I need to have `localhost` aliased to `retro` (a short version of my app name) so I can use auth0 and have it not spit out a bunch of CORS errors at me. It would be a lot easier if I could make `ionic serve` open `retro:8100` instead, as a result. Is this possible with the current Ionic CLI (1.7.2)? If not, can this be implemented?

**Comment by tlancina** [comment]
Should be possible with the `--address` flag: `ionic serve --address=retro`.

Going to close this, but feel free to reopen if you're still having issues, thanks!

**Comment by seiyria** [comment]
Works like a charm, thank you! Is there any place ionic options are all documented?

**Comment by tlancina** [comment]
Great! I believe docs are on the roadmap, but you can get the available flags for any command by running `ionic help [command]`, for example `ionic help serve`, and `ionic help` to see all available commands (right now it shows their flags as well, but this will be removed in the future).

**Comment by tlancina** [comment]
Oop looks like there are already docs up for v2: http://ionicframework.com/docs/v2/cli/serve/ :)

**Comment by seiyria** [comment]
Fabulous. It looks like some docs are missing (for example, `--address`), but that's a nice ref. Could not find anything like that before!
