### ISSUE TITLE
Cannot generate resources for iOS using Cordova iOS 4.0.0 / 4.0.1

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic-cli#721]
running the command `ionic resources` generates resources but they do not show up in the app or XCode ...

This issue only occurs when using Cordova iOS 4.0.0+

**Comment by jgw96** [comment]
Hello all! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1166. Thanks for using Ionic!
