### ISSUE TITLE
console.log and console.warn are out of order on Windows

### ISSUE THREAD

**Issue by jakub-g** [driftyco/ionic-cli#722]
I have the following code in `hooks\before_prepare\010_create_distribution.js`
 (I think the text has to be long enough to trigger the behavior, that's why I put multiple letters)

```
console.warn('aaaaaaaaaaaaaaaa')
console.warn('bbbbbbbbbbbbbbbb')
console.log('cccccccccccccccccc')
console.log('dddddddddddddddddd')
```

Now, when I run `cordova run android` it prints in proper order. Fine for now.

But when I run `ionic run android`, I see stuff out of order: 

```
aaaaaaaaaaaaaaaa          (in red)
cccccccccccccccccc
dddddddddddddddddd
bbbbbbbbbbbbbbbb          (in red)
```

My guess is that ionic does some overrides, maybe you do something like redirecting `console.warn` to a different stream (`stderr`?) that triggers this behavior?

Win7, ionic 1.7.12

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
