### ISSUE TITLE
After installing crosswalk, the javascript in the lib folder can't be found and loaded.

### ISSUE THREAD

**Issue by PrimeObjects** [driftyco/ionic-cli#726]
Please help

**Comment by jgw96** [comment]
Hello! Are you still having this issue? If so, could we have a little more info on it? Such as if your getting any errors, what commands you ran to get the issue and steps to reproduce? Also if you could run `ionic info` and post the output here that would be great. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
