### ISSUE TITLE
Missing updates to CHANGELOG.md

### ISSUE THREAD

**Issue by DOFandersolsen** [driftyco/ionic-cli#727]
I was just notified that a new Ionic CLI was available:

```
------------------------------------
Ionic CLI is out of date:
 * Locally installed version: 1.7.12
 * Latest version: 1.7.13
 * https://github.com/driftyco/ionic-cli/blob/master/CHANGELOG.md
 * Run npm install -g ionic to update
------------------------------------
```

However, the CHANGELOG.md file have not been updated since version 1.7.7
This makes it very hard to see what potential change might have caused a break in mine or others code that is based on Ionic.

Kind regards
Anders

**Comment by jimmyhax** [comment]
Agreed. I'm sure we all would like to know what changes have been made before we update. 
Thanks in advance.

**Comment by s200920014** [comment]
+1

**Comment by mcintosh101** [comment]
+1

**Comment by andRyanMiller** [comment]
+1

**Comment by GC-Mark** [comment]
+1

**Comment by malek-bessaies** [comment]
+1

**Comment by calebfaruki** [comment]
+1

We're now on v1.7.14. Changelog remains at 1.7.7

**Comment by TheMattRay** [comment]
Duplicate of #679

**Comment by jgw96** [comment]
Hello all, as this is a dupe of #679 i will be closing this issue. Thanks for using Ionic!
