### ISSUE TITLE
The "www/lib" directory should be configurable

### ISSUE THREAD

**Issue by jasonhulbert** [driftyco/ionic-cli#728]
I see that the installation dir (www/lib) is very much set in stone as far as the cli is concerned. Shouldn't this be configurable? I'm currently putting together a gulp/webpack build which includes ionic. Sourcing the www/lib folder seems dirty. I'm working around this currently by moving "www/lib/ionic" to the desired "src/lib/ionic" after running ``install`` or ```update```. The bundle would ultimately end up in www/js so would be included in a build. Other packages are not a problem as they comply with the .bowerrc ```directory``` value.

**Comment by jthoms1** [comment]
I believe that we are keeping this as a convention of all Ionic apps.  Thanks for the suggestion.
