### ISSUE TITLE
Ionic 2 CLI not building

### ISSUE THREAD

**Issue by gkedzierski** [driftyco/ionic-cli#732]
It looks like some kind of an issue might've been introduced between a few days ago and now. None of the `ionic` CLI commands building / starting the V2 project are working anymore - there is no output and the `ionic` command returns 0 exit code.

It works correctly with V1 projects.

Example workflow:

```
$ ionic start example-project --v2

One awesome Ionic app coming right up...

Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing Node Modules

♬ ♫ ♬ ♫  Your Ionic app is ready to go! ♬ ♫ ♬ ♫

..etc...

$ cd example-project
$ ionic serve
$ 
```

Other commands that are not working: (in exactly the same way - nothing happens, no output)

- `ionic emulate`
- `ionic build`

Reinstalling ionic completely doesn't help.

Here's `ionic info` output:

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.53
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.4 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by tlancina** [comment]
Hmm very strange, I'm unable to reproduce this.  Here's my info as a sanity check:
```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:
Ionic Version: 2.0.0-alpha.55
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2 Build version 7C68
```

I don't believe we made any drastic changes to either the CLI or starter project structure, so I'm not sure what it could be.

**Comment by gkedzierski** [comment]
Reinstalling everything completely from scratch (including getting rid of existing Cordova files) fixed the issue.
Worth closing the issue I guess, looks like a very specific problem with old dependencies I had.
