### ISSUE TITLE
ionic resources not completing

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic-cli#734]
Hey there,

In one Ionic project the `ionic resources` command is working perfectly, but in another all it does is this:

    Ionic icon and splash screen resources generator
     uploading android/icon.png...
     uploading ios/icon.png...
     uploading splash.png...
    splash.png (2208x2208) upload complete

And then stops. It doesn't complete the cropping process at all. How come?

**Comment by xvilo** [comment]
I have this exact same problem. When I tried `ionic resources --icon` that worked, but when I do `ionic resources --splash` if have this:
```
$ ionic resources --splash --verbose
Ionic splash screen resources generator
uploading splash.psd.
$
```

**Comment by sean-hill** [comment]
Hey @xvilo I ended up running my images through [imageoptim.com](https://imageoptim.com) and that fixed my issue. :mindblown:

**Comment by xvilo** [comment]
Ah, I just fixed it by saving the `.PSD` file as a `.PNG` file. Maybe there was something weird in the file that ionic resources can't handle

**Comment by jgw96** [comment]
Hello! I am going to be closing this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1166. Thanks for using Ionic!
