### ISSUE TITLE
Ionic 1.7  install error 

### ISSUE THREAD

**Issue by AndroX1** [driftyco/ionic-cli#735]
Said@HackerX MINGW32 /
$ npm install -g ionic
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 93.184.216.34:8080
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! path C:\Program Files (x86)\Git\npm-debug.log.93f1d0e25a5c6f03db8521516a6c3e1c
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Program Files (x86)\Git\npm-debug.log.93f1d0e25a5c6f03db8521516a6c3e1c'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Program Files (x86)\Git\npm-debug.log.93f1d0e25a5c6f03db8521516a6c3e1c']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Program Files (x86)\\Git\\npm-debug.log.93f1d0e25a5c6f03db8521516a6c3e1c' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\Git\npm-debug.log

**Comment by tlancina** [comment]
Hey there, thanks for the issue.
```
This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'
```

Going to close as not an Ionic CLI issue, but feel free to comment on here if you believe otherwise, thanks!

**Comment by kuzun9x** [comment]
You need set proxy as null:
`npm config proxy set null`
