### ISSUE TITLE
ionic 1.7.14 fails to build

### ISSUE THREAD

**Issue by vivekimsit** [driftyco/ionic-cli#736]
Machine config:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```

`npm --version 2.0.0`
`cordova --version 6.0.0`

while running: `ionic build ios` the build fails with the following output:

Running command:

```
{PROJECT_PATH}/hooks/after_prepare/010_add_platform_class.js  {PROJECT_PATH}
add to body class: platform-ios
ERROR building one of the platforms: xcodebuild was not found. Please install version 6.0.0 or greater from App Store
You may not have the required environment or OS to build this project
Error: xcodebuild was not found. Please install version 6.0.0 or greater from App Store
```

**Comment by tlancina** [comment]
Hey there, you'll need to be on a Mac to build for iOS.  

Have a look at: https://forum.ionicframework.com/t/unable-to-publish-ionic-framework-app-for-ios-in-ubuntu-14-04/37523/ where there is some discussion on other options if you're on Ubuntu.

**Comment by josx** [comment]
i am trying to do a cross compiling for ios on linux.
Here some clues on the voyage -> [cross-compiling_for_ios_on_linux](http://docs.godotengine.org/en/latest/reference/cross-compiling_for_ios_on_linux.html)
