### ISSUE TITLE
bug: TypeScript errors with noImplicitAny:true tsconfig

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#742]
_From @lehresman on February 10, 2016 20:32_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I want to be pedantic about typing in my Ionic app, so I added "noImplicitAny":true to my tsconfig.json.  Works great, except there seems to be some typing issues with the Swiper widget.  I get this when trying to compile my TypeScript:

```
ERROR in [default] /Users/lehresman/Projects/gazelle-mobile/node_modules/ionic-framework/components/slides/swiper-widget.d.ts:8:2 
'update', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in [default] /Users/lehresman/Projects/gazelle-mobile/node_modules/ionic-framework/components/slides/swiper-widget.d.ts:9:2 
'slideNext', which lacks return-type annotation, implicitly has an 'any' return type.

ERROR in [default] /Users/lehresman/Projects/gazelle-mobile/node_modules/ionic-framework/components/slides/swiper-widget.d.ts:10:2 
'slidePrev', which lacks return-type annotation, implicitly has an 'any' return type.
```

When I edit `swiper-widget.d.ts` and add `:any` to all the function declarations, it works fine.  But I suspect that's not the actual solution and figured I should report it.</span>

I'm running `2.0.0-beta.0`.

_Copied from original issue: driftyco/ionic#5396_

**Comment by tlancina** [comment]
Thanks for the issue! This is actually a framework issue that got migrated over to the CLI, so I'm going to track it there.
