### ISSUE TITLE
Typescript generators

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#753]
_From @mhartington on January 18, 2016 21:23_

_From @tlancina on January 8, 2016 1:32_

Right now the generated components are not typed.  Also might be nice for the tooling to differentiate between Typescript and ES6 projects (separate issue). 

_Copied from original issue: driftyco/ionic2#892_

_Copied from original issue: driftyco/ionic#5019_

**Comment by adamdbradley** [comment]
_From @lordgreg on January 26, 2016 21:31_

+1

**Comment by adamdbradley** [comment]
_From @Peekmo on January 26, 2016 21:35_

Hello,

I'll like it a lot (as it is already possible to `start` a projet with `--ts`)

Regards,
Peekmo

**Comment by cmellinas** [comment]
Yea it would be a nice feature, +1 as typescript should become the default in the future 
I will open an other issue for this generator concerning a way to chose a 'parent' directory

**Comment by davidsidlinger** [comment]
As we're working entirely in TypeScript, I would love to have this feature. The generated JS is _close_, but it is a pain to tweak it every time something is added.

**Comment by Heshyo** [comment]
It indeed makes sense that if you create a new project with `--ts`, the rest of the commands would match. That's what I did and I wondered why my service was `.js`, then I removed the files, called the command again with `--ts` and I wondered why I still got a `.js`.

**Comment by susanlinsfu** [comment]
This would be a very useful feature. Suck having to change extensions and covert every time something is created.

**Comment by williantenfen** [comment]
+1

**Comment by tlancina** [comment]
This is done in beta.24 of the CLI when using beta.4 of the framework.
