### ISSUE TITLE
Ionic 2 device simulator es6-shim.map missing

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#754]
_From @alecook on January 13, 2016 22:53_

Went through steps to create the "cutePuppyPics" starter app via the tutorial. Runs fine on the web but when trying to run on the ios simulator I get the following error (via safari debugging)

```
/Library/Developer/CoreSimulator/Devices/CED171AA-E5B2-4446-A931-8DEF68381866/data/Containers/Bundle/Application/D6FF91C4-1264-4424-B1E2-EDD6E05BC2D3/V2%20Test.app/www/build/js/es6-shim.map

Failed to load resource: The requested URL was not found on this server.
```

System Info:
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.7
Gulp local:   Local version undefined
Ionic Version: 2.0.0-alpha.49
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.3.0
Xcode version: Xcode 7.2 Build version 7C68

_Copied from original issue: driftyco/ionic#4952_

**Comment by adamdbradley** [comment]
_From @brandyscarney on February 4, 2016 15:44_

If you update the CLI to the latest beta version `npm install -g ionic@beta` does this error still happen?

**Comment by adamdbradley** [comment]
_From @alecook on February 5, 2016 17:34_

@brandyscarney I've updated my CLI to 2.0.0-beta.17

Still getting that error.

```
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.8.7
Gulp local:   Local version undefined
Ionic Version: 2.0.0-alpha.51
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.5.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

**Comment by adamdbradley** [comment]
_From @prateekjain on February 11, 2016 8:31_

Facing the same error

`

> Your system information:
> 
> Cordova CLI: 4.3.1
> Gulp version:  CLI version 3.9.0
> Gulp local:  
> Ionic Version: 2.0.0-alpha.57
> Ionic CLI Version: 2.0.0-beta.17
> Ionic App Lib Version: 2.0.0-beta.8
> ios-deploy version: 1.8.4 
> ios-sim version: 5.0.6 
> OS: Mac OS X El Capitan
> Node Version: v0.12.7
> Xcode version: Xcode 7.2 Build version 7C68

 `

**Comment by adamdbradley** [comment]
_From @benshope on February 11, 2016 9:17_

Same error: 

```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 0.4.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-alpha.55
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2.1 Build version 7C1002 
```
The app shows up, but it won't navigate between tabs.  Also, attempting to navigate between tabs does not make more console errors show up.

**Comment by ramoncarreras** [comment]
Same error here.

> Your system information:

> Cordova CLI: 6.0.0
> Gulp version:  CLI version 1.2.0
> Gulp local:   Local version 3.9.1
> Ionic Version: 2.0.0-alpha.57
> Ionic CLI Version: 2.0.0-beta.17
> Ionic App Lib Version: 2.0.0-beta.8
> ios-deploy version: 1.8.5 
> ios-sim version: 5.0.6 
> OS: Mac OS X El Capitan
> Node Version: v4.2.6
> Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by ZiFFeL1992** [comment]
Same here, but only on iOS devices/simulator.

```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-beta.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by benshope** [comment]
Probably another instance of this issue https://github.com/driftyco/ionic/issues/5601

**Comment by tlancina** [comment]
Just to reassure everyone, this doesn't break anything, it's just Safari failing to find the sourcemap for es-shim.js, not sure why it only happens on Safari.

**Comment by benshope** [comment]
@tlancina I realize that error message is unimportant - but the reason I saw that error message (and possibly the reason others saw it) was because the Tabs in my Ionic 2 app were working in Chrome but not in the iOS simulator - so I opened Safari to debug the simulator.

I also opened a fresh copy of the Ionic 2 Tabs starter app and attempted to run that in the simulator to see if there was just a problem with my build.  The fresh Ionic 2 Tabs starter only worked in Chrome also.

You guys probably have a handle on it, but I wanted to give some context.

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by jorge13300** [comment]
Hi, I have the same issue with ionic beta 11, works fine in android but not in IOs and safari

**Comment by drsandor** [comment]
Hello all! I found the solution. In the node_modules/ionic-gulp-scripts-copy/index.js file modify the defaultSrc variable to this:
```javascript 
var defaultSrc = [
  'node_modules/es6-shim/es6-shim.min.js',
  'node_modules/es6-shim/es6-shim.map',
  'node_modules/zone.js/dist/zone.js',
  'node_modules/reflect-metadata/Reflect.js',
  'node_modules/reflect-metadata/Reflect.js.map'
];
```

**Comment by jorge13300** [comment]
@drsandor thank's man!!, your fix work like a charm!!!
