### ISSUE TITLE
TypeScript 1.8.0 errors in starters

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#755]
_From @tlancina on February 4, 2016 1:5_

From https://github.com/driftyco/ionic/issues/5264, upgrading to TypeScript 1.8.0 breaks non TS starters because of https://github.com/Microsoft/TypeScript/issues/6766.

Looks like this has been fixed in TypeScript nightly, but will leave this open for reference until it's been resolved.

_Copied from original issue: driftyco/ionic#5327_

**Comment by tlancina** [comment]
Non issue as we've moved to Babel for the JS starters.
