### ISSUE TITLE
(v2) ionic serve doesn't detect changes in vagrant host

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#759]
_From @cxcxcxcx on January 27, 2016 8:32_

(This is for ionic v2)

I'm running ionic serve within a vagrant VM, and found that although it detects changes within the VM, but changes from the host wouldn't be respected.

On the other gulp watch works fine for my old projects.

Searching around this seems to be webpack problem, which has been resolved bug polling may need to be enabled separately: https://github.com/webpack/webpack/issues/125

Is there an easy way to enable polling for the watching for ionic serve v2?

Thanks!

_Copied from original issue: driftyco/ionic#5210_

**Comment by adamdbradley** [comment]
_From @tomsun on January 28, 2016 16:15_

Same issue when running `ionic serve` in a Docker container via [Docker Toolbox](https://www.docker.com/products/docker-toolbox) on OS X

...for the same reason: In both scenarios VirtualBox's "Shared Folders" feature tends to be a part of the workflow (Edit files in the GUI on the host OS, run Node in the VM), which is why the file events do not propagate: https://www.virtualbox.org/ticket/10660

**Comment by adamdbradley** [comment]
_From @cxcxcxcx on January 29, 2016 8:31_

The thread suggested enable --watch-poll for the webpack dev server. Not sure if there would be an equivalent for ionic serve? Thanks!

**Comment by tlancina** [comment]
Yes, we should expose watch options for `ionic serve`.  Although if the only real one is to use polling, perhaps just supporting `--watch-poll` as a flag for `ionic serve` would be enough.

**Comment by tomsun** [comment]
Gave this a shot: https://github.com/driftyco/ionic-app-lib/issues/73

Seems to detect js updates, but not html or sass

( Also added an entry to the --help menu over here: https://github.com/tomsun/ionic-cli/commit/e640f4cc786ffc50162df4f4d78c40012c9f811b )

**Comment by torch2424** [comment]
@tlancina is correct, this is due to vagrant's NFS filesystem syncing. I seem to have gotten this working by adding options to the gulp task in the meantime for HTML, and CSS. For browserify/watchify, polling works as well, but takes ~2mins to build :p going to try @tomsun solution now....

Also, here's the relevant pieces of my gulpfile.js:

````javascript
//Going to use polling for gulp watch because synced folders don't emit filesystem changes
//Gulp: https://github.com/floatdrop/gulp-watch/issues/213
//Browserify: http://stackoverflow.com/questions/27619248/watchify-update-event-never-fires-in-virtualbox
var watchInterval = 1000;
var watchOptions = {
	usePolling: true,
	interval: watchInterval
};

// Task to watch app folder for changes to semi e-build the app
gulp.task('watch', ['clean'], function(done) {
	runSequence(
		['sass', 'html', 'fonts', 'scripts'],
		function() {
			gulpWatch('app/**/*.scss', watchOptions, function() {
				gulp.start('sass');
			});
			gulpWatch('app/**/*.html', watchOptions, function() {
				gulp.start('html');
			});
			buildBrowserify({
				watch: true,
				watchifyOptions: {
					poll: true,
					interval: watchInterval
				},
			}).on('end', done);
		}
	);
});
````

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
