### ISSUE TITLE
Ionic resources

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#760]
_From @nbeydoon on February 9, 2016 14:47_

Hi, when I run `ionic resources` the command failed without any error and after retrying 10 times it works ...

_Copied from original issue: driftyco/ionic#5376_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! I will be closing this issue as a duplicate of https://github.com/driftyco/ionic-cli/issues/1166. Thanks!
