### ISSUE TITLE
Ionic 2 beta: Sass output is not minified

### ISSUE THREAD

**Issue by rjv** [driftyco/ionic-cli#761]
I was looking for a way to minify the CSS after the Sass is processed and I'm not finding a very obvious way to do this. As I understand it, the Sass handling was made more opaque (by being embedded into the CLI) in v2 to alleviate installation issues. Is there a way to hook into the Sass compilation process and perform other actions (such as make use of PostCSS modules)? With older versions I could just modify the gulpfile directly.

**Comment by tlancina** [comment]
Yes, at the moment there is no good way to do this, but it is something we need to think about and either give solid reasons for leaving it unconfigurable or expose some way to hook into the Sass compilation.
 
In the meantime, here is a gulpfile that essentially replicates what the CLI is doing: https://gist.github.com/tlancina/60893a5ef3a69669aa2f.

**Comment by jimitndiaye** [comment]
Why not just add it to the webpack loader pipeline then import the scss from the app?

**Comment by ramonornela** [comment]
@jimitndiaye beta.12 has used webpack closes issue @tlancina ;)

**Comment by tlancina** [comment]
Going to close, as this is handled by https://github.com/driftyco/ionic-app-scripts now.
