### ISSUE TITLE
cordova  build android  failed

### ISSUE THREAD

**Issue by freddy7mail** [driftyco/ionic-cli#762]
Hello anybody help please....I have facing this trouble...Thanks in advance.....

c:\yapp>cordova build android
ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_45
Download https://repo1.maven.org/maven2/com/android/databinding/compilerCommon/1.0-rc5/compilerCommon-1.0-rc5.ja
r
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-gradle/5.2.1/proguard-gradle-5.2.1.jar
Download https://repo1.maven.org/maven2/org/jacoco/org.jacoco.core/0.7.4.201502262128/org.jacoco.core-0.7.4.2015
02262128.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-model/1.5.0/builder-model-1.5.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/builder-test-api/1.5.0/builder-test-api-1.5.0.ja
r
Download https://repo1.maven.org/maven2/com/android/tools/sdklib/24.5.0/sdklib-24.5.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/sdk-common/24.5.0/sdk-common-24.5.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/common/24.5.0/common-24.5.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/build/manifest-merger/24.5.0/manifest-merger-24.5.0.ja
r
Download https://repo1.maven.org/maven2/com/android/tools/ddms/ddmlib/24.5.0/ddmlib-24.5.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/jack/jack-api/0.9.0/jack-api-0.9.0.jar
Download https://repo1.maven.org/maven2/com/android/tools/jill/jill-api/0.9.0/jill-api-0.9.0.jar
Download https://repo1.maven.org/maven2/com/squareup/javawriter/2.5.0/javawriter-2.5.0.jar
Download https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.48/bcpkix-jdk15on-1.48.jar
Download https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.48/bcprov-jdk15on-1.48.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar
Download https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
Download https://repo1.maven.org/maven2/org/antlr/antlr/3.5.2/antlr-3.5.2.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-checks/24.5.0/lint-checks-24.5.0.jar
Download https://repo1.maven.org/maven2/org/eclipse/jdt/core/compiler/ecj/4.4.2/ecj-4.4.2.jar
Download https://repo1.maven.org/maven2/com/android/tools/annotations/24.5.0/annotations-24.5.0.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/17.0/guava-17.0.jar
Download https://repo1.maven.org/maven2/com/android/databinding/baseLibrary/1.0-rc5/baseLibrary-1.0-rc5.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
Download https://repo1.maven.org/maven2/com/tunnelvisionlabs/antlr4/4.5/antlr4-4.5.jar
Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://repo1.maven.org/maven2/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchard
et-1.0.3.jar
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-base/5.2.1/proguard-base-5.2.1.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar
Download https://repo1.maven.org/maven2/com/android/tools/layoutlib/layoutlib-api/24.5.0/layoutlib-api-24.5.0.ja
r
Download https://repo1.maven.org/maven2/com/android/tools/dvlib/24.5.0/dvlib-24.5.0.jar
Download https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1.1/httpclient-4.1.1.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpmime/4.1/httpmime-4.1.jar
Download https://repo1.maven.org/maven2/net/sf/kxml/kxml2/2.3.0/kxml2-2.3.0.jar
Download https://repo1.maven.org/maven2/org/antlr/ST4/4.0.8/ST4-4.0.8.jar
Download https://repo1.maven.org/maven2/com/android/tools/lint/lint-api/24.5.0/lint-api-24.5.0.jar
Download https://repo1.maven.org/maven2/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar
Download https://repo1.maven.org/maven2/com/tunnelvisionlabs/antlr4-runtime/4.5/antlr4-runtime-4.5.jar
Download https://repo1.maven.org/maven2/com/tunnelvisionlabs/antlr4-annotations/4.5/antlr4-annotations-4.5.jar
Download https://repo1.maven.org/maven2/com/intellij/annotations/12.0/annotations-12.0.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar
Download https://repo1.maven.org/maven2/com/android/tools/external/lombok/lombok-ast/0.2.3/lombok-ast-0.2.3.jar
Download https://repo1.maven.org/maven2/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayou
t.core-1.0.1.jar
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFoldersThe message received from the daemon indicates that the daemon has disappeare
d.
Build request sent: Build{id=c6d23e2d-d777-4727-80c8-bdef9641b833.1, currentDir=c:\yapp}
Attempting to read last messages from the daemon log...
Daemon pid: 3516
  log file: C:\Users\MANOJ M\.gradle\daemon\2.2.1\daemon-3516.out.log
----- Last  20 lines from daemon log file - daemon-3516.out.log -----
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
----- End of the daemon log -----

FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
ERROR building one of the platforms: Error code 1 for command: cmd with args: /s,/c,"c:\yapp\platforms\android\g
radlew cdvBuildDebug -b c:\yapp\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedN
dk=true"
You may not have the required environment or OS to build this project
Error: Error code 1 for command: cmd with args: /s,/c,"c:\yapp\platforms\android\gradlew cdvBuildDebug -b c:\yap
p\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"

c:\yapp>javac -version
javac 1.7.0_45
c:\yapp>node --version
v5.6.0
c:\yapp>cordova -version
6.0.0
c:\yapp>adb version
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android

**Comment by tlancina** [comment]
Hey going to close this as it looks like it's a cordova issue and not an Ionic one, feel free to comment if that's not the case.
