### ISSUE TITLE
Missing plist in ionic-cli 1.7.14

### ISSUE THREAD

**Issue by mohamed-ahmed** [driftyco/ionic-cli#763]
Running command `ionic platform add ios`

returns the error

```
Updated the hooks directory to have execute permissions
Adding ios project...
iOS project created with cordova-ios@4.0.1
Running command: /Users/ma/repos/ionic-spauted/hooks/after_prepare/010_add_platform_class.js /Users/ma/repos/ionic-proj
add to body class: platform-ios
Error: Cannot find module 'plist'
```

**Comment by mohamed-ahmed** [comment]
`npm install` and removing and adding the platform didn't work.

@mhartington Any thoughts on this?

**Comment by mohamed-ahmed** [comment]
After trying to install the iOS platform I notice that its installing cordova-ios version 4.0.1, but a fresh sample project ionic project installs version 3.8.0 which I believe to be the latest supported version. Is there a reason its consistently installing the wrong version? Might that be causing the `Cannot find module 'plist'` error?

**Comment by tlancina** [comment]
Hey @mohamed-ahmed I'm not sure, could you post the output of `ionic info` please?

**Comment by mohamed-ahmed** [comment]
I added `"plist": "^1.2.0",` to the package.json and ran `ionic platform add ios@3.8.0` to make sure it would install the correct version of cordova ios and then it worked. It was installing 4.0.1 by default. Still not sure what caused the problem but incase it helps anyone else, running ionic info gave me

```
$ ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.13
Ionic App Lib Version: 0.6.5
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by iBasit** [comment]
+1 (system window)

on mac it works fine.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
