### ISSUE TITLE
Generated TypeSCript pages have .js extension

### ISSUE THREAD

**Issue by jeffbcross** [driftyco/ionic-cli#766]
Ionic CLI version 2.0.0-beta.17

I generated a project, and then generated a page. The page contained TypeScript, but the extension was .js.

```
$ ionic start reports --v2 --ts
$ cd reports
$ ionic g page reports
```

Output: reports.js
```ts
import {Page, NavController} from 'ionic/ionic';

/*
  Generated class for the ReportsPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Page({
  templateUrl: 'build/pages/reports/reports.html',
})
export class ReportsPage {
  constructor(nav: NavController) {
    this.nav = nav;
  }
}

```

**Comment by tlancina** [comment]
Hey thanks for the issue. This is on our roadmap, I think in the short term with a `--ts` flag similar to start, and ultimately from project metadata that indicates if it's using TS or not.

For now, going to close as a dup of https://github.com/driftyco/ionic-cli/issues/753.
