### ISSUE TITLE
List command unavailable in v2 projects

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#767]
_From @leonsas on February 15, 2016 4:5_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

I started the project with `ionic start new-edge --v2 --ts --sass`

```
leonsas at leonsas in ~/projects/temp/new-edge> ionic list
This command can only be used when in an Ionic project directory
leonsas at leonsas in ~/projects/temp/new-edge> ionic info

Your system information:

Cordova CLI: 4.3.0
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic Version: 2.0.0-alpha.57
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.5.0
ios-sim version: 3.1.1
OS: Mac OS X El Capitan
Node Version: v0.12.1
Xcode version: Xcode 7.2 Build version 7C68
```

_Copied from original issue: driftyco/ionic#5455_

**Comment by tlancina** [comment]
Thanks for the issue! The `list` command is unsupported in v2 projects, but there should be a proper message stating this.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
