### ISSUE TITLE
Security Alert from Google Play Developer Console 

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#770]
_From @sydneyhenrard on February 14, 2016 22:12_

I get a security alert in the Google Play Developer Console:
Please migrate your app(s) to Apache Cordova v.4.1.1 or higher as soon as possible and increment the version number of the upgraded APK.

Where do I check which version of Cordova my application use?

```
vagrant@ionic-android:/project$ cordova platform
Installed platforms: android 4.1.1
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ubuntu, webos
```

To fix it, I guess I just have to upgrade cordova, and release a new apk, right?
```
vagrant@ionic-android:/project$ cordova -v
5.4.1
```

```
vagrant@ionic-android:/project$ ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.3 LTS
Node Version: v4.3.0
```

Thanks

_Copied from original issue: driftyco/ionic#5451_

**Comment by tlancina** [comment]
I think you should be fine, as your platform version for android is `4.1.1`, which is the minimum they ask for.

You are correct though, if you update the Cordova CLI, you can then run `cordova platform update android` to have it update the platform to a higher version and then re-release.

Going to close this, but feel free to comment if you are still having issues.  Also there is a post on the forum that might be helpful: https://forum.ionicframework.com/t/version-number-apache-cordova/43550.
