### ISSUE TITLE
No generator available

### ISSUE THREAD

**Issue by ZiFFeL1992** [driftyco/ionic-cli#771]
```
MacBook-Air:app guille$ ionic generate page About
✗ There is no generator available with the name page.
Available generators:
 * component
 * directive
 * page
 * pipe
 * provider
 * tabs
```

I can't generate any component, I always get that message.
Do I have to run the command from any specific path?

**Comment by tlancina** [comment]
Could you run `ionic info` and paste the output please?

**Comment by ZiFFeL1992** [comment]
```
Your system information:

Cordova CLI: 6.0.0
Ionic Version: 2.0.0-alpha.55
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 7.2.1 Build version 7C1002 


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly suggested to install/upgrade the following:     

 Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************
```

I solved the dependencies warning and still have the same issue.
Thanks.

**Comment by tlancina** [comment]
Thanks for the info, it's not immediately obvious to me what the problem could be.

If you run `ionic start test-app --v2` and then try and generate a page from `test-app` does it give you the same error? And if not, is there anything different about the structure of it compared to your app?

**Comment by ZiFFeL1992** [comment]
Don't ask me how, but webpack.config.js files where different...
I have copy the file from the test folder and re-download all node_modules, now everything works fine.

![captura de pantalla 2016-02-16 20 32 10](https://cloud.githubusercontent.com/assets/5492960/13088443/899e48a0-d4ec-11e5-8828-94de583e9fd5.png)

Thank you :smile:
