### ISSUE TITLE
V2 - ionic state restore no longer works

### ISSUE THREAD

**Issue by danbucholtz** [driftyco/ionic-cli#778]
I see the state function was removed from the CLI.  Forgive my ignorance - is there a way to get functionality similar to executing "ionic state restore" from v1 in v2?

Thanks,
Dan

**Comment by tomsun** [comment]
The `ionic state` command seem to be there in the help menu (Ionic CLI Version: 2.0.0-beta.19)

When trying to use `ionic state restore` with a v2 app though, I get:
```
You cannot run any state commands on a project that is not an Ionic project.
Try adding an ionic.project file or running ionic start to get an application to save or restore (CLI v2.0.0-beta.19)
```

I.e. no `ionic.project` file in my v2 app... My memory was a bit rusty on whether v1 has one - it does:
```
$ ionic start foo
...
$ ionic start --v2 bar
...
$ ls -al foo/ionic*
-rw-r--r-- 1 root root 36 Mar  2 21:27 foo/ionic.project
$ ls -al bar/ionic*
-rw-r--r-- 1 root root 1244 Mar  2 21:27 bar/ionic.config.js
$ cat foo/ionic.project 
{
  "name": "foo",
  "app_id": ""
}
```

Adding a v1-style `ionic.project` seems to do the trick for my v2 app.

Purpose: using `ionic state restore` in postinstall seems like a neat workflow:
http://stackoverflow.com/a/32417044

```
# ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-crosswalk-webview
cordova plugin add cordova-plugin-whitelist
cordova plugin add cordova-plugin-x-socialsharing
cordova plugin add cordova-sqlite-storage
cordova plugin add cordova-plugin-console
cordova plugin add twitter-connect-plugin --variable FABRIC_KEY="REDACTED" 
Restore plugins is complete

Ionic state restore completed
```

**Comment by tlancina** [comment]
@tomsun thanks for the workaround! Since Cordova has since implemented the same functionality we considered deprecating it, but I think the plan right now is to have the commands remain and use the Cordova commands under the hood to get the same functionality.  This will mean plugins will be saved to config.xml and not package.json eventually (although I believe Cordova has hinted that they may move to package.json at some point, so we'll see).

**Comment by ansaritameem** [comment]
I had a different workaround... I ensure that my cordova config.xml ALSO maintains the list of plugins & platforms (by using --save during add operations using the CLI) along side package.json. My post-install step in package.json is to invoke ionic prepare (which inturn just passes this down to the cordova cli) to setup the platform & plugin dependencies.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!

**Comment by pugwonk** [comment]
In case anyone else hits this, this command is now completely gone (Ionic/cli-utils@1.7.0).
