### ISSUE TITLE
Exception running ionic state restore --plugins

### ISSUE THREAD

**Issue by LennyThompson** [driftyco/ionic-cli#784]
cordova plugin add cordova-plugin-console
cordova plugin add cordova-plugin-device
 ? Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

From package.json:

  "cordovaPlugins": [
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-inappbrowser",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "cordova-plugin-whitelist",
    "ionic-plugin-keyboard"
  ],
  "cordovaPlatforms": [
    {
      "platform": "android",
      "locator": "browser"
    }

**Comment by LennyThompson** [comment]
Hi there - I found out the problem - it seems that copying code from example projects is not a great idea.

The package.json secttion

"cordovaPlatforms": [
{
"platform": "android",
"locator": "browser"
}]

is the cause of the problem, and replacing it with 

"cordovaPlatforms": [
"android"
}

allows the ionic state restore --plugins to work correctly. I guess its a bug though.

**Comment by tlancina** [comment]
Thanks for the issue! Was this code from one of our examples?

**Comment by LennyThompson** [comment]
Hithere,

It came from https://github.com/mappmechanic/ionic-firebase, and I dont
remember how I got to it 0 either from the firebase ionic examples or
searching for them.

Cheers
Lenny

**Comment by mehrad-rafigh** [comment]
I am having this issue as well. When I run ``ìonic state restore```the platforms are getting restored correctly, but it throws an exception when it reaches `cordova plugin add cordova-plugin-device`.
This is the error message:
`Restoring Plugins

cordova plugin add cordova-plugin-device
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues`
Via `npm ls -g --depth=0` I'll see that Cordova is installed on my Mac.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!

**Comment by lygstate** [comment]
Still have the issue
```
Restoring Plugins

cordova plugin add cordova-plugin-device
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

**Comment by javiercno** [comment]
Please update Java JDK 1.8

**Comment by supdann** [comment]
@mehrad-rafigh @lygstate 

Did you solve this Issue?
```
cordova plugin add cordova-plugin-device
Caught exception:
 undefined
```

**Comment by lygstate** [comment]
solved update to JDK8

**Comment by metal3d** [comment]
I still have the problem:

```
bash-4.2$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)

bash-4.2$ cordova -version
6.4.0

bash-4.2$ ionic -version
2.1.0


bash-4.2$ ionic state reset
Removed platforms and plugins
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues



```

**Comment by metal3d** [comment]
Ok, I found how to fix *my* issue, maybe it could be *yours*:

```
npm install
npm run ionic:build
# or "npm run build" on older versions
ionic state reset 
```

It seem that without "www" directory, cordova doesn't consider the current directory as a poject. Am I wrong ?

**Comment by vargaendre** [comment]
Hi 
I had this same issue. The fact is ionic state reset is swallowing the cause, so to find it out I ran cordova plugin add cordova-plugin-geolocation (which was failing for me) and then in the error message it was clear that I did not have the Android SDK and that broke the plugin add. After installing all necessary SDKs the thing works. 
Hope this helps somebody.

**Comment by pugwonk** [comment]
Had this myself - as vargaendre mentioned, ionic state reset is eating the error message. To find out what it was, run `cordova plugin add cordova-plugin-device` on its own. For me it was running out of memory (and switching to a 64-bit JVM fixed it).

**Comment by farhaan008** [comment]
I also have same issue.

ionic state restore gives this error

cordova plugin add cordova-plugin-whitelist
Caught exception:
undefined

**Comment by aanchal-agarwal** [comment]
@farhaan008 could you solve it?

**Comment by farhaan008** [comment]
yes anyhow i solved it. i created www directory then run the command ionic state restore

**Comment by farhaan008** [comment]
if ur prblm not solve let me knw. whats ur error

**Comment by sarbuandreidaniel** [comment]
Same issue here. I confirm that @metal3d solution is working. It seems that it needs the _www_ directory in order to run properly.

**Comment by Jacob-McKay** [comment]
I just had an automated build succeed, even though this occurred: 
```
Caught exception:
undefined
```

during ionic state restore

Which resulted in a deployment in which build/tests passed but native components would fail when the user used the app.  This is a bit of a big deal, as it happened randomly, and just re-running the same CI build fixed it.  Could we make ionic state restore complete with a failed status code in this case?  Maybe it already does, I'm on 2.2.1

@jgw96 you said we'll be doing something else in the future, are we there yet or is ionic state restore what we got for now?

**Comment by benftwc** [comment]
Hello there, I've get the same issue, and I can fix it by adding the missing `www` folder. 

Hope it helps,

Cheers

**Comment by rajatkhare619** [comment]
Running _sudo_ ionic state reset fixed it for me on Mac.
