### ISSUE TITLE
I have installed ionic2' CLI,now ionic serve does't work in a new ionic2 project

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#786]
_From @yangheng on February 19, 2016 2:24_

#### I have installed ionic2' CLI,now ionic serve does't work in a new ionic2 project

In ionic2 project, ionic serve does't work.while i try start a ionic1 project and cd &,ionic serve works !! What's matter ?

**Ionic Version**: 2.x

**Browser & Operating System**: Chrome

**Run `ionic info` from terminal/cmd prompt:**

```
Cordova CLI: 5.3.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002 

```

_Copied from original issue: driftyco/ionic#5521_

**Comment by tlancina** [comment]
When you say 'doesn't work' what do you mean? Are there any errors?

**Comment by yangheng** [comment]
No errors !  In ionic1 project ,the chrome browser will start and load index.html after type "ionic serve",however there's nothing in ionic2 project and no errors.
The terminal like this : 
```
root$ ionic serve
root$ 
```

**Comment by Luchillo** [comment]
Try cleaning up node and cordova and re-install the cli and the `node-modules`, here's my default alias for that:
```sh
type uionic 
uionic is aliased to `rm -rf node_modules www/build platforms && npm uninstall -g ionic && npm uninstall -g cordova && npm cache clean && npm i -g cordova ionic@beta && npm i'
```

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
