### ISSUE TITLE
triggering ionic livereload when showing a view that has history loses the back button

### ISSUE THREAD

**Issue by jtmarmon** [driftyco/ionic-cli#787]
There's a pretty good overview of the issue with the original one here https://github.com/driftyco/ionic/issues/3222

As @Ionitron says

>If the entire app is refresh, it'll no longer have a history of previous views, which is why the back button no longer shows.

So perhaps the best idea is a suggestion by @mtpultz

> useful feature would involve being able to set a config variable that resets to specific state on livereload. Depending on what you are trying to achieve when working through the application. Sometimes I'm just working on a single page and the loss of history doesn't matter, but in other cases this function defeats the purpose of livereload since I have to go and change the URL back to my base domain, or to a specific state.

Another suggestion would be to have a default "go to back" for each view in the case of a reload

**Comment by jthoms1** [comment]
This is an enhancement that we might visit in the future but not at this time. Thanks!
