### ISSUE TITLE
The request entry was not found in the cache - android run -lcs

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-cli#788]
_From @apavillet on February 20, 2016 18:11_

#### Short description of the problem:
When launching the app after doing ionic run android -lcs i'm getting 

"Application Error"
 The request entry was not found in the cache ( http:xxxxx <= local ionic url )
"
Clicking ok on the dialog closes the app
This is new the app was working fine until now, did anyone know what could cause this?

EDIT / Building the app and installing via adb works

#### What behavior are you expecting?

The app should be working ;)

**Ionic Version**: 1.2.4 / CLI is 1.7.14

**Browser & Operating System**: iOS / Android / Chrome
Android

**Run `ionic info` from terminal/cmd prompt:**

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4-nightly-1917
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.2 Build version 7C68 

_Copied from original issue: driftyco/ionic#5539_

**Comment by cwoolum** [comment]
Has anyone found a solution to this? I'm having the same issue. I tried Ionic CLI 1.5.4, 1.6.5, and 2.0.0 with the same result. Also.tried cordova 6.0.0 and 5.4.1

**Comment by cjy37** [comment]
+1

**Comment by allanpoppe** [comment]
+1

**Comment by Rakonda** [comment]
+1

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.

**Comment by pavillet** [comment]
@jthoms1 You can it's an old one :) Thanks

**Comment by aneeshatgit** [comment]
Where is this fixed (which component, version)?
