### ISSUE TITLE
bug v2: "ionic run --livereload browser" is ignoring the platform

### ISSUE THREAD

**Issue by sebastianovide** [driftyco/ionic-cli#789]
- ionic info
```
Cordova CLI: 6.0.0
Ionic Version: 2.0.0-alpha.57
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

- to **reproduce** run `ionic run --livereload browser`

- **expected**: it should run on a browser with livereload enabled

- **instead**: it is run in all the platforms and **no** livereload enabled. It is necessary to stop it (ctrl+C) and re run it after every change

- console:

```
ionic run --livereload browser
...
...
...
** BUILD SUCCEEDED **

No target specified for emulator. Deploying to iPhone-6s-Plus, 9.2 simulator
io.ionic.starter: 18507
```

**Comment by sebastianovide** [comment]
running `ionic run browser --livereload` (see --livereload **after** browser) it runs on the platform browser as expected. So the bug is about the --help being misleading. Infact `run [options] <PLATFORM> ......................  Run an Ionic project on a connected device` should be `run <PLATFORM> [options] ......................  Run an Ionic project on a connected device`

I'm splitting this in two tickets. The new ticket reports only the not being livereload: https://github.com/driftyco/ionic-cli/issues/790

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
