### ISSUE TITLE
bug v2: "ionic run browser --livereload" is not refreshing the app after changes

### ISSUE THREAD

**Issue by sebastianovide** [driftyco/ionic-cli#790]
- to reproduce
  - run `ionic run browser --livereload`
  - modify a html or ts file
- expected
  - the app should change. Refreshing the browser you should see the changes
- instead
  - the console shows that the file changes is being copied by the changes are not reflected in the app. It is still necessary to ctrl+c and restart it
- **workaround**: after the change, wait until when the console shows the file changed and then `rsync -rtv www/ platforms/browser/www` or run another file watcher: `fswatch -r www/ | xargs  -I % rsync -rtv www/ platforms/browser/www`

**Comment by blakeface** [comment]
+1.
Also, I've double-checked my ionic address. This feature was functioning earlier, but has unexpectedly stopped. Any feedback?

**Comment by hersonls** [comment]
+1

**Comment by hersonls** [comment]
+1
I don't know about ionic-cli, but reading the [code](https://github.com/driftyco/ionic-cli/blob/v2/lib/utils/cordova.js#L215) of setupLiveReload the baseDir are the project baseDir and the serving dir by platform browser live inside the platform. To this case need to create a conditional for browser platform.

And I saw another alternative reading the run command from platform which have hardcoded localhost to run in the browser.

```javascript
 server.servePlatform('browser', {port: args.port, noServerInfo: true}).then(function () {
        var projectUrl = url.resolve('http://localhost:' + server.port + '/', sourceFile ? sourceFile[1] : 'index.html');
        console.log('Static file server running @ ' + projectUrl + '\nCTRL + C to shut down');
        return cordovaServe.launchBrowser({target: args.target, url: projectUrl});
    }).catch(function (error) {
        console.log(error.message || error.toString());
        if (server.server) {
            server.server.close();
        }
    });
```

In this case I believe the solution is set as a variable reading config.xml file or passing through args.

Please Correct me if I'm wrong.

**Comment by metal3d** [comment]
Exactly the same with new version

**Comment by jthoms1** [comment]
Please install the latest ionic cli. ionic@2.1.12.  This has incorporated the test tag branch. Thanks for your patience.  If you are still having issues please let me know!

`npm uninstall -g ionic`
`npm install -g ionic@latest`

**Comment by gino8080** [comment]
update to ionic@latest but same issue, browser does not reload

Your system information:

Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.14
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.9.0
ios-sim version: 5.0.12
OS: OS X El Capitan
Node Version: v6.6.0
Xcode version: Xcode 7.2 Build version 7C46t

**Comment by stovmascript** [comment]
I'm having an issue with the project failing to build after making a change in `src/`.

When I run `ionic run browser --livereload`, it builds fine and opens Chrome etc., but after making a change in a html/scss/ts file, it fails like this:

```
[14:49:06]  build started ... 
(node:39480) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'send' of undefined
[14:51:37]  build started ... 
(node:39480) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'send' of undefined
[14:51:43]  build started ... 
(node:39480) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'send' of undefined
```

```
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by zixia** [comment]
I ran into this issue today with ionic CLI 2.2.1

```shell
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by TTHledieu** [comment]
Same issue than @zixia

**Comment by imarcelolz** [comment]
Same issue on ubuntu 16.04:

Cordova CLI: 6.5.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.4.0
Xcode version: Not installed

**Comment by edwardrf** [comment]
Same issue on ubuntu 16.04.1 LTS (in docker see below for details):

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.3
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.8.0
Node Version: v7.6.0
Xcode version: Not installed


Using docker image mkaag/ionic, with docker-compose config:

```
    image: beevelop/ionic
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - ../:/myApp
      - ./google-chrome:/usr/local/bin/google-chrome
    working_dir: /myApp
    stdin_open: true
    tty: true
    command: ionic run browser --livereload 
```

google-chome is an empty bash script as placeholder when ionic tries to run chrome it will not exit with an error.

**Comment by zixia** [comment]
@jthoms1 I believe we should re-open this issue because it seems this bug still exist in the latest version of the code.

**Comment by shamank** [comment]
It's working as expected in cli 2.2.1 (just updated because I was having this issue in 2.1.0)

**Comment by shamank** [comment]
Nope... sorry. It worked well for the first hour and here is the issue again :-1:

**Comment by sebastianovide** [comment]
@jthoms1 , as this is still reproducible, could you reopen it ?

**Comment by sebastianovide** [comment]
actually I've just seen that somebody else has reported it in https://github.com/driftyco/ionic-cli/issues/1998

**Comment by mfreirehfexp** [comment]
Having the same issue. Mostly with templates update

**Comment by lngr** [comment]
Having the same issue as described an reported by others here.

**Comment by lcofresi** [comment]
Having the same issue ('ionic run browser --livereload' not reloading on template change):

Cordova CLI: 7.0.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.10
Node Version: v6.10.2
Xcode version: Not installed

Please, fix this problem, as it severely impedes fast prototyping.

**Comment by olegwn** [comment]
Same issue here :( Not only it does not update the source files, it does not live reload browser as well.

**Comment by sebastianovide** [comment]
Workaround: 
   `./node_modules/.bin/ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build`

**Comment by CliffyMk** [comment]
can you please explain this workaround. @sebastianovide

**Comment by wichanan** [comment]
From @sebastianovide answer

`Workaround:
./node_modules/.bin/ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build`

He force the ionic app script to serve and build the `www` from `./platform/browser` instead of serving from `./www` folder

for the shorter command, you can edit the `package.json` in the `scripts` key like this:

```
"scripts": {
    "build": "ionic-app-scripts build",
    "clean": "ionic-app-scripts clean",
    ...
    "browser": "ionic-app-scripts serve --sourceMap source-map --iscordovaserve --wwwDir platforms/browser/www/ --buildDir platforms/browser/www/build"
},
```

and then on the terminal, you just need to run 
`npm run browser`

now you got the browser version of your app that compatible with `cordova`

**Comment by tscislo** [comment]
Same here

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : browser 4.1.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Linux 4.4
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by airstep** [comment]
So, I solved it in such way:

`cp node_modules/@ionic/app-scripts/configs/watch.config.js {{root_project}}/scripts`

Edit:

```
var watch = require('../node_modules/@ionic/app-scripts/dist/watch');
module.exports = {
  srcFiles: {
    paths: ['{{SRC}}/**/*.(ts|html|s(c|a)ss)'],
    options: { ignored: ['{{SRC}}/**/*.spec.ts', '{{SRC}}/**/*.e2e.ts', '**/*.DS_Store', '{{SRC}}/index.html'] },
    callback: watch.buildUpdate
  }
};

```

Then, add such line to package.json:

`    "config": {
        "ionic_watch": "./scripts/watch.config.js"
    },`

And try it, works for me (tested few minutes now - but it doesn't work about half day ;)

**Comment by yxliang01** [comment]
I confirm that @wichanan 's solution worked perfectly for me.

**Comment by nikhilrane1992** [comment]
Same here 
```
cli packages: (/home/nikhil/.nvm/versions/node/v8.5.0/lib/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 26.1.1
    Node              : v8.5.0
    npm               : 5.3.0 
    OS                : Linux 4.10

Misc:

    backend : pro
```

**Comment by gabriellacerda** [comment]
@sebastianovide Workaround worked like a charm, thanks!

**Comment by dwieeb** [comment]
That workaround will only work for live-reload servers that write to disk (`@ionic/app-scripts`, but _not_ the Angular CLI). So, unfortunately, the workaround or a similar workaround won't work for Ionic Angular 4, which embraces the Angular CLI. 

Please see this feature request for proper support for live-reload with the Cordova browser platform: https://github.com/ionic-team/ionic-cli/issues/3043

**Comment by dwieeb** [comment]
I suppose one could use `ng build --watch`, however.

**Comment by gbbarroso** [comment]
Solution isn't working for me, as I get an error (by the ionic push plugin), which does not happen when running `ionic cordova platform browser`
