### ISSUE TITLE
Generated page has an incorrect import [v2]

### ISSUE THREAD

**Issue by maxx0r** [driftyco/ionic-cli#791]
I was getting started with the beta, but quickly I ran into an issue with the generator (which is a great idea :) ).

The ionic import is incorrect. It generates imports in the page from ionic/ionic, but that doesn't work. When I changed it to ionic-framework/ionic (got a cue from the starter), it does work.

**Comment by tlancina** [comment]
Thanks for the issue! We're going to be changing the import/package name at the next release, so I've updated the generators in https://github.com/driftyco/ionic/commit/1495a1353eb7a2501db955c52d9b4be5ba2c9bd6.
