### ISSUE TITLE
how to contribute ionic-cli as a cli developer ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [driftyco/ionic-cli#795]
Hi ! @mlynch and all ionic team 
 
      how to contribute ionic-cli as a cli developer ? 
      where are the docs for the same?
      How to debug at local system ?
      I am getting error , System Architecture node support 
please tell me any body. I love ionic framework.

**Comment by jgw96** [comment]
Hey! Thanks for wanting to contribute, thats awesome! Sorry that we have not gotten back to you until now. I would recommend going to our forum (forum.ionicframework.com) and asking on there. There are a ton of awesome dev's on there that can help you.

**Comment by DILEEP-YADAV** [comment]
sure!  Awesome tool for Cordova project  , still I am working another task , That's why .
