### ISSUE TITLE
ios version with new Ionic project is not the latest

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-cli#796]
I'm using the v2 beta of the Ionic CLI.

I made a new project and it auto added the ios platform, but at version 3.8.0. If I immediately rm and then add ios, I get 4.0.1.

**Comment by tlancina** [comment]
Thanks for the issue, the start command uses the Cordova node API to install the default platform, and it looks like our version is out of date.

**Comment by tlancina** [comment]
Looks like this is a dup of https://github.com/driftyco/ionic-cli/issues/725, going to close.
