### ISSUE TITLE
beta install failing

### ISSUE THREAD

**Issue by fhdk** [driftyco/ionic-cli#797]
**$ sudo npm install -g ionic@beta**

npm-debug log atttached
[npm-debug.log.txt](https://github.com/driftyco/ionic-cli/files/152295/npm-debug.log.txt)

**Comment by tlancina** [comment]
Thanks for the issue, not sure why it's failing as the error seems pretty generic.  If you cd to `/usr/lib/node_modules/ionic` and run `node lib/tasks/postinstall` does it error for you?

**Comment by fhdk** [comment]
Since the install fails everything is rolled back so the lib/tasks/postinstall does not exist

Then cloned the repo.
Switched to v2-beta branch.
Edited package.json to omit postinstall.

Run install with

    $ sudo npm install -g

No errors during install

Manually running the tasks from postinstall.js emits no errors

    $ npm rebuild node-sass spawn-sync

    $ uname -r
    4.4.1-2-ARCH

I suspect fsevents to be the culprit since this is only OSX relevant

>cmd += process.platform === 'darwin' ? ' fsevents' : '';

**Comment by zhouhao27** [comment]
But the version for v2-beta is 2 beta 17.

**Comment by fhdk** [comment]
Can't say why - we're only human - lots of things can go wrong

**Comment by sclausen** [comment]
@fhdk that's not what @zhouhao27 meant. Everything you did was working, because you worked with the old ionic version. beta 18 is not working and what you tried uses the old, working, beta 17.

**Comment by tlancina** [comment]
Yeah just got a working repro thanks to @brandyscarney, I use nvm so I wasn't seeing it because I don't use sudo.

@fhdk looks like you're correct in that the postinstall process doesn't have the permissions to rebuild the modules it's trying to.  Only thing I'm curious about is, why wasn't this happening to people on beta.17? There's still something fishy here.

**Comment by tlancina** [comment]
So there is some weirdness with using bundledDependencies and publishing with flat npm3 module structure.

I've republished beta.18 with npm2 module structure as beta.19, which seems to make the permission errors go away, but I think this highlights the need for some cleanup of the dependencies between ionic-cli and ionic-app-lib (e.g. why is npm a dependency?).

Could you guys try beta.19 and let me know if it's still erroring please? Thanks!

**Comment by fhdk** [comment]
Hi - thanks for the checkup.

@tlancina I still get permission errors - this time a bit different - so youre right, something is fishy.
When I exec the install with sudo a .npm folder is created at /root/ with fh:users.

    [fh:/home/fh] $ ls -la /root
    totalt 44
    drwxr-xr-x  7 root root  4096  1 mar 20:14 .
    drwxr-xr-x 17 root root  4096 18 feb 13:40 ..
    -- listing cut for brevity
    drwxr-xr-x  5 fh   users 4096  1 mar 20:14 .npm

    [fh:/home/fh] $ ls -la -R /root/.npm
    /root/.npm:
    totalt 20
    drwxr-xr-x 5 fh   users 4096  1 mar 20:14 .
    drwxr-xr-x 7 root root  4096  1 mar 20:14 ..
    drwxr-xr-x 3 fh   users 4096  1 mar 20:14 ionic
    drwxr-xr-x 2 fh   users 4096  1 mar 20:15 _locks
    drwxr-xr-x 3 fh   users 4096  1 mar 20:14 registry.npmjs.org
    
    /root/.npm/ionic:
    totalt 12
    drwxr-xr-x 3 fh users 4096  1 mar 20:14 .
    drwxr-xr-x 5 fh users 4096  1 mar 20:14 ..
    drwxr-xr-x 3 fh users 4096  1 mar 20:14 2.0.0-beta.19
    
    /root/.npm/ionic/2.0.0-beta.19:
    totalt 34888
    drwxr-xr-x 3 fh users     4096  1 mar 20:14 .
    drwxr-xr-x 3 fh users     4096  1 mar 20:14 ..
    drwxr-xr-x 2 fh users     4096  1 mar 20:14 package
    -rw-r--r-- 1 fh users 35709146  1 mar 20:14 package.tgz

    /root/.npm/ionic/2.0.0-beta.19/package:
    totalt 12
    drwxr-xr-x 2 fh users 4096  1 mar 20:14 .
    drwxr-xr-x 3 fh users 4096  1 mar 20:14 ..
    -rw-r--r-- 1 fh users 3270  1 mar 20:14 package.json

    /root/.npm/_locks:
    totalt 8
    drwxr-xr-x 2 fh users 4096  1 mar 20:15 .
    drwxr-xr-x 5 fh users 4096  1 mar 20:14 ..

    /root/.npm/registry.npmjs.org:
    totalt 12
    drwxr-xr-x 3 fh users 4096  1 mar 20:14 .
    drwxr-xr-x 5 fh users 4096  1 mar 20:14 ..
    drwxr-xr-x 2 fh users 4096  1 mar 20:14 ionic

    /root/.npm/registry.npmjs.org/ionic:
    totalt 668
    drwxr-xr-x 2 fh users   4096  1 mar 20:14 .
    drwxr-xr-x 3 fh users   4096  1 mar 20:14 ..
    -rw-r--r-- 1 fh users 673740  1 mar 20:14 .cache.json

In the install output mentioned below is this line

>user "root" does not have permission to access the dev dir "/root/.node-gyp/5.7.0"

But this folder does not exist and logically subsequent attempt to compile node-gyp fails. 
I have no idea of how the install process is supposed to exec and which folders/files to find where.

    $ sudo npm install -g ionic@beta
    /usr/bin/ionic -> /usr/lib/node_modules/ionic/bin/ionic

    > fsevents@1.0.8 install /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
    > node-pre-gyp install --fallback-to-build

    gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.7.0"
    gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/.node-gyp"
    make: Entering directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/build'
    make: *** No rule to make target '../.node-gyp/5.7.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
    make: Leaving directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:100:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 4.4.1-2-ARCH
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node" "--module_name=fse" "--module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64"
    gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
    gyp ERR! node -v v5.7.0
    gyp ERR! node-gyp -v v3.3.0
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Linux 4.4.1-2-ARCH
    node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
    node-pre-gyp ERR! node -v v5.7.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.21
    node-pre-gyp ERR! not ok 
    Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    npm WARN install:fsevents@1.0.8 fsevents@1.0.8 install: `node-pre-gyp install --fallback-to-build`
    npm WARN install:fsevents@1.0.8 Exit status 1

    > node-sass@3.4.2 install /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules    /gulp-sass/node_modules/node-sass
    > node scripts/install.js

    > fsevents@1.0.8 install /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
    > node-pre-gyp install --fallback-to-build

    gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.7.0"
    gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/.node-gyp"
    make: Entering directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build'
    make: *** No rule to make target '../.node-gyp/5.7.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
    make: Leaving directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:100:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 4.4.1-2-ARCH
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node" "--module_name=fse" "--module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64"
    gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
    gyp ERR! node -v v5.7.0
    gyp ERR! node-gyp -v v3.3.0
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Linux 4.4.1-2-ARCH
    node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
    node-pre-gyp ERR! node -v v5.7.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.21
    node-pre-gyp ERR! not ok 
    Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    npm WARN install:fsevents@1.0.8 fsevents@1.0.8 install: `node-pre-gyp install --fallback-to-build`
    npm WARN install:fsevents@1.0.8 Exit status 1

**Comment by mcorrigan** [comment]
@tlancina  19 fixes the issue for me. Thanks.

**Comment by tlancina** [comment]
@fhdk I wonder if this is an instance of https://github.com/npm/npm/issues/10768. If you try with npm 3.3.12 does it work?

I only say that because the Ionic postinstall script should not be doing anything with fsevents on Linux.

**Comment by danielbertini** [comment]
For me a got

    ERROR in [default] /Users/danielbertini/Gitlab/gethelpAdmin/node_modules/ionic-framework/animations/animation.d.ts:54:50 
A 'this' type is available only in a non-static member of a class or interface.

ionic -v
2.0.0-beta.19

**Comment by tlancina** [comment]
@danielbertini that's a type error from running `ionic serve` on a typescript starter :) Also should be fixed in beta.2 which we just released about a minute ago (give us a few to update the starters).

**Comment by fhdk** [comment]
@tlancina

On GMT+1 so will check tomorrow. 

Sent from mobile



Den 1. mar. 2016 21.29, fra 21.29, Tim Lancina <notifications@github.com> skrev:

**Comment by tlancina** [comment]
@fhdk no rush, thanks for sticking it out, it's appreciated!

**Comment by zhouhao27** [comment]
It works now. But my version is still beta 19.

**Comment by fhdk** [comment]
@tlancina
I had a look at https://github.com/npm/npm/issues/10768 and I think youre right and think my findings confirms it.

So first thing today I did the install and did thorough walk-through of the messages.

    $ sudo npm install ionic@beta -g

The npm guys mention that, though npm throw warn and error outputs, other parts of the installation is not affected. In fact they describe these outputs as informational in regard to that specific process.

All messages references this partial path

> .../chokidar/node_modules/fsevents/...

Which in turn relates back to npm's attempt to install an OSX specific on Arch Linux

Npm's conclusion is

>npm WARN install:fsevents@1.0.8 fsevents@1.0.8 install: `node-pre-gyp install --fallback-to-build`
>npm WARN install:fsevents@1.0.8 Exit status 1

The following is except from the messages with - what I believe is - the source location of the cause of the message. The full output is added at the bottom of this post

Beginning from top working down:

>gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
>gyp ERR! stack     at emitTwo (events.js:100:13)
>gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

>node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
>node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
>node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
>node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
>node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

>gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
>gyp ERR! stack     at emitTwo (events.js:100:13)
>gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
>gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)

>node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
>node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
>node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
>node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

This indicates the installation attempt appers twice in the install process and as the last output is the final conclusion on the out'ed messages

>npm WARN install:fsevents@1.0.8 fsevents@1.0.8 install: `node-pre-gyp install --fallback-to-build`
>npm WARN install:fsevents@1.0.8 Exit status 1

Here follows the full output of this mornings successfull installation

    $ sudo npm install -g ionic@beta
    /usr/bin/ionic -> /usr/lib/node_modules/ionic/bin/ionic

    > fsevents@1.0.8 install /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
    > node-pre-gyp install --fallback-to-build

    gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.7.0"
    gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/.node-gyp"
    make: Entering directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/build'
    make: *** No rule to make target '../.node-gyp/5.7.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
    make: Leaving directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:100:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 4.4.1-2-ARCH
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node" "--module_name=fse" "--module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64"
    gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
    gyp ERR! node -v v5.7.0
    gyp ERR! node-gyp -v v3.3.0
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Linux 4.4.1-2-ARCH
    node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents
    node-pre-gyp ERR! node -v v5.7.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.21
    node-pre-gyp ERR! not ok 
    Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    npm WARN install:fsevents@1.0.8 fsevents@1.0.8 install: `node-pre-gyp install --fallback-to-build`
    npm WARN install:fsevents@1.0.8 Exit status 1

    > fsevents@1.0.8 install /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
    > node-pre-gyp install --fallback-to-build

    gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.7.0"
    gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/.node-gyp"
    make: Entering directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build'
    make: *** No rule to make target '../.node-gyp/5.7.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
    make: Leaving directory '/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:100:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 4.4.1-2-ARCH
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node" "--module_name=fse" "--module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64"
    gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
    gyp ERR! node -v v5.7.0
    gyp ERR! node-gyp -v v3.3.0
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Linux 4.4.1-2-ARCH
    node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
    node-pre-gyp ERR! node -v v5.7.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.21
    node-pre-gyp ERR! not ok 
    Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64/fse.node --module_name=fse --module_path=/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-linux-x64' (1)
    npm WARN install:fsevents@1.0.8 fsevents@1.0.8 install: `node-pre-gyp install --fallback-to-build`
    npm WARN install:fsevents@1.0.8 Exit status 1
    
    > ionic@2.0.0-beta.19 postinstall /usr/lib/node_modules/ionic
    > node lib/tasks/postinstall
    
    
    > spawn-sync@1.0.15 postinstall /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
    > node postinstall
    
    
    > node-sass@3.4.2 install /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
    > node scripts/install.js
    
    
    > node-sass@3.4.2 postinstall /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass
    > node scripts/build.js
    
    ` /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-47/binding.node ` exists. 
 testing binary.
    Binary is fine; exiting.
spawn-sync@1.0.15 /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cross-spawn/node_modules/spawn-sync
    node-sass@3.4.2 /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/gulp-   sass/node_modules/node-sass
    /usr/lib
    └── ionic@2.0.0-beta.19 

 I assumes it fair to say this post can be closed.

**Comment by fhdk** [comment]
Closing - would be nice though if npm would simple os-check before trying to install fsevents.

Thanks ionic for great framework.
