### ISSUE TITLE
Failed at the ionic@2.0.0-beta.18

### ISSUE THREAD

**Issue by danielbertini** [driftyco/ionic-cli#800]
Hey Ionites... someone can help me?
Work with Ionic2 on Mac last week and everything was perfect.
Now I tried update to ionic@2.0.0-beta.18 and got the error:

    npm ERR! Darwin 15.2.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "cordova" "ionic@beta"
    npm ERR! node v5.6.0
    npm ERR! npm  v3.6.0
    npm ERR! code ELIFECYCLE
    npm ERR! ionic@2.0.0-beta.18 postinstall: `node lib/tasks/postinstall`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ionic@2.0.0-beta.18 postinstall script 'node lib/tasks/postinstall'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the ionic package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node lib/tasks/postinstall
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs ionic
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls ionic
    npm ERR! There is likely additional logging output above.
    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/danielbertini/npm-debug.log`
   
Node and NPM are updated with:

    node -v 
    v5.6.0
    npm -v
    3.6.0

**Comment by fhdk** [comment]
Have a look at this
https://github.com/driftyco/ionic-cli/issues/797

**Comment by zhouhao27** [comment]
Got the same issue.

**Comment by tlancina** [comment]
Going to close as a dup of #797, please post any follow up there, thanks!
