### ISSUE TITLE
ionic resources does NOT upload  icon and splash screen

### ISSUE THREAD

**Issue by alexonozor** [driftyco/ionic-cli#803]
When I ran the following command to upload my icons and splash screen I got the following response but it don't seems to be working. Can someone help me out? I have tried a png and a psd file but it keep happening 

response 

`$ ionic resources`
```
Ionic icon and splash screen resources generator
 uploading icon.png...
 uploading splash.psd...
```

**Comment by yahyazini** [comment]
+1

**Comment by flastowizka** [comment]
You can try generate only one to test:
`ionic resources --icon`
or
`ionic resources --splash`

I had the same problem. Because the format of my splash

**Comment by Sacusa** [comment]
Same issue here. Could really use some help.

**Comment by jthoms1** [comment]
We recently released a new version of the CLI that should fix this issue.  Could you please update your CLI to at least 2.1.4?

`npm install -g ionic@latest`

Thank you!
