### ISSUE TITLE
--nobundle option does not appear to work

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-cli#806]
_From @chrisfelix82 on March 2, 2016 4:23_

#### Short description of the problem:
I have been using Browserify and a custom gulpfile since v1, and would like to keep using this in v2.  I already had a root "app" directory with source and build to www.  I have updated my gulpfile to support TypeScript (e.g. tsify with Browserify is pretty simple).  The issue is that I would like to run in live preview mode via ionic run ios --nobundle, but it is not working.  Seems that webpack stuff is always run.  As such I have had to stick to live preview of an Ionic 2 app using an ionic 1 project structure and cli.

#### What behavior are you expecting?
I expect that when I run any of the ionic run/serve etc commands with --nobundle, that all the cli does is start the live preview server, and delegates to the developer to bundle/build as was the case in Ionic 1

**Steps to reproduce:**
1. Run ionic run ios --nobundle
2. webpack is still run

**Ionic Version**: 2.x

**Browser & Operating System**: iOS

_Copied from original issue: driftyco/ionic#5673_

**Comment by tlancina** [comment]
Hey thanks for the issue. This flag is going to be going away soon we move to a gulp build: https://forum.ionicframework.com/t/attention-upcoming-ionic-2-starter-changes/45058

I'll leave this open until it lands.  Let us know if you have any questions/concerns, thanks!

**Comment by chrisfelix82** [comment]
Awesome!  I like that you guys will be switching to gulp and browserify as it is much simpler to work with and can support using regular non typescript common js modules without additional work.

**Comment by tlancina** [comment]
Closing as the starters now use Browserify by default and the build has been handed off to Gulp, so this shouldn't be an issue anymore.
