### ISSUE TITLE
"ionic serve" command gives me back this :(

### ISSUE THREAD

**Issue by Bellalife** [driftyco/ionic-cli#807]
ionic $  ✗ Caught exception:
 Error: listen EADDRNOTAVAIL 92.242.132.16
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1223:19)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

**Comment by tlancina** [comment]
Looks like something is already using the port ionic serve uses to serve your app.  Could you post the output of `ionic info` please?

**Comment by Bellalife** [comment]
Hi tlancina

here ionic info:

Your system information:

Cordova CLI: 6.0.0
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.1
Xcode version: Xcode 7.2.1 Build version 7C1002 


******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly suggested to install/upgrade the following:     

 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************

I tried to install ios-deploy but some some reason I can't and I don't know why:

Base:~ base5$ npm install -g ios-deploy
npm ERR! tar.unpack untar error /Users/base5/.npm/ios-deploy/1.8.5/package.tgz
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path /usr/local/lib/node_modules/ios-deploy
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ios-deploy'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ios-deploy']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/ios-deploy',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/ios-deploy',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/base5/npm-debug.log

**Comment by Bellalife** [comment]
Can anybody help me? I'm still stuck...

**Comment by tlancina** [comment]
Hey @Bellalife sorry you're still having issues.  Don't worry so much about the `ios-deploy` errors for now, they're most likely separate from the `serve` issue, and I believe can be fixed by doing `sudo npm install -g ios-deploy`.

Do you still get the same error when doing `ionic serve`?

**Comment by gsanjeevkumar** [comment]
I agree with @tlancina however in this kind of situations i try to make sure my user has owns / has full permissions on the folder where the node_modules are installed.

that helped most of the time I am using Mac OS X though. This should be similar with other environments

let me know if you could fix it.

**Comment by Bellalife** [comment]
Thanks guys,
I installed everything I needed now but the "ionic serve" problem is still there. It's very strange because I can use it through Ionic Lab but I can't through terminal. In any case I'm ok if this issue won't ruin the development of my app... we'll see.

**Comment by gsanjeevkumar** [comment]
either /usr/local/lib/node_modules should have read and write permissions for user "base5"

or

user "base5" should own the /usr/local/lib/node_modules

try chown `whom`:<admin> -R /usr/local/lib/node_modules

<admin> = the group has admin permissions.

**Comment by Bellalife** [comment]
Nope @gsanjeevkumar, it doesn't work. when I "ionic serve" the result is this and the browser fails to show me my ionic project:

Base:project1 base5$ ionic serve
The port 8100 was taken on the host localhost - using port  instead

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file

∆ Compiling Sass to CSS
√ Matching patterns: app/theme/app.+(ios|md).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-angular/fonts/**/*.+(ttf|woff|woff2)

∆ Copying HTML
√ Matching patterns: app/**/*.html

√ Sass compilation complete
√ HTML copied to www/build
√ Fonts copied to www/build/fonts

Hash: ce8d8602a8e8752f5709
Version: webpack 1.12.11
Time: 7199ms
        Asset     Size  Chunks             Chunk Names
app.bundle.js  2.71 MB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 363 hidden modules

√ Webpack complete

∆ Starting dev server.

√ Running live reload server: http://localhost:35729
√ Running dev server:  http://localhost:
√ Watching: 0=www/build/**/*.html, 1=www/build/**/*.js, 2=www/build/**/*.css
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $  ✗ Caught exception:
 Error: listen EADDRNOTAVAIL 92.242.132.16
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1223:19)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

**Comment by Bellalife** [comment]
if I run server through nic lab the console gives me back this error:
GET http://0.0.0.0:8100/cordova.js 

I think "0.0.0.0" should be "localhost" instead. @gsanjeevkumar do you think this is the problem?
Thanks for your help!

**Comment by tlancina** [comment]
@Bellalife Is it working? `GET http://0.0.0.0:8100/cordova.js` is harmless, it just means that you are running in a browser and not on a device.

It is weird that `The port 8100 was taken on the host localhost - using port instead` doesn't display an alternate port. Any idea what is using port 8100 already on your machine? If you're not sure, then does restarting your computer help?

**Comment by Bellalife** [comment]
Hi @tlancina, it isn't working. Reboot my machine didn't help but maybe there's a command to figure out what is using port 8100, isn't there?

**Comment by Bellalife** [comment]
I fixed the problem. For some reason the file private/etc/hosts was changed. I replaced it with the original and now I can launch ionic serve form the terminal. Finally

**Comment by tlancina** [comment]
Great! Glad it's working, going to close the issue, but let us know if you're still having problems, thanks!

**Comment by oikonomopo** [comment]
Or someone could try `ionic serve --address=127.0.0.1`. 
In my case due proxy issues i couldn't serve at `0.0.0.0`

**Comment by pgomez-redsauce** [comment]
In my case (MacOS) the solution was to edit the /etc/hosts file and set 127.0.0.1 as localhost.
