### ISSUE TITLE
ionic start [name] tutorial --v2 fail because of wrong github repo URL

### ISSUE THREAD

**Issue by quentin-sommer** [driftyco/ionic-cli#808]
Running the command provided here http://ionicframework.com/docs/v2/getting-started/tutorial/

`ionic start MyIonic2Project tutorial --v2`

outputs :

```
Downloading: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip
 ✗ Not found: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip (404)
 ✗ Please verify the url and try again.
```

I believe the url https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip should be replace by https://github.com/driftyco/ionic2-starter-tutorial

Quentin

**Comment by tlancina** [comment]
Looks like you need the beta version of the CLI, `npm install -g ionic@beta`: http://ionicframework.com/docs/v2/getting-started/installation/.

Let me know if you're still having issues, thanks!

**Comment by quentin-sommer** [comment]
Works like a charm thanks !
