### ISSUE TITLE
ionic build android

### ISSUE THREAD

**Issue by physedo** [driftyco/ionic-cli#812]
I have this problem

ai@ai-laptop:~/cookbooke$ ionic build android
Running command: /home/ai/cookbooke/hooks/after_prepare/010_add_platform_class.js /home/ai/cookbooke
add to body class: platform-android
ANDROID_HOME=/home/ai/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:1.5.0.
     Required by:
         :android:unspecified
      > Could not GET 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom'.
         > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.678 secs
ERROR building one of the platforms: Error code 1 for command: /home/ai/cookbooke/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/ai/cookbooke/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
You may not have the required environment or OS to build this project
Error: Error code 1 for command: /home/ai/cookbooke/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/ai/cookbooke/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

ionic info
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.3.1

help

**Comment by tlancina** [comment]
Not sure, does this help: http://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse?

**Comment by physedo** [comment]
Thanks it works now. 👍

**Comment by tlancina** [comment]
Awesome, glad it's working.

**Comment by physedo** [comment]
It was something else. Thanks

**Comment by bazilbycom** [comment]
@physedo .. im having the same problem. can you tell me how ?

**Comment by bazilbycom** [comment]
should i upgrade to jdk 8?
