### ISSUE TITLE
Error: Cannot find module 'xmlbuilder'

### ISSUE THREAD

**Issue by piotrros** [driftyco/ionic-cli#813]
Hi, I'm using mac os yosemite and tried to install ionic.

First I've installed Node.js 4 and then 

`sudo npm install -g cordova ionic`

Installation succeeded and I tried to create blank app:

`ionic start myApp blank`

However I got following error:

> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'xmlbuilder'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:12:13)
>     at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:436:4)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)

**Comment by piotrros** [comment]
Ok, so after trying again, again and again:

```
sudo npm install -g xmlbuilder
sudo npm install -g archiver
sudo npm install -g wordwrap
sudo npm install -g winston
sudo npm install -g ios-sim
sudo npm install -g utile
sudo npm install -g read
sudo npm install -g revalidator
sudo npm install -g cycle
sudo npm install -g stack-trace
sudo npm install -g pkginfo
sudo npm install -g through
sudo npm install -g from
sudo npm install -g duplexer
sudo npm install -g map-stream
sudo npm install -g pause-stream
sudo npm install -g split
sudo npm install -g stream-combiner
sudo npm install -g tough-cookie
sudo npm install -g json-stringify-safe
sudo npm install -g qs
sudo npm install -g bl
sudo npm install -g hawk
sudo npm install -g aws-sign2
sudo npm install -g http-signature
sudo npm install -g mime-types
sudo npm install -g tunnel-agent
sudo npm install -g stringstream
sudo npm install -g forever-agent
sudo npm install -g combined-stream
sudo npm install -g mime-db
sudo npm install -g setimmediate
sudo npm install -g binary
sudo npm install -g pullstream
sudo npm install -g match-stream
sudo npm install -g inherits
sudo npm install -g mkdirp
sudo npm install -g rimraf
sudo npm install -g ionic-cordova-lib
sudo npm install -g htmlparser2
sudo npm install -g lodash
sudo npm install -g dom-serializer
sudo npm install -g css-select
```

finally errors are gone, but now it hangs on project creation:

```
ionic start myApp blank
Creating Ionic app in folder /Users/piotr/Documents/js/myApp based on blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
```

stuck on 100%, I've waited several minutes...

**Comment by tlancina** [comment]
Hey @piotrros sorry you're having issues, we've seen a few cases of these missing dependency errors and I'm not quite sure what causes them to not be installed correctly in the first place.  Was that list all things you had to install manually because they were throwing errors, or did you just do that to be safe?

**Comment by piotrros** [comment]
I was installing them like: 

try to: ionic start myApp blank
check what's missing, install it.

etc, etc.
Got me an hour to install all of them.
But it still doesn't work, it hangs on project creation... I've tried on my mate computer and it just installed without installing extra modules and project just created without a problem. 

Is there some other way to create project?

**Comment by tlancina** [comment]
@piotrros it sounds like `npm` has some serious issues on your machine, you shouldn't have to manually install all of those dependencies.

Could you post the output of `ionic info` and `npm -v` please?

**Comment by ngtrieuvi92** [comment]
i have the same problem when i try to install ionic on my ubuntu 14.04 machine, i'm using nodejs version `4.3.2`
output of `npm -v`:
`3.8.0`
and output of `ionic info`:
`module.js:327
    throw err;
    ^

Error: Cannot find module 'xmlbuilder'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:12:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/xml2js/lib/xml2js.js:436:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12`

how can i fix this problem?

**Comment by piotrros** [comment]
@tlancina ionic info hangs
npm -v returns 2.14.12

**Comment by tlancina** [comment]
@piotrros does `/usr/local/lib/node_modules/ionic/node_modules/xml2js/node_modules` contain `xmlbuilder`?

**Comment by piotrros** [comment]
It only contains "sax".

**Comment by piotrros** [comment]
Running ionic install once again reveals a lot of dependency warnings:

`sudo npm install -g cordova ionic`


```
Password:
/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/cheerio requires css-select@'~1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/css-select,
npm WARN unmet dependency which is version 1.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/cheerio requires htmlparser2@'~3.8.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/htmlparser2,
npm WARN unmet dependency which is version 3.9.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/cheerio requires lodash@'^3.2.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/lodash,
npm WARN unmet dependency which is version 4.6.1
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/event-stream requires split@'0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/split,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/event-stream requires stream-combiner@'~0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/stream-combiner,
npm WARN unmet dependency which is version 0.2.2
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/form-data requires combined-stream@'~0.0.4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/combined-stream,
npm WARN unmet dependency which is version 1.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib requires archiver@'^0.5.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/archiver,
npm WARN unmet dependency which is version 0.21.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib requires winston@'^1.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/winston,
npm WARN unmet dependency which is version 2.2.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/optimist requires wordwrap@'~0.0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/wordwrap,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/prompt requires revalidator@'0.1.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/revalidator,
npm WARN unmet dependency which is version 0.3.1
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/prompt requires utile@'0.2.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/utile,
npm WARN unmet dependency which is version 0.3.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires aws-sign2@'~0.5.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/aws-sign2,
npm WARN unmet dependency which is version 0.6.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires bl@'~0.9.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/bl,
npm WARN unmet dependency which is version 1.1.2
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires combined-stream@'~0.0.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/combined-stream,
npm WARN unmet dependency which is version 1.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires forever-agent@'~0.5.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/forever-agent,
npm WARN unmet dependency which is version 0.6.1
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires hawk@'1.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/hawk,
npm WARN unmet dependency which is version 4.1.2
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires http-signature@'~0.10.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/http-signature,
npm WARN unmet dependency which is version 1.1.1
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires mime-types@'~1.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/mime-types,
npm WARN unmet dependency which is version 2.1.10
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request requires qs@'~2.3.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/qs,
npm WARN unmet dependency which is version 6.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/unzip requires pullstream@'~0.4.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/pullstream,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request/node_modules/form-data requires combined-stream@'~0.0.4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/combined-stream,
npm WARN unmet dependency which is version 1.0.5
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request/node_modules/form-data/node_modules/mime-types requires mime-db@'~1.12.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/mime-db,
npm WARN unmet dependency which is version 1.22.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires osenv@'0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/osenv,
npm WARN unmet dependency which is version 0.1.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires nopt@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.6
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 5.0.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires ini@'~1.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/ini,
npm WARN unmet dependency which is version 1.3.4
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 5.0.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-git@'~1.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-git,
npm WARN unmet dependency which is version 1.4.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'0.0.2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2
ionic@1.7.14 /usr/local/lib/node_modules/ionic

cordova@6.0.0 /usr/local/lib/node_modules/cordova
├── underscore@1.7.0
├── ansi@0.3.1
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.7)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, repeating@1.1.3, chalk@1.1.1, configstore@1.4.0, latest-version@1.0.1)
└── cordova-lib@6.0.0 (valid-identifier@0.0.1, opener@1.4.1, properties-parser@0.2.3, semver@4.3.6, shelljs@0.3.0, nopt@3.0.6, dep-graph@1.1.0, xcode@0.8.0, npmconf@2.1.2, request@2.47.0, aliasify@1.9.0, cordova-serve@1.0.0, cordova-app-hello-world@3.10.0, tar@1.0.2, init-package-json@1.9.3, npm@2.14.22, cordova-js@4.1.3)
```

**Comment by tlancina** [comment]
Hmm I think those warnings are fine, do you still get the `xmlbuilder` error? And if so, does running `npm install` from `/usr/local/lib/node_modules/ionic/node_modules/xml2js/`make it go away?

**Comment by piotrros** [comment]
Yeah:

```
sudo npm install
Password:
zap@0.2.9 node_modules/zap

diff@2.2.1 node_modules/diff

coffee-script@1.10.0 node_modules/coffee-script

xmlbuilder@5.0.1 node_modules/xmlbuilder
└── lodash@4.6.1

docco@0.7.0 node_modules/docco
├── underscore@1.8.3
├── marked@0.3.5
├── highlight.js@9.2.0
├── commander@2.9.0 (graceful-readlink@1.0.1)
└── fs-extra@0.26.5 (graceful-fs@4.1.3, klaw@1.1.3, jsonfile@2.2.3, path-is-absolute@1.0.0, rimraf@2.5.2)
```

but still running command:

```
ionic start myApp blank
Creating Ionic app in folder /Users/piotr/Documents/js/myApp based on blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
```

hangs forever.

So - there's no error - just ionic is hanging...

**Comment by tlancina** [comment]
So to be clear, you got the `xmlbuilder` error still, and then running `npm install` from that directory made it go away? That is what I can't understand, why those dependencies are not being installed correctly.  This sounds like an npm bug.

Could you run `ionic start` with the `--verbose` flag and paste the output please?

**Comment by piotrros** [comment]
No, I'm not getting any dependencies errors while running 

npm install -g cordova ionic

or 

npm install

or

nom install -g xmlbuilder

ionic is simply hanging at project creation.

As for ionic start --verbose output is rather strange:

```
ionic start --verbose
Utils.fail Invalid command start
Utils.fail stack undefined
Utils.errorHandler is set, calling that now
Cli.Utils.errorHandler msg Invalid command string



Invalid command (CLI v1.7.14)

Your system information:

Cordova CLI: 6.0.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.2 Build version 7C68 
```

By the way I have Yosemite not El Capitan.

**Comment by tlancina** [comment]
Can you please paste the output of `ionic start --verbose myapp`

**Comment by piotrros** [comment]
```
ionic start --verbose myapp
Utils.fail Invalid command start
Utils.fail stack undefined
Utils.errorHandler is set, calling that now
Cli.Utils.errorHandler msg Invalid command string



Invalid command (CLI v1.7.14)

Your system information:

Cordova CLI: 6.0.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v4.3.2
Xcode version: Xcode 7.2 Build version 7C68 
```

**Comment by tlancina** [comment]
So sorry! The argument parsing is weird (this looks like a bug), can you do `ionic start myapp --verbose`?

**Comment by piotrros** [comment]
```
ionic start myapp --verbose
Utils.preprocessCliOptions _=[start, myapp], no-cordova=false, w=false, sass=false, s=false, list=false, l=false, verbose=true, $0=ionic
Creating Ionic app in folder /Users/piotr/Documents/js/myapp based on tabs project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
<-- hangs there
```

**Comment by piotrros** [comment]
I'm stuck :( What can I do else then reinstalling whole mac os x?

**Comment by tlancina** [comment]
@piotrros it looks like it's hanging on unzipping the downloaded file, I wonder if there is some error being swallowed.  I would suspect that it is again an uninstalled dependency.

Does doing `npm cache clean` or reinstalling npm do anything? I think the root cause of the problem here is that for some reason npm doesn't install all the dependencies it should.

If those still don't help could you try attaching the output of `sudo npm install ionic -g --verbose`? I'll take a look to see if I can tell if anything abnormal is going on during the install.

**Comment by piotrros** [comment]
After npm cache clean I'm getting following output (sudo npm install ionic -g --verbose):

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ionic" "-g" "--verbose"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.4.2 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild lib/node_modules/ionic
npm info preuninstall ionic@1.7.14
npm info uninstall ionic@1.7.14
npm verb unbuild rmStuff ionic@1.7.14 from /usr/local/lib/node_modules
npm verb gentlyRm vacuuming from /usr/local/bin/ionic up to /usr/local
npm info postuninstall ionic@1.7.14
npm verb gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ionic

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/piotr/Documents/js/npm-debug.log
```

**Comment by piotrros** [comment]
And installing node-sass alone works:

sudo npm install node-sass
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
 
> spawn-sync@1.0.15 postinstall /Users/piotr/Documents/js/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

-
> node-sass@3.4.2 install /Users/piotr/Documents/js/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/piotr/Documents/js/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.4.2 postinstall /Users/piotr/Documents/js/node_modules/node-sass
> node scripts/build.js

` /Users/piotr/Documents/js/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.4.2 node_modules/node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── mkdirp@0.5.1 (minimist@0.0.8)
├── nan@2.2.0
├── chalk@1.1.1 (escape-string-regexp@1.0.5, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1, ansi-styles@2.2.0)
├── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.3, semver@4.3.6, osenv@0.1.3, nopt@3.0.6, config-chain@1.1.10)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.3, minimatch@3.0.0)
├── gaze@0.5.2 (globule@0.1.0)
├── cross-spawn@2.1.5 (cross-spawn-async@2.1.9, spawn-sync@1.0.15)
├── meow@3.7.0 (map-obj@1.0.1, decamelize@1.2.0, trim-newlines@1.0.0, object-assign@4.0.1, minimist@1.2.0, camelcase-keys@2.0.0, loud-rejection@1.3.0, redent@1.0.0, normalize-package-data@2.3.5, read-pkg-up@1.0.1)
├── request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.0.2, combined-stream@1.0.5, mime-types@2.1.10, form-data@1.0.0-rc3, aws4@1.3.2, hawk@3.1.3, bl@1.0.3, http-signature@1.1.1, har-validator@2.0.6)
├── sass-graph@2.1.1 (glob@6.0.4, yargs@3.32.0, lodash@4.6.1)
└── node-gyp@3.3.1 (graceful-fs@4.1.3, semver@5.1.0, osenv@0.1.3, nopt@3.0.6, minimatch@1.0.0, fstream@1.0.8, which@1.2.4, glob@4.5.3, rimraf@2.5.2, tar@2.2.1, npmlog@2.0.2, path-array@1.0.1)

But then running sudo npm install ionic -g --verbose gives the same error again and again.

**Comment by abdulmujeebma786** [comment]
ionic start myApp blank
Creating Ionic app in folder /Users/piotr/Documents/js/myApp based on blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
**stuck on 100%, I've waited several minutes...**
Please help me

**Comment by piotrros** [comment]
@tlancina No such file or directory... Which tool is used to unpack zip file? Maybe I'll test if it's working.

**Comment by piotrros** [comment]
So, I've removed completely npm and it's modules and installed node from dmg (v4). And again I'm getting an error with node-sass, but when trying to install node-sass alone I'm getting:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-sass" "-g" "--verbose"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spawn-sync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.
```

And here's log:

http://speedy.sh/AtMj7/npm-debug.log

This is mission impossible...

**Comment by sparber** [comment]
I had the same issue on ubuntu.

I solved it by:
- removing nodejs,
- deleting the /usr/lib/node_modules (/usr/local/lib/node_modules) folder
- reinstalling nodejs,
- **clearing the npm cache** (npm cache clean)
- reinstalling ionic

I hope that helps

**Comment by xrexonx** [comment]
Hi. @piotrros 
 You can try this. Fixed my issue for that. 
http://stackoverflow.com/questions/35260593/ionic-installation-after-ionic2-installation/35952270#35952270

**Comment by piotrros** [comment]
Thanks for help!!

First of I followed @sparber instructions (removed nodejs using this script: https://gist.github.com/TonyMtz/d75101d9bdf764c890ef)

Then I installed ionic using this command:

sudo npm install -g ionic@beta  cordova --unsafe-perm

Without unsafe-perm I was getting access denied errors (even with sudo).

And it worked!

**Comment by sn0opr** [comment]
it doesn't work for me too, first time I installed ionic on Ubuntu 14.04 still, get the xmlbuilder problem, please fix this, I'm trying to convince about using ionic for a new project and I'm in a bad situation now :-1:

**Comment by abdulmujeebma786** [comment]
I had the same issue on ubuntu.

I solved it by:

removing nodejs,
deleting the /usr/lib/node_modules (/usr/local/lib/node_modules) folder
reinstalling nodejs,
clearing the npm cache (npm cache clean)
reinstalling ionic

I hope that helps

**Comment by MsEmma** [comment]
I resolved it by just doing it in docker :-p

**Comment by sn0opr** [comment]
like @abdulmujeebma786 said, deleting nodejs completely and deleting the node_modules folder solves the problem, use synaptic ubuntu package manager ui to delete nodejs

**Comment by ngtrieuvi92** [comment]
@sn0opr, I solved it on my ubuntu 14.04  by change nodejs version to v4.3.1

**Comment by bigloupe** [comment]
idem for Windows. 
No problem after this 2 commands :
npm cache clean
npm update -g

**Comment by mastah43** [comment]
solved it for me:
npm cache clean
npm install -g ionic cordova

**Comment by codeforkorea** [comment]
@mastah43  You save my life. thanks a lot!

**Comment by abdulmujeebma786** [comment]
👍💪👍💪👍

**Comment by xSteady** [comment]
I had the same issue. http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode  - this helped:

1) Clear NPM's cache:

sudo npm cache clean -f

2) Install a little helper called 'n'

sudo npm install -g n

3) Install latest stable NodeJS version

sudo n stable

**Comment by ashleypeacock** [comment]
Also having this issue on redhat, which is a fresh install. None of these commands are working currently to fix it.

**Comment by xSteady** [comment]
On Ubuntu 14.04 these steps helped.

**Comment by syntaxbliss** [comment]
This is worked for me on Ubuntu 14.04 LTS:

1) npm cache clean (probably not necessary, but...)
2) npm i -g n
3) n stable

After that, node switched to version 6.0.0, and problem solved. Hope this help for you as well.

**Comment by ivanevil** [comment]
Hello, a tried every single solution, this is what worked for me

inside 

1) /user/local/lib/node_module //or where your node_module directory is, you has to locate ionic module

2) cd ionic

from there install the dependency locally,  
3) sudo npm install -d xmlbuilder

I guarantee it will work like a charm.

**Comment by vigneshmuthukrishnan** [comment]
Hi guys I have some problem....
please fix...
module.js:442
    throw err;
    ^

Error: Cannot find module 'file-utils'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\ionic
\node_modules\ionic-app-lib\node_modules\archiver\lib\util\index.js:17:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by sn0opr** [comment]
@vigneshmuthukrishnan try to remove the the node_modules folder and reinstall again

**Comment by vigneshmuthukrishnan** [comment]
@sn0opr    Thanku for information i will try..........
