### ISSUE TITLE
Ionic v2: Ionic doesn't run on Android

### ISSUE THREAD

**Issue by MHerszak** [driftyco/ionic-cli#816]
I was trying to run my Ionic 2 App on my device. Build and Run are successful but nothing happens. No error report. Any idea what it might be?

**Comment by tlancina** [comment]
Hey could you clarify what you mean by "successful, but nothing happens"? Also if you could post the output from `ionic info` that would help as well, thanks!

**Comment by MHerszak** [comment]
Hi @tlancina 

I do a build and it seems successful. I do ionic run android and it seems successful but it is not send to my device. Connected via usb. I would expect the same deployment abilities as with Ionic 1. Does that make sense? 

Ionic info:

Cordova CLI: 4.3.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.2
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.7.0 
ios-sim version: 5.0.1 
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.2.1 Build version 7C1002 

Now I am pasting my console log:

michelherszak@Michels-MacBook-Air ~/P/J/i/ionic2-tutorial-github> ionic build android

∆ Compiling Sass to CSS
√ Matching patterns: app/theme/app.+(ios|md).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-angular/fonts/**/*.+(ttf|woff|woff2)

∆ Copying HTML
√ Matching patterns: app/**/*.html

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file
√ HTML copied to www/build
√ Sass compilation complete
√ Fonts copied to www/build/fonts
√ Compiling files complete.

Hash: 92b179dbef029bf68a93
Version: webpack 1.12.11
Time: 8806ms
        Asset     Size  Chunks             Chunk Names
app.bundle.js  2.71 MB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 361 hidden modules

√ Webpack complete

michelherszak@Michels-MacBook-Air ~/P/J/i/ionic2-tutorial-github> ionic run android

∆ Compiling Sass to CSS
√ Matching patterns: app/theme/app.+(ios|md).scss

∆ Copying fonts
√ Matching patterns: node_modules/ionic-angular/fonts/**/*.+(ttf|woff|woff2)

∆ Copying HTML
√ Matching patterns: app/**/*.html

∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file
√ HTML copied to www/build
√ Sass compilation complete
√ Fonts copied to www/build/fonts
√ Compiling files complete.

Hash: 92b179dbef029bf68a93
Version: webpack 1.12.11
Time: 8006ms
        Asset     Size  Chunks             Chunk Names
app.bundle.js  2.71 MB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 361 hidden modules

√ Webpack complete

**Comment by tlancina** [comment]
If you run `adb devices` does it show any devices listed?

**Comment by MHerszak** [comment]
Jupp.

List of devices attached
ZX1B225QLJ	device

It still works with Ionic 1.

**Comment by tlancina** [comment]
@MHerszak yeah something is definitely weird, it's not actually doing the `run` command.  Does `cordova run android` work for you?

**Comment by MHerszak** [comment]
@tlancina cordova run android does nothing, unfortunately. Any ideas?

**Comment by tlancina** [comment]
Does reinstalling/updating Cordova: `npm install -g cordova` help? Looks like the version you're on is a little old, I believe latest is 6.0.0.

**Comment by MHerszak** [comment]
Okay, so my device has been detected after installing cordova. So the next error that occurred was this: 
Error: Failed to run "ant -version", make sure you have ant installed and added to your PATH. I am trying to add ant but fail to do so. Any advice?

**Comment by tlancina** [comment]
Hey @MHerszak sorry for the late follow up, is this still an issue?

**Comment by MHerszak** [comment]
I haven't touched it in a while. However, I am giving a talk about Ionic2 this Thursday and I am going to start to work on it today. I can give you an update.

**Comment by tlancina** [comment]
Ok great, I was just going to close the issue as not an Ionic CLI bug and point you in the direction of http://stackoverflow.com/questions/19495610/error-executing-command-ant-on-mac-os-x-10-9-mavericks-when-building-for-andro for the ant problem.

Please open issues for any other problems you have getting up and running though, thanks!
