### ISSUE TITLE
Add the new starter template. Ionic v1.x

### ISSUE THREAD

**Issue by jdnichollsc** [driftyco/ionic-cli#818]
Hi Ionic team,

Please, share my starter template. https://github.com/jdnichollsc/Ionic-Starter-Template

Regards, Nicholls

**Comment by tlancina** [comment]
Hey @jdnichollsc, that starter looks pretty awesome, but we're not adding any new starters at the moment :)

**Comment by jdnichollsc** [comment]
why? :(
PD: About Ionic 2.... Will you continue support Ionic 1.x? :)
Regards @tlancina
