### ISSUE TITLE
Iphone 6 and iPhone 6+ splashscreens are not generated automatically

### ISSUE THREAD

**Issue by anonrig** [driftyco/ionic-cli#821]
Hello,

I am using cordova 6.0.0, ionic 1.7.14 and when I called `ionic resources` with proper `splash.png` file with size 1200x1200, only the respected images are created:

http://postimg.org/image/61gsks9if/

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
