### ISSUE TITLE
`ionic resources` incompatible with phonegap build

### ISSUE THREAD

**Issue by tomchiverton** [driftyco/ionic-cli#822]
`ionic resources` is only able to create the files in /resources/. `phonegap build` only packages files in /www/, so it would be good to have the option of where to create the various sized versions.

**Comment by tlancina** [comment]
Hey thanks for the issue, this can be accomplished with an npm script, gulp task or shell script to copy the files over and isn't a feature we'll be adding to the CLI at the moment.
