### ISSUE TITLE
Problem to install ios-deploy

### ISSUE THREAD

**Issue by zhouhao27** [driftyco/ionic-cli#823]
Got the following error message:

> ○ sudo npm i -g ios-deploy
> npm WARN lifecycle ios-deploy@1.8.5~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.8.5 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-298c9491
> npm ERR! Darwin 15.4.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "ios-deploy"
> npm ERR! node v5.7.1
> npm ERR! npm  v3.6.0
> npm ERR! path /usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall chmod
> 
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ios-deploy/build/Release/ios-deploy'
> npm ERR! enoent This is most likely not a problem with npm itself
> npm ERR! enoent and is related to npm not being able to find a file.
> npm ERR! enoent 
> 

What could be the reason? Thanks.

**Comment by tlancina** [comment]
Hey there, this isn't an Ionic CLI bug, so I'm going to close it.  I'd suggest trying on the forums: https://forum.ionicframework.com or the ios-deploy issues: https://github.com/phonegap/ios-deploy.
