### ISSUE TITLE
Wish: Ionic CLI should generate UTF-8 HTML

### ISSUE THREAD

**Issue by cawoodm** [driftyco/ionic-cli#829]
Noticed the pages (e.g. index.html) generated by `ionic start` are ANSI/ASCII which is fine for those working only in English but problematic for everyone else.

I think it would be a small fix - which wouldn't impact others - to encode the HTML files as UTF-8 and this support international users.

**Comment by tlancina** [comment]
Hey thanks for the issue, I'm not super familiar with encoding, but isn't that what https://github.com/driftyco/ionic-app-base/blob/master/www/index.html#L4 and https://github.com/driftyco/ionic2-starter-tabs/blob/master/www/index.html#L4 are?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
