### ISSUE TITLE
Unhandled rejection Error: Cannot resolve module 'ionic-angular' in app.ts

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-cli#831]
_From @hunterleaman on March 10, 2016 14:37_

##### Short description of the problem:
Console throws the titular error for no apparent reason. Project was running fine a day ago, then today after no changes, it throws this error when I try to serve the app. 

##### What behavior are you expecting?
Im expecting it to compile and serve like normal.

**Steps to reproduce:**
1. Honestly I can't layout the steps because I'm not sure what's causes the issue. It seems to come out of nowhere. The project with which I'm having this problem is very very basic at this point. Just started it, still has only one page. No errors or problems when I was running it a day ago.
2. 
3. 

Here's the full error output:
```
Unhandled rejection Error: Cannot resolve module 'ionic-angular' in app  
    Required in app/app.ts  
    at ResolutionError.Error (native)  
    at new ResolutionError (/Users/...[path].../[app name]/node_modules/awesome-typescript-loader/dist.babel/deps.js:482:88)  
    at (/Users/...[path].../[app name]/node_modules/awesome-typescript-loader/dist.babel/deps.js:301:37  
    at tryCatcher (/Users/...[path].../[app name]/node_modules/bluebird/js/main/util.js:26:23)  
    at CatchFilter.doFilter (/Users/...[path].../[app name]/node_modules/bluebird/js/main/catch_filter.js:52:40) 
    at CatchFilter.tryCatcher (/Users/...[path].../[app name]/node_modules/bluebird/js/main/util.js:26:23)  
    at Promise._settlePromiseFromHandler (/Users/...[path].../[app name]/node_modules/bluebird/js/main/promise.js:507:31)  
    at Promise._settlePromiseAt (/Users/...[path].../[app name]/node_modules/bluebird/js/main/promise.js:581:18)  
    at Promise._settlePromises (/Users/...[path].../[app name]/node_modules/bluebird/js/main/promise.js:697:14)  
    at Async._drainQueue (/Users/...[path].../[app name]/node_modules/bluebird/js/main/async.js:123:16) 
    at Async._drainQueues (/Users/...[path].../[app name]/node_modules/bluebird/js/main/async.js:133:10)  
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/...[path].../[app name]/node_modules/bluebird/js/main/async.js:15:14)  
    at processImmediate [as _immediateCallback] (timers.js:384:17)
```

This comes right after:  
```
∆ Copying HTML  
√ Matching patterns: app/**/*.html  
```

And is followed by:  
```
√ HTML copied to www/build  
√ Sass compilation complete  
√ Fonts copied to www/build/fonts  
```

System info:  

Cordova CLI: 5.4.1  
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.7.0
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v5.2.0
Xcode version: Xcode 7.2.1 Build version 7C1002

Any help is appreciated!

_Copied from original issue: driftyco/ionic#5794_

**Comment by tlancina** [comment]
Oops sorry, that's just the dist folder from awesome-typescript-loader.  How about the output of `webpack --display-error-details`, and if you don't have webpack installed globally you can do `$(npm bin)/webpack --display-error-details`

**Comment by hunterleaman** [comment]
Same error output when I run `webpack --display-error-details`

**Comment by hunterleaman** [comment]
Yep. Here's the module from the project https://www.dropbox.com/s/2xiftnktev0rqnx/ionic-angular.zip?dl=0

**Comment by hunterleaman** [comment]
tsconfig only to add formatCode options. Removed formatCodeOptions, restarted text editor and tried again with same result.

tsconfig:

```
"atom": {
    "rewriteTsconfig": true
  },
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "filesGlob": [
    "**/*.ts",
    "!node_modules/**/*"
  ],
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ],
  "compileOnSave": false,
  "files": [
    ...files...
  ]
```


webpack.config:  

```
var path = require('path');

module.exports = {
  entry: [
    path.normalize('es6-shim/es6-shim.min'),
    'reflect-metadata',
    path.normalize('zone.js/dist/zone-microtask'),
    path.resolve('app/app')
  ],
  output: {
    path: path.resolve('www/build/js'),
    filename: 'app.bundle.js',
    pathinfo: false // show module paths in the bundle, handy for debugging
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loader: 'awesome-typescript',
        query: {
          doTypeCheck: true,
          resolveGlobs: false,
          externals: ['typings/main.d.ts']
        },
        include: path.resolve('app'),
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        include: path.resolve('node_modules/angular2'),
        loader: 'strip-sourcemap'
      }
    ],
    noParse: [
      /es6-shim/,
      /reflect-metadata/,
      /zone\.js(\/|\\)dist(\/|\\)zone-microtask/
    ]
  },
  resolve: {
    root: ['app'],
    alias: {
      'angular2': path.resolve('node_modules/angular2')
    },
    extensions: ["", ".js", ".ts"]
  }
};
```

**Comment by tlancina** [comment]
Any change if you remove the files array from tsconfig?

**Comment by hunterleaman** [comment]
Changed atom rewriteTsconfig to false and removed the files and it works!

**Comment by hunterleaman** [comment]
Still a problem if I reenable rewriteTsconfig.

**Comment by tlancina** [comment]
Awesome, glad it's working! Sorry this got you, I believe it's a bug/weird behavior in the typescript loader in how it handles files in tsconfig, I've run into it as well. If I remember right, when it loads the files from tsconfig, there's some mismatch in absolute vs relative paths and it thinks that the module isn't found (even though the path _is_ correct).

Going to close since it's not an Ionic issue, if you have a simple reproduction might be worth opening an issue over at https://github.com/s-panferov/awesome-typescript-loader.

**Comment by tlancina** [comment]
@hunterleaman ah bummer, is there any reason you need it on? I personally don't like atom rewriting it because I've run into issues like this.

**Comment by tlancina** [comment]
Actually, what version of awesome-typescript-loader do you have? If it's not latest, you might want to give the latest a shot.

**Comment by hunterleaman** [comment]
3.3.12

**Comment by jorgeutrilla** [comment]
I´m trying to learn ionic 2 at the moment and I ran into this error, disabling rewriteTsconfig and removing the files section does get it fixed... I´m gratefull to both of you!
