### ISSUE TITLE
How to create a custom base starter?

### ISSUE THREAD

**Issue by dougludlow** [driftyco/ionic-cli#832]
Is it possible to create a custom starter for use with `ionic start` and not use https://github.com/driftyco/ionic2-app-base/?

**Comment by tlancina** [comment]
Not at the moment, could you explain your use case a little?

**Comment by dougludlow** [comment]
Ah, but I'm now seeing https://forum.ionicframework.com/t/attention-upcoming-ionic-2-starter-changes/45058. So it looks like my end goal will be an option eventually.

**Comment by tlancina** [comment]
Hey @dougludlow I'm going to close this as webpack is no longer hardcoded, so you should be able to integrate jspm with either npm scripts or gulp tasks.

I'd love to hear if there are any issues/challenges with using jspm with Ionic and anything we can do/document to make it easier.

**Comment by dougludlow** [comment]
:thumbsup:
