### ISSUE TITLE
iconic install error

### ISSUE THREAD

**Issue by chidinweke** [driftyco/ionic-cli#833]
Short description of the problem:

I tried to install iconic on my system and i'm getting this error...see image for error.

Ho do i solve this
![1error](https://cloud.githubusercontent.com/assets/7816720/13685184/7ccf6e44-e70f-11e5-9f74-b67a43a63907.png)

**Comment by tlancina** [comment]
Hey thanks for the issue, it looks like a proxy problem with npm: ```If you are behind a proxy, please make sure that the network 'proxy' config is set properly.  See: 'npm help config'```.  

Going to close this, but I'd suggest taking a look at the forum: https://forum.ionicframework.com/ if you're still having issues.
