### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#836]
_From @chidinweke on March 10, 2016 16:32_

**Note: for support questions, please use one of these channels:** 
![1error](https://cloud.githubusercontent.com/assets/7816720/13676375/e747158a-e6e5-11e5-8ffd-0ad3fe74a12e.png)

#### Short description of the problem:

I tried to install iconic on my system and i'm getting this error...see image for error.

Ho do i solve this 

_Copied from original issue: driftyco/ionic#5796_

**Comment by jgw96** [comment]
_From @BilelKrichen on March 10, 2016 16:44_

You must publish this issue on this repository
https://github.com/driftyco/ionic-cli/issues

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! As this is an issue related to the ionic cli i am going to be moving this issue to that repo as it could be answered better over there. Please feel free to continue the conversation on this issue in that repo!

**Comment by chidinweke** [comment]
Hello i've not gotten any response for this issue.

**Comment by tlancina** [comment]
Looks like you may need to set up your proxy, see if https://github.com/npm/npm/issues/3354 and http://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy help.
