### ISSUE TITLE
Error NDK Integration is deprecated in the current plugin.

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#837]
_From @gsanjeevkumar on March 9, 2016 19:13_

#### Short description of the problem:
Error in gradle when building ioinic project after adding crosswalk plugin.

#### What behavior are you expecting?
Build normally

**Steps to reproduce:**
1. add crosswalk plugin to a basic ionic project
2. ionic prepare android 
3. ionic build android
4. open the /platforms/android folder with Android Stuido

```
`Error:(185, 0) Error: NDK integration is deprecated in the current plugin.  Consider trying the new experimental plugin.  For details, see http://tools.android.com/tech-docs/new-build-system/gradle-experimental.  Set "android.useDeprecatedNdk=true" in gradle.properties to continue using the current NDK integration.`

Ionic info ( output below )
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.2.1 Build version 7C1002 



_Copied from original issue: driftyco/ionic#5784_

**Comment by jgw96** [comment]
Thanks for submitting an issue with us! As this bug is related to the ionic cli i am going to be moving this issue to that repo. Please feel free to continue this conversation over there!

**Comment by gsanjeevkumar** [comment]
so will there be a solution to this soon

i do the following as of now

`productFlavors {
//            armv7 {
//                versionCode defaultConfig.versionCode + 2
//                ndk {
//                    abiFilters "armeabi-v7a", ""
//                }
//            }
//            x86 {
//                versionCode defaultConfig.versionCode + 4
//                ndk {
//                    abiFilters "x86", ""
//                }
//            }
//            all {
//                ndk {
//                    abiFilters "all", ""
//                }
//            }
//        }`

**Comment by tlancina** [comment]
Is this still an issue if you use the beta version of the CLI? `npm install -g ionic@beta`

**Comment by Kinzi** [comment]
I've got the same problem and changing to beta didn't help unfortunately...

**Comment by jspenc72** [comment]
I am having this issue as well

```bash

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5 
ios-sim version: 3.1.1 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by jspenc72** [comment]
I get this output 
```bash
$ ionic browser add crosswalk
The browser task has been deprecated.
Please use the Cordova Crosswalk plugin instead:

ionic platform add android
ionic plugin add cordova-plugin-crosswalk-webview
```
when adding the crosswalk browser

**Comment by jspenc72** [comment]
After adding the android platform and the cordova-plugin-crosswalk-webview plugin as per the instructions given. I am still getting this error.


![astudio](https://cloud.githubusercontent.com/assets/2913536/14451993/8f5e9a4c-0048-11e6-9219-4419459dc15f.jpg)

**Comment by jspenc72** [comment]
Error:(185, 0) Error: NDK integration is deprecated in the current plugin.  Consider trying the new experimental plugin.  For details, see http://tools.android.com/tech-docs/new-build-system/gradle-experimental.  Set "android.useDeprecatedNdk=true" in gradle.properties to continue using the current NDK integration.
<a href="openFile:/Users/WREAdmin/Desktop/test/crosswalk-test/platforms/android/build.gradle">Open File</a>

**Comment by jspenc72** [comment]
```js
productFlavors { // armv7 { // versionCode defaultConfig.versionCode + 2 // ndk { // abiFilters "armeabi-v7a", "" // } // } // x86 { // versionCode defaultConfig.versionCode + 4 // ndk { // abiFilters "x86", "" // } // } // all { // ndk { // abiFilters "all", "" // } // } // }
```

**Comment by smarquez-dev** [comment]
I found a solution, manually create gradle.properties file and added inside android.useDeprecatedNdk = true

**Comment by jspenc72** [comment]
Can you post a copy of the gradle.properties file you created manually?

**Comment by smarquez-dev** [comment]
Of course only has a line of code.
`android.useDeprecatedNdk=true`
File has be at the root of platforms/android folder.

**Comment by gsanjeevkumar** [comment]
this worked for me. Hope this remains consistent for the future versions too...

**Comment by smarquez-dev** [comment]
Very glad that works for you, there must be a better way. And I guess fix it up in future versions of ionic.

**Comment by tlancina** [comment]
Thanks for the workaround @smarquez-dev, I'm going to close this as it's not something that Ionic needs to fix, rather it's something Cordova could add to cordova-android.

More information: 
https://issues.apache.org/jira/browse/CB-10386
http://markmail.org/message/wpeus6el34dsxcv5

**Comment by Kinzi** [comment]
this worked for me as well. Thanks a lot!

**Comment by kunalmangela** [comment]
File must be in the root of platforms/android folder.
where is this folder is located?
