### ISSUE TITLE
[bug] Lack of IOS icon of 57px and no way to generate it.

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#842]
_From @rafaelmezzomo on January 6, 2016 12:9_

When I try to upload my ionic app to the apple store, I receive an error about lack of app icon of 57px.

I have tried to add a new icon inside `/resources/ios/icon` and add it inside `config.xml`. But when I `ionic build ios` the icon is not added inside `platform/ios`.

To be able to upload I had to manually add the files in Xcode and add them to `my-app-name.plist`. 

_Copied from original issue: driftyco/ionic#4910_

**Comment by jgw96** [comment]
_From @PerfectionCSGO on January 6, 2016 12:48_

Possibly related to this? https://issues.apache.org/jira/browse/CB-10162

**Comment by jgw96** [comment]
_From @rafaelmezzomo on January 11, 2016 13:5_

Thanks @PerfectionCSGO

**Comment by jgw96** [comment]
Hello, thanks for opening this issue with us! As this issue is related to the cli i will be moving this issue over there. Feel free to please continue the conversation over there!

**Comment by jthoms1** [comment]
@rafaelmezzomo I had a followup question on this issue.  Did you run 'ionic resources' before the build?  This command should build out all of the images that you would need.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
