### ISSUE TITLE
Using sidemenu template, no sidemenu

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#846]
_From @amandeepmittal on March 15, 2016 12:0_

I installed `sidemenu` template as per Ionic framework documentation but the template on generating isn't creating any Javascript code for side menu to function in the `app.js` nor it is creating `ion-side-menus` tag itself in the `index.html`.
How can I resolve this? I am using `ionic-CLI`

_Copied from original issue: driftyco/ionic#5843_

**Comment by jgw96** [comment]
Thanks for submitting this issue! As this is more of an issue with the cli i will be moving this issue to that repo. Thanks again!

**Comment by tlancina** [comment]
Could you paste the output of `ionic info` please?
