### ISSUE TITLE
Ionic command won't run

### ISSUE THREAD

**Issue by neilRGS** [driftyco/ionic-cli#847]
Hi 
I have installed as per the instructions, ensured Ant is installed and the JDK, as well as Cordova and ionic. etc...

On trying the example command, `$ionic start todo blank`  all I get is the bland windows CLI error that "'ionic' is not recognized as an internal or external command,
operable program or batch file."

Any ideas please?

TIA

Neil

**Comment by tlancina** [comment]
Hey thanks for the issue, this is probably a better question for the forum: https://forum.ionicframework.com/. I'd try over there to see if anyone else has had a similar problem.
