### ISSUE TITLE
ionic2/tutorial-ionic2/node_modules/angular2/src/facade/promise.d.ts:1:9 Cannot re-export name that is not defined in the module.

### ISSUE THREAD

**Issue by RunningV** [driftyco/ionic-cli#848]
i use ionic start xxx --v2 --ts download the ionic2 project, when i run it the CLI show error:
<pre>ionic2/tutorial-ionic2/node_modules/angular2/src/facade/promise.d.ts:1:9
Cannot re-export name that is not defined in the module.</pre>
the version like this:
<pre>
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
angular Version: 2.0.0-beta.6
OS: Windows 7 SP1
Node Version: v4.4.0
</pre>

i try to add "node_modules/angular2/typings/browser.d.ts" to the tsconfig.json ,it became worse:
<pre>
ERROR in [default] E:/Running/angular2.0/ionic2/tutorialionic2/node_modules/angular2/src/facade/promise.d.ts:1:9
Cannot re-export name that is not defined in the module.

ERROR in [default] node_modules/angular2/typings/browser.d.ts:6:13
Duplicate identifier 'PromiseConstructor'.

ERROR in [default] node_modules/angular2/typings/es6-collections/es6-collections.d.ts:22:4
Duplicate identifier 'done'.

ERROR in [default] node_modules/angular2/typings/es6-collections/es6-collections.d.ts:23:4
Duplicate identifier 'value'.

ERROR in [default] node_modules/angular2/typings/es6-collections/es6-collections.d.ts:46:4
Duplicate identifier 'size'.
</pre>

what's wrong with the ts type of the project?

**Comment by tlancina** [comment]
Hey there, this is https://github.com/angular/angular/issues/6468, and will go away when the version of Angular that Ionic uses gets updated. I believe there's a workaround in https://github.com/angular/angular/issues/6468#issuecomment-176590156 if it helps.

I'll leave this open for anyone else who's having this problem until Ionic updates.

**Comment by keatz55** [comment]
+1

**Comment by nunoarruda** [comment]
Same here: 
<img width="697" alt="screen shot 2016-03-28 at 09 52 14" src="https://cloud.githubusercontent.com/assets/1189149/14069354/251c4f36-f4cb-11e5-9aae-529b2c178ae0.png">
Will wait for Ionic to update the Angular version then...

**Comment by tlancina** [comment]
This should be fixed in beta.4 of the framework.
