### ISSUE TITLE
bug: ionic build ios fails with Apple Watch target

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic-cli#850]
_From @thomaswb on March 20, 2016 21:17_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>- //create a new blank Ionic 2 app
- ionic platform add ios
- ionic build ios // works
- // Xcode > Add target > Apple Watch (WatchOS 2)
- ionic build ios // fails with this error:

=== BUILD TARGET Watch Companion Extension OF PROJECT Companion WITH CONFIGURATION Debug ===

Check dependencies
target specifies product type 'com.apple.product-type.watchkit2-extension', but there's no such product type for the 'iphonesimulator' platform

** BUILD FAILED **</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5893_

**Comment by brandyscarney** [comment]
_From @gylippus on March 21, 2016 16:30_

+1 
I can confirm we have the same issues. It's been so long since we haven't had to use Xcode just to run the app. :+1:

**Comment by brandyscarney** [comment]
_From @jgw96 on March 21, 2016 16:39_

Hello @thomaswb ! Thanks for opening an issue with us! Here is a workaround that will hopefully work for you: run `ionic run ios`, this will fail but the project should be updated. Then you should be able to run the app from xcode directly and it should work. Sorry that this is kinda hacky!

**Comment by brandyscarney** [comment]
_From @jgw96 on March 21, 2016 16:39_

I hope to have a better solution soon

**Comment by thomaswb** [comment]
Thanks for the workaround, Brandy. `ionic build ios` also works, in that it does all the things necessary to then run it in Xcode.

**Comment by brandyscarney** [comment]
@thomaswb The workaround was from @jgw96. I just moved the issue to this repo. :grin: Glad it works for you, though!

**Comment by thomaswb** [comment]
I just updated to Xcode 7.3 and the problem seems to have gone away.

**Comment by jgw96** [comment]
@thomaswb awesome! good to hear!

**Comment by jgw96** [comment]
Hello all! As this issue seems to have been fixed i will be closing this for now. Thanks for using Ionic!
