### ISSUE TITLE
✗ Not found: https://github.com/driftyco/ionic-starter-tutorial/archive/typescript.zip (404)

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic-cli#851]
http://ionicframework.com/docs/v2/getting-started/tutorial/

<img width="697" alt="screen shot 2016-03-22 at 15 04 25" src="https://cloud.githubusercontent.com/assets/1189149/13944370/c23da43a-f03f-11e5-8a75-708426c1843a.png">
<img width="697" alt="screen shot 2016-03-22 at 15 05 43" src="https://cloud.githubusercontent.com/assets/1189149/13944371/c242bdb2-f03f-11e5-8404-0ad46d27e7a8.png">

**Comment by tlancina** [comment]
Whoops, thanks! This should be fixed in the latest beta, you can update with `npm install -g ionic@beta`.
