### ISSUE TITLE
Socket hangup error while initializing ionic project

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#854]
_From @asherdmello on January 11, 2016 7:22_

i am getting socket hangup error while trying to download master.zip from from github 
when trying the command ' ionic start projectName '
please refer the attached screenshot for the same
i am behind a corporate proxy,
i tried downloading master.zip from the browser and could do so successfully, doesnot seem to be my proxy issue though

![image](https://cloud.githubusercontent.com/assets/16643518/12228493/29f67e64-b862-11e5-821b-1df704b3686c.png)

_Copied from original issue: driftyco/ionic#4936_

**Comment by jgw96** [comment]
_From @nusususuzu on January 28, 2016 2:43_

same too on os x
![ekran resmi 2016-01-28 04 42 21](https://cloud.githubusercontent.com/assets/4151349/12633340/94a962d4-c579-11e5-83b4-0740fcc5d259.png)

**Comment by jgw96** [comment]
@nusususuzu are you also behind a proxy?

**Comment by jgw96** [comment]
Since this is more of an issue with the cli and not the framework i am going to be moving this issue to the cli repo, please feel free to continue the conversation over there! Thanks again!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by HenokMillion** [comment]
why do you close threads without giving a solution? I'm still getting the error.

**Comment by dwieeb** [comment]
@HenokMillion This is a very general Node error. Please create a new issue.
