### ISSUE TITLE
Cannot re-export name that is not defined in the module

### ISSUE THREAD

**Issue by zhouhao27** [driftyco/ionic-cli#857]
Get the latest ionic-cli, beta 22. Still got the following error message:

> ERROR in [default] /Users/name/Projects/test/js/demo/node_modules/angular2/src/facade/promise.d.ts:1:9 
Cannot re-export name that is not defined in the module.

After I create a blank new project by:

> ionic start demo blank --v2 --ts

Although it seems not affect the application running.

**Comment by mhartington** [comment]
This is not a CLI error, but a warning from a v2 dependency
