### ISSUE TITLE
security profiles add returns 409 for "similar" tags

### ISSUE THREAD

**Issue by cawoodm** [driftyco/ionic-cli#858]
I noticed some weird behaviour: it is not possible to create 2 profiles "foo" and "foo2":
```
ionic security profiles add foo
ionic security profiles add foo2
```
You get message: "Profile already exists by that tag" status: 409 type: Conflict

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this seems like more of a support question i will urge that you ask this question on our forum (forum.ionicframework.com). Thanks for using Ionic!
