### ISSUE TITLE
Shouldn't `ionic plugin add`also update config.xml?

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic-cli#865]
<img width="739" alt="screen shot 2016-03-28 at 13 33 50" src="https://cloud.githubusercontent.com/assets/1189149/14071674/f1e53bfe-f4e9-11e5-9572-008c1e419c9b.png">
<img width="286" alt="screen shot 2016-03-28 at 13 34 27" src="https://cloud.githubusercontent.com/assets/1189149/14071675/f1e85744-f4e9-11e5-80ab-896cb6d670d0.png">
<img width="493" alt="screen shot 2016-03-28 at 13 34 44" src="https://cloud.githubusercontent.com/assets/1189149/14071676/f1ea6098-f4e9-11e5-8b97-6a0e69aa17ad.png">
Using Ionic CLI 2.0.0-beta.23.

PS: Documentation about the `ionic plugin` command would be useful. Currently there's none in v2 docs:
<img width="146" alt="screen shot 2016-03-28 at 13 39 04" src="https://cloud.githubusercontent.com/assets/1189149/14071716/80d88e60-f4ea-11e5-80c3-02a0bdfa06cc.png">

**Comment by tlancina** [comment]
Yes this is confusing! Originally Cordova didn't save plugins in config.xml, and so Ionic added support for plugin management with the `state` commands.  But now that Cordova does solve the problem in a different way it causes some issues/confusion, so `state` will be deprecated in the 2.0 version of the CLI (or will use Cordova under the hood) in favor of only using config.xml.

**Comment by jgw96** [comment]
Hello all! As it has been a while since there was any activity on this issue i will be closing it for now. Thanks for using Ionic!
