### ISSUE TITLE
Ionic 2 Tutorial Template "not found"

### ISSUE THREAD

**Issue by andreasbhansen** [driftyco/ionic-cli#866]
Hi,

After running ```npm install -g ionic@beta``` to ensure latest version, I tried to start a new Ionic project using the ```$ ionic start myTutorial tutorial --v2``` command<sup>1</sup>. This returns an error:

> Creating Ionic app in folder /[...]/myTutorial based on tutorial project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip
 ✗ Not found: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip (404)
 ✗ Please verify the url and try again.
Please verify you are using a valid URL or a valid ionic starter.
View available starter templates: `ionic templates`
More info available at: 
http://ionicframework.com/getting-started/
https://github.com/driftyco/ionic-cli

Upon inspection, it looks like the ```ionic-starter-tutorial``` template/repo is now called ```ionic2-starter-tutorial```? Is this something you must change internally in the CLI, or is there a quickfix for this?

----

<sup>1</sup>http://ionicframework.com/docs/v2/getting-started/tutorial/

**Comment by andreasbhansen** [comment]
EDIT: Restarted the terminal and it all works fine... Sorry, my fault.

**Comment by JapanYoshi** [comment]
I had this issue too, but restarting didn't work. Turns out, I needed the flag ``--type=ionic-angular``!

**Comment by JapanYoshi** [comment]
I had this issue too, but restarting didn't work. Turns out, I needed the flag ``--type=ionic-angular``!

**Comment by dwieeb** [comment]
@JapanYoshi Thanks, just updated this on our site: https://github.com/ionic-team/ionic-site/commit/9da88cc3be23c60111bd2b0668c6a41559936772

**Comment by swbrenneis** [comment]
You might want to update the tutorial to reflect this also.

[https://ionicframework.com/docs/v3/intro/tutorial/](url)

**Comment by dwieeb** [comment]
Thanks @swbrenneis! Done.
