### ISSUE TITLE
ionic-cli

### ISSUE THREAD

**Issue by anupam42** [driftyco/ionic-cli#867]
![screenshot from 2016-03-28 16 10 53](https://cloud.githubusercontent.com/assets/16332264/14076481/b48594f0-f4ff-11e5-92fc-be5a7cc8e5b7.png)

by removing cordova will it affect any of the changes in npm and nodejs or ionic

**Comment by andrewmcgivery** [comment]
What exactly is the issue here?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Thanks for using Ionic!
