### ISSUE TITLE
bug: Error with CLI v2.0.0-beta.23

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#871]
_From @kuntal-b on March 26, 2016 12:29_

**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Problem described at bellow forum link

https://forum.ionicframework.com/t/error-with-cli-v2-0-0-beta-23/47496</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5950_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is related to the cli and not the framework i will be moving this issue to that repo. Thanks again!

**Comment by tlancina** [comment]
Thanks for the issue, this should be resolved in the latest beta (beta.24).

**Comment by kuntal-b** [comment]
Hi @tlancina 
Today I update to beta 24 and try to start a project 
![untitled](https://cloud.githubusercontent.com/assets/7402233/14273252/d46cf9f2-fb26-11e5-9266-4b39579ea162.png)

and I  wait more then half an hour ,but not procede after download .can you please look into this?
