### ISSUE TITLE
Upgrade from 2.0.0-beta.19 to 2.0.0-beta.23 

### ISSUE THREAD

**Issue by mehrad-rafigh** [driftyco/ionic-cli#875]
Hello everybody,

I am currently facing the issue, that a few things have changed between the versions.
After I deleted the deprecated files and downloaded the new ones, I can't get ionic to serve, build, run or emulate.

The error message I get is this:
     ✗ Caught exception:
     Error: ENOENT: no such file or directory, lstat '/Users/dev/git/my-sample-app/app'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at /Users/dev/git/my-sample-app/node_modules/tsify/index.js:57:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (/Users/dev/git/my-sample-    app/node_modules/tsify/index.js:57:6)
    at DestroyableTransform.<anonymous> (/Users/dev/git/my-sample-app/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7) 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

The issue I think is caused by the fact, that the `app` folder in my sample-app is not called `app`.
Is there anyway I can change this? 

Furthermore:
Since webpack is not used anymore (or is it?), I have to update my index.html right? The problem is, that I have changed every `app` occurence in the new `gulpfile.js` but that did not solve my problem. 
Does anybody had the same issues when they updated to the "new" version of ionic beta?

**Comment by tlancina** [comment]
It could be that you need to configure Browserify to know where to look if you've changed the app files to something other than the default. 

Take a look at either:
  https://github.com/driftyco/ionic-gulp-tasks/tree/master/browserify-typescript#browserifybuildoptions
or 
https://github.com/driftyco/ionic-gulp-tasks/tree/master/browserify-es2015#browserifybuildoptions

So if you renamed `app` to `blah` it would look something like this:

```
gulp.task('build', ['sass', 'html', 'fonts', 'scripts'], function(){
  return buildBrowserify({
    src: ['blah/app.js'] // or ['blah/app.ts', 'main.d.ts']
  });
});
```

**Comment by mehrad-rafigh** [comment]
Thanks for your reply @tlancina. 
I checked out an older version of our project which was using the old dependecies. (ionic-framework instead of ionic-angular and ionic 2.0.0-beta.19.) 
My problem is now that the CLI does warn me, that I should rename my ionic.project into ionic.config.json , but the CLI does not create a gulpfile.js nor the ionic.config.json. 
I looked in this [repo](https://github.com/driftyco/ionic2-app-base/tree/typescript), but I didn't find any ionic.config.json file. Just this [commit of yours](https://github.com/driftyco/ionic2-app-base/commit/0fc0019a09ef0f106a58314bf9f4924e2d806df7). 

Is this a possible bug of the current (2.0.0-beta.23) CLI?

**Comment by Artfloriani** [comment]
I'm having a similar issue. 

Upgrading from 2.0.0-beta.19 to beta.23 does not build my project anymore. `ionic serve` does work but it runs the same version of the project, any changes are not considered. 

@mehrad-rafigh When you do a 'ionic start nameapp --v2 --ts' it will create a ionic.config.json which looks like this:

```
{
  "name": "nameapp ",
  "app_id": "",
  "v2": true,
  "typescript": true
}
```

**Comment by mehrad-rafigh** [comment]
@Artfloriani thanks for your message. I actually solved the problem just like you :)
BTW if you want to run `ionic build` you should add `gulp.task('build:before', ['build']);` like mentioned [in this issue](https://github.com/driftyco/ionic-cli/issues/879)

**Comment by tlancina** [comment]
Hey all I'm going to close this and point people to https://forum.ionicframework.com/t/ionic-2-projects-updating-to-beta-4/ for help with updating.
