### ISSUE TITLE
Add a gulp build:before task

### ISSUE THREAD

**Issue by kelvindart** [driftyco/ionic-cli#879]
At the moment, the following build tasks are defined:

    gulp.task('serve:before', ['watch']);
    gulp.task('emulate:before', ['build']);
    gulp.task('deploy:before', ['build']);

This is great if you use `ionic serve`, `ionic emulate` or `ionic deploy` respectively. However, I find myself working with the IDEs, so tend to use `ionic build` often and as a result, my HTML components are not built.

If I weren't too familiar with Ionic 2, it could have caused a headache trying to debug the reason why :).

May I suggest adding `gulp.task('build:before', ['build']);` to the default `before` hooks, so `ionic build` triggers the HTML components be built?

**Comment by dylanvdmerwe** [comment]
Similar issue to this? https://github.com/driftyco/ionic-gulp-tasks/issues/2

**Comment by kelvindart** [comment]
Good spot - exactly that :)

**Comment by tlancina** [comment]
Should be updated in the starters, thanks!

**Comment by magician03** [comment]
Hi,

This is not working in Ionic v3. How to enable it ?? Earlier it used to work in Ionic v3.

**Comment by dwieeb** [comment]
@magician03 -> https://github.com/driftyco/ionic-cli/issues/1989

Not a feature yet, unfortunately.
