### ISSUE TITLE
ionic build ios --device does not produce ipa

### ISSUE THREAD

**Issue by MSLaguana** [driftyco/ionic-cli#883]
Creating a new ionic project and attempting to `ionic build ios --device` or `cordova build ios --device` succeeds but there is no `.ipa` file in `platforms/ios/build/device`, however creating a new cordova project and doing a cordova build does produce an ipa file.

Ionic info:
```
Your system information:
Cordova CLI: 6.1.0 (cordova-lib@undefined)
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.4.1
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by tlancina** [comment]
Does this work with the beta of the CLI? `npm install -g ionic@beta`

**Comment by MSLaguana** [comment]
Looks like the issue was actually an outdated version of cordova-ios (possibly used by ionic by default) and not an issue with ionic itself. Apologies for the confusion.
