### ISSUE TITLE
ionic2's serve opens three tabs in my browser

### ISSUE THREAD

**Issue by bel3atar** [driftyco/ionic-cli#887]
The first has : http/
The second: file:///localhost
The third: 0.0.31.164

I am running Linux with no DM.

**Comment by tlancina** [comment]
Woah weird, any steps to reproduce?

**Comment by bel3atar** [comment]
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.22
Ionic App Lib Version: 2.0.0-beta.12
OS: /bin/sh: lsb_release: command not found 
Node Version: v5.10.0

**Comment by tlancina** [comment]
Thanks, what flavor of Linux are you using?

**Comment by bel3atar** [comment]
@tlancina Arch + i3wm with this https://github.com/march-linux/mimi if it makes any difference

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by bel3atar** [comment]
same issue with 2.0.0-beta.32
