### ISSUE TITLE
Caught exception undefined

### ISSUE THREAD

**Issue by mareczek** [driftyco/ionic-cli#890]
<img width="449" alt="screen shot 2016-04-01 at 15 52 28" src="https://cloud.githubusercontent.com/assets/791743/14208871/d6270254-f821-11e5-90ed-090c05832942.png">

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
