### ISSUE TITLE
ENOENT spawn error with ionic start

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#892]
_From @Bandito11 on April 2, 2016 2:8_

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
I upgraded to beta.23 and started to get an error when created a new project using 'ionic start foo --v2 --ts'.
The error in red says 
"Unable to spawn commandError: spawn npm ENOENT (CLI v2.0.0-beta.23)."

I don't even know what it did to the project. 
#### What behavior are you expecting?

**Steps to reproduce:**
1. ionic start foo --v2 --ts
2. it builds and creates the proyect
3. 

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

_Copied from original issue: driftyco/ionic#6018_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since this is an issue related to the ionic cli and not the framework i will be moving this issue to that repo. Feel free to continue the conversation over there! Thanks!

**Comment by Bandito11** [comment]
I think I solved it. I had python2 and python3 installed so after I deleted that everything was solved.

**Comment by Bandito11** [comment]
I think this should be added to the documents even though I think this pertains node and not the ionic cli

**Comment by jgw96** [comment]
@Bandito11 what version of nodejs are you using? You shouldn't have to uninstall python to be able to use the ionic cli.

**Comment by Bandito11** [comment]
I have the latest one. I uninstalled and installed everything yesterday because I've been using ASP.Net and Python3 (already had Python 2 installed) for college since January and wanted to have the latest npm and node. When I was 'ionic start'-ing the project it was mentioning that python 3 was in the path (don't remember what else it said) so I deleted python 3 and everything was fixed. 

I am using the latest ionic@beta too. It isbeta23

**Comment by jgw96** [comment]
Hmm, ok, thanks for the info! I will have to look more into this.

**Comment by dylanvdmerwe** [comment]
This error is happening on my side and I have not installed Python.

**Comment by tlancina** [comment]
The npm install task originally used `exec` to run `npm install`, which was sometimes [caused issues](https://github.com/driftyco/ionic-app-lib/issues/77) so it was switched to spawn, which doesn't work/works differently on Windows.

Switched to using https://github.com/IndigoUnited/node-cross-spawn in the latest beta, so this should be resolved, but let me know if you're still having issues, thanks!
