### ISSUE TITLE
If ionic.config.js has been deprecated why generate/download it when starting a project with `ionic start`?

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic-cli#893]
<img width="697" alt="screen shot 2016-04-03 at 19 00 31" src="https://cloud.githubusercontent.com/assets/1189149/14231875/d245d788-f9ce-11e5-97f2-ac94810ed68d.png">

**Comment by tlancina** [comment]
Great question, it's because older versions of the CLI will mysteriously fail without it, so it's in there to print an upgrade message.
