### ISSUE TITLE
Error postinstall: `node lib/tasks/postinstall`

### ISSUE THREAD

**Issue by warner-pinz** [driftyco/ionic-cli#896]
`$: sudo npm install -g ionic@beta`

`npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@beta"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! ionic@2.0.0-beta.23 postinstall: `node lib/tasks/postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic@2.0.0-beta.23 postinstall script 'node lib/tasks/postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/tasks/postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/codapay/Tools/temp/npm-debug.log
npm ERR! code 1
`

**Comment by tlancina** [comment]
Hey thanks for the issue, can you try installing again? The postinstall script has been removed in beta.24.
