### ISSUE TITLE
ionic 2 starter app fails to serve

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic-cli#899]
I can't get freshly generated app to serve for some reason. I have an older MyIonic2Tutorial app generated about 2 weeks ago that serves fine but not the newest one. After running `ionic serve` command ionic cli exits to command prompt.

Steps to recreate: 
1. Generate new sample app `ionic start test --v2 --ts`
2. After install is done `cd test`
3. Run `ionic serve`
4. Observe the app not lunch in the browser

Here is the console output:
```
mbp:test admuser$ ionic serve
WARN: ionic.config.js has been deprecated, you can remove it.

Running 'serve:before' gulp task before serve
[17:50:40] Starting 'clean'...
mbp:test admuser$ 

```

Here is my setup:
```
Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v4.4.1
Xcode version: Xcode 7.3 Build version 7D175 
```

**Comment by okonon** [comment]
also when i run `ionic run ios --device` i am seeing same behaviour the cli just exits after `clean` task

**Comment by okonon** [comment]
Package.json compare:
![screen shot 2016-04-04 at 6 02 29 pm](https://cloud.githubusercontent.com/assets/1832398/14265463/8e174ab2-fa8f-11e5-9ce1-9401f176d084.png)

**Comment by okonon** [comment]
I think i am getting closet to pinpointing what might be the problem. If i copy an older version of gulpfile.js to new projects all tasks are starting to run, if i revert the changes all tasks fail
There is someting here that is causing this issue:
![screen shot 2016-04-04 at 6 12 11 pm](https://cloud.githubusercontent.com/assets/1832398/14265702/02468b18-fa91-11e5-88d1-8504daed8afb.png)

**Comment by okonon** [comment]
It seems `clean` task is the problem. If i remove it from all tasks they execute fine:
![screen shot 2016-04-04 at 6 12 11 pm](https://cloud.githubusercontent.com/assets/1832398/14265967/d071c7b8-fa92-11e5-990f-0ddd3f65dc6d.png)

**Comment by nunoarruda** [comment]
Same here. `ionic serve` fails with Ionic CLI Version: 2.0.0-beta.24
<img width="697" alt="screen shot 2016-04-05 at 09 09 19" src="https://cloud.githubusercontent.com/assets/1189149/14267744/309a34a6-fb0e-11e5-8672-0c30761b3bdb.png">

**Comment by tlancina** [comment]
Thanks for the issue, sorry about that! The conference app was using version 1.1.1 of `del` (used by the clean task) which uses callbacks, whereas the rest of the starters have `del` 2.2.0, which returns a promise.

I've updated the starter base accordingly, so this should be resolved in new projects.  You can edit your existing gulpfile with the fix if it's easier: https://github.com/driftyco/ionic2-app-base/commit/6c62972044482d2602a5ac759f974ad83785905b.
