### ISSUE TITLE
input Date doesn't show widget on chrome desktop

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ionic-cli#900]
Plz find all the details here

https://forum.ionicframework.com/t/problem-with-date-picker-when-viewing-in-a-desktop-browser/20943

**Comment by jgw96** [comment]
Hello! As this issue is an issue with the Ionic framework and not the Ionic-cli i will be moving this issue to the correct repo. Feel free to continue the discussion over there!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic#6406
