### ISSUE TITLE
Caught Exception: Error: watch null EPERM

### ISSUE THREAD

**Issue by ct14it** [driftyco/ionic-cli#901]
node v4.4.2
npm 3.8.5
ionic 2.0.0-beta.24
cordova 6.1.1

**Replicate**
```
ionic start TabsTest tabs --v2
ionic serve
make a change to a HTML file (e.g. app/pages/page1/page1.html)
```

ionic serve process shows multiple of the following

```
Caught exception:
 Error: watch null EPERM
    at exports._errnoException (util.js:870:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1217:21)
```

**Comment by jorgeutrilla** [comment]
I´m getting this same error, had to 'q' and do 'ionic serve' on every html modification.

**Comment by tlancina** [comment]
Can you post your gulpfile please? There was a bug in the updates to the gulpfile from yesterday

**Comment by ct14it** [comment]
`gulpfile.js`

```
var gulp = require('gulp'),
    gulpWatch = require('gulp-watch'),
    del = require('del'),
    argv = process.argv;


/**
 * Ionic hooks
 * Add ':before' or ':after' to any Ionic project command name to run the specified
 * tasks before or after the command.
 */
gulp.task('serve:before', ['watch']);
gulp.task('emulate:before', ['build']);
gulp.task('deploy:before', ['build']);
gulp.task('build:before', ['build']);

// we want to 'watch' when livereloading
var shouldWatch = argv.indexOf('-l') > -1 || argv.indexOf('--livereload') > -1;
gulp.task('run:before', [shouldWatch ? 'watch' : 'build']);

/**
 * Ionic Gulp tasks, for more information on each see
 * https://github.com/driftyco/ionic-gulp-tasks
 *
 * Using these will allow you to stay up to date if the default Ionic 2 build
 * changes, but you are of course welcome (and encouraged) to customize your
 * build however you see fit.
 */
var buildBrowserify = require('ionic-gulp-browserify-es2015');
var buildSass = require('ionic-gulp-sass-build');
var copyHTML = require('ionic-gulp-html-copy');
var copyFonts = require('ionic-gulp-fonts-copy');
var copyScripts = require('ionic-gulp-scripts-copy');

gulp.task('watch', ['sass', 'html', 'fonts', 'scripts'], function(){
  gulpWatch('app/**/*.scss', function(){ gulp.start('sass'); });
  gulpWatch('app/**/*.html', function(){ gulp.start('html'); });
  return buildBrowserify({ watch: true });
});

gulp.task('build', ['sass', 'html', 'fonts', 'scripts'], buildBrowserify);
gulp.task('sass', ['clean'], buildSass);
gulp.task('html', ['clean'], copyHTML);
gulp.task('fonts', ['clean'], copyFonts);
gulp.task('scripts', ['clean'], copyScripts);
gulp.task('clean', function(){
  return del('www/build');
});
```

**Comment by tlancina** [comment]
Thanks! If you run `npm install run-sequence` and change your gulpfile to this:

```
var gulp = require('gulp'),
    gulpWatch = require('gulp-watch'),
    del = require('del'),
    runSequence = require('run-sequence'),
    argv = process.argv;


/**
 * Ionic hooks
 * Add ':before' or ':after' to any Ionic project command name to run the specified
 * tasks before or after the command.
 */
gulp.task('serve:before', ['watch']);
gulp.task('emulate:before', ['build']);
gulp.task('deploy:before', ['build']);
gulp.task('build:before', ['build']);

// we want to 'watch' when livereloading
var shouldWatch = argv.indexOf('-l') > -1 || argv.indexOf('--livereload') > -1;
gulp.task('run:before', [shouldWatch ? 'watch' : 'build']);

/**
 * Ionic Gulp tasks, for more information on each see
 * https://github.com/driftyco/ionic-gulp-tasks
 *
 * Using these will allow you to stay up to date if the default Ionic 2 build
 * changes, but you are of course welcome (and encouraged) to customize your
 * build however you see fit.
 */
var buildBrowserify = require('ionic-gulp-browserify-es2015');
var buildSass = require('ionic-gulp-sass-build');
var copyHTML = require('ionic-gulp-html-copy');
var copyFonts = require('ionic-gulp-fonts-copy');
var copyScripts = require('ionic-gulp-scripts-copy');

gulp.task('watch', ['clean'], function(done){
  runSequence(
    ['sass', 'html', 'fonts', 'scripts'],
    function(){
      gulpWatch('app/**/*.scss', function(){ gulp.start('sass'); });
      gulpWatch('app/**/*.html', function(){ gulp.start('html'); });
      buildBrowserify({ watch: true }).on('end', done);
    }
  );
});

gulp.task('build', ['clean'], function(done){
  runSequence(
    ['sass', 'html', 'fonts', 'scripts'],
    function(){
      buildBrowserify().on('end', done);
    }
  );
});
gulp.task('sass', buildSass);
gulp.task('html', copyHTML);
gulp.task('fonts', copyFonts);
gulp.task('scripts', copyScripts);
gulp.task('clean', function(){
  return del('www/build');
});
```

does it work?

**Comment by ct14it** [comment]
Indeed it does! Cheers Tim

**Comment by tlancina** [comment]
Great! Sorry about that, should be fixed for new projects.  Going to close this, but let me know if you're still having issues, thanks!

**Comment by jorgeutrilla** [comment]
Well, I did those two things and it asked me to install 'ionic-gulp-browserify-es2015' with npm... after doing that I cannot do ionic serve, I get an error message telling me that it cant find app.js:

C:\Users\jorge.utrilla\Desktop\Prjs\IDi\VisitApp\Dev\VisitApp.Mobile\app>ionic serve

Running 'serve:before' gulp task before serve
[18:41:22] Starting 'clean'...
[18:41:22] Finished 'clean' after 42 ms
[18:41:22] Starting 'watch'...
[18:41:22] Starting 'sass'...
[18:41:22] Starting 'html'...
[18:41:22] Starting 'fonts'...
[18:41:22] Starting 'scripts'...
[18:41:22] Finished 'scripts' after 85 ms
[18:41:22] Finished 'html' after 147 ms
[18:41:22] Finished 'fonts' after 204 ms
[18:41:24] Finished 'sass' after 1.71 s
Error: Cannot find module 'C:\Users\jorge.utrilla\Desktop\Prjs\IDi\VisitApp\Dev\VisitApp.Mobile\app\app.js' from 'C:\Users\jorge.utrilla\Desktop\Prjs\IDi\VisitApp\Dev\VisitApp.Mobile'

**Comment by renanaraujo** [comment]
@tlancina I'm getting this error using this gulpfile:

> 
> ionic $ module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module 'ionic-gulp-browserify-es2015'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (D:\ionic\teste\core\gulpfile.js:30:23)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)

**Comment by xkris6x** [comment]
help

There is an error in your gulpfile: 
Error: /home/project/web/nodeJS/proyecto/app1/node_modules/node-sass/vendor/linux-x64-48/binding.node: failed to map segment from shared object: Operation not permitted
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/project/web/nodeJS/proyecto/app1/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
