### ISSUE TITLE
promise is not defined     at LazyResult.async

### ISSUE THREAD

**Issue by ddarthp** [driftyco/ionic-cli#903]
just following this:
http://ionicframework.com/docs/v2/getting-started/installation/
I got this

![screen shot 2016-04-05 at 1 48 46 p m](https://cloud.githubusercontent.com/assets/6019186/14294192/670231ca-fb35-11e5-8a10-d3a6db1821d9.png)

**Comment by tlancina** [comment]
Thanks for the issue, could you post the output of `ionic info` please?

**Comment by oytuntez** [comment]
I encountered the same problem. Ionic was giving version conflicts with my `node`, so I upgraded nodeJS to the latest (5.11 at the moment) and then issued `npm rebuild` in my Ionic project. Then the problem was gone.

**Comment by tlancina** [comment]
Thanks for the workaround @oytuntez.

I believe this is only a problem if you're using node 0.10, which we don't support. I'm going to close this, but feel free to comment if you're still having issues/feel that this isn't the case, thanks!

**Comment by ken-courville-bds** [comment]
Saw this same issue with Node v6.0.0, Ionic 2.0.0-beta.25.

One work-around is to add this to the top of `gulpfile.js`

`require('es6-shim');`
