### ISSUE TITLE
Discuss: Deprecate/Remove state command

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-cli#904]
The state command was created to manage Cordova plugins before it was supported in Cordova. Cordova now manages plugins and platforms in config.xml: https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html so there is a decent amount of confusion between the Ionic and Cordova behavior.  As Cordova platforms and plugins are not an Ionic concern, let's deprecate the state command and document the existing Cordova command workflow, ie `plugin add --save`.

**Comment by jakub-g** [comment]
There's even a [SO question](http://stackoverflow.com/questions/33830058/package-json-vs-config-xml-for-cordova-plugins) about the topic so yes, indeed there's many people confused what to choose (and probably doubly confused when different team members are mixing cordova and ionic commands)

**Comment by dgproductions88** [comment]
Yesterday, i've installed new ionic CLI beta version and facing the same issue when trying to compile an ionic 1 code version...

**Comment by tlancina** [comment]
Closing in favor of https://github.com/driftyco/ionic-cli/issues/1324.
