### ISSUE TITLE
Improve tooling in ionic-cli repo

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic-cli#907]
- [x] eslint
- [ ] CI
- [x] changelog generation
- [x] automate GH release/tags

**Comment by ct14it** [comment]
May I ask how eslint fits in with the ionic toolset?

**Comment by tlancina** [comment]
Hey @ct14it this is for the ionic-cli repo, not as part of the tool itself, sorry for the possible confusion.

**Comment by ct14it** [comment]
Got ya, cheers

**Comment by tlancina** [comment]
@jthoms1 what's the plan for CI? Does it still need to be added for v2 or is this good to close?
