### ISSUE TITLE
Error with CLI v2.0.0-beta.24, start command fails for sidemenu projects

### ISSUE THREAD

**Issue by kuntal-b** [driftyco/ionic-cli#908]
Today I update to beta 24 and try to start a project 
![d46cf9f2-fb26-11e5-9266-4b39579ea162](https://cloud.githubusercontent.com/assets/7402233/14306002/1521400c-fbe0-11e5-9375-5dbd73797c38.png)

and I wait more then half an hour ,but not procede after download .can you please look into this?some times 2nd download not even start .

**Comment by tlancina** [comment]
Does running it with --skip-npm cause any change in behavior?

**Comment by kuntal-b** [comment]
try with 
`ionic start sample sidemenu --skip-npm --v2 --ts`
wait for 15 minute 

![untitled](https://cloud.githubusercontent.com/assets/7402233/14307036/ca161498-fbe9-11e5-88fc-aad2a5aaa22c.png)

**Comment by ct14it** [comment]
Posted this on the forums, but just to add here, I am having the same issues on W10 and OSX. The tabs starter app is fine, it just affects the sidemenu one.

**Comment by hazeeb** [comment]
I'm experiencing same issue. 
Version :2.0.0-beta.24

**Comment by tlancina** [comment]
Hey thanks for the issue, it seems to be a problem with the unzip2 library, for some reason it doesn't like unzipping the sidemenu starter.

**Comment by TobiasSchaeuble** [comment]
How to fix it? I'm still not able to start the sidemenu proj. ....

**Comment by kuntal-b** [comment]
any update?

**Comment by tlancina** [comment]
This should be fixed in the latest beta.
