### ISSUE TITLE
ionic state reset:  Referencing a plugin that doesn't exist causes exception in Ionic CLI Version: 2.0.0-beta.24

### ISSUE THREAD

**Issue by spikehardin** [driftyco/ionic-cli#914]
If a plugin is not found (returns 404), ionic CLI throws an exception on ionic state reset rather than passing along the error message from cordova.
```
ionic state reset
WARN: ionic.config.js has been deprecated, you can remove it.
WARN: ionic.config.js has been deprecated, you can remove it.
Removed platforms and plugins
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-statusbar
cordova plugin add ionic-plugin-keyboard
cordova plugin add org.apache.cordova.network-information
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

cordova plugin add org.apache.cordova.network-information
Error: Registry returned 404 for GET on https://registry.npmjs.org/org.apache.cordova.network-information
```

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.3
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!

**Comment by surya474** [comment]
can any body tell me how to solve this issue i am also getting 
"Error: Registry returned 404 for GET on https://registry.npmjs.org/org.apache.cordova.network-information"    
 error while trying to add network plug-in
