### ISSUE TITLE
Updating my proyect  to ionic2.0.0-beta.24

### ISSUE THREAD

**Issue by chnoelx** [driftyco/ionic-cli#917]
## I updated from ionic2.0.0-beta.19 to ionic2.0.0-beta.24,after exc ionic serve
Would you like to download the default gulpfile? Yes
Downloading default gulpfile from: https://raw.githubusercontent.com/driftyco/ionic2-app-base/typescript/gulpfile.js
Successfully downloaded gulpfile.

Now installing npm packages used by the gulpfile: 
    gulp gulp-watch del run-sequence ionic-gulp-browserify-typescript ionic-gulp-sass-build ionic-gulp-html-copy ionic-gulp-fonts-copy ionic-gulp-scripts-copy

Npm packages installed successfully. Try running 'serve' again.

### and ex ionic serve and get :::::::::::::::

app/theme/app.ios.scss
Error: File to import not found or unreadable: ionic.ios
       Parent style sheet: stdin
        on line 19 of stdin
>> @import "ionic.ios";
   ^

[10:24:45] Finished 'sass' after 174 ms
[10:24:45] Finished 'html' after 288 ms
Caught exception:
 Error: ENOENT: no such file or directory, lstat '/home/mchavarria/CambioVersion/leybookV2/app/app.ts'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at /home/mchavarria/CambioVersion/leybookV2/node_modules/tsify/index.js:57:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (/home/mchavarria/CambioVersion/leybookV2/node_modules/tsify/index.js:57:6)
    at DestroyableTransform.<anonymous> (/home/mchavarria/CambioVersion/leybookV2/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7) 

#### INFO
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Fedora Description:	Fedora release 22 (Twenty Two) 
Node Version: v5.7.0

**Comment by tlancina** [comment]
Thanks for the issue, are you using TypeScript? And if yes, did you move/rename your app/app.ts file?

**Comment by chnoelx** [comment]
Thanks.But I don't using TypeScript only JavaScript

**Comment by tlancina** [comment]
Hmm, could you post the output of `ionic info` please?

**Comment by chnoelx** [comment]
Cordova CLI: 6.0.0
Gulp version: CLI version 1.2.1
Gulp local: Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID: Fedora Description: Fedora release 22 (Twenty Two) 
Node Version: v5.7.0

**Comment by iignatov** [comment]
@chnoelx it seems that for some reason you received the TypeScript version of the file `gulpfile.js`.

I guess that upgrading your project to use the latest framework following [this upgrade guide for `beta.4`](https://forum.ionicframework.com/t/ionic-2-projects-updating-to-beta-4/49054) might solve your problem _(just make sure to select the JS versions of the files referenced there)_.

Since you're upgrading from an older version you may need to perform few additional steps _(in case that something is not working after the upgrade check out the breaking changes sections in the [changelog](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md) and perform the required updates)_.

**Comment by jgw96** [comment]
Hello @chnoelx are you still having this issue? Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
