### ISSUE TITLE
ionic cli v2.beta.24 start stalls with sidemenu option

### ISSUE THREAD

**Issue by leifwells** [driftyco/ionic-cli#919]
After updating to ionic cli 2.beta.24, I was attempting to create a sidemenu project to migrate my beta.3 code into and the process completely stalled in my terminal:

`leifwells$ ionic start MyIonic2ProjectSideMenuB4 sidemenu --v2 --ts
Creating Ionic app in folder /Users/leifwells/Code/ionic2/MyIonic2ProjectTabsB4/MyIonic2ProjectSideMenuB4 based on sidemenu project
Downloading: https://github.com/driftyco/ionic2-app-base/archive/typescript.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/typescript.zip
[=============================]  100%  0.0s`

My node version:

`leifwells$ node -v
v4.2.6
`

I've reinstalled the cli and tried again without change. 

Installing a tabs starter worked fine.

**Comment by tlancina** [comment]
Hey thanks for the issue, going to close as a dup of https://github.com/driftyco/ionic-cli/issues/908. I just updated the title of that issue to more accurately reflect the problem (since the title was vague).

This should be fixed in the next beta release.
