### ISSUE TITLE
Feat: ionic start from Plunker code

### ISSUE THREAD

**Issue by voliva** [driftyco/ionic-cli#92]
Personally I find that Plunker is better than Codepen, specially for normal-small sized screens (4 views...) and more than 3-file apps (I really rather having separate files, each one with a single responsibility, that all messed up into one JS, one HTML and one CSS that I probably won't use).

Is it possible to port the `ionic start` from Codepen URL feature to make it also use a Plunker URL?

**Comment by jbavari** [comment]
This would be a helpful feature for sure. I'm not sure why it wasnt implemented when codepen was added, to be honest.

As far as priority goes, I've got other issues to tend to before tackling this.

I'd love any help you'd have to offer on it. I accept PRs. :)

**Comment by jbavari** [comment]
@voliva The creator of Plnkr has given us an endpoint to download the apps to create starters with. This is being addressed in issue #299.

**Comment by voliva** [comment]
Awesome!

When you closed this issue i thought you were not going to do this, so I
forked ionic-cli and tried.

I have it unfinished, and I wans't using the .zip endpoint.... I had some
trouble with folder structure and file renaming.
El dia 13/03/2015 17:06, "Josh Bavari" <notifications@github.com> va
escriure:

**Comment by jbavari** [comment]
@voliva - we'll get it knocked out. Thanks for the attempt though! I'd love some help testing it, if you're up to it.

**Comment by voliva** [comment]
Sure! Thanks for the work!

I will follow #299
El dia 13/03/2015 18:07, "Josh Bavari" <notifications@github.com> va
escriure:
