### ISSUE TITLE
adb command failed with exit code null when emulate or run

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#922]
_From @swizardlv on April 11, 2016 1:15_

**Note: for support questions, please use one of these channels:** 

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
sometimes when run 'ionic emulate android ' or 'ionic run android' 

```
swizard@swizarddeMacBook-Pro:~/ws/rwworks/rich_mobile
>ionic emulate android
Running command: /Users/swizard/ws/rwworks/rich_mobile/hooks/after_prepare/010_add_platform_class.js /Users/swizard/ws/rwworks/rich_mobile
add to body class: platform-android
ANDROID_HOME=/Users/swizard/Documents/dev/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
Error: adb: Command failed with exit code null
```
it can be fixed only restart the system.

#### What behavior are you expecting?
the ionic emulate and run can be called successfully.

**Steps to reproduce:**
no steps to reproduce.

Where can I find the debug information?

```
insert any relevant code between the above and below backticks
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x 

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/jnOrQRtE8rN2WCXDQYQY?p=info

**For Ionic 2 issues** - http://plnkr.co/edit/TW20lftdc5s622pcJPkp?p=info

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
```
> ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v5.2.0
Xcode version: Xcode 7.2.1 Build version 7C1002
```

_Copied from original issue: driftyco/ionic#6111_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! So since this issue is more related to the cli and not the framework i will be moving this issue to that repo. Feel free to continue the conversation there! Thanks again!

**Comment by swizardlv** [comment]
Thanks @jgw96 !

**Comment by jgw96** [comment]
@swizardlv No problem!

**Comment by PhilHuot** [comment]
Having the same problem. @swizardlv you are saying that it happens only sometimes? Did you found any patterns to reproduce the bug or workarounds to make it work?

**Comment by swizardlv** [comment]
@PhilHuot haven't find the pattern. I tried to kill adb process and not work at all. The only work around is restarting the os.

**Comment by AllenConquest** [comment]
I don't know if this will help anyone. But I was having the exact same error. I couldn't kill adb and I couldn't restart it. After searching for some time I came up with people who had the same issue because other software was using a different version of adb (this only started happening after I upgraded to the latest Android Studio). So I started hunting through my machine.

It turned out that GapDebug was using an old version of adb and that was running in the background. Once I closed GapDebug the error went away. People suggested replacing adb in the application with the problem, but I've not bothered trying that at the moment, as I don't actually use GapDebug anyway.

**Comment by PhilHuot** [comment]
That's exactly what was happening to me. I closed GapDebug and adb is working just fine now. Thank you very much @AllenConquest.

**Comment by AllenConquest** [comment]
@PhilHuot glad I could help :

**Comment by swizardlv** [comment]
Thanks @AllenConquest, I am also using the gapdebug. I will try when meeting the issue again.

**Comment by jgw96** [comment]
@swizardlv Hey! Are you still having this issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by mbrookson** [comment]
I just had this issue and it is 100% something related to GapDebug as @AllenConquest says. If it is running then the error occurs, but as soon as I quit the GapDebug program the adb error no longer happens and everything runs fine
