### ISSUE TITLE
build error  

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#923]
_From @spiritelf on April 9, 2016 13:51_

Execution failed for task ':CordovaLib:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

_Copied from original issue: driftyco/ionic#6098_

**Comment by jgw96** [comment]
Hello! As this issue is more related to the ionic cli and not the framework itself i will be moving this issue over to that repo. Thanks!

**Comment by jgw96** [comment]
Hello @spiritelf ! Are you still having this issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by spiritelf** [comment]
ok thanks
