### ISSUE TITLE
Ionic app works in browser but not Android.

### ISSUE THREAD

**Issue by trb143** [driftyco/ionic-cli#924]
Build a basic app based around the Tutorial app and it works fine using ionic serve.

If I build and deploy to an android device it get a white screen and nothing.
Using chrome://inspect I have the following error

Uncaught TypeError: undefined is not a function   in collection.ts : 44

I am running the latest version of Ionic 2.

How can I find out what is wrong?

**Comment by delmotte** [comment]
same issue for me ... Did someone solve it ?

**Comment by wli** [comment]
@delmotte check out this thread: https://github.com/driftyco/ionic-cli/issues/898 You may need to install Crosswalk for this to work.

**Comment by jgw96** [comment]
Hello all! What version of android are you all having the issue with?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by chandelkushal5** [comment]
Hi jgw96 ,
i am facing the same issue with android version 6.0.1.showing white screen after splash to home page.

**Comment by marvinug** [comment]
I am having problems with any version of android, it does not even open me to the white screen it stays black and it tells me that after a while the app does not respond.
But in chrome it runs great and does not give me any mistakes.
Help please I've been stuck for several days and I do not get anywhere
