### ISSUE TITLE
Ionic2 start stuck for sidemenu template

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#927]
_From @mlaffargue on April 11, 2016 20:59_

#### Short description of the problem:
Using `ionic start myapp tabs --v2` works correctly
Using `ionic start myapp sidemenu` works correctly
Using `ionic start myapp sidemenu --v2` just get stuck after logging :

> $ ionic start myapp sidemenu --v2
>Creating Ionic app in folder C:\xxxxxx\myapp based on sidemenu project
>Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
>Downloading: https://github.com/driftyco/ionic2-starter-sidemenu/archive/master.zip

#### What behavior are you expecting?
I'm expecting the v2 template of sidemenu to work

**Steps to reproduce:**
1. `ionic start myapp sidemenu --v2`

**Which Ionic Version?**
Ionic CLI  v2.0.0-beta.24

_Copied from original issue: driftyco/ionic#6123_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue! Since this issue is more relevant to the ionic cli and not the framework i will be moving this issue to that repo. Thanks again!

**Comment by jthoms1** [comment]
Thanks for reporting this issue.  Sidemenu v2 has an empty zip file within it and is causing our zip library some issues. We have just merged a pull request to fix it and should be pushing a release tomorrow.

Thanks!

PR: driftyco/ionic-app-lib#87

**Comment by jenshelderweirdt** [comment]
Any idea when the new release will be pushed?

**Comment by NiltonFelicio** [comment]
Any news on this? There was a correction?

**Comment by tlancina** [comment]
Hey apologies for the delay, beta.25 should be out now.

**Comment by jenshelderweirdt** [comment]
Yes indeed. Thanks!
