### ISSUE TITLE
V2: ionic serve: exception when creating new folder inside www

### ISSUE THREAD

**Issue by bgse** [driftyco/ionic-cli#928]
My setup, ionic@beta => 2.0.0-beta.24:

  "dependencies": {
    "angular2": "2.0.0-beta.13",
    "es6-promise": "3.0.2",
    "es6-shim": "^0.35.0",
    "ionic-angular": "2.0.0-beta.4",
    "ionic-native": "^1.1.0",
    "ionicons": "3.0.0-alpha.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "zone.js": "0.6.6"
  },
  "devDependencies": {
    "del": "2.2.0",
    "gulp": "3.9.1",
    "gulp-watch": "4.3.5",
    "ionic-gulp-browserify-typescript": "^1.0.0",
    "ionic-gulp-fonts-copy": "^1.0.0",
    "ionic-gulp-html-copy": "^1.0.0",
    "ionic-gulp-sass-build": "^1.0.0",
    "ionic-gulp-scripts-copy": "^1.0.0",
    "run-sequence": "1.1.5"
  }

Steps to reproduce:

1. create new blank v2 project (--v2 --ts)
2. run 'ionic serve --lab'
3. create folder inside 'www', and rename it 'img'
4. put image in folder (probably not necessary to repro)

----------------------------------------------------
File changed: www/Unbenannter Ordner/
Caught exception:
 Error: watch ENOENT
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at Gaze._watchDir (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /usr/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11

**Comment by tlancina** [comment]
Hey thanks for the issue, unfortunately I'm unable to reproduce this. Could you paste the output of `ionic info` please?  It also appears that the folder is named "Unbennanter Order", is it possible that something else went wrong?

**Comment by bgse** [comment]
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID:	Fedora Description:	Fedora release 21 (Twenty One) 
Node Version: v0.12.7

**Comment by bgse** [comment]
@tlancina The "Unbenannter Ordner" (-> 'unnamed folder') is due me creating the folder using Gnome-Files, which will initially create a folder with that name, and invoke the "rename"-command on it so you can name if whatever you like immediately.

**Comment by jgw96** [comment]
Hello @bgse Unforunately I am also unable to repro this on both osx El Capitan and Ubuntu 16.04. Is there anything else that i should do to repro?

**Comment by bgse** [comment]
@jgw96 Sorry, I don't have any more info on how to repro this. There seems to be no adverse effect apart from the exception message, so it appears to be not even an inconveniance but purely cosmetic.

I'll close this issue, and will reopen when I have something more useful.
