### ISSUE TITLE
Hook after_plugin_add doesn't execute in ionic state reset

### ISSUE THREAD

**Issue by leonardobazico** [driftyco/ionic-cli#929]
I expect execute hooks from after_plugin_add always I add a plugin.
ionic state reset remove and add plugins, but the hook after_plugin_add doesn't execute.

**Comment by jgw96** [comment]
Hello all! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!
