### ISSUE TITLE
When you make a single html change gulp reports that all html files have changed

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic-cli#932]
<img width="697" alt="screen shot 2016-04-14 at 10 55 43" src="https://cloud.githubusercontent.com/assets/1189149/14514897/cfb96a2a-022f-11e6-85e0-a3c229c79789.png">
Here's my ionic info:
<img width="746" alt="screen shot 2016-04-14 at 10 59 20" src="https://cloud.githubusercontent.com/assets/1189149/14514915/f99f3ef0-022f-11e6-912e-38132210c7bb.png">

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
