### ISSUE TITLE
Error - There was a problem while parsing the package in android + ionic2 + Angular2

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#941]
_From @kanchansingh1123 on April 16, 2016 12:29_

Hello,

I have created an fresh app by following http://ionicframework.com/docs/v2/getting-started/installation and generated an apk file using the following command -

1. ionic platform add android
2. ionic build --release android

While trying to install the APK in mobile it give the following error - 
**"there was a problem while parsing the package in android"**

I tried to test with 4.x, 5.x and 6.x Android version.

Is this known issue with Ionic2 + Angular2 ?

_Copied from original issue: driftyco/ionic#6191_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to the cli and not the framework i will be moving this issue to that repo. Thanks again!

**Comment by jgw96** [comment]
Hello @kanchansingh1123 are you still having this issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by demsey2** [comment]
Hi, I have got the same issue, if I run 
`ionic build android`  it works fine
`ionic build --release android` this one shows parse error

**Comment by ismaail** [comment]
@demsey2 try
```
ionic build android --release
```
