### ISSUE TITLE
Problem with adding crosswalk browser

### ISSUE THREAD

**Issue by lukasz-kaluzny** [driftyco/ionic-cli#944]
We tried to add crosswalk to our application and installed it by `ionic browser add crosswalk` command. `ionic browser list`gives results:

```
Available - Crosswalk - ionic browser add crosswalk
	 Version 8.37.189.14 Published
	 Version 9.38.208.10 Published
	 Version 10.39.235.15 Published
	 Version 11.40.277.7 Published
	 Version 12.41.296.5 Published
(beta)	 Version 13.42.319.6 Published
(canary) Version 14.42.334.0 Published

Available - Crosswalk-lite - ionic browser add crosswalk-lite
(canary) Version 10.39.234.1 Published
(canary) Version 10.39.236.1 Published

Available - Browser (default) - ionic browser revert android
```

We want to switch to Crosswalk as default browser for our applications, yet nothing helps, even after `ionic browser revert android` Available - Browser displays as default.

After deploying app on android phone nothing changes, crosswalk is disabled. Can you provide us with help in this matter?

**Comment by tlancina** [comment]
The browser command will be deprecated in 2.0 as it's no longer necessary, you should use the cordova crosswalk plugin: https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview.
