### ISSUE TITLE
ionic-cli doesn't recognize gulpfile.babel.js

### ISSUE THREAD

**Issue by Zorgatone** [driftyco/ionic-cli#945]
gulp has an option to detect and run a `gulpfile.babel.js` using BabelJS (ES6).

Can we have support for it in ionic-cli too? gulp does everything already (transpiling using babel), we may be able to use this

**Comment by Zorgatone** [comment]
When running `ionic serve` I get this error message:
```
WARN: No gulpfile found!
If your app requires a build step, you may want to ensure it runs before serve.
```

**Comment by jthoms1** [comment]
It appears that `gulpfile.babel.js` support was added in gulp v3.9.0. Currently ionic-cli is using version v3.8.8.  I believe that upgrading the gulp version should fix this issue. Any thoughts @tlancina?

**Comment by tlancina** [comment]
Not supported yet in the CLI, but I see no reason it can't be: https://github.com/driftyco/ionic-cli/blob/v2/lib/cli.js#L229-L230. 

As a workaround for now, can you use https://babeljs.io/docs/usage/require/ in an ES6 file named `gulpfile.js`?

**Comment by Zorgatone** [comment]
At the moment I was using the babel-cli to manually create the `gulpfile.js` file required for ionic.

But I guess your workaround is even better :)

**Comment by Zorgatone** [comment]
I closed by mistake, I think
