### ISSUE TITLE
ionic generate pipe inconsistent file name

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic-cli#951]
When generating a pipe with the following command:

`ionic g pipe MyPipe`

The resulting file created is `MyPipe.js`. For consistency with the other generators the generated file should be `my-pipe.js`.

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
