### ISSUE TITLE
Ionic 2 Apps not working Earlier than Android 5.0

### ISSUE THREAD

**Issue by felsf** [driftyco/ionic-cli#953]
A whitescreen is shown, tried on Andyroid Emulator and Galaxy Tab (both 4.2.2).
Some recommended to install Crosswalk, but that's not possible on Ionic v2.
It installs normally, but on build to android it shows this error.

`FelipeS@Felipe486 MINGW64 /c/xampp/htdocs/test (master)
$ ionic build android
WARN: ionic.config.js has been deprecated, you can remove it.

Running 'build:before' gulp task before build
[19:17:19] Starting 'clean'...
[19:17:19] Finished 'clean' after 49 ms
[19:17:19] Starting 'build'...
[19:17:19] Starting 'sass'...
[19:17:19] Starting 'html'...
[19:17:19] Starting 'fonts'...
[19:17:19] Starting 'scripts'...
[19:17:20] Finished 'scripts' after 382 ms
[19:17:20] Finished 'html' after 579 ms
[19:17:21] Finished 'fonts' after 1.31 s
[19:17:24] Finished 'sass' after 4.66 s
[19:17:47] Finished 'build' after 27 s
[19:17:47] Starting 'build:before'...
[19:17:47] Finished 'build:before' after 9.68 μs

Running command: "C:\Program Files\nodejs\node.exe" C:\xampp\htdocs\test\hooks\after_prepare\010_add_platform_class.js C:/xampp/htdocs/test
add to body class: platform-android
ANDROID_HOME=C:\Users\FelipeS\AppData\Local\Android\android-sdk
JAVA_HOME=C:\Program Files\java\jdk1.8.0_73
null
embedded
org.xwalk:xwalk_core_library:17+

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.android.support:support-v4:[13.0.0,).
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/maven-metadata.xml
         https://download.01.org/crosswalk/releases/crosswalk/android/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified > org.xwalk:xwalk_core_library:17.46.448.10

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.564 secs
ERROR building one of the platforms: Error code 1 for command: cmd with args: /s,/c,"C:\xampp\htdocs\test\platforms\android\gradlew cdvBuildDebug -b C:\xampp\htdocs\test\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
You may not have the required environment or OS to build this project
Error: Error code 1 for command: cmd with args: /s,/c,"C:\xampp\htdocs\test\platforms\android\gradlew cdvBuildDebug -b C:\xampp\htdocs\test\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"`

**Comment by iignatov** [comment]
@felsf You have to install [the required dependencies](http://stackoverflow.com/questions/33675491/could-not-resolve-all-dependencies-for-configuration-armv7debugcompile):

- Open the SDK manager _(from the command line, type `android`)_.
- Under **Extras**, download and install the following items:
  - Android Support Repository
  - Google Repository
  - Local Maven repository for Support Libraries

**Comment by jgw96** [comment]
Hello! Since it has been a while since there was any activity on this issue i will be closing it for now. @iignatov is correct that you most likely do not have the required deps. Thanks for using Ionic!

**Comment by jgw96** [comment]
Hello! Since it has been a while since there was any activity on this issue i will be closing it for now. @iignatov is correct that you most likely do not have the required deps. Thanks for using Ionic!
