### ISSUE TITLE
Ionic start app cannot find module 'utile'

### ISSUE THREAD

**Issue by bot101** [driftyco/ionic-cli#954]
I have searched all over the internet but seem to be the only one with this issue.
I tried installing Ionic today and after many tries and independent dependency installations, I finally installed it.
 Below is what I get anytime I run ionic start appi

NB: This command completely fails to work when I try in non-administrator mode, unlike other commands. 
Also, the result below was the same before I upgraded Node to a nightly build version.

PS C:\Users\Ikenna> ionic start appi

Error: Cannot find module 'utile'
    at Function.Module._resolveFilename (
    at Function.Module._load (module.js:3
    at Module.require (module.js:377:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Ikenn
3)
    at Module._compile (module.js:423:34)
    at Object.Module._extensions..js (mod
    at Module.load (module.js:367:32)
    at Function.Module._load (module.js:3
    at Module.require (module.js:377:17)

Cannot find module 'utile' (CLI v1.7.14)

Your system information:

Cordova CLI: 6.1.1
Gulp version: CLI version 3.9.1
Gulp local:
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS: Windows 7 SP1
Node Version: v6.0.0-nightly2016012500f8e63caff

**Comment by viniciustrindade** [comment]
`npm install -g utile` should solve it.

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
