### ISSUE TITLE
Ionic 2 - Bug after make login with Facebook native and go to a tab page

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#957]
_From @villander on April 24, 2016 12:32_

After  using with native Facebook i did:

```
loginWithFacebook() {
    this.platform.ready().then(() => {
      Facebook.login(["public_profile", "user_birthday"]).then(() => {
        this.nav.setRoot(TabsPage);
      }, (...args) => {
        console.log(args);
      });
    });
  }
```

Whatever page works, except of type `tabs`. I tried with `setRoot` and `push` but without success

_Copied from original issue: driftyco/ionic#6297_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! As this issue is more related to Ionic-Native and not the framework itself i will be moving this issue to over there. Thanks for using Ionic!

**Comment by jgw96** [comment]
Sorry, this should not have been moved here.

**Comment by OyebisiJemil** [comment]
hi guys, i think this might help  http://stackoverflow.com/questions/39036349/best-way-to-connect-ionic-2-nativ-facebook-with-firebase

**Comment by DuaneQ** [comment]
This still isn't working for me no matter where I put     this.navCtrl.setRoot(HomePage);

  facebookLogin() {
    this.facebook.login(['email', 'public_profile']).then(result=>{
      const credentials=firebase.auth.FacebookAuthProvider.credential(result.authResponse.accessToken);
      firebase.auth().signInWithCredential(credentials).then((success)=>{
            this.userProfile = success;
            this.firebaseLogin.setUpUser(credentials, success);
      })
    }).catch(err=>{
      alert(JSON.stringify(err))
    })
    
    this.navCtrl.setRoot(HomePage);
  }
