### ISSUE TITLE
--ts flag not working for tutorial template

### ISSUE THREAD

**Issue by samuba** [driftyco/ionic-cli#963]
CLI Version: 2.0.0-beta.25

Whenever I try to start a project with the tutorial template and the "--ts"-flag, I get the following error:

> ionic start tut tutorial --ts
> Creating Ionic app in folder E:\SourceCode\test\tut based on tutorial project
> Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
> [=============================]  100%  0.0s
> Downloading: https://github.com/driftyco/ionic-starter-tutorial/archive/master.zip
> Caught exception:
>  TypeError: Cannot read property 'bold' of undefined
>     at Request._callback (C:\Users\samue_000\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\utils.js:114:37)
>     at Request.self.callback (C:\Users\samue_000\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:373:22)
>     at emitTwo (events.js:100:13)
>     at Request.emit (events.js:185:7)
>     at Request.<anonymous> (C:\Users\samue_000\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1318:14)
>     at emitOne (events.js:95:20)
>     at Request.emit (events.js:182:7)
>     at IncomingMessage.<anonymous> (C:\Users\samue_000\AppData\Roaming\npm\node_modules\ionic\node_modules\request\request.js:1266:12)
>     at emitNone (events.js:85:20)
>     at IncomingMessage.emit (events.js:179:7)
> 
> Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Looks like the wrong archive is being pulled.

**Comment by tlancina** [comment]
Thanks, that is indeed a bug, but the command you want to be running is `ionic start tut tutorial --v2 --ts` (the `--v2` flag is missing), since tutorial isn't the name of an Ionic v1 starter.

**Comment by jgw96** [comment]
Hello all! I am going to close this as the default is now Typescript. Thanks for using Ionic!
