### ISSUE TITLE
Exception occurs on creating a folder and renaming it after running ionic serve

### ISSUE THREAD

**Issue by immnk** [driftyco/ionic-cli#971]
✗ Caught exception:
 Error: watch ENOENT
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1231:11)
    at Object.fs.watch (fs.js:1257:11)
    at Gaze._watchDir (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! I am having trouble reproducing this with the latest ionic@beta cli. Would you mind running `ionic info` from inside your project and posting the output here?

**Comment by immnk** [comment]
Your system information:


Cordova CLI: 5.3.1

Gulp version:  CLI version 3.9.1

Gulp local:

Ionic Version: 1.3.0

Ionic CLI Version: 2.0.0-beta.19

Ionic App Lib Version: 2.0.0-beta.9

ios-deploy version: Not installed

ios-sim version: Not installed

OS: Mac OS X El Capitan

Node Version: v4.0.0

Xcode version: Xcode 7.2.1 Build version 7C1002



Regards,
*Manikanta Tankala*

**Comment by jgw96** [comment]
Hello @immnk ! Would you mind updating your ionic-cli? It seems that you are running an older version as the latest version of the ionic beta cli is beta.25. To update on a mac you can simply run `npm install -g ionic@beta`. You may or may not need `sudo` depending on how you installed npm. Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
