### ISSUE TITLE
Option to to prevent ionic start cloning from the ionic-base repo

### ISSUE THREAD

**Issue by NoNameProvided** [driftyco/ionic-cli#974]
Now if the user runs `ionic start myProj https"//github.com/org/repo` then ionic-cli still clones the base project first. We should have some flag to prevent that. (I simply want to clone only my starter pack.)

**Comment by jthoms1** [comment]
This is core to the ionic process.  We appreciate the idea but will keep it working as intended because the the possible complexities it could introduce.  Thanks!
