### ISSUE TITLE
ionic resources breaks <config-file> block in config.xml

### ISSUE THREAD

**Issue by PhilHuot** [driftyco/ionic-cli#983]
`ionic resources` breaks the `<config-file>` block in the `config.xml` file.

See this example where `<key>anotherinsecurehttp.com</key>` is moved right next to `<key>insecurehttp.com</key>` which becomes invalid once it gets to the .plist file.

Before ionic resources

       <config-file parent="NSAppTransportSecurity" platform="ios" target="*-Info.plist">
            <key>NSAppTransportSecurity</key>
            <dict>
                <key>NSExceptionDomains</key>
                <dict>
                    <key>insecurehttp.com</key>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                    <key>anotherinsecurehttp.com</key>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                </dict>
            </dict>
        </config-file>

After ionic resources:

       <config-file parent="NSAppTransportSecurity" platform="ios" target="*-Info.plist">
            <key>NSAppTransportSecurity</key>
            <dict>
                <key>NSExceptionDomains</key>
                <dict>
                    <key>insecurehttp.com</key>
                    <key>anotherinsecurehttp.com</key>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                    <dict>
                        <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                        <true></true>
                    </dict>
                </dict>
            </dict>
        </config-file>

**Comment by herman1vdb** [comment]
ionic package build also breaks dictionary key value order. Please help it's I can't get a proper build:
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.1
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
OS:
Node Version: v0.12.9

**Comment by herman1vdb** [comment]
Hi

This is a ionic-app-lib issue, I just added it: https://github.com/driftyco/ionic-app-lib/issues/105

**with fix provided** :smile:

**Comment by PhilHuot** [comment]
Thanks a lot @herman1vdb
