### ISSUE TITLE
Ionic 1 does not run CLI commands such as `ionic info` or `ionic build ios`

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#987]
_From @shotbyabel on May 6, 2016 18:36_

#### Short description of the problem:

Not sure if me updating to Node 6 is causing all this.. but I am working on an Ionic 1 app with a remote team and lately our versions have not liked each other. I was wondering if the fact that I have also been working on Ionic 2 projects for whatever reason my CLI "thinks" these apps are also Ionic 2 and there for is shooting me the error below? (i know it makes no sense but I have no clue)

#### What behavior are you expecting?

I want to be able to run ionic commands like `ionic info` , `ionic build ios` etc.. and not get this error.. or message.. 

[issue in detail](http://stackoverflow.com/questions/37078620/ionic-1-app-does-not-build-ios-ionic-project-has-been-renamed-to-ionic-config)
```
insert any relevant code between the above and below backticks

mymac ~/code/92_AAC/newApp on master[!]
$ ionic build ios
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'gulp'

Do you need to run `npm install`?

```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
 

**Which Ionic Version?** 1.x or 2.x

#### Plunker that shows an example of your issue

**For Ionic 1 issues** - http://plnkr.co/edit/Xo1QyAUx35ny1Xf9ODHx?p=preview

**For Ionic 2 issues** - http://plnkr.co/edit/L8JN6w5mqwbMY2E14dbk?p=preview

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

_Copied from original issue: driftyco/ionic#6461_

**Comment by jgw96** [comment]
Hey! Thanks for opening an issue with us! Most likely, this is related to node 6, as those commands should work, and do work for me (im on node 5.10.1). Would you mind downgrading to node 5 and testing? Also, since this issue is an issue related to the cli and not the framework im going to move this issue over to the ionic-cli repo. Ill continue the conversation with you over there. Thanks!

**Comment by shotbyabel** [comment]
@jgw96  Thanks! I downgraded to Node 5.9 and I have some "progress"? Perhaps you can tell me if I am headed in the right direction..  After running `ionic build ios` I got a new message along with the original one.. 

```
$ ionic build ios
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
(node:11866) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'bower'

Do you need to run `npm install`?
```

**Comment by jgw96** [comment]
@shotbyabel No problem at all! So did you just `git clone` this project? If so then you should run `npm install` first.

**Comment by shotbyabel** [comment]
@jgw96 That's the thing.. I've never had to run npm install on this project before.. We have been working on this since February and I am just able to run commands all day with no issues this is all new.

**Comment by jgw96** [comment]
Hmm, can you check your project for a `node_modules` folder please? Are you all pushing your `node_modules` to github?

**Comment by shotbyabel** [comment]
`ionic info` now works again! So I wanted you to check my system info and the project ownsers too maybe I need to upgraded something else? 

**_(node modules are there! :)_** and unfortunately these guys use SVN 

MINE:

**Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v5.9.1
Xcode version: Xcode 7.3.1 Build version 7D1014 **

OWNERs:
Cordova CLI: 6.1.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.3
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Awesome is `ionic build ios` still giving an error? One thing that i would make sure of is that they are using npm 3 and not npm 2, you can see this with `npm --version`. We recommend using npm 3 as npm 2 has alot of what i would call "weirdness" haha.

**Comment by shotbyabel** [comment]
Still getting the error. I am really at lost at the moment lol. 
I am tempted to run npm install but.. last time I did that I think it brought back the old apps config files.. (i dont know how to explain it) what we named the apps for iOs.. 

```
$ ionic build ios
******************************************************
 Dependency warning - for the CLI to run correctly,      
 it is highly recommended to install/upgrade the following:     

 Install ios-sim to deploy iOS applications. `npm install -g ios-sim` (may require sudo)
 Install ios-deploy to deploy iOS applications to devices. `npm install -g ios-deploy` (may require sudo)

******************************************************
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
(node:12065) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'bower'

Do you need to run `npm install`?
```

**Comment by jgw96** [comment]
Hmm, so one thing you could try instead of running `npm install` is to just run `npm install bower` since that seems to be the module your missing.

**Comment by shotbyabel** [comment]
@jgw96 I tried that.. and it did "something"..  If you want.. take a look at my UPDATE 3 to see a photo and description of what happened after. (thanks for sticking around)

[issue update 3](http://stackoverflow.com/questions/37078620/ionic-1-app-does-not-build-ios-ionic-project-has-been-renamed-to-ionic-config)

**Comment by jgw96** [comment]
No problem! Hmm from what im seeing it looks like you may need to do a `git pull` .

**Comment by shotbyabel** [comment]
@jgw96 these guys use SVN.. I did `svn update` which is equivalent to `git pull` oh man.. what a mess lol

**Comment by jgw96** [comment]
Oh sorry. Hmmm im starting to think this isnt an ionic related issue anymore, but something wrong with your teams repo. Does `ionic serve` work?

**Comment by shotbyabel** [comment]
@jgw96 wow.. `ionic serve` does not.. it's the same issue.. with the `configionic.project has been renamed to ionic.config.json`

```
$ ionic serve
WARN: ionic.project has been renamed to ionic.config.json, please rename it.
(node:12200) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
There is an error in your gulpfile: 
Error: ENOENT: no such file or directory, scandir '/Users/abelista/code/inov/cornerstone/inov/a4c/passengerApp/trunk/passenger/node_modules/gulp-sass/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.getInstalledBinaries (/Users/abelista/code/inov/cornerstone/inov/a4c/passengerApp/trunk/passenger/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:74:13)
    at foundBinariesList (/Users/abelista/code/inov/cornerstone/inov/a4c/passengerApp/trunk/passenger/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/abelista/code/inov/cornerstone/inov/a4c/passengerApp/trunk/passenger/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/abelista/code/inov/cornerstone/inov/a4c/passengerApp/trunk/passenger/node_modules/gulp-sass/node_modules/node-sass/lib/errors.js:45:5)
    at Object.<anonymous> (/Users/abelista/code/inov/cornerstone/inov/a4c/passengerApp/trunk/passenger/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)

```

BTW.. all the ionic commands WORK on other ionic projects.  This repo is messed up! 💨

**Comment by jgw96** [comment]
Actually that renaming to ionic.config.json is just a warning, so thats not causing the error. So i just have a few questions:

1. I'm assuming this project is an Ionic 1 project correct? And not an ionic 2 project? 
2. If you make a fresh project with `ionic start` and then copy and paste your www from the app (if this is an ionic 1 project) in does it work? 
3. Is everything working for the other team? If so, i would recommend directly comparing your directory to there's and seeing whats different.

**Comment by shotbyabel** [comment]
@jgw96 thanks for narrowing it down. I appreciate you taking the time to look into this. I like your suggestions. Let me ask you this..  What file or directory is in direct conflict here? 

When this problem began 5 days ago it started because the remote team changed some code or info inside the platform directories..  At the time when I was pulling the code those directories were ignored.. now they are not and I am getting the whole code.. There was some conflicts that I thought I solved? but then again I guess not? I made this 3 min screen cast to show how my terminal looks.. (again if you have time and feel like checking this out.. )

Thanks! 
[screencast video](http://screencast.com/t/iLSfp5qb)

**Comment by jgw96** [comment]
Hello, since this seems to be an issue with your teams local setup and not an issue with ionic i will be closing this issue. Thanks for using Ionic!

**Comment by xkris6x** [comment]
someone help me have this problem

xkris6x@Server:/home/project/web/nodeJS/ionic/oea$ ionic serve
There is an error in your gulpfile: 
Error: /home/project/web/nodeJS/ionic/oea/node_modules/node-sass/vendor/linux-x64-47/binding.node: failed to map segment from shared object: Operation not permitted
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/project/web/nodeJS/ionic/oea/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

xkris6x@Server:/home/project/web/nodeJS/ionic/oea$ ionic start
Invalid command (CLI v2.0.0-beta.35)
Your system information:
Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
OS: Distributor ID:	Debian Description:	Debian GNU/Linux 8.5 (jessie) 
Node Version: v5.12.0

**Comment by kingkarki** [comment]
i have also having this issue after upgrading ionic 2 with ionic 1 project when i do ```ionic server```

```WARN: ionic.project has been renamed to ionic.config.json, please rename it.
Uh oh! Looks like you're missing a module in your gulpfile:
Cannot find module 'gulp'

Do you need to run `npm install`?```

**Comment by kishorekumaru** [comment]
+1
I am facing the same issue 
`WARN: ionic.project has been renamed to ionic.config.json, please rename it.`

**Comment by cozzbie** [comment]
+1 Same as @kishorekumaru and now gulp templateCache doesn't create new template.js files

**Comment by cozzbie** [comment]
Seems like the solution is here https://forum.ionicframework.com/t/ionic2-cli-doesnt-run-gulp-tasks-on-ionic-serve/49085/6

**Comment by BigKBear** [comment]
You can create a new ionic project and copy paste the www folder 
then using
ionic platform add android
ionic emulate android OR ionic run android
then once it builds and runs successfully then go back to the previous folder that you had problems with.
then do 
ionic emulate android OR ionic run android
It should work again.

**Comment by groknit** [comment]
Hey folks, I know you have discussed a ton of ways to fix the add iOS issue for an IONIC project but my easy button was simply running IONIC Lab and clicking "Install" next to IOS and Android. Boom. It corrected the permissions problems I was having.

**Comment by gparsloe** [comment]
Hi groknit. When I run $ionic serve --lab, it opens as expected in the browser, but I don't see any 'Install' next to IOS or Android. Would you please clarify what you mean by '...clicking "Install" next to IOS an Android?" Thanks.
