### ISSUE TITLE
"ionic state reset --plugins" fails

### ISSUE THREAD

**Issue by lhammond** [driftyco/ionic-cli#996]
$ ionic state reset --plugins
Removed platforms and plugins
Attempting to restore your Ionic application from package.json

Restoring Plugins

cordova plugin add org.apache.cordova.device
cordova plugin add org.apache.cordova.console
cordova plugin add com.ionic.keyboard
Caught exception:
 undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.0.0-rc.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: 4.1.1
OS: Mac OS X El Capitan
Node Version: v5.0.0
Xcode version: Xcode 7.3 Build version 7D175

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us. We are currently in the process of deprecating the `ionic state` commands in favor of doing it the cordova way. https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html You can keep up with the status of this on #904 . Thanks for using Ionic!

**Comment by amcastror** [comment]
Hi @jgw96, which is the "cordova way"? I'm stuck with the same issue but when adding the cordova-plugin-device plugin.

Thanks!

**Comment by DharmendraVaishnav91** [comment]
Facing the same issue showing caught exception got undefined.

**Comment by fikkatra** [comment]
As ionic state swallows the exception, I tried debugging by running the command separately:
`> cordova plugin add cordova-plugin-device`

This showed me an EACCES error. Running
`> ionic hooks add`

solved the issue for me, and running `ionic state restore `works fine now.

**Comment by Dbl0207** [comment]
![screen shot 2017-11-21 at 5 54 52 pm](https://user-images.githubusercontent.com/22885198/33072350-293eabe0-cee5-11e7-89d8-8f2080b28dd3.png)


Im running a icymobi from CLI, but when restoring Cordova plugins, its running for 4 hours. Still not end. Can you advice me what could be the solution?
