### ISSUE TITLE
Suggestion: Generated providers

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-cli#997]
Currently when you generate a provider using the ionic@beta cli you get a provider that has `http` imported and injected and a simple promise based http request. I would suggest that our generated providers should instead use an observable based template based off of something like this: 

```
import { Injectable }     from 'angular2/core';
import { Http, Response } from 'angular2/http';
import { Observable }     from 'rxjs/Observable';


@Injectable()
export class DataService {
  constructor (private http: Http) {}

  getData (): Observable<any[]> {
    return this.http.get(/*api endpoint*/)
                    .map(this.extractData)
                    .catch(this.handleError);
  }

  private extractData(res: Response) {
    if (res.status < 200 || res.status >= 300) {
      throw new Error('Bad response status: ' + res.status);
    }
    let body = res.json();
    return body.data || { };
  }

  private handleError (error: any) {
    // In a real world app, we might send the error to remote logging infrastructure
    let errMsg = error.message || 'Server error';
    console.error(errMsg); // log to console instead
    return Observable.throw(errMsg);
  }
}
```

This would put it more in line with what i think is considered "standard" for Angular 2 and I think gives a better starting point for devs to build their provider off of. Would love to hear what anyone else thinks of this! Is something like this too complicated for just a simple generated provider?

**Comment by jthoms1** [comment]
Thanks for opening the issue. It seems that issue has been resolved. I am going to close this issue but please feel free to reopen another issue if this occurs again.
