### ISSUE TITLE
Update README to remove gulpStartupTasks

### ISSUE THREAD

**Issue by dually8** [driftyco/ionic-cli#999]
I use sass and typescript in my ionic projects and I've noticed that when I run `ionic serve`, the things that used to execute in `gulpStartupTasks` no longer execute.  I assume this might be deprecated (at least in the beta CLI), but the README still mentions to use `gulpStartupTasks` in order to run things before a serve occurs.  For anyone like me that is experiencing the same thing, you must add a new gulp.task to your gulpfile. I've replaced

```
{
  "name": "app",
  "app_id": "",
  "gulpStartupTasks": [
    "sass",
    "tsc",
    "watch"
  ],
  "watchPatterns": [
    "www/**/*",
    "!www/lib/**/*"
  ]
}
```

with `gulp.task('serve:before', ['sass', 'tsc', 'watch']);` in my `gulpfile.js`.  Below is my ionic info:

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.0-nightly-3203
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v4.4.4
Xcode version: Xcode 7.3.1 Build version 7D1014 
```

EDIT: I should mention I'm using v1 ionic and the beta CLI.

**Comment by getqd** [comment]
Thank you for adding the `gulp.task('serve:before', ['sass', 'tsc', 'watch']);`. 

The official Ionic CLI 2.0 release needs this to "build" the project before serve.

**Comment by ericongkc** [comment]
finally.

**Comment by Syldel** [comment]
Thank you very much @getqd ! It works for me ! ;-)
